// Findings → GitHub issues. Idempotent (a fingerprint marker in each body means
// a re-run never opens a duplicate). Every specific, actionable defect gets its
// OWN closeable ticket — P0/P1 always, and P2/P3 for the concrete-defect
// checkers (factual errors, wrong/junk images). Only genuinely bulk-advisory
// checkers (image.host-reputation: "this host is unvetted, eyeball it") roll up
// into a single tracking issue, so 194 non-defects don't drown the tracker.
// The engine only PROPOSES — an issue is a fix-it ticket, never a content change.
import { writeFileSync, unlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { rank, fingerprint } from './finding.mjs';
import { CONFIG } from '../config.mjs';
// Shared gh runner: CLI when present, GitHub REST when it isn't. This module
// used to shell out to `gh` directly, which is why Karen's 2026-07-26 nightly
// completed a clean 1096-item scan and then threw away all 623 filable
// findings with `spawn gh ENOENT`. See scripts/lib/gh.mjs and issue #528.
import { gh } from '../../lib/gh.mjs';

const PFX = CONFIG.output.issueLabelPrefix;

// Rollup vs individual is decided by SOURCE, not checker: deterministic P2/P3
// findings are mechanical/bulk (size-based image.quality, host-reputation,
// claim-risk) and roll up into one tracking issue per checker; agent findings
// are specific verified judgments (a wrong fact, a collage, an off-era photo)
// and each files as its own actionable ticket. P0/P1 always file individually.

const LABELS = [
  [`${PFX}`, '5319e7', 'Content Integrity Engine finding'],
  [`${PFX}:P0`, 'b60205', 'CIE P0 — credibility/safety/legal'],
  [`${PFX}:P1`, 'd93f0b', 'CIE P1 — major integrity gap'],
  [`${PFX}:P2`, 'fbca04', 'CIE P2 — improvement'],
  [`${PFX}:P3`, '0e8a16', 'CIE P3 — polish'],
  [`${PFX}:safety`, '000000', 'CIE safety/red-line finding'],
  [`${PFX}:escalate`, 'b60205', 'CIE — human review required now'],
  [`${PFX}:image`, '1d76db', 'CIE image finding (quality/relevance/safety)'],
  [`${PFX}:fact`, 'c2e0c6', 'CIE factual finding'],
];

export async function ensureLabels() {
  for (const [name, color, desc] of LABELS) {
    try {
      await gh(['label', 'create', name, '--color', color, '--description', desc, '--force']);
    } catch {
      /* label may already exist / --force covers it; ignore */
    }
  }
}

async function existsByFp(fp) {
  try {
    const { stdout } = await gh(['issue', 'list', '--state', 'all', '--search', `cie-fp:${fp} in:body`, '--json', 'number', '--limit', '1']);
    return JSON.parse(stdout || '[]').length > 0;
  } catch {
    return false;
  }
}

function bodyFor(f, fp) {
  const src = f.sources?.length ? `\n**Sources consulted:** ${f.sources.map((s) => `<${s}>`).join(' · ')}\n` : '';
  return [
    f.escalate ? '> ⚠️ **ESCALATION — human review required before anything else.**\n' : '',
    `**Checker:** \`${f.checker}\` · **Severity:** ${f.severity} · **Confidence:** ${f.confidence.toFixed(2)}${f.confidence < 0.5 ? ' _(review, not a confirmed defect)_' : ''}`,
    '',
    `**Where:** \`${f.itemRef.file ?? '?'}\`${f.itemRef.key ? ` · \`${f.itemRef.key}\`` : ''}${f.itemRef.field ? ` · field \`${f.itemRef.field}\`` : ''} (${f.itemRef.type})`,
    '',
    '**At issue:**',
    '```',
    f.excerpt || '(n/a)',
    '```',
    '',
    `**What the check found:** ${f.evidence}`,
    '',
    `**Suggested fix:** ${f.suggestedFix || '(see evidence)'}`,
    src,
    '',
    '---',
    '_Generated by the Content Integrity Engine (read-only; this is a proposed fix, not an applied change)._',
    `<!-- cie-fp:${fp} -->`,
  ].join('\n');
}

async function createIssue({ title, body, labels }, dryRun) {
  if (dryRun) return { dryRun: true, title };
  // Body goes through a temp file (--body-file), never argv: a rolled-up issue
  // body can exceed the OS command-line length limit (ENAMETOOLONG on Windows).
  const bodyPath = join(tmpdir(), `cie-issue-${Date.now()}-${Math.random().toString(36).slice(2)}.md`);
  writeFileSync(bodyPath, body, 'utf8');
  try {
    const args = ['issue', 'create', '--title', title, '--body-file', bodyPath];
    for (const l of labels) args.push('--label', l);
    const { stdout } = await gh(args);
    return { url: stdout.trim() };
  } finally {
    try { unlinkSync(bodyPath); } catch { /* best-effort cleanup */ }
  }
}

/**
 * Create issues from findings. Findings below `minConfidence` are treated as
 * agent-routing signals (verify-this), not filable defects, and are skipped —
 * this is what keeps the tracker actionable instead of drowning in low-signal
 * "verify" flags that the agent factual pass will adjudicate anyway.
 */
export async function createIssues(findings, { dryRun = true, limit = Infinity, minConfidence = 0.5 } = {}) {
  const ranked = rank(findings.filter((f) => f.confidence >= minConfidence || f.escalate));
  const created = [];
  const skipped = [];
  let count = 0;

  // 1) Individual issues — all P0/P1, plus every agent-sourced P2/P3 (a specific
    //  verified defect). One closeable ticket each.
  const individual = ranked.filter((f) =>
    f.severity === 'P0' || f.severity === 'P1' || f.source !== 'deterministic');
  for (const f of individual) {
    if (count >= limit) break;
    const fp = fingerprint(f);
    if (!dryRun && (await existsByFp(fp))) { skipped.push(fp); continue; }
    const labels = [PFX, `${PFX}:${f.severity}`];
    if (f.checker.startsWith('safety.')) labels.push(`${PFX}:safety`);
    if (f.checker.startsWith('image.')) labels.push(`${PFX}:image`);
    if (f.checker.startsWith('fact.')) labels.push(`${PFX}:fact`);
    if (f.escalate) labels.push(`${PFX}:escalate`);
    const title = `[CIE ${f.severity}] ${f.title}`;
    const r = await createIssue({ title, body: bodyFor(f, fp), labels }, dryRun);
    created.push({ ...r, severity: f.severity });
    count++;
  }

  // 2) Rollups — deterministic P2/P3 only: one tracking issue per checker.
  const lower = ranked.filter((f) =>
    (f.severity === 'P2' || f.severity === 'P3') && f.source === 'deterministic');
  const byChecker = new Map();
  for (const f of lower) {
    if (!byChecker.has(f.checker)) byChecker.set(f.checker, []);
    byChecker.get(f.checker).push(f);
  }
  for (const [checker, fs] of byChecker) {
    if (count >= limit) break;
    const fp = fingerprint({ checker, itemRef: { key: 'rollup' }, excerpt: `${fs.length}` });
    if (!dryRun && (await existsByFp(fp))) { skipped.push(fp); continue; }
    const worst = fs.some((f) => f.severity === 'P2') ? 'P2' : 'P3';
    const title = `[CIE ${worst}] ${checker}: ${fs.length} items to review`;
    // GitHub caps issue bodies at 65536 chars. Build a compact one-line-per-item
    // checklist and stop before the cap — the full per-item detail lives in the
    // committed run report + merged.json, so the issue is a pointer, not a dump.
    const BODY_CAP = 60000;
    const header = [
      `**Checker:** \`${checker}\` · ${fs.length} instances (rolled up to keep the tracker clean).`,
      '',
      '_Full per-item detail (evidence, suggested fix, sources) is in the committed run report under `docs/audits/engine/`._',
      '',
    ];
    const footer = ['', '---', '_Generated by the Content Integrity Engine (read-only)._', `<!-- cie-fp:${fp} -->`];
    const budget = BODY_CAP - header.join('\n').length - footer.join('\n').length - 40;
    const itemLines = [];
    let used = 0;
    let shown = 0;
    for (const f of fs) {
      const line = `- [ ] \`${f.itemRef.file ?? '?'}\`${f.itemRef.key ? ` · ${f.itemRef.key}` : ''} — ${f.title}`;
      if (used + line.length + 1 > budget) break;
      itemLines.push(line);
      used += line.length + 1;
      shown++;
    }
    if (shown < fs.length) itemLines.push(`\n…and ${fs.length - shown} more (see the run report for the full list).`);
    const r = await createIssue({ title, body: [...header, ...itemLines, ...footer].join('\n'), labels: [PFX, `${PFX}:${worst}`] }, dryRun);
    created.push({ ...r, severity: worst, rollup: fs.length });
    count++;
  }

  return { created, skipped: skipped.length, dryRun };
}
