// Findings → GitHub issues. Idempotent (a fingerprint marker in each body means
// a re-run never opens a duplicate). To avoid issue spam: P0/P1 get individual
// issues (they need action); P2/P3 roll up into ONE issue per checker with an
// instance list. The engine only PROPOSES — an issue is a fix-it ticket, never
// a content change.
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { rank, fingerprint } from './finding.mjs';
import { CONFIG } from '../config.mjs';

const exec = promisify(execFile);
const PFX = CONFIG.output.issueLabelPrefix;

async function gh(args, opts = {}) {
  return exec('gh', args, { maxBuffer: 1024 * 1024 * 16, ...opts });
}

const LABELS = [
  [`${PFX}`, '5319e7', 'Content Integrity Engine finding'],
  [`${PFX}:P0`, 'b60205', 'CIE P0 — credibility/safety/legal'],
  [`${PFX}:P1`, 'd93f0b', 'CIE P1 — major integrity gap'],
  [`${PFX}:P2`, 'fbca04', 'CIE P2 — improvement'],
  [`${PFX}:P3`, '0e8a16', 'CIE P3 — polish'],
  [`${PFX}:safety`, '000000', 'CIE safety/red-line finding'],
  [`${PFX}:escalate`, 'b60205', 'CIE — human review required now'],
];

export async function ensureLabels() {
  for (const [name, color, desc] of LABELS) {
    try {
      await gh(['label', 'create', name, '--color', color, '--description', desc, '--force']);
    } catch {
      /* label may already exist / --force covers it; ignore */
    }
  }
}

async function existsByFp(fp) {
  try {
    const { stdout } = await gh(['issue', 'list', '--state', 'all', '--search', `cie-fp:${fp} in:body`, '--json', 'number', '--limit', '1']);
    return JSON.parse(stdout || '[]').length > 0;
  } catch {
    return false;
  }
}

function bodyFor(f, fp) {
  const src = f.sources?.length ? `\n**Sources consulted:** ${f.sources.map((s) => `<${s}>`).join(' · ')}\n` : '';
  return [
    f.escalate ? '> ⚠️ **ESCALATION — human review required before anything else.**\n' : '',
    `**Checker:** \`${f.checker}\` · **Severity:** ${f.severity} · **Confidence:** ${f.confidence.toFixed(2)}${f.confidence < 0.5 ? ' _(review, not a confirmed defect)_' : ''}`,
    '',
    `**Where:** \`${f.itemRef.file ?? '?'}\`${f.itemRef.key ? ` · \`${f.itemRef.key}\`` : ''}${f.itemRef.field ? ` · field \`${f.itemRef.field}\`` : ''} (${f.itemRef.type})`,
    '',
    '**At issue:**',
    '```',
    f.excerpt || '(n/a)',
    '```',
    '',
    `**What the check found:** ${f.evidence}`,
    '',
    `**Suggested fix:** ${f.suggestedFix || '(see evidence)'}`,
    src,
    '',
    '---',
    '_Generated by the Content Integrity Engine (read-only; this is a proposed fix, not an applied change)._',
    `<!-- cie-fp:${fp} -->`,
  ].join('\n');
}

async function createIssue({ title, body, labels }, dryRun) {
  if (dryRun) return { dryRun: true, title };
  const args = ['issue', 'create', '--title', title, '--body', body];
  for (const l of labels) args.push('--label', l);
  const { stdout } = await gh(args);
  return { url: stdout.trim() };
}

/**
 * Create issues from findings. Findings below `minConfidence` are treated as
 * agent-routing signals (verify-this), not filable defects, and are skipped —
 * this is what keeps the tracker actionable instead of drowning in low-signal
 * "verify" flags that the agent factual pass will adjudicate anyway.
 */
export async function createIssues(findings, { dryRun = true, limit = Infinity, minConfidence = 0.5 } = {}) {
  const ranked = rank(findings.filter((f) => f.confidence >= minConfidence || f.escalate));
  const created = [];
  const skipped = [];
  let count = 0;

  // 1) P0/P1 — individual issues.
  for (const f of ranked.filter((f) => f.severity === 'P0' || f.severity === 'P1')) {
    if (count >= limit) break;
    const fp = fingerprint(f);
    if (!dryRun && (await existsByFp(fp))) { skipped.push(fp); continue; }
    const labels = [PFX, `${PFX}:${f.severity}`];
    if (f.checker.startsWith('safety.')) labels.push(`${PFX}:safety`);
    if (f.escalate) labels.push(`${PFX}:escalate`);
    const title = `[CIE ${f.severity}] ${f.title}`;
    const r = await createIssue({ title, body: bodyFor(f, fp), labels }, dryRun);
    created.push({ ...r, severity: f.severity });
    count++;
  }

  // 2) P2/P3 — one rollup issue per checker (instances listed inside).
  const lower = ranked.filter((f) => f.severity === 'P2' || f.severity === 'P3');
  const byChecker = new Map();
  for (const f of lower) {
    if (!byChecker.has(f.checker)) byChecker.set(f.checker, []);
    byChecker.get(f.checker).push(f);
  }
  for (const [checker, fs] of byChecker) {
    if (count >= limit) break;
    const fp = fingerprint({ checker, itemRef: { key: 'rollup' }, excerpt: `${fs.length}` });
    if (!dryRun && (await existsByFp(fp))) { skipped.push(fp); continue; }
    const worst = fs.some((f) => f.severity === 'P2') ? 'P2' : 'P3';
    const title = `[CIE ${worst}] ${checker}: ${fs.length} items to review`;
    const lines = [
      `**Checker:** \`${checker}\` · ${fs.length} instances (rolled up to keep the tracker clean).`,
      '',
      ...fs.slice(0, 200).map((f) => `- [ ] \`${f.itemRef.file ?? '?'}\`${f.itemRef.key ? ` · ${f.itemRef.key}` : ''} — ${f.title}${f.evidence ? `\n      ↳ ${f.evidence.slice(0, 200)}` : ''}`),
      fs.length > 200 ? `\n…and ${fs.length - 200} more.` : '',
      '',
      '---',
      '_Generated by the Content Integrity Engine (read-only)._',
      `<!-- cie-fp:${fp} -->`,
    ];
    const r = await createIssue({ title, body: lines.join('\n'), labels: [PFX, `${PFX}:${worst}`] }, dryRun);
    created.push({ ...r, severity: worst, rollup: fs.length });
    count++;
  }

  return { created, skipped: skipped.length, dryRun };
}
