import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  buildCoverage,
  formatCoverage,
  generateCoverage,
  parseCoverage,
} from './affiliate-coverage.mjs';

const products = [
  {
    item: 'Awin dress',
    retailer: 'awin.example',
    url: 'https://awin.example/dress',
    category: 'shop-the-look' as const,
    source: { eraId: 'lover', momentId: 'm-1' },
  },
  {
    item: 'Amazon vinyl',
    retailer: 'amazon.com',
    url: 'https://www.amazon.com/vinyl',
    category: 'shop-the-look' as const,
    source: { eraId: 'red', momentId: 'm-2' },
  },
  {
    item: 'Unmapped top',
    retailer: 'direct.example',
    url: 'https://direct.example/top',
    category: 'shop-the-look' as const,
    source: { eraId: '1989', momentId: 'm-3' },
  },
  {
    item: 'Official item',
    retailer: 'store.taylorswift.com',
    url: 'https://store.taylorswift.com/item',
    category: 'official-store' as const,
  },
  {
    item: 'Catch-all bag',
    retailer: 'catchall.example',
    url: 'https://catchall.example/bag',
    category: 'fan-made' as const,
  },
];

const resolveNetwork = (retailer: string) =>
  retailer === 'awin.example'
    ? { network: 'awin' as const, awinmid: '123' }
    : retailer === 'amazon.com'
    ? { network: 'amazon' as const }
    : retailer === 'catchall.example'
      ? { network: 'catchall' as const }
    : { network: 'none' as const };

describe('affiliate coverage', () => {
  it('classifies every product with an auditable status and link format', () => {
    const report = buildCoverage(products, {
      resolveNetwork,
      credentials: { awin: true, amazon: false, catchall: true },
      awinApplyRetailers: new Set(['direct.example']),
    });

    expect(report.rows.map((row) => [row.item, row.network, row.status, row.linkFormat])).toEqual([
      ['Amazon vinyl', 'amazon', 'pending-signup', 'amazon tag + ascsubtag'],
      ['Awin dress', 'awin', 'wrapped', 'awin cread.php + clickref'],
      ['Catch-all bag', 'catchall', 'wrapped', 'catchall redirect + xcust'],
      ['Official item', 'none', 'direct-by-policy', 'direct retailer URL'],
      ['Unmapped top', 'none', 'awin-apply', 'direct retailer URL'],
    ]);
    expect(report.summary).toEqual({
      total: 5,
      wrapped: 2,
      'awin-apply': 1,
      'pending-signup': 1,
      uncovered: 0,
      'direct-by-policy': 1,
    });
  });

  it('marks a non-network product uncovered rather than implying a programme', () => {
    const report = buildCoverage(products.slice(2, 3), { resolveNetwork });
    expect(report.rows[0].status).toBe('uncovered');
  });

  it('renders a deterministic generated document that round-trips its report', () => {
    const report = buildCoverage(products, { resolveNetwork, credentials: { awin: true, amazon: true } });
    const rendered = formatCoverage(report);
    expect(rendered).toContain('<!-- GENERATED by scripts/merch-engine/affiliate-coverage.mjs; DO NOT EDIT. -->');
    expect(parseCoverage(rendered)).toEqual(report);
  });

  it('loads E0 directory entries into generated awin-apply rows', () => {
    const directoryPath = join(mkdtempSync(join(tmpdir(), 'affiliate-coverage-')), 'awin-advertiser-directory.json');
    writeFileSync(
      directoryPath,
      JSON.stringify({
        source: 'E0 Awin Publisher API cross-reference',
        generatedAt: '2026-08-30T00:00:00.000Z',
        advertisers: [{ retailer: 'direct.example' }],
      }),
    );

    const rendered = generateCoverage(products, { resolveNetwork, directoryPath });

    expect(parseCoverage(rendered).rows.find((row) => row.retailer === 'direct.example')?.status).toBe('awin-apply');
    expect(parseCoverage(rendered).summary['awin-apply']).toBe(1);
  });

  it('keeps coverage output independent of public affiliate credentials', () => {
    const original = {
      awin: process.env.NEXT_PUBLIC_AWIN_ID,
      amazon: process.env.NEXT_PUBLIC_AMAZON_ASSOCIATES_TAG,
      catchall: process.env.NEXT_PUBLIC_CATCHALL_ID,
    };
    const withoutCredentials = generateCoverage(products, { resolveNetwork });
    process.env.NEXT_PUBLIC_AWIN_ID = 'test-awin';
    process.env.NEXT_PUBLIC_AMAZON_ASSOCIATES_TAG = 'test-amazon';
    process.env.NEXT_PUBLIC_CATCHALL_ID = 'test-catchall';

    try {
      expect(generateCoverage(products, { resolveNetwork })).toBe(withoutCredentials);
      expect(parseCoverage(withoutCredentials).summary['awin-apply']).toBe(0);
    } finally {
      for (const [key, value] of Object.entries({
        NEXT_PUBLIC_AWIN_ID: original.awin,
        NEXT_PUBLIC_AMAZON_ASSOCIATES_TAG: original.amazon,
        NEXT_PUBLIC_CATCHALL_ID: original.catchall,
      })) {
        if (value === undefined) delete process.env[key];
        else process.env[key] = value;
      }
    }
  });
});
