// Notifications Phase 4 (NOTIFICATIONS_PLAN.md, NOTIFICATIONS_SPEC.md §4
// "Fun categories" / `lyric_of_day`) — STARTER lyric pool.
//
// ****************************************************************
// * DRAFT — FOUNDER REVIEW REQUIRED BEFORE ANY REAL DEVICE SEES   *
// * THIS CONTENT. Do not treat as final production content.       *
// ****************************************************************
//
// What this is: one short (typically <=12-word), single-line excerpt per
// released Taylor Swift track across all 12 eras currently in this repo's
// track catalogue (supabase/seed/tracks/**), generated from the model's
// general knowledge of Taylor Swift's discography as a STARTER DRAFT for
// Joey to review, correct, and approve — per this task's explicit
// instruction ("generate a starter list for founder review rather than
// finalizing it yourself... keep the list clearly marked as a draft").
//
// ACCURACY CAVEAT (read before using any row): these lines were written
// from training-data familiarity with Taylor Swift's catalogue, NOT
// copy-pasted from a licensed lyrics database or verified against an
// official source line-by-line. Deep-catalogue/vault-track lines are
// materially more likely to contain a misquote (wrong word, wrong line
// grouping) than the marquee singles. A `verified` flag is included below
// per entry, defaulting to false, so the sync script and any future
// production-content checker can gate on "founder actually checked this
// line" rather than silently trusting an unreviewed guess. FLIP TO true
// ONLY after a human confirms the line against the actual released lyric.
//
// LEGAL CAVEAT: recorded founder decision (2026-08-31, NOTIFICATIONS_
// PLAN.md Phase 4 task body) — short-excerpt lyric content may proceed for
// now ("legal position: proceed, revisit if it becomes a problem"). This
// does not need to be re-litigated per NOTIFICATIONS_SPEC.md §12 Q3.
//
// SCHEMA: matches `lyrics` (song, album, lyric) — see
// supabase/migrations/20260913000000_notifications_fun.sql. `times_used`
// is not seeded here; it's a runtime counter the sync script initializes
// to 0.
//
// Deep-link convention: notification-deep-links.ts resolves lyric_of_day
// sends to the song's track-guide page — this file supplies `slug` (the
// TrackNote slug from supabase/seed/tracks/**) alongside `song`/`album` so
// the sync script can build that link without a second lookup, matching
// products.ts's `retailer` field precedent of storing everything a
// consumer needs on the row itself.

export const LYRIC_STARTER_POOL = [
  // ---- Taylor Swift (2006) ----
  {
    slug: 'tim-mcgraw',
    song: 'Tim McGraw',
    album: 'Taylor Swift',
    lyric: 'When you think Tim McGraw, I hope you think of me',
    verified: false,
  },
  {
    slug: 'picture-to-burn',
    song: 'Picture to Burn',
    album: 'Taylor Swift',
    lyric: "State the obvious, I didn't get my perfect fantasy",
    verified: false,
  },
  {
    slug: 'teardrops-on-my-guitar',
    song: 'Teardrops on My Guitar',
    album: 'Taylor Swift',
    lyric: 'Drew looks at me, I fake a smile so he won\u2019t see',
    verified: false,
  },
  {
    slug: 'a-place-in-this-world',
    song: 'A Place in This World',
    album: 'Taylor Swift',
    lyric: "I don't know what I want, so don't ask me",
    verified: false,
  },
  {
    slug: 'cold-as-you',
    song: 'Cold as You',
    album: 'Taylor Swift',
    lyric: 'You have a way of coming easily to me',
    verified: false,
  },
  {
    slug: 'the-outside',
    song: 'The Outside',
    album: 'Taylor Swift',
    lyric: "I've been a lot of lonely places",
    verified: false,
  },
  {
    slug: 'tied-together-with-a-smile',
    song: 'Tied Together with a Smile',
    album: 'Taylor Swift',
    lyric: "You're tied together with a smile but you're coming undone",
    verified: false,
  },
  {
    slug: 'stay-beautiful',
    song: 'Stay Beautiful',
    album: 'Taylor Swift',
    lyric: 'Cory\u2019s eyes are like a jungle',
    verified: false,
  },
  {
    slug: 'our-song',
    song: 'Our Song',
    album: 'Taylor Swift',
    lyric: 'I was riding shotgun with my hair undone',
    verified: false,
  },
  {
    slug: 'invisible',
    song: 'Invisible',
    album: 'Taylor Swift',
    lyric: "She can't see the way your eyes light up when you smile",
    verified: false,
  },
  {
    slug: 'a-perfectly-good-heart',
    song: 'A Perfectly Good Heart',
    album: 'Taylor Swift',
    lyric: 'Why would you wanna break a perfectly good heart?',
    verified: false,
  },

  // ---- Fearless (2008) ----
  {
    slug: 'fearless',
    song: 'Fearless',
    album: 'Fearless',
    lyric: 'And I don\u2019t know how it gets better than this',
    verified: false,
  },
  {
    slug: 'fifteen',
    song: 'Fifteen',
    album: 'Fearless',
    lyric: 'Take a deep breath girl, before you go',
    verified: false,
  },
  {
    slug: 'love-story',
    song: 'Love Story',
    album: 'Fearless',
    lyric: 'Romeo, take me somewhere we can be alone',
    verified: false,
  },
  {
    slug: 'hey-stephen',
    song: 'Hey Stephen',
    album: 'Fearless',
    lyric: 'Hey Stephen, I know looks can be deceiving',
    verified: false,
  },
  {
    slug: 'white-horse',
    song: 'White Horse',
    album: 'Fearless',
    lyric: "I'm not a princess, this ain't a fairytale",
    verified: false,
  },
  {
    slug: 'you-belong-with-me',
    song: 'You Belong with Me',
    album: 'Fearless',
    lyric: "If you could see that I'm the one who understands you",
    verified: false,
  },
  {
    slug: 'breathe',
    song: 'Breathe',
    album: 'Fearless',
    lyric: "It's 2 AM and I'm cursing your name",
    verified: false,
  },
  {
    slug: 'tell-me-why',
    song: 'Tell Me Why',
    album: 'Fearless',
    lyric: "I'm sick and tired of your attitude",
    verified: false,
  },
  {
    slug: 'the-way-i-loved-you',
    song: 'The Way I Loved You',
    album: 'Fearless',
    lyric: 'I miss screaming and fighting and kissing in the rain',
    verified: false,
  },
  {
    slug: 'forever-and-always',
    song: 'Forever & Always',
    album: 'Fearless',
    lyric: 'Was I out of line? Did I say something way too honest?',
    verified: false,
  },
  {
    slug: 'the-best-day',
    song: 'The Best Day',
    album: 'Fearless',
    lyric: "I'm thirteen now and don't know how my friends could be so mean",
    verified: false,
  },
  {
    slug: 'change',
    song: 'Change',
    album: 'Fearless',
    lyric: 'This is a state of grace, this is the worthwhile fight',
    verified: false,
  },
  {
    slug: 'jump-then-fall',
    song: 'Jump Then Fall',
    album: 'Fearless',
    lyric: 'You said, jump, then fall',
    verified: false,
  },
  {
    slug: 'untouchable',
    song: 'Untouchable',
    album: 'Fearless',
    lyric: 'You\u2019re like a criminal, ain\u2019t stole nothing but my heart',
    verified: false,
  },
  {
    slug: 'come-in-with-the-rain',
    song: 'Come In with the Rain',
    album: 'Fearless',
    lyric: "So come in with the rain, don't you go",
    verified: false,
  },
  {
    slug: 'superstar',
    song: 'Superstar',
    album: 'Fearless',
    lyric: 'You are flawless, ain\u2019t that the world\u2019s greatest lie',
    verified: false,
  },
  {
    slug: 'the-other-side-of-the-door',
    song: 'The Other Side of the Door',
    album: 'Fearless',
    lyric: "I didn't mean it when I said I didn't love you so",
    verified: false,
  },
  {
    slug: 'today-was-a-fairytale',
    song: 'Today Was a Fairytale',
    album: 'Fearless',
    lyric: 'Today was a fairytale, you were the prince',
    verified: false,
  },
  {
    slug: 'you-all-over-me',
    song: 'You All Over Me',
    album: 'Fearless',
    lyric: "I get drunk and make believe that you're in the seat",
    verified: false,
  },
  {
    slug: 'mr-perfectly-fine',
    song: 'Mr. Perfectly Fine',
    album: 'Fearless',
    lyric: 'Mr. Perfectly fine, how\u2019s your heart after breaking mine?',
    verified: false,
  },
  {
    slug: 'we-were-happy',
    song: 'We Were Happy',
    album: 'Fearless',
    lyric: 'You said if we lived in the ‘60s I\u2019d be your Baby Blue',
    verified: false,
  },
  {
    slug: 'bye-bye-baby',
    song: 'Bye Bye Baby',
    album: 'Fearless',
    lyric: 'It was you and me and this rollercoaster ride',
    verified: false,
  },

  // ---- Speak Now (2010) ----
  {
    slug: 'mine',
    song: 'Mine',
    album: 'Speak Now',
    lyric: 'You were in college working part-time waiting tables',
    verified: false,
  },
  {
    slug: 'sparks-fly',
    song: 'Sparks Fly',
    album: 'Speak Now',
    lyric: 'I run my fingers through your hair and watch the sparks fly',
    verified: false,
  },
  {
    slug: 'back-to-december',
    song: 'Back to December',
    album: 'Speak Now',
    lyric: 'I go back to December all the time',
    verified: false,
  },
  {
    slug: 'speak-now',
    song: 'Speak Now',
    album: 'Speak Now',
    lyric: 'I hear the preacher say, speak now or forever hold your peace',
    verified: false,
  },
  {
    slug: 'dear-john',
    song: 'Dear John',
    album: 'Speak Now',
    lyric: 'Dear John, I see it all now that you\u2019re gone',
    verified: false,
  },
  {
    slug: 'mean',
    song: 'Mean',
    album: 'Speak Now',
    lyric: "Someday I'll be big enough so you can't hit me",
    verified: false,
  },
  {
    slug: 'the-story-of-us',
    song: 'The Story of Us',
    album: 'Speak Now',
    lyric: 'Next chapter, how does the story go?',
    verified: false,
  },
  {
    slug: 'never-grow-up',
    song: 'Never Grow Up',
    album: 'Speak Now',
    lyric: "Oh darling, don't you ever grow up",
    verified: false,
  },
  {
    slug: 'enchanted',
    song: 'Enchanted',
    album: 'Speak Now',
    lyric: 'This night is sparkling, don\u2019t you let it go',
    verified: false,
  },
  {
    slug: 'better-than-revenge',
    song: 'Better Than Revenge',
    album: 'Speak Now',
    lyric: "She's not a saint and she's not what you think",
    verified: false,
  },
  {
    slug: 'innocent',
    song: 'Innocent',
    album: 'Speak Now',
    lyric: "It's alright, just wait and see",
    verified: false,
  },
  {
    slug: 'haunted',
    song: 'Haunted',
    album: 'Speak Now',
    lyric: 'You and I walk a fragile line',
    verified: false,
  },
  {
    slug: 'last-kiss',
    song: 'Last Kiss',
    album: 'Speak Now',
    lyric: 'I still remember the look on your face',
    verified: false,
  },
  {
    slug: 'long-live',
    song: 'Long Live',
    album: 'Speak Now',
    lyric: 'Long live all the mountains we moved',
    verified: false,
  },
  {
    slug: 'ours',
    song: 'Ours',
    album: 'Speak Now',
    lyric: 'People throw rocks at things that shine',
    verified: false,
  },
  {
    slug: 'if-this-was-a-movie',
    song: 'If This Was a Movie',
    album: 'Speak Now',
    lyric: 'If this was a movie, you\u2019d be here by now',
    verified: false,
  },
  {
    slug: 'superman',
    song: 'Superman',
    album: 'Speak Now',
    lyric: 'He\u2019s not faster than a train, not stronger than a plane',
    verified: false,
  },
  {
    slug: 'electric-touch',
    song: 'Electric Touch',
    album: 'Speak Now',
    lyric: 'This could be a bad idea, but I\u2019m in it',
    verified: false,
  },
  {
    slug: 'when-emma-falls-in-love',
    song: 'When Emma Falls in Love',
    album: 'Speak Now',
    lyric: 'When Emma falls in love, she paces the floor',
    verified: false,
  },
  {
    slug: 'i-can-see-you',
    song: 'I Can See You',
    album: 'Speak Now',
    lyric: 'I can see you up against the wall with me',
    verified: false,
  },
  {
    slug: 'castles-crumbling',
    song: 'Castles Crumbling',
    album: 'Speak Now',
    lyric: 'The stones I hurled are now a wall around me',
    verified: false,
  },
  {
    slug: 'foolish-one',
    song: 'Foolish One',
    album: 'Speak Now',
    lyric: "You're on to the next, before I know it",
    verified: false,
  },
  {
    slug: 'timeless',
    song: 'Timeless',
    album: 'Speak Now',
    lyric: 'We found love in a photograph, ninety years gone',
    verified: false,
  },

  // ---- Red (2012) ----
  {
    slug: 'state-of-grace',
    song: 'State of Grace',
    album: 'Red',
    lyric: 'This is a state of grace, this is the worthwhile fight',
    verified: false,
  },
  { slug: 'red', song: 'Red', album: 'Red', lyric: 'Loving him was red', verified: false },
  {
    slug: 'treacherous',
    song: 'Treacherous',
    album: 'Red',
    lyric: 'This slope is treacherous, this path is reckless',
    verified: false,
  },
  {
    slug: 'i-knew-you-were-trouble',
    song: 'I Knew You Were Trouble',
    album: 'Red',
    lyric: 'I knew you were trouble when you walked in',
    verified: false,
  },
  {
    slug: 'all-too-well',
    song: 'All Too Well',
    album: 'Red',
    lyric: 'I remember it all too well',
    verified: false,
  },
  {
    slug: '22',
    song: '22',
    album: 'Red',
    lyric: "We're happy, free, confused, and lonely at the same time",
    verified: false,
  },
  {
    slug: 'i-almost-do',
    song: 'I Almost Do',
    album: 'Red',
    lyric: 'I bet this time of night you\u2019re still up',
    verified: false,
  },
  {
    slug: 'we-are-never-ever-getting-back-together',
    song: 'We Are Never Ever Getting Back Together',
    album: 'Red',
    lyric: 'We are never, ever, ever getting back together',
    verified: false,
  },
  {
    slug: 'stay-stay-stay',
    song: 'Stay Stay Stay',
    album: 'Red',
    lyric: "I'm pretty sure we almost broke up last night",
    verified: false,
  },
  {
    slug: 'the-last-time',
    song: 'The Last Time',
    album: 'Red',
    lyric: "This is the last time I'm asking you why",
    verified: false,
  },
  {
    slug: 'holy-ground',
    song: 'Holy Ground',
    album: 'Red',
    lyric: 'Tonight I\u2019m gonna dance for all that we\u2019ve been through',
    verified: false,
  },
  {
    slug: 'sad-beautiful-tragic',
    song: 'Sad Beautiful Tragic',
    album: 'Red',
    lyric: 'Sad, beautiful, tragic, that\u2019s what we are',
    verified: false,
  },
  {
    slug: 'the-lucky-one',
    song: 'The Lucky One',
    album: 'Red',
    lyric: 'They tell you that you\u2019re lucky, but you\u2019re so confused',
    verified: false,
  },
  {
    slug: 'everything-has-changed',
    song: 'Everything Has Changed',
    album: 'Red',
    lyric: 'All I know since yesterday is everything has changed',
    verified: false,
  },
  {
    slug: 'starlight',
    song: 'Starlight',
    album: 'Red',
    lyric: 'Cause baby I could build a castle out of all the bricks they threw at me',
    verified: false,
  },
  {
    slug: 'begin-again',
    song: 'Begin Again',
    album: 'Red',
    lyric: 'Wait, oh, I remember this, I know it well',
    verified: false,
  },
  {
    slug: 'the-moment-i-knew',
    song: 'The Moment I Knew',
    album: 'Red',
    lyric: 'Happy birthday to me, no it\u2019s not what I thought it would be',
    verified: false,
  },
  {
    slug: 'come-back-be-here',
    song: 'Come Back... Be Here',
    album: 'Red',
    lyric: 'It\u2019s two AM and I\u2019m cursed',
    verified: false,
  },
  {
    slug: 'girl-at-home',
    song: 'Girl at Home',
    album: 'Red',
    lyric: "I hear you're better now, that's good",
    verified: false,
  },
  {
    slug: 'ronan',
    song: 'Ronan',
    album: 'Red',
    lyric: 'Ronan, you were s\u2019posed to be, held in my arms',
    verified: false,
  },
  {
    slug: 'better-man',
    song: 'Better Man',
    album: 'Red',
    lyric: "I know I've got a big imagination",
    verified: false,
  },
  {
    slug: 'nothing-new',
    song: 'Nothing New',
    album: 'Red',
    lyric: 'How can a person know everything at eighteen',
    verified: false,
  },
  {
    slug: 'babe',
    song: 'Babe',
    album: 'Red',
    lyric: 'You already know, so I don\u2019t know why I tell you',
    verified: false,
  },
  {
    slug: 'message-in-a-bottle',
    song: 'Message in a Bottle',
    album: 'Red',
    lyric: "I'm sending out a message in a bottle",
    verified: false,
  },
  {
    slug: 'i-bet-you-think-about-me',
    song: 'I Bet You Think About Me',
    album: 'Red',
    lyric: 'I bet you think about me when you say, oh, she\u2019s insane',
    verified: false,
  },
  {
    slug: 'forever-winter',
    song: 'Forever Winter',
    album: 'Red',
    lyric: 'You don\u2019t know that I know you cry',
    verified: false,
  },
  {
    slug: 'run',
    song: 'Run',
    album: 'Red',
    lyric: "Run, baby, run, don't look back",
    verified: false,
  },
  {
    slug: 'the-very-first-night',
    song: 'The Very First Night',
    album: 'Red',
    lyric: 'Reminds me all of my youth',
    verified: false,
  },
  {
    slug: 'all-too-well-10-minute-version',
    song: 'All Too Well (10 Minute Version)',
    album: 'Red',
    lyric: 'And you call me up again just to break me like a promise',
    verified: false,
  },

  // ---- 1989 (2014) ----
  {
    slug: 'welcome-to-new-york',
    song: 'Welcome to New York',
    album: '1989',
    lyric: 'Welcome to New York, it\u2019s been waiting for you',
    verified: false,
  },
  {
    slug: 'blank-space',
    song: 'Blank Space',
    album: '1989',
    lyric: 'Got a long list of ex-lovers',
    verified: false,
  },
  {
    slug: 'style',
    song: 'Style',
    album: '1989',
    lyric: 'Take me home, just take me home',
    verified: false,
  },
  {
    slug: 'out-of-the-woods',
    song: 'Out of the Woods',
    album: '1989',
    lyric: 'Are we out of the woods yet?',
    verified: false,
  },
  {
    slug: 'all-you-had-to-do-was-stay',
    song: 'All You Had to Do Was Stay',
    album: '1989',
    lyric: 'All you had to do was stay',
    verified: false,
  },
  {
    slug: 'shake-it-off',
    song: 'Shake It Off',
    album: '1989',
    lyric: 'Cause the players gonna play, play, play, and the haters gonna hate, hate, hate',
    verified: false,
  },
  {
    slug: 'i-wish-you-would',
    song: 'I Wish You Would',
    album: '1989',
    lyric: 'I wish you would come back, come back',
    verified: false,
  },
  {
    slug: 'bad-blood',
    song: 'Bad Blood',
    album: '1989',
    lyric: "Cause baby, now we've got bad blood",
    verified: false,
  },
  {
    slug: 'wildest-dreams',
    song: 'Wildest Dreams',
    album: '1989',
    lyric: 'Say you\u2019ll remember me, standing in a nice dress',
    verified: false,
  },
  {
    slug: 'how-you-get-the-girl',
    song: 'How You Get the Girl',
    album: '1989',
    lyric: 'Say you\u2019ll remember, standing in a nice dress',
    verified: false,
  },
  {
    slug: 'this-love',
    song: 'This Love',
    album: '1989',
    lyric: 'This love is good, this love is bad',
    verified: false,
  },
  {
    slug: 'i-know-places',
    song: 'I Know Places',
    album: '1989',
    lyric: 'I know places we won\u2019t be found',
    verified: false,
  },
  {
    slug: 'clean',
    song: 'Clean',
    album: '1989',
    lyric: 'The drought was the very worst, when the flowers that we grew, wilted',
    verified: false,
  },
  {
    slug: 'wonderland',
    song: 'Wonderland',
    album: '1989',
    lyric: 'We found wonderland, you and I got lost in it',
    verified: false,
  },
  {
    slug: 'you-are-in-love',
    song: 'You Are in Love',
    album: '1989',
    lyric: 'One night he wakes, strange look on his face',
    verified: false,
  },
  {
    slug: 'new-romantics',
    song: 'New Romantics',
    album: '1989',
    lyric: 'Heartbreak is the national anthem, we sing it proudly',
    verified: false,
  },
  {
    slug: 'slut',
    song: '"Slut!"',
    album: '1989 (Taylor\u2019s Version)',
    lyric: "But if I'm all dressed up, they might as well be looking at us",
    verified: false,
  },
  {
    slug: 'suburban-legends',
    song: 'Suburban Legends',
    album: '1989 (Taylor\u2019s Version)',
    lyric: 'We were born to be the pawns in a lover\u2019s game',
    verified: false,
  },
  {
    slug: 'is-it-over-now',
    song: 'Is It Over Now?',
    album: '1989 (Taylor\u2019s Version)',
    lyric: 'Once the flight had flown, wreckage strewn across the ground',
    verified: false,
  },

  // ---- reputation (2017) ----
  {
    slug: 'ready-for-it',
    song: '...Ready for It?',
    album: 'reputation',
    lyric: 'In the middle of the night, in my dreams, you should see the things we do',
    verified: false,
  },
  {
    slug: 'end-game',
    song: 'End Game',
    album: 'reputation',
    lyric: 'I wanna be your end game',
    verified: false,
  },
  {
    slug: 'i-did-something-bad',
    song: 'I Did Something Bad',
    album: 'reputation',
    lyric: 'I never trust a narcissist, but they love me',
    verified: false,
  },
  {
    slug: 'delicate',
    song: 'Delicate',
    album: 'reputation',
    lyric: 'Is it cool that I said all that?',
    verified: false,
  },
  {
    slug: 'look-what-you-made-me-do',
    song: 'Look What You Made Me Do',
    album: 'reputation',
    lyric: "I'm sorry, the old Taylor can't come to the phone right now",
    verified: false,
  },
  {
    slug: 'so-it-goes',
    song: 'So It Goes...',
    album: 'reputation',
    lyric: 'Trust issues, like you, but you know I\u2019d never leave',
    verified: false,
  },
  {
    slug: 'gorgeous',
    song: 'Gorgeous',
    album: 'reputation',
    lyric: "You're so gorgeous, I can't say anything to your face",
    verified: false,
  },
  {
    slug: 'getaway-car',
    song: 'Getaway Car',
    album: 'reputation',
    lyric: 'I was riding in a getaway car',
    verified: false,
  },
  {
    slug: 'king-of-my-heart',
    song: 'King of My Heart',
    album: 'reputation',
    lyric: 'All the boys and their expensive cars',
    verified: false,
  },
  {
    slug: 'dancing-with-our-hands-tied',
    song: 'Dancing with Our Hands Tied',
    album: 'reputation',
    lyric: 'We were dancing with our hands tied',
    verified: false,
  },
  {
    slug: 'dress',
    song: 'Dress',
    album: 'reputation',
    lyric: 'Only bought this dress so you could take it off',
    verified: false,
  },
  {
    slug: 'call-it-what-you-want',
    song: 'Call It What You Want',
    album: 'reputation',
    lyric: 'My castle crumbled overnight, I brought a knife to a gunfight',
    verified: false,
  },

  // ---- Lover (2019) ----
  {
    slug: 'i-forgot-that-you-existed',
    song: 'I Forgot That You Existed',
    album: 'Lover',
    lyric: 'I forgot that you existed, it isn\u2019t hate, it\u2019s just indifference',
    verified: false,
  },
  {
    slug: 'cruel-summer',
    song: 'Cruel Summer',
    album: 'Lover',
    lyric: 'And I snuck in through the garden gate',
    verified: false,
  },
  {
    slug: 'lover',
    song: 'Lover',
    album: 'Lover',
    lyric: 'Can I go where you go? Can we always be this close?',
    verified: false,
  },
  {
    slug: 'the-man',
    song: 'The Man',
    album: 'Lover',
    lyric: 'I' + "'" + 'd be a fearless leader, I\u2019d be an alpha type',
    verified: false,
  },
  {
    slug: 'the-archer',
    song: 'The Archer',
    album: 'Lover',
    lyric: "I've been the archer, I've been the prey",
    verified: false,
  },
  {
    slug: 'i-think-he-knows',
    song: 'I Think He Knows',
    album: 'Lover',
    lyric: 'I planned it, but do you know that I planned it?',
    verified: false,
  },
  {
    slug: 'miss-americana-and-the-heartbreak-prince',
    song: 'Miss Americana & the Heartbreak Prince',
    album: 'Lover',
    lyric: "It's you and me, that's my whole world",
    verified: false,
  },
  {
    slug: 'paper-rings',
    song: 'Paper Rings',
    album: 'Lover',
    lyric: "I like shiny things, but I'd marry you with paper rings",
    verified: false,
  },
  {
    slug: 'cornelia-street',
    song: 'Cornelia Street',
    album: 'Lover',
    lyric: 'I rent a place on Cornelia Street',
    verified: false,
  },
  {
    slug: 'death-by-a-thousand-cuts',
    song: 'Death by a Thousand Cuts',
    album: 'Lover',
    lyric:
      'My heart, my hips, my body, my love, trying to find a part of me that you didn\u2019t touch',
    verified: false,
  },
  {
    slug: 'london-boy',
    song: 'London Boy',
    album: 'Lover',
    lyric: 'I fancy you, would you fancy me?',
    verified: false,
  },
  {
    slug: 'false-god',
    song: 'False God',
    album: 'Lover',
    lyric: 'Religion\u2019s in your lips, even if it\u2019s a false god',
    verified: false,
  },
  {
    slug: 'you-need-to-calm-down',
    song: 'You Need to Calm Down',
    album: 'Lover',
    lyric: "You need to calm down, you're being too loud",
    verified: false,
  },
  {
    slug: 'afterglow',
    song: 'Afterglow',
    album: 'Lover',
    lyric: 'It\u2019s so excruciating to see you low',
    verified: false,
  },
  {
    slug: 'me',
    song: 'Me!',
    album: 'Lover',
    lyric: 'I promise that you\u2019ll never find another like me',
    verified: false,
  },
  {
    slug: 'daylight',
    song: 'Daylight',
    album: 'Lover',
    lyric: 'I once believed love would be, burning red',
    verified: false,
  },

  // ---- folklore (2020) ----
  {
    slug: 'the-1',
    song: 'the 1',
    album: 'folklore',
    lyric: 'I' + "'" + 'm doing good, I\u2019m on some new shit',
    verified: false,
  },
  {
    slug: 'cardigan',
    song: 'cardigan',
    album: 'folklore',
    lyric: 'And when I felt like I was an old cardigan under someone\u2019s bed',
    verified: false,
  },
  {
    slug: 'the-last-great-american-dynasty',
    song: 'the last great american dynasty',
    album: 'folklore',
    lyric: 'Rebekah rode up on the afternoon train, it was sunny',
    verified: false,
  },
  {
    slug: 'exile',
    song: 'exile',
    album: 'folklore',
    lyric: 'I can see you standing, honey, with his arms around your body',
    verified: false,
  },
  {
    slug: 'my-tears-ricochet',
    song: 'my tears ricochet',
    album: 'folklore',
    lyric: 'We gather stones, never knowing what they\u2019ll mean',
    verified: false,
  },
  {
    slug: 'mirrorball',
    song: 'mirrorball',
    album: 'folklore',
    lyric: "I'm a mirrorball, I'll show you every version of yourself",
    verified: false,
  },
  {
    slug: 'seven',
    song: 'seven',
    album: 'folklore',
    lyric: 'Please picture me in the trees, I hit my peak at seven',
    verified: false,
  },
  {
    slug: 'august',
    song: 'august',
    album: 'folklore',
    lyric: 'Salt air and the rust on your door, I never needed anything more',
    verified: false,
  },
  {
    slug: 'this-is-me-trying',
    song: 'this is me trying',
    album: 'folklore',
    lyric: "I've been having a hard time adjusting",
    verified: false,
  },
  {
    slug: 'illicit-affairs',
    song: 'illicit affairs',
    album: 'folklore',
    lyric: 'Make sure nobody sees you leave',
    verified: false,
  },
  {
    slug: 'invisible-string',
    song: 'invisible string',
    album: 'folklore',
    lyric: 'Time, curious time, gave me no compasses, no signs',
    verified: false,
  },
  {
    slug: 'mad-woman',
    song: 'mad woman',
    album: 'folklore',
    lyric: 'Every time you call me crazy, I get more crazy',
    verified: false,
  },
  {
    slug: 'epiphany',
    song: 'epiphany',
    album: 'folklore',
    lyric: 'Something med school did not cover, someone\u2019s daughter, someone\u2019s mother',
    verified: false,
  },
  {
    slug: 'betty',
    song: 'betty',
    album: 'folklore',
    lyric: "Betty, I won't make assumptions about why you switched your homeroom",
    verified: false,
  },
  {
    slug: 'peace',
    song: 'peace',
    album: 'folklore',
    lyric: "Our coming of age has come and gone, suddenly this summer, it's clear",
    verified: false,
  },
  {
    slug: 'hoax',
    song: 'hoax',
    album: 'folklore',
    lyric: 'My only one, my smoking gun, my eclipsed sun',
    verified: false,
  },
  {
    slug: 'the-lakes',
    song: 'the lakes',
    album: 'folklore',
    lyric: 'Is it romantic how all my elegies eulogize me?',
    verified: false,
  },

  // ---- evermore (2020) ----
  {
    slug: 'willow',
    song: 'willow',
    album: 'evermore',
    lyric: 'I' + "'" + 'm like the water when your ship rolled in that night',
    verified: false,
  },
  {
    slug: 'champagne-problems',
    song: 'champagne problems',
    album: 'evermore',
    lyric: "She would've made such a lovely bride, what a shame she's fucked in the head",
    verified: false,
  },
  {
    slug: 'gold-rush',
    song: 'gold rush',
    album: 'evermore',
    lyric: "My mind turns your life into folklore, I can't dare to dream about you",
    verified: false,
  },
  {
    slug: 'tolerate-it',
    song: 'tolerate it',
    album: 'evermore',
    lyric: 'I sit and watch you reading with your head low',
    verified: false,
  },
  {
    slug: 'no-body-no-crime',
    song: 'no body, no crime',
    album: 'evermore',
    lyric: "Este's a friend of mine, we meet up every Tuesday night",
    verified: false,
  },
  {
    slug: 'happiness',
    song: 'happiness',
    album: 'evermore',
    lyric: 'Honey, when I decided I loved you',
    verified: false,
  },
  {
    slug: 'dorothea',
    song: 'dorothea',
    album: 'evermore',
    lyric: 'Dorothea, do you ever stop and think about me?',
    verified: false,
  },
  {
    slug: 'coney-island',
    song: 'coney island',
    album: 'evermore',
    lyric: "Break my soul in two looking for you, but you're right there",
    verified: false,
  },
  {
    slug: 'ivy',
    song: 'ivy',
    album: 'evermore',
    lyric: "How's one to know? I'd meet you where the spirit meets the bones",
    verified: false,
  },
  {
    slug: 'cowboy-like-me',
    song: 'cowboy like me',
    album: 'evermore',
    lyric: 'And the skeletons in both our closets plotted hard to fuck this up',
    verified: false,
  },
  {
    slug: 'long-story-short',
    song: 'long story short',
    album: 'evermore',
    lyric: 'Long story short, I survived',
    verified: false,
  },
  {
    slug: 'marjorie',
    song: 'marjorie',
    album: 'evermore',
    lyric: 'Never be so kind, you forget to be clever',
    verified: false,
  },
  {
    slug: 'closure',
    song: 'closure',
    album: 'evermore',
    lyric: "Yes, I got your letter, yes, I'm doing better",
    verified: false,
  },
  {
    slug: 'evermore',
    song: 'evermore',
    album: 'evermore',
    lyric: 'Gray November, I\u2019ve been down since July',
    verified: false,
  },
  {
    slug: 'right-where-you-left-me',
    song: 'right where you left me',
    album: 'evermore',
    lyric: "I'm right where you left me",
    verified: false,
  },

  // ---- Midnights (2022) ----
  {
    slug: 'lavender-haze',
    song: 'Lavender Haze',
    album: 'Midnights',
    lyric: "I've been under scrutiny, you handle it beautifully",
    verified: false,
  },
  {
    slug: 'maroon',
    song: 'Maroon',
    album: 'Midnights',
    lyric: 'The rust that grew between telephones',
    verified: false,
  },
  {
    slug: 'anti-hero',
    song: 'Anti-Hero',
    album: 'Midnights',
    lyric: "It's me, hi, I'm the problem, it's me",
    verified: false,
  },
  {
    slug: 'snow-on-the-beach',
    song: 'Snow on the Beach',
    album: 'Midnights',
    lyric: 'One night a few moons ago, I saw flecks of what could be glitter',
    verified: false,
  },
  {
    slug: 'midnight-rain',
    song: 'Midnight Rain',
    album: 'Midnights',
    lyric: 'He wanted a bride, I was making my own name',
    verified: false,
  },
  {
    slug: 'question',
    song: 'Question...?',
    album: 'Midnights',
    lyric: 'I remember, I remember, remember it all too well',
    verified: false,
  },
  {
    slug: 'vigilante-shit',
    song: 'Vigilante Shit',
    album: 'Midnights',
    lyric: "I don't dress for women, I don't dress for men",
    verified: false,
  },
  {
    slug: 'bejeweled',
    song: 'Bejeweled',
    album: 'Midnights',
    lyric: 'Best believe I\u2019m still bejeweled, when I walk in the room',
    verified: false,
  },
  {
    slug: 'labyrinth',
    song: 'Labyrinth',
    album: 'Midnights',
    lyric: 'Uh-oh, I' + "'" + 'm falling in love again',
    verified: false,
  },
  {
    slug: 'karma',
    song: 'Karma',
    album: 'Midnights',
    lyric: 'Karma is my boyfriend, karma is a god',
    verified: false,
  },
  {
    slug: 'sweet-nothing',
    song: 'Sweet Nothing',
    album: 'Midnights',
    lyric: 'On the way home, I wrote a poem',
    verified: false,
  },
  {
    slug: 'mastermind',
    song: 'Mastermind',
    album: 'Midnights',
    lyric: "What if I told you I'm a mastermind?",
    verified: false,
  },
  {
    slug: 'the-great-war',
    song: 'The Great War',
    album: 'Midnights',
    lyric: 'My knuckles were bruised like violets',
    verified: false,
  },
  {
    slug: 'bigger-than-the-whole-sky',
    song: 'Bigger Than the Whole Sky',
    album: 'Midnights',
    lyric: 'Goodbye, goodbye, goodbye',
    verified: false,
  },
  {
    slug: 'paris',
    song: 'Paris',
    album: 'Midnights',
    lyric: "You could be my jackpot, but you'd have to be your own" + ' bodyguard',
    verified: false,
  },
  {
    slug: 'high-infidelity',
    song: 'High Infidelity',
    album: 'Midnights',
    lyric: 'You know there\u2019s many different ways that you can kill the one you love',
    verified: false,
  },
  {
    slug: 'glitch',
    song: 'Glitch',
    album: 'Midnights',
    lyric: "This isn't supposed to happen to us",
    verified: false,
  },
  {
    slug: 'dear-reader',
    song: 'Dear Reader',
    album: 'Midnights',
    lyric: "Dear reader, if it feels like a trap, you're already in one",
    verified: false,
  },
  {
    slug: 'hits-different',
    song: 'Hits Different',
    album: 'Midnights',
    lyric: 'And I was supposed to be sad, but I just feel angry',
    verified: false,
  },

  // ---- THE TORTURED POETS DEPARTMENT (2024) ----
  {
    slug: 'fortnight',
    song: 'Fortnight',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'I love you, it\u2019s ruining my life',
    verified: false,
  },
  {
    slug: 'the-tortured-poets-department',
    song: 'The Tortured Poets Department',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'You smoked, then ate seven bars of chocolate',
    verified: false,
  },
  {
    slug: 'my-boy-only-breaks-his-favorite-toys',
    song: 'My Boy Only Breaks His Favorite Toys',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'My boy only breaks his favorite toys',
    verified: false,
  },
  {
    slug: 'down-bad',
    song: 'Down Bad',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'Did you really beam me up in a cloud of sparkling dust?',
    verified: false,
  },
  {
    slug: 'so-long-london',
    song: 'So Long, London',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: "So long, London, you'll find someone",
    verified: false,
  },
  {
    slug: 'but-daddy-i-love-him',
    song: 'But Daddy I Love Him',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'I' + "'" + 'm having his baby, no I\u2019m not, but you should see your faces',
    verified: false,
  },
  {
    slug: 'fresh-out-the-slammer',
    song: 'Fresh Out the Slammer',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: "Fresh out the slammer, I know who I'm going to call",
    verified: false,
  },
  {
    slug: 'florida',
    song: 'Florida!!!',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'Florida is one hell of a drug',
    verified: false,
  },
  {
    slug: 'guilty-as-sin',
    song: 'Guilty as Sin?',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'Am I allowed to cry?',
    verified: false,
  },
  {
    slug: 'i-can-fix-him-no-really-i-can',
    song: 'I Can Fix Him (No Really I Can)',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'I can fix him, no really I can',
    verified: false,
  },
  {
    slug: 'loml',
    song: 'loml',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: "You said I'm the love of your life about a hundred times",
    verified: false,
  },
  {
    slug: 'i-can-do-it-with-a-broken-heart',
    song: 'I Can Do It with a Broken Heart',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: "I'm so depressed I act like it's my birthday every day",
    verified: false,
  },
  {
    slug: 'the-smallest-man-who-ever-lived',
    song: 'The Smallest Man Who Ever Lived',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'You said normal girls were boring, but you were gonna change',
    verified: false,
  },
  {
    slug: 'the-alchemy',
    song: 'The Alchemy',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'This is the golden age of something good and glorious and free',
    verified: false,
  },
  {
    slug: 'clara-bow',
    song: 'Clara Bow',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'You look like Clara Bow in this light',
    verified: false,
  },
  {
    slug: 'the-black-dog',
    song: 'The Black Dog',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'I hate you, but not like I used to',
    verified: false,
  },
  {
    slug: 'imgonnagetyouback',
    song: 'imgonnagetyouback',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: "I'm gonna get you back",
    verified: false,
  },
  {
    slug: 'the-albatross',
    song: 'The Albatross',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'Here comes the albatross, I circled above',
    verified: false,
  },
  {
    slug: 'chloe-or-sam-or-sophia-or-marcus',
    song: 'Chloe or Sam or Sophia or Marcus',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: "You'll find someone, but it won't be me",
    verified: false,
  },
  {
    slug: 'how-did-it-end',
    song: 'How Did It End?',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: "How did it end? They don't know",
    verified: false,
  },
  {
    slug: 'so-high-school',
    song: 'So High School',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'You know how to ball, I know Aristotle',
    verified: false,
  },
  {
    slug: 'i-hate-it-here',
    song: 'I Hate It Here',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'I hate it here so I will go to secret gardens in my mind',
    verified: false,
  },
  {
    slug: 'thank-you-aimee',
    song: 'thanK you aIMee',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric:
      'I don\u2019t think you did it maliciously, though I do like a story where a girl gets even',
    verified: false,
  },
  {
    slug: 'the-prophecy',
    song: 'The Prophecy',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'I got cursed like Eve got bitten',
    verified: false,
  },
  {
    slug: 'cassandra',
    song: 'Cassandra',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'Do you believe me now?',
    verified: false,
  },
  {
    slug: 'peter',
    song: 'Peter',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'Peter, losing your baby blues',
    verified: false,
  },
  {
    slug: 'the-bolter',
    song: 'The Bolter',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'She was a runaway bride, straight out the aisle',
    verified: false,
  },
  {
    slug: 'robin',
    song: 'Robin',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'You can\u2019t spell brother without r-o-b',
    verified: false,
  },
  {
    slug: 'the-manuscript',
    song: 'The Manuscript',
    album: 'THE TORTURED POETS DEPARTMENT',
    lyric: 'And now the reader s\u2019overcome, the story isn\u2019t mine anymore',
    verified: false,
  },

  // ---- The Life of a Showgirl (2025) ----
  {
    slug: 'the-fate-of-ophelia',
    song: 'The Fate of Ophelia',
    album: 'The Life of a Showgirl',
    lyric: 'You saved me from the fate of Ophelia',
    verified: false,
  },
  {
    slug: 'elizabeth-taylor',
    song: 'Elizabeth Taylor',
    album: 'The Life of a Showgirl',
    lyric: "I'm the eighth-time lucky girl",
    verified: false,
  },
  {
    slug: 'opalite',
    song: 'Opalite',
    album: 'The Life of a Showgirl',
    lyric: 'The sky was always more than just an ombre',
    verified: false,
  },
  {
    slug: 'father-figure',
    song: 'Father Figure',
    album: 'The Life of a Showgirl',
    lyric: "I'll take care of you",
    verified: false,
  },
  {
    slug: 'eldest-daughter',
    song: 'Eldest Daughter',
    album: 'The Life of a Showgirl',
    lyric: "I'm not who I used to be",
    verified: false,
  },
  {
    slug: 'ruin-the-friendship',
    song: 'Ruin the Friendship',
    album: 'The Life of a Showgirl',
    lyric: "I wish I'd ruined the friendship",
    verified: false,
  },
  {
    slug: 'actually-romantic',
    song: 'Actually Romantic',
    album: 'The Life of a Showgirl',
    lyric: 'I think you must be actually romantic',
    verified: false,
  },
  {
    slug: 'wish-list',
    song: 'Wish List',
    album: 'The Life of a Showgirl',
    lyric: "That's not what's on my wish list",
    verified: false,
  },
  {
    slug: 'wood',
    song: 'Wood',
    album: 'The Life of a Showgirl',
    lyric: 'Knock on wood',
    verified: false,
  },
  {
    slug: 'cancelled',
    song: 'Cancelled!',
    album: 'The Life of a Showgirl',
    lyric: 'My friends are cancelled',
    verified: false,
  },
  {
    slug: 'honey',
    song: 'Honey',
    album: 'The Life of a Showgirl',
    lyric: 'Call me honey',
    verified: false,
  },
  {
    slug: 'the-life-of-a-showgirl',
    song: 'The Life of a Showgirl',
    album: 'The Life of a Showgirl',
    lyric: 'This is the life of a showgirl',
    verified: false,
  },
];

export default LYRIC_STARTER_POOL;
