// One UI WP2.1-C: the single source of the reader fonts' CSS. Reads the
// committed latin-subset WOFF2 files in packages/ui/fonts and emits, from the
// SAME bytes:
//   fonts/fonts.web.css      url() to /fonts/<name>.<hash>.woff2   (Next web)
//   fonts/fonts.dom.css      data-URI @font-face                   (Expo DOM host:
//                            CSS url() and JS-imported woff2 both 404 there)
//   fonts/fonts.manifest.json  hashes + the preload list
//   apps/web/public/fonts/*  hashed copies served by the web
// Run `node packages/ui/scripts/build-fonts.mjs` after changing a woff2 or the
// table below; `--check` exits 1 if anything on disk is stale (the unit test
// runs the same comparison). The --font-* variable names are the ones
// apps/web/app/layout.tsx used to get from next/font/google.
import { Buffer } from 'node:buffer';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const FONTS_DIR = join(here, '..', 'fonts');
const PUBLIC_DIR = join(here, '..', '..', '..', 'apps', 'web', 'public', 'fonts');

const UNICODE_RANGE =
  'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, ' +
  'U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD';

// Same fallback faces next/font generated (size-adjusted local Arial / Times
// New Roman) so the swap does not shift layout.
export const FAMILIES = [
  {
    file: 'inter',
    family: 'Inter',
    style: 'normal',
    weight: '100 900',
    preload: true,
    fallback: { src: 'Arial', ascent: '90.44%', descent: '22.52%', size: '107.12%' },
  },
  {
    file: 'playfair-display',
    family: 'Playfair Display',
    style: 'normal',
    weight: '400 900',
    preload: true,
    fallback: { src: 'Times New Roman', ascent: '97.25%', descent: '22.56%', size: '111.26%' },
  },
  {
    file: 'special-elite',
    family: 'Special Elite',
    style: 'normal',
    weight: '400',
    fallback: { src: 'Arial', ascent: '60%', descent: '25.33%', size: '117.2%' },
  },
  {
    file: 'dancing-script',
    family: 'Dancing Script',
    style: 'normal',
    weight: '400 700',
    fallback: { src: 'Arial', ascent: '112.99%', descent: '34.39%', size: '81.43%' },
  },
  {
    file: 'bodoni-moda',
    family: 'Bodoni Moda',
    style: 'normal',
    weight: '400 800',
    fallback: { src: 'Times New Roman', ascent: '98.5%', descent: '35.02%', size: '114.21%' },
  },
  { file: 'bodoni-moda-italic', family: 'Bodoni Moda', style: 'italic', weight: '400 800' },
];

const VARS = {
  Inter: '--font-inter',
  'Playfair Display': '--font-playfair',
  'Special Elite': '--font-typewriter',
  'Dancing Script': '--font-script',
  'Bodoni Moda': '--font-bodoni',
};

const sha = (buf) => createHash('sha256').update(buf).digest('hex').slice(0, 8);

function faceCss(f, src) {
  return (
    `@font-face {\n  font-family: '${f.family}';\n  font-style: ${f.style};\n` +
    `  font-weight: ${f.weight};\n  font-display: swap;\n  src: ${src} format('woff2');\n` +
    `  unicode-range: ${UNICODE_RANGE};\n}\n`
  );
}

function fallbackCss() {
  return FAMILIES.filter((f) => f.fallback)
    .map((f) => {
      const k = f.fallback;
      return (
        `@font-face {\n  font-family: '${f.family} Fallback';\n  src: local('${k.src}');\n` +
        `  ascent-override: ${k.ascent};\n  descent-override: ${k.descent};\n` +
        `  line-gap-override: 0%;\n  size-adjust: ${k.size};\n}\n`
      );
    })
    .join('');
}

function rootCss() {
  const lines = Object.entries(VARS).map(
    ([family, v]) => `  ${v}: '${family}', '${family} Fallback';`,
  );
  return `:root {\n${lines.join('\n')}\n}\n`;
}

/** Everything the generator owns, as { absolutePath: Buffer | string }. */
export function buildFonts() {
  const header = '/* GENERATED by packages/ui/scripts/build-fonts.mjs - do not edit. */\n';
  const files = FAMILIES.map((f) => {
    const bytes = readFileSync(join(FONTS_DIR, `${f.file}.woff2`));
    return { ...f, bytes, hash: sha(bytes), publicName: `${f.file}.${sha(bytes)}.woff2` };
  });
  const tail = fallbackCss() + rootCss();
  const web =
    header + files.map((f) => faceCss(f, `url('/fonts/${f.publicName}')`)).join('') + tail;
  const dom =
    header +
    files
      .map((f) => faceCss(f, `url(data:font/woff2;base64,${f.bytes.toString('base64')})`))
      .join('') +
    tail;
  const manifest = {
    preload: files.filter((f) => f.preload).map((f) => `/fonts/${f.publicName}`),
    files: Object.fromEntries(files.map((f) => [f.file, { hash: f.hash, bytes: f.bytes.length }])),
  };
  const out = {
    [join(FONTS_DIR, 'fonts.web.css')]: web,
    [join(FONTS_DIR, 'fonts.dom.css')]: dom,
    [join(FONTS_DIR, 'fonts.manifest.json')]: `${JSON.stringify(manifest, null, 2)}\n`,
  };
  for (const f of files) out[join(PUBLIC_DIR, f.publicName)] = f.bytes;
  return out;
}

/** Public font files on disk that no longer correspond to a source woff2. */
export function staleFiles(expected) {
  if (!existsSync(PUBLIC_DIR)) return [];
  return readdirSync(PUBLIC_DIR)
    .map((n) => join(PUBLIC_DIR, n))
    .filter((p) => !(p in expected));
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const out = buildFonts();
  const stale = staleFiles(out);
  if (process.argv.includes('--check')) {
    const bad = Object.entries(out).filter(
      ([p, c]) => !existsSync(p) || !readFileSync(p).equals(Buffer.from(c)),
    );
    if (bad.length || stale.length) {
      process.stderr.write(`fonts out of date: ${[...bad.map(([p]) => p), ...stale].join(', ')}\n`);
      process.exit(1);
    }
    process.stdout.write('fonts up to date\n');
  } else {
    mkdirSync(PUBLIC_DIR, { recursive: true });
    for (const [p, c] of Object.entries(out)) writeFileSync(p, c);
    process.stdout.write(
      `wrote ${Object.keys(out).length} files; stale public fonts (delete by hand): ${stale.length}\n`,
    );
  }
}
