// Vault canonical releases — every studio album, re-recording, and notable
// EP/deluxe/live edition (rollout PR 3 scope, first pass).
//
// Facts only (dates, labels, track titles) — track titles are facts, never
// lyrics. Every record cites the Wikipedia article that anchors its date,
// label, and tracklist; all URLs verified reachable 2026-07-08. Wikipedia is
// reliability 2 (wiki) per the audit §5 rubric — fine for uncontested
// public-record discography data; contested claims would need stronger.
//
// Then run:  npm run db:seed:releases

const wiki = (article, title, notes) => ({
  source_url: `https://en.wikipedia.org/wiki/${article}`,
  source_title: title,
  publisher: 'Wikipedia',
  source_type: 'wiki',
  accessed_at: '2026-07-08',
  reliability_score: 2,
  excerpt: null,
  notes: notes ?? 'anchors release date, label, and tracklist',
});
const press = (source_url, source_title, publisher, notes) => ({
  source_url,
  source_title,
  publisher,
  source_type: 'reputable_press',
  accessed_at: '2026-07-09',
  reliability_score: 4,
  excerpt: null,
  notes,
});
const official = (source_url, source_title, publisher, notes) => ({
  source_url,
  source_title,
  publisher,
  source_type: 'official',
  accessed_at: '2026-07-09',
  reliability_score: 5,
  excerpt: null,
  notes,
});
const awards = (source_url, source_title, publisher, notes) => ({
  source_url,
  source_title,
  publisher,
  source_type: 'awards_database',
  accessed_at: '2026-07-09',
  reliability_score: 5,
  excerpt: null,
  notes,
});

export default {
  releases: [
    {
      slug: 'taylor-swift',
      eraSlug: 'debut',
      kind: 'album',
      title: 'Taylor Swift',
      releaseDate: '2006-10-24',
      label: 'Big Machine',
      trackCount: 11,
      parentReleaseSlug: null,
      tracklist: [
        'Tim McGraw',
        'Picture to Burn',
        'Teardrops on My Guitar',
        'A Place in This World',
        'Cold as You',
        'The Outside',
        'Tied Together with a Smile',
        'Stay Beautiful',
        "Should've Said No",
        "Mary's Song (Oh My My My)",
        'Our Song',
      ],
      note: 'The debut, written largely during her freshman year of high school — it spent more weeks on the Billboard 200 than any album of the 2000s decade.',
      sources: [
        wiki('Taylor_Swift_(album)', 'Taylor Swift (album)'),
        awards(
          'https://www.grammy.com/artists/taylor-swift/15450',
          'Taylor Swift | 14 Grammy Wins, 4 Album of the year',
          'Recording Academy',
          'supports the debut-era context: Big Machine release, age-16 breakthrough, and songwriting autonomy',
        ),
      ],
    },
    {
      slug: 'napster-live',
      eraSlug: 'debut',
      kind: 'ep',
      title: 'Napster Live',
      releaseDate: '2006-10-24',
      label: 'Big Machine',
      trackCount: null,
      parentReleaseSlug: null,
      note: 'A Napster-exclusive live EP from the debut rollout; the corpus tracks it as a real release but leaves the tracklist blank until a stronger listing is verified.',
      sources: [wiki('Taylor_Swift_albums_discography', 'Taylor Swift albums discography', 'anchors the EP release date, label, and Napster-exclusive status')],
    },
    {
      slug: 'the-taylor-swift-holiday-collection',
      eraSlug: 'debut',
      kind: 'ep',
      title: 'The Taylor Swift Holiday Collection',
      releaseDate: '2007-10-14',
      label: 'Big Machine',
      trackCount: 6,
      parentReleaseSlug: null,
      tracklist: [
        'Last Christmas',
        'Christmases When You Were Mine',
        'Santa Baby',
        'Silent Night',
        'Christmas Must Be Something More',
        'White Christmas',
      ],
      note: 'A six-song holiday EP — four covers plus two originals — first sold as a Target exclusive under the title Sounds of the Season.',
      sources: [wiki('The_Taylor_Swift_Holiday_Collection', 'The Taylor Swift Holiday Collection')],
    },
    {
      slug: 'itunes-live-from-soho',
      eraSlug: 'debut',
      kind: 'ep',
      title: 'iTunes Live from SoHo',
      releaseDate: '2008-01-15',
      label: 'Big Machine',
      trackCount: 8,
      parentReleaseSlug: null,
      note: 'An iTunes-exclusive live EP from the debut era; the release is represented here without an ordered tracklist until a stronger listing is verified.',
      sources: [wiki('Taylor_Swift_albums_discography', 'Taylor Swift albums discography', 'anchors the EP release date, label, and iTunes-exclusive status')],
    },
    {
      slug: 'beautiful-eyes',
      eraSlug: 'debut',
      kind: 'ep',
      title: 'Beautiful Eyes',
      releaseDate: '2008-07-15',
      label: 'Big Machine',
      trackCount: 6,
      parentReleaseSlug: null,
      tracklist: [
        'Beautiful Eyes',
        "Should've Said No (Alternate Version)",
        'Teardrops on My Guitar (Acoustic Version)',
        'Picture to Burn (Radio Edit)',
        "I'm Only Me When I'm with You",
        'I Heart ?',
      ],
      note: 'A Walmart-exclusive stopgap EP between the debut and Fearless — two new songs plus alternate cuts, released to tide fans over.',
      sources: [wiki('Beautiful_Eyes_(EP)', 'Beautiful Eyes (EP)')],
    },
    {
      slug: 'fearless',
      eraSlug: 'fearless',
      kind: 'album',
      title: 'Fearless',
      releaseDate: '2008-11-11',
      label: 'Big Machine',
      trackCount: 13,
      parentReleaseSlug: null,
      tracklist: [
        'Fearless',
        'Fifteen',
        'Love Story',
        'Hey Stephen',
        'White Horse',
        'You Belong with Me',
        'Breathe',
        'Tell Me Why',
        "You're Not Sorry",
        'The Way I Loved You',
        'Forever & Always',
        'The Best Day',
        'Change',
      ],
      note: 'The album that made her the youngest artist (at the time) to win the Grammy for Album of the Year — and 2009’s best-selling album in the US.',
      sources: [
        wiki('Fearless_(Taylor_Swift_album)', 'Fearless (Taylor Swift album)'),
        awards(
          'https://www.grammy.com/artists/taylor-swift/15450',
          'Taylor Swift | 14 Grammy Wins, 4 Album of the year',
          'Recording Academy',
          'supports the Fearless breakthrough, 2009 best-selling-album context, and 2010 Album of the Year win',
        ),
      ],
    },
    {
      slug: 'fearless-platinum-edition',
      eraSlug: 'fearless',
      kind: 'deluxe',
      title: 'Fearless: Platinum Edition',
      releaseDate: '2009-10-26',
      label: 'Big Machine',
      trackCount: 19,
      parentReleaseSlug: 'fearless',
      tracklist: [
        'Jump Then Fall',
        'Untouchable',
        'Forever & Always (Piano Version)',
        'Come In with the Rain',
        'Superstar',
        'The Other Side of the Door',
        'Fearless',
        'Fifteen',
        'Love Story',
        'Hey Stephen',
        'White Horse',
        'You Belong with Me',
        'Breathe',
        'Tell Me Why',
        "You're Not Sorry",
        'The Way I Loved You',
        'Forever & Always',
        'The Best Day',
        'Change',
      ],
      note: 'The reissue that put six new songs IN FRONT of the album — Jump Then Fall through The Other Side of the Door lead the tracklist.',
      sources: [wiki('Fearless_(Taylor_Swift_album)', 'Fearless (Taylor Swift album)', 'Platinum Edition date + added tracks documented in the album article')],
    },
    {
      slug: 'speak-now',
      eraSlug: 'speak-now',
      kind: 'album',
      title: 'Speak Now',
      releaseDate: '2010-10-25',
      label: 'Big Machine',
      trackCount: 14,
      parentReleaseSlug: null,
      tracklist: [
        'Mine',
        'Sparks Fly',
        'Back to December',
        'Speak Now',
        'Dear John',
        'Mean',
        'The Story of Us',
        'Never Grow Up',
        'Enchanted',
        'Better than Revenge',
        'Innocent',
        'Haunted',
        'Last Kiss',
        'Long Live',
      ],
      note: 'Written entirely by Taylor alone, ages 18 to 20 — her answer to critics who doubted she wrote her own songs. Over a million copies sold in week one.',
      sources: [
        wiki('Speak_Now', 'Speak Now'),
        awards(
          'https://www.grammy.com/artists/taylor-swift/15450',
          'Taylor Swift | 14 Grammy Wins, 4 Album of the year',
          'Recording Academy',
          'supports the entirely self-written Speak Now context and Grammy-era recognition',
        ),
      ],
    },
    {
      slug: 'speak-now-world-tour-live',
      eraSlug: 'speak-now',
      kind: 'live',
      title: 'Speak Now World Tour - Live',
      releaseDate: '2011-11-21',
      label: 'Big Machine',
      trackCount: 16,
      parentReleaseSlug: 'speak-now',
      note: 'The first live album/video-album release from the Speak Now World Tour, issued as a CD plus DVD/Blu-ray package.',
      sources: [wiki('Speak_Now_World_Tour_%E2%80%93_Live', 'Speak Now World Tour - Live', 'anchors release date, label, format, and track count')],
    },
    {
      slug: 'red',
      eraSlug: 'red',
      kind: 'album',
      title: 'Red',
      releaseDate: '2012-10-22',
      label: 'Big Machine',
      trackCount: 16,
      parentReleaseSlug: null,
      tracklist: [
        'State of Grace',
        'Red',
        'Treacherous',
        'I Knew You Were Trouble',
        'All Too Well',
        '22',
        'I Almost Do',
        'We Are Never Ever Getting Back Together',
        'Stay Stay Stay',
        'The Last Time',
        'Holy Ground',
        'Sad Beautiful Tragic',
        'The Lucky One',
        'Everything Has Changed',
        'Starlight',
        'Begin Again',
      ],
      note: 'The pivot record — country songwriting meets pop production (first Max Martin/Shellback collaborations), anchored by the fan-canonized All Too Well.',
      sources: [
        wiki('Red_(Taylor_Swift_album)', 'Red (Taylor Swift album)'),
        press(
          'https://pitchfork.com/reviews/albums/taylor-swift-red',
          'Red',
          'Pitchfork',
          'supports the Red-era country-to-pop pivot and Max Martin/Shellback collaboration context',
        ),
      ],
    },
    {
      slug: '1989',
      eraSlug: '1989',
      kind: 'album',
      title: '1989',
      releaseDate: '2014-10-27',
      label: 'Big Machine',
      trackCount: 13,
      parentReleaseSlug: null,
      tracklist: [
        'Welcome to New York',
        'Blank Space',
        'Style',
        'Out of the Woods',
        'All You Had to Do Was Stay',
        'Shake It Off',
        'I Wish You Would',
        'Bad Blood',
        'Wildest Dreams',
        'How You Get the Girl',
        'This Love',
        'I Know Places',
        'Clean',
      ],
      note: 'Her "first documented, official pop album" — named for her birth year, it swept Album of the Year at the Grammys and rewired her career.',
      sources: [
        wiki('1989_(album)', '1989 (album)'),
        press(
          'https://time.com/3533569/taylor-swift-1989-review/',
          'Review: 1989 Marks a Paradigm Swift',
          'Time',
          'supports the official pop-album pivot and Max Martin pop-production context',
        ),
        awards(
          'https://www.grammy.com/artists/taylor-swift/15450',
          'Taylor Swift | 14 Grammy Wins, 4 Album of the year',
          'Recording Academy',
          'supports the 1989 Album of the Year win and pop-category Grammy context',
        ),
      ],
    },
    {
      slug: 'reputation',
      eraSlug: 'reputation',
      kind: 'album',
      title: 'reputation',
      releaseDate: '2017-11-10',
      label: 'Big Machine',
      trackCount: 15,
      parentReleaseSlug: null,
      tracklist: [
        '...Ready for It?',
        'End Game',
        'I Did Something Bad',
        "Don't Blame Me",
        'Delicate',
        'Look What You Made Me Do',
        'So It Goes...',
        'Gorgeous',
        'Getaway Car',
        'King of My Heart',
        'Dancing with Our Hands Tied',
        'Dress',
        "This Is Why We Can't Have Nice Things",
        'Call It What You Want',
        "New Year's Day",
      ],
      note: 'The no-press, no-singles-cycle comeback after the 2016 snake summer — electropop armor on the outside, a love story underneath. Her last Big Machine album.',
      sources: [
        wiki('Reputation_(album)', 'Reputation (album)'),
        awards(
          'https://www.grammy.com/artists/taylor-swift/15450',
          'Taylor Swift | 14 Grammy Wins, 4 Album of the year',
          'Recording Academy',
          'supports the post-1989 public-retreat context and reputation Stadium Tour commercial impact',
        ),
      ],
    },
    {
      slug: 'spotify-singles',
      eraSlug: 'reputation',
      kind: 'ep',
      title: 'Spotify Singles',
      releaseDate: '2018-04-13',
      label: 'Big Machine',
      trackCount: 2,
      parentReleaseSlug: null,
      note: 'A Spotify-exclusive two-track session: an acoustic Delicate and a cover of Earth, Wind & Fire\'s September, recorded in Nashville.',
      sources: [
        wiki('Taylor_Swift_albums_discography', 'Taylor Swift albums discography', 'anchors the EP release date and Spotify-exclusive status'),
        official(
          'https://newsroom.spotify.com/2018-04-13/taylor-swift-records-delicate-and-earth-wind-fires-september-for-spotify-singles/',
          "Taylor Swift Records Delicate and Earth, Wind & Fire's September for Spotify Singles",
          'Spotify',
          'official Spotify announcement for the two-track Spotify Singles release',
        ),
      ],
    },
    {
      slug: 'lover',
      eraSlug: 'lover',
      kind: 'album',
      title: 'Lover',
      releaseDate: '2019-08-23',
      label: 'Republic',
      trackCount: 18,
      parentReleaseSlug: null,
      tracklist: [
        'I Forgot That You Existed',
        'Cruel Summer',
        'Lover',
        'The Man',
        'The Archer',
        'I Think He Knows',
        'Miss Americana & the Heartbreak Prince',
        'Paper Rings',
        'Cornelia Street',
        'Death by a Thousand Cuts',
        'London Boy',
        "Soon You'll Get Better",
        'False God',
        'You Need to Calm Down',
        'Afterglow',
        'ME!',
        "It's Nice to Have a Friend",
        'Daylight',
      ],
      note: 'The first album she has owned outright from day one — her Republic Records debut after leaving Big Machine, and the pastel reset after reputation.',
      sources: [
        wiki('Lover_(album)', 'Lover (album)'),
        press(
          'https://time.com/5651221/taylor-swift-lover-references-explained/',
          "Your Guide to the Many, Many References Taylor Swift Drops in the Lover Album",
          'Time',
          'supports the August 23, 2019 release and 18-track Lover album context',
        ),
      ],
    },
    {
      slug: 'live-from-clear-channel-stripped-2008',
      eraSlug: 'lover',
      kind: 'live',
      title: 'Live from Clear Channel Stripped 2008',
      releaseDate: '2020-04-24',
      label: 'Big Machine',
      trackCount: null,
      parentReleaseSlug: null,
      note: 'A 2008 radio-session live album released by Big Machine in 2020 without Swift\'s approval; included for discography completeness, not endorsement.',
      sources: [
        wiki('Live_from_Clear_Channel_Stripped_2008', 'Live from Clear Channel Stripped 2008'),
        press(
          'https://pitchfork.com/news/taylor-swift-says-former-label-is-releasing-unapproved-live-album-of-hers-tonight',
          'Taylor Swift Live Album Released by Former Label Despite Her Disapproval',
          'Pitchfork',
          'supports the release context and Swift objection',
        ),
      ],
    },
    {
      slug: 'folklore',
      eraSlug: 'folklore',
      kind: 'album',
      title: 'folklore',
      releaseDate: '2020-07-24',
      label: 'Republic',
      trackCount: 16,
      parentReleaseSlug: null,
      tracklist: [
        'the 1',
        'cardigan',
        'the last great american dynasty',
        'exile',
        'my tears ricochet',
        'mirrorball',
        'seven',
        'august',
        'this is me trying',
        'illicit affairs',
        'invisible string',
        'mad woman',
        'epiphany',
        'betty',
        'peace',
        'hoax',
      ],
      note: 'The surprise lockdown album, announced 16 hours before release — indie-folk storytelling with Aaron Dessner and Jack Antonoff. Album of the Year Grammy #3.',
      sources: [
        wiki('Folklore_(Taylor_Swift_album)', 'Folklore (Taylor Swift album)'),
        press(
          'https://pitchfork.com/news/the-nationals-aaron-dessner-talks-taylor-swifts-new-album-folklore',
          "The National's Aaron Dessner Talks Taylor Swift's New Album folklore",
          'Pitchfork',
          'supports the surprise July 2020 release and Aaron Dessner collaboration context',
        ),
        awards(
          'https://www.grammy.com/artists/taylor-swift/15450',
          'Taylor Swift | 14 Grammy Wins, 4 Album of the year',
          'Recording Academy',
          'supports the folklore Album of the Year win',
        ),
      ],
    },
    {
      slug: 'folklore-the-long-pond-studio-sessions',
      eraSlug: 'folklore',
      kind: 'live',
      title: 'folklore: the long pond studio sessions',
      releaseDate: '2020-11-25',
      label: 'Republic',
      trackCount: 17,
      parentReleaseSlug: 'folklore',
      note: 'The stripped live companion to the Disney+ film — folklore performed straight through at Long Pond with Dessner and Antonoff, plus "the lakes".',
      sources: [
        wiki('Folklore:_The_Long_Pond_Studio_Sessions', 'Folklore: The Long Pond Studio Sessions'),
        press(
          'https://www.teenvogue.com/story/taylor-swift-folklore-special-disney-plus',
          'Taylor Swift Is Releasing a "Folklore" Special on Disney+',
          'Teen Vogue',
          'supports the Disney+ film/release context for the Long Pond companion record',
        ),
      ],
    },
    {
      slug: 'evermore',
      eraSlug: 'evermore',
      kind: 'album',
      title: 'evermore',
      releaseDate: '2020-12-11',
      label: 'Republic',
      trackCount: 15,
      parentReleaseSlug: null,
      tracklist: [
        'willow',
        'champagne problems',
        'gold rush',
        "'tis the damn season",
        'tolerate it',
        'no body, no crime',
        'happiness',
        'dorothea',
        'coney island',
        'ivy',
        'cowboy like me',
        'long story short',
        'marjorie',
        'closure',
        'evermore',
      ],
      note: "folklore's \"sister album,\" dropped five months later as a second surprise — announced two days before her 31st birthday because 13 is her lucky number backwards.",
      sources: [
        wiki('Evermore_(Taylor_Swift_album)', 'Evermore (Taylor Swift album)'),
        press(
          'https://www.vanityfair.com/style/2020/12/taylor-swift-evermore-review',
          'Taylor Swift Shakes Off More of Her Self-Consciousness on Evermore',
          'Vanity Fair',
          'supports the December 2020 release and folklore sister-album context',
        ),
      ],
    },
    {
      slug: 'fearless-taylors-version',
      eraSlug: 'evermore',
      kind: 'rerecording',
      title: "Fearless (Taylor's Version)",
      releaseDate: '2021-04-09',
      label: 'Republic',
      trackCount: 26,
      parentReleaseSlug: 'fearless',
      tracklist: [
        'Fearless',
        'Fifteen',
        'Love Story',
        'Hey Stephen',
        'White Horse',
        'You Belong with Me',
        'Breathe',
        'Tell Me Why',
        "You're Not Sorry",
        'The Way I Loved You',
        'Forever & Always',
        'The Best Day',
        'Change',
        'Jump Then Fall',
        'Untouchable',
        'Forever & Always (Piano Version)',
        'Come In with the Rain',
        'Superstar',
        'The Other Side of the Door',
        'Today Was a Fairytale',
        'You All Over Me',
        'Mr. Perfectly Fine',
        'We Were Happy',
        "That's When",
        "Don't You",
        'Bye Bye Baby',
      ],
      note: 'The first re-recording in the masters battle — 26 tracks, including six never-released songs "From the Vault." Proof of concept for the whole project.',
      sources: [
        wiki('Fearless_(Taylor%27s_Version)', "Fearless (Taylor's Version)"),
        press(
          'https://pitchfork.com/reviews/albums/taylor-swift-fearless-taylors-version',
          "Fearless (Taylor's Version)",
          'Pitchfork',
          'supports the first Taylor\'s Version release and re-recording-project context',
        ),
      ],
    },
    {
      slug: 'red-taylors-version',
      eraSlug: 'evermore',
      kind: 'rerecording',
      title: "Red (Taylor's Version)",
      releaseDate: '2021-11-12',
      label: 'Republic',
      trackCount: 30,
      parentReleaseSlug: 'red',
      tracklist: [
        'State of Grace',
        'Red',
        'Treacherous',
        'I Knew You Were Trouble',
        'All Too Well',
        '22',
        'I Almost Do',
        'We Are Never Ever Getting Back Together',
        'Stay Stay Stay',
        'The Last Time',
        'Holy Ground',
        'Sad Beautiful Tragic',
        'The Lucky One',
        'Everything Has Changed',
        'Starlight',
        'Begin Again',
        'The Moment I Knew',
        'Come Back... Be Here',
        'Girl at Home',
        'State of Grace (Acoustic Version)',
        'Ronan',
        'Better Man',
        'Nothing New',
        'Babe',
        'Message in a Bottle',
        'I Bet You Think About Me',
        'Forever Winter',
        'Run',
        'The Very First Night',
        'All Too Well (10 Minute Version)',
      ],
      note: 'Thirty tracks capped by the ten-minute All Too Well — the version fans spent nine years asking for, which promptly became the longest #1 in Hot 100 history.',
      sources: [
        wiki('Red_(Taylor%27s_Version)', "Red (Taylor's Version)"),
        press(
          'https://pitchfork.com/reviews/albums/taylor-swift-red-taylors-version',
          "Red (Taylor's Version)",
          'Pitchfork',
          'supports the re-recorded Red release and vault/ten-minute All Too Well context',
        ),
      ],
    },
    {
      slug: 'midnights',
      eraSlug: 'midnights',
      kind: 'album',
      title: 'Midnights',
      releaseDate: '2022-10-21',
      label: 'Republic',
      trackCount: 13,
      parentReleaseSlug: null,
      tracklist: [
        'Lavender Haze',
        'Maroon',
        'Anti-Hero',
        'Snow on the Beach',
        "You're on Your Own, Kid",
        'Midnight Rain',
        'Question...?',
        'Vigilante Shit',
        'Bejeweled',
        'Labyrinth',
        'Karma',
        'Sweet Nothing',
        'Mastermind',
      ],
      note: '"13 sleepless nights" as a concept album — it broke Spotify’s single-day record and made her the first artist to occupy the entire Hot 100 top 10 at once.',
      sources: [
        wiki('Midnights', 'Midnights'),
        press(
          'https://pitchfork.com/news/taylor-swift-reveals-new-album-midnights-full-tracklist',
          "Taylor Swift Reveals New Album Midnights' Full Tracklist, Including New Song With Lana Del Rey",
          'Pitchfork',
          'supports the release date, 13-track standard edition, and album rollout context',
        ),
      ],
    },
    {
      slug: 'midnights-3am-edition',
      eraSlug: 'midnights',
      kind: 'deluxe',
      title: 'Midnights (3am Edition)',
      releaseDate: '2022-10-22',
      label: 'Republic',
      trackCount: 20,
      parentReleaseSlug: 'midnights',
      tracklist: [
        'Lavender Haze',
        'Maroon',
        'Anti-Hero',
        'Snow on the Beach',
        "You're on Your Own, Kid",
        'Midnight Rain',
        'Question...?',
        'Vigilante Shit',
        'Bejeweled',
        'Labyrinth',
        'Karma',
        'Sweet Nothing',
        'Mastermind',
        'The Great War',
        'Bigger Than the Whole Sky',
        'Paris',
        'High Infidelity',
        'Glitch',
        "Would've, Could've, Should've",
        'Dear Reader',
      ],
      note: 'Announced at literally 3am the night of release: seven more songs from the Midnights sessions, "we think of them as this special surprise".',
      sources: [
        wiki('Midnights', 'Midnights', '3am Edition date + added tracks documented in the album article'),
        press(
          'https://ew.com/music/taylor-swift-reveals-midnights-album-surprise-seven-more-songs/',
          'Taylor Swift reveals chaotic surprise for "Midnights" album: 7 more new songs',
          'Entertainment Weekly',
          'supports the 3am surprise release and seven added songs',
        ),
      ],
    },
    {
      slug: 'lover-live-from-paris',
      eraSlug: 'midnights',
      kind: 'live',
      title: 'Lover (Live from Paris)',
      releaseDate: '2023-02-14',
      label: 'Republic',
      trackCount: 8,
      parentReleaseSlug: 'lover',
      note: 'A heart-shaped vinyl live album from the 2019 City of Lover concert, released on Valentine\'s Day during the Midnights era.',
      sources: [
        wiki('Lover_(Live_from_Paris)', 'Lover (Live from Paris)'),
        press(
          'https://www.theguardian.com/music/2025/feb/14/taylor-swift-surpasses-madonna-as-female-artist-with-most-uk-no-1-albums',
          'Taylor Swift surpasses Madonna as female artist with most UK No 1 albums',
          'The Guardian',
          'supports the live-album release and later chart context',
        ),
      ],
    },
    {
      slug: 'midnights-the-til-dawn-edition',
      eraSlug: 'midnights',
      kind: 'deluxe',
      title: "Midnights (The Til Dawn Edition)",
      releaseDate: '2023-05-26',
      label: 'Republic',
      trackCount: 23,
      parentReleaseSlug: 'midnights',
      tracklist: [
        'Lavender Haze',
        'Maroon',
        'Anti-Hero',
        'Snow on the Beach',
        "You're on Your Own, Kid",
        'Midnight Rain',
        'Question...?',
        'Vigilante Shit',
        'Bejeweled',
        'Labyrinth',
        'Karma',
        'Sweet Nothing',
        'Mastermind',
        'The Great War',
        'Bigger Than the Whole Sky',
        'Paris',
        'High Infidelity',
        'Glitch',
        "Would've, Could've, Should've",
        'Dear Reader',
        'Hits Different',
        'Snow on the Beach (feat. More Lana Del Rey)',
        'Karma (feat. Ice Spice)',
      ],
      note: 'The Eras-Tour-summer expansion: Hits Different goes streaming-wide, Lana gets a full feature on Snow on the Beach, and Ice Spice joins Karma.',
      sources: [
        wiki('Midnights', 'Midnights', "Til Dawn Edition date + added tracks documented in the album article"),
        press(
          'https://people.com/music/taylor-swift-announces-midnights-til-dawn-edition-ice-spice-lana-del-rey/',
          "Taylor Swift Announces Midnights (Til Dawn Edition) Featuring Ice Spice and More Lana Del Rey",
          'People',
          'supports the Til Dawn Edition additions: Hits Different, More Lana Del Rey, and Karma featuring Ice Spice',
        ),
      ],
    },
    {
      slug: 'speak-now-taylors-version',
      eraSlug: 'midnights',
      kind: 'rerecording',
      title: "Speak Now (Taylor's Version)",
      releaseDate: '2023-07-07',
      label: 'Republic',
      trackCount: 22,
      parentReleaseSlug: 'speak-now',
      tracklist: [
        'Mine',
        'Sparks Fly',
        'Back to December',
        'Speak Now',
        'Dear John',
        'Mean',
        'The Story of Us',
        'Never Grow Up',
        'Enchanted',
        'Better than Revenge',
        'Innocent',
        'Haunted',
        'Last Kiss',
        'Long Live',
        'Ours',
        'Superman',
        'Electric Touch',
        'When Emma Falls in Love',
        'I Can See You',
        'Castles Crumbling',
        'Foolish One',
        'Timeless',
      ],
      note: 'Announced on stage in Nashville mid-Eras-Tour — the all-self-written album returns with vault guests Fall Out Boy and Hayley Williams.',
      sources: [
        wiki('Speak_Now_(Taylor%27s_Version)', "Speak Now (Taylor's Version)"),
        press(
          'https://pitchfork.com/news/taylor-swift-breaks-record-for-most-no-1-albums-by-a-female-artist-with-speak-now-taylors-version',
          "Taylor Swift Breaks Record for Most No. 1 Albums by a Female Artist With Speak Now (Taylor's Version)",
          'Pitchfork',
          "supports the Speak Now (Taylor's Version) release, vault expansion, and chart context",
        ),
      ],
    },
    {
      slug: '1989-taylors-version',
      eraSlug: 'midnights',
      kind: 'rerecording',
      title: "1989 (Taylor's Version)",
      releaseDate: '2023-10-27',
      label: 'Republic',
      trackCount: 21,
      parentReleaseSlug: '1989',
      tracklist: [
        'Welcome to New York',
        'Blank Space',
        'Style',
        'Out of the Woods',
        'All You Had to Do Was Stay',
        'Shake It Off',
        'I Wish You Would',
        'Bad Blood',
        'Wildest Dreams',
        'How You Get the Girl',
        'This Love',
        'I Know Places',
        'Clean',
        'Wonderland',
        'You Are in Love',
        'New Romantics',
        '"Slut!"',
        "Say Don't Go",
        "Now That We Don't Talk",
        'Suburban Legends',
        'Is It Over Now?',
      ],
      note: 'Announced at the final US Eras Tour show of 2023 (8/9, wink) — nine years to the season after the original, with five vault tracks fans decoded via Google puzzles.',
      sources: [
        wiki('1989_(Taylor%27s_Version)', "1989 (Taylor's Version)"),
        press(
          'https://pitchfork.com/reviews/albums/taylor-swift-1989-taylors-version',
          "1989 (Taylor's Version)",
          'Pitchfork',
          "supports the 1989 (Taylor's Version) re-recording and vault-track context",
        ),
      ],
    },
    {
      slug: 'the-tortured-poets-department',
      eraSlug: 'tortured-poets',
      kind: 'album',
      title: 'The Tortured Poets Department',
      releaseDate: '2024-04-19',
      label: 'Republic',
      trackCount: 16,
      parentReleaseSlug: null,
      tracklist: [
        'Fortnight',
        'The Tortured Poets Department',
        'My Boy Only Breaks His Favorite Toys',
        'Down Bad',
        'So Long, London',
        'But Daddy I Love Him',
        'Fresh Out the Slammer',
        'Florida!!!',
        'Guilty as Sin?',
        "Who's Afraid of Little Old Me?",
        'I Can Fix Him (No Really I Can)',
        'loml',
        'I Can Do It with a Broken Heart',
        'The Smallest Man Who Ever Lived',
        'The Alchemy',
        'Clara Bow',
      ],
      note: 'Announced from the Grammys stage while winning Album of the Year #4 — the quill-pen breakup opus that became Spotify’s most-streamed album in a single day.',
      sources: [
        wiki('The_Tortured_Poets_Department', 'The Tortured Poets Department'),
        press(
          'https://www.teenvogue.com/story/taylor-swift-new-album-tortured-poets-department',
          "Taylor Swift's Tortured Poets Department: Double Album, Tracklist, Bonus Songs, Release Date, and Everything to Know",
          'Teen Vogue',
          'supports the April 19, 2024 release, standard tracklist, and feature credits',
        ),
      ],
    },
    {
      slug: 'ttpd-the-anthology',
      eraSlug: 'tortured-poets',
      kind: 'deluxe',
      title: 'The Tortured Poets Department: The Anthology',
      releaseDate: '2024-04-19',
      label: 'Republic',
      trackCount: 31,
      parentReleaseSlug: 'the-tortured-poets-department',
      tracklist: [
        'Fortnight',
        'The Tortured Poets Department',
        'My Boy Only Breaks His Favorite Toys',
        'Down Bad',
        'So Long, London',
        'But Daddy I Love Him',
        'Fresh Out the Slammer',
        'Florida!!!',
        'Guilty as Sin?',
        "Who's Afraid of Little Old Me?",
        'I Can Fix Him (No Really I Can)',
        'loml',
        'I Can Do It with a Broken Heart',
        'The Smallest Man Who Ever Lived',
        'The Alchemy',
        'Clara Bow',
        'The Black Dog',
        'imgonnagetyouback',
        'The Albatross',
        'Chloe or Sam or Sophia or Marcus',
        'How Did It End?',
        'So High School',
        'I Hate It Here',
        'thanK you aIMee',
        "I Look in People's Windows",
        'The Prophecy',
        'Cassandra',
        'Peter',
        'The Bolter',
        'Robin',
        'The Manuscript',
      ],
      note: '"It’s a 2am surprise": two hours after release, the 16-track album doubled into a 31-track anthology — "I’ve written so much tortured poetry in the past 2 years".',
      sources: [
        wiki('The_Tortured_Poets_Department', 'The Tortured Poets Department', 'Anthology drop + added tracks documented in the album article'),
        press(
          'https://www.teenvogue.com/story/taylor-swift-new-album-tortured-poets-department',
          "Taylor Swift's Tortured Poets Department: Double Album, Tracklist, Bonus Songs, Release Date, and Everything to Know",
          'Teen Vogue',
          'supports The Anthology as the surprise double-album expansion and its added songs',
        ),
      ],
    },
    {
      slug: 'the-life-of-a-showgirl',
      eraSlug: 'the-life-of-a-showgirl',
      kind: 'album',
      title: 'The Life of a Showgirl',
      releaseDate: '2025-10-03',
      label: 'Republic',
      trackCount: 12,
      parentReleaseSlug: null,
      tracklist: [
        'The Fate of Ophelia',
        'Elizabeth Taylor',
        'Opalite',
        'Father Figure',
        'Eldest Daughter',
        'Ruin the Friendship',
        'Actually Romantic',
        'Wi$h Li$t',
        'Wood',
        'CANCELLED!',
        'Honey',
        'The Life of a Showgirl',
      ],
      note: 'Announced on the New Heights podcast in a burst of orange — 12 tracks written mid-Eras-Tour with Max Martin and Shellback, closing with the Sabrina Carpenter title duet.',
      sources: [
        wiki('The_Life_of_a_Showgirl', 'The Life of a Showgirl'),
        press(
          'https://apnews.com/article/c4262686b5b68ee210f7571b8716ab51',
          "Taylor Swift announces 12th studio album, 'The Life of a Showgirl,' shares release date",
          'Associated Press',
          'supports the October 3, 2025 release date, 12-track count, producers, and Sabrina Carpenter feature',
        ),
      ],
    },
  ],
};
