// Vault canonical releases — every studio album, re-recording, and notable
// EP/deluxe/live edition (rollout PR 3 scope, first pass).
//
// Facts only (dates, labels, track titles) — track titles are facts, never
// lyrics. Every record cites the Wikipedia article that anchors its date,
// label, and tracklist; all URLs verified reachable 2026-07-08. Wikipedia is
// reliability 2 (wiki) per the audit §5 rubric — fine for uncontested
// public-record discography data; contested claims would need stronger.
//
// Then run:  npm run db:seed:releases

const wiki = (article, title, notes) => ({
  source_url: `https://en.wikipedia.org/wiki/${article}`,
  source_title: title,
  publisher: 'Wikipedia',
  source_type: 'wiki',
  accessed_at: '2026-07-08',
  reliability_score: 2,
  excerpt: null,
  notes: notes ?? 'anchors release date, label, and tracklist',
});

export default {
  releases: [
    {
      slug: 'taylor-swift',
      eraSlug: 'debut',
      kind: 'album',
      title: 'Taylor Swift',
      releaseDate: '2006-10-24',
      label: 'Big Machine',
      trackCount: 11,
      parentReleaseSlug: null,
      tracklist: [
        'Tim McGraw',
        'Picture to Burn',
        'Teardrops on My Guitar',
        'A Place in This World',
        'Cold as You',
        'The Outside',
        'Tied Together with a Smile',
        'Stay Beautiful',
        "Should've Said No",
        "Mary's Song (Oh My My My)",
        'Our Song',
      ],
      note: 'The debut, written largely during her freshman year of high school — it spent more weeks on the Billboard 200 than any album of the 2000s decade.',
      sources: [wiki('Taylor_Swift_(album)', 'Taylor Swift (album)')],
    },
    {
      slug: 'the-taylor-swift-holiday-collection',
      eraSlug: 'debut',
      kind: 'ep',
      title: 'The Taylor Swift Holiday Collection',
      releaseDate: '2007-10-14',
      label: 'Big Machine',
      trackCount: 6,
      parentReleaseSlug: null,
      tracklist: [
        'Last Christmas',
        'Christmases When You Were Mine',
        'Santa Baby',
        'Silent Night',
        'Christmas Must Be Something More',
        'White Christmas',
      ],
      note: 'A six-song holiday EP — four covers plus two originals — first sold as a Target exclusive under the title Sounds of the Season.',
      sources: [wiki('The_Taylor_Swift_Holiday_Collection', 'The Taylor Swift Holiday Collection')],
    },
    {
      slug: 'beautiful-eyes',
      eraSlug: 'debut',
      kind: 'ep',
      title: 'Beautiful Eyes',
      releaseDate: '2008-07-15',
      label: 'Big Machine',
      trackCount: 6,
      parentReleaseSlug: null,
      tracklist: [
        'Beautiful Eyes',
        "Should've Said No (Alternate Version)",
        'Teardrops on My Guitar (Acoustic Version)',
        'Picture to Burn (Radio Edit)',
        "I'm Only Me When I'm with You",
        'I Heart ?',
      ],
      note: 'A Walmart-exclusive stopgap EP between the debut and Fearless — two new songs plus alternate cuts, released to tide fans over.',
      sources: [wiki('Beautiful_Eyes_(EP)', 'Beautiful Eyes (EP)')],
    },
    {
      slug: 'fearless',
      eraSlug: 'fearless',
      kind: 'album',
      title: 'Fearless',
      releaseDate: '2008-11-11',
      label: 'Big Machine',
      trackCount: 13,
      parentReleaseSlug: null,
      tracklist: [
        'Fearless',
        'Fifteen',
        'Love Story',
        'Hey Stephen',
        'White Horse',
        'You Belong with Me',
        'Breathe',
        'Tell Me Why',
        "You're Not Sorry",
        'The Way I Loved You',
        'Forever & Always',
        'The Best Day',
        'Change',
      ],
      note: 'The album that made her the youngest artist (at the time) to win the Grammy for Album of the Year — and 2009’s best-selling album in the US.',
      sources: [wiki('Fearless_(Taylor_Swift_album)', 'Fearless (Taylor Swift album)')],
    },
    {
      slug: 'fearless-platinum-edition',
      eraSlug: 'fearless',
      kind: 'deluxe',
      title: 'Fearless: Platinum Edition',
      releaseDate: '2009-10-26',
      label: 'Big Machine',
      trackCount: 19,
      parentReleaseSlug: 'fearless',
      tracklist: [
        'Jump Then Fall',
        'Untouchable',
        'Forever & Always (Piano Version)',
        'Come In with the Rain',
        'Superstar',
        'The Other Side of the Door',
        'Fearless',
        'Fifteen',
        'Love Story',
        'Hey Stephen',
        'White Horse',
        'You Belong with Me',
        'Breathe',
        'Tell Me Why',
        "You're Not Sorry",
        'The Way I Loved You',
        'Forever & Always',
        'The Best Day',
        'Change',
      ],
      note: 'The reissue that put six new songs IN FRONT of the album — Jump Then Fall through The Other Side of the Door lead the tracklist.',
      sources: [wiki('Fearless_(Taylor_Swift_album)', 'Fearless (Taylor Swift album)', 'Platinum Edition date + added tracks documented in the album article')],
    },
    {
      slug: 'speak-now',
      eraSlug: 'speak-now',
      kind: 'album',
      title: 'Speak Now',
      releaseDate: '2010-10-25',
      label: 'Big Machine',
      trackCount: 14,
      parentReleaseSlug: null,
      tracklist: [
        'Mine',
        'Sparks Fly',
        'Back to December',
        'Speak Now',
        'Dear John',
        'Mean',
        'The Story of Us',
        'Never Grow Up',
        'Enchanted',
        'Better than Revenge',
        'Innocent',
        'Haunted',
        'Last Kiss',
        'Long Live',
      ],
      note: 'Written entirely by Taylor alone, ages 18 to 20 — her answer to critics who doubted she wrote her own songs. Over a million copies sold in week one.',
      sources: [wiki('Speak_Now', 'Speak Now')],
    },
    {
      slug: 'red',
      eraSlug: 'red',
      kind: 'album',
      title: 'Red',
      releaseDate: '2012-10-22',
      label: 'Big Machine',
      trackCount: 16,
      parentReleaseSlug: null,
      tracklist: [
        'State of Grace',
        'Red',
        'Treacherous',
        'I Knew You Were Trouble',
        'All Too Well',
        '22',
        'I Almost Do',
        'We Are Never Ever Getting Back Together',
        'Stay Stay Stay',
        'The Last Time',
        'Holy Ground',
        'Sad Beautiful Tragic',
        'The Lucky One',
        'Everything Has Changed',
        'Starlight',
        'Begin Again',
      ],
      note: 'The pivot record — country songwriting meets pop production (first Max Martin/Shellback collaborations), anchored by the fan-canonized All Too Well.',
      sources: [wiki('Red_(Taylor_Swift_album)', 'Red (Taylor Swift album)')],
    },
    {
      slug: '1989',
      eraSlug: '1989',
      kind: 'album',
      title: '1989',
      releaseDate: '2014-10-27',
      label: 'Big Machine',
      trackCount: 13,
      parentReleaseSlug: null,
      tracklist: [
        'Welcome to New York',
        'Blank Space',
        'Style',
        'Out of the Woods',
        'All You Had to Do Was Stay',
        'Shake It Off',
        'I Wish You Would',
        'Bad Blood',
        'Wildest Dreams',
        'How You Get the Girl',
        'This Love',
        'I Know Places',
        'Clean',
      ],
      note: 'Her "first documented, official pop album" — named for her birth year, it swept Album of the Year at the Grammys and rewired her career.',
      sources: [wiki('1989_(album)', '1989 (album)')],
    },
    {
      slug: 'reputation',
      eraSlug: 'reputation',
      kind: 'album',
      title: 'reputation',
      releaseDate: '2017-11-10',
      label: 'Big Machine',
      trackCount: 15,
      parentReleaseSlug: null,
      tracklist: [
        '...Ready for It?',
        'End Game',
        'I Did Something Bad',
        "Don't Blame Me",
        'Delicate',
        'Look What You Made Me Do',
        'So It Goes...',
        'Gorgeous',
        'Getaway Car',
        'King of My Heart',
        'Dancing with Our Hands Tied',
        'Dress',
        "This Is Why We Can't Have Nice Things",
        'Call It What You Want',
        "New Year's Day",
      ],
      note: 'The no-press, no-singles-cycle comeback after the 2016 snake summer — electropop armor on the outside, a love story underneath. Her last Big Machine album.',
      sources: [wiki('Reputation_(album)', 'Reputation (album)')],
    },
    {
      slug: 'lover',
      eraSlug: 'lover',
      kind: 'album',
      title: 'Lover',
      releaseDate: '2019-08-23',
      label: 'Republic',
      trackCount: 18,
      parentReleaseSlug: null,
      tracklist: [
        'I Forgot That You Existed',
        'Cruel Summer',
        'Lover',
        'The Man',
        'The Archer',
        'I Think He Knows',
        'Miss Americana & the Heartbreak Prince',
        'Paper Rings',
        'Cornelia Street',
        'Death by a Thousand Cuts',
        'London Boy',
        "Soon You'll Get Better",
        'False God',
        'You Need to Calm Down',
        'Afterglow',
        'ME!',
        "It's Nice to Have a Friend",
        'Daylight',
      ],
      note: 'The first album she has owned outright from day one — her Republic Records debut after leaving Big Machine, and the pastel reset after reputation.',
      sources: [wiki('Lover_(album)', 'Lover (album)')],
    },
    {
      slug: 'folklore',
      eraSlug: 'folklore',
      kind: 'album',
      title: 'folklore',
      releaseDate: '2020-07-24',
      label: 'Republic',
      trackCount: 16,
      parentReleaseSlug: null,
      tracklist: [
        'the 1',
        'cardigan',
        'the last great american dynasty',
        'exile',
        'my tears ricochet',
        'mirrorball',
        'seven',
        'august',
        'this is me trying',
        'illicit affairs',
        'invisible string',
        'mad woman',
        'epiphany',
        'betty',
        'peace',
        'hoax',
      ],
      note: 'The surprise lockdown album, announced 16 hours before release — indie-folk storytelling with Aaron Dessner and Jack Antonoff. Album of the Year Grammy #3.',
      sources: [wiki('Folklore_(Taylor_Swift_album)', 'Folklore (Taylor Swift album)')],
    },
    {
      slug: 'folklore-the-long-pond-studio-sessions',
      eraSlug: 'folklore',
      kind: 'live',
      title: 'folklore: the long pond studio sessions',
      releaseDate: '2020-11-25',
      label: 'Republic',
      trackCount: 17,
      parentReleaseSlug: 'folklore',
      note: 'The stripped live companion to the Disney+ film — folklore performed straight through at Long Pond with Dessner and Antonoff, plus "the lakes".',
      sources: [wiki('Folklore:_The_Long_Pond_Studio_Sessions', 'Folklore: The Long Pond Studio Sessions')],
    },
    {
      slug: 'evermore',
      eraSlug: 'evermore',
      kind: 'album',
      title: 'evermore',
      releaseDate: '2020-12-11',
      label: 'Republic',
      trackCount: 15,
      parentReleaseSlug: null,
      tracklist: [
        'willow',
        'champagne problems',
        'gold rush',
        "'tis the damn season",
        'tolerate it',
        'no body, no crime',
        'happiness',
        'dorothea',
        'coney island',
        'ivy',
        'cowboy like me',
        'long story short',
        'marjorie',
        'closure',
        'evermore',
      ],
      note: "folklore's \"sister album,\" dropped five months later as a second surprise — announced two days before her 31st birthday because 13 is her lucky number backwards.",
      sources: [wiki('Evermore_(Taylor_Swift_album)', 'Evermore (Taylor Swift album)')],
    },
    {
      slug: 'fearless-taylors-version',
      eraSlug: 'evermore',
      kind: 'rerecording',
      title: "Fearless (Taylor's Version)",
      releaseDate: '2021-04-09',
      label: 'Republic',
      trackCount: 26,
      parentReleaseSlug: 'fearless',
      tracklist: [
        'Fearless',
        'Fifteen',
        'Love Story',
        'Hey Stephen',
        'White Horse',
        'You Belong with Me',
        'Breathe',
        'Tell Me Why',
        "You're Not Sorry",
        'The Way I Loved You',
        'Forever & Always',
        'The Best Day',
        'Change',
        'Jump Then Fall',
        'Untouchable',
        'Forever & Always (Piano Version)',
        'Come In with the Rain',
        'Superstar',
        'The Other Side of the Door',
        'Today Was a Fairytale',
        'You All Over Me',
        'Mr. Perfectly Fine',
        'We Were Happy',
        "That's When",
        "Don't You",
        'Bye Bye Baby',
      ],
      note: 'The first re-recording in the masters battle — 26 tracks, including six never-released songs "From the Vault." Proof of concept for the whole project.',
      sources: [wiki('Fearless_(Taylor%27s_Version)', "Fearless (Taylor's Version)")],
    },
    {
      slug: 'red-taylors-version',
      eraSlug: 'evermore',
      kind: 'rerecording',
      title: "Red (Taylor's Version)",
      releaseDate: '2021-11-12',
      label: 'Republic',
      trackCount: 30,
      parentReleaseSlug: 'red',
      tracklist: [
        'State of Grace',
        'Red',
        'Treacherous',
        'I Knew You Were Trouble',
        'All Too Well',
        '22',
        'I Almost Do',
        'We Are Never Ever Getting Back Together',
        'Stay Stay Stay',
        'The Last Time',
        'Holy Ground',
        'Sad Beautiful Tragic',
        'The Lucky One',
        'Everything Has Changed',
        'Starlight',
        'Begin Again',
        'The Moment I Knew',
        'Come Back... Be Here',
        'Girl at Home',
        'State of Grace (Acoustic Version)',
        'Ronan',
        'Better Man',
        'Nothing New',
        'Babe',
        'Message in a Bottle',
        'I Bet You Think About Me',
        'Forever Winter',
        'Run',
        'The Very First Night',
        'All Too Well (10 Minute Version)',
      ],
      note: 'Thirty tracks capped by the ten-minute All Too Well — the version fans spent nine years asking for, which promptly became the longest #1 in Hot 100 history.',
      sources: [wiki('Red_(Taylor%27s_Version)', "Red (Taylor's Version)")],
    },
    {
      slug: 'midnights',
      eraSlug: 'midnights',
      kind: 'album',
      title: 'Midnights',
      releaseDate: '2022-10-21',
      label: 'Republic',
      trackCount: 13,
      parentReleaseSlug: null,
      tracklist: [
        'Lavender Haze',
        'Maroon',
        'Anti-Hero',
        'Snow on the Beach',
        "You're on Your Own, Kid",
        'Midnight Rain',
        'Question...?',
        'Vigilante Shit',
        'Bejeweled',
        'Labyrinth',
        'Karma',
        'Sweet Nothing',
        'Mastermind',
      ],
      note: '"13 sleepless nights" as a concept album — it broke Spotify’s single-day record and made her the first artist to occupy the entire Hot 100 top 10 at once.',
      sources: [wiki('Midnights', 'Midnights')],
    },
    {
      slug: 'midnights-3am-edition',
      eraSlug: 'midnights',
      kind: 'deluxe',
      title: 'Midnights (3am Edition)',
      releaseDate: '2022-10-22',
      label: 'Republic',
      trackCount: 20,
      parentReleaseSlug: 'midnights',
      tracklist: [
        'Lavender Haze',
        'Maroon',
        'Anti-Hero',
        'Snow on the Beach',
        "You're on Your Own, Kid",
        'Midnight Rain',
        'Question...?',
        'Vigilante Shit',
        'Bejeweled',
        'Labyrinth',
        'Karma',
        'Sweet Nothing',
        'Mastermind',
        'The Great War',
        'Bigger Than the Whole Sky',
        'Paris',
        'High Infidelity',
        'Glitch',
        "Would've, Could've, Should've",
        'Dear Reader',
      ],
      note: 'Announced at literally 3am the night of release: seven more songs from the Midnights sessions, "we think of them as this special surprise".',
      sources: [wiki('Midnights', 'Midnights', '3am Edition date + added tracks documented in the album article')],
    },
    {
      slug: 'midnights-the-til-dawn-edition',
      eraSlug: 'midnights',
      kind: 'deluxe',
      title: "Midnights (The Til Dawn Edition)",
      releaseDate: '2023-05-26',
      label: 'Republic',
      trackCount: 23,
      parentReleaseSlug: 'midnights',
      tracklist: [
        'Lavender Haze',
        'Maroon',
        'Anti-Hero',
        'Snow on the Beach',
        "You're on Your Own, Kid",
        'Midnight Rain',
        'Question...?',
        'Vigilante Shit',
        'Bejeweled',
        'Labyrinth',
        'Karma',
        'Sweet Nothing',
        'Mastermind',
        'The Great War',
        'Bigger Than the Whole Sky',
        'Paris',
        'High Infidelity',
        'Glitch',
        "Would've, Could've, Should've",
        'Dear Reader',
        'Hits Different',
        'Snow on the Beach (feat. More Lana Del Rey)',
        'Karma (feat. Ice Spice)',
      ],
      note: 'The Eras-Tour-summer expansion: Hits Different goes streaming-wide, Lana gets a full feature on Snow on the Beach, and Ice Spice joins Karma.',
      sources: [wiki('Midnights', 'Midnights', "Til Dawn Edition date + added tracks documented in the album article")],
    },
    {
      slug: 'speak-now-taylors-version',
      eraSlug: 'midnights',
      kind: 'rerecording',
      title: "Speak Now (Taylor's Version)",
      releaseDate: '2023-07-07',
      label: 'Republic',
      trackCount: 22,
      parentReleaseSlug: 'speak-now',
      tracklist: [
        'Mine',
        'Sparks Fly',
        'Back to December',
        'Speak Now',
        'Dear John',
        'Mean',
        'The Story of Us',
        'Never Grow Up',
        'Enchanted',
        'Better than Revenge',
        'Innocent',
        'Haunted',
        'Last Kiss',
        'Long Live',
        'Ours',
        'Superman',
        'Electric Touch',
        'When Emma Falls in Love',
        'I Can See You',
        'Castles Crumbling',
        'Foolish One',
        'Timeless',
      ],
      note: 'Announced on stage in Nashville mid-Eras-Tour — the all-self-written album returns with vault guests Fall Out Boy and Hayley Williams.',
      sources: [wiki('Speak_Now_(Taylor%27s_Version)', "Speak Now (Taylor's Version)")],
    },
    {
      slug: '1989-taylors-version',
      eraSlug: 'midnights',
      kind: 'rerecording',
      title: "1989 (Taylor's Version)",
      releaseDate: '2023-10-27',
      label: 'Republic',
      trackCount: 21,
      parentReleaseSlug: '1989',
      tracklist: [
        'Welcome to New York',
        'Blank Space',
        'Style',
        'Out of the Woods',
        'All You Had to Do Was Stay',
        'Shake It Off',
        'I Wish You Would',
        'Bad Blood',
        'Wildest Dreams',
        'How You Get the Girl',
        'This Love',
        'I Know Places',
        'Clean',
        'Wonderland',
        'You Are in Love',
        'New Romantics',
        '"Slut!"',
        "Say Don't Go",
        "Now That We Don't Talk",
        'Suburban Legends',
        'Is It Over Now?',
      ],
      note: 'Announced at the final US Eras Tour show of 2023 (8/9, wink) — nine years to the season after the original, with five vault tracks fans decoded via Google puzzles.',
      sources: [wiki('1989_(Taylor%27s_Version)', "1989 (Taylor's Version)")],
    },
    {
      slug: 'the-tortured-poets-department',
      eraSlug: 'tortured-poets',
      kind: 'album',
      title: 'The Tortured Poets Department',
      releaseDate: '2024-04-19',
      label: 'Republic',
      trackCount: 16,
      parentReleaseSlug: null,
      tracklist: [
        'Fortnight',
        'The Tortured Poets Department',
        'My Boy Only Breaks His Favorite Toys',
        'Down Bad',
        'So Long, London',
        'But Daddy I Love Him',
        'Fresh Out the Slammer',
        'Florida!!!',
        'Guilty as Sin?',
        "Who's Afraid of Little Old Me?",
        'I Can Fix Him (No Really I Can)',
        'loml',
        'I Can Do It with a Broken Heart',
        'The Smallest Man Who Ever Lived',
        'The Alchemy',
        'Clara Bow',
      ],
      note: 'Announced from the Grammys stage while winning Album of the Year #4 — the quill-pen breakup opus that became Spotify’s most-streamed album in a single day.',
      sources: [wiki('The_Tortured_Poets_Department', 'The Tortured Poets Department')],
    },
    {
      slug: 'ttpd-the-anthology',
      eraSlug: 'tortured-poets',
      kind: 'deluxe',
      title: 'The Tortured Poets Department: The Anthology',
      releaseDate: '2024-04-19',
      label: 'Republic',
      trackCount: 31,
      parentReleaseSlug: 'the-tortured-poets-department',
      tracklist: [
        'Fortnight',
        'The Tortured Poets Department',
        'My Boy Only Breaks His Favorite Toys',
        'Down Bad',
        'So Long, London',
        'But Daddy I Love Him',
        'Fresh Out the Slammer',
        'Florida!!!',
        'Guilty as Sin?',
        "Who's Afraid of Little Old Me?",
        'I Can Fix Him (No Really I Can)',
        'loml',
        'I Can Do It with a Broken Heart',
        'The Smallest Man Who Ever Lived',
        'The Alchemy',
        'Clara Bow',
        'The Black Dog',
        'imgonnagetyouback',
        'The Albatross',
        'Chloe or Sam or Sophia or Marcus',
        'How Did It End?',
        'So High School',
        'I Hate It Here',
        'thanK you aIMee',
        "I Look in People's Windows",
        'The Prophecy',
        'Cassandra',
        'Peter',
        'The Bolter',
        'Robin',
        'The Manuscript',
      ],
      note: '"It’s a 2am surprise": two hours after release, the 16-track album doubled into a 31-track anthology — "I’ve written so much tortured poetry in the past 2 years".',
      sources: [wiki('The_Tortured_Poets_Department', 'The Tortured Poets Department', 'Anthology drop + added tracks documented in the album article')],
    },
    {
      slug: 'the-life-of-a-showgirl',
      eraSlug: 'the-life-of-a-showgirl',
      kind: 'album',
      title: 'The Life of a Showgirl',
      releaseDate: '2025-10-03',
      label: 'Republic',
      trackCount: 12,
      parentReleaseSlug: null,
      tracklist: [
        'The Fate of Ophelia',
        'Elizabeth Taylor',
        'Opalite',
        'Father Figure',
        'Eldest Daughter',
        'Ruin the Friendship',
        'Actually Romantic',
        'Wi$h Li$t',
        'Wood',
        'CANCELLED!',
        'Honey',
        'The Life of a Showgirl',
      ],
      note: 'Announced on the New Heights podcast in a burst of orange — 12 tracks written mid-Eras-Tour with Max Martin and Shellback, closing with the Sabrina Carpenter title duet.',
      sources: [wiki('The_Life_of_a_Showgirl', 'The Life of a Showgirl')],
    },
  ],
};
