/**
 * Long Live — Community section data, part A of 3 (entries 1-10).
 *
 * Transcribed verbatim from `data/communities.json` (generated_at 2026-08-14,
 * 30 entries, method: "Four parallel platform researchers, then orchestrator merge, dedupe, niche normalisation, single-scale rescoring and independent spot-check. See communities-report.md for per-platform reliability."). Split in three purely for
 * file-length hygiene (300-line guideline) — see communities.ts, which merges
 * all three parts and is the only import surface consumers should use.
 *
 * Never hand-edit an entry here without also updating `data/communities.json`
 * — that file is the source of truth this was generated from.
 */

import type { Community } from './communities';

export const COMMUNITIES_DATA_A: Community[] = [
  {
    name: "r/TaylorSwift (official Discord)",
    platform: "Discord",
    url: "https://discord.gg/taylorswift",
    memberCount: 99146,
    memberCountAsOf: "2026-08-14",
    onlineCount: 9465,
    activityLevel: "Medium",
    activityEvidence: "approximate_presence_count 9465 of 99146 members (9.5%) via invite API",
    description: "The companion Discord to r/TaylorSwift, and the biggest, most established Swiftie server out there. It is Discord-partnered and verified, with the scale to feel like a real town square during album drops and Eras Tour nights.",
    backstory: "Built as the official Discord home for the r/TaylorSwift subreddit community. It carries Discord's PARTNERED and DISCOVERABLE features and a member-verification screening gate (rules acceptance required to enter), which is unusually formal for a fan server and points to active, sustained moderation at scale.",
    niche: "general",
    joinRequirements: "rules screening (Discord MEMBER_VERIFICATION_GATE_ENABLED feature confirmed via invite API; verification_level 3/high)",
    hypeScore: 9,
    verification: {
      status: "verified-live",
      method: "invite API returned guild + counts; vanity_url_code confirmed as taylorswift",
      checkedAt: "2026-08-14",
      orchestratorRecheck: "invite API re-verified by orchestrator 2026-08-14, 0% count drift",
    },
    flags: [],
    recommendedIn: ["https://discord.com/invite/taylorswift", "https://disboard.org/servers/tag/taylor-swift"],
  },
  {
    name: "r/TaylorSwift (subreddit)",
    platform: "Reddit",
    url: "https://www.reddit.com/r/TaylorSwift/",
    memberCount: null,
    memberCountAsOf: null,
    activityLevel: "unknown",
    activityEvidence: "No new.json access; secondary sources describe it as extremely high-traffic (a moderator interview says it grew from 14,000 to nearly 2 million members) but that is not a live post-frequency read.",
    description: "The main hub of the fandom on Reddit: news, photos, video, theory threads, and the megathreads that form the moment Taylor drops anything. If you only join one Swiftie subreddit, this is the one everyone assumes you are already in.",
    backstory: "A moderator named Lydia took it over around 2017 and described the community before her as a very toxic environment. She did a full rules rehaul and hand-picked new moderators, and the sub grew from roughly 14,000 members to nearly 2 million under that stewardship. It has also become an unlikely home for NFL discussion since Taylor started dating Travis Kelce. Posting in support of Gaylor theories or discussing Taylor's sexuality is reportedly a bannable offense here, which is the likely reason spaces like r/SwiftlyNeutral and r/GaylorSwift exist as separate communities.",
    niche: "general",
    joinRequirements: "Open per secondary sources; not independently confirmed",
    hypeScore: 9,
    hypeBasis: "Named and described in 3 independently fetched sources (thehiveindex.com, Rolling Stone AU, a Yahoo/NBC syndicated mod interview) and treated as the default hub across nearly every other search performed for this task.",
    verification: {
      status: "blocked-unverified",
      method: "about.json and new.json both returned HTTP 403 Blocked from Reddit's edge on every attempt. See sources-reddit.md for the full blocker log. All facts here come from secondary sources fetched and quoted directly, not from Reddit's own API.",
      checkedAt: "2026-08-14",
      evidenceUrl: ["https://thehiveindex.com/communities/r-taylorswift/", "https://au.rollingstone.com/music/music-news/taylor-swift-fandom-gaylor-report-exclusive-46481/", "https://www.yahoo.com/entertainment/taylor-swift-subreddit-became-crash-053108842.html"],
    },
    flags: ["Reported member counts vary wildly by source and date (200k, 460k, 1.8M and 3.8M all appeared across different secondary sites during this research); none recorded as fact.", "Reportedly bans pro-Gaylor and sexuality-discussion posts per Rolling Stone AU."],
    recommendedIn: ["https://thehiveindex.com/communities/r-taylorswift/", "https://au.rollingstone.com/music/music-news/taylor-swift-fandom-gaylor-report-exclusive-46481/", "https://www.yahoo.com/entertainment/taylor-swift-subreddit-became-crash-053108842.html"],
  },
  {
    name: "ATRL — Taylor Swift megathread",
    platform: "Forum",
    url: "https://atrl.net/forums/topic/502599-taylor-swift/",
    memberCount: null,
    memberCountAsOf: null,
    activityLevel: "High",
    activityEvidence: "Fetched the threads last page (of 2,335 total): posts ranging from 2 days ago to about 50 minutes before fetch. Thread stats shown on-page: 58.4k replies, 3M views, created April 11, 2022.",
    description: "ATRL is a long-running pop-culture forum, and its single Taylor Swift megathread has become one of the internets most durable running rooms for her fandom, one continuous conversation since 2022, thousands of pages deep. Fans drop in for real-time reactions to everything from haircuts to award-show news.",
    backstory: "ATRL began in 1999 as Absolute TRL, a fansite for MTVs Total Request Live, renamed PopFusion in 2006 and ATRL in 2007 after TRL was cancelled, and it kept going as a general pop-culture debate forum. In 2017 ATRL members were the ones who dug up unreleased Reputation-era artwork and an incomplete tracklist ahead of Taylors own announcement, a genuine scoop that made outside press. The current Taylor megathread (started April 2022) is the direct descendant of that culture: obsessive, stats-driven, and unafraid to call itself out for clowning when a theory does not pan out.",
    niche: "general",
    joinRequirements: "account required to post; readable without an account",
    hypeScore: 8,
    verification: {
      status: "verified-live",
      method: "Fetched https://atrl.net/forums/topic/502599-taylor-swift (thread overview) and page 2335 (last page) directly; confirmed live posting activity and thread metadata.",
      checkedAt: "2026-08-14",
    },
    flags: ["ATRL is a general pop-culture forum, not Swift-exclusive, this is one very large thread within it, and forum-wide tone is blunter and snarkier than fan-only spaces"],
    recommendedIn: [],
  },
  {
    name: "Taylor Swift Fan Club (Discord)",
    platform: "Discord",
    url: "https://discord.gg/taylor-swift-fan-club-1311387776893321337",
    memberCount: 144217,
    memberCountAsOf: "2026-08-14",
    onlineCount: 15867,
    activityLevel: "High",
    activityEvidence: "approximate_presence_count 15867 of 144217 members (11.0%) via invite API",
    description: "The single biggest Taylor Swift server we could verify, and it is upfront that it is fan-run, not official. High raw numbers and a healthy presence ratio, so this is not just a dead number farm.",
    backstory: "Guild description literally reads 'WE ARE NOT AFFILIATED WITH TAYLOR SWIFT' -- a good sign of an honest, non-scammy fan operation rather than an impersonation server. Its long-form vanity URL confirms an active, stable community rather than a throwaway.",
    niche: "general",
    joinRequirements: "Unknown (not visible via invite API without joining)",
    hypeScore: 8,
    verification: {
      status: "verified-live",
      method: "invite API returned guild + counts; long-form vanity_url_code confirmed",
      checkedAt: "2026-08-14",
      orchestratorRecheck: "invite API re-verified by orchestrator 2026-08-14, 0% count drift",
    },
    flags: ["Invite code found in search (qfxP85uSYb) is a random, non-vanity code and could be rotated or revoked -- use the vanity URL above instead, which we confirmed is stable."],
    recommendedIn: ["https://discord.com/invite/qfxP85uSYb"],
  },
  {
    name: "Taylor Swift's Vault",
    platform: "Facebook",
    url: "https://www.facebook.com/groups/2254218764714763/",
    memberCount: 480000,
    memberCountAsOf: "reported as over 480,000 members by Bustle, published 2024-12-13 -- not independently verified, group has likely grown or shrunk since",
    activityLevel: "High",
    activityEvidence: "Bustle (2024-12-13) profiles a member who used the group to vet ticket sellers and reunite fans stranded by the Vienna show cancellation; separate Google-indexed post snippets from the group (not independently fetchable past the login wall) show live threads on vinyl variants, Easter-egg theories, and Any Australian Swifties meetups -- consistent with a large, general-purpose, internationally active group",
    description: "The closest thing this fandom has to a town square on Facebook -- a huge, general Swiftie group where fans trade vinyl variant intel, swap ticket-selling tips, theorize about Easter eggs, and check in on each other during tour chaos. If you only join one Facebook group, third-party coverage suggests this is the one people actually mean when they say the Swiftie Facebook group.",
    backstory: "Came into wider public notice during the Eras Tour era (2023-2024) as a hub for mutual aid among fans -- Bustle reported a 24-year-old member, Olivia Levin, used the group to vet ticket sellers and prevent scams, and to connect fans stranded overseas when the Vienna, Austria shows were cancelled in August 2024 over a terror plot. Members have also used it to make digital Eras yearbooks for each other post-tour.",
    niche: "general",
    joinRequirements: "unknown -- could not confirm past the login wall; Facebook search results show member posts referencing an admin verification process, suggesting request-to-join with some vetting, but this is not confirmed",
    hypeScore: 8,
    verification: {
      status: "third-party-cited",
      method: "Named with member count and detailed activity in a Bustle feature article; group URL and name additionally confirmed live via direct WebFetch (title tag resolved before the login wall, full content blocked)",
      checkedAt: "2026-08-14",
      evidenceUrl: "https://www.bustle.com/entertainment/taylor-swift-eras-tour-helped-us-heal",
    },
    flags: ["A second group calling itself Taylor Swifts Vault 2.0 also exists on Facebook (facebook.com/groups/taylorswiftsvault2/); a post in the original group titled a lot of confusion over whose verified and whose not suggests fans have had trouble telling legitimate admins/spinoffs from impersonators. Unconfirmed beyond that snippet -- flagging so fans double-check they have joined the group they intend to."],
    recommendedIn: ["https://www.bustle.com/entertainment/taylor-swift-eras-tour-helped-us-heal"],
  },
  {
    name: "New Taylor Connect",
    platform: "Forum",
    url: "https://newtaylorconnect.freeforums.net/",
    memberCount: null,
    memberCountAsOf: null,
    activityLevel: "Medium",
    activityEvidence: "Fetched the forum homepage directly: newest visible post dated August 13, 2026 21:29 GMT-5 in General Discussions; Off Topic board alone shows 447 threads.",
    description: "A fan-rebuilt version of Taylors own official fan forum, still running discussion boards on albums, news and off-topic chat in the exact format the original had.",
    backstory: "Taylor Connect was Taylor Swifts own official fan forum, built into taylorswift.com from December 2009, complete with member profiles and perks. Taylors team shut it down on December 1, 2017 to make room for the short-lived Swift Life app. When that closed too, fans stood up New Taylor Connect as an unofficial revival of the format Swift herself had once given them, one of the clearer examples in this fandom of fans rebuilding infrastructure the artists own team abandoned.",
    niche: "history",
    joinRequirements: "account required to post",
    hypeScore: 7,
    verification: {
      status: "verified-live",
      method: "Fetched https://newtaylorconnect.freeforums.net/ directly; corroborated Taylor Connects official history and 2017 closure via web search (theswiftagency.com archive post, Taylor Swift Switzerland wiki).",
      checkedAt: "2026-08-14",
      evidenceUrl: "https://taylorswiftswitzerland.ch/index.php/wiki/taylor-conncect/",
      orchestratorRecheck: "HTTP 406 (bot-block signature, not 404) — exists but could not be independently re-confirmed 2026-08-14",
    },
    flags: [],
    recommendedIn: ["https://forums.feedspot.com/taylor_swift_forums/"],
  },
  {
    name: "r/SwiftlyNeutral",
    platform: "Reddit",
    url: "https://www.reddit.com/r/SwiftlyNeutral/",
    memberCount: null,
    memberCountAsOf: null,
    activityLevel: "unknown",
    activityEvidence: "A third-party stats aggregator (gummysearch.com, fetched directly, not Reddit's own data) described it as active with daily discussion threads and named topics like Showgirl, Lyrics and Album as trending, but this is not a verified post-frequency count.",
    description: "The take-a-breath sub, for fans and skeptics who want to talk about Taylor without the main hub's stricter rules. A music critic covering her documentary called it an invaluable tool for gauging measured fan reaction to her career, which is about the best description there is: this is where you go for the temperature check, not the hype train.",
    backstory: "Positions itself explicitly as neutral ground, a refreshingly normal neutral sub for fans and non-fans to discuss topics about or involving Taylor Swift, where both praise and criticism are allowed. That framing reads as a direct response to the tighter moderation on r/TaylorSwift (see that entry). Could not independently confirm an exact founding story or a formal split event; that framing is inferred from how the two subs are described relative to each other, not stated outright by either source.",
    niche: "neutral-critical",
    joinRequirements: "Unknown",
    hypeScore: 7,
    hypeBasis: "Named and described in 2 independently fetched sources (gummysearch.com, theneedledrop.com), one of them a music-criticism outlet treating it as a genuine barometer of fan opinion.",
    verification: {
      status: "blocked-unverified",
      method: "about.json/new.json blocked identically to every other entry; see sources-reddit.md. Facts here from 2 fetched secondary sources only.",
      checkedAt: "2026-08-14",
      evidenceUrl: ["https://gummysearch.com/r/SwiftlyNeutral/", "https://theneedledrop.com/opinion/miniseries-review-taylor-swifts-the-end-of-an-era/"],
    },
    flags: [],
    recommendedIn: ["https://gummysearch.com/r/SwiftlyNeutral/", "https://theneedledrop.com/opinion/miniseries-review-taylor-swifts-the-end-of-an-era/"],
  },
  {
    name: "Swifties Want Tickets",
    platform: "Discord",
    url: "https://discord.gg/swiftieswanttickets",
    memberCount: 65838,
    memberCountAsOf: "2026-08-14",
    onlineCount: 1322,
    activityLevel: "Low",
    activityEvidence: "approximate_presence_count 1322 of 65838 members (2.0%) via invite API -- low idle presence is expected for a utility server people join for ticket drops, not day-to-day chat",
    description: "Not a hangout server, a mutual-aid ticket desk. Fans here help each other snag face-value Eras Tour (and other pop-tour) tickets and have a volunteer team that checks screenshots around the clock to catch fake listings before someone gets scammed.",
    backstory: "Covers ticket coordination beyond just Taylor (also Olivia Rodrigo, Adele, etc.), but Swift shows are its bread and butter. The low online-to-member ratio fits its use case: most members are lurking, waiting for a drop alert, not chatting.",
    niche: "tickets",
    joinRequirements: "Unknown (not visible via invite API without joining)",
    hypeScore: 7,
    verification: {
      status: "verified-live",
      method: "invite API returned guild + counts; vanity_url_code confirmed as swiftieswanttickets",
      checkedAt: "2026-08-14",
      orchestratorRecheck: "invite API re-verified by orchestrator 2026-08-14, 0% count drift",
    },
    flags: ["High verification_level (4) on the guild suggests phone-verification is required to join -- worth knowing before recommending to a casual fan."],
    recommendedIn: ["https://discord.com/invite/swiftieswanttickets"],
  },
  {
    name: "Taylor Swift (discord.gg/taylor)",
    platform: "Discord",
    url: "https://discord.gg/taylor",
    memberCount: 37792,
    memberCountAsOf: "2026-08-14",
    onlineCount: 4201,
    activityLevel: "High",
    activityEvidence: "approximate_presence_count 4201 of 37792 members (11.1%) via invite API",
    description: "A general-purpose Taylor Swift fan hub that punches above its member count on activity -- one of the highest presence ratios of any server we verified. Good middle-ground pick if the biggest servers feel too chaotic.",
    backstory: "Holds the short, one-word vanity 'taylor' -- Discord only grants that to servers with sustained boost levels, so this has been actively maintained and funded by its community for a while. No specific founding date could be verified.",
    niche: "general",
    joinRequirements: "Unknown (not visible via invite API without joining)",
    hypeScore: 7,
    verification: {
      status: "verified-live",
      method: "invite API returned guild + counts; vanity_url_code confirmed as taylor",
      checkedAt: "2026-08-14",
      orchestratorRecheck: "invite API re-verified by orchestrator 2026-08-14, 0% count drift",
    },
    flags: [],
    recommendedIn: ["https://discord.com/invite/taylor", "https://disboard.org/servers/tag/taylor"],
  },
  {
    name: "BuzzJack — Taylor Swift forum",
    platform: "Forum",
    url: "https://buzzjack.com/forums/Taylor-Swift-f177.html",
    memberCount: null,
    memberCountAsOf: null,
    activityLevel: "High",
    activityEvidence: "Fetched the subforum directly: posts visible from 3-5 hours before fetch; 1,010 topics across 41 pages; top threads showing 911 replies and 303.2k views, and 500 replies and 32k views; active threads on The Life of a Showgirl and certification milestones.",
    description: "BuzzJack is a UK chart-and-pop-music forum (the wider site has 1.6M-plus posts in its chart-tracking sections), and its Taylor subforum is one of the busiest artist boards on the site, daily new posts, deep chart-nerd analysis alongside plain fan chat.",
    backstory: "BuzzJack grew out of the UKs obsessive singles-chart-watching culture, the kind of forum where posters track first-week sales projections the way sports fans track box scores. Taylors subforum inherited that intensity: threads mix pure fan enthusiasm with hardcore chart and certification tracking, a different flavor of superfan than most US-centric spaces.",
    niche: "general",
    joinRequirements: "account required to post; readable without an account",
    hypeScore: 6,
    verification: {
      status: "verified-live",
      method: "Fetched https://buzzjack.com/forums/Taylor-Swift-f177.html directly.",
      checkedAt: "2026-08-14",
    },
    flags: [],
    recommendedIn: ["https://forums.feedspot.com/taylor_swift_forums/"],
  },
];
