/**
 * Long Live — Community section data, part C of 3 (entries 21-30).
 *
 * Transcribed verbatim from `data/communities.json` (generated_at 2026-08-14,
 * 30 entries, method: "Four parallel platform researchers, then orchestrator merge, dedupe, niche normalisation, single-scale rescoring and independent spot-check. See communities-report.md for per-platform reliability."). Split in three purely for
 * file-length hygiene (300-line guideline) — see communities.ts, which merges
 * all three parts and is the only import surface consumers should use.
 *
 * Never hand-edit an entry here without also updating `data/communities.json`
 * — that file is the source of truth this was generated from.
 */

import type { Community } from './communities';

export const COMMUNITIES_DATA_C: Community[] = [
  {
    name: "ｓｗｉｆｔｃｏｒｄ",
    platform: "Discord",
    url: "https://discord.gg/swiftcord",
    memberCount: 4555,
    memberCountAsOf: "2026-08-14",
    onlineCount: 375,
    activityLevel: "Medium",
    activityEvidence: "approximate_presence_count 375 of 4555 members (8.2%) via invite API",
    description: "A cozy, close-knit Swiftie server that describes itself as exactly that -- a close community rather than a mega-hangout. Good pick for fans who find the huge servers impersonal.",
    backstory: "No specific founding story verified. Holds the short 'swiftcord' vanity, indicating an established, community-funded server rather than a fresh startup.",
    niche: "general",
    joinRequirements: "Unknown (not visible via invite API without joining)",
    hypeScore: 4,
    verification: {
      status: "verified-live",
      method: "invite API returned guild + counts; vanity_url_code confirmed as swiftcord",
      checkedAt: "2026-08-14",
      orchestratorRecheck: "invite API re-verified by orchestrator 2026-08-14, 0% count drift",
    },
    flags: [],
    recommendedIn: ["https://discord.com/invite/swiftcord"],
  },
  {
    name: "Swiftie Super Worldwide Friendship Bracelet Trade",
    platform: "Facebook",
    url: "https://www.facebook.com/groups/1404884973507150/",
    memberCount: null,
    memberCountAsOf: "not reported by any source found",
    activityLevel: "unknown",
    activityEvidence: "not verifiable -- login wall",
    description: "A worldwide-facing bracelet-trading group -- for Swifties who want to trade beaded bracelets with fans outside their own country/region, not just at a local show.",
    backstory: "Part of the same Eras Tour friendship-bracelet trend as the other trading groups; the worldwide framing in the name points to international mail-trading rather than in-person swaps only, per general coverage of the trend (Today.com, Capital FM) but this specific groups founding story is not documented anywhere found.",
    niche: "bracelets",
    joinRequirements: "unknown -- could not confirm past the login wall",
    hypeScore: 4,
    verification: {
      status: "verified-live",
      method: "Direct WebFetch on the group URL returned the groups full name/title before hitting the login wall (member count and post content blocked)",
      checkedAt: "2026-08-14",
      evidenceUrl: "https://www.facebook.com/groups/1404884973507150/",
    },
    flags: [],
    recommendedIn: [],
  },
  {
    name: "Swifties ♡",
    platform: "Discord",
    url: "https://discord.gg/swifties-805215468734382111",
    memberCount: 4807,
    memberCountAsOf: "2026-08-14",
    onlineCount: 306,
    activityLevel: "Medium",
    activityEvidence: "approximate_presence_count 306 of 4807 members (6.4%) via invite API",
    description: "A friendly, mid-size general Swiftie server that describes itself plainly as a place for fun times and great conversation. No frills, just a steady hangout.",
    backstory: "No public founding story verified. Confirmed live via its long-form vanity URL, which is more durable than the short random invite code found in search results.",
    niche: "general",
    joinRequirements: "Unknown (not visible via invite API without joining)",
    hypeScore: 4,
    verification: {
      status: "verified-live",
      method: "invite API returned guild + counts; long-form vanity_url_code confirmed as swifties-805215468734382111",
      checkedAt: "2026-08-14",
      orchestratorRecheck: "invite API re-verified by orchestrator 2026-08-14, 0% count drift",
    },
    flags: ["Invite code originally found in search (nVmJbsFEsn) is a random, non-vanity code -- use the vanity URL above, which we confirmed is stable."],
    recommendedIn: ["https://discord.com/invite/nVmJbsFEsn"],
  },
  {
    name: "Taylor Swift Daily",
    platform: "Tumblr",
    url: "https://www.tumblr.com/taylorswiftdaily",
    memberCount: null,
    memberCountAsOf: null,
    activityLevel: "Medium",
    activityEvidence: "Fetched the blog directly and confirmed it is a live, populated fan blog with an active reblog culture (contributors tag edits with usertaylorswiftdaily for consideration) and recent-era content (Eras Tour finale material visible); could not pin an exact latest post date and timestamp from the fetch, so activity level here is a conservative estimate rather than a confirmed daily cadence.",
    description: "A classic Tumblr fan-blog-as-news-hub: news, photos, video and fan edits, explicitly unofficial (we are NOT taylor swift), built around a submission and reblog culture rather than original writing.",
    backstory: "Represents the still-alive Tumblr tradition of the daily fanblog, curators who reblog and credit fan edits rather than post original content, keeping the old edit-and-reblog culture from Tumblrs 2012-2016 Swiftie peak going.",
    niche: "general",
    joinRequirements: "Open",
    hypeScore: 4,
    verification: {
      status: "verified-live",
      method: "Fetched https://www.tumblr.com/taylorswiftdaily directly; could not confirm an exact recent timestamp within the fetched view.",
      checkedAt: "2026-08-14",
    },
    flags: ["Exact posting recency could not be pinned down precisely, treat activity_level here as a lower-confidence estimate"],
    recommendedIn: [],
  },
  {
    name: "Taylor Swift Updates",
    platform: "Discord",
    url: "https://discord.gg/tsnotifs",
    memberCount: 12998,
    memberCountAsOf: "2026-08-14",
    onlineCount: 715,
    activityLevel: "Medium",
    activityEvidence: "approximate_presence_count 715 of 12998 members (5.5%) via invite API",
    description: "A news-first server: think of it as a Taylor Swift newsroom with a chat attached. Good for fans who mainly want fast, reliable updates without wading through general chat noise.",
    backstory: "No public founding story verified. Holds the 'tsnotifs' vanity, matching its update-focused identity.",
    niche: "merch",
    joinRequirements: "Unknown (not visible via invite API without joining)",
    hypeScore: 4,
    verification: {
      status: "verified-live",
      method: "invite API returned guild + counts; vanity_url_code confirmed as tsnotifs",
      checkedAt: "2026-08-14",
      orchestratorRecheck: "invite API re-verified by orchestrator 2026-08-14, 0% count drift",
    },
    flags: [],
    recommendedIn: ["https://discord.com/invite/xfw4mAJR6j", "https://discord.com/invite/tsnotifs"],
  },
  {
    name: "Karlie Kloss/Taylor Swift",
    platform: "AO3",
    url: "https://archiveofourown.org/tags/Karlie%20Kloss*s*Taylor%20Swift/works",
    memberCount: null,
    memberCountAsOf: null,
    activityLevel: "Low",
    activityEvidence: "Could not fetch AO3 directly (403 to automated fetches). Confirmed the tag is real via search engine indexing (exact-title match). Related fic hubs on Wattpad (fic lists such as Maybe the biggest Kaylor fic list, and Kaylor Fanfics) and a dedicated Tumblr archive (kaylorfanfiction.tumblr.com) corroborate an ongoing, if niche, writing community, though the Tumblr archive itself shows no recent update dates and appears dormant.",
    description: "The relationship tag for Kaylor fic, fans writing Taylor Swift and Karlie Kloss into romantic fiction, independent of whether the real-life relationship theory is true.",
    backstory: "Kaylor is the shipping name that gave rise to the broader Gaylor theory culture (see Tales of Kaylor above); the fanfic side of it persisted even after Klosss 2018 marriage, including Kaylor: The Timeline, a Wattpad fic that got real media coverage (Cosmopolitan, BuzzFeed) and a Wattpad Star distinction, a rare case of shipping fanfic crossing into mainstream press coverage.",
    niche: "fanfic",
    joinRequirements: "Open (account required to post or comment, not to read)",
    hypeScore: 3,
    verification: {
      status: "third-party-cited",
      method: "Direct WebFetch to archiveofourown.org returned HTTP 403. Verified tag existence via search engine indexing of the exact page title, and corroborated the surrounding Kaylor-fic ecosystem via Wattpad list pages and kaylorfanfiction.tumblr.com (fetched directly, confirmed real but currently showing no recent activity).",
      checkedAt: "2026-08-14",
      evidenceUrl: "https://kaylorfanfiction.tumblr.com/timeline",
    },
    flags: ["Same real-person-shipping sensitivity as the Kaylor and Gaylor theory community above", "Could not confirm current (last-60-day) posting activity on the AO3 tag itself"],
    recommendedIn: [],
  },
  {
    name: "SimilarWorlds — Taylor Swift group",
    platform: "Forum",
    url: "https://similarworlds.com/music/taylor-swift",
    memberCount: 309,
    memberCountAsOf: "2026-08-14",
    activityLevel: "High",
    activityEvidence: "Fetched directly: 309 people following; newest visible post 16 hours before fetch (Ready For It discussion), others at 2 days and 6 days, steady daily-ish posting.",
    description: "A small but genuinely lively discussion group inside SimilarWorlds (a general interpersonal-topics site), where fans post open questions and short takes on Taylors music, her relationship with Travis Kelce, and general fandom chatter.",
    backstory: "Less a dedicated fansite than a topic-room inside a much bigger general discussion platform, an example of Swiftie conversation surfacing organically inside spaces that are not built for fandom at all.",
    niche: "general",
    joinRequirements: "account required to post",
    hypeScore: 3,
    verification: {
      status: "verified-live",
      method: "Fetched https://similarworlds.com/music/taylor-swift directly.",
      checkedAt: "2026-08-14",
    },
    flags: ["Hosted on a general discussion and relationships site, not a Swift-specific platform, expect non-fandom content nearby"],
    recommendedIn: [],
  },
  {
    name: "Taylor Swift Friendship Bracelets: (Buy / Sell / Trade)",
    platform: "Facebook",
    url: "https://www.facebook.com/groups/1220925938596348/",
    memberCount: null,
    memberCountAsOf: "not reported by any source found",
    activityLevel: "unknown",
    activityEvidence: "not verifiable -- login wall; WebFetch on this specific URL did not return even a title, so evidence rests on the search listing alone",
    description: "A bracelet-trading group that, unlike some others in this niche, explicitly allows buying and selling as well as trading -- worth knowing going in, since some bracelet groups ban sales outright.",
    backstory: "Surfaced in the same search cluster as the other Eras Tour friendship-bracelet trading groups; no independent article or forum post was found describing this specific groups history.",
    niche: "bracelets",
    joinRequirements: "unknown",
    hypeScore: 3,
    verification: {
      status: "listed-only",
      method: "Group name and URL appeared in Facebooks own indexed search results for friendship-bracelet trading groups; direct WebFetch of the URL did not return usable content (login wall gave no title this time), so this rests on the search listing only -- weakest tier of evidence in this file",
      checkedAt: "2026-08-14",
      evidenceUrl: "https://m.facebook.com/groups/1220925938596348/",
    },
    flags: ["Weakest-evidence entry in this file -- could not confirm the group is live/active beyond its appearance in a search result listing"],
    recommendedIn: [],
  },
  {
    name: "TBN (Taylor Boards)",
    platform: "Forum",
    url: "https://taylor.boards.net/",
    memberCount: 600,
    memberCountAsOf: "2026-08-14",
    activityLevel: "Low",
    activityEvidence: "Fetched the forum directly: 600 total members, 4,076 threads, 67,303 posts; latest post dated August 7, 2026. Shoutbox shows members asking is anyone still alive on here, and admins citing personal circumstances for reduced updates.",
    description: "A small, self-described moderated safe haven for swifties, protected by unicorns and the itty bitty pretty kitty committee, organized around per-album boards, merch and CD-collector trading, and forum games. Once busier, now a quieter core of regulars still checking in.",
    backstory: "The kind of mid-2010s-era Swiftie forum that had its own in-jokes and a dedicated CD-collector culture (some boards are restricted to verified collectors). It is visibly past its peak, but it has not gone dark, there is still a real, small, named community keeping the lights on rather than a dead shell.",
    niche: "history",
    joinRequirements: "account required to post",
    hypeScore: 3,
    verification: {
      status: "verified-live",
      method: "Fetched https://taylor.boards.net/ directly.",
      checkedAt: "2026-08-14",
      orchestratorRecheck: "HTTP 406 (bot-block signature, not 404) — exists but could not be independently re-confirmed 2026-08-14",
    },
    flags: ["Activity has visibly declined; admins have noted personal circumstances limiting updates, worth knowing before pointing fans somewhere quiet"],
    recommendedIn: ["https://forums.feedspot.com/taylor_swift_forums/"],
  },
  {
    name: "twitter swifties",
    platform: "Discord",
    url: "https://discord.gg/zaSXCfpzcF",
    memberCount: 2577,
    memberCountAsOf: "2026-08-14",
    onlineCount: 96,
    activityLevel: "Low",
    activityEvidence: "approximate_presence_count 96 of 2577 members (3.7%) via invite API",
    description: "A small crossover community for Swifties who mainly hang out on X/Twitter, built as a Discord extension of that scene. Its own description also mentions it runs a Minecraft SMP on the side, so expect a more casual, tangent-friendly vibe than the news-focused servers.",
    backstory: "Self-described as a Discord server for swifties, by swifties, positioning itself as community-run rather than a directory placeholder.",
    niche: "general",
    joinRequirements: "Unknown (not visible via invite API without joining)",
    hypeScore: 3,
    verification: {
      status: "verified-live",
      method: "invite API returned guild + counts; guild has no vanity_url_code (null) -- this is a plain, non-vanity invite",
      checkedAt: "2026-08-14",
      orchestratorRecheck: "invite API re-verified by orchestrator 2026-08-14, 0% count drift",
    },
    flags: ["No vanity URL on this guild -- the invite code is a plain random string and carries real risk of expiring or being regenerated. Check before publishing and re-verify periodically.", "Lowest presence ratio of the verified set (3.7%) -- treat activity_level as a soft signal, not a guarantee."],
    recommendedIn: ["https://discord.com/invite/zaSXCfpzcF"],
  },
];
