/**
 * Long Live — Community section data, part B of 3 (entries 11-20).
 *
 * Transcribed verbatim from `data/communities.json` (generated_at 2026-08-14,
 * 30 entries, method: "Four parallel platform researchers, then orchestrator merge, dedupe, niche normalisation, single-scale rescoring and independent spot-check. See communities-report.md for per-platform reliability."). Split in three purely for
 * file-length hygiene (300-line guideline) — see communities.ts, which merges
 * all three parts and is the only import surface consumers should use.
 *
 * Never hand-edit an entry here without also updating `data/communities.json`
 * — that file is the source of truth this was generated from.
 */

import type { Community } from './communities';

export const COMMUNITIES_DATA_B: Community[] = [
  {
    name: "Tales of Kaylor",
    platform: "Tumblr",
    url: "https://www.tumblr.com/tales-of-kaylor",
    memberCount: null,
    memberCountAsOf: null,
    activityLevel: "High",
    activityEvidence: "Fetched the blog directly: most recent post dated August 8, 2026; multiple posts per week visible, mostly reblogged news plus original analysis.",
    description: "A Kaylor and Gaylor blog run by a fan with a self-described PR background, picking apart celebrity-media strategy and reading Taylors public choices through a this-industry-defaults-to-straight-until-proven-otherwise lens. Bio: Fighting to burst this heteronormative bubble.",
    backstory: "Part of Tumblrs Gaylor tradition, the theory that Taylor has signaled queerness throughout her work, which traces back to blogs in the early 2010s speculating about Dianna Agron (sparked by a Red liner-note thank-you) and grew into the much larger Kaylor (Karlie Kloss) shipping culture from 2014 on, documented in detail by Tumblr user thoughts-reasons in a 2017 timeline post. It is one of the fandoms most persistent theory subcultures, openly acknowledged and often mocked even as Taylors public relationships have continued.",
    niche: "theories",
    joinRequirements: "Open",
    hypeScore: 6,
    verification: {
      status: "verified-live",
      method: "Fetched https://www.tumblr.com/tales-of-kaylor directly.",
      checkedAt: "2026-08-14",
    },
    flags: ["Gaylor and Kaylor content speculates about Taylor Swifts real-life sexuality without her confirmation, some fans find this genre invasive, flag before recommending"],
    recommendedIn: [],
  },
  {
    name: "Based on a Taylor Swift Song",
    platform: "AO3",
    url: "https://archiveofourown.org/tags/Based%20on%20a%20Taylor%20Swift%20Song/works",
    memberCount: null,
    memberCountAsOf: null,
    activityLevel: "Medium",
    activityEvidence: "Could not fetch AO3 directly (site returns 403 to automated fetches). Confirmed the tag is real and indexed via search engine (exact-title match: Based on a Taylor Swift Song - Works - Archive of Our Own) and via a secondary summary citing Fanlores count of 8,000-plus works under this tag as of March 2025.",
    description: "AO3s freeform tag for fic explicitly built around a specific Taylor Swift song, an entire wing of the archives transformative-fic culture organized by album era and lyric rather than by fandom pairing.",
    backstory: "This is the songfic tradition at fandom scale: instead of writing about Taylor herself, writers use her songs as prompts for completely unrelated fandoms and originals, a distinct and under-noticed way her music has seeded other creative communities.",
    niche: "fanfic",
    joinRequirements: "Open (account required to post or comment, not to read)",
    hypeScore: 5,
    verification: {
      status: "third-party-cited",
      method: "Direct WebFetch to archiveofourown.org returned HTTP 403 (bot-blocked). Verified the tags existence via web search engine indexing of the exact page title, and cited a source referencing Fanlores 8,000-plus-works figure.",
      checkedAt: "2026-08-14",
      evidenceUrl: "https://fanlore.org/wiki/Taylor_Swift",
    },
    flags: ["Work count (8,000-plus) is from March 2025 per the citing source, not independently re-verified live"],
    recommendedIn: [],
  },
  {
    name: "Kulto ni TAYLOR SWIFT",
    platform: "Facebook",
    url: "https://www.facebook.com/groups/557483725146375/",
    memberCount: null,
    memberCountAsOf: "not reported by any source found",
    activityLevel: "Medium",
    activityEvidence: "Philippine Star (philstar.com, 2023-04-28) describes it as a group where Filipino Swifties post Taylor-related content and organized around lobbying for a Philippine stop on the Eras Tour; not independently verifiable past the login wall",
    description: "A Filipino Swiftie group built on inside jokes and local flavor -- expect memes that only make sense if you are Pinoy, plus organizing energy (this group was part of the push to bring the Eras Tour to the Philippines).",
    backstory: "Covered by Philippine Star (The Freeman) in April 2023 in a piece on how a Pinoy Swiftie lobbied for a Philippine stop on the Eras Tour; the group was described as a space for Filipino fans to post Taylor content with inside jokes related to Filipino memes that other non-Filipino Swifties might not understand.",
    niche: "regional",
    joinRequirements: "unknown -- could not confirm past the login wall",
    hypeScore: 5,
    verification: {
      status: "third-party-cited",
      method: "Named and described (without URL) in a Philippine Star news article; matching group name and URL located via web search of Googles index of the groups public post titles",
      checkedAt: "2026-08-14",
      evidenceUrl: "https://www.philstar.com/the-freeman/cebu-entertainment/2023/04/28/2262265/how-pinoy-swiftie-lobbied-ph-stop-taylor-swifts-eras-tour",
    },
    flags: [],
    recommendedIn: ["https://www.philstar.com/the-freeman/cebu-entertainment/2023/04/28/2262265/how-pinoy-swiftie-lobbied-ph-stop-taylor-swifts-eras-tour"],
  },
  {
    name: "r/GaylorSwift",
    platform: "Reddit",
    url: "https://www.reddit.com/r/GaylorSwift/",
    memberCount: null,
    memberCountAsOf: null,
    activityLevel: "unknown",
    activityEvidence: "Not independently checkable. Secondary sources describe strong historical growth, under 1,000 members to over 50,000 since 2020, but that is not a current activity read.",
    description: "The home of Gaylor theorizing: fans who read Taylor's lyrics, videos and public appearances for what they interpret as hints about her sexuality. Per the sources found, it has grown into more than theory-crafting; it is described as functioning as a genuine support and connection space for queer women in the fandom, not only a speculation board.",
    backstory: "Gaylor theory itself reportedly predates the subreddit by close to 20 years, but the subreddit's own growth accelerated hard alongside the Eras Tour, going from under 1,000 to over 50,000 members since 2020. Important: per Wikipedia's Gaylor conspiracy theory article, moderators set the subreddit to private in August 2025, around Taylor's engagement announcement, specifically to avoid trolling from outsiders. That means this entry may currently be closed to new members; its status could not be re-checked given the network blocker, so treat open versus private as unresolved rather than assume either way.",
    niche: "theories",
    joinRequirements: "Unclear; reported to have gone private at least once in Aug 2025, current status unconfirmed",
    hypeScore: 5,
    hypeBasis: "Named and described in 2 independently fetched sources (spitfirenews.com, Wikipedia's Gaylor conspiracy theory article). Held below r/SwiftlyNeutral because of the unresolved private-access flag; a sub fans cannot currently join scores lower on a discovery basis even if historically well-recommended.",
    verification: {
      status: "blocked-unverified",
      method: "about.json/new.json blocked identically to every other entry; see sources-reddit.md. Facts here from 2 fetched secondary sources only.",
      checkedAt: "2026-08-14",
      evidenceUrl: ["https://spitfirenews.com/p/gaylor-subreddit-taylor-swift-gay", "https://en.wikipedia.org/wiki/Gaylor_conspiracy_theory"],
    },
    flags: ["Reported to have gone private in Aug 2025 per Wikipedia; could not confirm current open/closed status. Do not present as guaranteed-joinable without re-checking."],
    recommendedIn: ["https://spitfirenews.com/p/gaylor-subreddit-taylor-swift-gay", "https://en.wikipedia.org/wiki/Gaylor_conspiracy_theory"],
  },
  {
    name: "Swifties",
    platform: "Discord",
    url: "https://discord.gg/swifties",
    memberCount: 16565,
    memberCountAsOf: "2026-08-14",
    onlineCount: 1115,
    activityLevel: "Medium",
    activityEvidence: "approximate_presence_count 1115 of 16565 members (6.7%) via invite API",
    description: "A solid mid-size general Swiftie hangout holding the short 'swifties' vanity. Good option for fans who want something smaller than the mega-servers but still consistently active.",
    backstory: "No public founding story surfaced in search results -- we could not verify when it started or any notable moments, only that it is live, moderately active, and has held its vanity long enough to keep it.",
    niche: "general",
    joinRequirements: "Unknown (not visible via invite API without joining)",
    hypeScore: 5,
    verification: {
      status: "verified-live",
      method: "invite API returned guild + counts; vanity_url_code confirmed as swifties",
      checkedAt: "2026-08-14",
      orchestratorRecheck: "invite API re-verified by orchestrator 2026-08-14, 0% count drift",
    },
    flags: ["Name is generic -- easy to confuse with the separate server Swifties Heart also in this list; these are two different guilds."],
    recommendedIn: ["https://discord.com/invite/swifties"],
  },
  {
    name: "Taylor Swift Fan Club (Steam)",
    platform: "Steam",
    url: "https://steamcommunity.com/groups/tswiftfans",
    memberCount: 5374,
    memberCountAsOf: "2026-08-14",
    activityLevel: "Medium",
    activityEvidence: "Fetched directly: 5,374 members, self-described largest Taylor Swift group on Steam; 1,096 members online and 530 in the group chat room at fetch time; most recent formal announcement post dated November 18, 2025; member comments visible through mid-2025.",
    description: "A Taylor Swift fan group living inside the gaming platform Steam, of all places, with a genuinely large membership and a live chat room where gamers who are also Swifties hang out.",
    backstory: "One of the more surprising discoveries here: Swiftie community does not only live on fan platforms, it colonizes wherever fans already gather, including a PC gaming storefronts group-chat feature. It is its own little corner of the fandom that general Swiftie-community lists never mention.",
    niche: "general",
    joinRequirements: "Open (Steam account required)",
    hypeScore: 5,
    verification: {
      status: "verified-live",
      method: "Fetched https://steamcommunity.com/groups/tswiftfans directly.",
      checkedAt: "2026-08-14",
    },
    flags: ["Formal announcement posts are dated (Nov 2025); ongoing life of the group is mainly visible through its live chat room and online member count rather than fresh discussion posts"],
    recommendedIn: [],
  },
  {
    name: "Taylor Swift Friendship Bracelet Making and Trading (NO SALES)",
    platform: "Facebook",
    url: "https://www.facebook.com/groups/959997728506267/",
    memberCount: null,
    memberCountAsOf: "not reported by any source found",
    activityLevel: "unknown",
    activityEvidence: "not verifiable -- login wall; the groups own name (confirmed live via direct fetch) states it is strictly for making/trading bracelets and explicitly bans sales",
    description: "Exactly what it sounds like: a crafting-and-swapping space for the You are On Your Own, Kid beaded-bracelet tradition that took over the Eras Tour, with a hard no-sales rule to keep it about trading, not reselling.",
    backstory: "Part of the wider friendship-bracelet-trading wave documented by Today.com, Capital FM and others as an Eras Tour phenomenon inspired by the Midnights lyric so make the friendship bracelets; this particular group formalizes the no-commerce norm that many bracelet traders informally follow.",
    niche: "bracelets",
    joinRequirements: "unknown -- could not confirm past the login wall",
    hypeScore: 5,
    verification: {
      status: "verified-live",
      method: "Direct WebFetch on the group URL returned the groups full name/title before hitting the login wall (member count and post content blocked)",
      checkedAt: "2026-08-14",
      evidenceUrl: "https://www.facebook.com/groups/959997728506267/",
    },
    flags: [],
    recommendedIn: [],
  },
  {
    name: "Taylor Swift Store Updates",
    platform: "Discord",
    url: "https://discord.gg/merchbot",
    memberCount: 43532,
    memberCountAsOf: "2026-08-14",
    onlineCount: 2770,
    activityLevel: "Medium",
    activityEvidence: "approximate_presence_count 2770 of 43532 members (6.4%) via invite API",
    description: "Less a hangout, more a restock alarm: a server dedicated to flagging changes on the official Taylor Swift store the moment they happen -- new merch drops, price changes, sellouts. Genuinely useful, not a scam front.",
    backstory: "Description is explicit and narrow: 'providing updates about changes in merchandise.' We checked this carefully against the exclude-merch-scam rule -- it reads as a legitimate alert/bot server, not a front selling anything itself, so we kept it but flagged the distinction below.",
    niche: "merch",
    joinRequirements: "Unknown (not visible via invite API without joining)",
    hypeScore: 5,
    verification: {
      status: "verified-live",
      method: "invite API returned guild + counts; vanity_url_code confirmed as merchbot",
      checkedAt: "2026-08-14",
      orchestratorRecheck: "invite API re-verified by orchestrator 2026-08-14, 0% count drift",
    },
    flags: ["Utility/alert server, not really a discussion community -- flag this distinction to users expecting a hangout."],
    recommendedIn: ["https://discord.com/invite/merchbot"],
  },
  {
    name: "taylorswift (story tag)",
    platform: "Wattpad",
    url: "https://www.wattpad.com/stories/taylorswift/hot?locale=en_US",
    memberCount: null,
    memberCountAsOf: null,
    activityLevel: "High",
    activityEvidence: "Fetched directly: 1.2K stories tagged taylorswift; several stories show start dates in 2025-2026; top story (Taylor Swift Imagines, book seven, gxg) at 38,663 reads, with newer entries and only a handful of chapters posted so far.",
    description: "Wattpads living hub of Taylor Swift fanfiction, imagines, celebrity AUs, and relationship fic (Tayvis especially) updated continuously by a large, mostly teen and young-adult writer base.",
    backstory: "Wattpad fanfic culture around Taylor has run continuously since the 1989 era, evolving with whatever real-life relationship is current (Joe Alwyn-era fic gave way to Tayvis fic almost overnight after the Kelce relationship went public), a good barometer of what the fandoms collective imagination is doing with her life in real time.",
    niche: "fanfic",
    joinRequirements: "Open",
    hypeScore: 5,
    verification: {
      status: "verified-live",
      method: "Fetched https://www.wattpad.com/stories/taylorswift/hot?locale=en_US directly.",
      checkedAt: "2026-08-14",
    },
    flags: ["Some stories contain mature and adult themes and warnings; not curated or age-gated by fandom moderators"],
    recommendedIn: [],
  },
  {
    name: "The Swift Hub",
    platform: "Discord",
    url: "https://discord.gg/swiftie",
    memberCount: 2706,
    memberCountAsOf: "2026-08-14",
    onlineCount: 341,
    activityLevel: "High",
    activityEvidence: "approximate_presence_count 341 of 2706 members (12.6%) via invite API",
    description: "A smaller, tight-knit server built around collectible era and aesthetic tags and Easter-egg theorizing -- its own description name-checks both lyric theories and era obsession. The guild's self-description is in Portuguese, so it leans toward a Brazilian and Portuguese-speaking crowd, though it welcomes English speakers.",
    backstory: "Holds the short, highly-contested 'swiftie' vanity, which takes sustained community investment to keep -- a decent signal of an actively engaged, not-dormant server despite its smaller size.",
    niche: "theories",
    joinRequirements: "High verification_level (4) on the guild -- likely phone-verification required",
    hypeScore: 5,
    verification: {
      status: "verified-live",
      method: "invite API returned guild + counts; vanity_url_code confirmed as swiftie",
      checkedAt: "2026-08-14",
      orchestratorRecheck: "invite API re-verified by orchestrator 2026-08-14, 0% count drift",
    },
    flags: ["Primary language in the server's own description is Portuguese -- flag for English-only users."],
    recommendedIn: ["https://top.gg/discord/servers/721089405000564736"],
  },
];
