// The three legal pages the app still shows in a WebView (OS-039) and the
// native entry points to them. App Store guideline 5.1.1(i) needs the
// privacy policy to be easy to reach from inside the app, so Settings →
// About and the Clownbot AI disclosure both link here. Pure module (no
// react-native imports) so it runs under vitest.

export type LegalPageId = 'privacy' | 'terms' | 'support';

export const LEGAL_PAGES: readonly { id: LegalPageId; label: string; path: string }[] = [
  { id: 'privacy', label: 'Privacy Policy', path: '/privacy' },
  { id: 'terms', label: 'Terms of Use', path: '/terms' },
  { id: 'support', label: 'Support', path: '/support' },
];

/**
 * App Store guideline 5.1.2(i): the Clownbot / mood chat sends what the user
 * types to our server and on to Anthropic's Claude API. Shown under the
 * chat input on both modes, followed by a Privacy Policy link.
 */
export const CLOWNBOT_AI_DISCLOSURE =
  "Replies are generated by AI (Anthropic's Claude). What you type is sent to our server and to Anthropic to answer it, so please don't include personal information.";

const LEGAL_PATHS = new Set(LEGAL_PAGES.map((p) => p.path));

/** Full URL for one legal page on `siteUrl` (no trailing slash expected, same as SiteShell's SITE_URL). */
export function legalPageUrl(id: LegalPageId, siteUrl: string): string {
  const page = LEGAL_PAGES.find((p) => p.id === id);
  return `${siteUrl.replace(/\/$/, '')}${page ? page.path : '/privacy'}`;
}

/**
 * OS-039: the only three routes the WebView is still allowed to show —
 * static legal text with no native screen and no plan to ever get one.
 * Matched on pathname alone (query/hash ignored) against `siteUrl`'s own
 * host, same host-matching posture `destinationFor` (@swift2/shared) uses,
 * so a non-longlivets.com URL is never mistaken for a legal page.
 */
export function isLegalPageUrl(rawUrl: string, siteUrl: string): boolean {
  try {
    const site = new URL(siteUrl);
    const siteHosts = new Set(
      site.hostname.startsWith('www.')
        ? [site.hostname, site.hostname.slice('www.'.length)]
        : [site.hostname, `www.${site.hostname}`],
    );
    const u = new URL(rawUrl);
    return siteHosts.has(u.hostname) && LEGAL_PATHS.has(u.pathname);
  } catch {
    return false;
  }
}
