// ── The Proposal (sourced narrative thread) ─────────────────────────────────
// Publicly reported facts, attributed. Framed by an independent fan project.

// PROPOSAL_BEATS removed (consolidation stage 3, 2026-07-19): the End Game
// thread derives from vault moments tagged the-proposal — see
// components/longlive/proposal/ProposalThread.tsx and threads.ts.


// ── The Decode (hidden clue → payoff pairs) ─────────────────────────────────
// AI-researched, hand-audited: URLs flattened to direct links, plant precedes
// payoff, confirmed vs. fan-theory flags preserved.

export const CLUE_PAIRS = [
  {
    id: 'clue-delicate-pastel-nails',
    title: 'The pastel nails in “Delicate”',
    plant: {
      date: '2018-03-30',
      dateLabel: 'March 2018',
      eraId: 'reputation',
      what: 'The Spotify vertical video for “Delicate” showed Taylor’s nails in a soft pastel color story that looked out of place in the dark reputation era.',
    },
    payoff: {
      date: '2019-04-26',
      dateLabel: 'April 2019',
      eraId: 'lover',
      what: 'The “ME!” video launched the pastel Lover world, and Taylor later said the “Delicate” nail colors were an Easter egg for the next era.',
    },
    connection: 'A small beauty detail in a reputation video previewed the Lover palette more than a year early.',
    confirmed: true,
    sources: [
      { name: 'Entertainment Weekly', url: 'https://ew.com/music/2019/05/09/taylor-swift-secrets-album-easter-eggs/' },
      { name: 'People', url: 'https://people.com/music/taylor-swift-debuts-new-one-take-delicate-video-on-spotify/' },
    ],
  },
  {
    id: 'clue-seven-palm-trees',
    title: 'Seven palm trees',
    plant: {
      date: '2019-02-24',
      dateLabel: 'February 2019',
      eraId: 'lover',
      what: 'Taylor posted an Instagram photo of seven palm trees — a number fans tied to her upcoming seventh studio album.',
    },
    payoff: {
      date: '2019-04-26',
      dateLabel: 'April 2019',
      eraId: 'lover',
      what: 'The Lover rollout began with “ME!,” and Taylor later confirmed the palm-tree post was part of the TS7 Easter-egg trail.',
    },
    connection: 'The seven palm trees were a numeric clue pointing to TS7 before the Lover campaign began.',
    confirmed: true,
    sources: [
      { name: 'Entertainment Weekly', url: 'https://ew.com/music/2019/05/09/taylor-swift-cover-story/' },
      { name: 'Time', url: 'https://time.com/5538862/taylor-swift-countdown/' },
    ],
  },
  {
    id: 'clue-brendon-hints-in-print',
    title: 'Brendon Urie hidden in print',
    plant: {
      date: '2019-03-06',
      dateLabel: 'March 2019',
      eraId: 'lover',
      what: 'In her Elle essay “30 Things I Learned Before Turning 30,” Taylor referenced Panic! at the Disco’s “I Write Sins Not Tragedies.”',
    },
    payoff: {
      date: '2019-04-26',
      dateLabel: 'April 2019',
      eraId: 'lover',
      what: 'Taylor released “ME!” featuring Panic! at the Disco frontman Brendon Urie.',
    },
    connection: 'The Panic! reference quietly pointed to the collaborator on the first Lover single.',
    confirmed: true,
    sources: [
      { name: 'Elle', url: 'https://www.elle.com/culture/celebrities/a26628467/taylor-swift-30th-birthday-lessons/' },
      { name: 'Entertainment Weekly', url: 'https://ew.com/music/2019/05/09/taylor-swift-secrets-album-easter-eggs/' },
      { name: 'NME', url: 'https://www.nme.com/news/music/taylor-swift-duets-with-panic-at-the-discos-brendon-urie-on-new-single-me-2481142' },
    ],
  },
  {
    id: 'clue-lover-neon-sign',
    title: 'The neon “Lover” sign',
    plant: {
      date: '2019-04-26',
      dateLabel: 'April 2019',
      eraId: 'lover',
      what: 'The “ME!” video featured the word “Lover” glowing in neon; Taylor said the album title was hidden somewhere in the video.',
    },
    payoff: {
      date: '2019-06-13',
      dateLabel: 'June 2019',
      eraId: 'lover',
      what: 'Taylor announced her seventh album would be titled Lover.',
    },
    connection: 'The album title appeared inside the first video of the era before she officially revealed it.',
    confirmed: true,
    sources: [
      { name: 'Glamour', url: 'https://www.glamour.com/story/taylor-swift-me-video-easter-eggs' },
      { name: 'Time', url: 'https://time.com/5651221/taylor-swift-lover-references-explained/' },
    ],
  },
  {
    id: 'clue-hayley-kiyoko-arrow-five',
    title: 'Hayley Kiyoko’s arrow hit five',
    plant: {
      date: '2019-06-17',
      dateLabel: 'June 2019',
      eraId: 'lover',
      what: 'In the “You Need to Calm Down” video, Hayley Kiyoko appears as an archer and shoots an arrow into a target marked with the number 5.',
    },
    payoff: {
      date: '2019-07-23',
      dateLabel: 'July 2019',
      eraId: 'lover',
      what: 'Taylor released “The Archer,” revealed as track 5 on Lover.',
    },
    connection: 'The archer imagery and the number 5 pointed directly to the next song reveal.',
    confirmed: true,
    sources: [
      { name: 'Time', url: 'https://time.com/5651221/taylor-swift-lover-references-explained/' },
      { name: 'Teen Vogue', url: 'https://www.teenvogue.com/story/taylor-swift-releases-the-archer' },
    ],
  },
  {
    id: 'clue-cruel-summer-tattoo',
    title: 'The “Cruel Summer” tattoo',
    plant: {
      date: '2019-06-17',
      dateLabel: 'June 2019',
      eraId: 'lover',
      what: 'In the “You Need to Calm Down” video, Ellen DeGeneres appears with a large “Cruel Summer” tattoo.',
    },
    payoff: {
      date: '2019-08-16',
      dateLabel: 'August 2019',
      eraId: 'lover',
      what: 'Taylor revealed the Lover tracklist, confirming “Cruel Summer” as a song on the album.',
    },
    connection: 'A visual gag in the video doubled as an early reveal of a Lover track title.',
    confirmed: false,
    sources: [
      { name: 'Time', url: 'https://time.com/5651221/taylor-swift-lover-references-explained/' },
      { name: 'Consequence', url: 'https://consequence.net/2019/08/taylor-swift-lover-album-tracklist/' },
      { name: 'Glamour', url: 'https://www.glamour.com/story/taylor-swift-lover-tracklist' },
    ],
  },
  {
    id: 'clue-not-a-lot-evermore',
    title: '“Not a lot going on at the moment,” again',
    plant: {
      date: '2020-11-22',
      dateLabel: 'November 2020',
      eraId: 'evermore',
      what: 'Taylor posted a photo captioned “not a lot going on at the moment,” echoing language she used shortly before folklore.',
    },
    payoff: {
      date: '2020-12-10',
      dateLabel: 'December 2020',
      eraId: 'evermore',
      what: 'Taylor announced evermore, folklore’s sister album, the next month.',
    },
    connection: 'A deliberately quiet caption became a warning sign for another surprise album drop.',
    confirmed: false,
    sources: [
      { name: 'Seventeen', url: 'https://www.seventeen.com/celebrity/music/a34944674/evermore-easter-eggs-taylor-swift/' },
      { name: 'Teen Vogue', url: 'https://www.teenvogue.com/story/taylor-swift-teaser-easter-egg-old-music' },
    ],
  },
  {
    id: 'clue-love-story-match-ad',
    title: 'The Match ad preview',
    plant: {
      date: '2020-12-02',
      dateLabel: 'December 2020',
      eraId: 'fearless',
      what: 'A snippet of the re-recorded “Love Story” appeared in a Ryan Reynolds Match.com ad — the first public taste of the re-recordings.',
    },
    payoff: {
      date: '2021-02-11',
      dateLabel: 'February 2021',
      eraId: 'fearless',
      what: 'Taylor announced Fearless (Taylor’s Version) and the release of “Love Story (Taylor’s Version).”',
    },
    connection: 'The ad preview quietly introduced the first Taylor’s Version era before the album announcement.',
    confirmed: true,
    sources: [
      { name: 'Variety', url: 'https://variety.com/2020/music/news/taylor-swift-rerecording-love-story-ryan-reynolds-match-com-ad-1234844130/' },
      { name: 'Variety', url: 'https://variety.com/2021/music/news/taylor-swift-fearless-love-story-re-record-big-machine-albums-good-morning-america-1234905692/' },
    ],
  },
  {
    id: 'clue-red-vault-word-scramble',
    title: 'The Red vault word scramble',
    plant: {
      date: '2021-08-05',
      dateLabel: 'August 2021',
      eraId: 'red',
      what: 'Taylor posted a vault-themed word-puzzle video teasing the artists and titles connected to Red (Taylor’s Version).',
    },
    payoff: {
      date: '2021-08-06',
      dateLabel: 'August 2021',
      eraId: 'red',
      what: 'The full Red (Taylor’s Version) tracklist was revealed, confirming vault tracks and collaborators including Phoebe Bridgers and Chris Stapleton.',
    },
    connection: 'The scramble gave fans the exact clues to decode the vault-track rollout before the official reveal.',
    confirmed: true,
    sources: [
      { name: 'Variety', url: 'https://variety.com/2021/music/news/taylor-swift-phoebe-bridgers-red-remake-word-puzzle-1235035385/' },
      { name: 'Teen Vogue', url: 'https://www.teenvogue.com/story/taylor-swift-announces-massive-red-taylors-version-tracklist' },
      { name: 'Pitchfork', url: 'https://pitchfork.com/news/taylor-swift-cheekily-reveals-phoebe-bridgers-feature-on-new-red-taylors-version/' },
    ],
  },
  {
    id: 'clue-the-man-karma-graffiti',
    title: 'The “Karma” graffiti',
    plant: {
      date: '2020-02-27',
      dateLabel: 'February 2020',
      eraId: 'lover',
      what: 'In “The Man” video, “Karma” appears in graffiti alongside references to Taylor’s albums and masters.',
    },
    payoff: {
      date: '2022-10-07',
      dateLabel: 'October 2022',
      eraId: 'midnights',
      what: 'During the Midnights rollout, Taylor revealed “Karma” as a track title; the song released with the album on October 21, 2022.',
    },
    connection: 'A word fans treated as lost-album lore eventually became an official Midnights song title.',
    confirmed: false,
    sources: [
      { name: 'Teen Vogue', url: 'https://www.teenvogue.com/story/taylor-swift-karma-fan-theory-explained' },
      { name: 'Time', url: 'https://time.com/6223793/taylor-swift-midnights-album-takeaways/' },
    ],
  },
  {
    id: 'clue-bejeweled-speak-now',
    title: 'Speak Now clues in “Bejeweled”',
    plant: {
      date: '2022-10-25',
      dateLabel: 'October 2022',
      eraId: 'midnights',
      what: 'The “Bejeweled” video dropped on the 12th anniversary of Speak Now, full of purple imagery, elevator-button numbers, and Speak Now references.',
    },
    payoff: {
      date: '2023-05-05',
      dateLabel: 'May 2023',
      eraId: 'speak-now',
      what: 'Taylor announced Speak Now (Taylor’s Version) during the Nashville stop of the Eras Tour.',
    },
    connection: 'The purple-coded imagery and anniversary timing made “Bejeweled” a major breadcrumb toward the next Taylor’s Version.',
    confirmed: false,
    sources: [
      { name: 'Entertainment Weekly', url: 'https://ew.com/music/easter-eggs-taylor-swift-bejeweled-music-video/' },
      { name: 'People', url: 'https://people.com/music/taylor-swift-announces-speak-now-taylors-version-at-nashville-show/' },
    ],
  },
  {
    id: 'clue-i-can-see-you-1989-tv',
    title: 'The “1989 TV” bridge sign',
    plant: {
      date: '2023-07-07',
      dateLabel: 'July 2023',
      eraId: 'speak-now',
      what: 'The “I Can See You” video included a bridge sign fans read as “1989 TV” near the end.',
    },
    payoff: {
      date: '2023-08-09',
      dateLabel: 'August 2023',
      eraId: '1989',
      what: 'Taylor announced 1989 (Taylor’s Version) during the final Los Angeles show of the first U.S. Eras Tour leg.',
    },
    connection: 'A background detail in a Speak Now video pointed to the next re-recording announcement.',
    confirmed: false,
    sources: [
      { name: 'Seventeen', url: 'https://www.seventeen.com/celebrity/music/a44493917/taylor-swift-i-can-see-you-music-video-easter-eggs/' },
      { name: 'People', url: 'https://people.com/taylor-swift-announces-1989-taylors-version-standing-ovation-eras-tour-final-los-angeles-show-7629213/' },
      { name: 'Good Morning America', url: 'https://www.goodmorningamerica.com/culture/story/taylor-swift-announces-1989-taylors-version-details-hints-102157115' },
    ],
  },
  {
    id: 'clue-ttpd-two-fingers-anthology',
    title: 'The twos before The Anthology',
    plant: {
      date: '2024-02-04',
      dateLabel: 'February 2024',
      eraId: 'ttpd',
      what: 'After announcing The Tortured Poets Department at the Grammys, Taylor’s rollout repeatedly emphasized twos — peace-sign imagery and double-coded hints.',
    },
    payoff: {
      date: '2024-04-19',
      dateLabel: 'April 2024',
      eraId: 'ttpd',
      what: 'Two hours after release, Taylor revealed The Tortured Poets Department: The Anthology as a secret double album.',
    },
    connection: 'The repeated two-symbols became legible once the album expanded into a second installment at 2 a.m.',
    confirmed: false,
    sources: [
      { name: 'Marie Claire', url: 'https://www.marieclaire.co.uk/news/celebrity-news/taylor-swift-tortured-poets-easter-egg' },
      { name: 'Good Morning America', url: 'https://abcnews.go.com/GMA/Culture/taylor-swift-tortured-poets-department-album/story?id=109014004' },
      { name: 'People', url: 'https://people.com/taylor-swift-clues-about-the-tortured-poets-department-album-8558843' },
    ],
  },
  {
    id: 'clue-orange-door-showgirl',
    title: 'The orange door',
    plant: {
      date: '2024-12-08',
      dateLabel: 'December 2024',
      eraId: 'tloas',
      what: 'At the final Eras Tour show in Vancouver, Taylor exited through an orange door instead of the usual lift — a change fans flagged immediately.',
    },
    payoff: {
      date: '2025-08-12',
      dateLabel: 'August 2025',
      eraId: 'tloas',
      what: 'Taylor announced The Life of a Showgirl with a strongly orange visual identity, later acknowledging fans had correctly noticed the orange-door clue.',
    },
    connection: 'The final visual exit of the Eras Tour became the color-coded doorway into the next album era.',
    confirmed: true,
    sources: [
      { name: 'NBC Chicago', url: 'https://www.nbcchicago.com/entertainment/12-takeaways-from-taylor-swifts-new-heights-appearance-and-the-easter-eggs-found/3809515/' },
      { name: 'People', url: 'https://people.com/taylor-swift-announces-new-album-the-life-of-a-showgirl-with-help-travis-jason-kelce-11789202/' },
      { name: 'Elle', url: 'https://www.elle.com/culture/music/a65773807/why-taylor-swift-chose-orange-the-life-of-a-showgirl-era-color/' },
    ],
  },
  {
    id: 'clue-1989-elevator-eighteen',
    title: 'The elevator button 18',
    plant: {
      date: '2014-08-04',
      dateLabel: 'August 2014',
      eraId: '1989',
      what: 'Taylor posted what she called her “first clue”: a short Instagram video of an elevator button marked 18 being pressed repeatedly.',
    },
    payoff: {
      date: '2014-08-18',
      dateLabel: 'August 2014',
      eraId: '1989',
      what: 'On August 18, she announced 1989 during a Yahoo livestream and premiered “Shake It Off.”',
    },
    connection: 'The number 18 pointed to the exact date of the 1989 era reveal.',
    confirmed: true,
    sources: [
      { name: 'Vanity Fair', url: 'https://www.vanityfair.com/hollywood/2014/08/taylor-swift-kanye-west-new-music' },
      { name: 'Vanity Fair', url: 'https://www.vanityfair.com/hollywood/2014/08/taylor-swift-shake-it-off-video' },
    ],
  },
  {
    id: 'clue-reputation-social-blackout',
    title: 'The social media blackout',
    plant: {
      date: '2017-08-18',
      dateLabel: 'August 2017',
      eraId: 'reputation',
      what: 'Taylor wiped her social media accounts, leaving fans with a blank slate after a long public quiet period.',
    },
    payoff: {
      date: '2017-08-23',
      dateLabel: 'August 2017',
      eraId: 'reputation',
      what: 'She announced reputation and its black-and-white album artwork, formally beginning the new era.',
    },
    connection: 'The wipe reset her public image before an album explicitly about reputation and reinvention.',
    confirmed: true,
    sources: [
      { name: 'GQ', url: 'https://www.gq.com/story/taylor-swift-look-what-you-made-me-do' },
      { name: 'Vanity Fair', url: 'https://www.vanityfair.com/style/2017/08/taylor-swift-look-what-you-made-me-do-reputation' },
    ],
  },
  {
    id: 'clue-reputation-snake-videos',
    title: 'The snake teasers',
    plant: {
      date: '2017-08-21',
      dateLabel: 'August 2017',
      eraId: 'reputation',
      what: 'After blacking out her accounts, Taylor posted silent, glitchy snake clips across social media.',
    },
    payoff: {
      date: '2017-08-24',
      dateLabel: 'August 2017',
      eraId: 'reputation',
      what: 'She released “Look What You Made Me Do,” and snake imagery became central to the reputation rollout and video.',
    },
    connection: 'The snake clips previewed the symbol she would reclaim as the reputation era’s core iconography.',
    confirmed: true,
    sources: [
      { name: 'GQ', url: 'https://www.gq.com/story/taylor-swift-look-what-you-made-me-do' },
      { name: 'Pitchfork', url: 'https://pitchfork.com/news/watch-taylor-swifts-look-what-you-made-me-do-video/' },
    ],
  },
  {
    id: 'clue-iheartradio-butterfly-stilettos',
    title: 'The butterfly stilettos',
    plant: {
      date: '2019-03-14',
      dateLabel: 'March 2019',
      eraId: 'lover',
      what: 'Taylor attended the iHeartRadio Music Awards wearing butterfly-accented shoes, a sharp visual break from the snake-heavy reputation palette.',
    },
    payoff: {
      date: '2019-04-26',
      dateLabel: 'April 2019',
      eraId: 'lover',
      what: 'The “ME!” video opened with a snake bursting into butterflies, launching the pastel Lover era.',
    },
    connection: 'Butterflies quietly replaced snakes as the visual language of Taylor’s next era.',
    confirmed: true,
    sources: [
      { name: 'Entertainment Weekly', url: 'https://ew.com/music/2019/05/09/taylor-swift-secrets-album-easter-eggs/' },
      { name: 'Glamour', url: 'https://www.glamour.com/story/taylor-swift-me-video-easter-eggs' },
    ],
  },
  {
    id: 'clue-lover-426-countdown',
    title: 'The 4.26 countdown',
    plant: {
      date: '2019-04-13',
      dateLabel: 'April 2019',
      eraId: 'lover',
      what: 'Taylor launched a countdown on her site and social channels pointing to 4.26, without initially saying what would happen.',
    },
    payoff: {
      date: '2019-04-26',
      dateLabel: 'April 2019',
      eraId: 'lover',
      what: 'She released “ME!” featuring Brendon Urie and its pastel, butterfly-filled music video.',
    },
    connection: 'The countdown directly led fans to the first release of the Lover era.',
    confirmed: true,
    sources: [
      { name: 'Time', url: 'https://time.com/5538862/taylor-swift-countdown/' },
      { name: 'NME', url: 'https://www.nme.com/news/music/taylor-swift-duets-with-panic-at-the-discos-brendon-urie-on-new-single-me-2481142' },
    ],
  },
  {
    id: 'clue-lover-nashville-butterfly-mural',
    title: 'The Nashville butterfly mural',
    plant: {
      date: '2019-04-25',
      dateLabel: 'April 2019',
      eraId: 'lover',
      what: 'A butterfly mural appeared in Nashville, and Taylor showed up there with fans shortly before the new music reveal.',
    },
    payoff: {
      date: '2019-04-26',
      dateLabel: 'April 2019',
      eraId: 'lover',
      what: 'The next day, she released “ME!,” whose video made butterflies the defining symbol of the new era.',
    },
    connection: 'The mural served as a real-world butterfly breadcrumb before the Lover era officially opened.',
    confirmed: true,
    sources: [
      { name: 'Time', url: 'https://time.com/5538862/taylor-swift-countdown/' },
      { name: 'Glamour', url: 'https://www.glamour.com/story/taylor-swift-me-video-easter-eggs' },
    ],
  },
  {
    id: 'clue-me-calm-dialogue',
    title: 'The French calm-down line',
    plant: {
      date: '2019-04-26',
      dateLabel: 'April 2019',
      eraId: 'lover',
      what: 'The “ME!” video opened with Taylor and Brendon Urie arguing in French, including a translated version of “you need to calm down.”',
    },
    payoff: {
      date: '2019-06-14',
      dateLabel: 'June 2019',
      eraId: 'lover',
      what: 'Taylor released “You Need to Calm Down” as the second Lover single.',
    },
    connection: 'A line of dialogue in the first Lover video pointed to the title of the next single.',
    confirmed: false,
    sources: [
      { name: 'Glamour', url: 'https://www.glamour.com/story/taylor-swift-me-video-easter-eggs' },
      { name: 'Teen Vogue', url: 'https://www.teenvogue.com/story/taylor-swift-new-album-lover-new-single-june-14' },
    ],
  },
  {
    id: 'clue-me-dixie-chicks-photo',
    title: 'The Dixie Chicks photo',
    plant: {
      date: '2019-04-26',
      dateLabel: 'April 2019',
      eraId: 'lover',
      what: 'The “ME!” video included a framed photo of the Dixie Chicks, which fans flagged as more than background decoration.',
    },
    payoff: {
      date: '2019-08-16',
      dateLabel: 'August 2019',
      eraId: 'lover',
      what: 'Taylor revealed the Lover tracklist, confirming “Soon You’ll Get Better” featuring the Dixie Chicks.',
    },
    connection: 'A framed photo foreshadowed one of Lover’s most important collaborations.',
    confirmed: false,
    sources: [
      { name: 'Glamour', url: 'https://www.glamour.com/story/taylor-swift-me-video-easter-eggs' },
      { name: 'Entertainment Weekly', url: 'https://ew.com/music/2019/08/23/taylor-swift-lover-track-by-track-breakdown/' },
    ],
  },
  {
    id: 'clue-the-man-no-scooters',
    title: 'The “No Scooters” sign',
    plant: {
      date: '2020-02-27',
      dateLabel: 'February 2020',
      eraId: 'lover',
      what: 'In “The Man” video, the graffiti wall included a “No Scooters” sign next to the titles of Taylor’s earlier albums.',
    },
    payoff: {
      date: '2021-02-11',
      dateLabel: 'February 2021',
      eraId: 'fearless',
      what: 'Taylor announced Fearless (Taylor’s Version), beginning the public album-by-album re-recording campaign to reclaim her catalog.',
    },
    connection: 'The wall visually tied the masters dispute to the albums she would soon start re-recording.',
    confirmed: false,
    sources: [
      { name: 'Vulture', url: 'https://www.vulture.com/2020/02/taylor-swift-the-man-music-video-dwayne-johnson-watch.html' },
      { name: 'Pitchfork', url: 'https://pitchfork.com/news/taylor-swift-details-re-recorded-album-fearless-taylors-version/' },
    ],
  },
  {
    id: 'clue-folklore-not-a-lot',
    title: '“Not a lot going on at the moment”',
    plant: {
      date: '2020-04-27',
      dateLabel: 'April 2020',
      eraId: 'folklore',
      what: 'Taylor posted a quarantine photo captioned “Not a lot going on at the moment,” a phrase fans later treated as suspiciously understated.',
    },
    payoff: {
      date: '2020-07-23',
      dateLabel: 'July 2020',
      eraId: 'folklore',
      what: 'She announced folklore, a surprise album written and recorded during lockdown, for release at midnight.',
    },
    connection: 'The quiet caption became meaningful in hindsight once fans learned she had been making an entire album.',
    confirmed: false,
    sources: [
      { name: 'BuzzFeed', url: 'https://www.buzzfeed.com/elliewoodward/taylor-swift-folklore-cardigan-easter-egg-instagram-post' },
      { name: 'Taylor Swift Instagram', url: 'https://www.instagram.com/p/CC-9usjDzUw/' },
    ],
  },
  {
    id: 'clue-cardigan-to-willow',
    title: 'The magic piano continuation',
    plant: {
      date: '2020-07-24',
      dateLabel: 'July 2020',
      eraId: 'folklore',
      what: 'The “cardigan” video ended with Taylor soaked at a piano in a cabin, wearing the cardigan from the song.',
    },
    payoff: {
      date: '2020-12-11',
      dateLabel: 'December 2020',
      eraId: 'evermore',
      what: 'The “willow” video opened in the same setting and continued the visual story with a glowing golden thread.',
    },
    connection: 'The ending of folklore’s lead video became the starting point for evermore’s lead video.',
    confirmed: false,
    sources: [
      { name: 'Entertainment Weekly', url: 'https://ew.com/music/easter-eggs-taylor-swift-willow-music-video/' },
      { name: 'PopSugar', url: 'https://www.popsugar.com/entertainment/taylor-swift-willow-music-video-easter-eggs-48051587' },
    ],
  },
  {
    id: 'clue-fearless-april-ninth',
    title: 'The hidden “April Ninth” message',
    plant: {
      date: '2021-02-11',
      dateLabel: 'February 2021',
      eraId: 'fearless',
      what: 'Taylor announced Fearless (Taylor’s Version) with a letter whose random capital letters spelled “APRIL NINTH.”',
    },
    payoff: {
      date: '2021-04-09',
      dateLabel: 'April 2021',
      eraId: 'fearless',
      what: 'Fearless (Taylor’s Version) was released on April 9.',
    },
    connection: 'The capital-letter code revealed the album’s release date before fans reached the end of the rollout.',
    confirmed: true,
    sources: [
      { name: 'The Independent', url: 'https://www.independent.co.uk/arts-entertainment/music/news/taylor-swift-fearless-re-recorded-b1800919.html' },
      { name: 'Pitchfork', url: 'https://pitchfork.com/news/taylor-swift-details-re-recorded-album-fearless-taylors-version/' },
    ],
  },
  {
    id: 'clue-fearless-vault-scramble',
    title: 'The Fearless vault scramble',
    plant: {
      date: '2021-04-02',
      dateLabel: 'April 2021',
      eraId: 'fearless',
      what: 'Taylor posted a vault video with scrambled letters for fans to decode the unreleased Fearless (Taylor’s Version) tracks.',
    },
    payoff: {
      date: '2021-04-03',
      dateLabel: 'April 2021',
      eraId: 'fearless',
      what: 'She revealed the full Fearless (Taylor’s Version) tracklist, including vault tracks and collaborators.',
    },
    connection: 'The scrambled vault letters let fans solve the tracklist before the official reveal.',
    confirmed: true,
    sources: [
      { name: 'Seventeen', url: 'https://www.seventeen.com/celebrity/music/a36014856/taylor-swift-revealed-six-unreleased-songs-titles-instagram/' },
      { name: 'Teen Vogue', url: 'https://www.teenvogue.com/story/taylor-swift-shares-track-list-fearless-taylors-version' },
    ],
  },
  {
    id: 'clue-wildest-dreams-spirit-trailer',
    title: 'The “Wildest Dreams” trailer preview',
    plant: {
      date: '2021-03-12',
      dateLabel: 'March 2021',
      eraId: '1989',
      what: 'A trailer for Spirit Untamed used a preview of “Wildest Dreams (Taylor’s Version),” giving fans an early official taste of a 1989 re-recording.',
    },
    payoff: {
      date: '2021-09-17',
      dateLabel: 'September 2021',
      eraId: '1989',
      what: 'Taylor released the full “Wildest Dreams (Taylor’s Version)” track.',
    },
    connection: 'A movie-trailer snippet preceded the standalone release of the full Taylor’s Version recording.',
    confirmed: true,
    sources: [
      { name: 'Billboard', url: 'https://www.billboard.com/music/pop/taylor-swift-wildest-dreams-taylors-version-spirit-untamed-trailer-9540468/' },
      { name: 'NME', url: 'https://www.nme.com/news/music/taylor-swift-releases-wildest-dreams-taylors-version-after-it-goes-viral-on-tiktok-3048170' },
    ],
  },
  {
    id: 'clue-this-love-summer-trailer',
    title: 'The “This Love” trailer preview',
    plant: {
      date: '2022-05-05',
      dateLabel: 'May 2022',
      eraId: '1989',
      what: 'The trailer for The Summer I Turned Pretty featured a preview of “This Love (Taylor’s Version).”',
    },
    payoff: {
      date: '2022-05-06',
      dateLabel: 'May 2022',
      eraId: '1989',
      what: 'Taylor released the full “This Love (Taylor’s Version)” track the next day.',
    },
    connection: 'The trailer acted as a one-day breadcrumb for the next 1989 Taylor’s Version song drop.',
    confirmed: true,
    sources: [
      { name: 'Teen Vogue', url: 'https://www.teenvogue.com/story/taylor-swift-this-love-taylors-version-the-summer-i-turned-pretty-trailer' },
      { name: 'Variety', url: 'https://variety.com/2022/music/news/taylor-swift-this-love-taylors-version-summer-i-turned-pretty-trailer-1235260492/' },
    ],
  },
  {
    id: 'clue-midnights-music-movies-trailer',
    title: 'The Midnights music-movies trailer',
    plant: {
      date: '2022-10-20',
      dateLabel: 'October 2022',
      eraId: 'midnights',
      what: 'Taylor premiered a teaser trailer during Thursday Night Football showing clips from multiple secret Midnights visual projects.',
    },
    payoff: {
      date: '2023-01-27',
      dateLabel: 'January 2023',
      eraId: 'midnights',
      what: 'After “Anti-Hero” and “Bejeweled,” she released the “Lavender Haze” video, fulfilling another teased visual from the trailer.',
    },
    connection: 'The trailer previewed a slate of Midnights videos months before all of them were released.',
    confirmed: true,
    sources: [
      { name: 'Variety', url: 'https://variety.com/2022/music/news/taylor-swift-midnights-trailer-1235409770/' },
      { name: 'PopSugar', url: 'https://www.popsugar.com/entertainment/taylor-swift-midnights-music-videos-48986091' },
    ],
  },
  {
    id: 'clue-bejeweled-fifth-floor',
    title: 'The blue fifth-floor button',
    plant: {
      date: '2022-10-25',
      dateLabel: 'October 2022',
      eraId: 'midnights',
      what: 'In the “Bejeweled” video, Taylor rode an elevator with color-coded buttons; after the purple third-floor Speak Now clue, fans noticed the blue fifth-floor button.',
    },
    payoff: {
      date: '2023-08-09',
      dateLabel: 'August 2023',
      eraId: '1989',
      what: 'Taylor announced 1989 (Taylor’s Version), her fifth album’s re-recording, during the Eras Tour in Los Angeles.',
    },
    connection: 'The blue fifth-floor cue became legible once the next Taylor’s Version was 1989.',
    confirmed: false,
    sources: [
      { name: 'Good Morning America', url: 'https://www.goodmorningamerica.com/culture/story/taylor-swift-announces-1989-taylors-version-details-hints-102157115' },
      { name: 'Teen Vogue', url: 'https://www.teenvogue.com/story/taylor-swift-bejeweled-music-video-has-a-major-re-recording-clue-and-tons-of-celeb-cameos' },
    ],
  },
  {
    id: 'clue-karma-blue-nail-eight',
    title: 'The blue nail at eight',
    plant: {
      date: '2023-05-26',
      dateLabel: 'May 2023',
      eraId: 'midnights',
      what: 'In the “Karma” video, Taylor’s blue nail appeared near the number 8 on a clock face, which fans read as an August 1989 clue.',
    },
    payoff: {
      date: '2023-08-09',
      dateLabel: 'August 2023',
      eraId: '1989',
      what: 'Taylor announced 1989 (Taylor’s Version) in August, matching the blue color association and the number 8.',
    },
    connection: 'The color-and-number combination seemed to point to the month and era of the 1989 Taylor’s Version announcement.',
    confirmed: false,
    sources: [
      { name: 'Cosmopolitan', url: 'https://www.cosmopolitan.com/entertainment/music/a44020486/taylor-swift-karma-music-video-easter-eggs/' },
      { name: 'Good Morning America', url: 'https://www.goodmorningamerica.com/culture/story/taylor-swift-announces-1989-taylors-version-details-hints-102157115' },
    ],
  },
  {
    id: 'clue-karma-august-hourglass',
    title: 'The August hourglass',
    plant: {
      date: '2023-05-26',
      dateLabel: 'May 2023',
      eraId: 'midnights',
      what: 'The “Karma” video included an hourglass, which fans connected to Taylor’s folklore-era “August slipped away” hourglass merch.',
    },
    payoff: {
      date: '2023-08-09',
      dateLabel: 'August 2023',
      eraId: '1989',
      what: 'Taylor announced 1989 (Taylor’s Version) in August.',
    },
    connection: 'The hourglass became part of the fan-read August trail that culminated in the 1989 Taylor’s Version announcement.',
    confirmed: false,
    sources: [
      { name: 'People', url: 'https://people.com/music/taylor-swift-midnights-music-videos-easter-eggs/' },
      { name: 'Good Morning America', url: 'https://www.goodmorningamerica.com/culture/story/taylor-swift-announces-1989-taylors-version-details-hints-102157115' },
    ],
  },
  {
    id: 'clue-1989-google-vault',
    title: 'The Google vault puzzles',
    plant: {
      date: '2023-09-19',
      dateLabel: 'September 2023',
      eraId: '1989',
      what: 'Taylor and Google launched a blue-vault search puzzle requiring fans to solve millions of clues tied to 1989 (Taylor’s Version).',
    },
    payoff: {
      date: '2023-09-20',
      dateLabel: 'September 2023',
      eraId: '1989',
      what: 'The vault unlocked and revealed the 1989 (Taylor’s Version) vault-track titles.',
    },
    connection: 'The interactive puzzle was the mechanism for revealing the album’s previously unreleased songs.',
    confirmed: true,
    sources: [
      { name: 'Google', url: 'https://blog.google/products-and-platforms/products/search/taylor-swift-google-search-easter-egg/' },
      { name: 'People', url: 'https://people.com/taylor-swift-reveals-1989-taylors-version-vault-track-names-7972119' },
    ],
  },
  {
    id: 'clue-ttpd-aimee-hair-clip',
    title: 'The Aimee hair clip',
    plant: {
      date: '2023-10-01',
      dateLabel: 'October 2023',
      eraId: 'ttpd',
      what: 'Taylor was photographed wearing an Anthropologie hair clip from a set named “Aimee,” months before fans knew any TTPD track titles.',
    },
    payoff: {
      date: '2024-04-19',
      dateLabel: 'April 2024',
      eraId: 'ttpd',
      what: 'The Tortured Poets Department: The Anthology included the song “thanK you aIMee.”',
    },
    connection: 'A fashion item name appeared to foreshadow one of the Anthology song titles.',
    confirmed: false,
    sources: [
      { name: 'Glamour', url: 'https://www.glamour.com/story/taylor-swift-has-been-hiding-tortured-poets-easter-eggs-in-street-style-fits-for-6-months' },
      { name: 'Us Weekly', url: 'https://www.usmagazine.com/stylish/news/taylor-swifts-style-has-been-full-of-ttpd-easter-eggs-for-months/' },
    ],
  },
  {
    id: 'clue-ttpd-cassandra-bag',
    title: 'The Cassandra bag',
    plant: {
      date: '2023-11-13',
      dateLabel: 'November 2023',
      eraId: 'ttpd',
      what: 'Taylor was photographed in New York carrying a Saint Laurent Cassandra bag.',
    },
    payoff: {
      date: '2024-04-19',
      dateLabel: 'April 2024',
      eraId: 'ttpd',
      what: 'The Tortured Poets Department: The Anthology included a track titled “Cassandra.”',
    },
    connection: 'The handbag name matched an Anthology song title revealed five months later.',
    confirmed: false,
    sources: [
      { name: 'People', url: 'https://people.com/taylor-swift-was-spotted-wearing-the-ysl-cassandra-bag-5-months-before-releasing-a-song-of-the-same-name-8636853' },
      { name: 'Page Six', url: 'https://pagesix.com/2024/04/22/taylor-swift-the-tortured-poets-department-fashion-easter-eggs/' },
    ],
  },
  {
    id: 'clue-ttpd-robin-boots',
    title: 'The Robin boots',
    plant: {
      date: '2024-01-18',
      dateLabel: 'January 2024',
      eraId: 'ttpd',
      what: 'Taylor was photographed wearing The Row’s Robin Leather Chelsea Boots during her pre-TTPD street-style run.',
    },
    payoff: {
      date: '2024-04-19',
      dateLabel: 'April 2024',
      eraId: 'ttpd',
      what: 'The Tortured Poets Department: The Anthology included a track titled “Robin.”',
    },
    connection: 'The boot name matched a song title that would not be public until the Anthology release.',
    confirmed: false,
    sources: [
      { name: 'Elite Daily', url: 'https://www.elitedaily.com/fashion/taylor-swift-outfit-easter-eggs-for-tortured-poets' },
      { name: 'Page Six', url: 'https://pagesix.com/2024/04/22/taylor-swift-the-tortured-poets-department-fashion-easter-eggs/' },
    ],
  },
  {
    id: 'clue-ttpd-literary-academia-style',
    title: 'The literary-academia wardrobe',
    plant: {
      date: '2023-10-01',
      dateLabel: 'October 2023',
      eraId: 'ttpd',
      what: 'In the months before TTPD, Taylor repeatedly wore preppy, literary-academia-coded street-style pieces: pleated skirts, loafers, checked coats, and dark neutral layers.',
    },
    payoff: {
      date: '2024-04-19',
      dateLabel: 'April 2024',
      eraId: 'ttpd',
      what: 'The Tortured Poets Department arrived with a black-and-white, literary, poet-coded visual world.',
    },
    connection: 'The wardrobe moodboard previewed the intellectual, monochrome aesthetic of the TTPD era.',
    confirmed: false,
    sources: [
      { name: 'Vanity Fair', url: 'https://www.vanityfair.com/style/story/poetics-of-taylor-swift-style' },
      { name: 'Page Six', url: 'https://pagesix.com/2024/04/19/style/taylor-swift-tortured-poets-department-style-meaning/' },
    ],
  },
  {
    id: 'clue-showgirl-taylor-nation-orange-posts',
    title: 'Taylor Nation’s orange era posts',
    plant: {
      date: '2025-08-11',
      dateLabel: 'August 2025',
      eraId: 'tloas',
      what: 'Taylor Nation posted a set of orange Eras Tour images with language pointing fans toward the next era.',
    },
    payoff: {
      date: '2025-08-12',
      dateLabel: 'August 2025',
      eraId: 'tloas',
      what: 'Taylor announced her 12th studio album, The Life of a Showgirl, with an orange-heavy visual identity.',
    },
    connection: 'The official fan-team account used orange-coded tour imagery to prime fans for the Showgirl palette.',
    confirmed: true,
    sources: [
      { name: 'The Guardian', url: 'https://www.theguardian.com/music/2025/aug/12/taylor-swift-new-album-announcement-countdown-new-heights-podcast-the-life-of-a-showgirl' },
      { name: 'People', url: 'https://people.com/taylor-swift-new-album-life-of-a-showgirl-style-easter-eggs-decoded-11789517' },
    ],
  },
  {
    id: 'clue-showgirl-1212-countdown',
    title: 'The 12:12 countdown',
    plant: {
      date: '2025-08-11',
      dateLabel: 'August 2025',
      eraId: 'tloas',
      what: 'Taylor’s website displayed a glittering orange countdown set to expire at 12:12 a.m. ET.',
    },
    payoff: {
      date: '2025-08-12',
      dateLabel: 'August 2025',
      eraId: 'tloas',
      what: 'At the end of the countdown, the site revealed The Life of a Showgirl, Taylor’s 12th studio album.',
    },
    connection: 'The 12:12 timing pointed directly to TS12.',
    confirmed: true,
    sources: [
      { name: 'Good Morning America', url: 'https://abcnews.go.com/GMA/Culture/taylor-swift-announces-12th-studio-album-life-showgirl/story?id=124564822' },
      { name: 'The Guardian', url: 'https://www.theguardian.com/music/2025/aug/12/taylor-swift-new-album-announcement-countdown-new-heights-podcast-the-life-of-a-showgirl' },
    ],
  },
  {
    id: 'clue-showgirl-briefcase-colors',
    title: 'The mint-and-orange briefcase',
    plant: {
      date: '2025-08-12',
      dateLabel: 'August 2025',
      eraId: 'tloas',
      what: 'A New Heights teaser showed Taylor pulling a blurred album from a mint-green briefcase marked with orange “T.S.” initials.',
    },
    payoff: {
      date: '2025-08-13',
      dateLabel: 'August 2025',
      eraId: 'tloas',
      what: 'On the full New Heights episode, Taylor revealed The Life of a Showgirl cover, tracklist, release date, and its orange-and-mint visual world.',
    },
    connection: 'The briefcase previewed the album reveal and its key color palette before the full episode aired.',
    confirmed: true,
    sources: [
      { name: 'Pitchfork', url: 'https://pitchfork.com/news/taylor-swift-announces-new-album-the-life-of-a-showgirl/' },
      { name: 'Teen Vogue', url: 'https://www.teenvogue.com/story/taylor-swift-12th-album-the-life-of-a-showgirl-everything-you-need-to-know' },
    ],
  },
  {
    id: 'clue-showgirl-max-shellback-playlist',
    title: 'The Max Martin and Shellback playlist',
    plant: {
      date: '2025-08-12',
      dateLabel: 'August 2025',
      eraId: 'tloas',
      what: 'After the album announcement, Taylor shared a Spotify playlist made up of past songs produced by Max Martin and Shellback.',
    },
    payoff: {
      date: '2025-10-03',
      dateLabel: 'October 2025',
      eraId: 'tloas',
      what: 'The Life of a Showgirl was released with Max Martin and Shellback as central collaborators and producers.',
    },
    connection: 'The playlist previewed the production team behind Taylor’s next pop album.',
    confirmed: true,
    sources: [
      { name: 'NME', url: 'https://www.nme.com/news/music/taylor-swift-curates-playlist-for-the-life-of-a-showgirl-hinting-at-max-martin-and-shellback-collaboration-3884220' },
      { name: 'Entertainment Weekly', url: 'https://ew.com/taylor-swift-the-life-of-a-showgirl-credits-producers-11823950' },
    ],
  },
];
