export const EGG_LINKS = [
  { from: 'egg-13-debut', to: 'egg-13-video-1989', label: 'recurs as number motif' },
  { from: 'egg-13-video-1989', to: 'egg-13-tracks-midnights', label: 'escalates to track count' },
  { from: 'egg-capitals-debut', to: 'egg-capitals-fearless', label: 'recurs as format' },
  { from: 'egg-capitals-fearless', to: 'egg-fearless-tv-scramble', label: 'evolves into cipher' },
  { from: 'egg-clock-lastkiss', to: 'egg-midnights-vinyl-clock', label: 'recurs as clock motif' },
  { from: 'egg-red-burning', to: 'egg-color-daylight', label: 'flipped and resolved' },
  { from: 'egg-red-burning', to: 'egg-red-tv-rings', label: 'fulfilled via re-record' },
  { from: 'egg-snake-instagram', to: 'egg-snake-lwymmd', label: 'fulfilled in video' },
  { from: 'egg-snake-lwymmd', to: 'egg-snake-me-mv', label: 'shed and transformed' },
  { from: 'egg-loverhouse-mv', to: 'egg-cabin-folklore', label: 'fulfilled room theme' },
  { from: 'egg-loverhouse-mv', to: 'egg-eras-burning-house', label: 'escalated and destroyed' },
  { from: 'egg-man-graffiti', to: 'egg-fearless-tv-scramble', label: 'fulfilled rollout' },
  { from: 'egg-man-graffiti', to: 'egg-red-tv-rings', label: 'fulfilled rollout' },
  { from: 'egg-man-graffiti', to: 'egg-bejeweled-elevator', label: 'escalated tracking' },
  { from: 'egg-bejeweled-elevator', to: 'egg-speaknow-tv-nashville', label: 'fulfilled purple button' },
  { from: 'egg-bejeweled-elevator', to: 'egg-1989-tv-la', label: 'fulfilled blue button' },
  { from: 'egg-bejeweled-elevator', to: 'egg-rep-tv-clue-bejeweled', label: 'sparks fan theory' },
  { from: 'egg-color-daylight', to: 'egg-string-willow', label: 'recurs as golden motif' },
  { from: 'egg-grammys-two-fingers', to: 'egg-ttpd-timetable-clock', label: 'escalates clue density' },
  { from: 'egg-ttpd-timetable-clock', to: 'egg-ttpd-anthology-drop', label: 'fulfilled midnight twist' },
  { from: 'egg-karma-album-theory', to: 'egg-tloas-orange-doors', label: 'recurs as orange aesthetic' },
  { from: 'egg-tloas-orange-doors', to: 'egg-tloas-album-drop', label: 'fulfilled countdown' },
  { from: 'egg-tloas-orange-doors', to: 'egg-wood-track-tloas', label: 'sparks song theory' },
];
