// ── Easter Egg Web (constellation) ──────────────────────────────────────────
// x/y are normalized 0–100 coordinates for the SVG constellation layout.
// Dataset compiled by an AI research pass and hand-audited (URLs flattened,
// the "Last Kiss / 1:58" fact corrected, over-confident flags demoted).
// Both TLOAS soft-sourced nodes (`egg-tloas-orange-doors`, `egg-wood-track-tloas`)
// are marked confirmed: false pending a stronger primary source.

export const EGG_NODES = [
  {
    id: 'egg-13-debut',
    label: 'Lucky number 13',
    eraId: 'debut',
    year: 2006,
    kind: 'clue',
    detail: 'Taylor starts writing 13 on her hand before shows, calling it her lucky number and seeding a lifelong motif.',
    x: 10,
    y: 15,
    confirmed: true,
    sources: [{ name: 'MTV News', url: 'https://www.mtv.com/news/1628121/taylor-swift-explains-why-13-is-her-lucky-number/' }],
  },
  {
    id: 'egg-capitals-debut',
    label: 'Capitalized lyric codes',
    eraId: 'debut',
    year: 2006,
    kind: 'clue',
    detail: 'The debut album’s liner notes hide messages in randomized capital letters scattered through the printed lyrics.',
    x: 12,
    y: 75,
    confirmed: true,
    sources: [{ name: 'Billboard', url: 'https://www.billboard.com/lists/taylor-swift-liner-notes-secret-messages-decoded/' }],
  },
  {
    id: 'egg-capitals-fearless',
    label: 'Fearless hidden messages',
    eraId: 'fearless',
    year: 2008,
    kind: 'clue',
    detail: 'She continues the hidden-capitals tradition in the Fearless liner notes to drop clues about each song’s inspiration.',
    x: 22,
    y: 75,
    confirmed: true,
    sources: [{ name: 'Billboard', url: 'https://www.billboard.com/lists/taylor-swift-liner-notes-secret-messages-decoded/' }],
  },
  {
    id: 'egg-clock-lastkiss',
    label: 'Last Kiss 1:58 timestamp',
    eraId: 'speak-now',
    year: 2010,
    kind: 'clue',
    detail: '“Last Kiss” references a highly specific time — “lit through the darkness at 1:58” — establishing timestamps as clues.',
    x: 32,
    y: 45,
    confirmed: true,
    sources: [{ name: 'Rolling Stone', url: 'https://www.rollingstone.com/music/music-lists/taylor-swift-best-songs-1234731317/' }],
  },
  {
    id: 'egg-red-burning',
    label: 'Burning red motif',
    eraId: 'red',
    year: 2012,
    kind: 'clue',
    detail: 'The title track anchors her emotional spectrum to color, defining intense love as “burning red.”',
    x: 40,
    y: 30,
    confirmed: true,
    sources: [{ name: 'Pitchfork', url: 'https://pitchfork.com/reviews/albums/taylor-swift-red-taylors-version/' }],
  },
  {
    id: 'egg-13-video-1989',
    label: '1989 13-second teasers',
    eraId: '1989',
    year: 2014,
    kind: 'clue',
    detail: 'Ahead of 1989 she posts 13-second glitching Instagram videos to count down to her livestream announcement.',
    x: 48,
    y: 15,
    confirmed: true,
    sources: [{ name: 'Time', url: 'https://time.com/3103444/taylor-swift-1989-instagram-clues/' }],
  },
  {
    id: 'egg-karma-album-theory',
    label: 'The lost “Karma” album',
    eraId: 'reputation',
    year: 2016,
    kind: 'clue',
    detail: 'A widespread fan theory that a scrapped, orange-toned album called “Karma” was shelved in 2016 before reputation replaced it.',
    x: 52,
    y: 90,
    confirmed: false,
    sources: [{ name: 'Rolling Stone', url: 'https://www.rollingstone.com/music/music-features/taylor-swift-karma-scrapped-album-theory-explained-1234614742/' }],
  },
  {
    id: 'egg-snake-instagram',
    label: 'Cryptic snake videos',
    eraId: 'reputation',
    year: 2017,
    kind: 'clue',
    detail: 'After wiping her social media, she posts three silent, glitched videos of a slithering snake tail.',
    x: 55,
    y: 55,
    confirmed: true,
    sources: [{ name: 'Billboard', url: 'https://www.billboard.com/music/pop/taylor-swift-snake-videos-reputation-timeline-7948958/' }],
  },
  {
    id: 'egg-snake-lwymmd',
    label: 'Snake reclaimed in LWYMMD',
    eraId: 'reputation',
    year: 2017,
    kind: 'payoff',
    detail: 'The “Look What You Made Me Do” video fulfills the snake teasers, with Taylor serving tea atop a throne of serpents.',
    x: 58,
    y: 55,
    confirmed: true,
    sources: [{ name: 'Vogue', url: 'https://www.vogue.com/article/taylor-swift-look-what-you-made-me-do-music-video-hidden-meanings' }],
  },
  {
    id: 'egg-snake-me-mv',
    label: 'Snake turns to butterflies',
    eraId: 'lover',
    year: 2019,
    kind: 'payoff',
    detail: 'The “ME!” video opens on a pink serpent that bursts into butterflies, formally shedding the reputation era.',
    x: 64,
    y: 55,
    confirmed: true,
    sources: [{ name: 'Entertainment Weekly', url: 'https://ew.com/music/2019/04/26/taylor-swift-me-music-video-easter-eggs/' }],
  },
  {
    id: 'egg-color-daylight',
    label: 'Love is golden, not red',
    eraId: 'lover',
    year: 2019,
    kind: 'payoff',
    detail: 'In “Daylight” she resolves the Red-era color motif: “I once believed love would be burning red / but it’s golden.”',
    x: 65,
    y: 30,
    confirmed: true,
    sources: [{ name: 'Rolling Stone', url: 'https://www.rollingstone.com/music/music-album-reviews/taylor-swift-lover-875207/' }],
  },
  {
    id: 'egg-loverhouse-mv',
    label: 'The Lover house',
    eraId: 'lover',
    year: 2019,
    kind: 'clue',
    detail: 'The “Lover” video’s snow-globe house gives each room a color scheme corresponding to a distinct album/era.',
    x: 66,
    y: 45,
    confirmed: true,
    sources: [{ name: 'People', url: 'https://people.com/music/taylor-swift-lover-music-video-easter-eggs-breakdown/' }],
  },
  {
    id: 'egg-man-graffiti',
    label: '“The Man” graffiti wall',
    eraId: 'lover',
    year: 2020,
    kind: 'clue',
    detail: 'A wall in “The Man” lists her first six albums beside a sign reading “Missing: if found return to Taylor Swift.”',
    x: 68,
    y: 65,
    confirmed: true,
    sources: [{ name: 'BBC', url: 'https://www.bbc.com/news/entertainment-arts-51664182' }],
  },
  {
    id: 'egg-cabin-folklore',
    label: 'The folklore cabin',
    eraId: 'folklore',
    year: 2020,
    kind: 'payoff',
    detail: 'The rustic attic room in the Lover house becomes the aesthetic blueprint for the isolated folklore cabin.',
    x: 70,
    y: 45,
    confirmed: true,
    sources: [{ name: 'Vulture', url: 'https://www.vulture.com/2020/11/taylor-swift-folklore-the-long-pond-studio-sessions-review.html' }],
  },
  {
    id: 'egg-string-willow',
    label: 'Golden string destiny',
    eraId: 'evermore',
    year: 2020,
    kind: 'payoff',
    detail: 'The “willow” video introduces a physical golden string, resolving the “invisible string” motif from folklore.',
    x: 72,
    y: 30,
    confirmed: true,
    sources: [{ name: "Harper's Bazaar", url: 'https://www.harpersbazaar.com/culture/art-books-music/a34938637/taylor-swift-willow-music-video-easter-eggs/' }],
  },
  {
    id: 'egg-fearless-tv-scramble',
    label: 'Fearless TV date cipher',
    eraId: 'fearless',
    year: 2021,
    kind: 'payoff',
    detail: 'She kicks off the re-recordings by tweeting a message whose capital letters unscramble to “APRIL NINTH.”',
    x: 74,
    y: 65,
    confirmed: true,
    sources: [{ name: 'Good Morning America', url: 'https://www.goodmorningamerica.com/culture/story/taylor-swift-announces-re-recorded-fearless-album-drops-75825227' }],
  },
  {
    id: 'egg-red-tv-rings',
    label: 'Red TV ring teaser',
    eraId: 'red',
    year: 2021,
    kind: 'payoff',
    detail: 'After months of red emojis and custom “Red” rings, Red (Taylor’s Version) is officially announced.',
    x: 76,
    y: 67,
    confirmed: true,
    sources: [{ name: 'Variety', url: 'https://variety.com/2021/music/news/taylor-swift-red-taylors-version-release-date-1235000109/' }],
  },
  {
    id: 'egg-bejeweled-elevator',
    label: 'Bejeweled elevator buttons',
    eraId: 'midnights',
    year: 2022,
    kind: 'clue',
    detail: 'The “Bejeweled” video’s elevator lights up button 3 (purple, Speak Now) and 5 (blue, 1989), charting the next re-records.',
    x: 78,
    y: 62,
    confirmed: true,
    sources: [{ name: 'Teen Vogue', url: 'https://www.teenvogue.com/story/taylor-swift-bejeweled-music-video-easter-eggs' }],
  },
  {
    id: 'egg-rep-tv-clue-bejeweled',
    label: 'Reputation TV skipped',
    eraId: 'midnights',
    year: 2022,
    kind: 'clue',
    detail: 'Fans note the reputation floor is skipped on the Bejeweled elevator, reading it as a hint about its re-record timing.',
    x: 82,
    y: 72,
    confirmed: false,
    sources: [{ name: 'Teen Vogue', url: 'https://www.teenvogue.com/story/taylor-swift-bejeweled-music-video-easter-eggs' }],
  },
  {
    id: 'egg-13-tracks-midnights',
    label: '13 tracks on Midnights',
    eraId: 'midnights',
    year: 2022,
    kind: 'payoff',
    detail: 'Midnights ships with exactly 13 tracks on the standard edition — a payoff to her lifelong lucky-number constraint.',
    x: 80,
    y: 15,
    confirmed: true,
    sources: [{ name: 'Pitchfork', url: 'https://pitchfork.com/news/taylor-swift-reveals-all-midnights-track-names/' }],
  },
  {
    id: 'egg-midnights-vinyl-clock',
    label: 'Vinyl covers form a clock',
    eraId: 'midnights',
    year: 2022,
    kind: 'payoff',
    detail: 'The back covers of the four Midnights vinyl variants assemble into a working wall clock.',
    x: 84,
    y: 22,
    confirmed: true,
    sources: [{ name: 'Billboard', url: 'https://www.billboard.com/music/music-news/taylor-swift-midnights-vinyl-back-covers-clock-1235140134/' }],
  },
  {
    id: 'egg-speaknow-tv-nashville',
    label: 'Speak Now TV, in purple',
    eraId: 'speak-now',
    year: 2023,
    kind: 'payoff',
    detail: 'Fulfilling the purple button, she announces Speak Now TV in Nashville as the stadium’s bracelets glow deep purple.',
    x: 86,
    y: 60,
    confirmed: true,
    sources: [{ name: 'Rolling Stone', url: 'https://www.rollingstone.com/music/music-news/taylor-swift-announces-speak-now-taylors-version-eras-tour-nashville-1234730248/' }],
  },
  {
    id: 'egg-1989-tv-la',
    label: '1989 TV, in blue',
    eraId: '1989',
    year: 2023,
    kind: 'payoff',
    detail: 'At the final L.A. Eras show she debuts new light-blue gowns to announce 1989 (Taylor’s Version).',
    x: 88,
    y: 66,
    confirmed: true,
    sources: [{ name: 'Los Angeles Times', url: 'https://www.latimes.com/entertainment-arts/music/story/2023-08-09/taylor-swift-1989-taylors-version-eras-tour-sofi-stadium' }],
  },
  {
    id: 'egg-eras-burning-house',
    label: 'Burning the Lover house',
    eraId: 'midnights',
    year: 2023,
    kind: 'payoff',
    detail: 'The Eras Tour backdrop shows the Lover house burning down, closing the ownership-transition arc.',
    x: 82,
    y: 45,
    confirmed: true,
    sources: [{ name: 'The Hollywood Reporter', url: 'https://www.hollywoodreporter.com/news/general-news/taylor-swift-eras-tour-concert-review-1235355415/' }],
  },
  {
    id: 'egg-grammys-two-fingers',
    label: 'Grammys two fingers',
    eraId: 'midnights',
    year: 2024,
    kind: 'clue',
    detail: 'Announcing TTPD at the Grammys she holds up two fingers, which many fans read as hinting at a double album.',
    x: 88,
    y: 82,
    confirmed: false,
    sources: [{ name: 'Cosmopolitan', url: 'https://www.cosmopolitan.com/entertainment/music/a60538356/taylor-swift-two-fingers-clue-meaning/' }],
  },
  {
    id: 'egg-ttpd-timetable-clock',
    label: 'The 2:00 timetable video',
    eraId: 'ttpd',
    year: 2024,
    kind: 'clue',
    detail: 'A promo timetable video from her team lingers on a clock at the 2:00 mark, hinting at a late-night twist.',
    x: 90,
    y: 80,
    confirmed: true,
    sources: [{ name: 'USA Today', url: 'https://www.usatoday.com/story/entertainment/music/2024/04/16/taylor-swift-ttpd-release-timetable/73347101007/' }],
  },
  {
    id: 'egg-ttpd-anthology-drop',
    label: 'The 2 AM Anthology',
    eraId: 'ttpd',
    year: 2024,
    kind: 'payoff',
    detail: 'Fulfilling the “2” clues, she drops a surprise second half of the album at 2:00 AM, subtitled The Anthology.',
    x: 93,
    y: 82,
    confirmed: true,
    sources: [{ name: 'Variety', url: 'https://variety.com/2024/music/news/taylor-swift-secret-double-album-tortured-poets-department-anthology-1235975618/' }],
  },
  {
    id: 'egg-wood-track-tloas',
    label: 'The “Wood” track theory',
    eraId: 'tloas',
    year: 2025,
    kind: 'clue',
    detail: 'Fans comb early tracklists trying to decode the song “Wood” and tie it back to her folklore nature roots.',
    x: 94,
    y: 52,
    confirmed: false,
    sources: [{ name: 'Apple Music', url: 'https://music.apple.com/us/album/the-life-of-a-showgirl-a-look-behind-the-curtain/1838812720' }],
  },
  {
    id: 'egg-tloas-orange-doors',
    label: '12 orange doors cipher',
    eraId: 'tloas',
    year: 2025,
    kind: 'clue',
    detail: 'To promote the album, 12 orange doors appear in cities worldwide with QR codes and ciphers teasing the tracks.',
    x: 95,
    y: 40,
    confirmed: false,
    sources: [{ name: '7NEWS Australia', url: 'https://www.youtube.com/watch?v=utPXqqCAbzY' }],
  },
  {
    id: 'egg-tloas-album-drop',
    label: 'The Life of a Showgirl',
    eraId: 'tloas',
    year: 2025,
    kind: 'payoff',
    detail: 'On October 3, 2025 she releases her 12th album, resolving the orange-door ciphers with 12 showgirl-themed tracks.',
    x: 98,
    y: 48,
    confirmed: true,
    sources: [{ name: 'PR Newswire', url: 'https://www.prnewswire.com/news-releases/taylor-swifts-the-life-of-a-showgirl-earns-biggest-first-week-in-music-history-with-over-4-million-us-and-over-5-5-million-global-album-equivalent-units-302582496.html' }],
  },
];
