// Vault videos — 1989 era. Official uploads verified via YouTube oEmbed
// 2026-07-08; Wikipedia URLs verified the same day.

const wiki = (article, title, notes) => ({
  source_url: `https://en.wikipedia.org/wiki/${article}`,
  source_title: title,
  publisher: 'Wikipedia',
  source_type: 'wiki',
  accessed_at: '2026-07-08',
  reliability_score: 2,
  excerpt: null,
  notes: notes ?? 'anchors the video, director, and background',
});
const yt = (id, title) => ({
  source_url: `https://www.youtube.com/watch?v=${id}`,
  source_title: title,
  publisher: 'Taylor Swift (official YouTube channel)',
  source_type: 'official',
  accessed_at: '2026-07-08',
  reliability_score: 5,
  excerpt: null,
  notes: 'official upload — verified via YouTube oEmbed 2026-07-08',
});
const press = (source_url, source_title, publisher, notes) => ({
  source_url,
  source_title,
  publisher,
  source_type: 'reputable_press',
  accessed_at: '2026-07-09',
  reliability_score: 4,
  excerpt: null,
  notes,
});
const embed = (id, fetchedOn = '2026-07-08') => ({
  kind: 'oembed',
  rights: 'platform_tos',
  provider: 'youtube',
  post_url: `https://www.youtube.com/watch?v=${id}`,
  oembed_fetched_at: fetchedOn,
  attribution: 'Taylor Swift — official YouTube channel',
});

import { appearance, pressSource, upload } from './_appearance-helpers.mjs';

export default {
  eraSlug: '1989',
  videos: [
    {
      slug: 'shake-it-off-mv',
      kind: 'music_video',
      title: 'Shake It Off',
      director: 'Mark Romanek',
      releasedOn: '2014-08-18',
      relatedSongs: ['Shake It Off'],
      tags: ['Music'],
      summary:
        'Dropped the day 1989 was announced: Taylor gamely flails through ballet, breakdance, twerk squads and cheer lines before the finale says the quiet part — just dance like the fans do.',
      symbolism: 'Failing every polished dance style on purpose is the thesis: the haters\' scorecard doesn\'t apply.',
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=nfWlot6h_JM',
      media: [embed('nfWlot6h_JM')],
      sources: [yt('nfWlot6h_JM', 'Taylor Swift - Shake It Off'), wiki('Shake_It_Off', 'Shake It Off')],
    },
    {
      slug: 'blank-space-mv',
      kind: 'music_video',
      title: 'Blank Space',
      director: 'Joseph Kahn',
      releasedOn: '2014-11-10',
      relatedSongs: ['Blank Space'],
      tags: ['Music'],
      summary:
        'The satire that ended the "boy-crazy" narrative by playing it to the hilt: a mansion romance curdles into golf-club-to-the-sports-car mania, with Taylor grinning through the tabloid caricature.',
      symbolism:
        'She is playing the media\'s version of Taylor Swift, not herself — the video is the song\'s joke made visible, and mainstream coverage read it exactly that way.',
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=e-ORhEE9VVg',
      media: [embed('e-ORhEE9VVg')],
      sources: [yt('e-ORhEE9VVg', 'Taylor Swift - Blank Space'), wiki('Blank_Space', 'Blank Space')],
    },
    {
      slug: 'style-mv',
      kind: 'music_video',
      title: 'Style',
      director: 'Joseph Kahn',
      releasedOn: '2015-02-13',
      relatedSongs: ['Style'],
      tags: ['Music'],
      summary:
        'No plot, all texture: shattered mirrors, projected faces, fog and headlights — the album\'s moodiest song gets a video made of double exposures instead of story.',
      symbolism: 'The broken-mirror shards and projections keep the two lovers overlapping without ever quite aligning — the never-out-of-style loop rendered literally.',
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=-CmadmM5cOk',
      media: [embed('-CmadmM5cOk')],
      sources: [yt('-CmadmM5cOk', 'Taylor Swift - Style'), wiki('Style_(Taylor_Swift_song)', 'Style (Taylor Swift song)')],
    },
    {
      slug: 'bad-blood-mv',
      kind: 'music_video',
      title: 'Bad Blood',
      director: 'Joseph Kahn',
      releasedOn: '2015-05-17',
      relatedSongs: ['Bad Blood'],
      tags: ['Music'],
      summary:
        'The squad-era action trailer: a betrayal, a training montage, and a cast of codenamed stars (Catastrophe, Arsyn, Knockout...) marching into a fireball — premiered at the Billboard Music Awards.',
      symbolism: null,
      easterEggs: ['Every cameo carries a comic-book codename in the credits — fans keep a full roster of who played whom.'],
      officialUrl: 'https://www.youtube.com/watch?v=QcIy9NiNbmo',
      media: [embed('QcIy9NiNbmo')],
      sources: [yt('QcIy9NiNbmo', 'Taylor Swift - Bad Blood ft. Kendrick Lamar'), wiki('Bad_Blood_(Taylor_Swift_song)', 'Bad Blood (Taylor Swift song)')],
    },
    {
      slug: 'wildest-dreams-mv',
      kind: 'music_video',
      title: 'Wildest Dreams',
      director: 'Joseph Kahn',
      releasedOn: '2015-08-30',
      relatedSongs: ['Wildest Dreams'],
      tags: ['Music'],
      summary:
        'Old-Hollywood safari melodrama: two co-stars fall for each other on a 1950s film set, and the premiere ends the romance the way the song promised it would end. Proceeds went to African Parks.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=IdneKLhsWOQ',
      media: [embed('IdneKLhsWOQ')],
      sources: [yt('IdneKLhsWOQ', 'Taylor Swift - Wildest Dreams'), wiki('Wildest_Dreams', 'Wildest Dreams')],
    },
    {
      slug: 'out-of-the-woods-mv',
      kind: 'music_video',
      title: 'Out of the Woods',
      director: 'Joseph Kahn',
      releasedOn: '2015-12-31',
      relatedSongs: ['Out of the Woods'],
      tags: ['Music'],
      summary:
        'Premiered on New Year\'s Eve: the woods literally chase Taylor — vines grab, snow buries, wolves close in — until she outruns the forest back to the beach and meets herself.',
      symbolism: 'The pursuing forest is the anxiety spiral of the lyric; arriving at her own calm self on the shore closes the loop the song leaves open.',
      easterEggs: [],
      // Official upload on Taylor's own channel — oEmbed-verified 2026-08-13
      // (author_name "Taylor Swift", title "Taylor Swift - Out Of The Woods").
      // The record shipped with no embed and rendered an unplayable card
      // (playable-first reversal, docs/decisions.md 2026-08-13).
      officialUrl: 'https://www.youtube.com/watch?v=JLf9q36UsBk',
      media: [embed('JLf9q36UsBk', '2026-08-13')],
      sources: [
        wiki('Out_of_the_Woods_(song)', 'Out of the Woods (song)'),
        press(
          'https://time.com/4164964/taylor-swift-new-music-video-out-woods-watch/',
          "Watch Taylor Swift's New Music Video 'Out of the Woods'",
          'Time',
          "supports the New Year's Eve premiere and video imagery",
        ),
        press(
          'https://www.vanityfair.com/hollywood/2015/12/taylor-swift-out-of-the-woods-music-video-announcement',
          'Taylor Swift Will Close Out Her Stellar 2015 with a New Music Video',
          'Vanity Fair',
          "supports the New Year's Rockin' Eve video-premiere setup",
        ),
      ],
    },
    {
      slug: 'new-romantics-mv',
      kind: 'music_video',
      title: 'New Romantics',
      director: 'Jonas Åkerlund',
      releasedOn: null,
      relatedSongs: ['New Romantics'],
      tags: ['Music', 'Tour'],
      summary:
        'A thank-you cut from 1989 World Tour footage — backstage, crowd waves, confetti — released as the era\'s victory lap for the fans who made the bonus track a hit.',
      symbolism: null,
      easterEggs: [],
      // oEmbed-verified 2026-08-13 (author_name "Taylor Swift", title
      // "Taylor Swift - New Romantics"). Search surfaces several higher-res
      // re-uploads of this video on fan channels; this is the one on her own
      // channel, which is the only kind that may be an officialUrl.
      officialUrl: 'https://www.youtube.com/watch?v=wyK7YuwUWsU',
      media: [embed('wyK7YuwUWsU', '2026-08-13')],
      sources: [wiki('New_Romantics_(song)', 'New Romantics (song)')],
    },
    {
      // Not a 1989 album track — a ZAYN/Taylor Swift duet for the Fifty Shades
      // Darker soundtrack, released between 1989 and reputation with no album
      // era of its own. Wikipedia describes it as "her first original song
      // since her 2014 studio album, 1989" — filed here as the contemporaneous
      // era at release, same precedent as 'Safe & Sound' (a Hunger Games
      // soundtrack single) being filed under Red in supabase/seed/videos/red.mjs.
      slug: 'i-dont-wanna-live-forever-mv',
      kind: 'music_video',
      title: "I Don't Wanna Live Forever",
      director: null,
      releasedOn: '2017-01-27',
      relatedSongs: ["I Don't Wanna Live Forever"],
      tags: ['Music'],
      summary:
        'A ZAYN/Taylor Swift duet written for the Fifty Shades Darker soundtrack — her first original song since 1989 — released December 2016, with its official video following in January 2017.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=7F37r50VUTQ',
      media: [
        {
          kind: 'oembed',
          rights: 'platform_tos',
          provider: 'youtube',
          post_url: 'https://www.youtube.com/watch?v=7F37r50VUTQ',
          oembed_fetched_at: '2026-08-25',
          attribution: 'ZAYN — official YouTube channel',
        },
      ],
      sources: [
        {
          source_url: 'https://www.youtube.com/watch?v=7F37r50VUTQ',
          source_title: "ZAYN, Taylor Swift - I Don't Wanna Live Forever (Fifty Shades Darker)",
          publisher: 'ZAYN (official YouTube channel)',
          source_type: 'official',
          accessed_at: '2026-08-25',
          reliability_score: 5,
          excerpt: null,
          notes: 'official upload, uploaded on ZAYN\'s channel rather than Taylor\'s own — this is a featured duet, not a Taylor Swift-headlined release',
        },
        wiki('I_Don%27t_Wanna_Live_Forever', "I Don't Wanna Live Forever", 'confirms release dates, soundtrack context, and "first original song since 1989" framing'),
      ],
    },
    {
      slug: 'the-1989-world-tour-live-film',
      kind: 'tour_film',
      title: 'The 1989 World Tour Live',
      director: 'Jonas Åkerlund',
      releasedOn: '2015-12-20',
      relatedSongs: [],
      tags: ['Tour'],
      summary:
        'The Sydney stadium show captured for Apple Music — light-up wristbands, the catwalk, and the era\'s guest-star ritual folded into a streaming-exclusive concert film.',
      symbolism: null,
      easterEggs: [],
      // No official upload of the work itself exists — it is an Apple Music streaming exclusive.
      // With no embed this record is HIDDEN from every reader-facing surface
      // rather than shown as a card that cannot play (playable-first rule,
      // docs/decisions.md 2026-08-13). Add a verified official upload here and
      // it comes back automatically — no code change needed.
      officialUrl: null,
      media: [],
      sources: [
        wiki('The_1989_World_Tour_Live', 'The 1989 World Tour Live'),
        press(
          'https://www.billboard.com/music/pop/taylor-swift-1989-world-tour-live-concert-film-apple-music-6805694/',
          "Taylor Swift '1989 World Tour Live' Concert Film Coming to Apple Music: Watch Trailer",
          'Billboard',
          'supports the Apple Music concert-film release and Sydney-tour-film framing',
        ),
      ],
    },
    // ── YouTube catalog additions (issue #3286, batch C, 2026-08-25) ────────
    {
      slug: 'ice-bucket-challenge-with-jamie-king',
      kind: 'documentary',
      title: 'Ice Bucket Challenge with Jamie King',
      director: null,
      // Official channel upload is dated 2014-10-06, but contemporaneous press
      // (MTV, Just Jared) places the actual VMA-rehearsal event on 2014-08-16 —
      // the real-world date is used here per docs/decisions.md's era-by-real-
      // date rule.
      releasedOn: '2014-08-16',
      relatedSongs: [],
      tags: [],
      summary:
        'Nominated by Lily Aldridge and friends, Taylor and Jamie King take the ALS Ice Bucket Challenge together during a break in VMA rehearsals, then nominate Selena Gomez, Emma Stone, and Ed Sheeran.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=AoYtgGHfsG4',
      media: [embed('AoYtgGHfsG4', '2026-08-25')],
      sources: [
        yt('AoYtgGHfsG4', 'Taylor Swift Ice Bucket Challenge with Jamie King'),
        press(
          'https://www.mtv.com/news/gkiyef/taylor-swift-ice-bucket-challenge',
          'Taylor Swift Just Took The Ice Bucket Challenge -- Watch Her Get Drenched',
          'MTV',
          'confirms the August 16, 2014 VMA-rehearsal date, ahead of the official channel\'s later October upload',
        ),
      ],
    },
    {
      slug: 'worldwide-live-stream-yahoo-highlights',
      kind: 'documentary',
      title: "Taylor Swift's Worldwide Live Stream on Yahoo — Highlights",
      director: null,
      releasedOn: '2014-08-18',
      relatedSongs: ['Shake It Off'],
      tags: ['Music'],
      summary:
        'Highlights from the global Yahoo livestream Taylor hosted the day she announced 1989 and released "Shake It Off."',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=1D5E5KLkfsI',
      media: [embed('1D5E5KLkfsI', '2026-08-25')],
      sources: [yt('1D5E5KLkfsI', "Taylor Swift's Worldwide Live Stream on Yahoo - Highlights")],
    },
    {
      slug: 'shake-it-off-outtakes-1-cheerleaders',
      kind: 'documentary',
      title: 'Shake It Off Outtakes Video #1 - The Cheerleaders',
      director: null,
      releasedOn: '2014-09-11',
      relatedSongs: ['Shake It Off'],
      tags: ['Music'],
      summary:
        'The first outtakes cut from the "Shake It Off" shoot: the cheerleaders get their own behind-the-scenes video, the opening entry in an eight-part weekly series.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=TEpTNFHHjNg',
      media: [embed('TEpTNFHHjNg', '2026-08-25')],
      sources: [yt('TEpTNFHHjNg', 'Taylor Swift - Shake It Off Outtakes Video #1 - The Cheerleaders (Behind The Scenes Video)')],
    },
    {
      slug: 'shake-it-off-outtakes-2-ballerinas',
      kind: 'documentary',
      title: 'Shake It Off Outtakes Video #2 - The Ballerinas',
      director: null,
      releasedOn: '2014-09-11',
      relatedSongs: ['Shake It Off'],
      tags: ['Music'],
      summary:
        'Outtakes #2 from the "Shake It Off" shoot, behind the scenes with the ballerinas.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=kY-_D-IptZE',
      media: [embed('kY-_D-IptZE', '2026-08-25')],
      sources: [yt('kY-_D-IptZE', 'Taylor Swift - Shake It Off Outtakes Video #2 - The Ballerinas (Behind The Scenes Video)')],
    },
    {
      slug: 'shake-it-off-outtakes-3-modern-dancers',
      kind: 'documentary',
      title: 'Shake It Off Outtakes Video #3 - The Modern Dancers',
      director: null,
      releasedOn: '2014-09-11',
      relatedSongs: ['Shake It Off'],
      tags: ['Music'],
      summary:
        'Outtakes #3 from the "Shake It Off" shoot, behind the scenes with the modern dancers.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=zdYy6-P_ggQ',
      media: [embed('zdYy6-P_ggQ', '2026-08-25')],
      sources: [yt('zdYy6-P_ggQ', 'Taylor Swift - Shake It Off Outtakes Video #3 - The Modern Dancers (Behind The Scenes Video)')],
    },
    {
      slug: 'shake-it-off-outtakes-4-animators',
      kind: 'documentary',
      title: 'Shake It Off Outtakes Video #4 - The Animators',
      director: null,
      releasedOn: '2014-09-16',
      relatedSongs: ['Shake It Off'],
      tags: ['Music'],
      summary:
        'Outtakes #4 from the "Shake It Off" shoot, behind the scenes with the animators.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=vMWpIfxvnWo',
      media: [embed('vMWpIfxvnWo', '2026-08-25')],
      sources: [yt('vMWpIfxvnWo', 'Taylor Swift - Shake It Off Outtakes Video #4 - The Animators (Behind The Scenes Video)')],
    },
    {
      slug: 'shake-it-off-outtakes-5-twerkers',
      kind: 'documentary',
      title: 'Shake It Off Outtakes Video #5 - The Twerkers and Finger Tutting',
      director: null,
      releasedOn: '2014-09-23',
      relatedSongs: ['Shake It Off'],
      tags: ['Music'],
      summary:
        'Outtakes #5 from the "Shake It Off" shoot, behind the scenes with the twerkers and finger-tutting dancers.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=70Ps-GzbSfw',
      media: [embed('70Ps-GzbSfw', '2026-08-25')],
      sources: [yt('70Ps-GzbSfw', 'Shake It Off Outtakes Video #5 - The Twerkers and Finger Tutting (Behind-The-Scenes Video)')],
    },
    {
      slug: 'shake-it-off-outtakes-6-ribbon-dancers',
      kind: 'documentary',
      title: 'Shake It Off Outtakes Video #6 - The Ribbon Dancers',
      director: null,
      releasedOn: '2014-09-30',
      relatedSongs: ['Shake It Off'],
      tags: ['Music'],
      summary:
        'Outtakes #6 from the "Shake It Off" shoot, behind the scenes with the ribbon dancers.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=bs5SZOHowHI',
      media: [embed('bs5SZOHowHI', '2026-08-25')],
      sources: [yt('bs5SZOHowHI', 'Taylor Swift - Shake It Off Outtakes Video #6 - The Ribbon Dancers (Behind The Scenes Video)')],
    },
    {
      slug: 'shake-it-off-outtakes-7-band-fans-extras',
      kind: 'documentary',
      title: 'Shake It Off Outtakes Video #7 - The Band, The Fans and The Extras',
      director: null,
      releasedOn: '2014-10-07',
      relatedSongs: ['Shake It Off'],
      tags: ['Music'],
      summary:
        'Outtakes #7 from the "Shake It Off" shoot, behind the scenes with the band, the fans, and the extras.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=s8h0tZy0HqA',
      media: [embed('s8h0tZy0HqA', '2026-08-25')],
      sources: [yt('s8h0tZy0HqA', 'Taylor Swift - Shake It Off Outtakes Video #7 - The Band, The Fans and The Extras')],
    },
    {
      slug: 'shake-it-off-outtakes-8-director',
      kind: 'documentary',
      title: 'Shake It Off Outtakes Video #8 - The Director',
      director: null,
      releasedOn: '2014-10-14',
      relatedSongs: ['Shake It Off'],
      tags: ['Music'],
      summary:
        'The final outtakes cut from the "Shake It Off" shoot, closing the eight-part series with a look at the director\'s side of the set.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=DqZOcABIgTk',
      media: [embed('DqZOcABIgTk', '2026-08-25')],
      sources: [yt('DqZOcABIgTk', 'Taylor Swift - Shake It Off Outtakes Video #8 - The Director')],
    },
    {
      slug: '1989-secret-sessions-bts',
      kind: 'documentary',
      title: '1989 Secret Sessions, Behind The Scenes!',
      director: null,
      releasedOn: '2014-10-16',
      relatedSongs: [],
      tags: ['Music'],
      summary:
        'Behind the scenes of the #1989SecretSessions — the top-secret listening parties where Taylor tracked down fans across the US and UK on social media and invited them to her homes to hear 1989 before release.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=EKnl7STzSMU',
      media: [embed('EKnl7STzSMU', '2026-08-25')],
      sources: [yt('EKnl7STzSMU', '1989 Secret Sessions, Behind The Scenes!')],
    },
    {
      slug: 'incredible-things-fragrance-bts',
      kind: 'documentary',
      title: 'Behind The Fragrance: Taylor Swift Incredible Things',
      director: null,
      releasedOn: '2014-12-15',
      relatedSongs: ['Blank Space'],
      tags: [],
      summary:
        'The story behind Taylor\'s fragrance Incredible Things — named for the "Blank Space" lyric — with Taylor on set explaining the name and the inspiration behind the scent.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=BxZi6jC2JAI',
      media: [embed('BxZi6jC2JAI', '2026-08-25')],
      sources: [yt('BxZi6jC2JAI', 'Behind The Fragrance, Taylor Swift Incredible Things featuring Taylor Swift (Behind The Scenes)')],
    },
    {
      slug: 'swiftmas-2014',
      kind: 'documentary',
      title: "Taylor Swift's Gift Giving of 2014 | SWIFTMAS",
      director: null,
      releasedOn: '2014-12-31',
      relatedSongs: [],
      tags: [],
      summary:
        'After the #TayLurking phenomenon saw fans track every detail of her online, Taylor spent the run-up to Christmas secretly shipping personally chosen gifts to dozens of fans and documented the surprise deliveries as #Swiftmas.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=j3yyF31jbKo',
      media: [embed('j3yyF31jbKo', '2026-08-25')],
      sources: [yt('j3yyF31jbKo', "Taylor Swift's Gift Giving of 2014 | SWIFTMAS")],
    },
    {
      slug: 'wildest-dreams-grammy-museum',
      kind: 'performance',
      title: 'Wildest Dreams — The GRAMMY Museum',
      director: null,
      releasedOn: '2016-01-04',
      relatedSongs: ['Wildest Dreams'],
      tags: ['Music'],
      summary:
        'A stripped-down "Wildest Dreams" performed live at the GRAMMY Museum in Los Angeles, filmed for the museum\'s official channel.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=OGDkg3QiJmk',
      media: [embed('OGDkg3QiJmk', '2026-08-25')],
      sources: [yt('OGDkg3QiJmk', 'Taylor Performs "Wildest Dreams" at The GRAMMY Museum')],
    },
    {
      slug: 'blank-space-grammy-museum',
      kind: 'performance',
      title: 'Blank Space — The GRAMMY Museum',
      director: null,
      releasedOn: '2016-01-07',
      relatedSongs: ['Blank Space'],
      tags: ['Music'],
      summary:
        'A stripped-down "Blank Space" performed live at the GRAMMY Museum in Los Angeles, filmed for the museum\'s official channel.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=p1Zt47V3pPw',
      media: [embed('p1Zt47V3pPw', '2026-08-25')],
      sources: [yt('p1Zt47V3pPw', 'Taylor performs "Blank Space" at The GRAMMY Museum')],
    },
    {
      slug: 'out-of-the-woods-making-of',
      kind: 'documentary',
      title: 'Out Of The Woods — The Making Of',
      director: null,
      releasedOn: '2016-02-09',
      relatedSongs: ['Out of the Woods'],
      tags: ['Music'],
      summary:
        'The making of the "Out of the Woods" music video — the practical effects behind the pursuing forest and wolves, and the New Year\'s Eve premiere shoot, from the crew and Taylor.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=TXJlB9riS1Y',
      media: [embed('TXJlB9riS1Y', '2026-08-25')],
      sources: [yt('TXJlB9riS1Y', 'Taylor Swift - Out Of The Woods – The Making Of')],
    },
    {
      slug: 'i-dont-wanna-live-forever-bts-key-light',
      kind: 'documentary',
      title: "I Don't Wanna Live Forever (Fifty Shades Darker) BTS 2 - Key Light?",
      director: null,
      releasedOn: '2017-01-27',
      relatedSongs: ["I Don't Wanna Live Forever"],
      tags: [],
      summary:
        'Behind-the-scenes lighting setup from the "I Don\'t Wanna Live Forever" shoot with ZAYN and Taylor.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=OsJ5RyWpY5w',
      media: [embed('OsJ5RyWpY5w', '2026-08-25')],
      sources: [yt('OsJ5RyWpY5w', "I Don't Wanna Live Forever (Fifty Shades Darker) BTS 2 - Key Light? [EXTENDED]")],
    },
    {
      slug: 'i-dont-wanna-live-forever-bts-zayn-taylor',
      kind: 'documentary',
      title: "I Don't Wanna Live Forever (Fifty Shades Darker) BTS 1 - Zayn & Taylor",
      director: null,
      releasedOn: '2017-01-27',
      relatedSongs: ["I Don't Wanna Live Forever"],
      tags: [],
      summary:
        'Behind-the-scenes footage of ZAYN and Taylor together on set for the "I Don\'t Wanna Live Forever" shoot.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=QIUWI7dfnC0',
      media: [embed('QIUWI7dfnC0', '2026-08-25')],
      sources: [yt('QIUWI7dfnC0', "I Don't Wanna Live Forever (Fifty Shades Darker) BTS 1 - Zayn & Taylor [EXTENDED]")],
    },
    {
      slug: 'i-dont-wanna-live-forever-bts-glitter-lip',
      kind: 'documentary',
      title: "I Don't Wanna Live Forever (Fifty Shades Darker) BTS 4 – Glitter Lip",
      director: null,
      releasedOn: '2017-02-01',
      relatedSongs: ["I Don't Wanna Live Forever"],
      tags: [],
      summary:
        'Behind-the-scenes footage of the glitter-lip makeup setup from the "I Don\'t Wanna Live Forever" shoot with ZAYN and Taylor.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=dwdtzwua2pY',
      media: [embed('dwdtzwua2pY', '2026-08-25')],
      sources: [yt('dwdtzwua2pY', "Taylor Swift, ZAYN - I Don't Wanna Live Forever (Fifty Shades Darker) BTS 4 – Glitter Lip [EXTENDED]")],
    },
    {
      slug: 'i-dont-wanna-live-forever-directv-now-rehearsal',
      kind: 'documentary',
      title: "Rehearsing \"I Don't Wanna Live Forever\" for DIRECTV NOW Super Saturday Night",
      director: null,
      releasedOn: '2017-02-02',
      relatedSongs: ["I Don't Wanna Live Forever"],
      tags: [],
      summary:
        'Rehearsal footage from Houston, TX ahead of the DIRECTV NOW Super Saturday Night live TV special, built around Super Bowl LI weekend.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=J37Pitvp7RI',
      media: [embed('J37Pitvp7RI', '2026-08-25')],
      sources: [yt('J37Pitvp7RI', 'Rehearsing "I Don\'t Wanna Live Forever (Fifty Shades Darker)" for DIRECTV NOW Super Saturday Night')],
    },
    // ── Appearances (YouTube-appearances pass, 2026-08-12) ──────────────────
    appearance({
      slug: 'grammys-album-of-the-year-2016',
      kind: 'award_speech',
      title: 'Accepting Album of the Year for 1989 — 58th GRAMMYs',
      releasedOn: '2016-02-15',
      summary:
        'A second Album of the Year makes her the first woman to win it twice — and she closes with advice to any young woman watching: there will be people who try to undercut your success.',
      youtubeId: 'dMCAEUb0h34',
      channel: 'GRAMMYS',
      attribution: "GRAMMYs — the Recording Academy's official YouTube channel",
      tags: ['Music'],
      sources: [
        upload({
          youtubeId: 'dMCAEUb0h34',
          title: 'Taylor Swift | Album of the Year | 58th GRAMMYs',
          channel: 'GRAMMYS',
          note: "official upload on the Recording Academy's own channel — oEmbed-verified 2026-08-12",
        }),
        pressSource(
          'https://time.com/4225261/2016-grammys-taylor-swift-kanye-west/',
          "Taylor Swift's Grammys Speech",
          'Time',
          'reports the speech and the reaction to it',
        ),
      ],
    }),
  ],
};
