// Vault videos — debut era. Official uploads verified via YouTube oEmbed
// 2026-07-08; Wikipedia URLs verified the same day.

const wiki = (article, title, notes) => ({
  source_url: `https://en.wikipedia.org/wiki/${article}`,
  source_title: title,
  publisher: 'Wikipedia',
  source_type: 'wiki',
  accessed_at: '2026-07-08',
  reliability_score: 2,
  excerpt: null,
  notes: notes ?? 'anchors the video, director, and background',
});
const yt = (id, title) => ({
  source_url: `https://www.youtube.com/watch?v=${id}`,
  source_title: title,
  publisher: 'Taylor Swift (official YouTube channel)',
  source_type: 'official',
  accessed_at: '2026-07-08',
  reliability_score: 5,
  excerpt: null,
  notes: 'official upload — verified via YouTube oEmbed 2026-07-08',
});
const press = (source_url, source_title, publisher, notes) => ({
  source_url,
  source_title,
  publisher,
  source_type: 'reputable_press',
  accessed_at: '2026-07-09',
  reliability_score: 4,
  excerpt: null,
  notes,
});
const embed = (id, fetchedOn = '2026-07-08') => ({
  kind: 'oembed',
  rights: 'platform_tos',
  provider: 'youtube',
  post_url: `https://www.youtube.com/watch?v=${id}`,
  oembed_fetched_at: fetchedOn,
  attribution: 'Taylor Swift — official YouTube channel',
});

import { appearance, pressSource, upload } from './_appearance-helpers.mjs';

export default {
  eraSlug: 'debut',
  videos: [
    {
      slug: 'tim-mcgraw-mv',
      kind: 'music_video',
      title: 'Tim McGraw',
      director: 'Trey Fanjoy',
      releasedOn: null,
      relatedSongs: ['Tim McGraw'],
      tags: ['Music'],
      summary:
        'The first video: a sun-flared lakeside memory reel — a 16-year-old Taylor in a white sundress, a Chevy truck, a summer already turning into a song about being remembered.',
      symbolism:
        'Establishes the visual grammar her early videos reuse: golden-hour nostalgia, the letter/memory motif, and Taylor as narrator of her own past.',
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=GkD20ajVxnY',
      media: [embed('GkD20ajVxnY')],
      sources: [yt('GkD20ajVxnY', 'Taylor Swift - Tim McGraw'), wiki('Tim_McGraw_(song)', 'Tim McGraw (song)')],
    },
    {
      slug: 'teardrops-on-my-guitar-mv',
      kind: 'music_video',
      title: 'Teardrops on My Guitar',
      director: 'Trey Fanjoy',
      releasedOn: null,
      relatedSongs: ['Teardrops on My Guitar'],
      tags: ['Music'],
      summary:
        'High-school hallways and a bedroom confessional: Taylor watches Drew from the next locker over, then tells the guitar what she can\'t tell him.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=xKCek6_dB0M',
      media: [embed('xKCek6_dB0M')],
      sources: [yt('xKCek6_dB0M', 'Taylor Swift - Teardrops On My Guitar'), wiki('Teardrops_on_My_Guitar', 'Teardrops on My Guitar')],
    },
    {
      slug: 'our-song-mv',
      kind: 'music_video',
      title: 'Our Song',
      director: 'Trey Fanjoy',
      releasedOn: null,
      relatedSongs: ['Our Song'],
      tags: ['Music'],
      summary:
        'Front-porch performance piece — barefoot on the steps in a blue dress, then a flower-drenched fantasy set, for the song she wrote for her ninth-grade talent show.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=Jb2stN7kH28',
      media: [embed('Jb2stN7kH28')],
      sources: [yt('Jb2stN7kH28', 'Taylor Swift - Our Song'), wiki('Our_Song_(Taylor_Swift_song)', 'Our Song (Taylor Swift song)')],
    },
    {
      slug: 'shouldve-said-no-mv',
      kind: 'music_video',
      title: "Should've Said No",
      director: 'Trey Fanjoy',
      releasedOn: null,
      relatedSongs: ["Should've Said No"],
      tags: ['Music'],
      summary:
        'Built from her live 43rd ACM Awards performance: hooded-sweatshirt confessional through a costume change into a black dress, closing on the last lines sung in pouring stage rain.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=v9bxXO9fj98',
      media: [embed('v9bxXO9fj98')],
      sources: [
        yt('v9bxXO9fj98', "Should've Said No"),
        wiki("Should've_Said_No", "Should've Said No"),
      ],
    },
    {
      slug: 'picture-to-burn-mv',
      kind: 'music_video',
      title: 'Picture to Burn',
      director: 'Trey Fanjoy',
      releasedOn: null,
      relatedSongs: ['Picture to Burn'],
      tags: ['Music'],
      summary:
        'Revenge fantasy: Taylor and her friend Abigail spy on the ex from a parked truck, then Taylor leads her band inside to trash his house in her imagination while Abigail keeps watch outside — the first of many satirical self-aware villain turns.',
      symbolism: null,
      easterEggs: [],
      // oEmbed-verified 2026-08-13 (author_name "Taylor Swift", title
      // "Taylor Swift - Picture To Burn").
      officialUrl: 'https://www.youtube.com/watch?v=yCMqcFAigRg',
      media: [embed('yCMqcFAigRg', '2026-08-13')],
      sources: [
        wiki('Picture_to_Burn', 'Picture to Burn'),
        press(
          'https://theboot.com/video-premiere-picture-to-burn-taylor-swift/',
          "Video Premiere: 'Picture to Burn,' Taylor Swift",
          'The Boot',
          'supports the music-video premiere and early-video revenge-comedy framing',
        ),
      ],
    },
    // ── Live From Clear Channel Stripped 2008 (catalog pass 2026-08-25,
    // issue #3286). A promotional acoustic radio session recorded June 8,
    // 2008 — before the Nov 11, 2008 Fearless release, so filed here per the
    // era-by-real-date rule even though two of the seven songs (Fearless,
    // Love Story) are Fearless-album tracks performed ahead of release. The
    // session's audio was later packaged into an unauthorized 2020 Big
    // Machine release, unrelated to these individual YouTube uploads.
    {
      slug: 'fearless-live-clear-channel-stripped-2008',
      kind: 'performance',
      title: 'Taylor Swift - Fearless (Live From Clear Channel Stripped 2008 / Audio)',
      director: null,
      releasedOn: '2008-06-08',
      relatedSongs: ['Fearless'],
      tags: ['Music'],
      summary: 'An early acoustic performance of "Fearless," recorded months before the album of the same name was released.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=Tj6qU4dlKeA',
      media: [embed('Tj6qU4dlKeA', '2026-08-25')],
      sources: [
        yt('Tj6qU4dlKeA', 'Taylor Swift - Fearless (Live From Clear Channel Stripped 2008 / Audio)'),
        wiki('Live_from_Clear_Channel_Stripped_2008', 'Live from Clear Channel Stripped 2008', 'documents the June 8, 2008 recording date'),
      ],
    },
    {
      slug: 'love-story-live-clear-channel-stripped-2008',
      kind: 'performance',
      title: 'Taylor Swift - Love Story (Live From Clear Channel Stripped 2008 / Audio)',
      director: null,
      releasedOn: '2008-06-08',
      relatedSongs: ['Love Story'],
      tags: ['Music'],
      summary: 'An early acoustic performance of "Love Story," recorded months before the Fearless album\'s release.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=opS9a1_PuWA',
      media: [embed('opS9a1_PuWA', '2026-08-25')],
      sources: [
        yt('opS9a1_PuWA', 'Taylor Swift - Love Story (Live From Clear Channel Stripped 2008 / Audio)'),
        wiki('Live_from_Clear_Channel_Stripped_2008', 'Live from Clear Channel Stripped 2008', 'documents the June 8, 2008 recording date'),
      ],
    },
    {
      slug: 'untouchable-live-clear-channel-stripped-2008',
      kind: 'performance',
      title: 'Taylor Swift - Untouchable (Live From Clear Channel Stripped 2008 / Audio)',
      director: null,
      releasedOn: '2008-06-08',
      relatedSongs: ['Untouchable'],
      tags: ['Music'],
      summary: 'An acoustic performance of the Fearless bonus track "Untouchable" from the 2008 Clear Channel Stripped session.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=o_CgCUINYmQ',
      media: [embed('o_CgCUINYmQ', '2026-08-25')],
      sources: [
        yt('o_CgCUINYmQ', 'Taylor Swift - Untouchable (Live From Clear Channel Stripped 2008 / Audio)'),
        wiki('Live_from_Clear_Channel_Stripped_2008', 'Live from Clear Channel Stripped 2008', 'documents the June 8, 2008 recording date'),
      ],
    },
    {
      slug: 'picture-to-burn-live-clear-channel-stripped-2008',
      kind: 'performance',
      title: 'Taylor Swift - Picture To Burn (Live From Clear Channel Stripped 2008 / Audio)',
      director: null,
      releasedOn: '2008-06-08',
      relatedSongs: ['Picture to Burn'],
      tags: ['Music'],
      summary: 'An acoustic performance of "Picture to Burn" from the 2008 Clear Channel Stripped session.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=kX6h4gDYLzM',
      media: [embed('kX6h4gDYLzM', '2026-08-25')],
      sources: [
        yt('kX6h4gDYLzM', 'Taylor Swift - Picture To Burn (Live From Clear Channel Stripped 2008 / Audio)'),
        wiki('Live_from_Clear_Channel_Stripped_2008', 'Live from Clear Channel Stripped 2008', 'documents the June 8, 2008 recording date'),
      ],
    },
    {
      slug: 'change-live-clear-channel-stripped-2008',
      kind: 'performance',
      title: 'Taylor Swift - Change (Live From Clear Channel Stripped 2008 / Audio)',
      director: null,
      releasedOn: '2008-06-08',
      relatedSongs: ['Change'],
      tags: ['Music'],
      summary: 'An acoustic performance of the debut-album bonus track "Change" from the 2008 Clear Channel Stripped session.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=QDiyzUSx288',
      media: [embed('QDiyzUSx288', '2026-08-25')],
      sources: [
        yt('QDiyzUSx288', 'Taylor Swift - Change (Live From Clear Channel Stripped 2008 / Audio)'),
        wiki('Live_from_Clear_Channel_Stripped_2008', 'Live from Clear Channel Stripped 2008', 'documents the June 8, 2008 recording date'),
      ],
    },
    {
      slug: 'shouldve-said-no-live-clear-channel-stripped-2008',
      kind: 'performance',
      title: "Taylor Swift - Should've Said No (Live From Clear Channel Stripped 2008 / Audio)",
      director: null,
      releasedOn: '2008-06-08',
      relatedSongs: ["Should've Said No"],
      tags: ['Music'],
      summary: "An acoustic performance of \"Should've Said No\" from the 2008 Clear Channel Stripped session.",
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=FydBi2b_eoA',
      media: [embed('FydBi2b_eoA', '2026-08-25')],
      sources: [
        yt('FydBi2b_eoA', "Taylor Swift - Should've Said No (Live From Clear Channel Stripped 2008 / Audio)"),
        wiki('Live_from_Clear_Channel_Stripped_2008', 'Live from Clear Channel Stripped 2008', 'documents the June 8, 2008 recording date'),
      ],
    },
    {
      slug: 'beautiful-eyes-live-clear-channel-stripped-2008',
      kind: 'performance',
      title: 'Taylor Swift - Beautiful Eyes (Live From Clear Channel Stripped 2008 / Audio)',
      director: null,
      releasedOn: '2008-06-08',
      relatedSongs: ['Beautiful Eyes'],
      tags: ['Music'],
      summary: 'An acoustic performance of the "Beautiful Eyes" EP title track from the 2008 Clear Channel Stripped session.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=2SXLyqKAFYU',
      media: [embed('2SXLyqKAFYU', '2026-08-25')],
      sources: [
        yt('2SXLyqKAFYU', 'Taylor Swift - Beautiful Eyes (Live From Clear Channel Stripped 2008 / Audio)'),
        wiki('Live_from_Clear_Channel_Stripped_2008', 'Live from Clear Channel Stripped 2008', 'documents the June 8, 2008 recording date'),
      ],
    },
    // ── Appearances (YouTube-appearances pass, 2026-08-12) ──────────────────
    appearance({
      slug: 'ellen-first-interview-2008',
      kind: 'interview',
      title: 'First interview on The Ellen DeGeneres Show',
      releasedOn: '2008-01-17',
      summary:
        "Eighteen years old and one album in, with 'Teardrops on My Guitar' crossing over to pop radio: her first talk-show sit-down, on a couch she would keep coming back to for the next decade.",
      youtubeId: 'vBgiDYBCuxY',
      channel: 'TheEllenShow',
      sources: [
        upload({
          youtubeId: 'vBgiDYBCuxY',
          title: "Taylor Swift's First Interview with Ellen!",
          channel: 'TheEllenShow',
        }),
        pressSource(
          'https://www.billboard.com/music/music-news/taylor-swift-ellen-appearances-8511659/',
          "Taylor Swift's Best Moments on 'Ellen'",
          'Billboard',
          'dates the first appearance to Jan. 17, 2008 and tracks the run of return visits',
        ),
      ],
    }),
  ],
};
