// Vault videos — Red era. Official uploads verified via YouTube oEmbed
// 2026-07-08; Wikipedia URLs verified the same day.

const wiki = (article, title, notes) => ({
  source_url: `https://en.wikipedia.org/wiki/${article}`,
  source_title: title,
  publisher: 'Wikipedia',
  source_type: 'wiki',
  accessed_at: '2026-07-08',
  reliability_score: 2,
  excerpt: null,
  notes: notes ?? 'anchors the video, director, and background',
});
const yt = (id, title) => ({
  source_url: `https://www.youtube.com/watch?v=${id}`,
  source_title: title,
  publisher: 'Taylor Swift (official YouTube channel)',
  source_type: 'official',
  accessed_at: '2026-07-08',
  reliability_score: 5,
  excerpt: null,
  notes: 'official upload — verified via YouTube oEmbed 2026-07-08',
});
const press = (source_url, source_title, publisher, notes) => ({
  source_url,
  source_title,
  publisher,
  source_type: 'reputable_press',
  accessed_at: '2026-07-09',
  reliability_score: 4,
  excerpt: null,
  notes,
});
const embed = (id, fetchedOn = '2026-07-08') => ({
  kind: 'oembed',
  rights: 'platform_tos',
  provider: 'youtube',
  post_url: `https://www.youtube.com/watch?v=${id}`,
  oembed_fetched_at: fetchedOn,
  attribution: 'Taylor Swift — official YouTube channel',
});

export default {
  eraSlug: 'red',
  videos: [
    {
      slug: 'safe-and-sound-mv',
      kind: 'music_video',
      title: 'Safe & Sound',
      director: null,
      releasedOn: '2012-02-13',
      relatedSongs: ['Safe & Sound'],
      tags: ['Music'],
      summary:
        'A barefoot walk through a Watertown, Tennessee forest and cemetery in a long white gown, intercut with The Civil Wars performing by firelight — recorded for The Hunger Games soundtrack, dotted with mockingjay references.',
      symbolism: null,
      easterEggs: ['Taylor finds a mockingjay pin during the woods sequence, tying the video to the film\'s central symbol.'],
      officialUrl: 'https://www.youtube.com/watch?v=RzhAS_GnJIc',
      media: [embed('RzhAS_GnJIc')],
      sources: [
        yt('RzhAS_GnJIc', 'Safe & Sound feat. The Civil Wars (The Hunger Games: Songs From District 12 And Beyond)'),
        wiki('Safe_%26_Sound_(Taylor_Swift_song)', 'Safe & Sound (Taylor Swift song)'),
      ],
    },
    {
      slug: 'red-mv',
      kind: 'music_video',
      title: 'Red',
      director: 'Kenny Jackson',
      releasedOn: '2013-07-03',
      relatedSongs: ['Red'],
      tags: ['Music'],
      summary:
        'An edited concert-performance video cut from live shows in front of thousands of fans, rather than a scripted narrative — the album\'s fifth single.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=Zlot0i3Zykw',
      media: [embed('Zlot0i3Zykw')],
      sources: [yt('Zlot0i3Zykw', 'Taylor Swift - Red'), wiki('Red_(Taylor_Swift_song)', 'Red (Taylor Swift song)')],
    },
    {
      slug: 'we-are-never-ever-getting-back-together-mv',
      kind: 'music_video',
      title: 'We Are Never Ever Getting Back Together',
      director: 'Declan Whitebloom',
      releasedOn: null,
      relatedSongs: ['We Are Never Ever Getting Back Together'],
      tags: ['Music'],
      summary:
        'Styled as one continuous take through a storybook house party — pajamas, a phone call, and a band in animal costumes — for her first Hot 100 #1.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=WA4iX5D9Z64',
      media: [embed('WA4iX5D9Z64')],
      sources: [yt('WA4iX5D9Z64', 'Taylor Swift - We Are Never Ever Getting Back Together'), wiki('We_Are_Never_Ever_Getting_Back_Together', 'We Are Never Ever Getting Back Together')],
    },
    {
      slug: 'i-knew-you-were-trouble-mv',
      kind: 'music_video',
      title: 'I Knew You Were Trouble',
      director: 'Anthony Mandler',
      releasedOn: null,
      relatedSongs: ['I Knew You Were Trouble'],
      tags: ['Music'],
      summary:
        'A two-minute spoken prologue, a desert festival, a doomed bad-boy romance told in flashback grit — the era\'s deliberate swerve from country sweetheart staging into pop cinema.',
      symbolism: 'Waking up alone in the desert bookends the story: the video opens on the aftermath and spends its runtime explaining the wreckage.',
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=vNoKguSdy4Y',
      media: [embed('vNoKguSdy4Y')],
      sources: [yt('vNoKguSdy4Y', 'Taylor Swift - I Knew You Were Trouble'), wiki('I_Knew_You_Were_Trouble', 'I Knew You Were Trouble')],
    },
    {
      slug: '22-mv',
      kind: 'music_video',
      title: '22',
      director: 'Anthony Mandler',
      releasedOn: null,
      relatedSongs: ['22'],
      tags: ['Music'],
      summary:
        'Shot like a home movie of the best day off ever: real-friends hangout energy, the "not a lot going on at the moment" tee, a beach-party ending — breakfast at midnight canonized.',
      symbolism: null,
      easterEggs: [
        'Anti-Hero\'s party ghosts wear the 22 video\'s heart-shaped sunglasses and cat ears, and the "not a lot going on at the moment" tee returned — reworded — as an Eras Tour costume.',
      ],
      officialUrl: 'https://www.youtube.com/watch?v=AgFeZr5ptV8',
      media: [embed('AgFeZr5ptV8')],
      sources: [yt('AgFeZr5ptV8', 'Taylor Swift - 22'), wiki('22_(Taylor_Swift_song)', '22 (Taylor Swift song)')],
    },
    {
      slug: 'everything-has-changed-mv',
      kind: 'music_video',
      title: 'Everything Has Changed',
      director: 'Philip Andelman',
      releasedOn: null,
      relatedSongs: ['Everything Has Changed'],
      tags: ['Music'],
      summary:
        'Two grade-schoolers play out the duet\'s friendship-into-something-more — and the kicker reveals Taylor and Ed Sheeran as the parents picking them up.',
      symbolism: null,
      easterEggs: [],
      // oEmbed-verified 2026-08-13 (author_name "Taylor Swift", title "Taylor
      // Swift - Everything Has Changed ft. Ed Sheeran") — the 2013 original.
      officialUrl: 'https://www.youtube.com/watch?v=w1oM3kQpXRo',
      media: [embed('w1oM3kQpXRo', '2026-08-13')],
      sources: [
        wiki('Everything_Has_Changed', 'Everything Has Changed'),
        press(
          'https://www.billboard.com/music/music-news/taylor-swift-ed-sheeran-return-to-childhood-in-everything-has-changed-video-watch-1565874/',
          "Taylor Swift, Ed Sheeran Return to Childhood in 'Everything Has Changed' Video: Watch",
          'Billboard',
          'supports the Philip Andelman video release and child-counterpart story framing',
        ),
      ],
    },
    {
      slug: 'the-last-time-mv',
      kind: 'music_video',
      title: 'The Last Time',
      director: null,
      releasedOn: null,
      relatedSongs: ['The Last Time'],
      tags: ['Music'],
      summary:
        'A live-performance video built from Red Tour footage of Taylor and duet partner Gary Lightbody trading the song\'s dueling verses onstage, seated on facing stools — the album\'s final single.',
      symbolism: null,
      easterEggs: [],
      // oEmbed-verified 2026-08-24 (author_name "Taylor Swift", title "Taylor
      // Swift - The Last Time ft. Gary Lightbody").
      officialUrl: 'https://www.youtube.com/watch?v=QuijXg8wm28',
      media: [embed('QuijXg8wm28', '2026-08-24')],
      sources: [
        yt('QuijXg8wm28', 'Taylor Swift - The Last Time ft. Gary Lightbody'),
        wiki('The_Last_Time_(Taylor_Swift_song)', 'The Last Time (Taylor Swift song)'),
      ],
    },
    {
      slug: 'begin-again-mv',
      kind: 'music_video',
      title: 'Begin Again',
      director: 'Philip Andelman',
      releasedOn: null,
      relatedSongs: ['Begin Again'],
      tags: ['Music'],
      summary:
        'Shot in Paris: a slow, sunlit walk out of one story and into the possibility of another — café tables, cobblestones, and the album\'s gentlest landing.',
      symbolism: null,
      easterEggs: [],
      // oEmbed-verified 2026-08-13 (author_name "Taylor Swift", title "Taylor
      // Swift - Begin Again"). Same id the red.mjs timeline moment already
      // embeds, so the Videos filter de-dupes this record against the moment
      // (eraVideoFeed) — by design; the rail still carries it.
      officialUrl: 'https://www.youtube.com/watch?v=cMPEd8m79Hw',
      media: [embed('cMPEd8m79Hw', '2026-08-13')],
      sources: [
        wiki('Begin_Again_(Taylor_Swift_song)', 'Begin Again (Taylor Swift song)'),
        press(
          'https://tasteofcountry.com/taylor-swift-begin-again-video/',
          "Taylor Swift Starts Over in Scenic 'Begin Again' Video",
          'Taste of Country',
          'supports the Paris-shot video and moving-on visual narrative',
        ),
      ],
    },
    {
      slug: 'red-live-from-new-york-city',
      kind: 'performance',
      title: 'Red (Live from New York City)',
      director: null,
      releasedOn: null,
      relatedSongs: ['Red'],
      tags: ['Music'],
      summary:
        'A solo live performance of the title track taped in New York City, one of six Red-era and catalog songs the official channel posted under the "Live From New York City" banner.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=gQ0pP2z9niw',
      media: [embed('gQ0pP2z9niw', '2026-08-25')],
      sources: [
        yt('gQ0pP2z9niw', 'Taylor Swift - Red (Live from New York City)'),
        wiki('Red_(Taylor_Swift_song)', 'Red (Taylor Swift song)'),
      ],
    },
    {
      slug: 'we-are-never-ever-getting-back-together-live-from-new-york-city',
      kind: 'performance',
      title: 'We Are Never Ever Getting Back Together (Live from New York City)',
      director: null,
      releasedOn: null,
      relatedSongs: ['We Are Never Ever Getting Back Together'],
      tags: ['Music'],
      summary:
        'A solo live performance of the Red lead single taped in New York City, one of six Red-era and catalog songs the official channel posted under the "Live From New York City" banner.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=BktS1hkMx_k',
      media: [embed('BktS1hkMx_k', '2026-08-25')],
      sources: [
        yt('BktS1hkMx_k', 'Taylor Swift - We Are Never Ever Getting Back Together (Live from New York City)'),
        wiki('We_Are_Never_Ever_Getting_Back_Together', 'We Are Never Ever Getting Back Together'),
      ],
    },
    {
      slug: 'love-story-live-from-new-york-city',
      kind: 'performance',
      title: 'Love Story (Live from New York City)',
      director: null,
      releasedOn: null,
      relatedSongs: ['Love Story'],
      tags: ['Music'],
      summary:
        'A solo live performance of the Fearless-era catalog hit taped in New York City during the Red run, one of six songs the official channel posted under the "Live From New York City" banner.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=yfWgXcrNQIw',
      media: [embed('yfWgXcrNQIw', '2026-08-25')],
      sources: [
        yt('yfWgXcrNQIw', 'Taylor Swift - Love Story (Live from New York City)'),
        wiki('Love_Story_(Taylor_Swift_song)', 'Love Story (Taylor Swift song)'),
      ],
    },
    {
      slug: 'you-belong-with-me-live-from-new-york-city',
      kind: 'performance',
      title: 'You Belong with Me (Live from New York City)',
      director: null,
      releasedOn: null,
      relatedSongs: ['You Belong with Me'],
      tags: ['Music'],
      summary:
        'A solo live performance of the Fearless-era catalog hit taped in New York City during the Red run, one of six songs the official channel posted under the "Live From New York City" banner.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=tvnGBYMe9gM',
      media: [embed('tvnGBYMe9gM', '2026-08-25')],
      sources: [
        yt('tvnGBYMe9gM', 'Taylor Swift - You Belong With Me (Live from New York City)'),
        wiki('You_Belong_with_Me', 'You Belong with Me'),
      ],
    },
    {
      slug: 'mean-live-from-new-york-city',
      kind: 'performance',
      title: 'Mean (Live from New York City)',
      director: null,
      releasedOn: null,
      relatedSongs: ['Mean'],
      tags: ['Music'],
      summary:
        'A solo live performance of the Grammy-winning Speak Now single taped in New York City during the Red run, one of six songs the official channel posted under the "Live From New York City" banner.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=RQuY8kERaU0',
      media: [embed('RQuY8kERaU0', '2026-08-25')],
      sources: [
        yt('RQuY8kERaU0', 'Taylor Swift - Mean (Live from New York City)'),
        wiki('Mean_(song)', 'Mean (song)'),
      ],
    },
    {
      slug: 'everything-has-changed-britains-got-talent-2013',
      kind: 'performance',
      title: "Everything Has Changed — Britain's Got Talent",
      director: null,
      releasedOn: '2013-06-08',
      relatedSongs: ['Everything Has Changed'],
      tags: ['Music'],
      summary:
        'A guest performance of "Everything Has Changed" with Ed Sheeran during the live final of Britain\'s Got Talent series 7, alongside fellow guest act Psy.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=YfPfgZjhH1w',
      media: [embed('YfPfgZjhH1w', '2026-08-25')],
      sources: [
        yt('YfPfgZjhH1w', "Britain's Got Talent performance: Everything Has Changed"),
        wiki(
          'Britain%27s_Got_Talent_(series_7)',
          "Britain's Got Talent (series 7)",
          'confirms the June 8, 2013 live final and the Taylor Swift / Ed Sheeran guest performance',
        ),
      ],
    },
    // ── YouTube catalog additions (issue #3286, batch C, 2026-08-25) ────────
    {
      slug: 'i-knew-you-were-trouble-bts-1',
      kind: 'documentary',
      title: '"I Knew You Were Trouble." Behind-The-Scenes #1',
      director: null,
      releasedOn: '2013-02-05',
      relatedSongs: ['I Knew You Were Trouble'],
      tags: ['Music'],
      summary:
        'The first behind-the-scenes cut from the "I Knew You Were Trouble." video shoot, straight from Taylor\'s own channel.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=rghH6QlT5a0',
      media: [embed('rghH6QlT5a0', '2026-08-25')],
      sources: [yt('rghH6QlT5a0', '"I Knew You Were Trouble." Behind-The-Scenes #1')],
    },
    {
      slug: 'i-knew-you-were-trouble-bts-3',
      kind: 'documentary',
      title: '"I Knew You Were Trouble." Behind-The-Scenes #3',
      director: null,
      releasedOn: '2013-02-05',
      relatedSongs: ['I Knew You Were Trouble'],
      tags: ['Music'],
      summary:
        'The third behind-the-scenes cut from the "I Knew You Were Trouble." video shoot, posted the same day as #1.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=jinbX0hwYOo',
      media: [embed('jinbX0hwYOo', '2026-08-25')],
      sources: [yt('jinbX0hwYOo', '"I Knew You Were Trouble." Behind-The-Scenes #3')],
    },
    {
      slug: 'red-guitar-solo-red-tour-opening-night',
      kind: 'performance',
      title: '"Red" Guitar Solo — RED Tour Opening Night',
      director: null,
      releasedOn: '2013-03-15',
      relatedSongs: ['Red'],
      tags: ['Tour'],
      summary:
        'The guitar solo from "Red," filmed at the RED Tour\'s March 13, 2013 opening night in Omaha and posted two days later.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=NZnRUnOQZWU',
      media: [embed('NZnRUnOQZWU', '2026-08-25')],
      sources: [yt('NZnRUnOQZWU', '"Red" Guitar Solo from RED Tour Opening Night')],
    },
    {
      slug: 'holy-ground-live-red-tour-opening-night',
      kind: 'performance',
      title: '"Holy Ground" Live on the RED Tour',
      director: null,
      releasedOn: '2013-03-15',
      relatedSongs: ['Holy Ground'],
      tags: ['Tour'],
      summary:
        '"Holy Ground" performed live at the RED Tour\'s Omaha opening night, filmed for the official channel.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=3H21433WdtU',
      media: [embed('3H21433WdtU', '2026-08-25')],
      sources: [yt('3H21433WdtU', '"Holy Ground" Live on the RED Tour!')],
    },
    {
      slug: 'sparks-fly-acoustic-red-tour-opening-night',
      kind: 'performance',
      title: '"Sparks Fly" (Acoustic) Live on the RED Tour',
      director: null,
      releasedOn: '2013-03-15',
      relatedSongs: ['Sparks Fly'],
      tags: ['Tour'],
      summary:
        'An acoustic "Sparks Fly" from the RED Tour\'s Omaha opening night, filmed for the official channel.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=Nx-5bHeC6xo',
      media: [embed('Nx-5bHeC6xo', '2026-08-25')],
      sources: [yt('Nx-5bHeC6xo', '"Sparks Fly" (acoustic) Live on the RED Tour!')],
    },
    {
      slug: 'youre-so-vain-with-carly-simon',
      kind: 'performance',
      title: "You're So Vain — with Carly Simon",
      director: null,
      releasedOn: '2013-07-29',
      relatedSongs: [],
      tags: ['Tour'],
      summary:
        'A Gillette Stadium surprise on the RED Tour: Taylor brings out one of her heroes, Carly Simon, for a duet of Simon\'s "You\'re So Vain" in front of more than 55,000 fans in Foxborough, Massachusetts.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=y7CsaOF3S5c',
      media: [embed('y7CsaOF3S5c', '2026-08-25')],
      sources: [yt('y7CsaOF3S5c', "Taylor Swift and Carly Simon: You're So Vain")],
    },
    {
      slug: 'taylor-by-taylor-swift-fragrance-qa',
      kind: 'documentary',
      title: 'Q&A with Taylor on Taylor By Taylor Swift, the Fragrance',
      director: null,
      releasedOn: '2013-08-01',
      relatedSongs: [],
      tags: [],
      summary:
        'A Q&A with Taylor about her Taylor by Taylor Swift fragrance and behind-the-scenes footage from the commercial shoot, which features "Starlight" from Red.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=EuT6nQvdcpo',
      media: [embed('EuT6nQvdcpo', '2026-08-25')],
      sources: [yt('EuT6nQvdcpo', 'Q&A with Taylor on Taylor By Taylor Swift, the fragrance')],
    },
    {
      slug: 'on-style-part-3',
      kind: 'documentary',
      title: 'Taylor Swift on Style: Part 3',
      director: null,
      releasedOn: '2013-08-12',
      relatedSongs: [],
      tags: ['Fashion'],
      summary:
        'Taylor talks fall trends and how fashion applies to her life with style expert Zanna Roberts Rassi, in a segment presented by Keds.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=y9yIBAmBDtk',
      media: [embed('y9yIBAmBDtk', '2026-08-25')],
      sources: [yt('y9yIBAmBDtk', 'Taylor Swift on Style: Part 3')],
    },
    {
      slug: 'on-style-part-4',
      kind: 'documentary',
      title: 'Taylor Swift on Style: Part 4',
      director: null,
      releasedOn: '2013-08-14',
      relatedSongs: [],
      tags: ['Fashion'],
      summary:
        'Taylor talks about her inspiration behind the Keds fall line with style expert Zanna Roberts Rassi, in a segment presented by Keds.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=41Zxe-tqjoE',
      media: [embed('41Zxe-tqjoE', '2026-08-25')],
      sources: [yt('41Zxe-tqjoE', 'Taylor Swift on Style: Part 4')],
    },
    {
      slug: 'on-style-outtakes',
      kind: 'documentary',
      title: 'Taylor Swift on Style: Outtakes',
      director: null,
      releasedOn: '2013-08-16',
      relatedSongs: [],
      tags: ['Fashion'],
      summary:
        'Outtakes with Taylor and style expert Zanna Roberts Rassi from the "On Style" series presented by Keds.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=Ac7wMLgLtpY',
      media: [embed('Ac7wMLgLtpY', '2026-08-25')],
      sources: [yt('Ac7wMLgLtpY', 'Taylor Swift on Style: Outtakes')],
    },
    {
      slug: 'staples-center-week-bts',
      kind: 'documentary',
      title: "Behind the Scenes of Taylor Swift's Week at Staples Center",
      director: null,
      releasedOn: '2013-09-06',
      relatedSongs: [],
      tags: ['Tour'],
      summary:
        'Behind-the-scenes footage from Taylor\'s week headlining the Staples Center on the RED Tour.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=6wEVDvnqQOM',
      media: [embed('6wEVDvnqQOM', '2026-08-25')],
      sources: [yt('6wEVDvnqQOM', "Behind the scenes of Taylor Swift's week at Staples Center")],
    },
    {
      slug: 'jenny-from-the-block-with-jennifer-lopez',
      kind: 'performance',
      title: 'Jenny from the Block — with Jennifer Lopez',
      director: null,
      releasedOn: '2013-09-12',
      relatedSongs: [],
      tags: ['Tour'],
      summary:
        'A Staples Center surprise on the RED Tour: Jennifer Lopez joins Taylor to perform her own hit "Jenny from the Block" live.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=FTA4kzsTmxc',
      media: [embed('FTA4kzsTmxc', '2026-08-25')],
      sources: [yt('FTA4kzsTmxc', 'Taylor Swift and Jennifer Lopez: Jenny from the Block')],
    },
    {
      slug: 'red-tour-nashville-week-recap',
      kind: 'documentary',
      title: 'RED Tour Nashville Week',
      director: null,
      releasedOn: '2013-10-08',
      relatedSongs: [],
      tags: ['Tour'],
      summary:
        "A recap of the RED Tour's North American finale — three sold-out Nashville shows featuring Luke Bryan, Rascal Flatts, and Hunter Hayes, plus a surprise Ed Sheeran appearance.",
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=DJXfSaOJXOQ',
      media: [embed('DJXfSaOJXOQ', '2026-08-25')],
      sources: [yt('DJXfSaOJXOQ', 'Taylor Swift RED Tour Nashville Week')],
    },
    {
      slug: 'surprising-gena',
      kind: 'documentary',
      title: 'Surprising Gena',
      director: null,
      releasedOn: '2014-04-16',
      relatedSongs: [],
      tags: [],
      summary:
        'Taylor flies to Columbus, Ohio to surprise longtime fan Gena Gabrielle at her bridal shower — cookies, a stand mixer, and a doorstep reveal caught on camera.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=J1LMp-jEH_k',
      media: [embed('J1LMp-jEH_k', '2026-08-25')],
      sources: [
        yt('J1LMp-jEH_k', 'Surprising Gena'),
        press(
          'https://abcnews.go.com/Entertainment/taylor-swift-surprise-fan-bridal-shower/story?id=23353944',
          'See Taylor Swift Surprise a Fan at Her Bridal Shower',
          'ABC News',
          'confirms the April 2014 Columbus, Ohio bridal-shower surprise for fan Gena Gabrielle',
        ),
      ],
    },
  ],
};
