// Vault videos — reputation era. Official uploads verified via YouTube oEmbed
// 2026-07-08; Wikipedia URLs verified the same day.

const wiki = (article, title, notes) => ({
  source_url: `https://en.wikipedia.org/wiki/${article}`,
  source_title: title,
  publisher: 'Wikipedia',
  source_type: 'wiki',
  accessed_at: '2026-07-08',
  reliability_score: 2,
  excerpt: null,
  notes: notes ?? 'anchors the video, director, and background',
});
const yt = (id, title) => ({
  source_url: `https://www.youtube.com/watch?v=${id}`,
  source_title: title,
  publisher: 'Taylor Swift (official YouTube channel)',
  source_type: 'official',
  accessed_at: '2026-07-08',
  reliability_score: 5,
  excerpt: null,
  notes: 'official upload — verified via YouTube oEmbed 2026-07-08',
});
const press = (source_url, source_title, publisher, notes) => ({
  source_url,
  source_title,
  publisher,
  source_type: 'reputable_press',
  accessed_at: '2026-07-09',
  reliability_score: 4,
  excerpt: null,
  notes,
});
const embed = (id) => ({
  kind: 'oembed',
  rights: 'platform_tos',
  provider: 'youtube',
  post_url: `https://www.youtube.com/watch?v=${id}`,
  oembed_fetched_at: '2026-07-08',
  attribution: 'Taylor Swift — official YouTube channel',
});

export default {
  eraSlug: 'reputation',
  videos: [
    {
      slug: 'look-what-you-made-me-do-mv',
      kind: 'music_video',
      title: 'Look What You Made Me Do',
      director: 'Joseph Kahn',
      releasedOn: '2017-08-27',
      relatedSongs: ['Look What You Made Me Do'],
      tags: ['Music'],
      summary:
        'The VMA-premiered resurrection: zombie Taylor claws out of a grave, a snake serves tea on a throne, and the finale lines up fifteen past Taylors to bicker over which one is fake.',
      symbolism:
        'Every set piece answers a headline from the preceding decade — the era\'s whole thesis is that she is burying the old narratives on camera.',
      easterEggs: [
        'The gravestone reads Nils Sjöberg — the pseudonym she used as a songwriter on "This Is What You Came For."',
        '"The old Taylor can\'t come to the phone right now" is delivered from atop a mountain of her past selves; the closing lineup of fifteen era-Taylors instead bickers over her old media narratives.',
        'The "Junior Jewels" shirt from You Belong with Me returns, now scrawled with her real friends\' names.',
      ],
      officialUrl: 'https://www.youtube.com/watch?v=3tmd-ClpJxA',
      media: [embed('3tmd-ClpJxA')],
      sources: [yt('3tmd-ClpJxA', 'Taylor Swift - Look What You Made Me Do'), wiki('Look_What_You_Made_Me_Do', 'Look What You Made Me Do')],
    },
    {
      slug: 'ready-for-it-mv',
      kind: 'music_video',
      title: '...Ready for It?',
      director: 'Joseph Kahn',
      releasedOn: '2017-10-26',
      relatedSongs: ['...Ready for It?'],
      tags: ['Music'],
      summary:
        'Cyberpunk Taylor vs. Taylor: a cloaked figure walks a neon corridor to confront a caged android version of herself — the robot cracks its shell and levels the wall between them.',
      symbolism:
        'Widely read (and reported) as public-image Taylor confronting the real one — the naked android is the self the armor was built around.',
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=wIft-t-MQuE',
      media: [embed('wIft-t-MQuE')],
      sources: [yt('wIft-t-MQuE', 'Taylor Swift - ...Ready For It?'), wiki('...Ready_for_It%3F', '...Ready for It?')],
    },
    {
      slug: 'end-game-mv',
      kind: 'music_video',
      title: 'End Game',
      director: 'Joseph Kahn',
      releasedOn: '2018-01-12',
      relatedSongs: ['End Game'],
      tags: ['Music'],
      summary:
        'A globe-hopping party flex — Miami boat lights, Tokyo arcades, London double-deckers — with Ed Sheeran and Future riding shotgun through the era\'s one pure hangout video.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=dfnCAmr569k',
      media: [embed('dfnCAmr569k')],
      sources: [yt('dfnCAmr569k', 'Taylor Swift - End Game ft. Ed Sheeran, Future'), wiki('End_Game_(Taylor_Swift_song)', 'End Game (Taylor Swift song)')],
    },
    {
      slug: 'delicate-mv',
      kind: 'music_video',
      title: 'Delicate',
      director: 'Joseph Kahn',
      releasedOn: '2018-03-11',
      relatedSongs: ['Delicate'],
      tags: ['Music'],
      summary:
        'Premiered at the iHeartRadio Awards: a note makes Taylor invisible mid-press-gauntlet, and she dances unwatched through a hotel — lobby, hallway, rain — until the note\'s magic runs out at a dive bar.',
      symbolism:
        'Invisibility as relief: the fame-armor drops the second nobody can see her, which is the lyric\'s whole ache — wanting one person to see through it on purpose.',
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=tCXGJQYZ9JA',
      media: [embed('tCXGJQYZ9JA')],
      sources: [yt('tCXGJQYZ9JA', 'Taylor Swift - Delicate'), wiki('Delicate_(Taylor_Swift_song)', 'Delicate (Taylor Swift song)')],
    },
    {
      slug: 'reputation-stadium-tour-film',
      kind: 'tour_film',
      title: 'Taylor Swift: reputation Stadium Tour',
      director: 'Paul Dugdale',
      releasedOn: '2018-12-31',
      relatedSongs: [],
      tags: ['Tour'],
      summary:
        'The Dallas stadium show, released to Netflix on New Year\'s Eve — the snake-throne era preserved in full, from the tilted stage to the Long Live/New Year\'s Day piano coda.',
      symbolism: null,
      easterEggs: [],
      // No official upload of the work itself exists — it is a Netflix original.
      // With no embed this record is HIDDEN from every reader-facing surface
      // rather than shown as a card that cannot play (playable-first rule,
      // docs/decisions.md 2026-08-13). Add a verified official upload here and
      // it comes back automatically — no code change needed.
      officialUrl: null,
      media: [],
      sources: [
        wiki('Taylor_Swift:_Reputation_Stadium_Tour', 'Taylor Swift: Reputation Stadium Tour'),
        press(
          'https://www.rollingstone.com/music/music-live-reviews/taylor-swift-reputation-stadium-tour-netflix-movie-review-773808/',
          "Taylor Swift's Reputation Film Shows Why She's One of the All-Time Greats",
          'Rolling Stone',
          'supports the Netflix concert-film release and Dallas stadium-show framing',
        ),
      ],
    },
    {
      slug: 'angels-with-robbie-williams-reputation-tour-2018',
      kind: 'performance',
      title: 'Angels (with Robbie Williams) — reputation Stadium Tour, Wembley',
      director: null,
      releasedOn: '2018-06-23',
      relatedSongs: [],
      tags: ['Tour'],
      summary:
        'A surprise Wembley Stadium duet: Robbie Williams joins for his own 1997 hit "Angels" during the London stop of the reputation Stadium Tour.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=RamgJyJsep4',
      media: [
        {
          kind: 'oembed',
          rights: 'platform_tos',
          provider: 'youtube',
          post_url: 'https://www.youtube.com/watch?v=RamgJyJsep4',
          oembed_fetched_at: '2026-08-25',
          attribution: 'Taylor Swift — official YouTube channel',
        },
      ],
      sources: [
        {
          source_url: 'https://www.youtube.com/watch?v=RamgJyJsep4',
          source_title: 'Taylor Swift and Robbie Williams - Angels - reputation Stadium Tour',
          publisher: 'Taylor Swift (official YouTube channel)',
          source_type: 'official',
          accessed_at: '2026-08-25',
          reliability_score: 5,
          excerpt: null,
          notes: 'official upload on the verified Taylor Swift channel',
        },
        wiki('Reputation_Stadium_Tour', 'Reputation Stadium Tour', 'confirms the June 23, 2018 Wembley date and Robbie Williams special-guest duet'),
      ],
    },
    // ── YouTube-catalog pass, issue #3286 batch B (2026-08-25) ──────────────
    {
      slug: 'end-game-behind-the-scenes',
      kind: 'documentary',
      title: 'End Game - Behind The Scenes',
      director: null,
      releasedOn: '2018-02-09',
      relatedSongs: ['End Game'],
      tags: ['Music'],
      summary:
        'A short making-of clip from the "End Game" shoot, with Ed Sheeran and Future along for the globe-hopping video\'s Miami and Tokyo setups.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=VA7Y_Psp5l4',
      media: [embed('VA7Y_Psp5l4')],
      sources: [
        {
          source_url: 'https://www.youtube.com/watch?v=VA7Y_Psp5l4',
          source_title: 'End Game - Behind The Scenes',
          publisher: 'Taylor Swift (official YouTube channel)',
          source_type: 'official',
          accessed_at: '2026-08-25',
          reliability_score: 5,
          excerpt: null,
          notes: 'official upload — verified via YouTube oEmbed and page date 2026-08-25 (Feb 9, 2018)',
        },
        press(
          'https://www.billboard.com/music/pop/taylor-swift-ed-sheeran-end-game-behind-the-scenes-8098936/',
          "Taylor Swift and Ed Sheeran's 'End Game': Watch Behind-the-Scenes Video",
          'Billboard',
          'confirms the February 2018 release of the behind-the-scenes clip',
        ),
      ],
    },
    {
      slug: 'making-of-a-song-delicate',
      kind: 'documentary',
      title: 'The Making of a Song: "Delicate"',
      director: null,
      releasedOn: '2017-11-14',
      relatedSongs: ['Delicate'],
      tags: ['Music'],
      summary:
        'A Taylor Swift NOW segment following the songwriting process behind "Delicate," released months before the reputation-era single itself.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=eQVhAN7-IAw',
      media: [embed('eQVhAN7-IAw')],
      sources: [
        {
          source_url: 'https://www.youtube.com/watch?v=eQVhAN7-IAw',
          source_title: 'The Making of a Song: "Delicate" – watch more on Taylor Swift NOW',
          publisher: 'Taylor Swift (official YouTube channel)',
          source_type: 'official',
          accessed_at: '2026-08-25',
          reliability_score: 5,
          excerpt: null,
          notes: 'official upload — verified via YouTube oEmbed and page date 2026-08-25 (Nov 14, 2017)',
        },
        wiki('Delicate_(Taylor_Swift_song)', 'Delicate (Taylor Swift song)'),
      ],
    },
    {
      slug: 'delicate-dance-rehearsal-part-1',
      kind: 'documentary',
      title: 'Delicate Music Video Dance Rehearsal Part 1',
      director: null,
      releasedOn: '2018-03-13',
      relatedSongs: ['Delicate'],
      tags: ['Music'],
      summary:
        'Rehearsal footage of Taylor working the "Delicate" video\'s choreography — splits, kicks and turns — two days after the video premiered.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=sEr7bAtZ8rY',
      media: [embed('sEr7bAtZ8rY')],
      sources: [
        {
          source_url: 'https://www.youtube.com/watch?v=sEr7bAtZ8rY',
          source_title: 'Delicate Music Video Dance Rehearsal Part 1',
          publisher: 'Taylor Swift (official YouTube channel)',
          source_type: 'official',
          accessed_at: '2026-08-25',
          reliability_score: 5,
          excerpt: null,
          notes: 'official upload — verified via YouTube oEmbed and page date 2026-08-25 (Mar 13, 2018)',
        },
        press(
          'https://www.billboard.com/music/music-news/taylor-swift-delicate-rehearsal-video-8244830/',
          "Taylor Swift 'Delicate' Rehearsal Video",
          'Billboard',
          'confirms the March 2018 rehearsal-footage release',
        ),
      ],
    },
    {
      slug: 'delicate-dance-rehearsal-part-2',
      kind: 'documentary',
      title: 'Delicate Music Video Dance Rehearsal Part 2',
      director: null,
      releasedOn: '2018-03-13',
      relatedSongs: ['Delicate'],
      tags: ['Music'],
      summary:
        'The second rehearsal clip from the "Delicate" video shoot, released the same day as Part 1.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=zGSneb3McDo',
      media: [embed('zGSneb3McDo')],
      sources: [
        {
          source_url: 'https://www.youtube.com/watch?v=zGSneb3McDo',
          source_title: 'Delicate Music Video Dance Rehearsal Part 2',
          publisher: 'Taylor Swift (official YouTube channel)',
          source_type: 'official',
          accessed_at: '2026-08-25',
          reliability_score: 5,
          excerpt: null,
          notes: 'official upload — verified via YouTube oEmbed and page date 2026-08-25 (Mar 13, 2018)',
        },
        press(
          'https://www.billboard.com/music/music-news/taylor-swift-delicate-rehearsal-video-8244830/',
          "Taylor Swift 'Delicate' Rehearsal Video",
          'Billboard',
          'confirms the March 2018 rehearsal-footage release',
        ),
      ],
    },
    {
      slug: 'reputation-secret-sessions',
      kind: 'documentary',
      title: 'The reputation Secret Sessions',
      director: null,
      releasedOn: '2017-11-07',
      relatedSongs: [],
      tags: ['Music', 'Lore'],
      summary:
        'A behind-the-scenes look at the Secret Sessions — the small, personally invited album-preview listening parties Taylor hosted at her homes ahead of reputation\'s release.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=kGOmPmILndU',
      media: [embed('kGOmPmILndU')],
      sources: [
        {
          source_url: 'https://www.youtube.com/watch?v=kGOmPmILndU',
          source_title: 'The reputation Secret Sessions',
          publisher: 'Taylor Swift (official YouTube channel)',
          source_type: 'official',
          accessed_at: '2026-08-25',
          reliability_score: 5,
          excerpt: null,
          notes: 'official upload — verified via YouTube oEmbed and page date 2026-08-25 (Nov 7, 2017)',
        },
        press(
          'https://www.billboard.com/music/pop/taylor-swift-reputation-secret-sessions-behind-scenes-video-8029951/',
          'Taylor Swift Shares an Intimate Peek Into \'Reputation\' Secret Sessions',
          'Billboard',
          'confirms the November 2017 Secret Sessions and the fan-listening-party format',
        ),
      ],
    },
    {
      slug: 'look-what-you-made-me-do-looks',
      kind: 'documentary',
      title: 'Look What You Made Me Do - Looks',
      director: null,
      releasedOn: '2017-10-17',
      relatedSongs: ['Look What You Made Me Do'],
      tags: ['Music', 'Fashion'],
      summary:
        'A styling-focused featurette on the wardrobe built for "Look What You Made Me Do" — the zombie resurrection look through the throne-room finale.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=np4Nw0tBun8',
      media: [embed('np4Nw0tBun8')],
      sources: [
        {
          source_url: 'https://www.youtube.com/watch?v=np4Nw0tBun8',
          source_title: 'Look What You Made Me Do - Looks',
          publisher: 'Taylor Swift (official YouTube channel)',
          source_type: 'official',
          accessed_at: '2026-08-25',
          reliability_score: 5,
          excerpt: null,
          notes: 'official upload — verified via YouTube oEmbed and page date 2026-08-25 (Oct 17, 2017)',
        },
        wiki('Look_What_You_Made_Me_Do', 'Look What You Made Me Do'),
      ],
    },
    {
      slug: 'you-need-to-calm-down-bts-friends-and-neighbors',
      kind: 'documentary',
      title: 'You Need To Calm Down Behind The Scenes: Friends & Neighbors',
      director: null,
      releasedOn: '2019-07-18',
      relatedSongs: ['You Need to Calm Down'],
      tags: ['Music'],
      summary:
        'One of three making-of clips from the "You Need to Calm Down" trailer-park shoot, focused on the guest cast playing Taylor\'s neighbors.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=SYd0pYqOJqA',
      media: [embed('SYd0pYqOJqA')],
      sources: [
        {
          source_url: 'https://www.youtube.com/watch?v=SYd0pYqOJqA',
          source_title: 'You Need To Calm Down Behind The Scenes: Friends & Neighbors',
          publisher: 'Taylor Swift (official YouTube channel)',
          source_type: 'official',
          accessed_at: '2026-08-25',
          reliability_score: 5,
          excerpt: null,
          notes: 'official upload — verified via YouTube oEmbed and page date 2026-08-25 (Jul 18, 2019)',
        },
        wiki('You_Need_to_Calm_Down', 'You Need to Calm Down'),
      ],
    },
    {
      slug: 'you-need-to-calm-down-bts-morning-routine',
      kind: 'documentary',
      title: 'You Need To Calm Down Behind The Scenes: Morning Routine',
      director: null,
      releasedOn: '2019-07-09',
      relatedSongs: ['You Need to Calm Down'],
      tags: ['Music'],
      summary:
        'A making-of clip from the "You Need to Calm Down" shoot centered on the trailer-park morning-routine sequence.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=s4MN_hGvTCA',
      media: [embed('s4MN_hGvTCA')],
      sources: [
        {
          source_url: 'https://www.youtube.com/watch?v=s4MN_hGvTCA',
          source_title: 'You Need To Calm Down Behind The Scenes: Morning Routine',
          publisher: 'Taylor Swift (official YouTube channel)',
          source_type: 'official',
          accessed_at: '2026-08-25',
          reliability_score: 5,
          excerpt: null,
          notes: 'official upload — verified via YouTube oEmbed and page date 2026-08-25 (Jul 9, 2019)',
        },
        wiki('You_Need_to_Calm_Down', 'You Need to Calm Down'),
      ],
    },
    {
      slug: 'you-need-to-calm-down-bts-pop-queen-pageant',
      kind: 'documentary',
      title: 'You Need To Calm Down Behind The Scenes: Pop Queen Pageant',
      director: null,
      releasedOn: '2019-06-20',
      relatedSongs: ['You Need to Calm Down'],
      tags: ['Music'],
      summary:
        'A making-of clip from the "You Need to Calm Down" shoot covering the video\'s pop-queen pageant sequence.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=6MLzSp0OJL0',
      media: [embed('6MLzSp0OJL0')],
      sources: [
        {
          source_url: 'https://www.youtube.com/watch?v=6MLzSp0OJL0',
          source_title: 'You Need To Calm Down Behind The Scenes: Pop Queen Pageant',
          publisher: 'Taylor Swift (official YouTube channel)',
          source_type: 'official',
          accessed_at: '2026-08-25',
          reliability_score: 5,
          excerpt: null,
          notes: 'official upload — verified via YouTube oEmbed and page date 2026-08-25 (Jun 20, 2019)',
        },
        wiki('You_Need_to_Calm_Down', 'You Need to Calm Down'),
      ],
    },
    {
      slug: 'me-bts-je-suis-calme',
      kind: 'documentary',
      title: 'ME! Behind The Scenes: Je Suis Calme',
      director: null,
      releasedOn: '2019-05-01',
      relatedSongs: ['ME!'],
      tags: ['Music'],
      summary:
        'A making-of clip from the "ME!" video shoot, released the day after the song and video dropped.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=lj2mZ8zDToY',
      media: [embed('lj2mZ8zDToY')],
      sources: [
        {
          source_url: 'https://www.youtube.com/watch?v=lj2mZ8zDToY',
          source_title: 'ME! Behind The Scenes: Je Suis Calme',
          publisher: 'Taylor Swift (official YouTube channel)',
          source_type: 'official',
          accessed_at: '2026-08-25',
          reliability_score: 5,
          excerpt: null,
          notes: 'official upload — verified via YouTube oEmbed and page date 2026-08-25 (May 1, 2019)',
        },
        wiki('Me!', 'ME!'),
      ],
    },
    {
      slug: 'me-bts-the-story-of-benjamin-button',
      kind: 'documentary',
      title: 'ME! Behind The Scenes: The Story of Benjamin Button',
      director: null,
      releasedOn: '2019-04-30',
      relatedSongs: ['ME!'],
      tags: ['Music'],
      summary:
        'A making-of clip from the "ME!" video shoot, released the same day the song and its musical-theater-styled video premiered.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=MUf1ili4Zew',
      media: [embed('MUf1ili4Zew')],
      sources: [
        {
          source_url: 'https://www.youtube.com/watch?v=MUf1ili4Zew',
          source_title: 'ME! Behind The Scenes: The Story of Benjamin Button',
          publisher: 'Taylor Swift (official YouTube channel)',
          source_type: 'official',
          accessed_at: '2026-08-25',
          reliability_score: 5,
          excerpt: null,
          notes: 'official upload — verified via YouTube oEmbed and page date 2026-08-25 (Apr 30, 2019)',
        },
        wiki('Me!', 'ME!'),
      ],
    },
    {
      slug: 'me-live-graham-norton-show-2019',
      kind: 'performance',
      title: 'ME! (Live on The Graham Norton Show)',
      director: null,
      releasedOn: '2019-05-24',
      relatedSongs: ['ME!'],
      tags: ['Music'],
      summary:
        'A UK television performance of "ME!" on The Graham Norton Show during the song\'s promotional run.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=MA0HQG9J9Yk',
      media: [embed('MA0HQG9J9Yk')],
      sources: [
        {
          source_url: 'https://www.youtube.com/watch?v=MA0HQG9J9Yk',
          source_title: 'Taylor Swift - ME! (Live on The Graham Norton Show)',
          publisher: 'Taylor Swift (official YouTube channel)',
          source_type: 'official',
          accessed_at: '2026-08-25',
          reliability_score: 5,
          excerpt: null,
          notes: 'official upload — verified via YouTube oEmbed and page date 2026-08-25 (May 24, 2019)',
        },
        wiki('Me!', 'ME!'),
      ],
    },
    {
      slug: 'me-live-the-voice-2019',
      kind: 'performance',
      title: 'ME! (Live on The Voice / 2019) ft. Brendon Urie',
      director: null,
      releasedOn: '2019-05-21',
      relatedSongs: ['ME!'],
      tags: ['Music'],
      summary:
        'A live performance of "ME!" with Brendon Urie on the U.S. broadcast of The Voice.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=_zUCMfYkgj0',
      media: [embed('_zUCMfYkgj0')],
      sources: [
        {
          source_url: 'https://www.youtube.com/watch?v=_zUCMfYkgj0',
          source_title: 'Taylor Swift - ME! (Live on The Voice / 2019) ft. Brendon Urie',
          publisher: 'Taylor Swift (official YouTube channel)',
          source_type: 'official',
          accessed_at: '2026-08-25',
          reliability_score: 5,
          excerpt: null,
          notes: 'official upload — verified via YouTube oEmbed and page date 2026-08-25 (May 21, 2019)',
        },
        wiki('Me!', 'ME!'),
      ],
    },
    {
      slug: 'taylors-diary-first-cat-tour-middle-school',
      kind: 'interview',
      title: "Taylor's Diary - Discusses Getting Her First Cat Meredith Grey, Tour and Middle School",
      director: null,
      releasedOn: '2019-08-22',
      relatedSongs: [],
      tags: ['Music'],
      summary:
        'A "Taylor\'s Diary" segment, released the day before Lover, with Taylor talking through getting her first cat Meredith Grey, touring, and middle school.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=gRIWxlehJVg',
      media: [embed('gRIWxlehJVg')],
      sources: [
        {
          source_url: 'https://www.youtube.com/watch?v=gRIWxlehJVg',
          source_title: "Taylor's Diary -  Discusses Getting Her First Cat Meredith Grey, Tour and Middle School",
          publisher: 'Taylor Swift (official YouTube channel)',
          source_type: 'official',
          accessed_at: '2026-08-25',
          reliability_score: 5,
          excerpt: null,
          notes: 'official upload — verified via YouTube oEmbed and page date 2026-08-25 (Aug 22, 2019)',
        },
      ],
    },
    {
      slug: 'lovers-lounge-fan-qa-2019',
      kind: 'interview',
      title: "Taylor Swift Answers Questions From Fans From Lover's Lounge Live",
      director: null,
      releasedOn: '2019-08-22',
      relatedSongs: [],
      tags: ['Music'],
      summary:
        'A fan Q&A filmed at Lover\'s Lounge, released the day before the Lover album dropped.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=iyYhqYELWtA',
      media: [embed('iyYhqYELWtA')],
      sources: [
        {
          source_url: 'https://www.youtube.com/watch?v=iyYhqYELWtA',
          source_title: "Taylor Swift Answers Questions From Fans From Lover's Lounge Live",
          publisher: 'Taylor Swift (official YouTube channel)',
          source_type: 'official',
          accessed_at: '2026-08-25',
          reliability_score: 5,
          excerpt: null,
          notes: 'official upload — verified via YouTube oEmbed and page date 2026-08-25 (Aug 22, 2019)',
        },
      ],
    },
    {
      slug: 'taylors-diary-13-year-old-self-lover-deluxe',
      kind: 'interview',
      title: "Taylor's Diary - My 13 Year Old Self (Exclusive Reading from Deluxe Edition Lover Album)",
      director: null,
      releasedOn: '2019-08-22',
      relatedSongs: [],
      tags: ['Music'],
      summary:
        'Taylor reads from her own 13-year-old diary in this "Taylor\'s Diary" segment, part of the Lover deluxe-edition exclusive content released the day before the album.',
      symbolism: null,
      easterEggs: [],
      officialUrl: 'https://www.youtube.com/watch?v=UY3UfH-ittk',
      media: [embed('UY3UfH-ittk')],
      sources: [
        {
          source_url: 'https://www.youtube.com/watch?v=UY3UfH-ittk',
          source_title: "Taylor's Diary - My 13 Year Old Self (Exclusive Reading from Deluxe Edition Lover Album)",
          publisher: 'Taylor Swift (official YouTube channel)',
          source_type: 'official',
          accessed_at: '2026-08-25',
          reliability_score: 5,
          excerpt: null,
          notes: 'official upload — verified via YouTube oEmbed and page date 2026-08-25 (Aug 22, 2019)',
        },
      ],
    },
  ],
};
