export const FAN_MADE = [
  {
    brand: 'the Clandestine Underground',
    item: 'Underground Original Design: So Long, London Boxy Cotton TShirt',
    kind: 'apparel',
    retailer: 'theclandestineunderground.com',
    url: 'https://theclandestineunderground.com/products/underground-original-design-so-long-london-oversized-tshirt',
    price: '$43.00',
    imageUrl:
      'https://cdn.shopify.com/s/files/1/0280/6916/7175/files/solonglondonmockteelaclearblue_dc05c580-bd93-457f-93e3-30f7e1e83012.png?v=1770739609',
    inStock: true,
    discoveredVia: 'independent-shopify-listing',
    discoveredAt: '2026-08-30T14:30:56Z',
    verifiedAt: '2026-08-30T14:31:37.402Z',
    provenance: [
      {
        discoveredVia: 'independent-shopify-listing',
        discoveredAt: '2026-08-30T14:30:56Z',
        sourceUrl:
          'https://theclandestineunderground.com/products/underground-original-design-so-long-london-oversized-tshirt',
        d3: {
          judgment: 'inspired-original',
          prohibitedMaterial: 'none',
          basis:
            'Merchant product JSON describes a Taylor Swift-inspired postcard design with Tower Bridge; direct image inspection shows the same original Tower Bridge postcard illustration and no Taylor likeness, official album artwork, or official tour graphic.',
        },
        e1: {
          listingVerified: true,
          evidenceUrl:
            'https://theclandestineunderground.com/products/underground-original-design-so-long-london-oversized-tshirt.js',
          productId: '9189687886112',
          available: true,
          price: '$43.00',
          title: 'Underground Original Design: So Long, London Boxy Cotton TShirt',
        },
        e2: {
          imageVerified: true,
          evidenceUrl:
            'https://cdn.shopify.com/s/files/1/0280/6916/7175/files/solonglondonmockteelaclearblue_dc05c580-bd93-457f-93e3-30f7e1e83012.png?v=1770739609',
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: 'Tower Bridge postcard illustration printed on a light-blue shirt',
        },
      },
    ],
  },
  {
    brand: "NoteworthyKY",
    item: "Greeting Card | I Got You A Card Again | Taylor Folklore Inspired",
    kind: "print",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/1221270133/i-got-you-a-card-again-custom-printing",
    price: "$6.00",
    imageUrl: "https://i.etsystatic.com/25496512/r/il/ef8501/8196811368/il_fullxfull.8196811368_kdbu.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/1221270133/i-got-you-a-card-again-custom-printing",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "The image shows a hand-drawn line illustration of a gray cardigan sweater with a small 'folklore' tag sewn on the chest, paired with the printed phrase 'I got you a card again' — an original illustrated design referencing the folklore era/cardigan motif with no photograph of Taylor Swift or reproduction of the actual album cover art.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/1221270133/i-got-you-a-card-again-custom-printing",
          productId: "1221270133",
          available: true,
          price: "$6.00",
          title: "Greeting Card | I Got You A Card Again | Taylor Folklore Inspired",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/25496512/r/il/ef8501/8196811368/il_fullxfull.8196811368_kdbu.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "A white greeting card printed with a hand-drawn illustration of a gray button cardigan with a small 'folklore' tag and the caption 'I got you a card again', on a kraft paper envelope.",
        },
      },
    ],
  },
  {
    brand: "MoonWaterApoth",
    item: "ROOM SPRAY {Fearless} – Lemon Neroli Oud Scent | Clean Citrus Home Fragrance | Inspired by Taylor Swift Swiftie Gift",
    kind: "home-decor",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/1504284645/room-spray-fearless-lemon-neroli-oud",
    price: "$22.00",
    imageUrl: "https://i.etsystatic.com/35754408/r/il/2a3cd9/7123667627/il_fullxfull.7123667627_iqcl.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/1504284645/room-spray-fearless-lemon-neroli-oud",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "The image shows an amber apothecary spray bottle labeled 'FEARLESS — Room & Linen Spray — Moon Water Apothecary' decorated with a simple gold guitar graphic and gold streamers, referencing the era name only, with no photograph of Taylor Swift or official album/tour artwork.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/1504284645/room-spray-fearless-lemon-neroli-oud",
          productId: "1504284645",
          available: true,
          price: "$22.00",
          title: "ROOM SPRAY {Fearless} – Lemon Neroli Oud Scent | Clean Citrus Home Fragrance | Inspired by Taylor Swift Swiftie Gift",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/35754408/r/il/2a3cd9/7123667627/il_fullxfull.7123667627_iqcl.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "An amber glass spray bottle with a paper label reading 'Fearless' and 'Moon Water Apothecary', decorated with an illustrated gold guitar and gold streamer graphics.",
        },
      },
    ],
  },
  {
    brand: "ivieandjade",
    item: "Girls Midnight Sparkle Bodysuit | Kids Dark Blue Rhinestone Print Leotard | Pop Star Inspired",
    kind: "apparel",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/1565209313/girls-midnight-sparkle-bodysuit-kids",
    price: "$65.00",
    imageUrl: "https://i.etsystatic.com/41222609/r/il/137803/6295895090/il_fullxfull.6295895090_t16a.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/1565209313/girls-midnight-sparkle-bodysuit-kids",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "The image shows a kids' bodysuit in a dark navy/midnight blue color with an abstract rhinestone-style sparkle print pattern; there is no photograph, face, or likeness of Taylor Swift and no official tour/album graphics, only a generic 'pop star inspired' sparkle aesthetic tied to the Midnights era name.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/1565209313/girls-midnight-sparkle-bodysuit-kids",
          productId: "1565209313",
          available: true,
          price: "$65.00",
          title: "Girls Midnight Sparkle Bodysuit | Kids Dark Blue Rhinestone Print Leotard | Pop Star Inspired",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/41222609/r/il/137803/6295895090/il_fullxfull.6295895090_t16a.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "A long-sleeve dark navy blue children's bodysuit/leotard covered in an all-over faux-rhinestone sparkle print pattern.",
        },
      },
    ],
  },
  {
    brand: "BeCleverBeKind",
    item: "Invisible String, Folklore-inspired Sweatshirt",
    kind: "apparel",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/1609387109/invisible-string-folklore-inspired",
    price: "$42.00",
    imageUrl: "https://i.etsystatic.com/38066864/r/il/8d5252/7185263464/il_fullxfull.7185263464_diw5.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/1609387109/invisible-string-folklore-inspired",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "The image shows a navy sweatshirt printed with the lyric text 'one single thread of gold tied me to you' alongside a simple original line-art illustration of two clasped hands, with no photograph of Taylor Swift and no official album or tour artwork reproduced.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/1609387109/invisible-string-folklore-inspired",
          productId: "1609387109",
          available: true,
          price: "$42.00",
          title: "Invisible String, Folklore-inspired Sweatshirt",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/38066864/r/il/8d5252/7185263464/il_fullxfull.7185263464_diw5.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "A navy crewneck sweatshirt printed with a lyric phrase and a small line-drawing illustration of two clasped hands.",
        },
      },
    ],
  },
  {
    brand: "midnightbraceletcoUS",
    item: "Denver Broncos Friendship Bracelets – Stackable Team Colors – Taylor Swift Inspired",
    kind: "jewelry",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/1631787556/denver-broncos-friendship-bracelets",
    price: "$12.50",
    imageUrl: "https://i.etsystatic.com/48368276/r/il/7687f1/7637051357/il_fullxfull.7637051357_a9vh.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/1631787556/denver-broncos-friendship-bracelets",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "The image shows handmade beaded stretch bracelets in orange, blue, and white with letter beads spelling 'DENVER BRONCOS'; there is no photograph, likeness, album art, or tour graphic of Taylor Swift, only an independent design in the general 'friendship bracelet' craft trend associated with the Eras Tour.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/1631787556/denver-broncos-friendship-bracelets",
          productId: "1631787556",
          available: true,
          price: "$12.50",
          title: "Denver Broncos Friendship Bracelets – Stackable Team Colors – Taylor Swift Inspired",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/48368276/r/il/7687f1/7637051357/il_fullxfull.7637051357_a9vh.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "Two stacked beaded bracelets in orange/navy/white team colors with letter beads spelling 'DENVER BRONCOS', displayed on a woven burlap pillow.",
        },
      },
    ],
  },
  {
    brand: "BogRoadDesigns",
    item: "I'm The Problem Wood Sign, Taylor Office Sign, Eras Tour Theme",
    kind: "home-decor",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/1708008591/im-the-problem-wood-sign-taylor-office",
    price: "$13.99",
    imageUrl: "https://i.etsystatic.com/17945384/r/il/16480a/5893142082/il_fullxfull.5893142082_pc55.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/1708008591/im-the-problem-wood-sign-taylor-office",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "The wood sign itself displays only the printed lyric text 'IT'S ME / Hi! I'm the problem / IT'S ME' with no illustration, photograph of Taylor Swift, or reproduction of official album/tour artwork — purely a lyric-based text design.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/1708008591/im-the-problem-wood-sign-taylor-office",
          productId: "1708008591",
          available: true,
          price: "$13.99",
          title: "I'm The Problem Wood Sign, Taylor Office Sign, Eras Tour Theme",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/17945384/r/il/16480a/5893142082/il_fullxfull.5893142082_pc55.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "A rectangular wood sign printed with the text 'IT'S ME / Hi! I'm the problem / IT'S ME' in a stylized font, photographed on a desk/shelf setting.",
        },
      },
    ],
  },
  {
    brand: "SewShamrocks",
    item: "Cornelia Street Embroidery File - Taylor Inspired - Lover Album Patch Design",
    kind: "other",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/1884623210/cornelia-street-embroidery-file-taylor",
    price: "$3.50",
    imageUrl: "https://i.etsystatic.com/37595507/r/il/11830b/6818027967/il_fullxfull.6818027967_34c5.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/1884623210/cornelia-street-embroidery-file-taylor",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "The image shows an original embroidery patch design of a green street sign reading 'CORNELIA ST' (a reference to the Taylor Swift 'Lover' album song/lyric), with no photo, likeness, or official album artwork reproduced.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/1884623210/cornelia-street-embroidery-file-taylor",
          productId: "1884623210",
          available: true,
          price: "$3.50",
          title: "Cornelia Street Embroidery File - Taylor Inspired - Lover Album Patch Design",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/37595507/r/il/11830b/6818027967/il_fullxfull.6818027967_34c5.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "A green and white embroidered street-sign patch reading 'CORNELIA ST' shown against a plain background alongside 'EMBROIDERY DESIGNS' text.",
        },
      },
    ],
  },
  {
    brand: "GrimGoddessCo",
    item: "stretchy friendship bracelet • 'all too well' • charm bracelet",
    kind: "jewelry",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/4332968227/stretchy-friendship-bracelet-all-too",
    price: "$13.00",
    imageUrl: "https://i.etsystatic.com/57398872/r/il/d6f3df/8219036192/il_fullxfull.8219036192_oppq.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/4332968227/stretchy-friendship-bracelet-all-too",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "The bracelet is a handmade stretchy charm bracelet spelling out 'ALL TOO WELL' in letter beads (a Taylor Swift song title/lyric reference) with decorative charms; it is an original independent friendship-bracelet design with no photo, likeness, or official artwork reproduced.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/4332968227/stretchy-friendship-bracelet-all-too",
          productId: "4332968227",
          available: true,
          price: "$13.00",
          title: "stretchy friendship bracelet • 'all too well' • charm bracelet",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/57398872/r/il/d6f3df/8219036192/il_fullxfull.8219036192_oppq.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "A beaded stretchy bracelet with letter beads spelling 'ALL TOO WELL' alongside small decorative charms.",
        },
      },
    ],
  },
  {
    brand: "TheMainery",
    item: "In My Maine Era Tank Top | Swiftie Inspired Maine Shirt",
    kind: "apparel",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/4357340831/in-my-maine-era-tank-top-swiftie",
    price: "$17.95",
    imageUrl: "https://i.etsystatic.com/6378850/r/il/535145/7184123085/il_fullxfull.7184123085_9owe.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/4357340831/in-my-maine-era-tank-top-swiftie",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "The tank top features bold bubble-letter text reading 'IN MY MAINE ERA' surrounded by Maine-themed icons (lobster, moose, lighthouse, sailboat), an original design riffing on Taylor Swift's 'Eras' concept/general theme with no photo, likeness, or official tour/album artwork reproduced.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/4357340831/in-my-maine-era-tank-top-swiftie",
          productId: "4357340831",
          available: true,
          price: "$17.95",
          title: "In My Maine Era Tank Top | Swiftie Inspired Maine Shirt",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/6378850/r/il/535145/7184123085/il_fullxfull.7184123085_9owe.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "Two women wearing tank tops printed with 'IN MY MAINE ERA' bubble text and small Maine icons (lobster, moose, lighthouse, sailboat) in pink and blue color schemes, against an outdoor coastal backdrop.",
        },
      },
    ],
  },
  {
    brand: "TheMainery",
    item: "In My Maine Era Coffee Mug | Swiftie Aesthetic Maine Souvenir",
    kind: "home-decor",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/4357417167/in-my-maine-era-coffee-mug-swiftie",
    price: "$16.95",
    imageUrl: "https://i.etsystatic.com/6378850/r/il/51af49/7184300815/il_fullxfull.7184300815_pbh6.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/4357417167/in-my-maine-era-coffee-mug-swiftie",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "The mug is printed with 'IN MY MAINE ERA' bubble-letter text and Maine-themed icons, an original design echoing Taylor Swift's general 'Eras' theme/wordplay with no photo, likeness, or official artwork reproduced.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/4357417167/in-my-maine-era-coffee-mug-swiftie",
          productId: "4357417167",
          available: true,
          price: "$16.95",
          title: "In My Maine Era Coffee Mug | Swiftie Aesthetic Maine Souvenir",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/6378850/r/il/51af49/7184300815/il_fullxfull.7184300815_pbh6.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "A coffee mug printed with 'IN MY MAINE ERA' text and small Maine-themed icons such as a lobster, lighthouse, and moose.",
        },
      },
    ],
  },
  {
    brand: "HEYPARTAY",
    item: "Custom Graduation Lei | Giant Friendship Bracelet Necklace | Senior 2027 (GRAD ERA)",
    kind: "accessory",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/4410526167/custom-graduation-lei-giant-friendship",
    price: "$44.95",
    imageUrl: "https://i.etsystatic.com/60256362/r/il/08339f/7870722395/il_fullxfull.7870722395_7vrz.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/4410526167/custom-graduation-lei-giant-friendship",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "Giant beaded lei/necklace styled as an oversized friendship bracelet, with letter beads spelling 'GRAD ERA' — an original pun riffing on Taylor Swift's Eras Tour concept, accented with disco-ball beads reminiscent of Eras tour visual motifs.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/4410526167/custom-graduation-lei-giant-friendship",
          productId: "4410526167",
          available: true,
          price: "$44.95",
          title: "Custom Graduation Lei | Giant Friendship Bracelet Necklace | Senior 2027 (GRAD ERA)",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/60256362/r/il/08339f/7870722395/il_fullxfull.7870722395_7vrz.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "A person in a graduation gown wearing a large purple, gold, white, and silver disco-ball beaded lei with letter beads spelling 'GRAD ERA.'",
        },
      },
    ],
  },
  {
    brand: "SHOPViABiA",
    item: "I Protect the Family - Father Figure Inspired Sticker - Eras",
    kind: "other",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/4411347103/i-protect-the-family-father-figure",
    price: "$4.00",
    imageUrl: "https://i.etsystatic.com/24797225/r/il/634ade/7436057260/il_fullxfull.7436057260_n514.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/4411347103/i-protect-the-family-father-figure",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "Vinyl sticker with an original multicolor vertical-stripe background (referencing era-color palettes) and bold serif text reading 'I PROTECT THE FAMILY' — a lyric-inspired independent design, no photograph or official artwork used.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/4411347103/i-protect-the-family-father-figure",
          productId: "4411347103",
          available: true,
          price: "$4.00",
          title: "I Protect the Family - Father Figure Inspired Sticker - Eras",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/24797225/r/il/634ade/7436057260/il_fullxfull.7436057260_n514.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "A rectangular sticker with vertical color-block stripes in muted earth tones and the white serif text 'I PROTECT THE FAMILY' centered on it.",
        },
      },
    ],
  },
  {
    brand: "JunieandRoo",
    item: "Taylor Inspired Bookmarks|Life of a Bookgirl|Tour|Gifts|Readers",
    kind: "accessory",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/4450047068/taylor-inspired-bookmarks",
    price: "$4.50",
    imageUrl: "https://i.etsystatic.com/15946213/r/il/f29631/7707793461/il_fullxfull.7707793461_r67w.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/4450047068/taylor-inspired-bookmarks",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "Glossy teal glitter-effect bookmark with original red serif text reading 'THE LIFE OF A BOOKGIRL' — a wordplay design inspired by a Taylor Swift era name, with no likeness or official artwork reproduced.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/4450047068/taylor-inspired-bookmarks",
          productId: "4450047068",
          available: true,
          price: "$4.50",
          title: "Taylor Inspired Bookmarks|Life of a Bookgirl|Tour|Gifts|Readers",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/15946213/r/il/f29631/7707793461/il_fullxfull.7707793461_r67w.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "A teal glittery bookmark with sparkle/bokeh graphics and red text 'THE LIFE OF A BOOKGIRL' resting on an open paperback book.",
        },
      },
    ],
  },
  {
    brand: "SpelledWithLoveDecor",
    item: "Swiftie Definition Sign, Taylor Swift Fan Decor, Eras Tour Inspired Gift",
    kind: "home-decor",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/4452218104/swiftie-definition-sign-taylor-swift-fan",
    price: "$56.00",
    imageUrl: "https://i.etsystatic.com/15935017/r/il/c14de5/7721941765/il_fullxfull.7721941765_p0bz.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/4452218104/swiftie-definition-sign-taylor-swift-fan",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "Wooden/printed wall sign styled as a dictionary-definition entry for the word 'Swiftie' — purely typographic original design with no photograph, album art, or tour graphic reproduced.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/4452218104/swiftie-definition-sign-taylor-swift-fan",
          productId: "4452218104",
          available: true,
          price: "$56.00",
          title: "Swiftie Definition Sign, Taylor Swift Fan Decor, Eras Tour Inspired Gift",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/15935017/r/il/c14de5/7721941765/il_fullxfull.7721941765_p0bz.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "A vertical decorative sign with dictionary-style typography defining the fan term 'Swiftie,' in a neutral color palette with no imagery of a person.",
        },
      },
    ],
  },
  {
    brand: "TheFriendshipXchange",
    item: "Showgirl Inspired Sourdough Accessories Set: Cotton Jar Cover & Friendship Bracelet",
    kind: "home-decor",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/4453367609/showgirl-inspired-sourdough-accessories",
    price: "$15.00",
    imageUrl: "https://i.etsystatic.com/52041116/r/il/618e06/7729449475/il_fullxfull.7729449475_ff8q.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/4453367609/showgirl-inspired-sourdough-accessories",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "Sourdough starter jar cotton cover paired with a matching beaded friendship bracelet, both bearing an original text pun ('Loaf of a Doughgirl') riffing on the Taylor Swift era name 'Showgirl' — no likeness or official artwork used.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/4453367609/showgirl-inspired-sourdough-accessories",
          productId: "4453367609",
          available: true,
          price: "$15.00",
          title: "Showgirl Inspired Sourdough Accessories Set: Cotton Jar Cover & Friendship Bracelet",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/52041116/r/il/618e06/7729449475/il_fullxfull.7729449475_ff8q.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "A cloth jar cover and a beaded bracelet, both printed/lettered with a baking-themed pun on 'Showgirl,' laid out with sourdough-related props.",
        },
      },
    ],
  },
  {
    brand: "WishUponAWrist",
    item: "Taylor Swift Themed Birthday Party Friendship Bracelets, Personalized Swiftie Gifts",
    kind: "jewelry",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/4527636744/taylor-swift-themed-birthday-party",
    price: "$5.00",
    imageUrl: "https://i.etsystatic.com/59546301/r/il/ddb3d6/8175915610/il_fullxfull.8175915610_e3t2.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/4527636744/taylor-swift-themed-birthday-party",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "Handmade beaded friendship bracelets with individual lyric/era word beads (e.g. 'Bejeweled,' 'Long Live,' 'Shake It Off,' '22') — original fan-craft text designs with no photograph or official artwork reproduced.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/4527636744/taylor-swift-themed-birthday-party",
          productId: "4527636744",
          available: true,
          price: "$5.00",
          title: "Taylor Swift Themed Birthday Party Friendship Bracelets, Personalized Swiftie Gifts",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/59546301/r/il/ddb3d6/8175915610/il_fullxfull.8175915610_e3t2.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "A set of colorful beaded friendship bracelets, each spelling out a different Taylor Swift song title or lyric phrase in lettered beads.",
        },
      },
    ],
  },
  {
    brand: "ResinbyMissyRoxy",
    item: "Taylor Swift Eras Tour Inspired Chubby Pumpkins! Set of 12, Variation 1",
    kind: "home-decor",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/4565565933/taylor-swift-eras-tour-inspired-chubby",
    price: "$35.00",
    imageUrl: "https://i.etsystatic.com/51263734/r/il/81afa7/8501336213/il_fullxfull.8501336213_cg5u.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/4565565933/taylor-swift-eras-tour-inspired-chubby",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "Handmade set of 12 miniature resin pumpkins in varied glitter finishes, each color loosely evoking a different Taylor Swift 'Eras' color palette without depicting her likeness or any official artwork.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/4565565933/taylor-swift-eras-tour-inspired-chubby",
          productId: "4565565933",
          available: true,
          price: "$35.00",
          title: "Taylor Swift Eras Tour Inspired Chubby Pumpkins! Set of 12, Variation 1",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/51263734/r/il/81afa7/8501336213/il_fullxfull.8501336213_cg5u.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "The image shows twelve small glossy/glitter resin pumpkins in a rainbow of solid colors (navy, copper, teal, gold, purple, red, ice-blue, black, olive, dark bronze, magenta, and blue-purple) arranged in a circle on a white surface, with no faces, photos, or logos visible.",
        },
      },
    ],
  },
  {
    brand: "ResinbyMissyRoxy",
    item: "Set of 12! Cute little Fall Pumpkins fanmade Swiftie Inspired! OOAK Handmade V1",
    kind: "home-decor",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/4565575008/set-of-12-cute-little-fall-pumpkins",
    price: "$30.00",
    imageUrl: "https://i.etsystatic.com/51263734/r/il/f6ab6b/8453375396/il_fullxfull.8453375396_7lr4.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/4565575008/set-of-12-cute-little-fall-pumpkins",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "One-of-a-kind handmade set of 12 small resin pumpkins in assorted glitter/metallic colors, marketed as 'Swiftie inspired' via color theming rather than any likeness or official artwork.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/4565575008/set-of-12-cute-little-fall-pumpkins",
          productId: "4565575008",
          available: true,
          price: "$30.00",
          title: "Set of 12! Cute little Fall Pumpkins fanmade Swiftie Inspired! OOAK Handmade V1",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/51263734/r/il/f6ab6b/8453375396/il_fullxfull.8453375396_7lr4.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "The image shows twelve small resin pumpkins in different solid glitter colors (green, gold, purple, red, blue, black, magenta, olive, bronze, white, orange) displayed on tiered black glass shelves, with no photos, faces, or logos visible.",
        },
      },
    ],
  },
  {
    brand: "ResinbyMissyRoxy",
    item: "Set of 12! Cute Tall Pumpkins fanmade Swiftie Inspired! OOAK Handmade V1",
    kind: "home-decor",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/4565580254/set-of-12-cute-tall-pumpkins-fanmade",
    price: "$30.00",
    imageUrl: "https://i.etsystatic.com/51263734/r/il/a00459/8453418668/il_fullxfull.8453418668_nc1n.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/4565580254/set-of-12-cute-tall-pumpkins-fanmade",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "One-of-a-kind handmade set of 12 taller resin pumpkins in varied glitter colors, described as fan-made 'Swiftie inspired' decor via color palette only, no likeness or official imagery used.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/4565580254/set-of-12-cute-tall-pumpkins-fanmade",
          productId: "4565580254",
          available: true,
          price: "$30.00",
          title: "Set of 12! Cute Tall Pumpkins fanmade Swiftie Inspired! OOAK Handmade V1",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/51263734/r/il/a00459/8453418668/il_fullxfull.8453418668_nc1n.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "The image shows twelve taller resin pumpkins in solid glitter colors (green, gold, purple, dark red, light blue, black, pink-purple, olive, bronze, navy, white, orange) arranged on multi-tier black glass shelving, with no faces or logos visible.",
        },
      },
    ],
  },
  {
    brand: "ResinbyMissyRoxy",
    item: "Set of 12! Cute Tall Pumpkins fanmade Swiftie Inspired! OOAK Handmade V2",
    kind: "home-decor",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/4565585448/set-of-12-cute-tall-pumpkins-fanmade",
    price: "$30.00",
    imageUrl: "https://i.etsystatic.com/51263734/r/il/9a1a74/8453458684/il_fullxfull.8453458684_m5qj.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/4565585448/set-of-12-cute-tall-pumpkins-fanmade",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "One-of-a-kind handmade set of 12 tall resin pumpkins, second color variation, sold as fan-made 'Swiftie inspired' decor via color theming only, no likeness or official artwork depicted.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/4565585448/set-of-12-cute-tall-pumpkins-fanmade",
          productId: "4565585448",
          available: true,
          price: "$30.00",
          title: "Set of 12! Cute Tall Pumpkins fanmade Swiftie Inspired! OOAK Handmade V2",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/51263734/r/il/9a1a74/8453458684/il_fullxfull.8453458684_m5qj.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "The image shows twelve tall resin pumpkins in solid glitter colors (green, gold, purple, dark red, light blue, black, blue-pink, olive, bronze, navy, white, orange) stacked on four tiers of a black glass shelf, with no faces or logos visible.",
        },
      },
    ],
  },
  {
    brand: "ResinbyMissyRoxy",
    item: "Taylor Swift Eras Tour Inspired Chubby Pumpkins! Set of 12, Variation 2",
    kind: "home-decor",
    retailer: "www.etsy.com",
    url: "https://www.etsy.com/listing/4565591008/taylor-swift-eras-tour-inspired-chubby",
    price: "$35.00",
    imageUrl: "https://i.etsystatic.com/51263734/r/il/c2eafd/8501350791/il_fullxfull.8501350791_j5jv.jpg",
    inStock: true,
    discoveredVia: "etsy-search",
    discoveredAt: "2026-08-30T21:10:00.000Z",
    verifiedAt: "2026-08-30T21:10:00.000Z",
    provenance: [
      {
        discoveredVia: "etsy-search",
        discoveredAt: "2026-08-30T21:10:00.000Z",
        sourceUrl: "https://www.etsy.com/listing/4565591008/taylor-swift-eras-tour-inspired-chubby",
        d3: {
          judgment: "inspired-original",
          prohibitedMaterial: "none",
          basis: "Handmade set of 12 miniature resin pumpkins, second color variation, each hue evoking a different Taylor Swift 'Eras' color palette without depicting her likeness or official artwork.",
        },
        e1: {
          listingVerified: true,
          evidenceUrl: "https://www.etsy.com/listing/4565591008/taylor-swift-eras-tour-inspired-chubby",
          productId: "4565591008",
          available: true,
          price: "$35.00",
          title: "Taylor Swift Eras Tour Inspired Chubby Pumpkins! Set of 12, Variation 2",
        },
        e2: {
          imageVerified: true,
          evidenceUrl: "https://i.etsystatic.com/51263734/r/il/c2eafd/8501350791/il_fullxfull.8501350791_j5jv.jpg",
          officialArtwork: false,
          tourGraphic: false,
          taylorPhoto: false,
          depicts: "The image shows twelve small chubby resin pumpkins in solid glitter colors (green, gold, purple, dark red, light blue, black, blue-purple, olive, bronze, navy, white, orange) arranged on tiered black glass shelves, with no faces, photos, or logos visible.",
        },
      },
    ],
  },

];

export default FAN_MADE;
