// GENERATED FILE — do not hand-edit.
// Produced by scripts/sync-longlive-era-secrets.mjs from supabase/seed/era-secrets/**
// Re-run that script after era-secret-seed changes; don't edit this file directly.

import type { EraId, EraSecret } from '@swift2/experience';

export const ERA_SECRETS_RAW: Partial<Record<EraId, EraSecret[]>> = {
  "1989": [
    {
      slug: "1989-lowercase-inversion",
      title: "She flipped her own cipher",
      secret: "Fans spent five albums decoding messages hidden in the CAPITALIZED letters of her printed lyrics. On 1989 she inverted the trick — the hidden messages moved to the lowercase letters — and read in track order they tell one continuous story of the two years before the album.",
      deeperLink: "egg:1989-lowercase-liner-codes",
      sources: [{ name: "Taylor Swift's '1989' Liner Note Messages & Reference Guide", url: "https://www.billboard.com/music/music-news/taylor-swift-1989-liner-notes-6296676/" }, { name: "Liner notes and easter eggs: How Taylor Swift turned fandom into a scavenger hunt", url: "https://www.today.com/popculture/music/taylor-swift-easter-eggs-hidden-messages-rcna51887" }],
    },
    {
      slug: "1989-65-polaroids",
      title: "Sixty-five Polaroids, five albums deep",
      secret: "Every 1989 CD came with 13 Polaroids of Taylor, lyrics scrawled in marker along the bottom. What most fans never clocked: there were 65 different Polaroids in circulation, packed in five random sets of 13 — completing the collection meant buying the album five times over.",
      deeperLink: "moment:vault-red-a-yahoo-livestream-announces-1989-her-first-documented-offic",
      sources: [{ name: "1989 (album)", url: "https://en.wikipedia.org/wiki/1989_(album)" }, { name: "Beyond 1989: Taylor Swift and Polaroids", url: "https://www.thelineofbestfit.com/features/articles/beyond-1989-taylor-swift-and-polaroids" }],
    },
    {
      slug: "1989-stay-came-from-a-dream",
      title: "The \"stay!\" is from an actual dream",
      secret: "That high, almost operatic 'stay!' on 'All You Had to Do Was Stay' isn't a studio trick — it came from a dream. Taylor dreamed she opened the door to an ex and the only sound that came out was that weird high note. She woke up, recorded it into her phone, and built the hook around it.",
      deeperLink: "song:all-you-had-to-do-was-stay",
      sources: [{ name: "Taylor Swift Reveals '1989' Song 'All You Had To Do Was Stay' Is About A Dream", url: "https://www.ibtimes.com/taylor-swift-reveals-1989-song-all-you-had-do-was-stay-about-dream-her-ex-boyfriend-2147005" }, { name: "All You Had to Do Was Stay", url: "https://en.wikipedia.org/wiki/All_You_Had_to_Do_Was_Stay_(Taylor_Swift_song)" }],
    },
    {
      slug: "1989-ootw-voice-memo",
      title: "Thirty minutes, one voice memo",
      secret: "Jack Antonoff sent her the 'Out of the Woods' instrumental and got a voice memo back with the melody and lyrics roughly thirty minutes later. It was the first time Taylor had ever written a song over someone else's finished track — the working method that would carry through folklore and beyond.",
      deeperLink: "song:out-of-the-woods",
      sources: [{ name: "Taylor Swift's 'Out Of The Woods': Jack Antonoff Reveals Inspiration", url: "https://www.billboard.com/articles/news/6281680/taylor-swift-out-of-the-woods-jack-antonoff" }, { name: "Taylor Swift's 'Out of the Woods': Jack Antonoff on Inspiration", url: "https://www.hollywoodreporter.com/earshot/taylor-swifts-woods-jack-antonoff-inspiration-new-1989-song-title-740605" }],
    },
    {
      slug: "1989-starbucks-lovers",
      title: "There are no Starbucks lovers",
      secret: "The lyric is \"got a long list of ex-lovers\" — but \"all the lonely Starbucks lovers\" was misheard so universally that even her mom heard it wrong. Taylor eventually leaned in, tweeting: \"Sending my love to all the lonely Starbucks lovers out there this Valentine's Day.\"",
      deeperLink: "song:blank-space",
      sources: [{ name: "Even Taylor Swift's Mom Thought She Was Singing \"Starbucks Lovers\" in \"Blank Space\"", url: "https://www.eonline.com/news/659883/even-taylor-swift-s-mom-thought-she-was-singing-starbucks-lovers-in-blank-space" }, { name: "Taylor Swift's Blank Space Lyrics Not About Starbucks Lovers", url: "https://time.com/3895936/taylor-swift-blank-space-lyrics-starbucks-lovers/" }],
    },
  ],
  "debut": [
    {
      slug: "debut-track-five-tradition",
      title: "The track-five tradition begins with \"Cold As You\"",
      secret: "The pattern fans would spend a decade decoding starts on the very first album: track 5 is Taylor's most vulnerable song, a habit she later admitted was instinctive. On the 2006 debut that seat belongs to \"Cold As You\" — a quiet, cutting breakup song, years before \"All Too Well\" made the track-five slot legendary.",
      deeperLink: "song:cold-as-you",
      sources: [{ name: "Here Is Every Taylor Swift Track 5, Ranked (Critic's Picks)", url: "https://www.billboard.com/lists/taylor-swift-track-fives-ranked/" }, { name: "'So Long, London' Is a Classic Taylor Swift Track 5 Song", url: "https://time.com/6969042/taylor-swift-track-five-songs-tortured-poets-department/" }],
    },
    {
      slug: "debut-anthem-strategy",
      title: "The national anthem was her way onto a stage",
      secret: "Before any record deal, a young Taylor worked out a hack for singing to big crowds. \"When I was 11 years old, it occurred to me that the national anthem was the best way to get in front of a large group of people if you don't have a record deal,\" she said — so she sang it anywhere she could, working up to a Philadelphia 76ers game in front of more than 20,000 fans.",
      deeperLink: "song:tim-mcgraw",
      sources: [{ name: "Taylor Swift's connections to sports go back to her early days performing the national anthem", url: "https://www.nbcphiladelphia.com/news/local/taylor-swifts-connections-to-sports-go-back-to-her-early-days-performing-the-national-anthem/3772093/" }, { name: "Watch 12-year-old Taylor Swift sing impressive anthem before 76ers game", url: "https://www.foxsports.com/stories/nba/watch-12-year-old-taylor-swift-sing-impressive-anthem-before-76ers-game" }],
    },
    {
      slug: "debut-named-after-james-taylor",
      title: "She was named after James Taylor — on purpose, for business",
      secret: "Her parents chose a gender-neutral name deliberately: her mother, a former mutual-fund marketing executive, believed \"Taylor\" would read the same on a business card whether people pictured a man or a woman. The singer they had in mind when they picked it was James Taylor.",
      deeperLink: "song:a-place-in-this-world",
      sources: [{ name: "Taylor Swift", url: "https://en.wikipedia.org/wiki/Taylor_Swift" }, { name: "Taylor Swift Was Named After This Massachusetts Legend", url: "https://wbsm.com/massachusetts-taylor-swift-named-james-taylor/" }],
    },
    {
      slug: "debut-abercrombie-rising-stars",
      title: "She was an Abercrombie model before she had a single out",
      secret: "Two years before her debut single, a 14-year-old Taylor turned up in Abercrombie & Fitch's \"Rising Stars\" campaign — shot by the brand's longtime photographer Bruce Weber and printed in its glossy A&F Quarterly. She was billed as a star on the rise before a single one of her records existed.",
      deeperLink: "song:the-outside",
      sources: [{ name: "Abercrombie Updates Its \"Stars On The Rise\" Ad Campaign For A New Generation", url: "https://www.buzzfeednews.com/article/sapna/abercrombie-revives-stars-on-the-rise-ad-campaign" }, { name: "Abercrombie & Fitch Debuts New Rising Stars", url: "https://variety.com/2013/scene/vpage/abercrombie-fitch-rising-stars-1200561909/" }],
    },
    {
      slug: "debut-christmas-tree-farm",
      title: "She actually grew up on a Christmas tree farm",
      secret: "Before Nashville, before the guitar, Taylor spent her early childhood on an 11-acre Christmas tree farm outside Reading, Pennsylvania — Fraser and Douglas firs her family sold by the truckload. She helped work it as a kid, then revisited the whole memory decades later in her 2019 song \"Christmas Tree Farm.\"",
      deeperLink: "song:marys-song-oh-my-my-my",
      sources: [{ name: "Everything You Need To Know About Taylor Swift's Christmas Tree Farm", url: "https://www.refinery29.com/en-us/2019/12/8979759/taylor-swift-pine-ridge-christmas-tree-farm-pa" }, { name: "'Christmas Tree Farm': Taylor Swift recalls growing up on Pennsylvania Pine Ridge Farm in new music video", url: "https://6abc.com/post/taylor-swift-recalls-growing-up-on-pa-farm-in-new-music-video/5737195/" }],
    },
  ],
  "evermore": [
    {
      slug: "evermore-vinyl-modern-record",
      title: "The vinyl broke a 30-year record — six months late",
      secret: "evermore's LPs shipped in May 2021, five months after the surprise drop — and promptly sold 102,000 copies in one week, the biggest vinyl sales week since tracking began in 1991 and the first ever to clear 100,000. The old record (Jack White's Lazaretto) was 40,000. The wave vaulted the album from No. 74 straight back to No. 1.",
      deeperLink: "moment:vault-evermore-evermore-makes-her-the-first-artist-to-top-both-charts-at-on",
      sources: [{ name: "Taylor Swift's 'Evermore' Breaks Modern-Era Record for Biggest Vinyl Album Sales Week", url: "https://www.billboard.com/pro/taylor-swift-evermore-record-breaking-vinyl-album-sales-week/" }, { name: "Taylor Swift's 'Evermore' Is The First Album To Sell 100,000 Vinyl Copies In One Week In U.S. History", url: "https://www.forbes.com/sites/hughmcintyre/2021/06/07/taylor-swifts-evermore-is-the-first-album-to-sell-100000-vinyl-copies-in-one-week-in-us-history/" }],
    },
    {
      slug: "evermore-gasoline-return-favor",
      title: "She paid HAIM back with a verse on their song",
      secret: "The murder ballad had a sequel: two months after the Haim sisters sang on \"no body, no crime,\" Taylor returned the favor with guest vocals on the remix of \"Gasoline\" — she'd told them it was her favorite song on Women in Music Pt. III, so when the expanded edition came together, they called it in. Este gets killed in her song; Taylor sings on Este's.",
      deeperLink: "moment:vault-evermore-a-surprise-cameo-at-haims-sold-out-o2-arena-show",
      sources: [{ name: "Taylor Swift Joins Haim for Remix of Sister Trio's 'Gasoline'", url: "https://variety.com/2021/music/news/taylor-swift-haim-remix-featured-gasoline-1234910806/" }, { name: "Haim Release 'Women in Music Pt. III' Expanded Edition With Taylor Swift", url: "https://www.rollingstone.com/music/music-news/taylor-swift-haim-gasoline-1128513/" }],
    },
    {
      slug: "evermore-true-crime-origin",
      title: "no body, no crime came out of a true-crime binge",
      secret: "Taylor wrote \"no body, no crime\" alone, after a lockdown deep-dive into true-crime podcasts and documentaries — then named the victim Este because, in her words, she's \"the friend I have who would be stoked to be in a song like that.\" The genre homework shows: the song is built like an episode, alibi and all.",
      deeperLink: "song:no-body-no-crime",
      sources: [{ name: "Taylor Swift Channels True-Crime Fandom In New Song, 'No Body, No Crime'", url: "https://www.oxygen.com/true-crime-buzz/taylor-swifts-no-body-no-crime-off-evermore-album-has-true-crime-roots" }, { name: "What Is No Body No Crime About On Taylor Swift Evermore", url: "https://www.refinery29.com/en-us/2020/12/10222300/taylor-swift-haim-no-body-no-crime-real-murder-mystery" }],
    },
    {
      slug: "evermore-gold-rush-lone-antonoff",
      title: "One song on evermore is a heist",
      secret: "Aaron Dessner produced every track on evermore except one: \"gold rush\" is Jack Antonoff's lone fingerprint on the record, a glittering pop daydream smuggled into the middle of the folk album. Flip it around and it makes the sister-album split visible — folklore split the credits, evermore went almost all-in on Dessner.",
      deeperLink: "song:gold-rush",
      sources: [{ name: "Evermore", url: "https://en.wikipedia.org/wiki/Evermore" }, { name: "Gold Rush by Taylor Swift", url: "https://www.songfacts.com/facts/taylor-swift/gold-rush" }],
    },
    {
      slug: "evermore-happiness-gatsby",
      title: "happiness is narrated from inside The Great Gatsby",
      secret: "Listen to \"happiness\" with Fitzgerald open: \"I hope she'll be your beautiful fool\" reworks Daisy Buchanan's most famous line, and \"all you want from me now is the green light of forgiveness\" borrows the dock light itself. Taylor — who was \"feeling so Gatsby\" back on reputation — wrote her divorce ballad in Daisy's vocabulary.",
      deeperLink: "song:happiness",
      sources: [{ name: "Zelda, Daisy, Taylor: Beautiful Fools?", url: "https://post45.org/2020/12/zelda-daisy-taylor-beautiful-fools/" }, { name: "The Real Meaning Behind Taylor Swift's Happiness Lyrics", url: "https://www.nickiswift.com/294137/the-real-meaning-behind-taylor-swifts-happiness-lyrics/" }],
    },
  ],
  "fearless": [
    {
      slug: "fearless-track-five-tradition",
      title: "Track five is the album's rawest nerve — here, \"White Horse\"",
      secret: "Fans clocked the pattern before Taylor named it: track 5 of every album is its most emotionally exposed song. \"Instinctively I was just kind of putting a very vulnerable, personal, honest, emotional song as track five,\" she confirmed in 2019. Fearless hands the seat to \"White Horse\" — a fairy tale collapsing in real time.",
      deeperLink: "song:white-horse",
      sources: [{ name: "Here Is Every Taylor Swift Track 5, Ranked (Critic's Picks)", url: "https://www.billboard.com/lists/taylor-swift-track-fives-ranked/" }, { name: "'So Long, London' Is a Classic Taylor Swift Track 5 Song", url: "https://time.com/6969042/taylor-swift-track-five-songs-tortured-poets-department/" }],
    },
    {
      slug: "fearless-what-fearless-means",
      title: "The album title is a definition — and it isn't \"unafraid\"",
      secret: "The Fearless booklet opens with Taylor defining her own title: \"Fearless is not the absence of fear… fearless is having fears. Fearless is having doubts. Lots of them. To me, fearless is living in spite of those things that scare you to death.\" The whole era, stated in four lines before the first song plays.",
      deeperLink: "song:fearless",
      sources: [{ name: "Taylor Swift – Fearless [Liner Notes]", url: "https://readdork.com/lyrics/taylor-swift-fearless-liner-notes" }, { name: "Taylor Swift — Wikiquote (Fearless liner notes)", url: "https://en.wikiquote.org/wiki/Taylor_Swift" }],
    },
    {
      slug: "fearless-love-story-castle-gwynn",
      title: "The \"Love Story\" castle is a short drive from Nashville",
      secret: "Taylor assumed the \"Love Story\" video would mean flying to Europe for a castle — until someone found Castle Gwynn, a real turreted castle in Arrington, Tennessee, barely outside Nashville. \"I just didn't think that castles were in Tennessee at all,\" she admitted. Locals know it as the home of the state's Renaissance Festival.",
      deeperLink: "song:love-story",
      sources: [{ name: "How a Tennessee castle brought 'Love Story' to life", url: "https://www.wkrn.com/news/local-news/story-behind-castle-gwynn-where-taylor-swift-filmed-love-story-music-video/" }, { name: "Castle in Taylor Swift's music video 'Love Story' to host weddings", url: "https://www.wsmv.com/2024/04/24/castle-taylor-swifts-music-video-love-story-host-weddings/" }],
    },
    {
      slug: "fearless-vault-tracks-guests",
      title: "The re-recordings started here — and the vault brought friends",
      secret: "Rebuilding Fearless as Fearless (Taylor's Version) in 2021 made it her first re-recorded album — and the first re-record ever to debut at No. 1. It also unlocked songs shelved in 2008: \"You All Over Me,\" the first \"From the Vault\" track she released, features Maren Morris, and the vault duet \"That's When\" pairs her with Keith Urban.",
      deeperLink: "song:you-all-over-me",
      sources: [{ name: "'Fearless (Taylor's Version)': Everything We Know", url: "https://www.billboard.com/music/pop/taylor-swift-fearless-taylors-version-everything-we-know-9552361/" }, { name: "Fearless (Taylor's Version)", url: "https://en.wikipedia.org/wiki/Fearless_(Taylor's_Version)" }],
    },
    {
      slug: "fearless-fifteen-miley-grammys",
      title: "Two teenagers sang \"Fifteen\" on the Grammy stage",
      secret: "At the 2009 Grammys, a 19-year-old Taylor played \"Fifteen\" on acoustic guitar and handed the chorus to her duet partner: 16-year-old Miley Cyrus. Two of the biggest teenagers in music, trading a song about surviving freshman year, on the industry's biggest night.",
      deeperLink: "song:fifteen",
      sources: [{ name: "'Fifteen,' Taylor Swift and Miley Cyrus — Grammy Awards 2009", url: "https://content.time.com/time/specials/packages/article/0,28804,1877619_1877620_1878024,00.html" }, { name: "Taylor Swift and Miley Cyrus' Beautiful, Live Duet of \"Fifteen\" Is Timeless", url: "https://www.nbc.com/nbc-insider/taylor-swift-miley-cyrus-sing-fifteen-listen" }],
    },
  ],
  "folklore": [
    {
      slug: "folklore-never-in-the-same-room",
      title: "The whole album was made by people who were never in the same room",
      secret: "Taylor and Aaron Dessner wrote and recorded all of folklore without once meeting in person — she cut her vocals in a home studio she named Kitty Committee, streaming takes to him live over Audiomovers. They weren't in the same room until September 2020, when she finally drove to Long Pond to film the documentary — months after the album was out.",
      deeperLink: "moment:vault-folklore-folklore-the-long-pond-studio-sessions-marks-her-directorial",
      sources: [{ name: "Aaron Dessner: Producing folklore And evermore", url: "https://www.soundonsound.com/people/aaron-dessner-producing-folklore-and-evermore" }, { name: "How Aaron Dessner and Taylor Swift Stripped Down Her Sound on 'Folklore'", url: "https://www.rollingstone.com/music/music-features/aaron-dessner-taylor-swift-interview-folklore-1033870/" }],
    },
    {
      slug: "folklore-seven-at-seven",
      title: "seven, at seven, at No. 7",
      secret: "The numbers on \"seven\" line up like she planned them: a narrator remembering being seven years old, sitting at track 7 — and when folklore dropped, the song entered Billboard's Hot Rock & Alternative Songs chart at No. 7. Her lucky number is 13, but for one week in 2020, seven put up a fight.",
      deeperLink: "song:seven",
      sources: [{ name: "Seven (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Seven_(Taylor_Swift_song)" }, { name: "Hot Rock & Alternative Songs — chart dated August 8, 2020", url: "https://www.billboard.com/charts/hot-rock-songs/2020-08-08/" }],
    },
    {
      slug: "folklore-first-f-bomb",
      title: "Fourteen years in, she finally swore on a record",
      secret: "\"mad woman\" carries the first F-bomb of Taylor's entire catalog — eight albums in. She'd held a private rule that she couldn't do it because she never had; folklore's characters broke it for her, and she told an interviewer the release of finally swearing on record felt, fittingly, \"f***ing fantastic.\"",
      deeperLink: "song:mad-woman",
      sources: [{ name: "Taylor Swift Explains Why It Felt \"F*cking Fantastic\" To F*cking Swear On folklore", url: "https://www.refinery29.com/en-us/2020/12/10216208/taylor-swift-folklore-interview-mad-woman-explicit-swear" }, { name: "Taylor Swift's Most Explicit Lyrics: Swear Words in Her Lyrics", url: "https://www.billboard.com/lists/taylor-swift-swear-words-lyrics-explicit/" }],
    },
    {
      slug: "folklore-marriage-story-ricochet",
      title: "my tears ricochet started with a movie about a divorce",
      secret: "The first lines of \"my tears ricochet\" — the first song written for folklore — came right after Taylor watched Marriage Story. She'd found herself wrecked by divorce narratives without ever having lived one, and realized why: losing her masters felt like watching a marriage end. The film gave the grief its shape.",
      deeperLink: "song:my-tears-ricochet",
      sources: [{ name: "Taylor Swift wrote early 'My Tears Ricochet' lyrics after watching 'Marriage Story'", url: "https://www.nme.com/news/music/taylor-swift-my-tears-ricochet-marriage-story-2834641" }, { name: "Taylor Swift's \"My Tears Ricochet\" Lyrics Were Inspired By 'Marriage Story'", url: "https://www.bustle.com/entertainment/taylor-swifts-my-tears-ricochet-lyrics-were-inspired-by-marriage-story" }],
    },
    {
      slug: "folklore-rubber-bridge-guitar",
      title: "That \"old\" guitar sound is a rubber band trick from an LA shop",
      secret: "The muted, decades-old-sounding guitar under \"invisible string\" is a real 1950s-style guitar fitted with a rubber bridge by Reuben Cox of LA's Old Style Guitar Shop — Aaron Dessner says the rubber \"deadens the strings so that it sounds old.\" The same instrument came back to open \"willow.\" One thrift-store mod, the sonic signature of both sister albums.",
      deeperLink: "song:invisible-string",
      sources: [{ name: "Five Sounds With Aaron Dessner", url: "https://vintageking.com/blog/five-sounds-aaron-dessner/" }, { name: "How to get the rubber bridge guitar sound without permanently modifying your guitar", url: "https://www.guitarworld.com/features/diy-rubber-bridge-indie-rock-sound" }],
    },
  ],
  "lover": [
    {
      slug: "lover-choir-that-funds-a-school",
      title: "The kids on the last track are paying a school's bills",
      secret: "Those children's voices on 'It's Nice to Have a Friend' belong to a youth choir from Toronto's Regent Park School of Music — sampled from a library producer Frank Dukes built so that the royalties flow back to fund the school. Every play of the album's quietest track helps keep a music program running.",
      deeperLink: "song:its-nice-to-have-a-friend",
      sources: [{ name: "Taylor Swift Sampled a Toronto Youth Choir on 'Lover'", url: "https://exclaim.ca/music/article/taylor_swift_sampled_regent_park_youth_choir_on_lover_track_its_nice_to_have_a_friend" }, { name: "Taylor Swift's Lover features students from Toronto's Regent Park School of Music", url: "https://nowtoronto.com/music/taylor-swift-regent-park-school-of-music/" }],
    },
    {
      slug: "lover-spelling-is-fun-vanishes",
      title: "The line that quietly vanished",
      secret: "Two days before Lover dropped, the most clowned-on line of \"ME!\" — \"Hey kids, spelling is fun!\" — silently disappeared from the song. No statement, no acknowledgment; the album version simply doesn't have it. She had defended the line for months as a tone decision made in the studio.",
      deeperLink: "song:me",
      sources: [{ name: "Taylor Swift Drops 'Spelling Is Fun!' Lyric From 'Me!'", url: "https://www.billboard.com/music/pop/taylor-swift-drops-spelling-is-fun-lyric-me-8527951/" }, { name: "Taylor Swift Removes 'Spelling Is Fun!' Lyric From 'Me!'", url: "https://www.rollingstone.com/music/music-news/taylor-swift-removes-me-lyric-874631/" }],
    },
    {
      slug: "lover-me-video-called-its-shot",
      title: "The 'ME!' video called its shot",
      secret: "A painting of the Dixie Chicks hangs on the wall of the 'ME!' video — four months before they actually appeared on Lover, harmonizing on 'Soon You'll Get Better.' And the kitten Brendon Urie hands her mid-video became a real adoption: that's how Benjamin Button joined the family.",
      deeperLink: "egg:me-video-chicks-painting",
      sources: [{ name: "Taylor Swift's 'ME!' Video Easter Eggs: Album Title, Her Next Single & More", url: "https://www.billboard.com/music/pop/taylor-swift-me-video-easter-eggs-8509007/" }, { name: "Taylor Swift's ''ME!'' Music Video: All the Hidden Easter Eggs and Symbolism", url: "https://www.eonline.com/news/1035688/taylor-swift-s-me-music-video-all-the-hidden-easter-eggs-and-symbolism" }],
    },
    {
      slug: "lover-the-man-graffiti-wall",
      title: "Freeze-frame the subway wall",
      secret: "Pause the subway scene in 'The Man': the wall behind Tyler Swift is tagged with her album titles, a 'Missing — if found return to Taylor Swift' poster standing in for the debut, and one word fans had been chasing for years: Karma. All of it shot mid-fight over her stolen masters.",
      deeperLink: "egg:the-man-karma-graffiti",
      sources: [{ name: "Easter Eggs In Taylor Swift's 'The Man' Video Are Everywhere", url: "https://www.marieclaire.com/celebrity/a31129779/easter-eggs-taylor-swift-the-man/" }, { name: "7 Easter Eggs You Might Not Have Noticed in Taylor Swift's \"The Man\" Music Video", url: "https://www.distractify.com/p/taylor-swift-the-man-music-video-easter-eggs" }],
    },
    {
      slug: "lover-house-eras-map",
      title: "The house with an era behind every door",
      secret: "The fan reading: every room in the 'Lover' video's snow-globe house is one of her albums — the red room for Red, the hazy attic for reputation. Taylor has never said it outright, but when Midnights was announced, she liked the TikTok declaring the starry ceiling the final room.",
      deeperLink: "song:lover",
      sources: [{ name: "Taylor Swift Approves of This Theory About Her 10 Albums", url: "https://www.eonline.com/news/1344281/taylor-swift-approves-of-this-theory-about-her-10-albums" }, { name: "Taylor Swift seemingly confirms fan theory about the \"Lover\" house", url: "https://digital.abcaudio.com/news/taylor-swift-seemingly-confirms-fan-theory-about-lover-house" }],
    },
  ],
  "midnights": [
    {
      slug: "midnights-track-five-tradition",
      title: "Track five is the seat she saves for the knife-twist",
      secret: "Fans spotted it before Taylor admitted it: track 5 of every album is its most vulnerable song. \"Instinctively I was just kind of putting a very vulnerable, personal, honest, emotional song as track five,\" she confirmed in 2019. Midnights' entry in the tradition: \"You're On Your Own, Kid.\"",
      deeperLink: "song:youre-on-your-own-kid",
      sources: [{ name: "Here Is Every Taylor Swift Track 5, Ranked (Critic's Picks)", url: "https://www.billboard.com/lists/taylor-swift-track-fives-ranked/" }, { name: "'So Long, London' is a Classic Taylor Swift Track 5 Song", url: "https://time.com/6969042/taylor-swift-track-five-songs-tortured-poets-department/" }],
    },
    {
      slug: "midnights-vinyl-clock",
      title: "The four vinyl back covers are a clock",
      secret: "The Jade Green, Blood Moon, Mahogany, and Lavender vinyl editions aren't just color variants — line their back covers up and the numbers printed on each curve complete one clock face, 12 to 11. Her store even sold the shelf kit with brass hands to hang them as a working clock.",
      deeperLink: "moment:vault-midnights-custom-schiaparelli-with-a-midnights-clock-hidden-in-the-cho",
      sources: [{ name: "Taylor Swift's 'Midnights' LPs Assemble to Make a Clock", url: "https://www.billboard.com/music/music-news/taylor-swift-midnights-artwork-clock-1235140079/" }, { name: "Taylor Swift's 'Midnights' Album Artwork Assemble to Create a Clock", url: "https://www.rollingstone.com/music/music-news/taylor-swift-elevates-midnights-artwork-clock-1234594274/" }],
    },
    {
      slug: "midnights-mayhem-bingo-tracklist",
      title: "The tracklist came out of a bingo cage",
      secret: "No press release, no post — Midnights' 13 track titles were revealed one ping-pong ball at a time, in a TikTok series called \"Midnights Mayhem With Me\": Taylor cranked a bingo cage, drew a number, and answered a vintage telephone to say the title. Episodes dropped at midnight, of course.",
      deeperLink: "moment:vault-midnights-midnights-3am-edition-surprises-fans-with-7-more-songs",
      sources: [{ name: "'Midnights' tracklist: Song names of Taylor Swift's new album", url: "https://www.today.com/popculture/music/taylor-swift-midnights-tracklist-song-names-rcna50738" }, { name: "Taylor Swift begins to reveal tracklist for upcoming album 'Midnights' with TikTok series", url: "https://www.phillyvoice.com/taylor-swift-midnights-album-tracklist-release-tiktok-series-bingo/" }],
    },
    {
      slug: "midnights-lavender-haze-mad-men",
      title: "\"Lavender Haze\" came from Mad Men",
      secret: "She heard the phrase watching Mad Men and looked it up: '50s slang for being in love — \"if you were in the lavender haze, then that meant that you were in that all-encompassing love glow.\" The song is about fighting to stay inside that glow while the outside world speculates.",
      deeperLink: "song:lavender-haze",
      sources: [{ name: "Taylor Swift Shares Inspiration Behind Midnights Track 'Lavender Haze'", url: "https://www.rollingstone.com/music/music-news/taylor-swift-reveals-lavender-haze-midnights-inspiration-joe-alwyn-1234607000/" }, { name: "Lavender Haze", url: "https://en.wikipedia.org/wiki/Lavender_Haze" }],
    },
    {
      slug: "midnights-vmas-speech-announcement",
      title: "The album was announced mid-acceptance-speech",
      secret: "Midnights arrived as a mic drop: accepting Video of the Year for the All Too Well short film at the 2022 VMAs — her record third win in the category — she ended the speech by announcing a brand-new album for October 21. The cover and its \"Meet me at midnight\" caption hit Instagram at, naturally, midnight.",
      deeperLink: "moment:vault-midnights-midnights-breaks-spotify-in-a-single-day",
      sources: [{ name: "Taylor Swift Reveals 'Midnights' Album During 2022 VMAs Speech", url: "https://www.billboard.com/music/pop/taylor-swift-new-album-announcement-vmas-speech-1235132031/" }, { name: "Taylor Swift says a new album is coming, after winning the top award at the MTV VMAs", url: "https://www.npr.org/2022/08/28/1119845749/mtv-vmas-ready-to-host-and-honor-some-of-musics-biggest-acts" }],
    },
  ],
  "red": [
    {
      slug: "red-don-mclean-flowers",
      title: "She broke a 50-year record, then sent the loser flowers",
      secret: "When the 10-minute \"All Too Well\" dethroned \"American Pie\" as the longest No. 1 in Hot 100 history — a record Don McLean had held since 1972 — Taylor sent him flowers and a handwritten note. McLean posted the bouquet with a caption of his own: \"What a class act!\" Fifty years of chart history changed hands with a thank-you card.",
      deeperLink: "song:all-too-well-10-minute-version",
      sources: [{ name: "Don McLean Reacts to Taylor Swift For Breaking Half-Century 'American Pie' Record", url: "https://www.billboard.com/music/pop/don-mclean-reacts-taylor-swift-for-breaking-half-century-american-pie-record-1235001870/" }, { name: "Taylor Swift sends flowers, note to Don McLean after breaking his record", url: "https://www.today.com/popculture/taylor-swift-sends-flowers-note-don-mclean-after-breaking-his-t242099" }],
    },
    {
      slug: "red-all-too-well-maple-lattes",
      title: "All Too Well's liner-note code is a coffee order",
      secret: "Before the scarf became scripture, the original Red booklet hid a plainer clue: the coded message threaded through \"All Too Well\"'s printed lyrics — capital letters, per the era's tradition — spells MAPLE LATTES, matching a much-photographed fall 2010 coffee run. The codes usually hinted at a song's subject; this one practically drew a map.",
      deeperLink: "song:all-too-well",
      sources: [{ name: "Taylor Swift's 13 Best Liner Note Secret Messages", url: "https://www.billboard.com/music/music-news/taylor-swift-liner-note-secret-messages-6296379/" }, { name: "Hidden Messages in Taylor Swift's 'Red' Liner Notes Revealed", url: "https://tasteofcountry.com/taylor-swift-red-hidden-messages/" }],
    },
    {
      slug: "red-wanegbt-one-take-video",
      title: "The 'Never Ever' video never cuts — it's one single shot",
      secret: "The \"We Are Never Ever Getting Back Together\" video looks like a dozen sets because it is — but the camera never stops rolling. Director Declan Whitebloom staged the whole thing as one continuous take, Taylor swapping five outfits mid-frame while the rooms rebuilt themselves around her. One shot, five costumes, zero edits.",
      deeperLink: "song:we-are-never-ever-getting-back-together",
      sources: [{ name: "Taylor Swift's \"We Are Never Ever Getting Back Together\" Music Video: Filmed in One Take!", url: "https://www.eonline.com/news/342415/taylor-swift-s-we-are-never-ever-getting-back-together-music-video-filmed-in-one-take" }, { name: "Making of Taylor Swift's \"We Are Never Ever Getting Back Together\"", url: "https://www.fdtimes.com/2012/09/05/taylor-swifts-we-are-never-ever-getting-back-together/" }],
    },
    {
      slug: "red-ibytam-blake-lively-debut",
      title: "Blake Lively's directing career started on Red TV",
      secret: "\"I Bet You Think About Me\" isn't just a vault track — its video is Blake Lively's directorial debut. Taylor co-wrote the treatment with her best friend, handed her the chair, and cast Miles Teller as the groom with his real-life wife Keleigh as the bride — a wedding-crasher revenge fantasy staged as a family affair on both sides of the camera.",
      deeperLink: "song:i-bet-you-think-about-me",
      sources: [{ name: "Taylor Swift Releases \"I Bet You Think About Me\" Music Video Directed by Blake Lively", url: "https://www.hollywoodreporter.com/music/music-news/taylor-swift-blake-lively-music-video-red-taylors-version-1235047645/" }, { name: "Miles Teller stars in Taylor Swift's new music video directed by Blake Lively", url: "https://www.nbcnews.com/pop-culture/pop-culture-news/miles-teller-stars-taylor-swifts-new-music-video-directed-blake-lively-rcna5586" }],
    },
    {
      slug: "red-kennedy-wedding-flap",
      title: "The Conor summer had a wedding-crash controversy",
      secret: "August 2012's strangest news cycle: the mother of a Kennedy bride said Taylor and Conor were told \"please do not come\" to a family wedding — and came anyway. Taylor's rep insisted she was invited and thanked for being there; wedding guest Kathie Lee Gifford sided with the bride. The accounts never matched, and Taylor later called the whole thing a misunderstanding.",
      deeperLink: "moment:vault-red-the-conor-kennedy-summer-quietly-ends",
      sources: [{ name: "Kathie Lee on Taylor Swift wedding flap: 'It was the bride's day'", url: "https://www.today.com/popculture/kathie-lee-taylor-swift-wedding-flap-it-was-brides-day-flna960916" }, { name: "Kathie Lee Gifford: Yes, Taylor Swift Crashed Kennedy Wedding!", url: "https://www.eonline.com/news/340429/kathie-lee-gifford-calls-out-taylor-swift-insists-songbird-crashed-kennedy-nuptials" }],
    },
  ],
  "reputation": [
    {
      slug: "rep-karyn-the-cobra",
      title: "The snake had a name: Karyn",
      secret: "The 63-foot cobra that reared up over the Reputation Stadium Tour had a name — Karyn — and Taylor later admitted the bit kept her sane: \"I can't tell you how hard I had to keep from laughing every time my 63-foot inflatable cobra named Karyn appeared onstage in front of 60,000 screaming fans.\"",
      deeperLink: "egg:snake-reclamation",
      sources: [{ name: "Taylor Swift Alluded To Kim Kardashian's Snake Comments In Her New Interview", url: "https://www.bustle.com/p/taylor-swift-alluded-to-kim-kardashians-snake-comments-in-her-new-interview-without-calling-out-the-reality-star-16817249" }, { name: "Karyn", url: "https://taylorswift.fandom.com/wiki/Karyn" }],
    },
    {
      slug: "rep-liner-codes-go-dark",
      title: "The album where the hidden messages stopped",
      secret: "From the debut through 1989, every printed lyric sheet hid a coded message in stray letters. reputation broke the streak: no booklet codes at all, for the first time in her career. The scavenger hunt didn't die — it moved into the music videos, starting with the most egg-stuffed one she'd ever made.",
      deeperLink: "egg:1989-lowercase-liner-codes",
      sources: [{ name: "Taylor Swift's 13 Best Liner Note Secret Messages", url: "https://www.billboard.com/music/music-news/taylor-swift-liner-note-secret-messages-6296379/" }, { name: "Liner notes and easter eggs: How Taylor Swift turned fandom into a scavenger hunt", url: "https://www.today.com/popculture/music/taylor-swift-easter-eggs-hidden-messages-rcna51887" }],
    },
    {
      slug: "rep-lwymmd-graveyard-receipts",
      title: "The graveyard has receipts",
      secret: "The 'Look What You Made Me Do' video is wall-to-wall references — outlets ran full decoder guides the week it dropped. Start in the graveyard: the headstone beside the grave zombie-Taylor is digging reads Nils Sjöberg, the fake Swedish name she hid behind on a Calvin Harris co-write.",
      deeperLink: "egg:lwymmd-nils-sjoberg-gravestone",
      sources: [{ name: "All the References You Might Have Missed in Taylor Swift's 'Look What You Made Me Do' Video", url: "https://time.com/4918411/taylor-swift-look-what-you-made-me-do-music-video-references/" }, { name: "Taylor Swift's 'Look What You Made Me Do' Video Decoded: 13 Things You Missed", url: "https://www.rollingstone.com/music/music-news/taylor-swifts-look-what-you-made-me-do-video-decoded-13-things-you-missed-126268/" }],
    },
    {
      slug: "rep-magazines-two-poems",
      title: "She published poetry, and half the fandom missed it",
      secret: "The Target-exclusive reputation magazines carried two original Taylor poems — \"Why She Disappeared\" and \"If You're Anything Like Me\" — plus her paintings and handwritten lyrics. For an era with essentially no press interviews, the poems were the closest thing to an explanation she ever gave.",
      deeperLink: "moment:vault-1989-the-reputation-secret-sessions-500-fans-four-houses-zero-lea",
      sources: [{ name: "Taylor Swift Explains Her Disappearance in Heartbreaking Poem", url: "https://www.eonline.com/news/893003/taylor-swift-explains-disappearance-in-poem-in-target-magazine-reputation-bundle" }, { name: "Taylor Swift's 'Reputation' Poem Meanings Make Having Vulnerabilities Seem Like A Blessing", url: "https://www.bustle.com/p/taylor-swifts-reputation-poem-meanings-make-having-vulnerabilities-seem-like-a-blessing-3344701" }],
    },
    {
      slug: "rep-ups-trucks",
      title: "The album cover drove a delivery route",
      secret: "reputation had an 'official delivery partner': UPS. Her face rode co-branded brown trucks through Nashville, Atlanta and New York starting August 26, 2017 — the first time UPS had ever wrapped its trucks for a promotion — and preordering from UPS.com entered fans to win tickets and airfare.",
      deeperLink: "song:look-what-you-made-me-do",
      sources: [{ name: "Taylor Swift's Face Is Going to Be on UPS Delivery Trucks Across the Country", url: "https://www.billboard.com/music/pop/taylor-swift-ups-trucks-reputation-face-branded-partnership-7942081/" }, { name: "Taylor Swift, UPS Team For 'Reputation' Shipping Strategy", url: "https://www.grammy.com/news/taylor-swift-ups-team-reputation-shipping-strategy" }],
    },
  ],
  "speak-now": [
    {
      slug: "speak-now-hometown-covers",
      title: "Every tour stop got its own hometown cover",
      secret: "On the Speak Now World Tour she did homework on every city: a surprise acoustic cover of a local hero, different nearly every night. Grand Rapids got her rapping Eminem's \"Lose Yourself\" with an Uncle Kracker chaser; Newark got Bon Jovi and Springsteen; Toronto got Alanis and Bieber. Fans traded the recordings like bootlegs — no two cities heard the same show.",
      deeperLink: "moment:vault-speak-now-the-speak-now-world-tour-opens-in-singapore",
      sources: [{ name: "Taylor Swift Raps Eminem's 'Lose Yourself' at Concert", url: "https://www.etonline.com/music/113134_Taylor_Swift_Raps_Eminem_s_Lose_Yourself_at_Concert" }, { name: "Video: Taylor Swift Covers Eminem's \"Lose Yourself\"", url: "https://www.complex.com/music/a/complex/video-taylor-swift-covers-eminems-lose-yourself" }, { name: "Taylor Swift Covered Songs and Artists — Speak Now World Tour", url: "https://www.setlist.fm/stats/covers/taylor-swift-3bd6bc5c.html?tour=bd6adc6" }],
    },
    {
      slug: "speak-now-itwam-omission",
      title: "The re-record dropped one of its own songs",
      secret: "Speak Now (Taylor's Version) quietly runs one song short: \"If This Was a Movie,\" the deluxe cut co-written with Boys Like Girls' Martin Johnson, is the only original that didn't return. Dropping the lone co-write made the re-record something the 2010 album nearly was: entirely self-written. Its Taylor's Version had already slipped out months earlier — filed under Fearless.",
      deeperLink: "song:if-this-was-a-movie",
      sources: [{ name: "The Taylor Swift Song That Won't Be On 'Speak Now (Taylor's Version)'", url: "https://www.capitalfm.com/news/taylor-swift-speak-now-if-this-was-a-movie/" }, { name: "Is Taylor Swift's 'If This Was A Movie' From 'Speak Now?'", url: "https://uproxx.com/pop/is-taylor-swift-if-this-was-a-movie-from-speak-now/" }, { name: "If This Was a Movie", url: "https://en.wikipedia.org/wiki/If_This_Was_a_Movie" }],
    },
    {
      slug: "speak-now-last-kiss-code",
      title: "Last Kiss's liner code points back two eras",
      secret: "The Speak Now booklet's hidden message under \"Last Kiss\" spells FOREVER AND ALWAYS — the title of a Fearless breakup song. Fans read the cross-reference the obvious way: same story, two albums apart, the sequel filed under the original's name. She never explained it; the liner notes were allowed to do the talking.",
      deeperLink: "song:last-kiss",
      sources: [{ name: "Taylor Swift's 13 Best Liner Note Secret Messages", url: "https://www.billboard.com/music/music-news/taylor-swift-liner-note-secret-messages-6296379/" }, { name: "Who is Taylor Swift singing about on 'Speak Now'? A complete guide to the album", url: "https://theweek.com/feature/briefing/1024743/who-is-taylor-swift-singing-about-on-speak-now-a-complete-guide-to-the" }],
    },
    {
      slug: "speak-now-i-can-see-you-reunion",
      title: "The Mean video kids came back 12 years later",
      secret: "The \"I Can See You\" heist crew is a reunion: Joey King and Presley Cash — the bullied kids from 2011's \"Mean\" video, ages 9 and 13 back then — return grown up to break Speak Now-era Taylor out of a museum vault, alongside Taylor Lautner, the era's own leading man. She premiered it onstage in Kansas City and named the theme herself: the fans helping her reclaim her music.",
      deeperLink: "song:i-can-see-you",
      sources: [{ name: "Taylor Swift 'I Can See You' Video Has Taylor Lautner as Surprise Star", url: "https://variety.com/2023/music/news/taylor-swift-lautner-i-can-see-you-music-video-joey-king-presley-cash-1235664478/" }, { name: "Taylor Swift Premieres 'I Can See You' Video With Taylor Lautner at Eras Tour Show in Kansas City", url: "https://www.billboard.com/music/music-news/taylor-swift-i-can-see-you-video-taylor-lautner-joey-king-presley-cash-1235368510/" }],
    },
    {
      slug: "speak-now-long-live-portuguese",
      title: "Long Live has a second official language",
      secret: "There's a version of \"Long Live\" most U.S. fans have never heard: a 2012 duet with Brazilian country star Paula Fernandes, with new verses written and sung in Portuguese. Cut for the Brazilian edition of the Speak Now live album, it went four-times diamond in Brazil and soundtracked the primetime soap Avenida Brasil — a parallel life for the album's farewell toast.",
      deeperLink: "song:long-live",
      sources: [{ name: "Long Live (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Long_Live_(Taylor_Swift_song)" }, { name: "Paula Fernandes revela como foi encontro com Taylor Swift em 2012", url: "https://rollingstone.com.br/musica/paula-fernandes-revela-como-foi-encontro-com-taylor-swift-em-2012/" }],
    },
  ],
  "ttpd": [
    {
      slug: "ttpd-track-five-so-long-london",
      title: "Track five strikes again",
      secret: "The track-5 tradition — the most gutting song on the album in the fifth slot, confirmed by Taylor herself in 2019 — continues here with \"So Long, London.\" Fans clocked the sequencing before release day: the London farewell sitting exactly where \"All Too Well\" and \"Dear John\" once sat said everything.",
      deeperLink: "song:so-long-london",
      sources: [{ name: "'So Long, London' is a Classic Taylor Swift Track 5 Song", url: "https://time.com/6969042/taylor-swift-track-five-songs-tortured-poets-department/" }, { name: "Here Is Every Taylor Swift Track 5, Ranked (Critic's Picks)", url: "https://www.billboard.com/lists/taylor-swift-track-fives-ranked/" }],
    },
    {
      slug: "ttpd-thank-you-aimee-capitals",
      title: "The capital letters in \"thanK you aIMee\" spell a name",
      secret: "The stylized title \"thanK you aIMee\" capitalizes exactly three letters: K-I-M. Then, in August 2024, an official live release quietly restyled it \"thank You aimEe\" — now capitalizing Y-E. One song, two addressees, spelled out in the typography itself.",
      deeperLink: "song:thank-you-aimee",
      sources: [{ name: "Taylor Swift Shifts From Kim to Ye With New Live Release of 'thank You aimEe'", url: "https://www.billboard.com/music/pop/taylor-swift-thank-you-aimee-kanye-west-title-live-1235754448/" }, { name: "Are Taylor Swift's 'thanK you aIMee' and 'Cassandra' About Kim Kardashian?", url: "https://www.today.com/popculture/music/taylor-swift-kim-kardashian-thank-you-aimee-lyrics-rcna148523" }],
    },
    {
      slug: "ttpd-2am-secret-double-album",
      title: "The double album was a secret until 2 a.m.",
      secret: "Everyone went to bed thinking TTPD was 16 songs. At 2 a.m. a second post landed: \"It's a 2am surprise: The Tortured Poets Department is a secret DOUBLE album.\" The Anthology's 15 extra tracks pushed the night's total to 31 songs — and past the two-hour mark.",
      deeperLink: "moment:vault-ttpd-a-2am-surprise-ttpd-was-a-secret-double-album-all-along",
      sources: [{ name: "Taylor Swift Drops '2am Surprise': 'The Tortured Poets Department' Is a Secret Double Album", url: "https://www.billboard.com/music/pop/taylor-swift-2am-surprise-secret-double-album-the-tortured-poets-department-1235660643/" }, { name: "Taylor Swift Unveils Double Album 'The Tortured Poets Department: The Anthology'", url: "https://www.rollingstone.com/music/music-news/taylor-swift-the-tortured-poets-department-the-anthology-announcement-1235007251/" }],
    },
    {
      slug: "ttpd-thirty-one-thirteen-backwards",
      title: "Why 31 songs? Read it backwards",
      secret: "Fans noticed the math immediately: the Anthology's 31 total songs is 13 reversed — the lucky number she's carried since birth (\"I was born on the 13th. I turned 13 on Friday the 13th. My first album went gold in 13 weeks\"). A fan reading, not a confirmed one — but for a number she's never once deployed by accident.",
      deeperLink: "moment:vault-ttpd-a-2am-surprise-ttpd-was-a-secret-double-album-all-along",
      sources: [{ name: "Taylor Swift Album Detail Sends Internet Into Meltdown", url: "https://www.newsweek.com/taylor-swift-album-detail-internet-meltdown-1892085" }, { name: "What is 'The Tortured Poets Department The Anthology'? Every surprise song you need to know", url: "https://www.capitalfm.com/news/music/the-tortured-poets-department-anthology-extra-songs/" }],
    },
    {
      slug: "ttpd-clara-bow-real-it-girl",
      title: "Clara Bow was real — and the song ends on \"Taylor Swift\"",
      secret: "The closer of the standard album is named for a real person: Clara Bow, the 1920s silent-film star whose movie \"It\" coined \"It Girl,\" who got 35,000 fan letters a month and walked away from Hollywood at her peak. The song's last verse hands the spotlight down the line — to a new girl who looks \"like Taylor Swift.\"",
      deeperLink: "song:clara-bow",
      sources: [{ name: "Who Is Clara Bow? The Inspiration Behind Taylor Swift's Song", url: "https://time.com/6969048/clara-bow-taylor-swift-song/" }, { name: "Who is Clara Bow from Taylor Swift's new album?", url: "https://www.pbs.org/newshour/arts/who-is-clara-bow-from-taylor-swifts-new-album" }],
    },
  ],
};
