export type Network = 'awin' | 'amazon' | 'catchall' | 'none';

export type NetworkResolution =
  | { network: 'awin'; awinmid: string }
  | { network: 'amazon' }
  | { network: 'catchall' }
  | { network: 'none' };

export type AwinAdvertisers = Readonly<Record<string, string>>;

function hostnameFor(retailer: string): string {
  return retailer.trim().toLowerCase().replace(/^www\./, '');
}

/**
 * Resolves a retailer against the map generated by E0. The production map is
 * deliberately empty until E0 has written a verified joined-programmes map;
 * no hostname is ever assumed to be an Awin advertiser.
 */
export function createNetworkResolver(advertisers: AwinAdvertisers) {
  const awinByHostname = new Map(
    Object.entries(advertisers).map(([hostname, awinmid]) => [hostnameFor(hostname), awinmid]),
  );

  return (retailer: string): NetworkResolution => {
    const hostname = hostnameFor(retailer);
    const awinmid = awinByHostname.get(hostname);
    if (awinmid) return { network: 'awin', awinmid };
    if (hostname === 'amazon.com') return { network: 'amazon' };
    return { network: 'none' };
  };
}

/**
 * E0 replaces this empty value with its checked-in generated hostname map.
 * Until then the resolver fails closed, leaving all non-Amazon retailers
 * direct instead of fabricating affiliate coverage.
 */
const GENERATED_AWIN_ADVERTISERS: AwinAdvertisers = {};

export const networkFor = createNetworkResolver(GENERATED_AWIN_ADVERTISERS);