// GENERATED FILE — do not hand-edit.
// Produced by scripts/sync-song-moods.mjs from supabase/seed/tracks/**
// (the song list) merged with supabase/seed/song-moods/** (the mood scores).
// Re-run that script after seed changes; don't edit this file directly.
//
// 244 songs, 162 scored.

import type { SongMood } from './types';

export const SONG_MOODS: SongMood[] = [
  {
    slug: "tim-mcgraw",
    title: "Tim McGraw",
    eraId: "debut",
    youtubeId: "GkD20ajVxnY",
    moods: { heartbreak: 0.4, anger: 0.02, nostalgia: 0.9, joy: 0.35, calm: 0.6, defiance: 0.05, longing: 0.7, catharsis: 0.4 },
    energy: 0.35,
    valence: 0.5,
    useCase: ["missing a summer that ended", "a first-love goodbye", "back roads at dusk"],
    oneLiner: "A debut goodbye that just wants to be remembered when the right song comes on.",
  },
  {
    slug: "picture-to-burn",
    title: "Picture to Burn",
    eraId: "debut",
    youtubeId: "yCMqcFAigRg",
    moods: { heartbreak: 0.3, anger: 0.85, nostalgia: 0.1, joy: 0.4, calm: 0.05, defiance: 0.8, longing: 0.05, catharsis: 0.6 },
    energy: 0.8,
    valence: 0.45,
    useCase: ["a petty breakup singalong", "burning an ex from memory", "feeling done and loving it"],
    oneLiner: "A banjo kiss-off that turns a bad boyfriend into a bonfire and laughs about it.",
  },
  {
    slug: "teardrops-on-my-guitar",
    title: "Teardrops on My Guitar",
    eraId: "debut",
    youtubeId: "xKCek6_dB0M",
    moods: { heartbreak: 0.75, anger: 0.05, nostalgia: 0.4, joy: 0.1, calm: 0.4, defiance: 0.05, longing: 0.85, catharsis: 0.4 },
    energy: 0.4,
    valence: 0.2,
    useCase: ["loving someone who wants someone else", "smiling through a crush", "quiet heartache"],
    oneLiner: "Being the shoulder a boy cries on about another girl, and hiding what it costs.",
  },
  {
    slug: "a-place-in-this-world",
    title: "A Place in This World",
    eraId: "debut",
    youtubeId: "_FNQ5qLuLjA",
    moods: { heartbreak: 0.05, anger: 0.02, nostalgia: 0.2, joy: 0.4, calm: 0.35, defiance: 0.4, longing: 0.6, catharsis: 0.4 },
    energy: 0.5,
    valence: 0.55,
    useCase: ["starting over somewhere new", "not knowing your path yet", "believing there is a place for you"],
    oneLiner: "A thirteen-year-old narrating her own uncertainty, sure only that a path exists.",
  },
  {
    slug: "cold-as-you",
    title: "Cold as You",
    eraId: "debut",
    youtubeId: "aGvIwzgJ9hU",
    moods: { heartbreak: 0.7, anger: 0.4, nostalgia: 0.15, joy: 0.02, calm: 0.35, defiance: 0.3, longing: 0.4, catharsis: 0.5 },
    energy: 0.35,
    valence: 0.15,
    useCase: ["done with someone who gives nothing back", "quiet anger", "a surgical breakup ballad"],
    oneLiner: "A slow, precise takedown of a boy who never gave anything back.",
  },
  {
    slug: "the-outside",
    title: "The Outside",
    eraId: "debut",
    youtubeId: "IAeicVet6SU",
    moods: { heartbreak: 0.3, anger: 0.05, nostalgia: 0.35, joy: 0.05, calm: 0.35, defiance: 0.35, longing: 0.6, catharsis: 0.55 },
    energy: 0.4,
    valence: 0.25,
    useCase: ["feeling shut out of the group", "writing through loneliness", "when nobody saved you a seat"],
    oneLiner: "A kid on the outside of every friend group turning exclusion into a song.",
  },
  {
    slug: "tied-together-with-a-smile",
    title: "Tied Together with a Smile",
    eraId: "debut",
    youtubeId: "aCVHGH5sO0c",
    moods: { heartbreak: 0.4, anger: 0.02, nostalgia: 0.2, joy: 0.05, calm: 0.45, defiance: 0.05, longing: 0.4, catharsis: 0.6 },
    energy: 0.35,
    valence: 0.25,
    useCase: ["worrying about a friend", "loving someone falling apart", "the girl who seems fine but isnt"],
    oneLiner: "A tender letter to a beautiful friend who is quietly coming undone.",
  },
  {
    slug: "stay-beautiful",
    title: "Stay Beautiful",
    eraId: "debut",
    youtubeId: "TQ9haUkCV-M",
    moods: { heartbreak: 0.05, anger: 0.02, nostalgia: 0.25, joy: 0.6, calm: 0.55, defiance: 0.05, longing: 0.6, catharsis: 0.3 },
    energy: 0.45,
    valence: 0.7,
    useCase: ["a crush you admire from afar", "wishing someone well", "soft hopeful daydreams"],
    oneLiner: "Admiring a boy from a distance and wishing him well, ending or not.",
  },
  {
    slug: "shouldve-said-no",
    title: "Should've Said No",
    eraId: "debut",
    youtubeId: "v9bxXO9fj98",
    moods: { heartbreak: 0.55, anger: 0.75, nostalgia: 0.1, joy: 0.05, calm: 0.1, defiance: 0.75, longing: 0.1, catharsis: 0.8 },
    energy: 0.75,
    valence: 0.3,
    useCase: ["when someone cheated and chose it", "a stadium-sized kiss-off", "blame where it belongs"],
    oneLiner: "A betrayal answered with a stadium chorus that puts the blame exactly where it belongs.",
  },
  {
    slug: "marys-song-oh-my-my-my",
    title: "Mary's Song (Oh My My My)",
    eraId: "debut",
    youtubeId: "9TCRiGA1A2U",
    moods: { heartbreak: 0.02, anger: 0, nostalgia: 0.85, joy: 0.7, calm: 0.6, defiance: 0.05, longing: 0.3, catharsis: 0.4 },
    energy: 0.45,
    valence: 0.85,
    useCase: ["believing in forever love", "a wedding slow dance", "growing old with someone"],
    oneLiner: "A whole lifetime of love, from backyard dares to a porch swing at eighty-seven.",
  },
  {
    slug: "our-song",
    title: "Our Song",
    eraId: "debut",
    youtubeId: "Jb2stN7kH28",
    moods: { heartbreak: 0, anger: 0, nostalgia: 0.5, joy: 0.85, calm: 0.4, defiance: 0.05, longing: 0.2, catharsis: 0.45 },
    energy: 0.7,
    valence: 0.9,
    useCase: ["giddy new-relationship joy", "young love with no soundtrack", "a windows-down singalong"],
    oneLiner: "A couple with no song deciding the everyday details already are one.",
  },
  {
    slug: "im-only-me-when-im-with-you",
    title: "I'm Only Me When I'm with You",
    eraId: "debut",
    youtubeId: "AlTfYj7q5gQ",
    moods: { heartbreak: 0, anger: 0, nostalgia: 0.45, joy: 0.8, calm: 0.4, defiance: 0.15, longing: 0.15, catharsis: 0.45 },
    energy: 0.7,
    valence: 0.88,
    useCase: ["the people you never perform for", "best-friend belonging", "feeling fully yourself"],
    oneLiner: "A stomping tribute to the people around whom you never have to perform.",
  },
  {
    slug: "invisible",
    title: "Invisible",
    eraId: "debut",
    youtubeId: "IiWI7qG8Jpc",
    moods: { heartbreak: 0.55, anger: 0.05, nostalgia: 0.25, joy: 0.05, calm: 0.45, defiance: 0.05, longing: 0.85, catharsis: 0.35 },
    energy: 0.35,
    valence: 0.25,
    useCase: ["being overlooked by someone", "wallflower longing", "waiting to be noticed"],
    oneLiner: "Watching a boy chase someone else while you wait, unseen and seeing everything.",
  },
  {
    slug: "a-perfectly-good-heart",
    title: "A Perfectly Good Heart",
    eraId: "debut",
    youtubeId: "mbs84V9S5Lc",
    moods: { heartbreak: 0.85, anger: 0.15, nostalgia: 0.2, joy: 0.02, calm: 0.3, defiance: 0.1, longing: 0.5, catharsis: 0.55 },
    energy: 0.45,
    valence: 0.15,
    useCase: ["first heartbreak bewilderment", "asking why someone hurt you", "no revenge, just confusion"],
    oneLiner: "First heartbreak as pure bewilderment: why break a heart that was working fine?",
  },
  {
    slug: "fearless",
    title: "Fearless",
    eraId: "fearless",
    youtubeId: "7lLigiVgJsE",
    moods: { heartbreak: 0, anger: 0, nostalgia: 0.3, joy: 0.85, calm: 0.35, defiance: 0.4, longing: 0.5, catharsis: 0.55 },
    energy: 0.65,
    valence: 0.9,
    useCase: ["taking a leap on someone new", "dancing in the rain anyway", "optimistic butterflies"],
    oneLiner: "Fearless not as being unafraid but driving into the storm anyway.",
  },
  {
    slug: "fifteen",
    title: "Fifteen",
    eraId: "fearless",
    youtubeId: "rLCol1C3ouc",
    moods: { heartbreak: 0.4, anger: 0.05, nostalgia: 0.85, joy: 0.35, calm: 0.5, defiance: 0.15, longing: 0.5, catharsis: 0.65 },
    energy: 0.45,
    valence: 0.5,
    useCase: ["looking back on being young", "advice to a younger self", "freshman-year nostalgia"],
    oneLiner: "Freshman year in hindsight, when who you become matters more than the boy.",
  },
  {
    slug: "love-story",
    title: "Love Story",
    eraId: "fearless",
    youtubeId: "aXzVF3XeS8M",
    moods: { heartbreak: 0.1, anger: 0.02, nostalgia: 0.4, joy: 0.85, calm: 0.3, defiance: 0.6, longing: 0.7, catharsis: 0.7 },
    energy: 0.7,
    valence: 0.9,
    useCase: ["a giddy fairy-tale romance", "wanting a happy ending", "forbidden-love butterflies"],
    oneLiner: "Romeo and Juliet with Shakespeare overruled and the happy ending written in.",
  },
  {
    slug: "hey-stephen",
    title: "Hey Stephen",
    eraId: "fearless",
    youtubeId: "tMhiHrL7rPE",
    moods: { heartbreak: 0, anger: 0, nostalgia: 0.25, joy: 0.8, calm: 0.4, defiance: 0.1, longing: 0.55, catharsis: 0.35 },
    energy: 0.55,
    valence: 0.88,
    useCase: ["a flirty crush", "making your case to someone", "playful infatuation"],
    oneLiner: "A serenade that lists every other girl, then makes its own case with a wink.",
  },
  {
    slug: "white-horse",
    title: "White Horse",
    eraId: "fearless",
    youtubeId: "9-rKvhsjwKU",
    moods: { heartbreak: 0.8, anger: 0.2, nostalgia: 0.35, joy: 0.02, calm: 0.4, defiance: 0.5, longing: 0.4, catharsis: 0.7 },
    energy: 0.35,
    valence: 0.2,
    useCase: ["realizing it was never a fairy tale", "leaving a boy who wont change", "rescuing yourself"],
    oneLiner: "The moment after the apology when you realize there was never going to be a rescue.",
  },
  {
    slug: "you-belong-with-me",
    title: "You Belong with Me",
    eraId: "fearless",
    youtubeId: "vwp8Ur6tO-8",
    moods: { heartbreak: 0.35, anger: 0.05, nostalgia: 0.3, joy: 0.55, calm: 0.3, defiance: 0.35, longing: 0.85, catharsis: 0.5 },
    energy: 0.65,
    valence: 0.6,
    useCase: ["pining for someone taken", "underdog crush", "wishing they saw you"],
    oneLiner: "The girl next door making her closing argument to a boy who never looks over.",
  },
  {
    slug: "breathe",
    title: "Breathe",
    eraId: "fearless",
    youtubeId: "qsUK-BG5OQQ",
    moods: { heartbreak: 0.65, anger: 0.02, nostalgia: 0.4, joy: 0.05, calm: 0.55, defiance: 0.02, longing: 0.55, catharsis: 0.6 },
    energy: 0.35,
    valence: 0.25,
    useCase: ["losing a friend with no villain", "a goodbye nobody wanted", "the guilt of leaving"],
    oneLiner: "A breakup with no one to blame: losing a friend and grieving the guilt of it.",
  },
  {
    slug: "tell-me-why",
    title: "Tell Me Why",
    eraId: "fearless",
    youtubeId: "cwFbq-70EwE",
    moods: { heartbreak: 0.4, anger: 0.6, nostalgia: 0.1, joy: 0.1, calm: 0.2, defiance: 0.6, longing: 0.3, catharsis: 0.55 },
    energy: 0.6,
    valence: 0.35,
    useCase: ["done with someone hot and cold", "mixed-signal frustration", "demanding better"],
    oneLiner: "A vented rant set to a stomp, done guessing which version of him shows up.",
  },
  {
    slug: "youre-not-sorry",
    title: "You're Not Sorry",
    eraId: "fearless",
    youtubeId: "DNaSlUYIXBg",
    moods: { heartbreak: 0.7, anger: 0.45, nostalgia: 0.15, joy: 0.02, calm: 0.3, defiance: 0.6, longing: 0.3, catharsis: 0.7 },
    energy: 0.45,
    valence: 0.2,
    useCase: ["refusing a fake apology", "finally hanging up", "done being lied to"],
    oneLiner: "The sound of someone finally hanging up on an apology that was never real.",
  },
  {
    slug: "the-way-i-loved-you",
    title: "The Way I Loved You",
    eraId: "fearless",
    youtubeId: "DlexmDDSDZ0",
    moods: { heartbreak: 0.5, anger: 0.15, nostalgia: 0.75, joy: 0.2, calm: 0.25, defiance: 0.35, longing: 0.85, catharsis: 0.55 },
    energy: 0.55,
    valence: 0.35,
    useCase: ["missing a chaotic ex", "safe love that feels like nothing", "craving intensity"],
    oneLiner: "A perfect-on-paper boyfriend losing to the memory of a screaming-in-the-rain love.",
  },
  {
    slug: "forever-and-always",
    title: "Forever & Always",
    eraId: "fearless",
    youtubeId: "T-41vMWQTUA",
    moods: { heartbreak: 0.75, anger: 0.6, nostalgia: 0.25, joy: 0.05, calm: 0.1, defiance: 0.4, longing: 0.5, catharsis: 0.65 },
    energy: 0.6,
    valence: 0.2,
    useCase: ["a promise revoked out of nowhere", "breakup whiplash", "wanting an explanation"],
    oneLiner: "A forever promise revoked in real time, and the demand to know where he went.",
  },
  {
    slug: "the-best-day",
    title: "The Best Day",
    eraId: "fearless",
    youtubeId: "KZeI9I875Ig",
    moods: { heartbreak: 0.05, anger: 0, nostalgia: 0.95, joy: 0.7, calm: 0.7, defiance: 0.05, longing: 0.35, catharsis: 0.6 },
    energy: 0.35,
    valence: 0.85,
    useCase: ["missing your mom", "childhood-memory comfort", "gratitude for family"],
    oneLiner: "A secret thank-you to the mother who drove her away from every mean day.",
  },
  {
    slug: "change",
    title: "Change",
    eraId: "fearless",
    youtubeId: "jwWR1cQTKyw",
    moods: { heartbreak: 0, anger: 0.15, nostalgia: 0.15, joy: 0.6, calm: 0.2, defiance: 0.85, longing: 0.35, catharsis: 0.8 },
    energy: 0.8,
    valence: 0.75,
    useCase: ["believing the underdog wins", "a perseverance anthem", "walls coming down"],
    oneLiner: "A fight song for the scrappy underdog who believes the walls will come down.",
  },
  {
    slug: "jump-then-fall",
    title: "Jump Then Fall",
    eraId: "fearless",
    youtubeId: "vUHDR6Rg3Y4",
    moods: { heartbreak: 0, anger: 0, nostalgia: 0.1, joy: 0.9, calm: 0.35, defiance: 0.1, longing: 0.45, catharsis: 0.4 },
    energy: 0.6,
    valence: 0.92,
    useCase: ["falling fast and happily", "all butterflies, no warnings", "new-crush giddiness"],
    oneLiner: "The sunniest kind of falling: all butterflies, no warnings.",
  },
  {
    slug: "untouchable",
    title: "Untouchable",
    eraId: "fearless",
    youtubeId: "8bNlGwnEUAs",
    moods: { heartbreak: 0.2, anger: 0, nostalgia: 0.3, joy: 0.3, calm: 0.6, defiance: 0.05, longing: 0.9, catharsis: 0.45 },
    energy: 0.4,
    valence: 0.5,
    useCase: ["yearning for someone out of reach", "a starlit daydream", "distance as romance"],
    oneLiner: "Longing for someone just out of reach, rendered as a starlit trance.",
  },
  {
    slug: "come-in-with-the-rain",
    title: "Come In with the Rain",
    eraId: "fearless",
    youtubeId: "ePjcjLRHPOo",
    moods: { heartbreak: 0.5, anger: 0.02, nostalgia: 0.35, joy: 0.1, calm: 0.6, defiance: 0.1, longing: 0.7, catharsis: 0.4 },
    energy: 0.35,
    valence: 0.3,
    useCase: ["done chasing but still hoping", "leaving a door unlocked", "quiet letting go"],
    oneLiner: "Done chasing someone but not done hoping, with a door left quietly unlocked.",
  },
  {
    slug: "superstar",
    title: "Superstar",
    eraId: "fearless",
    youtubeId: "IsCik8wznlU",
    moods: { heartbreak: 0.1, anger: 0, nostalgia: 0.3, joy: 0.45, calm: 0.45, defiance: 0.05, longing: 0.8, catharsis: 0.35 },
    energy: 0.45,
    valence: 0.55,
    useCase: ["a hopeless celebrity crush", "loving someone from the crowd", "front-row daydreams"],
    oneLiner: "A front-row daydream about loving someone famous who will never look down.",
  },
  {
    slug: "the-other-side-of-the-door",
    title: "The Other Side of the Door",
    eraId: "fearless",
    youtubeId: "425n1NoRtgA",
    moods: { heartbreak: 0.55, anger: 0.4, nostalgia: 0.15, joy: 0.1, calm: 0.15, defiance: 0.5, longing: 0.65, catharsis: 0.7 },
    energy: 0.65,
    valence: 0.3,
    useCase: ["saying leave when you mean stay", "wanting the grand gesture", "a post-fight standoff"],
    oneLiner: "Saying go when you mean stay, and waiting for the grand gesture instead of silence.",
  },
  {
    slug: "today-was-a-fairytale",
    title: "Today Was a Fairytale",
    eraId: "fearless",
    youtubeId: "xSWVPqnKcXQ",
    moods: { heartbreak: 0, anger: 0, nostalgia: 0.35, joy: 0.9, calm: 0.35, defiance: 0.05, longing: 0.4, catharsis: 0.4 },
    energy: 0.6,
    valence: 0.92,
    useCase: ["a perfect ordinary date", "giddy new romance", "magic on a plain afternoon"],
    oneLiner: "A perfect ordinary date replayed in storybook terms.",
  },
  {
    slug: "you-all-over-me",
    title: "You All Over Me",
    eraId: "fearless",
    youtubeId: "1uKi3ZD75RE",
    moods: { heartbreak: 0.7, anger: 0.05, nostalgia: 0.7, joy: 0.05, calm: 0.45, defiance: 0.1, longing: 0.75, catharsis: 0.55 },
    energy: 0.4,
    valence: 0.25,
    useCase: ["a breakup that leaves residue", "moving on but not clean", "wiser and wearier"],
    oneLiner: "Clean but not new: a breakup leaves a residue no amount of moving on scrubs off.",
  },
  {
    slug: "mr-perfectly-fine",
    title: "Mr. Perfectly Fine",
    eraId: "fearless",
    youtubeId: "rFjJs6ZjPe8",
    moods: { heartbreak: 0.45, anger: 0.55, nostalgia: 0.2, joy: 0.4, calm: 0.15, defiance: 0.75, longing: 0.25, catharsis: 0.7 },
    energy: 0.75,
    valence: 0.45,
    useCase: ["an ex who moved on too fast", "wit as armor", "a receipts singalong"],
    oneLiner: "A catalog of a casually cruel ex, skewered with a wink and the receipts.",
  },
  {
    slug: "we-were-happy",
    title: "We Were Happy",
    eraId: "fearless",
    youtubeId: "seU5y5EgIwk",
    moods: { heartbreak: 0.7, anger: 0.02, nostalgia: 0.85, joy: 0.15, calm: 0.5, defiance: 0.05, longing: 0.7, catharsis: 0.55 },
    energy: 0.35,
    valence: 0.25,
    useCase: ["grieving a love that worked", "missing the golden middle", "the happiness that hurts"],
    oneLiner: "Cataloging the golden middle of a love, because the happiness is what hurts to recall.",
  },
  {
    slug: "thats-when",
    title: "That's When",
    eraId: "fearless",
    youtubeId: "aOa6D6ku3dM",
    moods: { heartbreak: 0.2, anger: 0.05, nostalgia: 0.35, joy: 0.55, calm: 0.5, defiance: 0.05, longing: 0.6, catharsis: 0.5 },
    energy: 0.45,
    valence: 0.7,
    useCase: ["finding a way back", "forgiving and returning", "negotiating a reunion"],
    oneLiner: "An apology and its answer, traded verse by verse toward a way back.",
  },
  {
    slug: "dont-you",
    title: "Don't You",
    eraId: "fearless",
    youtubeId: "dHdAN4FXzmc",
    moods: { heartbreak: 0.55, anger: 0.1, nostalgia: 0.5, joy: 0.15, calm: 0.55, defiance: 0.2, longing: 0.75, catharsis: 0.45 },
    energy: 0.4,
    valence: 0.3,
    useCase: ["running into an ex", "unfair leftover chemistry", "guarding yourself"],
    oneLiner: "Running into the ex who acts like nothing happened, and hating how well it works.",
  },
  {
    slug: "bye-bye-baby",
    title: "Bye Bye Baby",
    eraId: "fearless",
    youtubeId: "yuFuwXd-B9E",
    moods: { heartbreak: 0.65, anger: 0.05, nostalgia: 0.55, joy: 0.05, calm: 0.55, defiance: 0.05, longing: 0.6, catharsis: 0.65 },
    energy: 0.35,
    valence: 0.25,
    useCase: ["a goodbye with no fight left", "accepting its over", "watching a future drive away"],
    oneLiner: "A goodbye sadder than it is angry, letting a whole planned future drive away.",
  },
  {
    slug: "mine",
    title: "Mine",
    eraId: "speak-now",
    youtubeId: "oxNLRqMJMZk",
    moods: { heartbreak: 0.15, anger: 0.05, nostalgia: 0.3, joy: 0.7, calm: 0.35, defiance: 0.35, longing: 0.6, catharsis: 0.6 },
    energy: 0.65,
    valence: 0.8,
    useCase: ["scared to let love in", "hoping against your own pattern", "building a life with someone"],
    oneLiner: "A careless man's careful daughter imagining, verse by verse, what staying could look like.",
  },
  {
    slug: "sparks-fly",
    title: "Sparks Fly",
    eraId: "speak-now",
    youtubeId: "UlFrV5GJA_4",
    moods: { heartbreak: 0.05, anger: 0, nostalgia: 0.25, joy: 0.8, calm: 0.2, defiance: 0.35, longing: 0.65, catharsis: 0.5 },
    energy: 0.75,
    valence: 0.85,
    useCase: ["a magnetic bad idea", "electric first attraction", "wanting the rain-soaked kiss"],
    oneLiner: "Attraction as weather: a green-eyed bad idea and the kiss she wants anyway.",
  },
  {
    slug: "back-to-december",
    title: "Back to December",
    eraId: "speak-now",
    youtubeId: "qc2Z-OX9wnc",
    moods: { heartbreak: 0.7, anger: 0.05, nostalgia: 0.7, joy: 0.05, calm: 0.45, defiance: 0.05, longing: 0.75, catharsis: 0.7 },
    energy: 0.4,
    valence: 0.25,
    useCase: ["owning that you hurt someone", "an apology you owe", "wishing you could go back"],
    oneLiner: "Her first apology song: owning the December she gave back someone who deserved better.",
  },
  {
    slug: "speak-now",
    title: "Speak Now",
    eraId: "speak-now",
    youtubeId: "JlZnvyBqceY",
    moods: { heartbreak: 0.05, anger: 0.1, nostalgia: 0.15, joy: 0.8, calm: 0.2, defiance: 0.6, longing: 0.5, catharsis: 0.6 },
    energy: 0.65,
    valence: 0.85,
    useCase: ["saying it before its too late", "a rom-com fantasy", "crashing the wrong wedding"],
    oneLiner: "A rom-com heist: crash the wedding and say it before the door closes forever.",
  },
  {
    slug: "dear-john",
    title: "Dear John",
    eraId: "speak-now",
    youtubeId: "N-FYySSy0rM",
    moods: { heartbreak: 0.8, anger: 0.6, nostalgia: 0.35, joy: 0.02, calm: 0.3, defiance: 0.6, longing: 0.5, catharsis: 0.85 },
    energy: 0.45,
    valence: 0.15,
    useCase: ["leaving someone who played games", "reclaiming your story", "a slow blues burn"],
    oneLiner: "A young woman reclaiming a manipulative older love: she should have known, but he did.",
  },
  {
    slug: "mean",
    title: "Mean",
    eraId: "speak-now",
    youtubeId: "8AR1dKawCi8",
    moods: { heartbreak: 0.1, anger: 0.55, nostalgia: 0.1, joy: 0.4, calm: 0.15, defiance: 0.9, longing: 0.2, catharsis: 0.75 },
    energy: 0.75,
    valence: 0.6,
    useCase: ["answering a bully", "proving them wrong", "resilience against cheap shots"],
    oneLiner: "A banjo clapback at a critic: someday she'll be big enough the cheap shots can't reach.",
  },
  {
    slug: "the-story-of-us",
    title: "The Story of Us",
    eraId: "speak-now",
    youtubeId: "pRhWAXg4xek",
    moods: { heartbreak: 0.45, anger: 0.25, nostalgia: 0.3, joy: 0.15, calm: 0.15, defiance: 0.4, longing: 0.65, catharsis: 0.6 },
    energy: 0.75,
    valence: 0.35,
    useCase: ["performing indifference near an ex", "pride versus longing", "an unfinished story"],
    oneLiner: "Two exes rows apart performing indifference, narrated by the one who hates the silence.",
  },
  {
    slug: "never-grow-up",
    title: "Never Grow Up",
    eraId: "speak-now",
    youtubeId: "maEVfpxDB8k",
    moods: { heartbreak: 0.3, anger: 0, nostalgia: 0.9, joy: 0.25, calm: 0.75, defiance: 0.05, longing: 0.65, catharsis: 0.65 },
    energy: 0.3,
    valence: 0.4,
    useCase: ["wishing time would slow down", "homesick for childhood", "first night on your own"],
    oneLiner: "A lullaby to a child that turns out to be a lullaby to herself, alone in a new apartment.",
  },
  {
    slug: "enchanted",
    title: "Enchanted",
    eraId: "speak-now",
    youtubeId: "igIfiqqVHtA",
    moods: { heartbreak: 0.1, anger: 0, nostalgia: 0.4, joy: 0.75, calm: 0.35, defiance: 0.1, longing: 0.85, catharsis: 0.6 },
    energy: 0.6,
    valence: 0.8,
    useCase: ["a dazzling first meeting", "replaying a night all over", "hoping hes not taken"],
    oneLiner: "One wonderstruck first meeting replayed all night, hoping he isn't going home to someone else.",
  },
  {
    slug: "better-than-revenge",
    title: "Better Than Revenge",
    eraId: "speak-now",
    youtubeId: "EH70M5OeS4o",
    moods: { heartbreak: 0.2, anger: 0.8, nostalgia: 0.2, joy: 0.3, calm: 0.05, defiance: 0.85, longing: 0.15, catharsis: 0.65 },
    energy: 0.85,
    valence: 0.4,
    useCase: ["a full-drama grudge", "pop-punk jealousy", "teenage revenge energy"],
    oneLiner: "A full-drama-mode grudge song written at eighteen against the girl who stole him.",
  },
  {
    slug: "innocent",
    title: "Innocent",
    eraId: "speak-now",
    youtubeId: "vO6JqQpJboY",
    moods: { heartbreak: 0.25, anger: 0.1, nostalgia: 0.45, joy: 0.2, calm: 0.6, defiance: 0.3, longing: 0.4, catharsis: 0.65 },
    energy: 0.4,
    valence: 0.45,
    useCase: ["extending grace to someone", "forgiving in public", "everyone can still grow"],
    oneLiner: "A pointedly gracious hand offered to the man who humiliated her on live TV.",
  },
  {
    slug: "haunted",
    title: "Haunted",
    eraId: "speak-now",
    youtubeId: "4cC6fw8EqWU",
    moods: { heartbreak: 0.75, anger: 0.2, nostalgia: 0.2, joy: 0.02, calm: 0.1, defiance: 0.2, longing: 0.8, catharsis: 0.7 },
    energy: 0.75,
    valence: 0.15,
    useCase: ["feeling someone slip away", "the panic of losing them", "a gothic breakdown"],
    oneLiner: "The orchestral panic of feeling someone slip away mid-sentence.",
  },
  {
    slug: "last-kiss",
    title: "Last Kiss",
    eraId: "speak-now",
    youtubeId: "idWma942CUI",
    moods: { heartbreak: 0.9, anger: 0.02, nostalgia: 0.8, joy: 0.02, calm: 0.5, defiance: 0.02, longing: 0.85, catharsis: 0.7 },
    energy: 0.3,
    valence: 0.1,
    useCase: ["a 1am breakup autopsy", "hoarding the small details", "the saddest slow ballad"],
    oneLiner: "A 1 a.m. autopsy of a breakup, kept alive in remembered dates and doorway postures.",
  },
  {
    slug: "long-live",
    title: "Long Live",
    eraId: "speak-now",
    youtubeId: "F5TMU6916U8",
    moods: { heartbreak: 0.1, anger: 0, nostalgia: 0.75, joy: 0.75, calm: 0.35, defiance: 0.35, longing: 0.55, catharsis: 0.85 },
    energy: 0.7,
    valence: 0.8,
    useCase: ["a victory lap with your people", "celebrating a shared run", "graduation and goodbyes"],
    oneLiner: "A toast to everyone who built the improbable run: remember how it felt to hold the crown.",
  },
  {
    slug: "ours",
    title: "Ours",
    eraId: "speak-now",
    youtubeId: "PH8Uc0Z_KRY",
    moods: { heartbreak: 0.05, anger: 0.05, nostalgia: 0.2, joy: 0.75, calm: 0.55, defiance: 0.5, longing: 0.3, catharsis: 0.45 },
    energy: 0.45,
    valence: 0.85,
    useCase: ["a love others dont get", "tuning out the gossip", "quiet contentment together"],
    oneLiner: "A shrug at everyone who disapproves, because the love belongs to exactly two people.",
  },
  {
    slug: "if-this-was-a-movie",
    title: "If This Was a Movie",
    eraId: "speak-now",
    youtubeId: "9wZEx9A8p9k",
    moods: { heartbreak: 0.6, anger: 0.05, nostalgia: 0.55, joy: 0.1, calm: 0.4, defiance: 0.1, longing: 0.85, catharsis: 0.55 },
    energy: 0.5,
    valence: 0.25,
    useCase: ["waiting for a reunion scene", "wishing life had a third act", "the ache of no comeback"],
    oneLiner: "Knowing exactly how the movie ends—he comes back in the rain—and living the unscripted version.",
  },
  {
    slug: "superman",
    title: "Superman",
    eraId: "speak-now",
    youtubeId: "Fn0er7H1Dm0",
    moods: { heartbreak: 0.35, anger: 0.02, nostalgia: 0.35, joy: 0.35, calm: 0.4, defiance: 0.05, longing: 0.8, catharsis: 0.4 },
    energy: 0.5,
    valence: 0.45,
    useCase: ["loving someone always leaving", "hero worship with a bruise", "waiting for a return"],
    oneLiner: "Hero worship with a bruise in it: he saves the world, she does the un-dazzling waiting.",
  },
  {
    slug: "electric-touch",
    title: "Electric Touch",
    eraId: "speak-now",
    youtubeId: "hMPK2vNXr-E",
    moods: { heartbreak: 0.15, anger: 0, nostalgia: 0.2, joy: 0.6, calm: 0.2, defiance: 0.35, longing: 0.65, catharsis: 0.55 },
    energy: 0.75,
    valence: 0.7,
    useCase: ["a first date that could go either way", "hope over a bad track record", "second-chance nerves"],
    oneLiner: "Two people with bad track records meeting anyway: every ending says run, the spark says stay.",
  },
  {
    slug: "when-emma-falls-in-love",
    title: "When Emma Falls in Love",
    eraId: "speak-now",
    youtubeId: "IYqgVYjN3Go",
    moods: { heartbreak: 0.1, anger: 0, nostalgia: 0.4, joy: 0.55, calm: 0.65, defiance: 0.05, longing: 0.4, catharsis: 0.4 },
    energy: 0.35,
    valence: 0.7,
    useCase: ["admiring how a friend loves", "a tender character study", "wishing you loved like her"],
    oneLiner: "An admiring portrait of a friend who loves carefully and completely.",
  },
  {
    slug: "i-can-see-you",
    title: "I Can See You",
    eraId: "speak-now",
    youtubeId: "lVkKLf4DCn8",
    moods: { heartbreak: 0.05, anger: 0, nostalgia: 0.2, joy: 0.55, calm: 0.2, defiance: 0.3, longing: 0.8, catharsis: 0.5 },
    energy: 0.75,
    valence: 0.65,
    useCase: ["a crush kept behind the eyes", "slow-burn tension", "wanting what you cant say"],
    oneLiner: "Desire kept strictly behind the eyes, a secret both people pretend not to notice.",
  },
  {
    slug: "castles-crumbling",
    title: "Castles Crumbling",
    eraId: "speak-now",
    youtubeId: "HtDriYDIhRs",
    moods: { heartbreak: 0.4, anger: 0.15, nostalgia: 0.3, joy: 0.02, calm: 0.2, defiance: 0.15, longing: 0.5, catharsis: 0.7 },
    energy: 0.55,
    valence: 0.15,
    useCase: ["fearing a fall from grace", "the terror of letting everyone down", "cheers turning to jeers"],
    oneLiner: "A ruler watching cheers turn to jeers, terrified of disappointing everyone who chanted her name.",
  },
  {
    slug: "foolish-one",
    title: "Foolish One",
    eraId: "speak-now",
    youtubeId: "6-x1AlDudZw",
    moods: { heartbreak: 0.5, anger: 0.05, nostalgia: 0.2, joy: 0.2, calm: 0.35, defiance: 0.15, longing: 0.85, catharsis: 0.5 },
    energy: 0.45,
    valence: 0.3,
    useCase: ["waiting for a text that wont come", "catching your own delusion", "reading into the crumbs"],
    oneLiner: "Lecturing herself to stop reading into the crumbs, then planning the wedding anyway.",
  },
  {
    slug: "timeless",
    title: "Timeless",
    eraId: "speak-now",
    youtubeId: "osmzwWw4RYM",
    moods: { heartbreak: 0.05, anger: 0, nostalgia: 0.75, joy: 0.6, calm: 0.65, defiance: 0.1, longing: 0.6, catharsis: 0.55 },
    energy: 0.4,
    valence: 0.8,
    useCase: ["believing love is fated", "love across any century", "old-photograph romance"],
    oneLiner: "Flipping through strangers' old photos and deciding she'd have found him in any century.",
  },
  {
    slug: "state-of-grace",
    title: "State of Grace",
    eraId: "red",
    youtubeId: "-mrC5tRkxrY",
    moods: { heartbreak: 0.2, anger: 0.05, nostalgia: 0.4, joy: 0.5, calm: 0.15, defiance: 0.4, longing: 0.55, catharsis: 0.7 },
    energy: 0.75,
    valence: 0.6,
    useCase: ["falling into something risky", "a love worth the wreck", "arena-sized new beginnings"],
    oneLiner: "The door kicked open on a love that will change everything — reckless, ruinous, and chosen anyway.",
  },
  {
    slug: "red",
    title: "Red",
    eraId: "red",
    youtubeId: "R_rUYuFtNO4",
    moods: { heartbreak: 0.6, anger: 0.2, nostalgia: 0.6, joy: 0.4, calm: 0.1, defiance: 0.2, longing: 0.7, catharsis: 0.7 },
    energy: 0.7,
    valence: 0.4,
    useCase: ["a love that ran too hot to keep", "remembering in color", "the highs and the gray after"],
    oneLiner: "An entire relationship graded by color — and red saved for the parts that refuse to fade.",
  },
  {
    slug: "treacherous",
    title: "Treacherous",
    eraId: "red",
    youtubeId: "u1D1AgDfreg",
    moods: { heartbreak: 0.15, anger: 0.02, nostalgia: 0.1, joy: 0.3, calm: 0.4, defiance: 0.35, longing: 0.85, catharsis: 0.45 },
    energy: 0.4,
    valence: 0.45,
    useCase: ["wanting what you know is trouble", "a slow-burn you cant stop", "the first step down a bad slope"],
    oneLiner: "Seeing exactly where the slope leads and taking the first step down it anyway, slowly.",
  },
  {
    slug: "i-knew-you-were-trouble",
    title: "I Knew You Were Trouble",
    eraId: "red",
    youtubeId: "TqAollrUJdA",
    moods: { heartbreak: 0.55, anger: 0.45, nostalgia: 0.1, joy: 0.15, calm: 0.05, defiance: 0.3, longing: 0.2, catharsis: 0.8 },
    energy: 0.85,
    valence: 0.3,
    useCase: ["blaming yourself for ignoring red flags", "a self-aware bad-decision spiral", "the floor giving out"],
    oneLiner: "The red flags were visible from the parking lot — and the bass drop is the floor giving out anyway.",
  },
  {
    slug: "all-too-well",
    title: "All Too Well",
    eraId: "red",
    youtubeId: "9OQBDdNHmXo",
    moods: { heartbreak: 0.9, anger: 0.4, nostalgia: 0.9, joy: 0.05, calm: 0.15, defiance: 0.25, longing: 0.85, catharsis: 0.8 },
    energy: 0.5,
    valence: 0.15,
    useCase: ["crying in the car", "an autumn you cant give back", "remembering every detail on purpose"],
    oneLiner: "A relationship rebuilt object by object — a scarf, an autumn, a refrigerator-light dance — because remembering is the only power left.",
  },
  {
    slug: "22",
    title: "22",
    eraId: "red",
    youtubeId: "9boiT64sm0Q",
    moods: { heartbreak: 0.05, anger: 0.02, nostalgia: 0.3, joy: 0.9, calm: 0.1, defiance: 0.4, longing: 0.1, catharsis: 0.5 },
    energy: 0.85,
    valence: 0.9,
    useCase: ["a night out with your friends", "ditching the heartbreak for one night", "happy free confused all at once"],
    oneLiner: "Being twenty-two as a whole mood: dressed up, heartbreak benched, dancing like the night belongs to your friends.",
  },
  {
    slug: "i-almost-do",
    title: "I Almost Do",
    eraId: "red",
    youtubeId: "w1AV_35zVwU",
    moods: { heartbreak: 0.65, anger: 0.05, nostalgia: 0.4, joy: 0.05, calm: 0.4, defiance: 0.2, longing: 0.85, catharsis: 0.4 },
    energy: 0.4,
    valence: 0.2,
    useCase: ["hovering over the call button", "not texting the ex", "every reason to reach out but one not to"],
    oneLiner: "Every reason to call after a breakup, held back by the one reason not to — so the song replaces the phone call.",
  },
  {
    slug: "we-are-never-ever-getting-back-together",
    title: "We Are Never Ever Getting Back Together",
    eraId: "red",
    youtubeId: "zJFcr1KyFqE",
    moods: { heartbreak: 0.2, anger: 0.4, nostalgia: 0.1, joy: 0.6, calm: 0.05, defiance: 0.85, longing: 0.05, catharsis: 0.7 },
    energy: 0.85,
    valence: 0.75,
    useCase: ["done with the on-again-off-again", "a gleeful spiteful breakup", "closing the door with an eye-roll"],
    oneLiner: "A breakup declared with a flounce and an eye-roll — the never-ever doing gleeful, spiteful work.",
  },
  {
    slug: "stay-stay-stay",
    title: "Stay Stay Stay",
    eraId: "red",
    youtubeId: "OhJ-S9Nrh7Q",
    moods: { heartbreak: 0.05, anger: 0.05, nostalgia: 0.2, joy: 0.85, calm: 0.45, defiance: 0.1, longing: 0.15, catharsis: 0.4 },
    energy: 0.65,
    valence: 0.85,
    useCase: ["a love that survives the fights", "goofy easygoing devotion", "staying instead of storming out"],
    oneLiner: "A fight that ends in laughter instead of tears — staying becomes the punchline and the point.",
  },
  {
    slug: "the-last-time",
    title: "The Last Time",
    eraId: "red",
    youtubeId: "pCH4QrSx2Jg",
    moods: { heartbreak: 0.75, anger: 0.2, nostalgia: 0.25, joy: 0.02, calm: 0.35, defiance: 0.25, longing: 0.7, catharsis: 0.7 },
    energy: 0.5,
    valence: 0.2,
    useCase: ["worn down from giving last chances", "two people talking past each other", "the same doorway one more time"],
    oneLiner: "Two exhausted people at the same doorway again — one pleading for a last chance, one too worn down to give it.",
  },
  {
    slug: "holy-ground",
    title: "Holy Ground",
    eraId: "red",
    youtubeId: "S4PuN-IWi2g",
    moods: { heartbreak: 0.15, anger: 0.02, nostalgia: 0.8, joy: 0.65, calm: 0.3, defiance: 0.15, longing: 0.35, catharsis: 0.7 },
    energy: 0.8,
    valence: 0.75,
    useCase: ["looking back fondly instead of bitter", "gratitude for a love that ended", "making peace with the past"],
    oneLiner: "Years later the anger burns off and only gratitude is left — the ground a good love stood on, consecrated.",
  },
  {
    slug: "sad-beautiful-tragic",
    title: "Sad Beautiful Tragic",
    eraId: "red",
    youtubeId: "jQfB4Gahi3I",
    moods: { heartbreak: 0.75, anger: 0.05, nostalgia: 0.7, joy: 0.02, calm: 0.5, defiance: 0.05, longing: 0.7, catharsis: 0.5 },
    energy: 0.3,
    valence: 0.15,
    useCase: ["mourning something already gone", "the fog of remembering", "no blame left, only sadness"],
    oneLiner: "A relationship seen from the far shore with no blame left — just the three adjectives of the title taking turns.",
  },
  {
    slug: "the-lucky-one",
    title: "The Lucky One",
    eraId: "red",
    youtubeId: "4LtQxA_ooLk",
    moods: { heartbreak: 0.1, anger: 0.1, nostalgia: 0.5, joy: 0.25, calm: 0.4, defiance: 0.3, longing: 0.55, catharsis: 0.45 },
    energy: 0.5,
    valence: 0.4,
    useCase: ["wondering if the fame is worth it", "wanting to disappear from the spotlight", "admiring someone who walked away"],
    oneLiner: "A starlet trades Madison Square Garden for a rose garden — and you start to suspect the runaway was the lucky one.",
  },
  {
    slug: "everything-has-changed",
    title: "Everything Has Changed",
    eraId: "red",
    youtubeId: "eMcMbWl0fDk",
    moods: { heartbreak: 0.05, anger: 0, nostalgia: 0.2, joy: 0.75, calm: 0.45, defiance: 0.05, longing: 0.65, catharsis: 0.4 },
    energy: 0.5,
    valence: 0.8,
    useCase: ["first-meeting butterflies", "wanting to know everything about someone", "the day that split before and after"],
    oneLiner: "Two people who just met and already split time into before and after — all butterflies and wanting to know more.",
  },
  {
    slug: "starlight",
    title: "Starlight",
    eraId: "red",
    youtubeId: "lPvcwgEuKTg",
    moods: { heartbreak: 0.02, anger: 0, nostalgia: 0.75, joy: 0.75, calm: 0.35, defiance: 0.2, longing: 0.5, catharsis: 0.45 },
    energy: 0.7,
    valence: 0.85,
    useCase: ["dreaming up a glamorous night", "young and sure the future is gleaming", "dancing like its decades ago"],
    oneLiner: "A whole shimmering night invented around one old photograph — two teenagers and a future still unwritten.",
  },
  {
    slug: "begin-again",
    title: "Begin Again",
    eraId: "red",
    youtubeId: "dXNZaHuKWNA",
    moods: { heartbreak: 0.25, anger: 0.02, nostalgia: 0.3, joy: 0.65, calm: 0.6, defiance: 0.1, longing: 0.4, catharsis: 0.6 },
    energy: 0.45,
    valence: 0.8,
    useCase: ["a first date after heartbreak", "realizing love isnt all scorn", "quietly starting to believe again"],
    oneLiner: "A Wednesday-cafe first date where she catches herself laughing — and heartbreak does not get the last word.",
  },
  {
    slug: "the-moment-i-knew",
    title: "The Moment I Knew",
    eraId: "red",
    youtubeId: "LmXn6BU16e0",
    moods: { heartbreak: 0.85, anger: 0.25, nostalgia: 0.2, joy: 0.02, calm: 0.2, defiance: 0.1, longing: 0.7, catharsis: 0.6 },
    energy: 0.45,
    valence: 0.12,
    useCase: ["watching a door for someone who wont come", "a birthday that fell apart", "the exact moment you knew"],
    oneLiner: "Standing in a party dress watching a door that never opens — the relationship ending in an empty doorway.",
  },
  {
    slug: "come-back-be-here",
    title: "Come Back... Be Here",
    eraId: "red",
    youtubeId: "hHWOAUjnmjQ",
    moods: { heartbreak: 0.5, anger: 0.02, nostalgia: 0.35, joy: 0.15, calm: 0.4, defiance: 0.05, longing: 0.9, catharsis: 0.4 },
    energy: 0.45,
    valence: 0.3,
    useCase: ["missing someone an ocean away", "resenting the distance", "a perfect weekend cut short"],
    oneLiner: "One perfect weekend, then an ocean — resenting geography itself for interrupting something that barely started.",
  },
  {
    slug: "girl-at-home",
    title: "Girl at Home",
    eraId: "red",
    youtubeId: "UNckfN9upqo",
    moods: { heartbreak: 0.05, anger: 0.15, nostalgia: 0.1, joy: 0.55, calm: 0.2, defiance: 0.65, longing: 0.05, catharsis: 0.45 },
    energy: 0.7,
    valence: 0.65,
    useCase: ["turning down a taken man", "solidarity with the girl at home", "doing the right thing on principle"],
    oneLiner: "A flirtatious guy with a girlfriend gets shut down out of solidarity — not jealousy, just the girl at home.",
  },
  {
    slug: "ronan",
    title: "Ronan",
    eraId: "red",
    youtubeId: "kdiBc40gW7s",
    moods: { heartbreak: 0.95, anger: 0.05, nostalgia: 0.6, joy: 0.1, calm: 0.3, defiance: 0.05, longing: 0.8, catharsis: 0.75 },
    energy: 0.35,
    valence: 0.1,
    useCase: ["grieving a child", "holding a memory that hurts", "a loss with no words"],
    oneLiner: "A eulogy in a grieving mother’s own words for a boy who died just before turning four — one of her heaviest songs.",
  },
  {
    slug: "better-man",
    title: "Better Man",
    eraId: "red",
    youtubeId: "PReSQYTFvcs",
    moods: { heartbreak: 0.6, anger: 0.3, nostalgia: 0.5, joy: 0.05, calm: 0.35, defiance: 0.4, longing: 0.6, catharsis: 0.65 },
    energy: 0.5,
    valence: 0.3,
    useCase: ["missing someone you were right to leave", "grief without regret", "wishing hed just been kinder"],
    oneLiner: "Missing someone and refusing to apologize for leaving — the love was real, but so was the pattern.",
  },
  {
    slug: "nothing-new",
    title: "Nothing New",
    eraId: "red",
    youtubeId: "m3fWCRvz5JA",
    moods: { heartbreak: 0.35, anger: 0.1, nostalgia: 0.4, joy: 0.05, calm: 0.45, defiance: 0.15, longing: 0.6, catharsis: 0.55 },
    energy: 0.35,
    valence: 0.25,
    useCase: ["fearing youll be replaced", "aging out of the spotlight", "wondering if the applause fades"],
    oneLiner: "The fear of being novelty — what happens when a newer, shinier girl arrives and everyone stops clapping.",
  },
  {
    slug: "babe",
    title: "Babe",
    eraId: "red",
    youtubeId: "3pj39qZZYoQ",
    moods: { heartbreak: 0.7, anger: 0.5, nostalgia: 0.2, joy: 0.05, calm: 0.1, defiance: 0.55, longing: 0.4, catharsis: 0.7 },
    energy: 0.6,
    valence: 0.25,
    useCase: ["one betrayal that ends everything", "the last straw", "a future canceled in a moment"],
    oneLiner: "One act of betrayal detonates the whole future tense — every plan they made now needs a new pronoun.",
  },
  {
    slug: "message-in-a-bottle",
    title: "Message in a Bottle",
    eraId: "red",
    youtubeId: "cVaG6adE2mA",
    moods: { heartbreak: 0.05, anger: 0, nostalgia: 0.15, joy: 0.8, calm: 0.15, defiance: 0.1, longing: 0.65, catharsis: 0.45 },
    energy: 0.8,
    valence: 0.85,
    useCase: ["a crush youre hoping reaches them", "fizzy long-shot hope", "throwing your heart into the void"],
    oneLiner: "A crush lobbed into the void like a corked note into the sea — pure fizzy hope it finds the right person.",
  },
  {
    slug: "i-bet-you-think-about-me",
    title: "I Bet You Think About Me",
    eraId: "red",
    youtubeId: "AccGdO5XeZY",
    moods: { heartbreak: 0.15, anger: 0.35, nostalgia: 0.3, joy: 0.5, calm: 0.2, defiance: 0.7, longing: 0.1, catharsis: 0.55 },
    energy: 0.65,
    valence: 0.6,
    useCase: ["betting an ex still thinks of you", "a witty class-warfare kiss-off", "small-town pride vs his fancy world"],
    oneLiner: "A small-town girl toasts the rich ex at his own imaginary wedding — and bets she still haunts his world.",
  },
  {
    slug: "forever-winter",
    title: "Forever Winter",
    eraId: "red",
    youtubeId: "TkAomsYFsJw",
    moods: { heartbreak: 0.55, anger: 0.05, nostalgia: 0.2, joy: 0.15, calm: 0.25, defiance: 0.2, longing: 0.75, catharsis: 0.7 },
    energy: 0.6,
    valence: 0.3,
    useCase: ["loving someone whos struggling", "wishing youd understood sooner", "staying on the line for someone"],
    oneLiner: "Circling someone in crisis, terrified of losing them and promising to stay on the line.",
  },
  {
    slug: "run",
    title: "Run",
    eraId: "red",
    youtubeId: "flv8AEWrRMI",
    moods: { heartbreak: 0.05, anger: 0.02, nostalgia: 0.2, joy: 0.45, calm: 0.6, defiance: 0.4, longing: 0.65, catharsis: 0.45 },
    energy: 0.4,
    valence: 0.6,
    useCase: ["running away with someone", "a private escape from expectations", "a quiet getaway fantasy"],
    oneLiner: "An elopement daydream in hushed harmony — two people ditching everyone’s expectations with a head start.",
  },
  {
    slug: "the-very-first-night",
    title: "The Very First Night",
    eraId: "red",
    youtubeId: "rVuyi-dPMIc",
    moods: { heartbreak: 0.4, anger: 0.02, nostalgia: 0.8, joy: 0.7, calm: 0.15, defiance: 0.1, longing: 0.8, catharsis: 0.6 },
    energy: 0.8,
    valence: 0.6,
    useCase: ["missing the private early days", "dancing back to the beginning", "grief hiding inside a bop"],
    oneLiner: "Grief disguised as a party track — missing the private version of a love, back when it was only theirs.",
  },
  {
    slug: "all-too-well-10-minute-version",
    title: "All Too Well (10 Minute Version)",
    eraId: "red",
    youtubeId: "sRxrwjOtIag",
    moods: { heartbreak: 0.95, anger: 0.6, nostalgia: 0.85, joy: 0.05, calm: 0.1, defiance: 0.3, longing: 0.9, catharsis: 0.8 },
    energy: 0.5,
    valence: 0.15,
    useCase: ["the 3am spiral", "ten minutes of reopening the wound", "the directors cut of heartbreak"],
    oneLiner: "Ten minutes of a wound reopened on purpose — the uncut draft, every excised verse restored.",
  },
  {
    slug: "welcome-to-new-york",
    title: "Welcome to New York",
    eraId: "1989",
    youtubeId: "FsGdznlfE2U",
    moods: { heartbreak: 0.02, anger: 0, nostalgia: 0.1, joy: 0.85, calm: 0.2, defiance: 0.4, longing: 0.4, catharsis: 0.6 },
    energy: 0.8,
    valence: 0.9,
    useCase: ["moving somewhere new", "a clean-slate fresh start", "the city as rebirth"],
    oneLiner: "Arrival as rebirth — a new city where nobody knows the old story and everyone came to reinvent themselves.",
  },
  {
    slug: "blank-space",
    title: "Blank Space",
    eraId: "1989",
    youtubeId: "e-ORhEE9VVg",
    moods: { heartbreak: 0.05, anger: 0.3, nostalgia: 0.05, joy: 0.65, calm: 0.1, defiance: 0.8, longing: 0.1, catharsis: 0.5 },
    energy: 0.8,
    valence: 0.65,
    useCase: ["leaning into a reputation", "playing the villain they wrote", "a wink at your own bad press"],
    oneLiner: "Playing the maneater the tabloids invented — and writing the character better than they ever could.",
  },
  {
    slug: "style",
    title: "Style",
    eraId: "1989",
    youtubeId: "2JgvVfOfoWI",
    moods: { heartbreak: 0.3, anger: 0.05, nostalgia: 0.3, joy: 0.4, calm: 0.25, defiance: 0.2, longing: 0.8, catharsis: 0.5 },
    energy: 0.7,
    valence: 0.5,
    useCase: ["a cant-quit attraction", "crashing back to the same person", "a midnight drive with someone"],
    oneLiner: "Two people who keep crashing back together — chemistry that never goes out of fashion, dread humming underneath.",
  },
  {
    slug: "out-of-the-woods",
    title: "Out of the Woods",
    eraId: "1989",
    youtubeId: "JLf9q36UsBk",
    moods: { heartbreak: 0.35, anger: 0.05, nostalgia: 0.3, joy: 0.2, calm: 0.05, defiance: 0.15, longing: 0.55, catharsis: 0.75 },
    energy: 0.8,
    valence: 0.35,
    useCase: ["love that feels one crisis from over", "anxious cliffhanger romance", "asking are we in the clear yet"],
    oneLiner: "A fragile love lived one disaster at a time — panic rendered as a chorus you cannot stop repeating.",
  },
  {
    slug: "all-you-had-to-do-was-stay",
    title: "All You Had to Do Was Stay",
    eraId: "1989",
    youtubeId: "_Usd5X5XJXM",
    moods: { heartbreak: 0.4, anger: 0.45, nostalgia: 0.15, joy: 0.2, calm: 0.05, defiance: 0.6, longing: 0.3, catharsis: 0.7 },
    energy: 0.75,
    valence: 0.4,
    useCase: ["an ex crawling back too late", "he had one job", "closing a door with self-respect"],
    oneLiner: "An ex comes crawling back and the answer is the title — he had exactly one job.",
  },
  {
    slug: "shake-it-off",
    title: "Shake It Off",
    eraId: "1989",
    youtubeId: "nfWlot6h_JM",
    moods: { heartbreak: 0.02, anger: 0.05, nostalgia: 0.02, joy: 0.9, calm: 0.1, defiance: 0.75, longing: 0.02, catharsis: 0.6 },
    energy: 0.9,
    valence: 0.92,
    useCase: ["shrugging off the haters", "dancing through criticism", "refusing to let it land"],
    oneLiner: "The haters keep hating and she keeps dancing — laughing at the noise instead of arguing with it.",
  },
  {
    slug: "i-wish-you-would",
    title: "I Wish You Would",
    eraId: "1989",
    youtubeId: "89aQIli8aVU",
    moods: { heartbreak: 0.4, anger: 0.1, nostalgia: 0.35, joy: 0.15, calm: 0.15, defiance: 0.25, longing: 0.85, catharsis: 0.55 },
    energy: 0.75,
    valence: 0.35,
    useCase: ["wishing theyd make the first move", "driving past an ex’s street", "late-night stubborn regret"],
    oneLiner: "Two stubborn exes driving past each other’s lives, each wishing the other would make the move neither will.",
  },
  {
    slug: "bad-blood",
    title: "Bad Blood",
    eraId: "1989",
    youtubeId: "QcIy9NiNbmo",
    moods: { heartbreak: 0.4, anger: 0.8, nostalgia: 0.1, joy: 0.2, calm: 0.05, defiance: 0.75, longing: 0.1, catharsis: 0.7 },
    energy: 0.85,
    valence: 0.4,
    useCase: ["a friend who betrayed you", "holding a stadium-sized grudge", "a backstab, not a breakup"],
    oneLiner: "A friendship betrayed at the professional level — not a breakup, a backstab, with a chorus built for grudges.",
  },
  {
    slug: "wildest-dreams",
    title: "Wildest Dreams",
    eraId: "1989",
    youtubeId: "IdneKLhsWOQ",
    moods: { heartbreak: 0.45, anger: 0.02, nostalgia: 0.5, joy: 0.3, calm: 0.35, defiance: 0.1, longing: 0.85, catharsis: 0.5 },
    energy: 0.55,
    valence: 0.4,
    useCase: ["a romance you know is doomed", "wanting to be remembered beautifully", "pre-writing the nostalgia"],
    oneLiner: "Scripting the memory before the romance even ends — if it has to be doomed, let it be remembered cinematic.",
  },
  {
    slug: "how-you-get-the-girl",
    title: "How You Get the Girl",
    eraId: "1989",
    youtubeId: "XQh8zhmTtBg",
    moods: { heartbreak: 0.1, anger: 0.05, nostalgia: 0.1, joy: 0.65, calm: 0.25, defiance: 0.2, longing: 0.5, catharsis: 0.4 },
    energy: 0.65,
    valence: 0.75,
    useCase: ["winning someone back", "the exact right thing to say", "showing up in the rain"],
    oneLiner: "A step-by-step how-to for the boy who left — sunny on top, pointed underneath.",
  },
  {
    slug: "this-love",
    title: "This Love",
    eraId: "1989",
    youtubeId: "r9VzPf8a4kI",
    moods: { heartbreak: 0.2, anger: 0.02, nostalgia: 0.35, joy: 0.45, calm: 0.75, defiance: 0.05, longing: 0.6, catharsis: 0.55 },
    energy: 0.3,
    valence: 0.6,
    useCase: ["a love that quietly comes back", "stillness after the storm", "patient tidal devotion"],
    oneLiner: "Love as tide — something released that actually comes back, the quietest song on a maximalist record.",
  },
  {
    slug: "i-know-places",
    title: "I Know Places",
    eraId: "1989",
    youtubeId: "0jTGzm-6cYE",
    moods: { heartbreak: 0.15, anger: 0.2, nostalgia: 0.05, joy: 0.3, calm: 0.1, defiance: 0.6, longing: 0.45, catharsis: 0.5 },
    energy: 0.75,
    valence: 0.45,
    useCase: ["protecting a love from prying eyes", "us against the watchers", "a romance planned like a heist"],
    oneLiner: "Two lovers planning a romance like a heist — the watchers are hunters, and privacy is the getaway route.",
  },
  {
    slug: "clean",
    title: "Clean",
    eraId: "1989",
    youtubeId: "AppsjTInqiw",
    moods: { heartbreak: 0.4, anger: 0.02, nostalgia: 0.4, joy: 0.35, calm: 0.7, defiance: 0.15, longing: 0.4, catharsis: 0.85 },
    energy: 0.3,
    valence: 0.5,
    useCase: ["finally over someone", "the day the wound stops needing checking", "healing as detox"],
    oneLiner: "Healing framed as detox — the drought, the flood, and the morning you notice the wound finally closed.",
  },
  {
    slug: "wonderland",
    title: "Wonderland",
    eraId: "1989",
    youtubeId: "E048L9PaZsk",
    moods: { heartbreak: 0.3, anger: 0.05, nostalgia: 0.1, joy: 0.45, calm: 0.1, defiance: 0.3, longing: 0.6, catharsis: 0.55 },
    energy: 0.8,
    valence: 0.45,
    useCase: ["falling fast and losing the plot", "a dazzling disorienting romance", "madness you both chose"],
    oneLiner: "Falling fast into a dazzling, disorienting romance and losing the plot together — madness as the destination.",
  },
  {
    slug: "you-are-in-love",
    title: "You Are in Love",
    eraId: "1989",
    youtubeId: "a_zwscPcDGM",
    moods: { heartbreak: 0.05, anger: 0, nostalgia: 0.3, joy: 0.6, calm: 0.75, defiance: 0.02, longing: 0.7, catharsis: 0.5 },
    energy: 0.3,
    valence: 0.8,
    useCase: ["the small unglamorous proofs of love", "yearning for an ordinary intimacy", "watching real love up close"],
    oneLiner: "Real love assembled from small proofs — burnt toast, a word mid-dance — narrated from just outside it.",
  },
  {
    slug: "new-romantics",
    title: "New Romantics",
    eraId: "1989",
    youtubeId: "3-BcH7KowGE",
    moods: { heartbreak: 0.25, anger: 0.1, nostalgia: 0.1, joy: 0.75, calm: 0.1, defiance: 0.6, longing: 0.2, catharsis: 0.7 },
    energy: 0.85,
    valence: 0.75,
    useCase: ["treating heartbreak as raw material", "bored broke and building anyway", "collective bright defiance"],
    oneLiner: "An anthem for turning heartbreak into raw material — bored, broke, and building castles from the bricks thrown at you.",
  },
  {
    slug: "slut",
    title: "\"Slut!\"",
    eraId: "1989",
    youtubeId: "qrxsceexTBw",
    moods: { heartbreak: 0.2, anger: 0.15, nostalgia: 0.2, joy: 0.5, calm: 0.55, defiance: 0.6, longing: 0.5, catharsis: 0.5 },
    energy: 0.45,
    valence: 0.6,
    useCase: ["choosing love despite the gossip", "letting the name-calling be the tax", "a dreamy shrug at the headlines"],
    oneLiner: "If the tabloids will call her that anyway, this love is worth the headline — anger swapped for a dreamy shrug.",
  },
  {
    slug: "say-dont-go",
    title: "Say Don't Go",
    eraId: "1989",
    youtubeId: "C-z-IckrQK8",
    moods: { heartbreak: 0.6, anger: 0.15, nostalgia: 0.15, joy: 0.1, calm: 0.15, defiance: 0.2, longing: 0.8, catharsis: 0.7 },
    energy: 0.6,
    valence: 0.25,
    useCase: ["waiting for someone to fight for you", "loving someone who lets you twist", "the silence that answers for them"],
    oneLiner: "Loving someone who lets you twist — waiting for him to fight for it while the silence gives its own answer.",
  },
  {
    slug: "now-that-we-dont-talk",
    title: "Now That We Don't Talk",
    eraId: "1989",
    youtubeId: "yF4ulRTCn44",
    moods: { heartbreak: 0.3, anger: 0.2, nostalgia: 0.2, joy: 0.5, calm: 0.15, defiance: 0.65, longing: 0.25, catharsis: 0.65 },
    energy: 0.75,
    valence: 0.6,
    useCase: ["no longer faking his taste", "reclaiming yourself after a breakup", "a petty precise post-mortem"],
    oneLiner: "Once the silence sets in, the wins count themselves — no more faking a taste for his music, his friends, his idea of you.",
  },
  {
    slug: "suburban-legends",
    title: "Suburban Legends",
    eraId: "1989",
    youtubeId: "ZGBPKYbzSXs",
    moods: { heartbreak: 0.4, anger: 0.1, nostalgia: 0.4, joy: 0.45, calm: 0.15, defiance: 0.2, longing: 0.7, catharsis: 0.55 },
    energy: 0.7,
    valence: 0.45,
    useCase: ["a love you turned into legend", "destiny meeting ordinary letdown", "forgiving someone too fast"],
    oneLiner: "Casting the two of you as hometown legend, then watching him wreck the legend right on schedule.",
  },
  {
    slug: "is-it-over-now",
    title: "Is It Over Now?",
    eraId: "1989",
    youtubeId: "tNxUxm3-658",
    moods: { heartbreak: 0.45, anger: 0.55, nostalgia: 0.25, joy: 0.15, calm: 0.05, defiance: 0.6, longing: 0.45, catharsis: 0.7 },
    energy: 0.8,
    valence: 0.35,
    useCase: ["a breakup with no clean ending", "who ended it and when", "seeing an ex move on too fast"],
    oneLiner: "The question you ask when a breakup never got a clean end — who ended what, and why is he already photographed with someone new.",
  },
  {
    slug: "ready-for-it",
    title: "...Ready for It?",
    eraId: "reputation",
    youtubeId: "T62maKYX9tU",
    moods: { heartbreak: 0.05, anger: 0.2, nostalgia: 0.1, joy: 0.55, calm: 0.05, defiance: 0.8, longing: 0.65, catharsis: 0.55 },
    energy: 0.95,
    valence: 0.6,
    useCase: ["a new love you keep secret", "armor up and let someone in", "the thrill of a co-conspirator"],
    oneLiner: "Industrial armor on the verses, a secret love song hiding in the chorus.",
  },
  {
    slug: "end-game",
    title: "End Game",
    eraId: "reputation",
    youtubeId: "dfnCAmr569k",
    moods: { heartbreak: 0.1, anger: 0.15, nostalgia: 0.1, joy: 0.55, calm: 0.1, defiance: 0.55, longing: 0.7, catharsis: 0.45 },
    energy: 0.85,
    valence: 0.6,
    useCase: ["wanting to be someone’s ending", "judged by your worst headlines", "past baggage on the table"],
    oneLiner: "Big reputations all asking the same thing: judge me up close, not by the highlight reel.",
  },
  {
    slug: "i-did-something-bad",
    title: "I Did Something Bad",
    eraId: "reputation",
    youtubeId: "xYLxUJ9v6KU",
    moods: { heartbreak: 0.05, anger: 0.75, nostalgia: 0.05, joy: 0.5, calm: 0.02, defiance: 0.95, longing: 0.05, catharsis: 0.8 },
    energy: 0.9,
    valence: 0.5,
    useCase: ["done apologizing for existing", "burned as a witch anyway", "playing the villain on purpose"],
    oneLiner: "Zero remorse as a power stance: if they’ll burn her either way, she’ll supply the gasoline.",
  },
  {
    slug: "dont-blame-me",
    title: "Don't Blame Me",
    eraId: "reputation",
    youtubeId: "kRJKB291Z1g",
    moods: { heartbreak: 0.15, anger: 0.15, nostalgia: 0.05, joy: 0.5, calm: 0.1, defiance: 0.6, longing: 0.8, catharsis: 0.85 },
    energy: 0.8,
    valence: 0.5,
    useCase: ["love that feels like a drug", "obsessive devotion", "pleading guilty with a choir behind you"],
    oneLiner: "A gospel-stomp confession that love made her crazy and she’d be convicted for it gladly.",
  },
  {
    slug: "delicate",
    title: "Delicate",
    eraId: "reputation",
    youtubeId: "tCXGJQYZ9JA",
    moods: { heartbreak: 0.2, anger: 0.02, nostalgia: 0.15, joy: 0.5, calm: 0.55, defiance: 0.15, longing: 0.8, catharsis: 0.55 },
    energy: 0.5,
    valence: 0.6,
    useCase: ["starting something real, terrified", "wondering if it’s too soon", "liked despite your worst name"],
    oneLiner: "The soft center: your reputation’s never been worse, so someone liking you anyway must be real.",
  },
  {
    slug: "look-what-you-made-me-do",
    title: "Look What You Made Me Do",
    eraId: "reputation",
    youtubeId: "3tmd-ClpJxA",
    moods: { heartbreak: 0.05, anger: 0.85, nostalgia: 0.1, joy: 0.4, calm: 0.02, defiance: 0.95, longing: 0.05, catharsis: 0.8 },
    energy: 0.85,
    valence: 0.45,
    useCase: ["clapping back at the whole narrative", "the old you can’t come to the phone", "reinventing after a burial"],
    oneLiner: "A revenge overture that kills the old Taylor and dares everyone who wrote her obituary.",
  },
  {
    slug: "so-it-goes",
    title: "So It Goes...",
    eraId: "reputation",
    youtubeId: "iAv1Y1YIwm8",
    moods: { heartbreak: 0.1, anger: 0.1, nostalgia: 0.1, joy: 0.5, calm: 0.35, defiance: 0.35, longing: 0.65, catharsis: 0.4 },
    energy: 0.6,
    valence: 0.55,
    useCase: ["someone only you get to see", "shutting the door on the world", "private intensity"],
    oneLiner: "A dissolve into someone behind closed doors, shrugging at everything outside the two of them.",
  },
  {
    slug: "gorgeous",
    title: "Gorgeous",
    eraId: "reputation",
    youtubeId: "EUoe7cf0HYw",
    moods: { heartbreak: 0.05, anger: 0.2, nostalgia: 0.05, joy: 0.75, calm: 0.1, defiance: 0.3, longing: 0.65, catharsis: 0.35 },
    energy: 0.65,
    valence: 0.75,
    useCase: ["furious that someone’s that attractive", "a tipsy inconvenient crush", "petty and loving it"],
    oneLiner: "The album’s lightest confession: being mad at someone just for being that gorgeous.",
  },
  {
    slug: "getaway-car",
    title: "Getaway Car",
    eraId: "reputation",
    youtubeId: "FhPLQVlUiNQ",
    moods: { heartbreak: 0.55, anger: 0.1, nostalgia: 0.3, joy: 0.35, calm: 0.05, defiance: 0.5, longing: 0.5, catharsis: 0.8 },
    energy: 0.8,
    valence: 0.45,
    useCase: ["a rebound you knew was doomed", "fleeing one wreck into another", "owning that you did wrong"],
    oneLiner: "A heist epic about using one love to escape another, doomed from the ignition and knowing it.",
  },
  {
    slug: "king-of-my-heart",
    title: "King of My Heart",
    eraId: "reputation",
    youtubeId: "5U7bF68xcRg",
    moods: { heartbreak: 0.05, anger: 0.02, nostalgia: 0.15, joy: 0.8, calm: 0.35, defiance: 0.25, longing: 0.6, catharsis: 0.6 },
    energy: 0.7,
    valence: 0.85,
    useCase: ["falling deeper in stages", "contentment over flash", "someone winning over your cynicism"],
    oneLiner: "Three acts of falling: from liking your own company to full fanfare for the right person.",
  },
  {
    slug: "dancing-with-our-hands-tied",
    title: "Dancing with Our Hands Tied",
    eraId: "reputation",
    youtubeId: "erGyUphZSt8",
    moods: { heartbreak: 0.4, anger: 0.1, nostalgia: 0.25, joy: 0.4, calm: 0.15, defiance: 0.5, longing: 0.75, catharsis: 0.7 },
    energy: 0.75,
    valence: 0.45,
    useCase: ["loving someone under a spotlight", "holding on as it might blow up", "a dance inside the blast radius"],
    oneLiner: "Loving someone while the world watches with knives out, and slow-dancing through the dread anyway.",
  },
  {
    slug: "dress",
    title: "Dress",
    eraId: "reputation",
    youtubeId: "FNEoPctNIUE",
    moods: { heartbreak: 0.05, anger: 0.05, nostalgia: 0.15, joy: 0.55, calm: 0.3, defiance: 0.25, longing: 0.85, catharsis: 0.5 },
    energy: 0.55,
    valence: 0.65,
    useCase: ["friendship burning past its container", "grown-up wanting", "a want you finally say out loud"],
    oneLiner: "The most grown-up song yet: desire stated plainly enough to make the listening parties blush.",
  },
  {
    slug: "this-is-why-we-cant-have-nice-things",
    title: "This Is Why We Can't Have Nice Things",
    eraId: "reputation",
    youtubeId: "6Z3QJ4L1Bg0",
    moods: { heartbreak: 0.15, anger: 0.65, nostalgia: 0.15, joy: 0.55, calm: 0.02, defiance: 0.85, longing: 0.1, catharsis: 0.75 },
    energy: 0.85,
    valence: 0.5,
    useCase: ["a betrayal you can laugh at now", "offering forgiveness then yanking it", "gleeful pettiness"],
    oneLiner: "A party-crash diss track that fake-toasts forgiveness for a knife-in-the-back friendship, then laughs.",
  },
  {
    slug: "call-it-what-you-want",
    title: "Call It What You Want",
    eraId: "reputation",
    youtubeId: "V54CEElTF_U",
    moods: { heartbreak: 0.15, anger: 0.05, nostalgia: 0.2, joy: 0.55, calm: 0.6, defiance: 0.5, longing: 0.5, catharsis: 0.65 },
    energy: 0.45,
    valence: 0.65,
    useCase: ["the calm after your name got wrecked", "one person who stayed", "not caring what they call it"],
    oneLiner: "The peace treaty after the war: the castle fell, the crowd left, and the one who stayed is enough.",
  },
  {
    slug: "new-years-day",
    title: "New Year's Day",
    eraId: "reputation",
    youtubeId: "MWSn0H4qfAs",
    moods: { heartbreak: 0.15, anger: 0.02, nostalgia: 0.55, joy: 0.45, calm: 0.85, defiance: 0.05, longing: 0.7, catharsis: 0.6 },
    energy: 0.2,
    valence: 0.65,
    useCase: ["wanting the person who stays to clean up", "the quiet morning after", "ordinary, unglamorous devotion"],
    oneLiner: "A bare piano closer: after twelve tracks of armor, she just wants whoever holds the trash bag.",
  },
  {
    slug: "i-forgot-that-you-existed",
    title: "I Forgot That You Existed",
    eraId: "lover",
    youtubeId: "p1cEvNn88jM",
    moods: { heartbreak: 0.05, anger: 0.1, nostalgia: 0.1, joy: 0.7, calm: 0.45, defiance: 0.55, longing: 0.05, catharsis: 0.7 },
    energy: 0.55,
    valence: 0.8,
    useCase: ["finally not caring about a grudge", "indifference as the real revenge", "closing a heavy chapter"],
    oneLiner: "The giggling epilogue to reputation: not love, not hate, just the freedom of forgetting.",
  },
  {
    slug: "cruel-summer",
    title: "Cruel Summer",
    eraId: "lover",
    youtubeId: "ic8j13piAhQ",
    moods: { heartbreak: 0.2, anger: 0.1, nostalgia: 0.2, joy: 0.6, calm: 0.05, defiance: 0.4, longing: 0.9, catharsis: 0.85 },
    energy: 0.85,
    valence: 0.55,
    useCase: ["a secret summer romance", "blurting out love you meant to hide", "desperation under a cool surface"],
    oneLiner: "A garden-gate summer fling with the catalog’s most famous bridge-scream about saying too much.",
  },
  {
    slug: "lover",
    title: "Lover",
    eraId: "lover",
    youtubeId: "-BjZmE2gtdo",
    moods: { heartbreak: 0.05, anger: 0.02, nostalgia: 0.4, joy: 0.7, calm: 0.75, defiance: 0.1, longing: 0.6, catharsis: 0.55 },
    energy: 0.35,
    valence: 0.85,
    useCase: ["a first dance at a wedding", "leaving the Christmas lights up", "settling into a forever"],
    oneLiner: "A waltz with its own vows in the bridge, written in one night to be slow-danced to indefinitely.",
  },
  {
    slug: "the-man",
    title: "The Man",
    eraId: "lover",
    youtubeId: "AqAJLh9wuZ0",
    moods: { heartbreak: 0.05, anger: 0.55, nostalgia: 0.05, joy: 0.5, calm: 0.1, defiance: 0.85, longing: 0.1, catharsis: 0.6 },
    energy: 0.75,
    valence: 0.55,
    useCase: ["tired of the double standard", "ambition read as a liability", "flipping the genders on your critics"],
    oneLiner: "A thought experiment: run every criticism of her career with the genders swapped and watch it flip.",
  },
  {
    slug: "the-archer",
    title: "The Archer",
    eraId: "lover",
    youtubeId: "8KpKc3C9V3w",
    moods: { heartbreak: 0.35, anger: 0.05, nostalgia: 0.2, joy: 0.15, calm: 0.45, defiance: 0.1, longing: 0.8, catharsis: 0.55 },
    energy: 0.4,
    valence: 0.35,
    useCase: ["wondering who could ever stay", "attachment anxiety at 2am", "being both hunter and target"],
    oneLiner: "One synth pulse, no chorus, no drop: pure confession that nothing resolves, including her.",
  },
  {
    slug: "i-think-he-knows",
    title: "I Think He Knows",
    eraId: "lover",
    youtubeId: "2d1wKn-oJnA",
    moods: { heartbreak: 0.02, anger: 0.02, nostalgia: 0.05, joy: 0.8, calm: 0.2, defiance: 0.2, longing: 0.7, catharsis: 0.35 },
    energy: 0.7,
    valence: 0.85,
    useCase: ["a confident, electric crush", "flirting with someone who knows it", "the charge of mutual attraction"],
    oneLiner: "A strutting deep cut about a crush on someone fully, infuriatingly aware of his own charm.",
  },
  {
    slug: "miss-americana-and-the-heartbreak-prince",
    title: "Miss Americana & the Heartbreak Prince",
    eraId: "lover",
    youtubeId: "Kwf7P2GNAVw",
    moods: { heartbreak: 0.35, anger: 0.4, nostalgia: 0.35, joy: 0.35, calm: 0.1, defiance: 0.65, longing: 0.45, catharsis: 0.7 },
    energy: 0.65,
    valence: 0.4,
    useCase: ["disillusioned but deciding to speak", "watching a rigged scoreboard", "political heartbreak in a letterman jacket"],
    oneLiner: "High-school Americana as national allegory: the homecoming-queen dream curdling, and speaking anyway.",
  },
  {
    slug: "paper-rings",
    title: "Paper Rings",
    eraId: "lover",
    youtubeId: "8zdg-pDF10g",
    moods: { heartbreak: 0.02, anger: 0.02, nostalgia: 0.15, joy: 0.9, calm: 0.2, defiance: 0.3, longing: 0.5, catharsis: 0.5 },
    energy: 0.85,
    valence: 0.9,
    useCase: ["giddy about the whole package", "the person over the paperwork", "joyful, all-in commitment"],
    oneLiner: "Pop-punk giddiness: she’d marry this one with rings cut from paper after years of gilded drama.",
  },
  {
    slug: "cornelia-street",
    title: "Cornelia Street",
    eraId: "lover",
    youtubeId: "VikHHWrgb4Y",
    moods: { heartbreak: 0.4, anger: 0.02, nostalgia: 0.6, joy: 0.35, calm: 0.4, defiance: 0.05, longing: 0.85, catharsis: 0.65 },
    energy: 0.45,
    valence: 0.45,
    useCase: ["a memory pinned to one street", "fear a place could turn unlivable", "love tangled up with geography"],
    oneLiner: "A whole street she couldn’t walk again if this love ended — memory amputated block by block.",
  },
  {
    slug: "death-by-a-thousand-cuts",
    title: "Death by a Thousand Cuts",
    eraId: "lover",
    youtubeId: "GTEFSuFfgnU",
    moods: { heartbreak: 0.75, anger: 0.1, nostalgia: 0.4, joy: 0.25, calm: 0.15, defiance: 0.2, longing: 0.7, catharsis: 0.7 },
    energy: 0.6,
    valence: 0.3,
    useCase: ["a city full of reminders", "heartbreak felt in a hundred small places", "grief you imagined into being"],
    oneLiner: "A breakup song written inside a happy relationship, sparked by a rom-com in a strange creative loop.",
  },
  {
    slug: "london-boy",
    title: "London Boy",
    eraId: "lover",
    youtubeId: "VsKoOH6DVys",
    moods: { heartbreak: 0.02, anger: 0.02, nostalgia: 0.15, joy: 0.85, calm: 0.25, defiance: 0.1, longing: 0.55, catharsis: 0.35 },
    energy: 0.65,
    valence: 0.9,
    useCase: ["falling for someone’s whole city", "playful, all-in devotion", "a tourist-map valentine"],
    oneLiner: "An American falls for the whole British kit — pubs, rugby, high tea — geography chaos and all.",
  },
  {
    slug: "soon-youll-get-better",
    title: "Soon You'll Get Better",
    eraId: "lover",
    youtubeId: "tMoW5G5LU08",
    moods: { heartbreak: 0.85, anger: 0.15, nostalgia: 0.35, joy: 0.1, calm: 0.35, defiance: 0.1, longing: 0.8, catharsis: 0.75 },
    energy: 0.25,
    valence: 0.2,
    useCase: ["a parent in a hospital", "bargaining with something bigger", "love that can only wait and hope"],
    oneLiner: "Written amid her mother’s cancer: waiting rooms, bargaining, and a refrain that has to be true.",
  },
  {
    slug: "false-god",
    title: "False God",
    eraId: "lover",
    youtubeId: "acQXa5ArHIk",
    moods: { heartbreak: 0.3, anger: 0.2, nostalgia: 0.2, joy: 0.4, calm: 0.4, defiance: 0.35, longing: 0.8, catharsis: 0.6 },
    energy: 0.45,
    valence: 0.5,
    useCase: ["fighting across time zones", "love neither of you will quit", "devotion even when it’s misplaced"],
    oneLiner: "Saxophone and sacrilege: a long-distance argument where the relationship is treated as religion.",
  },
  {
    slug: "you-need-to-calm-down",
    title: "You Need to Calm Down",
    eraId: "lover",
    youtubeId: "GWtfOHBF1_w",
    moods: { heartbreak: 0.02, anger: 0.35, nostalgia: 0.05, joy: 0.75, calm: 0.15, defiance: 0.75, longing: 0.05, catharsis: 0.6 },
    energy: 0.8,
    valence: 0.8,
    useCase: ["telling trolls to take a seat", "standing up as an ally", "de-escalating with a smile"],
    oneLiner: "Three verses of \"take several seats\" — haters, picketers, rivals — ending on a real policy ask.",
  },
  {
    slug: "afterglow",
    title: "Afterglow",
    eraId: "lover",
    youtubeId: "8HxbqAsppwU",
    moods: { heartbreak: 0.5, anger: 0.15, nostalgia: 0.2, joy: 0.3, calm: 0.35, defiance: 0.1, longing: 0.75, catharsis: 0.75 },
    energy: 0.5,
    valence: 0.4,
    useCase: ["owning that you started the fight", "anxiety torching something good", "an apology and a plea to stay"],
    oneLiner: "An accountability ballad: she claims the arson and asks the other person to stay inside the glow.",
  },
  {
    slug: "me",
    title: "Me!",
    eraId: "lover",
    youtubeId: "FuXNumBwDOM",
    moods: { heartbreak: 0.02, anger: 0.05, nostalgia: 0.05, joy: 0.85, calm: 0.1, defiance: 0.5, longing: 0.2, catharsis: 0.45 },
    energy: 0.85,
    valence: 0.9,
    useCase: ["a technicolor confidence boost", "celebrating being one of a kind", "a pastel palette flip"],
    oneLiner: "Self-celebration as a duet: two dramatic people pitching their own irreplaceability in full color.",
  },
  {
    slug: "its-nice-to-have-a-friend",
    title: "It's Nice to Have a Friend",
    eraId: "lover",
    youtubeId: "eaP1VswBF28",
    moods: { heartbreak: 0.05, anger: 0.02, nostalgia: 0.55, joy: 0.6, calm: 0.75, defiance: 0.05, longing: 0.6, catharsis: 0.4 },
    energy: 0.3,
    valence: 0.8,
    useCase: ["friendship ripening into love", "a whole life told in miniature", "quiet, gentle tenderness"],
    oneLiner: "Steel drums and a children’s choir tell a whole life — snow fights to a ring — in under three minutes.",
  },
  {
    slug: "daylight",
    title: "Daylight",
    eraId: "lover",
    youtubeId: "u9raS7-NisU",
    moods: { heartbreak: 0.1, anger: 0.02, nostalgia: 0.45, joy: 0.65, calm: 0.8, defiance: 0.15, longing: 0.55, catharsis: 0.8 },
    energy: 0.4,
    valence: 0.8,
    useCase: ["redefining what love means to you", "peace after years of drama", "choosing what you love over what you hate"],
    oneLiner: "The closer that revises her own catalog: love isn’t golden or red drama but ordinary daylight.",
  },
  {
    slug: "the-1",
    title: "the 1",
    eraId: "folklore",
    youtubeId: "KsZ6tROaVOQ",
    moods: { heartbreak: 0.45, anger: 0.05, nostalgia: 0.6, joy: 0.35, calm: 0.6, defiance: 0.1, longing: 0.75, catharsis: 0.5 },
    energy: 0.45,
    valence: 0.45,
    useCase: ["doing the math on the one who got away", "fine, honestly, but wistful", "imagining the parallel life"],
    oneLiner: "A breezy what-if with a bruise under it: someone doing okay who can’t stop wondering.",
  },
  {
    slug: "cardigan",
    title: "cardigan",
    eraId: "folklore",
    youtubeId: "K-a8s8OLBSE",
    moods: { heartbreak: 0.6, anger: 0.1, nostalgia: 0.75, joy: 0.3, calm: 0.4, defiance: 0.15, longing: 0.85, catharsis: 0.7 },
    energy: 0.45,
    valence: 0.4,
    useCase: ["being chosen back years later", "remembering a teenage love", "the ache of first heartbreak"],
    oneLiner: "Betty grown up, remembering being young and discarded and chosen again — the favorite comfort object.",
  },
  {
    slug: "the-last-great-american-dynasty",
    title: "the last great american dynasty",
    eraId: "folklore",
    youtubeId: "2s5xdY6MCeI",
    moods: { heartbreak: 0.1, anger: 0.25, nostalgia: 0.5, joy: 0.5, calm: 0.25, defiance: 0.75, longing: 0.2, catharsis: 0.6 },
    energy: 0.6,
    valence: 0.6,
    useCase: ["a woman labeled mad for having fun", "inheriting someone’s notoriety", "history rhyming across owners"],
    oneLiner: "A scandalous widow’s fifty years of gossip — then the narrator buys the house and inherits it all.",
  },
  {
    slug: "exile",
    title: "exile",
    eraId: "folklore",
    youtubeId: "osdoLjUNFnA",
    moods: { heartbreak: 0.85, anger: 0.25, nostalgia: 0.4, joy: 0.05, calm: 0.3, defiance: 0.15, longing: 0.75, catharsis: 0.8 },
    energy: 0.5,
    valence: 0.2,
    useCase: ["talking past someone you loved", "a breakup with no shared story", "two people, two truths"],
    oneLiner: "A duet staged as two monologues: he saw no signs, she gave hundreds, and neither one hears the other.",
  },
  {
    slug: "my-tears-ricochet",
    title: "my tears ricochet",
    eraId: "folklore",
    youtubeId: "OWbDJFtHl3w",
    moods: { heartbreak: 0.75, anger: 0.65, nostalgia: 0.35, joy: 0.05, calm: 0.2, defiance: 0.55, longing: 0.55, catharsis: 0.85 },
    energy: 0.45,
    valence: 0.2,
    useCase: ["betrayed by a former ally", "grieving something that was stolen", "haunting the person who wronged you"],
    oneLiner: "Narrated from inside a casket: a betrayer shows up to mourn the very person he cast out and sold.",
  },
  {
    slug: "mirrorball",
    title: "mirrorball",
    eraId: "folklore",
    youtubeId: "KaM1bCuG4xo",
    moods: { heartbreak: 0.4, anger: 0.05, nostalgia: 0.35, joy: 0.35, calm: 0.55, defiance: 0.1, longing: 0.65, catharsis: 0.55 },
    energy: 0.4,
    valence: 0.45,
    useCase: ["wondering who you are with no audience", "exhausted from people-pleasing", "shining hardest when they might leave"],
    oneLiner: "A disco-ball confession from a performer with nowhere left to perform, spinning to keep the crowd.",
  },
  {
    slug: "seven",
    title: "seven",
    eraId: "folklore",
    youtubeId: "pEY-GPsru_E",
    moods: { heartbreak: 0.3, anger: 0.1, nostalgia: 0.9, joy: 0.4, calm: 0.55, defiance: 0.1, longing: 0.8, catharsis: 0.6 },
    energy: 0.35,
    valence: 0.5,
    useCase: ["a childhood friend you never forgot", "innocence witnessing something dark", "love passed down like a folk song"],
    oneLiner: "Two little girls plotting pirate escapes, one of them living in a frightening house, remembered decades on.",
  },
  {
    slug: "august",
    title: "august",
    eraId: "folklore",
    youtubeId: "nn_0zPAfyo8",
    moods: { heartbreak: 0.65, anger: 0.05, nostalgia: 0.7, joy: 0.3, calm: 0.35, defiance: 0.1, longing: 0.9, catharsis: 0.75 },
    energy: 0.5,
    valence: 0.35,
    useCase: ["wanting someone who was never yours", "a summer that felt like a lifetime", "hoping against the facts"],
    oneLiner: "The summer fling from the other girl’s side: she knew he was never hers and wanted him anyway.",
  },
  {
    slug: "this-is-me-trying",
    title: "this is me trying",
    eraId: "folklore",
    youtubeId: "9bdLTPNrlEg",
    moods: { heartbreak: 0.5, anger: 0.2, nostalgia: 0.3, joy: 0.2, calm: 0.35, defiance: 0.3, longing: 0.55, catharsis: 0.8 },
    energy: 0.4,
    valence: 0.35,
    useCase: ["when just showing up is heroic", "invisible effort no one claps for", "one day sober, one more time"],
    oneLiner: "Three people barely holding on, where pulling into the driveway you almost skipped is the whole victory.",
  },
  {
    slug: "illicit-affairs",
    title: "illicit affairs",
    eraId: "folklore",
    youtubeId: "MLV2SJKWk4M",
    moods: { heartbreak: 0.7, anger: 0.25, nostalgia: 0.3, joy: 0.15, calm: 0.25, defiance: 0.2, longing: 0.8, catharsis: 0.8 },
    energy: 0.4,
    valence: 0.25,
    useCase: ["a secret world one person wide", "the ruin under the high", "erasing yourself for someone"],
    oneLiner: "An affair anatomized in second person, curdling from instructions into an indictment and a bridge-scream.",
  },
  {
    slug: "invisible-string",
    title: "invisible string",
    eraId: "folklore",
    youtubeId: "OuFnpmGwg5k",
    moods: { heartbreak: 0.05, anger: 0.02, nostalgia: 0.7, joy: 0.65, calm: 0.7, defiance: 0.05, longing: 0.55, catharsis: 0.6 },
    energy: 0.4,
    valence: 0.8,
    useCase: ["every wrong turn now looks like fate", "gratitude for the detours", "thanking even the old wounds"],
    oneLiner: "A fate song where every detour reads, in hindsight, as one gold string pulling two people together.",
  },
  {
    slug: "mad-woman",
    title: "mad woman",
    eraId: "folklore",
    youtubeId: "6DP4q_1EgQQ",
    moods: { heartbreak: 0.2, anger: 0.85, nostalgia: 0.1, joy: 0.1, calm: 0.1, defiance: 0.9, longing: 0.15, catharsis: 0.8 },
    energy: 0.55,
    valence: 0.3,
    useCase: ["called crazy until you become it", "female rage with teeth", "refusing the no-win trap"],
    oneLiner: "The angriest song on the quietest album: gaslight a woman into the witch role and she’ll play it with teeth.",
  },
  {
    slug: "epiphany",
    title: "epiphany",
    eraId: "folklore",
    youtubeId: "DUnDkI7l9LQ",
    moods: { heartbreak: 0.6, anger: 0.05, nostalgia: 0.5, joy: 0.05, calm: 0.5, defiance: 0.1, longing: 0.6, catharsis: 0.75 },
    energy: 0.25,
    valence: 0.25,
    useCase: ["things too heavy to say out loud", "honoring frontline workers", "trauma carried across generations"],
    oneLiner: "Her grandfather’s war and a 2020 hospital ward in one hymn: some things can only be slept off in dreams.",
  },
  {
    slug: "betty",
    title: "betty",
    eraId: "folklore",
    youtubeId: "6TAPqXkZW_I",
    moods: { heartbreak: 0.35, anger: 0.1, nostalgia: 0.55, joy: 0.5, calm: 0.35, defiance: 0.2, longing: 0.75, catharsis: 0.6 },
    energy: 0.55,
    valence: 0.55,
    useCase: ["a doorstep apology you owe", "teenage recklessness and regret", "betting everything on forgiveness"],
    oneLiner: "James’s harmonica-flavored apology: a seventeen-year-old grovels at a party, and the answer stays unwritten.",
  },
  {
    slug: "peace",
    title: "peace",
    eraId: "folklore",
    youtubeId: "HpxX4ZE4KWE",
    moods: { heartbreak: 0.3, anger: 0.05, nostalgia: 0.25, joy: 0.4, calm: 0.5, defiance: 0.2, longing: 0.8, catharsis: 0.7 },
    energy: 0.3,
    valence: 0.5,
    useCase: ["offering everything but a normal life", "loving someone under permanent siege", "honesty about what you can’t give"],
    oneLiner: "A pre-nup of the soul: she can promise devotion, loyalty, and fire — but never, ever peace.",
  },
  {
    slug: "hoax",
    title: "hoax",
    eraId: "folklore",
    youtubeId: "ryLGxpjwAhM",
    moods: { heartbreak: 0.8, anger: 0.15, nostalgia: 0.3, joy: 0.05, calm: 0.4, defiance: 0.1, longing: 0.7, catharsis: 0.7 },
    energy: 0.2,
    valence: 0.15,
    useCase: ["staying faithful to what wounds you", "a barefoot walk back anyway", "braided, composite grief"],
    oneLiner: "A bleak piano ending: choosing a love that hurts over every painless alternative on offer.",
  },
  {
    slug: "the-lakes",
    title: "the lakes",
    eraId: "folklore",
    youtubeId: "tOHcAc3r2kw",
    moods: { heartbreak: 0.2, anger: 0.2, nostalgia: 0.55, joy: 0.4, calm: 0.7, defiance: 0.4, longing: 0.8, catharsis: 0.6 },
    energy: 0.35,
    valence: 0.5,
    useCase: ["retiring from the discourse", "escaping somewhere with no wifi", "taking the one person who matters"],
    oneLiner: "A Lake District escape fantasy: leave the hunters and clowns online, take the muse, grow roses.",
  },
  {
    slug: "willow",
    title: "willow",
    eraId: "evermore",
    youtubeId: "RsEZmictANA",
  },
  {
    slug: "champagne-problems",
    title: "champagne problems",
    eraId: "evermore",
    youtubeId: "wMpqCRF7TKg",
  },
  {
    slug: "gold-rush",
    title: "gold rush",
    eraId: "evermore",
    youtubeId: "Pz-f9mM3Ms8",
  },
  {
    slug: "tis-the-damn-season",
    title: "'tis the damn season",
    eraId: "evermore",
    youtubeId: "WuvhOD-mP8M",
  },
  {
    slug: "tolerate-it",
    title: "tolerate it",
    eraId: "evermore",
    youtubeId: "ukxEKY_7MOc",
  },
  {
    slug: "no-body-no-crime",
    title: "no body, no crime",
    eraId: "evermore",
    youtubeId: "IEPomqor2A8",
  },
  {
    slug: "happiness",
    title: "happiness",
    eraId: "evermore",
    youtubeId: "tP4TTgt4nb0",
  },
  {
    slug: "dorothea",
    title: "dorothea",
    eraId: "evermore",
    youtubeId: "zI4DS5GmQWE",
  },
  {
    slug: "coney-island",
    title: "coney island",
    eraId: "evermore",
    youtubeId: "c_p_TBaHvos",
  },
  {
    slug: "ivy",
    title: "ivy",
    eraId: "evermore",
    youtubeId: "9nIOx-ezlzA",
  },
  {
    slug: "cowboy-like-me",
    title: "cowboy like me",
    eraId: "evermore",
    youtubeId: "YPlNBb6I8qU",
  },
  {
    slug: "long-story-short",
    title: "long story short",
    eraId: "evermore",
    youtubeId: "rqQHa2HcGtM",
  },
  {
    slug: "marjorie",
    title: "marjorie",
    eraId: "evermore",
    youtubeId: "hP6QpMeSG6s",
  },
  {
    slug: "closure",
    title: "closure",
    eraId: "evermore",
    youtubeId: "AIFnKqIeEdY",
  },
  {
    slug: "evermore",
    title: "evermore",
    eraId: "evermore",
    youtubeId: "EXLgZZE072g",
  },
  {
    slug: "right-where-you-left-me",
    title: "right where you left me",
    eraId: "evermore",
    youtubeId: "Ur_wAcYDnuA",
  },
  {
    slug: "its-time-to-go",
    title: "it's time to go",
    eraId: "evermore",
    youtubeId: "1iRbIYkccgw",
  },
  {
    slug: "lavender-haze",
    title: "Lavender Haze",
    eraId: "midnights",
    youtubeId: "h8DLofLM7No",
  },
  {
    slug: "maroon",
    title: "Maroon",
    eraId: "midnights",
    youtubeId: "lvHZjvIyqsk",
  },
  {
    slug: "anti-hero",
    title: "Anti-Hero",
    eraId: "midnights",
    youtubeId: "b1kbLwvqugk",
  },
  {
    slug: "snow-on-the-beach",
    title: "Snow on the Beach",
    eraId: "midnights",
    youtubeId: "_p0jeMjTccw",
  },
  {
    slug: "youre-on-your-own-kid",
    title: "You're on Your Own, Kid",
    eraId: "midnights",
    youtubeId: "7Gbg6Z70J7E",
  },
  {
    slug: "midnight-rain",
    title: "Midnight Rain",
    eraId: "midnights",
    youtubeId: "Odh9ddPUkEY",
  },
  {
    slug: "question",
    title: "Question...?",
    eraId: "midnights",
    youtubeId: "xxrf_QBD5DE",
  },
  {
    slug: "vigilante-shit",
    title: "Vigilante Shit",
    eraId: "midnights",
    youtubeId: "Uoey4W_3bos",
  },
  {
    slug: "bejeweled",
    title: "Bejeweled",
    eraId: "midnights",
    youtubeId: "b7QlX3yR2xs",
  },
  {
    slug: "labyrinth",
    title: "Labyrinth",
    eraId: "midnights",
    youtubeId: "xTXsKMXUi7w",
  },
  {
    slug: "karma",
    title: "Karma",
    eraId: "midnights",
    youtubeId: "rg18Kf4en2o",
  },
  {
    slug: "sweet-nothing",
    title: "Sweet Nothing",
    eraId: "midnights",
    youtubeId: "rn0brgg2BpI",
  },
  {
    slug: "mastermind",
    title: "Mastermind",
    eraId: "midnights",
    youtubeId: "Tmz1lz0zcLQ",
  },
  {
    slug: "the-great-war",
    title: "The Great War",
    eraId: "midnights",
    youtubeId: "iFX6_9h7th0",
  },
  {
    slug: "bigger-than-the-whole-sky",
    title: "Bigger Than the Whole Sky",
    eraId: "midnights",
    youtubeId: "l8Tps3PITx4",
  },
  {
    slug: "paris",
    title: "Paris",
    eraId: "midnights",
    youtubeId: "ySZGZrcqvr4",
  },
  {
    slug: "high-infidelity",
    title: "High Infidelity",
    eraId: "midnights",
    youtubeId: "-qee6dFKlw4",
  },
  {
    slug: "glitch",
    title: "Glitch",
    eraId: "midnights",
    youtubeId: "Y2a73EvnZ4s",
  },
  {
    slug: "wouldve-couldve-shouldve",
    title: "Would've, Could've, Should've",
    eraId: "midnights",
    youtubeId: "B-MfwP_RmHY",
  },
  {
    slug: "dear-reader",
    title: "Dear Reader",
    eraId: "midnights",
    youtubeId: "X0Jti9F-oQA",
  },
  {
    slug: "hits-different",
    title: "Hits Different",
    eraId: "midnights",
    youtubeId: "_f4yoKJL7IQ",
  },
  {
    slug: "youre-losing-me",
    title: "You're Losing Me",
    eraId: "midnights",
    youtubeId: "pQq9eP5OFhw",
  },
  {
    slug: "fortnight",
    title: "Fortnight",
    eraId: "ttpd",
    youtubeId: "q3zqJs7JUCQ",
  },
  {
    slug: "the-tortured-poets-department",
    title: "The Tortured Poets Department",
    eraId: "ttpd",
    youtubeId: "RQMz4JDbtmI",
  },
  {
    slug: "my-boy-only-breaks-his-favorite-toys",
    title: "My Boy Only Breaks His Favorite Toys",
    eraId: "ttpd",
    youtubeId: "wRKXAAV6jh4",
  },
  {
    slug: "down-bad",
    title: "Down Bad",
    eraId: "ttpd",
    youtubeId: "EVbtjaWXQVg",
  },
  {
    slug: "so-long-london",
    title: "So Long, London",
    eraId: "ttpd",
    youtubeId: "CCUr2pNJft4",
  },
  {
    slug: "but-daddy-i-love-him",
    title: "But Daddy I Love Him",
    eraId: "ttpd",
    youtubeId: "U2W173hRfyA",
  },
  {
    slug: "fresh-out-the-slammer",
    title: "Fresh Out the Slammer",
    eraId: "ttpd",
    youtubeId: "0EKbEP2L32M",
  },
  {
    slug: "florida",
    title: "Florida!!!",
    eraId: "ttpd",
    youtubeId: "uEssK8o3jKg",
  },
  {
    slug: "guilty-as-sin",
    title: "Guilty as Sin?",
    eraId: "ttpd",
    youtubeId: "OOYlWF6V8t8",
  },
  {
    slug: "whos-afraid-of-little-old-me",
    title: "Who's Afraid of Little Old Me?",
    eraId: "ttpd",
    youtubeId: "vOZFiX6hDXQ",
  },
  {
    slug: "i-can-fix-him-no-really-i-can",
    title: "I Can Fix Him (No Really I Can)",
    eraId: "ttpd",
    youtubeId: "OKWfv-x2rdU",
  },
  {
    slug: "loml",
    title: "loml",
    eraId: "ttpd",
    youtubeId: "GZ4vaTRn0HU",
  },
  {
    slug: "i-can-do-it-with-a-broken-heart",
    title: "I Can Do It with a Broken Heart",
    eraId: "ttpd",
    youtubeId: "Sl6en1NPTYM",
  },
  {
    slug: "the-smallest-man-who-ever-lived",
    title: "The Smallest Man Who Ever Lived",
    eraId: "ttpd",
    youtubeId: "Atdzfj8LcuY",
  },
  {
    slug: "the-alchemy",
    title: "The Alchemy",
    eraId: "ttpd",
    youtubeId: "iMMUAd66vxo",
  },
  {
    slug: "clara-bow",
    title: "Clara Bow",
    eraId: "ttpd",
    youtubeId: "fcVUbmdQfaE",
  },
  {
    slug: "the-black-dog",
    title: "The Black Dog",
    eraId: "ttpd",
    youtubeId: "56TZ3B8Qxsk",
  },
  {
    slug: "imgonnagetyouback",
    title: "imgonnagetyouback",
    eraId: "ttpd",
    youtubeId: "SBGdvxi2JmU",
  },
  {
    slug: "the-albatross",
    title: "The Albatross",
    eraId: "ttpd",
    youtubeId: "4wOsiM2T_xc",
  },
  {
    slug: "chloe-or-sam-or-sophia-or-marcus",
    title: "Chloe or Sam or Sophia or Marcus",
    eraId: "ttpd",
    youtubeId: "gOtOWeD9YJk",
  },
  {
    slug: "how-did-it-end",
    title: "How Did It End?",
    eraId: "ttpd",
    youtubeId: "O3wlMR0y4a4",
  },
  {
    slug: "so-high-school",
    title: "So High School",
    eraId: "ttpd",
    youtubeId: "w-FkV0EM_CU",
  },
  {
    slug: "i-hate-it-here",
    title: "I Hate It Here",
    eraId: "ttpd",
    youtubeId: "BpkmUfv1I4Q",
  },
  {
    slug: "thank-you-aimee",
    title: "thanK you aIMee",
    eraId: "ttpd",
    youtubeId: "oaBJlKXBvjk",
  },
  {
    slug: "i-look-in-peoples-windows",
    title: "I Look in People's Windows",
    eraId: "ttpd",
    youtubeId: "6HIA7ouBfGY",
  },
  {
    slug: "the-prophecy",
    title: "The Prophecy",
    eraId: "ttpd",
    youtubeId: "_PsBoqNwYo4",
  },
  {
    slug: "cassandra",
    title: "Cassandra",
    eraId: "ttpd",
    youtubeId: "0hYY86DmqPY",
  },
  {
    slug: "peter",
    title: "Peter",
    eraId: "ttpd",
    youtubeId: "Mxxswu7V1Us",
  },
  {
    slug: "the-bolter",
    title: "The Bolter",
    eraId: "ttpd",
    youtubeId: "bAi80EylyXQ",
  },
  {
    slug: "robin",
    title: "Robin",
    eraId: "ttpd",
    youtubeId: "FQyEZZPbOb0",
  },
  {
    slug: "the-manuscript",
    title: "The Manuscript",
    eraId: "ttpd",
    youtubeId: "iY6Qhlua8Zw",
  },
  {
    slug: "the-fate-of-ophelia",
    title: "The Fate of Ophelia",
    eraId: "tloas",
    youtubeId: "ko70cExuzZM",
  },
  {
    slug: "elizabeth-taylor",
    title: "Elizabeth Taylor",
    eraId: "tloas",
    youtubeId: "WqbJT_vC0rs",
  },
  {
    slug: "opalite",
    title: "Opalite",
    eraId: "tloas",
    youtubeId: "1FVF-9KQiPo",
  },
  {
    slug: "father-figure",
    title: "Father Figure",
    eraId: "tloas",
    youtubeId: "98SmlWOKuME",
  },
  {
    slug: "eldest-daughter",
    title: "Eldest Daughter",
    eraId: "tloas",
    youtubeId: "HwQnW_ZRKhc",
  },
  {
    slug: "ruin-the-friendship",
    title: "Ruin the Friendship",
    eraId: "tloas",
    youtubeId: "WQCPl5rTMDQ",
  },
  {
    slug: "actually-romantic",
    title: "Actually Romantic",
    eraId: "tloas",
    youtubeId: "FnEg1RgmqO4",
  },
  {
    slug: "wish-list",
    title: "Wish List",
    eraId: "tloas",
    youtubeId: "wqgUzLHgNMI",
  },
  {
    slug: "wood",
    title: "Wood",
    eraId: "tloas",
    youtubeId: "6m50keINEOI",
  },
  {
    slug: "cancelled",
    title: "Cancelled!",
    eraId: "tloas",
    youtubeId: "F-5XoUZ42Tc",
  },
  {
    slug: "honey",
    title: "Honey",
    eraId: "tloas",
    youtubeId: "4-EzK5UB40U",
  },
  {
    slug: "the-life-of-a-showgirl-title-track",
    title: "The Life of a Showgirl",
    eraId: "tloas",
    youtubeId: "OU6362Nggg0",
  },
];
