// GENERATED FILE — do not hand-edit.
// Produced by scripts/sync-song-moods.mjs from supabase/seed/tracks/**
// (the song list) merged with supabase/seed/song-moods/** (the mood scores).
// Re-run that script after seed changes; don't edit this file directly.
//
// 244 songs, 0 scored.

import type { SongMood } from './types';

export const SONG_MOODS: SongMood[] = [
  {
    slug: "tim-mcgraw",
    title: "Tim McGraw",
    eraId: "debut",
    youtubeId: "GkD20ajVxnY",
  },
  {
    slug: "picture-to-burn",
    title: "Picture to Burn",
    eraId: "debut",
    youtubeId: "yCMqcFAigRg",
  },
  {
    slug: "teardrops-on-my-guitar",
    title: "Teardrops on My Guitar",
    eraId: "debut",
    youtubeId: "xKCek6_dB0M",
  },
  {
    slug: "a-place-in-this-world",
    title: "A Place in This World",
    eraId: "debut",
    youtubeId: "_FNQ5qLuLjA",
  },
  {
    slug: "cold-as-you",
    title: "Cold as You",
    eraId: "debut",
    youtubeId: "aGvIwzgJ9hU",
  },
  {
    slug: "the-outside",
    title: "The Outside",
    eraId: "debut",
    youtubeId: "IAeicVet6SU",
  },
  {
    slug: "tied-together-with-a-smile",
    title: "Tied Together with a Smile",
    eraId: "debut",
    youtubeId: "aCVHGH5sO0c",
  },
  {
    slug: "stay-beautiful",
    title: "Stay Beautiful",
    eraId: "debut",
    youtubeId: "TQ9haUkCV-M",
  },
  {
    slug: "shouldve-said-no",
    title: "Should've Said No",
    eraId: "debut",
    youtubeId: "v9bxXO9fj98",
  },
  {
    slug: "marys-song-oh-my-my-my",
    title: "Mary's Song (Oh My My My)",
    eraId: "debut",
    youtubeId: "9TCRiGA1A2U",
  },
  {
    slug: "our-song",
    title: "Our Song",
    eraId: "debut",
    youtubeId: "Jb2stN7kH28",
  },
  {
    slug: "im-only-me-when-im-with-you",
    title: "I'm Only Me When I'm with You",
    eraId: "debut",
    youtubeId: "AlTfYj7q5gQ",
  },
  {
    slug: "invisible",
    title: "Invisible",
    eraId: "debut",
    youtubeId: "IiWI7qG8Jpc",
  },
  {
    slug: "a-perfectly-good-heart",
    title: "A Perfectly Good Heart",
    eraId: "debut",
    youtubeId: "mbs84V9S5Lc",
  },
  {
    slug: "fearless",
    title: "Fearless",
    eraId: "fearless",
    youtubeId: "7lLigiVgJsE",
  },
  {
    slug: "fifteen",
    title: "Fifteen",
    eraId: "fearless",
    youtubeId: "rLCol1C3ouc",
  },
  {
    slug: "love-story",
    title: "Love Story",
    eraId: "fearless",
    youtubeId: "aXzVF3XeS8M",
  },
  {
    slug: "hey-stephen",
    title: "Hey Stephen",
    eraId: "fearless",
    youtubeId: "tMhiHrL7rPE",
  },
  {
    slug: "white-horse",
    title: "White Horse",
    eraId: "fearless",
    youtubeId: "9-rKvhsjwKU",
  },
  {
    slug: "you-belong-with-me",
    title: "You Belong with Me",
    eraId: "fearless",
    youtubeId: "vwp8Ur6tO-8",
  },
  {
    slug: "breathe",
    title: "Breathe",
    eraId: "fearless",
    youtubeId: "qsUK-BG5OQQ",
  },
  {
    slug: "tell-me-why",
    title: "Tell Me Why",
    eraId: "fearless",
    youtubeId: "cwFbq-70EwE",
  },
  {
    slug: "youre-not-sorry",
    title: "You're Not Sorry",
    eraId: "fearless",
    youtubeId: "DNaSlUYIXBg",
  },
  {
    slug: "the-way-i-loved-you",
    title: "The Way I Loved You",
    eraId: "fearless",
    youtubeId: "DlexmDDSDZ0",
  },
  {
    slug: "forever-and-always",
    title: "Forever & Always",
    eraId: "fearless",
    youtubeId: "T-41vMWQTUA",
  },
  {
    slug: "the-best-day",
    title: "The Best Day",
    eraId: "fearless",
    youtubeId: "KZeI9I875Ig",
  },
  {
    slug: "change",
    title: "Change",
    eraId: "fearless",
    youtubeId: "jwWR1cQTKyw",
  },
  {
    slug: "jump-then-fall",
    title: "Jump Then Fall",
    eraId: "fearless",
    youtubeId: "vUHDR6Rg3Y4",
  },
  {
    slug: "untouchable",
    title: "Untouchable",
    eraId: "fearless",
    youtubeId: "8bNlGwnEUAs",
  },
  {
    slug: "come-in-with-the-rain",
    title: "Come In with the Rain",
    eraId: "fearless",
    youtubeId: "ePjcjLRHPOo",
  },
  {
    slug: "superstar",
    title: "Superstar",
    eraId: "fearless",
    youtubeId: "IsCik8wznlU",
  },
  {
    slug: "the-other-side-of-the-door",
    title: "The Other Side of the Door",
    eraId: "fearless",
    youtubeId: "425n1NoRtgA",
  },
  {
    slug: "today-was-a-fairytale",
    title: "Today Was a Fairytale",
    eraId: "fearless",
    youtubeId: "xSWVPqnKcXQ",
  },
  {
    slug: "you-all-over-me",
    title: "You All Over Me",
    eraId: "fearless",
    youtubeId: "1uKi3ZD75RE",
  },
  {
    slug: "mr-perfectly-fine",
    title: "Mr. Perfectly Fine",
    eraId: "fearless",
    youtubeId: "rFjJs6ZjPe8",
  },
  {
    slug: "we-were-happy",
    title: "We Were Happy",
    eraId: "fearless",
    youtubeId: "seU5y5EgIwk",
  },
  {
    slug: "thats-when",
    title: "That's When",
    eraId: "fearless",
    youtubeId: "aOa6D6ku3dM",
  },
  {
    slug: "dont-you",
    title: "Don't You",
    eraId: "fearless",
    youtubeId: "dHdAN4FXzmc",
  },
  {
    slug: "bye-bye-baby",
    title: "Bye Bye Baby",
    eraId: "fearless",
    youtubeId: "yuFuwXd-B9E",
  },
  {
    slug: "mine",
    title: "Mine",
    eraId: "speak-now",
    youtubeId: "oxNLRqMJMZk",
  },
  {
    slug: "sparks-fly",
    title: "Sparks Fly",
    eraId: "speak-now",
    youtubeId: "UlFrV5GJA_4",
  },
  {
    slug: "back-to-december",
    title: "Back to December",
    eraId: "speak-now",
    youtubeId: "qc2Z-OX9wnc",
  },
  {
    slug: "speak-now",
    title: "Speak Now",
    eraId: "speak-now",
    youtubeId: "JlZnvyBqceY",
  },
  {
    slug: "dear-john",
    title: "Dear John",
    eraId: "speak-now",
    youtubeId: "N-FYySSy0rM",
  },
  {
    slug: "mean",
    title: "Mean",
    eraId: "speak-now",
    youtubeId: "8AR1dKawCi8",
  },
  {
    slug: "the-story-of-us",
    title: "The Story of Us",
    eraId: "speak-now",
    youtubeId: "pRhWAXg4xek",
  },
  {
    slug: "never-grow-up",
    title: "Never Grow Up",
    eraId: "speak-now",
    youtubeId: "maEVfpxDB8k",
  },
  {
    slug: "enchanted",
    title: "Enchanted",
    eraId: "speak-now",
    youtubeId: "igIfiqqVHtA",
  },
  {
    slug: "better-than-revenge",
    title: "Better Than Revenge",
    eraId: "speak-now",
    youtubeId: "EH70M5OeS4o",
  },
  {
    slug: "innocent",
    title: "Innocent",
    eraId: "speak-now",
    youtubeId: "vO6JqQpJboY",
  },
  {
    slug: "haunted",
    title: "Haunted",
    eraId: "speak-now",
    youtubeId: "4cC6fw8EqWU",
  },
  {
    slug: "last-kiss",
    title: "Last Kiss",
    eraId: "speak-now",
    youtubeId: "idWma942CUI",
  },
  {
    slug: "long-live",
    title: "Long Live",
    eraId: "speak-now",
    youtubeId: "F5TMU6916U8",
  },
  {
    slug: "ours",
    title: "Ours",
    eraId: "speak-now",
    youtubeId: "PH8Uc0Z_KRY",
  },
  {
    slug: "if-this-was-a-movie",
    title: "If This Was a Movie",
    eraId: "speak-now",
    youtubeId: "9wZEx9A8p9k",
  },
  {
    slug: "superman",
    title: "Superman",
    eraId: "speak-now",
    youtubeId: "Fn0er7H1Dm0",
  },
  {
    slug: "electric-touch",
    title: "Electric Touch",
    eraId: "speak-now",
    youtubeId: "hMPK2vNXr-E",
  },
  {
    slug: "when-emma-falls-in-love",
    title: "When Emma Falls in Love",
    eraId: "speak-now",
    youtubeId: "IYqgVYjN3Go",
  },
  {
    slug: "i-can-see-you",
    title: "I Can See You",
    eraId: "speak-now",
    youtubeId: "lVkKLf4DCn8",
  },
  {
    slug: "castles-crumbling",
    title: "Castles Crumbling",
    eraId: "speak-now",
    youtubeId: "HtDriYDIhRs",
  },
  {
    slug: "foolish-one",
    title: "Foolish One",
    eraId: "speak-now",
    youtubeId: "6-x1AlDudZw",
  },
  {
    slug: "timeless",
    title: "Timeless",
    eraId: "speak-now",
    youtubeId: "osmzwWw4RYM",
  },
  {
    slug: "state-of-grace",
    title: "State of Grace",
    eraId: "red",
  },
  {
    slug: "red",
    title: "Red",
    eraId: "red",
  },
  {
    slug: "treacherous",
    title: "Treacherous",
    eraId: "red",
  },
  {
    slug: "i-knew-you-were-trouble",
    title: "I Knew You Were Trouble",
    eraId: "red",
  },
  {
    slug: "all-too-well",
    title: "All Too Well",
    eraId: "red",
  },
  {
    slug: "22",
    title: "22",
    eraId: "red",
  },
  {
    slug: "i-almost-do",
    title: "I Almost Do",
    eraId: "red",
  },
  {
    slug: "we-are-never-ever-getting-back-together",
    title: "We Are Never Ever Getting Back Together",
    eraId: "red",
  },
  {
    slug: "stay-stay-stay",
    title: "Stay Stay Stay",
    eraId: "red",
  },
  {
    slug: "the-last-time",
    title: "The Last Time",
    eraId: "red",
  },
  {
    slug: "holy-ground",
    title: "Holy Ground",
    eraId: "red",
  },
  {
    slug: "sad-beautiful-tragic",
    title: "Sad Beautiful Tragic",
    eraId: "red",
  },
  {
    slug: "the-lucky-one",
    title: "The Lucky One",
    eraId: "red",
  },
  {
    slug: "everything-has-changed",
    title: "Everything Has Changed",
    eraId: "red",
  },
  {
    slug: "starlight",
    title: "Starlight",
    eraId: "red",
  },
  {
    slug: "begin-again",
    title: "Begin Again",
    eraId: "red",
  },
  {
    slug: "the-moment-i-knew",
    title: "The Moment I Knew",
    eraId: "red",
  },
  {
    slug: "come-back-be-here",
    title: "Come Back... Be Here",
    eraId: "red",
  },
  {
    slug: "girl-at-home",
    title: "Girl at Home",
    eraId: "red",
  },
  {
    slug: "ronan",
    title: "Ronan",
    eraId: "red",
  },
  {
    slug: "better-man",
    title: "Better Man",
    eraId: "red",
  },
  {
    slug: "nothing-new",
    title: "Nothing New",
    eraId: "red",
  },
  {
    slug: "babe",
    title: "Babe",
    eraId: "red",
  },
  {
    slug: "message-in-a-bottle",
    title: "Message in a Bottle",
    eraId: "red",
  },
  {
    slug: "i-bet-you-think-about-me",
    title: "I Bet You Think About Me",
    eraId: "red",
  },
  {
    slug: "forever-winter",
    title: "Forever Winter",
    eraId: "red",
  },
  {
    slug: "run",
    title: "Run",
    eraId: "red",
  },
  {
    slug: "the-very-first-night",
    title: "The Very First Night",
    eraId: "red",
  },
  {
    slug: "all-too-well-10-minute-version",
    title: "All Too Well (10 Minute Version)",
    eraId: "red",
  },
  {
    slug: "welcome-to-new-york",
    title: "Welcome to New York",
    eraId: "1989",
    youtubeId: "FsGdznlfE2U",
  },
  {
    slug: "blank-space",
    title: "Blank Space",
    eraId: "1989",
    youtubeId: "e-ORhEE9VVg",
  },
  {
    slug: "style",
    title: "Style",
    eraId: "1989",
    youtubeId: "2JgvVfOfoWI",
  },
  {
    slug: "out-of-the-woods",
    title: "Out of the Woods",
    eraId: "1989",
    youtubeId: "JLf9q36UsBk",
  },
  {
    slug: "all-you-had-to-do-was-stay",
    title: "All You Had to Do Was Stay",
    eraId: "1989",
    youtubeId: "_Usd5X5XJXM",
  },
  {
    slug: "shake-it-off",
    title: "Shake It Off",
    eraId: "1989",
    youtubeId: "nfWlot6h_JM",
  },
  {
    slug: "i-wish-you-would",
    title: "I Wish You Would",
    eraId: "1989",
    youtubeId: "89aQIli8aVU",
  },
  {
    slug: "bad-blood",
    title: "Bad Blood",
    eraId: "1989",
    youtubeId: "QcIy9NiNbmo",
  },
  {
    slug: "wildest-dreams",
    title: "Wildest Dreams",
    eraId: "1989",
    youtubeId: "IdneKLhsWOQ",
  },
  {
    slug: "how-you-get-the-girl",
    title: "How You Get the Girl",
    eraId: "1989",
    youtubeId: "XQh8zhmTtBg",
  },
  {
    slug: "this-love",
    title: "This Love",
    eraId: "1989",
    youtubeId: "r9VzPf8a4kI",
  },
  {
    slug: "i-know-places",
    title: "I Know Places",
    eraId: "1989",
    youtubeId: "0jTGzm-6cYE",
  },
  {
    slug: "clean",
    title: "Clean",
    eraId: "1989",
    youtubeId: "AppsjTInqiw",
  },
  {
    slug: "wonderland",
    title: "Wonderland",
    eraId: "1989",
    youtubeId: "E048L9PaZsk",
  },
  {
    slug: "you-are-in-love",
    title: "You Are in Love",
    eraId: "1989",
    youtubeId: "a_zwscPcDGM",
  },
  {
    slug: "new-romantics",
    title: "New Romantics",
    eraId: "1989",
    youtubeId: "3-BcH7KowGE",
  },
  {
    slug: "slut",
    title: "\"Slut!\"",
    eraId: "1989",
    youtubeId: "qrxsceexTBw",
  },
  {
    slug: "say-dont-go",
    title: "Say Don't Go",
    eraId: "1989",
    youtubeId: "C-z-IckrQK8",
  },
  {
    slug: "now-that-we-dont-talk",
    title: "Now That We Don't Talk",
    eraId: "1989",
    youtubeId: "yF4ulRTCn44",
  },
  {
    slug: "suburban-legends",
    title: "Suburban Legends",
    eraId: "1989",
    youtubeId: "ZGBPKYbzSXs",
  },
  {
    slug: "is-it-over-now",
    title: "Is It Over Now?",
    eraId: "1989",
    youtubeId: "tNxUxm3-658",
  },
  {
    slug: "ready-for-it",
    title: "...Ready for It?",
    eraId: "reputation",
    youtubeId: "T62maKYX9tU",
  },
  {
    slug: "end-game",
    title: "End Game",
    eraId: "reputation",
    youtubeId: "dfnCAmr569k",
  },
  {
    slug: "i-did-something-bad",
    title: "I Did Something Bad",
    eraId: "reputation",
    youtubeId: "xYLxUJ9v6KU",
  },
  {
    slug: "dont-blame-me",
    title: "Don't Blame Me",
    eraId: "reputation",
    youtubeId: "kRJKB291Z1g",
  },
  {
    slug: "delicate",
    title: "Delicate",
    eraId: "reputation",
    youtubeId: "tCXGJQYZ9JA",
  },
  {
    slug: "look-what-you-made-me-do",
    title: "Look What You Made Me Do",
    eraId: "reputation",
    youtubeId: "3tmd-ClpJxA",
  },
  {
    slug: "so-it-goes",
    title: "So It Goes...",
    eraId: "reputation",
    youtubeId: "iAv1Y1YIwm8",
  },
  {
    slug: "gorgeous",
    title: "Gorgeous",
    eraId: "reputation",
    youtubeId: "EUoe7cf0HYw",
  },
  {
    slug: "getaway-car",
    title: "Getaway Car",
    eraId: "reputation",
    youtubeId: "FhPLQVlUiNQ",
  },
  {
    slug: "king-of-my-heart",
    title: "King of My Heart",
    eraId: "reputation",
    youtubeId: "5U7bF68xcRg",
  },
  {
    slug: "dancing-with-our-hands-tied",
    title: "Dancing with Our Hands Tied",
    eraId: "reputation",
    youtubeId: "erGyUphZSt8",
  },
  {
    slug: "dress",
    title: "Dress",
    eraId: "reputation",
    youtubeId: "FNEoPctNIUE",
  },
  {
    slug: "this-is-why-we-cant-have-nice-things",
    title: "This Is Why We Can't Have Nice Things",
    eraId: "reputation",
    youtubeId: "6Z3QJ4L1Bg0",
  },
  {
    slug: "call-it-what-you-want",
    title: "Call It What You Want",
    eraId: "reputation",
    youtubeId: "V54CEElTF_U",
  },
  {
    slug: "new-years-day",
    title: "New Year's Day",
    eraId: "reputation",
    youtubeId: "MWSn0H4qfAs",
  },
  {
    slug: "i-forgot-that-you-existed",
    title: "I Forgot That You Existed",
    eraId: "lover",
    youtubeId: "p1cEvNn88jM",
  },
  {
    slug: "cruel-summer",
    title: "Cruel Summer",
    eraId: "lover",
    youtubeId: "ic8j13piAhQ",
  },
  {
    slug: "lover",
    title: "Lover",
    eraId: "lover",
    youtubeId: "-BjZmE2gtdo",
  },
  {
    slug: "the-man",
    title: "The Man",
    eraId: "lover",
    youtubeId: "AqAJLh9wuZ0",
  },
  {
    slug: "the-archer",
    title: "The Archer",
    eraId: "lover",
    youtubeId: "8KpKc3C9V3w",
  },
  {
    slug: "i-think-he-knows",
    title: "I Think He Knows",
    eraId: "lover",
    youtubeId: "2d1wKn-oJnA",
  },
  {
    slug: "miss-americana-and-the-heartbreak-prince",
    title: "Miss Americana & the Heartbreak Prince",
    eraId: "lover",
    youtubeId: "Kwf7P2GNAVw",
  },
  {
    slug: "paper-rings",
    title: "Paper Rings",
    eraId: "lover",
    youtubeId: "8zdg-pDF10g",
  },
  {
    slug: "cornelia-street",
    title: "Cornelia Street",
    eraId: "lover",
    youtubeId: "VikHHWrgb4Y",
  },
  {
    slug: "death-by-a-thousand-cuts",
    title: "Death by a Thousand Cuts",
    eraId: "lover",
    youtubeId: "GTEFSuFfgnU",
  },
  {
    slug: "london-boy",
    title: "London Boy",
    eraId: "lover",
    youtubeId: "VsKoOH6DVys",
  },
  {
    slug: "soon-youll-get-better",
    title: "Soon You'll Get Better",
    eraId: "lover",
    youtubeId: "tMoW5G5LU08",
  },
  {
    slug: "false-god",
    title: "False God",
    eraId: "lover",
    youtubeId: "acQXa5ArHIk",
  },
  {
    slug: "you-need-to-calm-down",
    title: "You Need to Calm Down",
    eraId: "lover",
    youtubeId: "GWtfOHBF1_w",
  },
  {
    slug: "afterglow",
    title: "Afterglow",
    eraId: "lover",
    youtubeId: "8HxbqAsppwU",
  },
  {
    slug: "me",
    title: "Me!",
    eraId: "lover",
    youtubeId: "FuXNumBwDOM",
  },
  {
    slug: "its-nice-to-have-a-friend",
    title: "It's Nice to Have a Friend",
    eraId: "lover",
    youtubeId: "eaP1VswBF28",
  },
  {
    slug: "daylight",
    title: "Daylight",
    eraId: "lover",
    youtubeId: "u9raS7-NisU",
  },
  {
    slug: "the-1",
    title: "the 1",
    eraId: "folklore",
    youtubeId: "KsZ6tROaVOQ",
  },
  {
    slug: "cardigan",
    title: "cardigan",
    eraId: "folklore",
    youtubeId: "K-a8s8OLBSE",
  },
  {
    slug: "the-last-great-american-dynasty",
    title: "the last great american dynasty",
    eraId: "folklore",
    youtubeId: "2s5xdY6MCeI",
  },
  {
    slug: "exile",
    title: "exile",
    eraId: "folklore",
    youtubeId: "osdoLjUNFnA",
  },
  {
    slug: "my-tears-ricochet",
    title: "my tears ricochet",
    eraId: "folklore",
    youtubeId: "OWbDJFtHl3w",
  },
  {
    slug: "mirrorball",
    title: "mirrorball",
    eraId: "folklore",
    youtubeId: "KaM1bCuG4xo",
  },
  {
    slug: "seven",
    title: "seven",
    eraId: "folklore",
    youtubeId: "pEY-GPsru_E",
  },
  {
    slug: "august",
    title: "august",
    eraId: "folklore",
    youtubeId: "nn_0zPAfyo8",
  },
  {
    slug: "this-is-me-trying",
    title: "this is me trying",
    eraId: "folklore",
    youtubeId: "9bdLTPNrlEg",
  },
  {
    slug: "illicit-affairs",
    title: "illicit affairs",
    eraId: "folklore",
    youtubeId: "MLV2SJKWk4M",
  },
  {
    slug: "invisible-string",
    title: "invisible string",
    eraId: "folklore",
    youtubeId: "OuFnpmGwg5k",
  },
  {
    slug: "mad-woman",
    title: "mad woman",
    eraId: "folklore",
    youtubeId: "6DP4q_1EgQQ",
  },
  {
    slug: "epiphany",
    title: "epiphany",
    eraId: "folklore",
    youtubeId: "DUnDkI7l9LQ",
  },
  {
    slug: "betty",
    title: "betty",
    eraId: "folklore",
    youtubeId: "6TAPqXkZW_I",
  },
  {
    slug: "peace",
    title: "peace",
    eraId: "folklore",
    youtubeId: "HpxX4ZE4KWE",
  },
  {
    slug: "hoax",
    title: "hoax",
    eraId: "folklore",
    youtubeId: "ryLGxpjwAhM",
  },
  {
    slug: "the-lakes",
    title: "the lakes",
    eraId: "folklore",
    youtubeId: "tOHcAc3r2kw",
  },
  {
    slug: "willow",
    title: "willow",
    eraId: "evermore",
    youtubeId: "RsEZmictANA",
  },
  {
    slug: "champagne-problems",
    title: "champagne problems",
    eraId: "evermore",
    youtubeId: "wMpqCRF7TKg",
  },
  {
    slug: "gold-rush",
    title: "gold rush",
    eraId: "evermore",
    youtubeId: "Pz-f9mM3Ms8",
  },
  {
    slug: "tis-the-damn-season",
    title: "'tis the damn season",
    eraId: "evermore",
    youtubeId: "WuvhOD-mP8M",
  },
  {
    slug: "tolerate-it",
    title: "tolerate it",
    eraId: "evermore",
    youtubeId: "ukxEKY_7MOc",
  },
  {
    slug: "no-body-no-crime",
    title: "no body, no crime",
    eraId: "evermore",
    youtubeId: "IEPomqor2A8",
  },
  {
    slug: "happiness",
    title: "happiness",
    eraId: "evermore",
    youtubeId: "tP4TTgt4nb0",
  },
  {
    slug: "dorothea",
    title: "dorothea",
    eraId: "evermore",
    youtubeId: "zI4DS5GmQWE",
  },
  {
    slug: "coney-island",
    title: "coney island",
    eraId: "evermore",
    youtubeId: "c_p_TBaHvos",
  },
  {
    slug: "ivy",
    title: "ivy",
    eraId: "evermore",
    youtubeId: "9nIOx-ezlzA",
  },
  {
    slug: "cowboy-like-me",
    title: "cowboy like me",
    eraId: "evermore",
    youtubeId: "YPlNBb6I8qU",
  },
  {
    slug: "long-story-short",
    title: "long story short",
    eraId: "evermore",
    youtubeId: "rqQHa2HcGtM",
  },
  {
    slug: "marjorie",
    title: "marjorie",
    eraId: "evermore",
    youtubeId: "hP6QpMeSG6s",
  },
  {
    slug: "closure",
    title: "closure",
    eraId: "evermore",
    youtubeId: "AIFnKqIeEdY",
  },
  {
    slug: "evermore",
    title: "evermore",
    eraId: "evermore",
    youtubeId: "EXLgZZE072g",
  },
  {
    slug: "right-where-you-left-me",
    title: "right where you left me",
    eraId: "evermore",
    youtubeId: "Ur_wAcYDnuA",
  },
  {
    slug: "its-time-to-go",
    title: "it's time to go",
    eraId: "evermore",
    youtubeId: "1iRbIYkccgw",
  },
  {
    slug: "lavender-haze",
    title: "Lavender Haze",
    eraId: "midnights",
    youtubeId: "h8DLofLM7No",
  },
  {
    slug: "maroon",
    title: "Maroon",
    eraId: "midnights",
    youtubeId: "lvHZjvIyqsk",
  },
  {
    slug: "anti-hero",
    title: "Anti-Hero",
    eraId: "midnights",
    youtubeId: "b1kbLwvqugk",
  },
  {
    slug: "snow-on-the-beach",
    title: "Snow on the Beach",
    eraId: "midnights",
    youtubeId: "_p0jeMjTccw",
  },
  {
    slug: "youre-on-your-own-kid",
    title: "You're on Your Own, Kid",
    eraId: "midnights",
    youtubeId: "7Gbg6Z70J7E",
  },
  {
    slug: "midnight-rain",
    title: "Midnight Rain",
    eraId: "midnights",
    youtubeId: "Odh9ddPUkEY",
  },
  {
    slug: "question",
    title: "Question...?",
    eraId: "midnights",
    youtubeId: "xxrf_QBD5DE",
  },
  {
    slug: "vigilante-shit",
    title: "Vigilante Shit",
    eraId: "midnights",
    youtubeId: "Uoey4W_3bos",
  },
  {
    slug: "bejeweled",
    title: "Bejeweled",
    eraId: "midnights",
    youtubeId: "b7QlX3yR2xs",
  },
  {
    slug: "labyrinth",
    title: "Labyrinth",
    eraId: "midnights",
    youtubeId: "xTXsKMXUi7w",
  },
  {
    slug: "karma",
    title: "Karma",
    eraId: "midnights",
    youtubeId: "rg18Kf4en2o",
  },
  {
    slug: "sweet-nothing",
    title: "Sweet Nothing",
    eraId: "midnights",
    youtubeId: "rn0brgg2BpI",
  },
  {
    slug: "mastermind",
    title: "Mastermind",
    eraId: "midnights",
    youtubeId: "Tmz1lz0zcLQ",
  },
  {
    slug: "the-great-war",
    title: "The Great War",
    eraId: "midnights",
    youtubeId: "iFX6_9h7th0",
  },
  {
    slug: "bigger-than-the-whole-sky",
    title: "Bigger Than the Whole Sky",
    eraId: "midnights",
    youtubeId: "l8Tps3PITx4",
  },
  {
    slug: "paris",
    title: "Paris",
    eraId: "midnights",
    youtubeId: "ySZGZrcqvr4",
  },
  {
    slug: "high-infidelity",
    title: "High Infidelity",
    eraId: "midnights",
    youtubeId: "-qee6dFKlw4",
  },
  {
    slug: "glitch",
    title: "Glitch",
    eraId: "midnights",
    youtubeId: "Y2a73EvnZ4s",
  },
  {
    slug: "wouldve-couldve-shouldve",
    title: "Would've, Could've, Should've",
    eraId: "midnights",
    youtubeId: "B-MfwP_RmHY",
  },
  {
    slug: "dear-reader",
    title: "Dear Reader",
    eraId: "midnights",
    youtubeId: "X0Jti9F-oQA",
  },
  {
    slug: "hits-different",
    title: "Hits Different",
    eraId: "midnights",
    youtubeId: "_f4yoKJL7IQ",
  },
  {
    slug: "youre-losing-me",
    title: "You're Losing Me",
    eraId: "midnights",
    youtubeId: "pQq9eP5OFhw",
  },
  {
    slug: "fortnight",
    title: "Fortnight",
    eraId: "ttpd",
  },
  {
    slug: "the-tortured-poets-department",
    title: "The Tortured Poets Department",
    eraId: "ttpd",
  },
  {
    slug: "my-boy-only-breaks-his-favorite-toys",
    title: "My Boy Only Breaks His Favorite Toys",
    eraId: "ttpd",
  },
  {
    slug: "down-bad",
    title: "Down Bad",
    eraId: "ttpd",
  },
  {
    slug: "so-long-london",
    title: "So Long, London",
    eraId: "ttpd",
  },
  {
    slug: "but-daddy-i-love-him",
    title: "But Daddy I Love Him",
    eraId: "ttpd",
  },
  {
    slug: "fresh-out-the-slammer",
    title: "Fresh Out the Slammer",
    eraId: "ttpd",
  },
  {
    slug: "florida",
    title: "Florida!!!",
    eraId: "ttpd",
  },
  {
    slug: "guilty-as-sin",
    title: "Guilty as Sin?",
    eraId: "ttpd",
  },
  {
    slug: "whos-afraid-of-little-old-me",
    title: "Who's Afraid of Little Old Me?",
    eraId: "ttpd",
  },
  {
    slug: "i-can-fix-him-no-really-i-can",
    title: "I Can Fix Him (No Really I Can)",
    eraId: "ttpd",
  },
  {
    slug: "loml",
    title: "loml",
    eraId: "ttpd",
  },
  {
    slug: "i-can-do-it-with-a-broken-heart",
    title: "I Can Do It with a Broken Heart",
    eraId: "ttpd",
  },
  {
    slug: "the-smallest-man-who-ever-lived",
    title: "The Smallest Man Who Ever Lived",
    eraId: "ttpd",
  },
  {
    slug: "the-alchemy",
    title: "The Alchemy",
    eraId: "ttpd",
  },
  {
    slug: "clara-bow",
    title: "Clara Bow",
    eraId: "ttpd",
  },
  {
    slug: "the-black-dog",
    title: "The Black Dog",
    eraId: "ttpd",
  },
  {
    slug: "imgonnagetyouback",
    title: "imgonnagetyouback",
    eraId: "ttpd",
  },
  {
    slug: "the-albatross",
    title: "The Albatross",
    eraId: "ttpd",
  },
  {
    slug: "chloe-or-sam-or-sophia-or-marcus",
    title: "Chloe or Sam or Sophia or Marcus",
    eraId: "ttpd",
  },
  {
    slug: "how-did-it-end",
    title: "How Did It End?",
    eraId: "ttpd",
  },
  {
    slug: "so-high-school",
    title: "So High School",
    eraId: "ttpd",
  },
  {
    slug: "i-hate-it-here",
    title: "I Hate It Here",
    eraId: "ttpd",
  },
  {
    slug: "thank-you-aimee",
    title: "thanK you aIMee",
    eraId: "ttpd",
  },
  {
    slug: "i-look-in-peoples-windows",
    title: "I Look in People's Windows",
    eraId: "ttpd",
  },
  {
    slug: "the-prophecy",
    title: "The Prophecy",
    eraId: "ttpd",
  },
  {
    slug: "cassandra",
    title: "Cassandra",
    eraId: "ttpd",
  },
  {
    slug: "peter",
    title: "Peter",
    eraId: "ttpd",
  },
  {
    slug: "the-bolter",
    title: "The Bolter",
    eraId: "ttpd",
  },
  {
    slug: "robin",
    title: "Robin",
    eraId: "ttpd",
  },
  {
    slug: "the-manuscript",
    title: "The Manuscript",
    eraId: "ttpd",
  },
  {
    slug: "the-fate-of-ophelia",
    title: "The Fate of Ophelia",
    eraId: "tloas",
    youtubeId: "ko70cExuzZM",
  },
  {
    slug: "elizabeth-taylor",
    title: "Elizabeth Taylor",
    eraId: "tloas",
    youtubeId: "WqbJT_vC0rs",
  },
  {
    slug: "opalite",
    title: "Opalite",
    eraId: "tloas",
    youtubeId: "1FVF-9KQiPo",
  },
  {
    slug: "father-figure",
    title: "Father Figure",
    eraId: "tloas",
    youtubeId: "98SmlWOKuME",
  },
  {
    slug: "eldest-daughter",
    title: "Eldest Daughter",
    eraId: "tloas",
    youtubeId: "HwQnW_ZRKhc",
  },
  {
    slug: "ruin-the-friendship",
    title: "Ruin the Friendship",
    eraId: "tloas",
    youtubeId: "WQCPl5rTMDQ",
  },
  {
    slug: "actually-romantic",
    title: "Actually Romantic",
    eraId: "tloas",
    youtubeId: "FnEg1RgmqO4",
  },
  {
    slug: "wish-list",
    title: "Wish List",
    eraId: "tloas",
    youtubeId: "wqgUzLHgNMI",
  },
  {
    slug: "wood",
    title: "Wood",
    eraId: "tloas",
    youtubeId: "6m50keINEOI",
  },
  {
    slug: "cancelled",
    title: "Cancelled!",
    eraId: "tloas",
    youtubeId: "F-5XoUZ42Tc",
  },
  {
    slug: "honey",
    title: "Honey",
    eraId: "tloas",
    youtubeId: "4-EzK5UB40U",
  },
  {
    slug: "the-life-of-a-showgirl-title-track",
    title: "The Life of a Showgirl",
    eraId: "tloas",
    youtubeId: "OU6362Nggg0",
  },
];
