// GENERATED FILE — do not hand-edit.
// Produced by scripts/sync-longlive-theories.mjs from supabase/seed/theories/**
// (or the live Supabase theory table when configured).
// Re-run that script after theory-seed changes; don't edit this file directly.

import type { EraId, TheoryNote } from './types';

export const THEORIES_RAW: Partial<Record<EraId, TheoryNote[]>> = {
  "1989": [
    {
      slug: "no-its-becky",
      kind: "theory",
      title: "\"no it's becky\"",
      claim: "The 2014 Tumblr joke: a photo of Taylor captioned as a girl named Becky who \"snorted marijuana at a party and died,\" answered with \"no it's becky.\" Fans ran with Becky as Taylor's alter ego — and Taylor got the joke.",
      evidence: "Born as a Tumblr exchange during her famously online 1989-era presence. Taylor canonized the meme herself by wearing a \"no its becky\" T-shirt, turning a fandom in-joke into official-adjacent lore.",
      confidence: "joke_meme",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift Wears 'no its becky' T-Shirt", url: "https://time.com/3430491/taylor-swift-internet-meme-no-its-becky-tshirt/" }, { name: "Swifties", url: "https://en.wikipedia.org/wiki/Swifties" }],
    },
    {
      slug: "1989-lowercase-liner-codes",
      kind: "easter_egg",
      title: "The lowercase inversion",
      claim: "1989's booklet flips her oldest trick: after five albums of hidden messages spelled in capitalized letters, the codes moved to the lowercase letters — and read in track order, the thirteen messages tell one continuous story.",
      evidence: "Billboard decoded and published the full 1989 set the week the album dropped — it opens \"We begin our story in New York\" and runs as a single arc through all thirteen tracks, a two-year autobiography threaded through the lyric sheets. The inversion mattered to code-watchers: new sound, new cipher. It was also the finale — the booklet codes stop entirely at reputation.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift's '1989' Liner Note Messages & Reference Guide", url: "https://www.billboard.com/music/music-news/taylor-swift-1989-liner-notes-6296676/" }, { name: "Liner notes and easter eggs: How Taylor Swift turned fandom into a scavenger hunt", url: "https://www.today.com/popculture/music/taylor-swift-easter-eggs-hidden-messages-rcna51887" }],
      relatedSlugs: ["debut:liner-notes-hidden-messages", "red:twenty-two-liner-note-code"],
    },
  ],
  "debut": [
    {
      slug: "lucky-number-13",
      kind: "easter_egg",
      title: "13, the number that runs through everything",
      claim: "Taylor treats 13 as her lucky number — born December 13, she drew it on her hand for early shows, and fans hunt for it in track sequencing, dates, and clue-drops to this day.",
      evidence: "On the record from the start: she has repeatedly explained the number (her birthday, her first album going gold in 13 weeks, seat rows and awards-show coincidences) and wore a hand-painted 13 at Fearless-era shows. Decoding-by-13 became the founding grammar of Swiftie lore.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift", url: "https://en.wikipedia.org/wiki/Taylor_Swift" }, { name: "Cultural impact of Taylor Swift", url: "https://en.wikipedia.org/wiki/Cultural_impact_of_Taylor_Swift" }],
    },
    {
      slug: "liner-notes-hidden-messages",
      kind: "easter_egg",
      title: "The liner-note code: capital letters spell secrets",
      claim: "From the debut album onward, the lyric booklets hid messages: read only the capitalized letters in each printed lyric and they spell out a secret line about the song.",
      evidence: "A confirmed, deliberate practice — the booklet codes ran from the 2006 debut through 1989 (2014) and trained the fandom to decode everything that followed. She later said the clue-planting simply moved from liner notes into videos, posts, and performances.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "A Complete History of Taylor Swift's Best Easter Eggs", url: "https://www.today.com/today/amp/rcna51887" }, { name: "Swifties", url: "https://en.wikipedia.org/wiki/Swifties" }],
    },
  ],
  "evermore": [
    {
      slug: "thirteen-backwards",
      kind: "easter_egg",
      title: "Dropped when 13 runs backwards",
      claim: "evermore arrived two days before her 31st birthday — and she said the timing was the point: she'd been excited about turning 31 \"because it's my lucky number backwards, which is why I wanted to surprise you with this now.\"",
      evidence: "Stated in her own announcement of the album: the 31/13 mirror was her framing, not a fan read. The numerology habit that started with hand-painted 13s now sets release dates.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Evermore (Taylor Swift album)", url: "https://en.wikipedia.org/wiki/Evermore_(Taylor_Swift_album)" }],
      relatedSlugs: ["debut:lucky-number-13", "folklore:woodvale"],
    },
  ],
  "fearless": [
    {
      slug: "the-best-day-liner-note-code",
      kind: "easter_egg",
      title: "A liner-note code hidden inside \"The Best Day\"",
      claim: "The 2008 Fearless CD booklet capitalized scattered letters within \"The Best Day\" lyric sheet that, read in order, spell out \"GOD BLESS ANDREA SWIFT\" — a hidden tribute to her mother.",
      evidence: "Swift used this capitalization-code technique across her early album booklets, letting fans decode a short message per song from oddly capitalized letters in the printed lyrics. For \"The Best Day\" — itself written about her mother — the decoded message names her directly, tying the song's subject to its hidden dedication.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift's 13 Best Liner Note Secret Messages", url: "https://www.billboard.com/music/music-news/taylor-swift-liner-note-secret-messages-6296379/" }],
    },
    {
      slug: "vault-track-anagram-reveal",
      kind: "easter_egg",
      title: "An anagram video unlocks the \"From the Vault\" track list",
      claim: "Before officially announcing the six \"From the Vault\" songs on Fearless (Taylor's Version), Swift posted a scrambled-letter anagram video on social media that fans raced to decode, correctly working out the titles — and a Keith Urban feature — hours ahead of the formal reveal.",
      evidence: "The teaser clip showed jumbled letters that fans reassembled into the vault-track titles; Swift confirmed the full list, including the Keith Urban duet, on April 3, 2021, six days ahead of the April 9 release. The announcement date (Feb. 11) and release date (April 9) each reduce to her frequently cited number 13 (2+11 and 4+9), a numerology pattern she has said she builds into release timing on purpose.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Fearless (Taylor's Version)", url: "https://en.wikipedia.org/wiki/Fearless_(Taylor%27s_Version)" }, { name: "Taylor Swift Reveals 'Fearless (Taylor's Version)' Track List, Including Keith Urban Duet", url: "https://www.rollingstone.com/music/music-news/taylor-swift-fearless-taylors-version-track-list-keith-urban-1150599/" }],
    },
  ],
  "folklore": [
    {
      slug: "woodvale",
      kind: "theory",
      title: "Woodvale: the third sister album that never was",
      claim: "Fans spotted the word \"Woodvale\" hidden in a folklore promo image and concluded a THIRD surprise sister album was coming after evermore. It never did.",
      evidence: "The word really was there — Taylor later explained on late-night TV that \"Woodvale\" was a working codename for folklore that mistakenly survived on a mock-up. A perfect case study: real artifact, real pattern-matching, wrong conclusion, official debunk.",
      confidence: "strong_fan_consensus",
      outcome: "debunked",
      sources: [{ name: "Evermore (Taylor Swift album)", url: "https://en.wikipedia.org/wiki/Evermore_(Taylor_Swift_album)" }],
      relatedSlugs: ["evermore:thirteen-backwards"],
    },
    {
      slug: "teenage-love-triangle",
      kind: "theory",
      title: "The teenage love triangle",
      claim: "Fans mapped \"cardigan,\" \"august,\" and \"betty\" as one story told by three narrators — Betty, Augustine, and James — and were right: Taylor confirmed the Teenage Love Triangle by name.",
      evidence: "Decoded within hours of release from shared names and mirrored details across the three lyrics; Taylor confirmed the intended triangle in interviews and the Long Pond sessions. The characters are explicitly fictional — which is what makes this the fandom's cleanest confirmed close-read.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Folklore (Taylor Swift album)", url: "https://en.wikipedia.org/wiki/Folklore_(Taylor_Swift_album)" }, { name: "cardigan (song)", url: "https://en.wikipedia.org/wiki/Cardigan_(song)" }],
    },
    {
      slug: "william-bowery",
      kind: "theory",
      title: "Who is William Bowery?",
      claim: "A never-before-seen co-writer named William Bowery appeared in the folklore credits. Fans immediately suspected a pseudonym — and in the Long Pond film Taylor confirmed it on camera.",
      evidence: "The credits were the entire clue: no such songwriter existed anywhere. The confirmation came in folklore: the long pond studio sessions, where she named the person behind the pen name. Textbook fandom arc — anomaly, theory, on-record resolution within months.",
      confidence: "confirmed_interview",
      outcome: "confirmed",
      sources: [{ name: "Folklore: The Long Pond Studio Sessions", url: "https://en.wikipedia.org/wiki/Folklore:_The_Long_Pond_Studio_Sessions" }],
    },
  ],
  "lover": [
    {
      slug: "butterfly-mural",
      kind: "easter_egg",
      title: "The butterfly mural that announced the era",
      claim: "Hours before \"ME!\" dropped in April 2019, a pastel butterfly mural by street artist Kelsey Montague appeared in Nashville — fans swarmed it, correctly reading it as the snake era molting into something new.",
      evidence: "Documented rollout stunt: the mural went up unannounced, fan detectives connected it to the countdown Taylor had posted, and she showed up at the wall herself. The butterfly-eats-snake beat inside the \"ME!\" video completed the metamorphosis arc.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "ME!", url: "https://en.wikipedia.org/wiki/Me!" }],
      relatedSlugs: ["reputation:snake-reclamation"],
    },
    {
      slug: "mastermind-doctrine",
      kind: "easter_egg",
      title: "The easter-egg doctrine, stated on the record",
      claim: "Not a theory — a confession: Taylor has said outright that she plants clues about future music years in advance, and that decoding them is a game she deliberately plays with fans.",
      evidence: "She described the practice in Lover-era interviews and later wrote it into a song (\"Mastermind\"). This record is the anchor for every other entry in this collection: the eggs are real, planted, and intended to be found — which is exactly why unconfirmed readings still need labels.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Cultural impact of Taylor Swift", url: "https://en.wikipedia.org/wiki/Cultural_impact_of_Taylor_Swift" }, { name: "Swifties", url: "https://en.wikipedia.org/wiki/Swifties" }],
      relatedSlugs: ["debut:liner-notes-hidden-messages"],
    },
    {
      slug: "me-video-chicks-painting",
      kind: "easter_egg",
      title: "The 'ME!' video predicted the album's guest stars",
      claim: "A painting of the Dixie Chicks hangs on the wall of the 'ME!' video, spotted by fans within hours and read as a collab tease. Four months later the Chicks were on Lover, harmonizing on 'Soon You'll Get Better.'",
      evidence: "Egg roundups flagged the painting the day the video dropped in April 2019, months after Taylor had name-checked the group in her Elle essay — and the payoff shipped on the album that August. The same video gasped a real cat into existence: the kitten Brendon Urie offers her became Benjamin Button, adopted from the shoot.",
      confidence: "reputable_reporting",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift's 'ME!' Video Easter Eggs: Album Title, Her Next Single & More", url: "https://www.billboard.com/music/pop/taylor-swift-me-video-easter-eggs-8509007/" }, { name: "Taylor Swift's ''ME!'' Music Video: All the Hidden Easter Eggs and Symbolism", url: "https://www.eonline.com/news/1035688/taylor-swift-s-me-music-video-all-the-hidden-easter-eggs-and-symbolism" }],
      relatedSlugs: ["lover:mastermind-doctrine"],
    },
    {
      slug: "the-man-karma-graffiti",
      kind: "easter_egg",
      title: "The subway wall in 'The Man' maps her whole catalog",
      claim: "The graffiti wall Tyler Swift walks past in 'The Man' is tagged with her album titles, a 'Missing: if found return to Taylor Swift' poster standing in for the stolen debut — and, largest of all, the word KARMA.",
      evidence: "Outlets catalogued the wall shot when the video dropped in February 2020, mid-fight over her masters — the graffiti read as a map of the back catalog Scooter Braun had just bought, with the 13th Street station sign as a bonus. The KARMA tag fed the long-running lost-album theory; no Karma album ever surfaced, but 'Karma' the song arrived on Midnights and she has kept the wink going since.",
      confidence: "reputable_reporting",
      outcome: "confirmed",
      sources: [{ name: "Easter Eggs In Taylor Swift's 'The Man' Video Are Everywhere", url: "https://www.marieclaire.com/celebrity/a31129779/easter-eggs-taylor-swift-the-man/" }, { name: "7 Easter Eggs You Might Not Have Noticed in Taylor Swift's \"The Man\" Music Video", url: "https://www.distractify.com/p/taylor-swift-the-man-music-video-easter-eggs" }],
      relatedSlugs: ["midnights:karma-lost-album"],
    },
    {
      slug: "lover-house-eras-map",
      kind: "theory",
      title: "Every room in the Lover house is an era",
      claim: "Fans read each room of the 'Lover' video's snow-globe house as one of her albums — the red room for Red, the hazy attic for reputation — with the starry ceiling revealed as Midnights, completing the house.",
      evidence: "The room-by-room mapping circulated for years before a viral TikTok matched every room to an album when Midnights was announced in 2022 and declared the house complete. Taylor liked the TikTok — E! and ABC Audio both covered it as a seeming nod of approval — but she has never confirmed the mapping outright, so the thumbs-up is as official as it gets.",
      confidence: "strong_fan_consensus",
      outcome: "partially_confirmed",
      sources: [{ name: "Taylor Swift Approves of This Theory About Her 10 Albums", url: "https://www.eonline.com/news/1344281/taylor-swift-approves-of-this-theory-about-her-10-albums" }, { name: "Taylor Swift seemingly confirms fan theory about the \"Lover\" house", url: "https://digital.abcaudio.com/news/taylor-swift-seemingly-confirms-fan-theory-about-lover-house" }],
      relatedSlugs: ["lover:mastermind-doctrine"],
    },
  ],
  "midnights": [
    {
      slug: "karma-lost-album",
      kind: "theory",
      title: "The lost \"Karma\" album",
      claim: "Long-running fan theory that a finished album called Karma was scrapped in 2016 when the era imploded — and that later karma references (the Midnights track above all) are Taylor winking at what was shelved.",
      evidence: "Built from 2016-era teasers fans read as an album hint, then supercharged when Midnights shipped a song literally called \"Karma.\" Never confirmed, never denied; every era adds a new \"proof\" and the theory keeps its engine running. Filed as beloved, unresolved canon.",
      confidence: "strong_fan_consensus",
      outcome: "pending",
      sources: [{ name: "Karma (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Karma_(Taylor_Swift_song)" }],
    },
    {
      slug: "bejeweled-speak-now-clues",
      kind: "easter_egg",
      title: "The Bejeweled video was a Speak Now announcement",
      claim: "Fans read the \"Bejeweled\" video — the purple gown, the pointed floor-three elevator button, the Enchanted-coded ballroom — as a coded reveal that Speak Now (Taylor's Version), album three, was next. It was.",
      evidence: "Taylor said on release day that the video was stuffed with easter eggs; the fandom filed the purple/third-floor cluster under Speak Now within hours. Just over six months later the Nashville announcement proved the read. The clean template of clue -> consensus -> confirmation.",
      confidence: "strong_fan_consensus",
      outcome: "confirmed",
      sources: [{ name: "Bejeweled (song)", url: "https://en.wikipedia.org/wiki/Bejeweled_(song)" }, { name: "Speak Now (Taylor's Version)", url: "https://en.wikipedia.org/wiki/Speak_Now_(Taylor%27s_Version)" }],
      relatedSlugs: ["lover:mastermind-doctrine"],
    },
    {
      slug: "vault-puzzles-1989",
      kind: "easter_egg",
      title: "The Google vault puzzles",
      claim: "To reveal the 1989 (Taylor's Version) vault track titles, fans had to collectively solve 33 million Google word puzzles — searching her name spilled a literal blue vault across the results page.",
      evidence: "An official, platform-scale scavenger hunt run with Google in September 2023; the fandom cleared the 33-million target in under a day (crashing the puzzle at one point) and the vault titles unlocked. Easter-egg culture as infrastructure.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "1989 (Taylor's Version)", url: "https://en.wikipedia.org/wiki/1989_(Taylor%27s_Version)" }],
    },
    {
      slug: "eight-nine-sofi",
      kind: "theory",
      title: "8/9: the date fans called in advance",
      claim: "Swifties bet 1989 (Taylor's Version) would be announced on August 9, 2023 — the final 2023 US Eras show, on 8/9 — after weeks of blue outfits and cursive-“T” hints. She announced it that night.",
      evidence: "A genuinely predictive win for fan numerology: date logic (8/9 = ’89), the color-code system (blue = 1989), and the tour calendar all pointed the same way, publicly, before the show. Documented as called-in-advance rather than retrofitted.",
      confidence: "strong_fan_consensus",
      outcome: "confirmed",
      sources: [{ name: "1989 (Taylor's Version)", url: "https://en.wikipedia.org/wiki/1989_(Taylor%27s_Version)" }],
      relatedSlugs: ["midnights:album-color-canon"],
    },
    {
      slug: "album-color-canon",
      kind: "theory",
      title: "Every era has a color",
      claim: "Fan canon assigns each album a color — gold Fearless, purple Speak Now, red Red, blue 1989, black reputation, pink Lover, grey folklore, rust evermore, midnight-blue Midnights — and Taylor signals eras by wearing the palette before announcing anything.",
      evidence: "The color system started as fan taxonomy and became a two-way channel: the Eras Tour staged each act in its color, and announcement-watching now runs on outfit forensics (blue before 1989 TV, purple before Speak Now TV). Repeatedly validated, never formally codified.",
      confidence: "strong_fan_consensus",
      outcome: "partially_confirmed",
      sources: [{ name: "The Eras Tour", url: "https://en.wikipedia.org/wiki/The_Eras_Tour" }, { name: "Cultural impact of Taylor Swift", url: "https://en.wikipedia.org/wiki/Cultural_impact_of_Taylor_Swift" }],
      relatedSlugs: ["midnights:eight-nine-sofi"],
    },
    {
      slug: "surprise-song-metagame",
      kind: "theory",
      title: "The surprise-song metagame",
      claim: "Eras Tour fans treated the nightly two-song acoustic set as a solvable system: a no-repeat rule, dwindling remaining-songs spreadsheets, and city-specific logic used to predict each night's picks.",
      evidence: "The no-repeat pattern held through most of 2023 (screwed-up songs earned reruns, by her own stage admission), making the community spreadsheets genuinely predictive — until the 2024 mashup era deliberately broke the system. Pattern real; rule informal; expiration confirmed.",
      confidence: "reputable_reporting",
      outcome: "partially_confirmed",
      sources: [{ name: "The Eras Tour", url: "https://en.wikipedia.org/wiki/The_Eras_Tour" }],
    },
    {
      slug: "friendship-bracelets",
      kind: "easter_egg",
      title: "One lyric started the bracelet economy",
      claim: "The Eras Tour friendship-bracelet ritual — millions of beaded bracelets made, traded, and stacked at every show — grew out of a single \"You're on Your Own, Kid\" lyric about making friendship bracelets and taking the moment.",
      evidence: "Fans took the lyric as an instruction within weeks of opening night; by mid-2023 bracelet trading was the tour's defining ritual, covered everywhere from local news to bead-shortage business stories. A lyric became a subculture — the fandom's favorite kind of easter egg: one they built themselves.",
      confidence: "reputable_reporting",
      outcome: "confirmed",
      sources: [{ name: "The Eras Tour", url: "https://en.wikipedia.org/wiki/The_Eras_Tour" }, { name: "Swifties", url: "https://en.wikipedia.org/wiki/Swifties" }],
    },
  ],
  "red": [
    {
      slug: "twenty-two-liner-note-code",
      kind: "easter_egg",
      title: "A liner-note code names the friends behind \"22\"",
      claim: "The 2012 Red CD booklet hid a capitalization code inside \"22\" that decodes to \"ASHLEY DIANNA CLAIRE SELENA\" — a shout-out to the real friends the song's carefree night was inspired by.",
      evidence: "Following the same hidden-capital-letters technique used on her earlier album booklets, the \"22\" lyric sheet's decoded message names four friends rather than a romantic subject, matching the song's own framing as a friendship anthem about a birthday night out.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift's 13 Best Liner Note Secret Messages", url: "https://www.billboard.com/music/music-news/taylor-swift-liner-note-secret-messages-6296379/" }],
    },
    {
      slug: "vault-track-word-puzzle-reveal",
      kind: "easter_egg",
      title: "A word puzzle unlocks the Red (Taylor's Version) vault tracks",
      claim: "On Aug. 5, 2021, Swift posted an interactive word-puzzle video across social media that, once solved, revealed the \"From the Vault\" collaborators and titles — including Chris Stapleton, Phoebe Bridgers, \"Babe,\" \"Better Man,\" and the All Too Well (10 Minute Version) — ahead of the album's release.",
      evidence: "The puzzle format built on the anagram-teaser approach from the Fearless re-record, this time rewarding fans who solved it with a bonus image. All of the revealed information — the featured artists and track titles — matched the official track list confirmed at release.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Red (Taylor's Version)", url: "https://en.wikipedia.org/wiki/Red_(Taylor%27s_Version)" }],
      relatedSlugs: ["fearless:vault-track-anagram-reveal"],
    },
  ],
  "reputation": [
    {
      slug: "snake-reclamation",
      kind: "easter_egg",
      title: "Reclaiming the snake",
      claim: "After the 2016 feud fallout flooded her comments with snake emoji, the reputation rollout weaponized it: glitchy snake teasers announced the era, a serpent slithered through the visuals, and a giant snake named Karyn towered over the stadium tour.",
      evidence: "The era launch was three wordless snake videos posted to blacked-out socials; 'Look What You Made Me Do' leaned all the way in (a snake serving tea); the Stadium Tour made the snake a mascot. A documented, deliberate reclamation arc — the insult became the brand.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Look What You Made Me Do", url: "https://en.wikipedia.org/wiki/Look_What_You_Made_Me_Do" }, { name: "Kanye West–Taylor Swift feud", url: "https://en.wikipedia.org/wiki/Kanye_West%E2%80%93Taylor_Swift_feud" }],
    },
    {
      slug: "lwymmd-nils-sjoberg-gravestone",
      kind: "easter_egg",
      title: "A gravestone for Nils Sjöberg",
      claim: "In the 'Look What You Made Me Do' graveyard, the headstone beside the grave zombie-Taylor digs reads Nils Sjöberg — the Swedish pseudonym she used to secretly co-write Calvin Harris's 'This Is What You Came For,' buried on camera.",
      evidence: "Outlets ran full decoder guides the week the video premiered at the 2017 VMAs, and the gravestone was near the top of every list. The pseudonym's story was already public — the co-write came out messily after the Harris breakup in July 2016 — which is what made burying the name read as such a pointed goodbye to the era of hiding her own credits.",
      confidence: "reputable_reporting",
      outcome: "confirmed",
      sources: [{ name: "All the References You Might Have Missed in Taylor Swift's 'Look What You Made Me Do' Video", url: "https://time.com/4918411/taylor-swift-look-what-you-made-me-do-music-video-references/" }, { name: "Taylor Swift's 'Look What You Made Me Do' Video Decoded: 13 Things You Missed", url: "https://www.rollingstone.com/music/music-news/taylor-swifts-look-what-you-made-me-do-video-decoded-13-things-you-missed-126268/" }],
      relatedSlugs: ["reputation:snake-reclamation"],
    },
    {
      slug: "lwymmd-dollar-bill",
      kind: "theory",
      title: "The single dollar in the bathtub of diamonds",
      claim: "In the 'Look What You Made Me Do' bathtub-of-jewels shot, a lone dollar bill sits beside her. Fans read it as the symbolic $1 she sued for — and won — in her Denver sexual assault trial, days before the video premiered.",
      evidence: "The timing does the arguing: the jury found in her favor on August 14, 2017, awarding the single symbolic dollar she had asked for, and the video premiered at the VMAs on August 27. Outlets covered the fan reading immediately, and a year later fans held up $1 bills at her Tampa show on the verdict's anniversary. Taylor has never confirmed the detail herself — which is why this stays a theory, not a fact.",
      confidence: "strong_fan_consensus",
      outcome: "pending",
      sources: [{ name: "The $1 Taylor Swift won during her sexual assault trial makes an appearance in \"Look What You Made Me Do\"", url: "https://hellogiggles.com/taylor-swift-sexual-assault-trial-music-video/" }, { name: "Taylor Swift Speaks Out About Believing Sexual Assault Victims on Anniversary of Her Trial Verdict", url: "https://time.com/5367874/taylor-swift-sexual-assault/" }],
      relatedSlugs: ["reputation:lwymmd-nils-sjoberg-gravestone"],
    },
  ],
  "speak-now": [
    {
      slug: "never-grow-up-liner-note-code",
      kind: "easter_egg",
      title: "A liner-note code confirms when she moved out",
      claim: "The 2010 Speak Now CD booklet hid a capitalization code inside \"Never Grow Up\" that decodes to \"MOVED OUT IN JULY\" — a real detail about Swift leaving her family's home, matching the song's own coming-of-age theme.",
      evidence: "Using the same hidden-capital-letters technique found across her early album booklets, the \"Never Grow Up\" lyric sheet's decoded phrase lines up with Swift's own account of moving into her first apartment that July, turning a lyric-sheet puzzle into a factual footnote on the song.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift's 13 Best Liner Note Secret Messages", url: "https://www.billboard.com/music/music-news/taylor-swift-liner-note-secret-messages-6296379/" }],
    },
    {
      slug: "speak-now-tv-tracklist-reveal",
      kind: "easter_egg",
      title: "The Speak Now (Taylor's Version) track list drops on social media",
      claim: "Swift unveiled the full Speak Now (Taylor's Version) track list, including its \"From the Vault\" songs, directly via social media on June 5, 2023, ahead of the album's July 7, 2023 release — continuing her established pattern of announcing re-record vault tracks in a dedicated reveal moment rather than a traditional press release.",
      evidence: "Fearless and Red (Taylor's Version) vault tracks had each been revealed through a cryptic scrambled-word \"vault\" puzzle video fans had to decode. Speak Now (TV) skipped the puzzle: a single, fan-facing announcement post named every vault track and its guest directly, rather than a label press cycle — a simplification of the earlier playbook, not a repeat of it.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Speak Now (Taylor's Version)", url: "https://en.wikipedia.org/wiki/Speak_Now_(Taylor%27s_Version)" }],
      relatedSlugs: ["fearless:vault-track-anagram-reveal", "red:vault-track-word-puzzle-reveal"],
    },
  ],
  "tloas": [
    {
      slug: "orange-era-clues",
      kind: "theory",
      title: "The orange era, called before the announcement",
      claim: "Through the TTPD stretch, TS12 watchers bet the next era's color was orange — reading glittery orange accents into late Eras Tour looks and posts. When The Life of a Showgirl arrived, the branding was orange head to toe.",
      evidence: "The album was announced on the New Heights podcast in August 2025 wrapped in glittering orange (and mint) — instantly validating months of color-watching. How much of the pre-announcement orange was planted versus pattern-matched has never been itemized, so the call is graded, not fully confirmed.",
      confidence: "strong_fan_consensus",
      outcome: "partially_confirmed",
      sources: [{ name: "The Life of a Showgirl", url: "https://en.wikipedia.org/wiki/The_Life_of_a_Showgirl" }],
      relatedSlugs: ["midnights:album-color-canon"],
    },
    {
      slug: "ophelia-rewrite",
      kind: "easter_egg",
      title: "Ophelia, rewritten to live",
      claim: "The lead single \"The Fate of Ophelia\" flips Shakespeare: where Hamlet's Ophelia drowns in abandonment, the song's narrator is pulled out of that fate by love — a literary inversion fans and critics mapped line by line.",
      evidence: "The allusion is the title; coverage of the single documented the Hamlet inversion as the song's central conceit, continuing the quill-pen literary streak from TTPD (Peter Pan, Cassandra, Clara Bow).",
      confidence: "reputable_reporting",
      outcome: "confirmed",
      sources: [{ name: "The Fate of Ophelia", url: "https://en.wikipedia.org/wiki/The_Fate_of_Ophelia" }],
      relatedSlugs: ["ttpd:peter-pan-throughline"],
    },
  ],
  "ttpd": [
    {
      slug: "thank-you-aimee-capitals",
      kind: "easter_egg",
      title: "The capitals in \"thanK you aIMee\"",
      claim: "The track title is stylized \"thanK you aIMee\" — the stray capitals spell KIM. Press and fans read the song as addressed to a famous bully by that name; Taylor has never said so herself.",
      evidence: "The stylization is objective fact (it is printed that way on the tracklist) and the reading was reported by major outlets within hours. But the attribution remains an inference from typography — so it stays labeled as reporting, not confirmation.",
      confidence: "reputable_reporting",
      outcome: "pending",
      sources: [{ name: "The Tortured Poets Department", url: "https://en.wikipedia.org/wiki/The_Tortured_Poets_Department" }],
      relatedSlugs: ["reputation:snake-reclamation"],
    },
    {
      slug: "peter-pan-throughline",
      kind: "easter_egg",
      title: "Peter, four years later",
      claim: "The Anthology track \"Peter\" reads as the grown-up ending to folklore's Peter-and-Wendy thread — fans hold that the boy who \"lost Wendy\" in \"cardigan\" is the same Peter who finally never comes back here.",
      evidence: "The Peter Pan allusion is explicit in both lyrics four years apart, and the callback was noted across the album's press coverage. The songs connect textually; whether they share one narrator is the (unconfirmed) fan layer.",
      confidence: "reputable_reporting",
      outcome: "partially_confirmed",
      sources: [{ name: "The Tortured Poets Department", url: "https://en.wikipedia.org/wiki/The_Tortured_Poets_Department" }, { name: "cardigan (song)", url: "https://en.wikipedia.org/wiki/Cardigan_(song)" }],
      relatedSlugs: ["folklore:teenage-love-triangle"],
    },
  ],
};
