import type { EraId, TheoryNote } from '@swift2/experience';
import { setTheoriesRawProvider } from '@swift2/experience';
import { THEORIES_RAW } from './theories-bundle.generated';

export { theoriesForEra, resolveRelatedTheory } from '@swift2/experience';

/**
 * Wires the app's per-era theories dataset into `packages/experience`'s
 * `theories.ts` (OS-023 — see `thread-content-provider.ts`'s doc comment):
 * the headless package can't load content itself (content loading is
 * OS-013/OS-014b scope), so the app injects the raw data in at import time.
 *
 * OS-014b-3: `THEORIES_RAW` now comes from `theories-bundle.generated.ts`
 * (regenerated by `scripts/generate-bundle-backed-modules.mjs` from the
 * PUBLISHED content bundle — `apps/web/public/content/<bundleVersion>/
 * theories.json`, written by `scripts/publish-content-bundle.mjs` — see
 * `package.json`'s `prebuild` script) instead of directly from
 * `theories.generated.ts` (the seed-derived intermediate that feeds the
 * bundle build itself, via `scripts/lib/dump-longlive-sources.ts`).
 *
 * A GENERATED module, not a runtime bundle read: `theoriesForEra` is called
 * synchronously from client-component render code (`TheoryGuide.tsx`), so
 * Next/Turbopack must bundle this whole import graph for the BROWSER too —
 * a `fs`/`fetch` read at this layer either doesn't exist in that
 * environment (`fs`) or would ship a per-user network call (`fetch`),
 * violating CLAUDE.md's "Vault stays static, no per-user LLM/network
 * calls" rule. A plain object literal, generated ahead of time from the
 * bundle, is bundler-safe on every target exactly like the old
 * `theories.generated.ts` was.
 */
setTheoriesRawProvider((): Partial<Record<EraId, TheoryNote[]>> => THEORIES_RAW);
