// GENERATED FILE — do not hand-edit.
// Produced by scripts/sync-longlive-theories.mjs from supabase/seed/theories/**
// (or the live Supabase theory table when configured).
// Re-run that script after theory-seed changes; don't edit this file directly.

import type { EraId, TheoryNote } from './types';

export const THEORIES_RAW: Partial<Record<EraId, TheoryNote[]>> = {
  "1989": [
    {
      slug: "no-its-becky",
      kind: "theory",
      title: "\"no it's becky\"",
      claim: "The 2014 Tumblr joke: a photo of Taylor captioned as a girl named Becky who \"snorted marijuana at a party and died,\" answered with \"no it's becky.\" Fans ran with Becky as Taylor's alter ego — and Taylor got the joke.",
      evidence: "Born as a Tumblr exchange during her famously online 1989-era presence. Taylor canonized the meme herself by wearing a \"no its becky\" T-shirt, turning a fandom in-joke into official-adjacent lore.",
      confidence: "joke_meme",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift Wears 'no its becky' T-Shirt", url: "https://time.com/3430491/taylor-swift-internet-meme-no-its-becky-tshirt/", reliability: 4, type: "reputable_press" }, { name: "Swifties", url: "https://en.wikipedia.org/wiki/Swifties", reliability: 2, type: "wiki" }],
    },
    {
      slug: "1989-lowercase-liner-codes",
      kind: "easter_egg",
      title: "The lowercase inversion",
      claim: "1989's booklet flips her oldest trick: after five albums of hidden messages spelled in capitalized letters, the codes moved to the lowercase letters — and read in track order, the thirteen messages tell one continuous story.",
      evidence: "Billboard decoded and published the full 1989 set the week the album dropped — it opens \"We begin our story in New York\" and runs as a single arc through all thirteen tracks, a two-year autobiography threaded through the lyric sheets. The inversion mattered to code-watchers: new sound, new cipher. It was also the finale — the booklet codes stop entirely at reputation.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift's '1989' Liner Note Messages & Reference Guide", url: "https://www.billboard.com/music/music-news/taylor-swift-1989-liner-notes-6296676/", reliability: 4, type: "reputable_press" }, { name: "Liner notes and easter eggs: How Taylor Swift turned fandom into a scavenger hunt", url: "https://www.today.com/popculture/music/taylor-swift-easter-eggs-hidden-messages-rcna51887", reliability: 4, type: "reputable_press" }],
      relatedSlugs: ["debut:liner-notes-hidden-messages", "red:twenty-two-liner-note-code"],
    },
    {
      slug: "1989-polaroid-cover",
      kind: "easter_egg",
      title: "The cropped Polaroid",
      claim: "1989's cover is a real Polaroid — Taylor's face cut off at the eyes on purpose, so no expression could give away whether the album was happy or sad. Every deluxe CD hid a packet of 13 more: one of five sets drawn from 65 numbered Polaroids, each front scrawled with a line of handwritten lyric.",
      evidence: "Taylor told ABC News the album photos were shot on an instant camera — \"that photo you are seeing is a Polaroid we took… it was kind of an accident, so I figured why not make that photo the album cover?\" — and cropped the frame at her eyes so fans couldn't immediately read the record's emotional tone. The physical release turned that instant-photo motif into a scavenger hunt: each 1989 CD shipped with a packet of 13 Polaroids drawn from 65 numbered shots (#01–#65), five different sets in all, every one captioned with a scrap of lyric in her handwriting. Completists needed all five copies to assemble the full 65 — and the concept is credited with helping spark a real-world revival of instant film.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift Explains Meaning Behind Cover of New Album '1989'", url: "https://abcnews.com/Entertainment/meaning-cover-taylor-swifts-album-1989/story?id=25028609", reliability: 4, type: "reputable_press" }, { name: "1989 (Taylor Swift album)", url: "https://en.wikipedia.org/wiki/1989_(Taylor_Swift_album)", reliability: 2, type: "wiki" }],
      relatedSlugs: ["1989:1989-lowercase-liner-codes"],
    },
    {
      slug: "1989-deluxe-voice-memos",
      kind: "easter_egg",
      title: "The voice memos",
      claim: "The Target deluxe edition tucked three phone voice memos among the bonus tracks — early, unfinished recordings of \"I Know Places,\" \"I Wish You Would\" and \"Blank Space\" — letting fans eavesdrop on the songs mid-build, straight off Taylor's phone.",
      evidence: "Alongside three extra songs, the deluxe 1989 hid a rarer bonus: raw voice memos Taylor had recorded on her phone while the songs were still forming — piano-and-vocal for \"I Know Places,\" a rough track-and-vocal for \"I Wish You Would,\" guitar-and-vocal for \"Blank Space.\" You hear her humming a melody into the phone, talking through the writing, catching an idea before it is finished. It made the songwriting process itself a bonus track — a behind-the-curtain move she liked enough to bring back for the Taylor's Version re-records years later.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift's Songwriting Memos Reveal Secrets About '1989' Tracks", url: "https://www.bustle.com/articles/47243-taylor-swifts-songwriting-memos-reveal-secrets-about-1989-tracks", reliability: 3, type: "reputable_press" }, { name: "1989 (Taylor Swift album)", url: "https://en.wikipedia.org/wiki/1989_(Taylor_Swift_album)", reliability: 2, type: "wiki" }],
    },
    {
      slug: "blank-space-media-caricature",
      kind: "theory",
      title: "\"Blank Space\" is the joke on the tabloids",
      claim: "The reading — which Taylor confirmed — that \"Blank Space\" isn't a confession but a satire: she plays the boy-crazy, unhinged \"man-eater\" the media invented for her, so straight-faced that half the audience missed that it was a bit.",
      evidence: "Fans and critics heard \"Blank Space\" as Taylor performing the caricature the press had drawn of her, and she said as much. She told NME the song was deliberately ironic — \"It's so opposite my actual life. Half the people got the joke, half the people really think that I was like really owning the fact that I'm a psychopath\" — framing it as a reply to a media that \"every few years… finds something that they unanimously feel is annoying about me.\" She described the character elsewhere as \"a girl who's crazy but seductive but glamorous but nuts but manipulative.\" The theory is squarely about the media narrative she was skewering, not any real relationship.",
      confidence: "confirmed_interview",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift explained to us the story and misconceptions of 'Blank Space'", url: "https://www.nme.com/blogs/nme-blogs/taylor-swift-explained-to-us-the-story-and-misconceptions-of-blank-space-14783", reliability: 4, type: "reputable_press" }, { name: "Blank Space", url: "https://en.wikipedia.org/wiki/Blank_Space", reliability: 2, type: "wiki" }],
    },
    {
      slug: "blank-space-starbucks-lovers",
      kind: "theory",
      title: "The \"Starbucks lovers\" mishearing",
      claim: "Radio listeners heard the \"Blank Space\" line \"got a long list of ex-lovers\" as \"all the lonely Starbucks lovers\" — a mondegreen so pervasive that even Taylor's own mother fell for it, and Taylor leaned all the way in.",
      evidence: "The real lyric is \"got a long list of ex-lovers,\" but \"all the lonely Starbucks lovers\" became one of 2014–15's defining misheard lines. Taylor acknowledged the mix-up on Valentine's Day 2015, and that May she posted her mom's verdict — \"hahah it really does sound like Starbucks Lovers… -my mom just now who is SUPPOSED TO BE ON MY SIDE,\" with a resigned \"Smh\" (May 25, 2015). Starbucks eventually built a 122-track \"Starbucks Lovers\" playlist off the joke. Like \"no it's becky,\" it's 1989-era proof of how online the era was — a slip of the ear the fandom, and the artist, adopted on purpose.",
      confidence: "joke_meme",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift’s Blank Space Lyrics Not About Starbucks Lovers", url: "https://time.com/3895936/taylor-swift-blank-space-lyrics-starbucks-lovers/", reliability: 4, type: "reputable_press" }, { name: "Taylor Swift's Mom Misheard 'Starbucks Lovers' Too", url: "https://abcnews.com/Entertainment/taylor-swifts-mom-mishears-starbucks-lovers/story?id=31289081", reliability: 4, type: "reputable_press" }],
      relatedSlugs: ["1989:no-its-becky"],
    },
  ],
  "debut": [
    {
      slug: "lucky-number-13",
      kind: "easter_egg",
      title: "13, the number that runs through everything",
      claim: "Taylor treats 13 as her lucky number — born December 13, she drew it on her hand for early shows, and fans hunt for it in track sequencing, dates, and clue-drops to this day.",
      evidence: "On the record from the start: she has repeatedly explained the number (her birthday, her first album going gold in 13 weeks, seat rows and awards-show coincidences) and wore a hand-painted 13 at Fearless-era shows. Decoding-by-13 became the founding grammar of Swiftie lore.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift", url: "https://en.wikipedia.org/wiki/Taylor_Swift", reliability: 2, type: "wiki" }, { name: "Cultural impact of Taylor Swift", url: "https://en.wikipedia.org/wiki/Cultural_impact_of_Taylor_Swift", reliability: 2, type: "wiki" }],
    },
    {
      slug: "liner-notes-hidden-messages",
      kind: "easter_egg",
      title: "The liner-note code: capital letters spell secrets",
      claim: "From the debut album onward, the lyric booklets hid messages: read only the capitalized letters in each printed lyric and they spell out a secret line about the song.",
      evidence: "A confirmed, deliberate practice — the booklet codes ran from the 2006 debut through 1989 (2014) and trained the fandom to decode everything that followed. She later said the clue-planting simply moved from liner notes into videos, posts, and performances.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "A Complete History of Taylor Swift's Best Easter Eggs", url: "https://www.today.com/today/amp/rcna51887", reliability: 4, type: "reputable_press" }, { name: "Swifties", url: "https://en.wikipedia.org/wiki/Swifties", reliability: 2, type: "wiki" }],
      relatedSlugs: ["debut:tim-mcgraw-debut-single-nested-clue"],
    },
    {
      slug: "tim-mcgraw-debut-single-nested-clue",
      kind: "easter_egg",
      title: "\"Tim McGraw\": the first single was already a hidden reference",
      claim: "Her very first single is a reference folded inside a reference — named after a country legend, built around one of his songs, and hiding that song's title in the liner-note code. The clue-planting that became her signature was there on record one.",
      evidence: "Taylor wrote it in about fifteen minutes during a math class, singing \"when you think Tim McGraw\" to herself. Big Machine head Scott Borchetta talked her out of the longer working title \"When You Think Tim McGraw\" and down to just \"Tim McGraw\" — and naming a debut single after an established star, as one music scholar put it, was \"a clever strategy\" that handed an unknown sixteen-year-old instant \"country music legibility.\" The song turns on McGraw's 2004 hit \"Can't Tell Me Nothin',\" her favorite of his — and the debut booklet's capitalized-letter secret message for the track spells out that same title, \"CAN'T TELL ME NOTHIN'.\" The homage is doubled: the name on the marquee, and the name hidden in the margins.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Tim McGraw at 20: how Taylor Swift's debut single set her formula for success", url: "https://theconversation.com/tim-mcgraw-at-20-how-taylor-swifts-debut-single-set-her-formula-for-success-285254", reliability: 4, type: "reputable_press" }, { name: "The Reactions of the Men Behind Taylor Swift's Debut Single, \"Tim McGraw\"", url: "https://americansongwriter.com/the-reactions-of-the-men-behind-taylor-swifts-debut-single-tim-mcgraw-released-on-this-day-in-2006/", reliability: 4, type: "reputable_press" }, { name: "Tim McGraw (song)", url: "https://en.wikipedia.org/wiki/Tim_McGraw_(song)", reliability: 2, type: "wiki" }, { name: "Taylor Swift's 13 Best Liner Note Secret Messages", url: "https://www.billboard.com/music/music-news/taylor-swift-liner-note-secret-messages-6296379/", reliability: 4, type: "reputable_press" }],
      relatedSlugs: ["debut:liner-notes-hidden-messages"],
    },
    {
      slug: "the-outside-first-song-outcast",
      kind: "theory",
      title: "\"The Outside\": the outcast anthem that started the songwriting",
      claim: "Fans read \"The Outside\" as Taylor's origin story as a songwriter — a song about being a complete outcast at school that doubles as the reason she ever picked up a pen at all.",
      evidence: "Taylor has confirmed exactly that reading. She has called it one of the first songs she ever wrote and said it \"talks about the very reason I ever started to write songs. It was when I was twelve years old, and a complete outcast at school.\" She told Entertainment Weekly the song is about \"the scariest feeling I've ever felt: going to school, walking down the hall, looking at all those faces, and not knowing who you're gonna talk to that day.\" The isolation traced to a country-music obsession her classmates didn't share — the same difference that later became her whole brand.",
      confidence: "confirmed_interview",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift — \"The Outside\" (Songfacts)", url: "https://www.songfacts.com/facts/taylor-swift/the-outside", reliability: 4, type: "reputable_press" }, { name: "The Outside (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/The_Outside_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
    },
    {
      slug: "a-place-in-this-world-mission-statement",
      kind: "theory",
      title: "\"A Place in This World\": the thirteen-year-old's mission statement",
      claim: "A common reading holds \"A Place in This World\" as the thesis of the whole debut — a newly-transplanted teenager measuring the gap between where she was and where she was determined to end up.",
      evidence: "Taylor's own account backs the reading. She wrote it at thirteen, just after the family moved to Nashville, with co-writers Robert Ellis Orrall and Angelo Petraglia: \"It was tough trying to find out how I was going to get where I wanted to go. I knew where I wanted to be, but I just didn't know how to get there.\" She has traced the ambition itself to a television special about Faith Hill leaving for Nashville — the move Taylor then made herself.",
      confidence: "confirmed_interview",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift — \"A Place in This World\" (Songfacts)", url: "https://www.songfacts.com/facts/taylor-swift/a-place-in-this-world", reliability: 4, type: "reputable_press" }, { name: "A Place in This World", url: "https://en.wikipedia.org/wiki/A_Place_in_This_World", reliability: 2, type: "wiki" }],
    },
  ],
  "evermore": [
    {
      slug: "thirteen-backwards",
      kind: "easter_egg",
      title: "Dropped when 13 runs backwards",
      claim: "evermore arrived two days before her 31st birthday — and she said the timing was the point: she'd been excited about turning 31 \"because it's my lucky number backwards, which is why I wanted to surprise you with this now.\"",
      evidence: "Stated in her own announcement of the album: the 31/13 mirror was her framing, not a fan read. The numerology habit that started with hand-painted 13s now sets release dates.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Evermore (Taylor Swift album)", url: "https://en.wikipedia.org/wiki/Evermore_(Taylor_Swift_album)", reliability: 2, type: "wiki" }],
      relatedSlugs: ["debut:lucky-number-13", "folklore:woodvale"],
    },
    {
      slug: "dorothea-and-the-love-triangle",
      kind: "theory",
      title: "Does the love triangle grow up on evermore?",
      claim: "Fans read 'tis the damn season and dorothea as one hometown girl who left for Hollywood and the ex she keeps circling back to — and tie her to the folklore teenage love triangle, reading evermore as those characters grown up.",
      evidence: "Taylor framed evermore as folklore's sister record, set in the same fictional world, and the two songs share a narrator: someone who left a small town for the screen, and the road that keeps leading her back to an old flame. Fans map her onto Betty, or onto the one who got away — but Taylor confirmed only the shared universe, never that Dorothea IS any named folklore character, so the specific casting stays an open close-read rather than canon.",
      confidence: "strong_fan_consensus",
      outcome: "unfalsifiable",
      sources: [{ name: "Evermore (Taylor Swift album)", url: "https://en.wikipedia.org/wiki/Evermore_(Taylor_Swift_album)", reliability: 2, type: "wiki" }, { name: "Folklore (Taylor Swift album)", url: "https://en.wikipedia.org/wiki/Folklore_(Taylor_Swift_album)", reliability: 2, type: "wiki" }],
      relatedSlugs: ["folklore:teenage-love-triangle"],
    },
    {
      slug: "ivy-the-affair-narrative",
      kind: "theory",
      title: "'ivy': an affair told in a garden",
      claim: "The near-universal reading of ivy is the confession of a married woman in love with someone else — creeping 'ivy' standing in for a love that spreads where it isn't wanted — with a companion theory that the literary, 19th-century diction nods to Emily Dickinson.",
      evidence: "evermore is built from fictional character studies, and ivy's narrator is widely read as a wife whose heart has gone elsewhere, the overgrown-garden metaphor doing the work a plainer confession couldn't. Its old-fashioned, poem-like language fed a second reading that the song echoes Dickinson. Both stay interpretation of a deliberately literary, fictional lyric — not a key Taylor has handed over.",
      confidence: "strong_fan_consensus",
      outcome: "unfalsifiable",
      sources: [{ name: "Evermore (Taylor Swift album)", url: "https://en.wikipedia.org/wiki/Evermore_(Taylor_Swift_album)", reliability: 2, type: "wiki" }],
    },
    {
      slug: "cowboy-like-me-two-con-artists",
      kind: "theory",
      title: "'cowboy like me': two grifters fall in love",
      claim: "The popular reading of cowboy like me is a love story between two con artists who spot the hustle in each other — a pair of charmers who prey on the wealthy, then dangerously fall for the one mark who can read them right back.",
      evidence: "The lyric's tells — the tallied marks, the wariness, the recognition of a fellow schemer — support a near-universal fan reading of two grifters undone by real feeling. Like most of evermore it's a character study, so the reading is about the fictional narrators rather than anyone real; Taylor has left the song to speak for itself.",
      confidence: "strong_fan_consensus",
      outcome: "unfalsifiable",
      sources: [{ name: "Evermore (Taylor Swift album)", url: "https://en.wikipedia.org/wiki/Evermore_(Taylor_Swift_album)", reliability: 2, type: "wiki" }],
    },
    {
      slug: "closure-discomfort-by-design",
      kind: "theory",
      title: "'closure' is uncomfortable on purpose",
      claim: "Fans argue closure's jarring, off-kilter production isn't a misstep but the whole point — a song that refuses a clean resolution, set to music that refuses to sit still, so the listener feels the closure the narrator won't grant.",
      evidence: "closure pairs a bitter kiss-off — thanks but no thanks to a peace offering that's really about the ex's comfort — with a deliberately abrasive, industrial-leaning arrangement in an unsettled meter. Critics and fans read the mismatch as intentional: the discomfort in the mix mirrors a narrator denying the tidy ending everyone expects. A craft reading, not a confirmed statement.",
      confidence: "plausible",
      outcome: "unfalsifiable",
      sources: [{ name: "Evermore (Taylor Swift album)", url: "https://en.wikipedia.org/wiki/Evermore_(Taylor_Swift_album)", reliability: 2, type: "wiki" }],
    },
    {
      slug: "evermore-bonus-tracks-true-ending",
      kind: "theory",
      title: "The bonus tracks are evermore's real ending",
      claim: "Fans treat the two deluxe tracks — right where you left me and it's time to go — as evermore's true emotional finale: one narrator frozen at the table where she was left, the other finally learning when to walk away — a matched pair about staying versus leaving.",
      evidence: "Placed after the title track, the pair reads as a deliberate coda: right where you left me strands a woman in the exact moment of heartbreak while the world moves on, and it's time to go answers it with the wisdom to recognize a lost cause and leave first. Fans prize the two as the record's thesis on endings — an editorial reading of track placement, not an official 'real ending' Taylor has claimed.",
      confidence: "strong_fan_consensus",
      outcome: "unfalsifiable",
      sources: [{ name: "Evermore (Taylor Swift album)", url: "https://en.wikipedia.org/wiki/Evermore_(Taylor_Swift_album)", reliability: 2, type: "wiki" }],
    },
    {
      slug: "marjorie-grandmothers-vocals",
      kind: "easter_egg",
      title: "Her grandmother really sings on 'marjorie'",
      claim: "The soaring background vocals in the last minute of marjorie aren't a session singer — they're Marjorie Finlay herself, Taylor's late grandmother and a trained opera singer, woven in from old recordings.",
      evidence: "Taylor has said she layered her grandmother's real operatic vocals into the track named for her, so Marjorie Finlay quite literally sings on her own tribute. It's the era's most-cited egg because it's confirmed and quietly devastating — a fact Taylor shared herself about a family member the family made public, not a fan guess.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Evermore (Taylor Swift album)", url: "https://en.wikipedia.org/wiki/Evermore_(Taylor_Swift_album)", reliability: 2, type: "wiki" }],
    },
  ],
  "fearless": [
    {
      slug: "the-best-day-liner-note-code",
      kind: "easter_egg",
      title: "A liner-note code hidden inside \"The Best Day\"",
      claim: "The 2008 Fearless CD booklet capitalized scattered letters within \"The Best Day\" lyric sheet that, read in order, spell out \"GOD BLESS ANDREA SWIFT\" — a hidden tribute to her mother.",
      evidence: "Taylor used this capitalization-code technique across her early album booklets, letting fans decode a short message per song from oddly capitalized letters in the printed lyrics. For \"The Best Day\" — itself written about her mother — the decoded message names her directly, tying the song's subject to its hidden dedication.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift's 13 Best Liner Note Secret Messages", url: "https://www.billboard.com/music/music-news/taylor-swift-liner-note-secret-messages-6296379/", reliability: 4, type: "reputable_press" }],
      relatedSlugs: ["fearless:the-best-day-surprise-home-video"],
    },
    {
      slug: "vault-track-anagram-reveal",
      kind: "easter_egg",
      title: "An anagram video unlocks the \"From the Vault\" track list",
      claim: "Before officially announcing the six \"From the Vault\" songs on Fearless (Taylor's Version), Taylor posted a scrambled-letter anagram video on social media that fans raced to decode, correctly working out the titles — and a Keith Urban feature — hours ahead of the formal reveal.",
      evidence: "The teaser clip showed jumbled letters that fans reassembled into the vault-track titles; Taylor confirmed the full list, including the Keith Urban duet, on April 3, 2021, six days ahead of the April 9 release. The announcement date (Feb. 11) and release date (April 9) each reduce to her frequently cited number 13 (2+11 and 4+9), a numerology pattern she has said she builds into release timing on purpose.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Fearless (Taylor's Version)", url: "https://en.wikipedia.org/wiki/Fearless_(Taylor%27s_Version)", reliability: 2, type: "wiki" }, { name: "Taylor Swift Reveals 'Fearless (Taylor's Version)' Track List, Including Keith Urban Duet", url: "https://www.rollingstone.com/music/music-news/taylor-swift-fearless-taylors-version-track-list-keith-urban-1150599/", reliability: 4, type: "reputable_press" }],
    },
    {
      slug: "the-best-day-surprise-home-video",
      kind: "easter_egg",
      title: "The home video she made in secret",
      claim: "Taylor wrote and recorded \"The Best Day\" about her mother and then, without telling her, cut a music video out of the family's real home movies — saving the whole thing as a Christmas surprise before it ever reached the public.",
      evidence: "She kept the song and the video hidden from Andrea, then played both for her on Christmas Eve. \"That's when I lost it,\" Andrea recalled, \"and I've lost it pretty much every time I've heard that song since.\" The self-edited clip of childhood footage went public on May 1, 2009 as a Mother's Day release through Big Machine — the moving-image companion to the booklet's decoded \"GOD BLESS ANDREA SWIFT\" tribute, so the same dedication is hidden twice on the same album, once in the printed letters and once on film. Years later she extended the gesture, adding never-before-seen home movies to the \"Best Day (Taylor's Version)\" lyric video.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "The Best Day (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/The_Best_Day_(Taylor_Swift_song)", reliability: 2, type: "wiki" }, { name: "Taylor Swift Pays Tribute to Mom Andrea With Unseen Home Movies in 'The Best Day' Lyric Video", url: "https://www.eonline.com/news/1257438/taylor-swift-pays-tribute-to-mom-andrea-with-unseen-home-movies-in-the-best-day-lyric-video", reliability: 3, type: "reputable_press" }],
      relatedSlugs: ["fearless:the-best-day-liner-note-code"],
    },
    {
      slug: "love-story-rewritten-ending",
      kind: "theory",
      title: "The Shakespeare rewrite",
      claim: "The reading — which Taylor has confirmed — that \"Love Story\" deliberately rewrites Romeo and Juliet: it keeps the star-crossed lovers and the disapproving family, then throws out the double suicide and hands the couple the ending Shakespeare denied them.",
      evidence: "Taylor has said she wrote the song in about twenty minutes on her bedroom floor, using Romeo and Juliet as the frame but refusing its tragedy: \"I thought, why can't you make it a happy ending and put a key change in the song and turn it into a marriage proposal?\" The finished lyric ends not with a tomb but with a proposal, and the music literally lifts a whole step at the payoff — the key change she described built into the song. It is a reading about craft and literary source, not about who the song is written for.",
      confidence: "confirmed_interview",
      outcome: "confirmed",
      sources: [{ name: "Love Story (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Love_Story_(Taylor_Swift_song)", reliability: 2, type: "wiki" }, { name: "Love Story by Taylor Swift", url: "https://www.songfacts.com/facts/taylor-swift/love-story", reliability: 3, type: "reputable_press" }],
    },
    {
      slug: "change-underdog-anthem",
      kind: "theory",
      title: "\"Change\" is the underdog-label anthem",
      claim: "The reading — in Taylor's own words — that \"Change\" isn't a breakup song but an underdog anthem: she wrote it about being sixteen on the smallest label in Nashville, willing her tiny team to beat the giants, and only later did an Olympics broadcast make it about athletes.",
      evidence: "Taylor has called it plainly \"an underdog story,\" written \"about being on a small record label and being a 16 year-old girl and having a lot of odds against all of us\" — Big Machine against the Nashville majors, the feeling of \"when are we going to get a fighting chance?\" She finished it around her 2007 CMA Horizon Award win, watching label head Scott Borchetta react. NBC then chose it for the 2008 Summer Olympics and the AT&T Team USA Soundtrack, which she found fitting but unexpected: \"it's kind of crazy to think that the Olympics chose this.\" The entry is about the song's stated meaning and rollout, not any relationship.",
      confidence: "confirmed_interview",
      outcome: "confirmed",
      sources: [{ name: "Change (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Change_(Taylor_Swift_song)", reliability: 2, type: "wiki" }, { name: "Change by Taylor Swift", url: "https://www.songfacts.com/facts/taylor-swift/change", reliability: 3, type: "reputable_press" }],
    },
  ],
  "folklore": [
    {
      slug: "woodvale",
      kind: "theory",
      title: "Woodvale: the third sister album that never was",
      claim: "Fans spotted the word \"Woodvale\" hidden in a folklore promo image and concluded a THIRD surprise sister album was coming after evermore. It never did.",
      evidence: "The word really was there — Taylor later explained on late-night TV that \"Woodvale\" was a working codename for folklore that mistakenly survived on a mock-up. A perfect case study: real artifact, real pattern-matching, wrong conclusion, official debunk.",
      confidence: "strong_fan_consensus",
      outcome: "debunked",
      sources: [{ name: "Evermore (Taylor Swift album)", url: "https://en.wikipedia.org/wiki/Evermore_(Taylor_Swift_album)", reliability: 2, type: "wiki" }],
      relatedSlugs: ["evermore:thirteen-backwards"],
    },
    {
      slug: "teenage-love-triangle",
      kind: "theory",
      title: "The teenage love triangle",
      claim: "Fans mapped \"cardigan,\" \"august,\" and \"betty\" as one story told by three narrators — Betty, Augustine, and James — and were right: Taylor confirmed the Teenage Love Triangle by name.",
      evidence: "Decoded within hours of release from shared names and mirrored details across the three lyrics; Taylor confirmed the intended triangle in interviews and the Long Pond sessions. The characters are explicitly fictional — which is what makes this the fandom's cleanest confirmed close-read.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Folklore (Taylor Swift album)", url: "https://en.wikipedia.org/wiki/Folklore_(Taylor_Swift_album)", reliability: 2, type: "wiki" }, { name: "cardigan (song)", url: "https://en.wikipedia.org/wiki/Cardigan_(song)", reliability: 2, type: "wiki" }],
      relatedSlugs: ["evermore:dorothea-and-the-love-triangle"],
    },
    {
      slug: "william-bowery",
      kind: "theory",
      title: "Who is William Bowery?",
      claim: "A never-before-seen co-writer named William Bowery appeared in the folklore credits. Fans immediately suspected a pseudonym — and in the Long Pond film Taylor confirmed it on camera.",
      evidence: "The credits were the entire clue: no such songwriter existed anywhere. The confirmation came in folklore: the long pond studio sessions, where she named the person behind the pen name. Textbook fandom arc — anomaly, theory, on-record resolution within months.",
      confidence: "confirmed_interview",
      outcome: "confirmed",
      sources: [{ name: "Folklore: The Long Pond Studio Sessions", url: "https://en.wikipedia.org/wiki/Folklore:_The_Long_Pond_Studio_Sessions", reliability: 2, type: "wiki" }],
    },
  ],
  "lover": [
    {
      slug: "butterfly-mural",
      kind: "easter_egg",
      title: "The butterfly mural that announced the era",
      claim: "Hours before \"ME!\" dropped in April 2019, a pastel butterfly mural by street artist Kelsey Montague appeared in Nashville — fans swarmed it, correctly reading it as the snake era molting into something new.",
      evidence: "Documented rollout stunt: the mural went up unannounced, fan detectives connected it to the countdown Taylor had posted, and she showed up at the wall herself. The butterfly-eats-snake beat inside the \"ME!\" video completed the metamorphosis arc.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "ME!", url: "https://en.wikipedia.org/wiki/Me!", reliability: 2, type: "wiki" }],
      relatedSlugs: ["reputation:snake-reclamation"],
    },
    {
      slug: "mastermind-doctrine",
      kind: "easter_egg",
      title: "The easter-egg doctrine, stated on the record",
      claim: "Not a theory — a confession: Taylor has said outright that she plants clues about future music years in advance, and that decoding them is a game she deliberately plays with fans.",
      evidence: "She described the practice in Lover-era interviews and later wrote it into a song (\"Mastermind\"). This record is the anchor for every other entry in this collection: the eggs are real, planted, and intended to be found — which is exactly why unconfirmed readings still need labels.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Cultural impact of Taylor Swift", url: "https://en.wikipedia.org/wiki/Cultural_impact_of_Taylor_Swift", reliability: 2, type: "wiki" }, { name: "Swifties", url: "https://en.wikipedia.org/wiki/Swifties", reliability: 2, type: "wiki" }],
      relatedSlugs: ["debut:liner-notes-hidden-messages"],
    },
    {
      slug: "me-video-chicks-painting",
      kind: "easter_egg",
      title: "The 'ME!' video predicted the album's guest stars",
      claim: "A painting of the Dixie Chicks hangs on the wall of the 'ME!' video, spotted by fans within hours and read as a collab tease. Four months later the Chicks were on Lover, harmonizing on 'Soon You'll Get Better.'",
      evidence: "Egg roundups flagged the painting the day the video dropped in April 2019, months after Taylor had name-checked the group in her Elle essay — and the payoff shipped on the album that August. The same video gasped a real cat into existence: the kitten Brendon Urie offers her became Benjamin Button, adopted from the shoot.",
      confidence: "reputable_reporting",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift's 'ME!' Video Easter Eggs: Album Title, Her Next Single & More", url: "https://www.billboard.com/music/pop/taylor-swift-me-video-easter-eggs-8509007/", reliability: 4, type: "reputable_press" }, { name: "Taylor Swift's ''ME!'' Music Video: All the Hidden Easter Eggs and Symbolism", url: "https://www.eonline.com/news/1035688/taylor-swift-s-me-music-video-all-the-hidden-easter-eggs-and-symbolism", reliability: 4, type: "reputable_press" }],
      relatedSlugs: ["lover:mastermind-doctrine"],
    },
    {
      slug: "the-man-karma-graffiti",
      kind: "easter_egg",
      title: "The subway wall in 'The Man' maps her whole catalog",
      claim: "The graffiti wall Tyler Swift walks past in 'The Man' is tagged with her album titles, a 'Missing: if found return to Taylor Swift' poster standing in for the stolen debut — and, largest of all, the word KARMA.",
      evidence: "Outlets catalogued the wall shot when the video dropped in February 2020, mid-fight over her masters — the graffiti read as a map of the back catalog Scooter Braun had just bought, with the 13th Street station sign as a bonus. The KARMA tag fed the long-running lost-album theory; no Karma album ever surfaced, but 'Karma' the song arrived on Midnights and she has kept the wink going since.",
      confidence: "reputable_reporting",
      outcome: "confirmed",
      sources: [{ name: "Easter Eggs In Taylor Swift's 'The Man' Video Are Everywhere", url: "https://www.marieclaire.com/celebrity/a31129779/easter-eggs-taylor-swift-the-man/", reliability: 4, type: "reputable_press" }, { name: "7 Easter Eggs You Might Not Have Noticed in Taylor Swift's \"The Man\" Music Video", url: "https://www.distractify.com/p/taylor-swift-the-man-music-video-easter-eggs", reliability: 3, type: "reputable_press" }],
      relatedSlugs: ["midnights:karma-lost-album"],
    },
    {
      slug: "lover-house-eras-map",
      kind: "theory",
      title: "Every room in the Lover house is an era",
      claim: "Fans read each room of the 'Lover' video's snow-globe house as one of her albums — the red room for Red, the hazy attic for reputation — with the starry ceiling revealed as Midnights, completing the house.",
      evidence: "The room-by-room mapping circulated for years before a viral TikTok matched every room to an album when Midnights was announced in 2022 and declared the house complete. Taylor liked the TikTok — E! and ABC Audio both covered it as a seeming nod of approval — but she has never confirmed the mapping outright, so the thumbs-up is as official as it gets.",
      confidence: "strong_fan_consensus",
      outcome: "partially_confirmed",
      sources: [{ name: "Taylor Swift Approves of This Theory About Her 10 Albums", url: "https://www.eonline.com/news/1344281/taylor-swift-approves-of-this-theory-about-her-10-albums", reliability: 4, type: "reputable_press" }, { name: "Taylor Swift seemingly confirms fan theory about the \"Lover\" house", url: "https://digital.abcaudio.com/news/taylor-swift-seemingly-confirms-fan-theory-about-lover-house", reliability: 3, type: "reputable_press" }],
      relatedSlugs: ["lover:mastermind-doctrine"],
    },
  ],
  "midnights": [
    {
      slug: "karma-lost-album",
      kind: "theory",
      title: "The lost \"Karma\" album",
      claim: "Long-running fan theory that a finished album called Karma was scrapped in 2016 when the era imploded — and that later karma references (the Midnights track above all) are Taylor winking at what was shelved.",
      evidence: "Built from 2016-era teasers fans read as an album hint, then supercharged when Midnights shipped a song literally called \"Karma.\" Never confirmed, never denied; every era adds a new \"proof\" and the theory keeps its engine running. Filed as beloved, unresolved canon.",
      confidence: "strong_fan_consensus",
      outcome: "pending",
      sources: [{ name: "Karma (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Karma_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
    },
    {
      slug: "bejeweled-speak-now-clues",
      kind: "easter_egg",
      title: "The Bejeweled video was a Speak Now announcement",
      claim: "Fans read the \"Bejeweled\" video — the purple gown, the pointed floor-three elevator button, the Enchanted-coded ballroom — as a coded reveal that Speak Now (Taylor's Version), album three, was next. It was.",
      evidence: "Taylor said on release day that the video was stuffed with easter eggs; the fandom filed the purple/third-floor cluster under Speak Now within hours. Just over six months later the Nashville announcement proved the read. The clean template of clue -> consensus -> confirmation.",
      confidence: "strong_fan_consensus",
      outcome: "confirmed",
      sources: [{ name: "Bejeweled (song)", url: "https://en.wikipedia.org/wiki/Bejeweled_(song)", reliability: 2, type: "wiki" }, { name: "Speak Now (Taylor's Version)", url: "https://en.wikipedia.org/wiki/Speak_Now_(Taylor%27s_Version)", reliability: 2, type: "wiki" }],
      relatedSlugs: ["lover:mastermind-doctrine"],
    },
    {
      slug: "vault-puzzles-1989",
      kind: "easter_egg",
      title: "The Google vault puzzles",
      claim: "To reveal the 1989 (Taylor's Version) vault track titles, fans had to collectively solve 33 million Google word puzzles — searching her name spilled a literal blue vault across the results page.",
      evidence: "An official, platform-scale scavenger hunt run with Google in September 2023; the fandom cleared the 33-million target in under a day (crashing the puzzle at one point) and the vault titles unlocked. Easter-egg culture as infrastructure.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "1989 (Taylor's Version)", url: "https://en.wikipedia.org/wiki/1989_(Taylor%27s_Version)", reliability: 2, type: "wiki" }],
    },
    {
      slug: "eight-nine-sofi",
      kind: "theory",
      title: "8/9: the date fans called in advance",
      claim: "Swifties bet 1989 (Taylor's Version) would be announced on August 9, 2023 — the final 2023 US Eras show, on 8/9 — after weeks of blue outfits and cursive-“T” hints. She announced it that night.",
      evidence: "A genuinely predictive win for fan numerology: date logic (8/9 = ’89), the color-code system (blue = 1989), and the tour calendar all pointed the same way, publicly, before the show. Documented as called-in-advance rather than retrofitted.",
      confidence: "strong_fan_consensus",
      outcome: "confirmed",
      sources: [{ name: "1989 (Taylor's Version)", url: "https://en.wikipedia.org/wiki/1989_(Taylor%27s_Version)", reliability: 2, type: "wiki" }],
      relatedSlugs: ["midnights:album-color-canon"],
    },
    {
      slug: "album-color-canon",
      kind: "theory",
      title: "Every era has a color",
      claim: "Fan canon assigns each album a color — gold Fearless, purple Speak Now, red Red, blue 1989, black reputation, pink Lover, grey folklore, rust evermore, midnight-blue Midnights — and Taylor signals eras by wearing the palette before announcing anything.",
      evidence: "The color system started as fan taxonomy and became a two-way channel: the Eras Tour staged each act in its color, and announcement-watching now runs on outfit forensics (blue before 1989 TV, purple before Speak Now TV). Repeatedly validated, never formally codified.",
      confidence: "strong_fan_consensus",
      outcome: "partially_confirmed",
      sources: [{ name: "The Eras Tour", url: "https://en.wikipedia.org/wiki/The_Eras_Tour", reliability: 2, type: "wiki" }, { name: "Cultural impact of Taylor Swift", url: "https://en.wikipedia.org/wiki/Cultural_impact_of_Taylor_Swift", reliability: 2, type: "wiki" }],
      relatedSlugs: ["midnights:eight-nine-sofi"],
    },
    {
      slug: "surprise-song-metagame",
      kind: "theory",
      title: "The surprise-song metagame",
      claim: "Eras Tour fans treated the nightly two-song acoustic set as a solvable system: a no-repeat rule, dwindling remaining-songs spreadsheets, and city-specific logic used to predict each night's picks.",
      evidence: "The no-repeat pattern held through most of 2023 (screwed-up songs earned reruns, by her own stage admission), making the community spreadsheets genuinely predictive — until the 2024 mashup era deliberately broke the system. Pattern real; rule informal; expiration confirmed.",
      confidence: "reputable_reporting",
      outcome: "partially_confirmed",
      sources: [{ name: "The Eras Tour", url: "https://en.wikipedia.org/wiki/The_Eras_Tour", reliability: 2, type: "wiki" }],
    },
    {
      slug: "friendship-bracelets",
      kind: "easter_egg",
      title: "One lyric started the bracelet economy",
      claim: "The Eras Tour friendship-bracelet ritual — millions of beaded bracelets made, traded, and stacked at every show — grew out of a single \"You're on Your Own, Kid\" lyric about making friendship bracelets and taking the moment.",
      evidence: "Fans took the lyric as an instruction within weeks of opening night; by mid-2023 bracelet trading was the tour's defining ritual, covered everywhere from local news to bead-shortage business stories. A lyric became a subculture — the fandom's favorite kind of easter egg: one they built themselves.",
      confidence: "reputable_reporting",
      outcome: "confirmed",
      sources: [{ name: "The Eras Tour", url: "https://en.wikipedia.org/wiki/The_Eras_Tour", reliability: 2, type: "wiki" }, { name: "Swifties", url: "https://en.wikipedia.org/wiki/Swifties", reliability: 2, type: "wiki" }],
    },
  ],
  "red": [
    {
      slug: "twenty-two-liner-note-code",
      kind: "easter_egg",
      title: "A liner-note code names the friends behind \"22\"",
      claim: "The 2012 Red CD booklet hid a capitalization code inside \"22\" that decodes to \"ASHLEY DIANNA CLAIRE SELENA\" — a shout-out to the real friends the song's carefree night was inspired by.",
      evidence: "Following the same hidden-capital-letters technique used on her earlier album booklets, the \"22\" lyric sheet's decoded message names four friends rather than a romantic subject, matching the song's own framing as a friendship anthem about a birthday night out.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift's 13 Best Liner Note Secret Messages", url: "https://www.billboard.com/music/music-news/taylor-swift-liner-note-secret-messages-6296379/", reliability: 4, type: "reputable_press" }],
    },
    {
      slug: "vault-track-word-puzzle-reveal",
      kind: "easter_egg",
      title: "A word puzzle unlocks the Red (Taylor's Version) vault tracks",
      claim: "On Aug. 5, 2021, Taylor posted an interactive word-puzzle video across social media that, once solved, revealed the \"From the Vault\" collaborators and titles — including Chris Stapleton, Phoebe Bridgers, \"Babe,\" \"Better Man,\" and the All Too Well (10 Minute Version) — ahead of the album's release.",
      evidence: "The puzzle format built on the anagram-teaser approach from the Fearless re-record, this time rewarding fans who solved it with a bonus image. All of the revealed information — the featured artists and track titles — matched the official track list confirmed at release.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Red (Taylor's Version)", url: "https://en.wikipedia.org/wiki/Red_(Taylor%27s_Version)", reliability: 2, type: "wiki" }],
      relatedSlugs: ["fearless:vault-track-anagram-reveal"],
    },
    {
      slug: "not-a-lot-going-on-shirt",
      kind: "easter_egg",
      title: "The \"22\" video T-shirt became a years-long clue vehicle",
      claim: "In the 2013 \"22\" video Taylor wears a tee reading \"Not a lot going on at the moment.\" Fans have tracked the phrase ever since: she revives it as a caption before big moves, and on the Eras Tour her \"22\" tees carried red letters that scramble to \"Speak Now (Taylor's Version)\" — the album she announced next.",
      evidence: "The shirt debuts in the Red-era \"22\" video (2012 album, 2013 single), then takes on a life of its own. On April 27, 2020 Taylor captioned a selfie with the same words and fans went hunting for a reveal — early guesses ran to a \"Cruel Summer\" single (Refinery29) — months before folklore surprise-dropped that July. On the Eras Tour \"22\" set she wore variants (\"A lot going on at the moment\") whose red-highlighted words — \"A lot,\" \"never,\" \"ever,\" \"ew\" — fans unscrambled on April 1, 2023 to \"Speak Now Taylor's Version,\" weeks before she announced that re-record. Read honestly: the recurring-caption sightings are fan tracking, not a confirmed cipher, but the Eras Tour anagram was staged deliberately and did precede the announcement.",
      confidence: "strong_fan_consensus",
      outcome: "partially_confirmed",
      sources: [{ name: "Taylor Swift Is Not Being Subtle With Her Clues Anymore", url: "https://www.refinery29.com/en-us/2020/04/9746793/taylor-swift-not-a-lot-going-on-photo-theories-clues", reliability: 4, type: "reputable_press" }, { name: "Taylor Swift Fans Seemingly Decode Hidden Message In 'Eras Tour' Outfits", url: "https://www.iheart.com/content/2023-04-01-taylor-swift-fans-seemingly-decode-hidden-message-in-eras-tour-outfits/", reliability: 3, type: "reputable_press" }],
      relatedSlugs: ["speak-now:speak-now-tv-tracklist-reveal"],
    },
    {
      slug: "i-bet-you-think-about-me-video-eggs",
      kind: "easter_egg",
      title: "Blake Lively's \"I Bet You Think About Me\" video is stuffed with self-referential eggs",
      claim: "Blake Lively's directorial debut for \"I Bet You Think About Me\" (November 2021) tucks Taylor's own catalog into the frame: she wears the red diamond-shaped ring from the Red (Taylor's Version) cover, gives the bride a red scarf nodding to \"All Too Well,\" and the reception light shifts to deep blue as a wink to the song \"Red.\"",
      evidence: "Released alongside Red (Taylor's Version) and co-treated by Taylor and Lively, the video became an egg hunt. Reporters cataloged them: the RED-cover ring; the red scarf handed over mid-toast, a direct callback to \"All Too Well\"; a lighting change from bright to dark blue during the dance, read as a nod to the track \"Red\"; and a tiered cake carrying 13 (Taylor's number) and 26 (her age when 1989 released), its birds echoing the 1989 cover, with a white-roses-turning-red set piece mirroring Alice in Wonderland (\"Wonderland\" is a 1989 deluxe track). Those 1989-leaning details also fuel the separate next-re-record reading.",
      confidence: "reputable_reporting",
      outcome: "confirmed",
      sources: [{ name: "8 'I Bet You Think About Me' Easter Eggs", url: "https://www.newsweek.com/taylor-swift-i-bet-you-think-about-me-easter-eggs-1989-speak-now-miles-teller-1649696", reliability: 4, type: "reputable_press" }, { name: "Taylor Swift, Blake Lively Debut I Bet You Think About Me Music Video", url: "https://variety.com/2021/music/news/taylor-swift-blake-lively-i-bet-you-think-about-me-music-video-miles-teller-1235111991/", reliability: 4, type: "reputable_press" }],
      relatedSlugs: ["red:i-bet-you-think-about-me-rerecord-clues"],
    },
    {
      slug: "all-too-well-original-ten-minutes",
      kind: "theory",
      title: "Fans were right: \"All Too Well\" was born a 10-minute song",
      claim: "Years before the 2021 release, fans traded the legend that \"All Too Well\" began as a much longer song, cut down for Red. Taylor confirmed it: she first wrote a roughly ten-minute version and phoned co-writer Liz Rose to help \"filter it down\" to the album's five-and-a-half minutes.",
      evidence: "Taylor has recounted (Good Morning America) that the song poured out at about ten minutes and that she called Liz Rose — \"Come over, we've gotta filter this down\" — to pare it for Red (2012); the original even carried profanity later scrubbed for the album cut. The full \"All Too Well (10 Minute Version)\" arrived on Red (Taylor's Version) on November 12, 2021, with the short film a day later, vindicating the long-held fan belief that a longer \"real\" version existed. Kept strictly to songwriting history — the song's subject is out of scope.",
      confidence: "confirmed_interview",
      outcome: "confirmed",
      sources: [{ name: "'All Too Well': Behind Taylor Swift's Ten Minute Long Heartbreak Anthem", url: "https://www.wideopencountry.com/all-too-well/", reliability: 4, type: "reputable_press" }, { name: "All Too Well (10 Minute Version)", url: "https://en.wikipedia.org/wiki/All_Too_Well_(10_Minute_Version)", reliability: 2, type: "wiki" }],
      relatedSlugs: ["red:vault-track-word-puzzle-reveal"],
    },
    {
      slug: "i-bet-you-think-about-me-rerecord-clues",
      kind: "theory",
      title: "The \"I Bet You Think About Me\" video was read as a map to the next re-records",
      claim: "Fans combed \"I Bet You Think About Me\" for hints about the next re-records: the cake's seagulls and its 13/26 numbers pointed to 1989, while the wedding setting and her billowing red gown echoed Speak Now. Both albums did follow in 2023 — though Taylor never confirmed the clues were planted.",
      evidence: "November 2021 coverage (Newsweek, E!) laid out the competing reads: birds on the cake mirroring the 1989 cover, \"26\" for her age when 1989 released, and Alice-in-Wonderland roses tied to 1989's \"Wonderland\"; against that, the wedding theme and a voluminous red dress resembling the Speak Now deluxe gown argued Speak Now was up next. In the event, both were re-recorded in 2023 — Speak Now (Taylor's Version) in July, 1989 (Taylor's Version) in October — so both reads landed, in that order. Marked partially confirmed: the sequencing bore out, but whether any single frame was an intentional clue stays fan speculation.",
      confidence: "strong_fan_consensus",
      outcome: "partially_confirmed",
      sources: [{ name: "8 'I Bet You Think About Me' Easter Eggs That Prove Taylor's Next Re-Record", url: "https://www.newsweek.com/taylor-swift-i-bet-you-think-about-me-easter-eggs-1989-speak-now-miles-teller-1649696", reliability: 4, type: "reputable_press" }, { name: "All the Easter Eggs in Taylor Swift's \"I Bet You Think About Me\" Music Video", url: "https://www.eonline.com/news/1309712/all-the-easter-eggs-in-taylor-swifts-i-bet-you-think-about-me-music-video-with-miles-teller", reliability: 4, type: "reputable_press" }],
      relatedSlugs: ["red:i-bet-you-think-about-me-video-eggs", "speak-now:speak-now-tv-tracklist-reveal"],
    },
  ],
  "reputation": [
    {
      slug: "snake-reclamation",
      kind: "easter_egg",
      title: "Reclaiming the snake",
      claim: "After the 2016 feud fallout flooded her comments with snake emoji, the reputation rollout weaponized it: glitchy snake teasers announced the era, a serpent slithered through the visuals, and a giant snake named Karyn towered over the stadium tour.",
      evidence: "The era launch was three wordless snake videos posted to blacked-out socials; 'Look What You Made Me Do' leaned all the way in (a snake serving tea); the Stadium Tour made the snake a mascot. A documented, deliberate reclamation arc — the insult became the brand.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Look What You Made Me Do", url: "https://en.wikipedia.org/wiki/Look_What_You_Made_Me_Do", reliability: 2, type: "wiki" }, { name: "Kanye West–Taylor Swift feud", url: "https://en.wikipedia.org/wiki/Kanye_West%E2%80%93Taylor_Swift_feud", reliability: 2, type: "wiki" }],
    },
    {
      slug: "lwymmd-nils-sjoberg-gravestone",
      kind: "easter_egg",
      title: "A gravestone for Nils Sjöberg",
      claim: "In the 'Look What You Made Me Do' graveyard, the headstone beside the grave zombie-Taylor digs reads Nils Sjöberg — the Swedish pseudonym she used to secretly co-write Calvin Harris's 'This Is What You Came For,' buried on camera.",
      evidence: "Outlets ran full decoder guides the week the video premiered at the 2017 VMAs, and the gravestone was near the top of every list. The pseudonym's story was already public — the co-write came out messily after the Harris breakup in July 2016 — which is what made burying the name read as such a pointed goodbye to the era of hiding her own credits.",
      confidence: "reputable_reporting",
      outcome: "confirmed",
      sources: [{ name: "All the References You Might Have Missed in Taylor Swift's 'Look What You Made Me Do' Video", url: "https://time.com/4918411/taylor-swift-look-what-you-made-me-do-music-video-references/", reliability: 4, type: "reputable_press" }, { name: "Taylor Swift's 'Look What You Made Me Do' Video Decoded: 13 Things You Missed", url: "https://www.rollingstone.com/music/music-news/taylor-swifts-look-what-you-made-me-do-video-decoded-13-things-you-missed-126268/", reliability: 4, type: "reputable_press" }],
      relatedSlugs: ["reputation:snake-reclamation"],
    },
    {
      slug: "lwymmd-dollar-bill",
      kind: "theory",
      title: "The single dollar in the bathtub of diamonds",
      claim: "In the 'Look What You Made Me Do' bathtub-of-jewels shot, a lone dollar bill sits beside her. Fans read it as the symbolic $1 she sued for — and won — in her Denver sexual assault trial, days before the video premiered.",
      evidence: "The timing does the arguing: the jury found in her favor on August 14, 2017, awarding the single symbolic dollar she had asked for, and the video premiered at the VMAs on August 27. Outlets covered the fan reading immediately, and a year later fans held up $1 bills at her Tampa show on the verdict's anniversary. Taylor has never confirmed the detail herself — which is why this stays a theory, not a fact.",
      confidence: "strong_fan_consensus",
      outcome: "pending",
      sources: [{ name: "The $1 Taylor Swift won during her sexual assault trial makes an appearance in \"Look What You Made Me Do\"", url: "https://hellogiggles.com/taylor-swift-sexual-assault-trial-music-video/", reliability: 3, type: "reputable_press" }, { name: "Taylor Swift Speaks Out About Believing Sexual Assault Victims on Anniversary of Her Trial Verdict", url: "https://time.com/5367874/taylor-swift-sexual-assault/", reliability: 4, type: "reputable_press" }],
      relatedSlugs: ["reputation:lwymmd-nils-sjoberg-gravestone"],
    },
    {
      slug: "old-taylors-ending",
      kind: "easter_egg",
      title: "A courtroom of old Taylors",
      claim: "The final 40 seconds of 'Look What You Made Me Do' line up a squabbling crowd of past Taylors — the personas from every earlier scene and era — who bicker in the words her own critics used, ending with the 2009 VMAs version snapping 'I would very much like to be excluded from this narrative,' met by a collective 'SHUT UP!'",
      evidence: "Each figure is a resurrected version of herself — the 'You Belong With Me' Junior Jewels tee, the 2014 Met Gala look, the snake-throne queen, zombie-Taylor from the video's own graveyard — and their lines quote real jabs ('There she goes playing the victim again,' 'Stop making that surprised face, it's so annoying'). The closing quote lifts verbatim from the statement she posted during the 2016 phone-call controversy, so the gag turns her most-mocked moments into a chorus she talks back to. Video director Joseph Kahn later confirmed that the ending was conceived around having all the Taylors talk to one another, and that the video's deeper messages came from Taylor.",
      confidence: "confirmed_interview",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift's 'Look What You Made Me Do' Video Decoded: 13 Things You Missed", url: "https://www.rollingstone.com/music/music-news/taylor-swifts-look-what-you-made-me-do-video-decoded-13-things-you-missed-126268/", reliability: 4, type: "reputable_press" }, { name: "All the References You Might Have Missed in Taylor Swift's 'Look What You Made Me Do' Video", url: "https://time.com/4918411/taylor-swift-look-what-you-made-me-do-music-video-references/", reliability: 4, type: "reputable_press" }, { name: "Director Joseph Kahn Shares Secrets Behind Taylor Swift's Most Iconic Music Videos", url: "https://www.etonline.com/director-joseph-kahn-shares-secrets-behind-taylor-swifts-most-iconic-music-videos-exclusive-112418", reliability: 4, type: "reputable_press" }],
      relatedSlugs: ["reputation:snake-reclamation", "reputation:lwymmd-nils-sjoberg-gravestone"],
    },
    {
      slug: "lwymmd-et-tu-brute",
      kind: "easter_egg",
      title: "\"Et Tu, Brute?\" on the snake throne",
      claim: "In 'Look What You Made Me Do,' the arm of Taylor's throne and the columns flanking it are carved with 'Et Tu, Brute?' — Caesar's dying words to the friend who helped stab him — while a snake slithers up to pour her a cup of tea.",
      evidence: "The inscription and tea-pouring snake are directly visible in Taylor's official music video. The Latin tag frames the era's betrayal theme in one prop: Julius Caesar realizing his ally Brutus was among his assassins. Paired with the tea-pouring snake — a literal 'serving tea' pun that also reclaims the snake-emoji pile-on — the throne scene reads as the album's thesis staged as set design. Named in the frame-by-frame decoder guides that ran the week the video premiered.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift - Look What You Made Me Do", url: "https://www.youtube.com/watch?v=3tmd-ClpJxA", reliability: 5, type: "official" }, { name: "Taylor Swift's 'Look What You Made Me Do' Video Decoded: 13 Things You Missed", url: "https://www.rollingstone.com/music/music-news/taylor-swifts-look-what-you-made-me-do-video-decoded-13-things-you-missed-126268/", reliability: 4, type: "reputable_press" }, { name: "All the References You Might Have Missed in Taylor Swift's 'Look What You Made Me Do' Video", url: "https://time.com/4918411/taylor-swift-look-what-you-made-me-do-music-video-references/", reliability: 4, type: "reputable_press" }],
      relatedSlugs: ["reputation:snake-reclamation"],
    },
    {
      slug: "reputation-tabloid-cover",
      kind: "easter_egg",
      title: "A cover printed like the tabloids",
      claim: "The reputation cover is built to look like newspaper: her face half-buried under black-and-white headline print. Zoom in and the 'headlines' aren't stories at all — the text just repeats 'Taylor Swift' over and over, turning years of tabloid coverage into a wall of her own name.",
      evidence: "The design (shot by Mert & Marcus) mimics tabloid front-page typography as a comment on the media narrative that had defined her since 2016 — and the rollout extended the joke, with Target-exclusive physical copies packaged as two magazine-style booklets styled like gossip rags. Outlets read the repeated-name newsprint as her taking the pen back: the press wrote her story, so she reprinted it as nothing but her signature.",
      confidence: "reputable_reporting",
      outcome: "confirmed",
      sources: [{ name: "What Does Taylor Swift's 'Reputation' Album Cover Art Mean?", url: "https://www.bustle.com/p/what-does-taylor-swifts-reputation-album-cover-art-mean-the-singer-may-be-reclaiming-her-image-78525", reliability: 3, type: "reputable_press" }, { name: "Taylor Swift's New Album Cover for 'Reputation' Is...Headline-Making", url: "https://www.papermag.com/taylor-swifts-new-album-cover-for-reputation-is-headline-making", reliability: 3, type: "reputable_press" }],
      relatedSlugs: ["reputation:snake-reclamation"],
    },
  ],
  "speak-now": [
    {
      slug: "never-grow-up-liner-note-code",
      kind: "easter_egg",
      title: "A liner-note code confirms when she moved out",
      claim: "The 2010 Speak Now CD booklet hid a capitalization code inside \"Never Grow Up\" that decodes to \"MOVED OUT IN JULY\" — a real detail about Taylor leaving her family's home, matching the song's own coming-of-age theme.",
      evidence: "Using the same hidden-capital-letters technique found across her early album booklets, the \"Never Grow Up\" lyric sheet's decoded phrase lines up with Taylor's own account of moving into her first apartment that July, turning a lyric-sheet puzzle into a factual footnote on the song.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift's 13 Best Liner Note Secret Messages", url: "https://www.billboard.com/music/music-news/taylor-swift-liner-note-secret-messages-6296379/", reliability: 4, type: "reputable_press" }],
    },
    {
      slug: "speak-now-tv-tracklist-reveal",
      kind: "easter_egg",
      title: "The Speak Now (Taylor's Version) track list drops on social media",
      claim: "Taylor unveiled the full Speak Now (Taylor's Version) track list, including its \"From the Vault\" songs, directly via social media on June 5, 2023, ahead of the album's July 7, 2023 release — continuing her established pattern of announcing re-record vault tracks in a dedicated reveal moment rather than a traditional press release.",
      evidence: "Fearless and Red (Taylor's Version) vault tracks had each been revealed through a cryptic scrambled-word \"vault\" puzzle video fans had to decode. Speak Now (TV) skipped the puzzle: a single, fan-facing announcement post named every vault track and its guest directly, rather than a label press cycle — a simplification of the earlier playbook, not a repeat of it.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Speak Now (Taylor's Version)", url: "https://en.wikipedia.org/wiki/Speak_Now_(Taylor%27s_Version)", reliability: 2, type: "wiki" }],
      relatedSlugs: ["fearless:vault-track-anagram-reveal", "red:vault-track-word-puzzle-reveal"],
    },
    {
      slug: "mine-leak-rush-release",
      kind: "easter_egg",
      title: "A leak forced \"Mine\" out early",
      claim: "Lead single \"Mine\" was not meant to arrive on August 4, 2010 — a low-quality MP3 leaked online that day, and Big Machine rush-released the finished song to country radio and iTunes within hours, roughly two weeks ahead of its planned mid-August debut.",
      evidence: "Taylor had been teasing the single with a countdown when the leak collapsed the timeline; rather than let a bootleg define the song, the label pushed the official version out the same afternoon. Taylor said the leak left her in tears, but the rushed release still shot to No. 1 on iTunes, and Speak Now followed on October 25, 2010. It is an early, accidental version of the rollout chaos her later eras would stage on purpose.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift Rush Releases \"Mine\" to Radio After Internet Leak, \"Speak Now\" Album in October", url: "https://www.cbsnews.com/news/taylor-swift-rush-releases-mine-to-radio-after-internet-leak-speak-now-album-in-october/", reliability: 4, type: "reputable_press" }, { name: "Taylor Swift Unleashes New Single \"Mine\"", url: "https://www.rollingstone.com/music/music-news/taylor-swift-unleashes-new-single-mine-78726/", reliability: 4, type: "reputable_press" }],
    },
    {
      slug: "speak-now-tour-surprise-covers",
      kind: "easter_egg",
      title: "The surprise-song tradition was born on this tour",
      claim: "The Speak Now World Tour (February 2011–March 2012) is where Taylor first began slipping a different acoustic cover into the set city by city — often a song by a local or homegrown artist — the ritual that later hardened into the Eras Tour's nightly \"surprise song.\"",
      evidence: "Seated under a lit tree with a ukulele or guitar, she used the acoustic segment to break from the otherwise-rehearsed show: Alanis Morissette and Avril Lavigne in Toronto, the Beach Boys and Kim Carnes' \"Bette Davis Eyes\" in Los Angeles, the Fray's \"How to Save a Life\" in Denver. \"You'll have a lot of people who will come to more than one show,\" she explained, \"and I want them to get a different experience every time.\" By the Red Tour the surprise slot had become a permanent fixture of the setlist, and the Eras Tour turned it into two songs a night.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Speak Now World Tour", url: "https://en.wikipedia.org/wiki/Speak_Now_World_Tour", reliability: 2, type: "wiki" }, { name: "Taylor Swift Eras Tour: Every Surprise Song From Taylor's Setlist So Far", url: "https://www.capitalfm.com/artists/taylor-swift/eras-tour-surprise-songs-setlist/", reliability: 3, type: "reputable_press" }],
    },
    {
      slug: "speak-now-written-entirely-alone",
      kind: "theory",
      title: "She wrote the whole album alone — on purpose",
      claim: "Fans read Speak Now (2010) as Taylor answering the critics who doubted she wrote her own songs: every track on the 14-song standard edition is credited to her and her alone, with no co-writers — a point she has said was deliberate. The lone asterisk is a deluxe-only bonus, \"If This Was a Movie,\" co-written with Martin Johnson.",
      evidence: "Taylor has framed the solo writing as a reaction to critics' doubts about her songwriting, and described finishing songs on the road with no collaborator on hand: \"I'd get my best ideas at 3:00 a.m. in Arkansas, and I didn't have a co-writer around so I would just finish it.\" Released Oct. 25, 2010 and co-produced with Nathan Chapman, the standard album carries only her name in every writing credit — the claim is verifiable from the credits themselves, not a reading of the lyrics.",
      confidence: "confirmed_interview",
      outcome: "confirmed",
      sources: [{ name: "Speak Now", url: "https://en.wikipedia.org/wiki/Speak_Now", reliability: 2, type: "wiki" }],
      relatedSlugs: ["speak-now:long-live-band-and-fans-tribute"],
    },
    {
      slug: "long-live-band-and-fans-tribute",
      kind: "theory",
      title: "The closer is a love song — to her band and her fans",
      claim: "Fans read the Speak Now closer \"Long Live\" not as a romance but as a thank-you to the people who built the era with her — her band, her crew, and her audience. It is a reading Taylor confirmed, calling it \"the first love song that I've written to my team.\"",
      evidence: "Introducing the song, Taylor described it as being \"about my band, and my producer, and all the people who have helped us build this brick by brick,\" and cast it as replaying a photo album of award-show and stadium moments shared with her collaborators and crowd. The royalty-and-graduation imagery is universal enough that it also reads as a graduation anthem, but her stated intent — the closing track of the 14-song standard edition — was gratitude to her team.",
      confidence: "confirmed_interview",
      outcome: "confirmed",
      sources: [{ name: "Long Live (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Long_Live_(Taylor_Swift_song)", reliability: 2, type: "wiki" }, { name: "Long Live by Taylor Swift", url: "https://www.songfacts.com/facts/taylor-swift/long-live", reliability: 3, type: "reputable_press" }],
      relatedSlugs: ["speak-now:speak-now-written-entirely-alone"],
    },
  ],
  "tloas": [
    {
      slug: "orange-era-clues",
      kind: "theory",
      title: "The orange era, called before the announcement",
      claim: "Through the TTPD stretch, TS12 watchers bet the next era's color was orange — reading glittery orange accents into late Eras Tour looks and posts. When The Life of a Showgirl arrived, the branding was orange head to toe.",
      evidence: "The album was announced on the New Heights podcast in August 2025 wrapped in glittering orange (and mint) — instantly validating months of color-watching. How much of the pre-announcement orange was planted versus pattern-matched has never been itemized, so the call is graded, not fully confirmed.",
      confidence: "strong_fan_consensus",
      outcome: "partially_confirmed",
      sources: [{ name: "The Life of a Showgirl", url: "https://en.wikipedia.org/wiki/The_Life_of_a_Showgirl", reliability: 2, type: "wiki" }],
      relatedSlugs: ["midnights:album-color-canon"],
    },
    {
      slug: "ophelia-rewrite",
      kind: "easter_egg",
      title: "Ophelia, rewritten to live",
      claim: "The lead single \"The Fate of Ophelia\" flips Shakespeare: where Hamlet's Ophelia drowns in abandonment, the song's narrator is pulled out of that fate by love — a literary inversion fans and critics mapped line by line.",
      evidence: "The allusion is the title; coverage of the single documented the Hamlet inversion as the song's central conceit, continuing the quill-pen literary streak from TTPD (Peter Pan, Cassandra, Clara Bow).",
      confidence: "reputable_reporting",
      outcome: "confirmed",
      sources: [{ name: "The Fate of Ophelia", url: "https://en.wikipedia.org/wiki/The_Fate_of_Ophelia", reliability: 2, type: "wiki" }],
      relatedSlugs: ["ttpd:peter-pan-throughline"],
    },
    {
      slug: "father-figure-george-michael-interpolation",
      kind: "easter_egg",
      title: "Father Figure, built on George Michael's own",
      claim: "Track 4, \"Father Figure,\" is not just named after George Michael's 1987 classic — it interpolates it, rebuilding the hook and melody of Michael's chorus inside a TS12 song. The tell is in the credits: George Michael is listed as a co-writer, a Wham!-era hitmaker folded whole into the album decades on.",
      evidence: "An interpolation re-records a song's musical elements rather than sampling the original master, and it shows up as a formal songwriting credit — which is exactly where this one is documented, with George Michael credited as a co-writer on \"Father Figure.\" Coverage describes Taylor's track as an interpolation of Michael's song, reusing its title-line hook and a similar melody. Reaching back into a specific catalog and crediting it in the liner metadata is the same buried-clue instinct that runs through her rollouts; here the clue is hiding in the songwriting credits themselves.",
      confidence: "reputable_reporting",
      outcome: "confirmed",
      sources: [{ name: "Father Figure (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Father_Figure_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      relatedSlugs: ["tloas:ophelia-rewrite"],
    },
    {
      slug: "eldest-daughter-track-five",
      kind: "easter_egg",
      title: "Eldest Daughter and the Track 5 rule",
      claim: "Swifties treat track 5 as sacred: since Fearless, the fifth song on each album is reliably her most emotionally exposed — a pattern she has spoken about and fans now brace for. On The Life of a Showgirl, track 5 is \"Eldest Daughter,\" and reviewers immediately read it as this album's Track 5 confessional.",
      evidence: "The \"Track 5\" convention — the album's most vulnerable, confessional song deliberately placed fifth — is a long-documented Taylor trademark running through the catalog (e.g. \"The Archer\" on Lover, \"mirrorball\" on folklore). \"Eldest Daughter\" is the fifth track on The Life of a Showgirl, and critics placed it directly in that lineage, comparing it to \"The Archer\" and \"mirrorball\" and their shared themes of perseverance, desperation and perfectionism. The egg is structural rather than hidden-in-the-art: knowing the rule tells a listener where to look for the album's emotional core before pressing play.",
      confidence: "reputable_reporting",
      outcome: "confirmed",
      sources: [{ name: "Eldest Daughter", url: "https://en.wikipedia.org/wiki/Eldest_Daughter", reliability: 2, type: "wiki" }],
      relatedSlugs: ["tloas:ophelia-rewrite"],
    },
    {
      slug: "ophelia-video-self-references",
      kind: "easter_egg",
      title: "The Ophelia video, hiding the rest of the album",
      claim: "The video for lead single \"The Fate of Ophelia\" is seeded with easter eggs — visual callbacks to other songs on The Life of a Showgirl and to moments from the Eras Tour — plus a brief cameo of Vancouver's Science World near the end. The rollout hid the album inside its own opening visual.",
      evidence: "Documentation of the video notes that it features easter eggs referencing other tracks from The Life of a Showgirl and moments from the Eras Tour, and that Vancouver's Science World makes a brief appearance near the end. Planting references to the record's other songs inside the first video is the same self-referential clue-laying — the album teasing itself — that has defined her visual rollouts since the reputation and Lover eras; here it runs through the era's very first frames.",
      confidence: "reputable_reporting",
      outcome: "confirmed",
      sources: [{ name: "The Fate of Ophelia", url: "https://en.wikipedia.org/wiki/The_Fate_of_Ophelia", reliability: 2, type: "wiki" }],
      relatedSlugs: ["tloas:ophelia-rewrite"],
    },
    {
      slug: "ts12-twelfth-album-twelve-tracks",
      kind: "easter_egg",
      title: "TS12: the twelfth album, twelve tracks",
      claim: "The Life of a Showgirl is Taylor's twelfth studio album, and its standard edition runs exactly twelve tracks — the era Swifties had been counting toward and tagging \"TS12\" before it had a title. Fans read the twelve-on-twelfth alignment as one more of her deliberate number games.",
      evidence: "The album is her twelfth studio LP and its standard tracklist is twelve songs long — both plain, documented facts. Taylor has a long, self-acknowledged history of number play (the recurring 13 motif; release dates and track counts used as planted clues), which is why fans read the twelve-on-twelfth symmetry as intentional rather than incidental. The alignment itself is verified fact; the intent behind it is the fan reading, so the egg is graded partially confirmed — the numbers line up, but Taylor has not itemized this one as a wink.",
      confidence: "strong_fan_consensus",
      outcome: "partially_confirmed",
      sources: [{ name: "The Life of a Showgirl", url: "https://en.wikipedia.org/wiki/The_Life_of_a_Showgirl", reliability: 2, type: "wiki" }],
      relatedSlugs: ["tloas:orange-era-clues"],
    },
    {
      slug: "showgirl-spotify-canvas-color-swap",
      kind: "theory",
      title: "The Spotify canvas colors that set off a re-recording hunt",
      claim: "Over the weekend of July 18–19, 2026, fans clocked that Taylor had quietly swapped the Spotify canvases — the short looping visuals behind a track — on three songs: \"I Knew It, I Knew You\" went green, its Piano Version purple, and \"Blank Space\" red. Swifties read the color-coding as an easter-egg tease of a re-recording, most loudly a debut \"Taylor's Version.\"",
      evidence: "The change itself is documented — Just Jared (Bradley Stern, July 20) and geo.tv both logged the three new canvases — but nothing was announced, and Just Jared's own line was that \"no one seems to know what it means yet.\" Everything past the color swap is fan decoding, and the reads openly contradict each other. The loudest leans on green as debut's color, pointing to a debut \"Taylor's Version.\" A date-code version lines up the three albums' release days — debut on Oct 24, Speak Now on Oct 25, Red on Oct 22 — and fixates on the missing Oct 23, a Friday in 2026 and Taylor's usual release day. A numerology version adds the albums' places in her catalog (Red 4th + Speak Now 3rd + reputation 6th = 13). None of them cleanly accounts for \"Blank Space,\" a 1989 track that belongs to none of those records — which is exactly why it stays a theory. If a re-recording or new release follows, this promotes with the citation; if it goes quiet, it fades.",
      confidence: "plausible",
      outcome: "pending",
      sources: [{ name: "Taylor Swift Fans Spiral Over Tiny Spotify Change, Fueling New Album & 'Taylor's Version' Theories", url: "https://www.justjared.com/2026/07/20/taylor-swift-fans-spiral-over-tiny-spotify-change-fueling-new-album-taylors-version-theories/", reliability: 3, type: "reputable_press" }, { name: "Taylor Swift sparks curiosity with new \"Easter Eggs\" on streaming platforms", url: "https://www.geo.tv/latest/673940-taylor-swift-sparks-curiosity-with-new-easter-eggs-on-streaming-platforms", reliability: 3, type: "reputable_press" }],
      relatedSlugs: ["tloas:orange-era-clues"],
    },
    {
      slug: "gracie-abrams-death-wish-not-about-taylor",
      kind: "theory",
      title: "The \"Death Wish\" theory, shut down by its own co-writer",
      claim: "When Gracie Abrams's \"Death Wish\" circulated, some Swifties read its lines about power, cruelty and a damaged relationship as a coded shot at Taylor — folding Abrams, one of Taylor's close friends and Eras Tour openers, into a supposed hidden feud.",
      evidence: "The song's co-writer and producer, Aaron Dessner — the same collaborator behind folklore and evermore — was asked about the theory head-on in a July 21, 2026 Billboard interview and shut it down flatly: \"Yeah, definitely not.\" He said Abrams wrote it \"at a time when [Gracie] was writing about a friend's ex, being in a bad relationship,\" and added that he did not even know the person's identity — so there is no hidden third party to expose, and nothing about Taylor in it. NME and E! News carried the same denial. The reading was always a fan inference stacked on a public friendship, never anything Abrams or Dessner had suggested; on the record from the man who helped write the song, it resolves debunked.",
      confidence: "confirmed_interview",
      outcome: "debunked",
      sources: [{ name: "Aaron Dessner Sets the Record Straight on Gracie Abrams' 'Death Wish': It's 'Definitely Not' About Taylor Swift", url: "https://www.billboard.com/music/music-news/aaron-dessner-gracie-abrams-death-wish-noah-kahan-interview-1236299956/", reliability: 4, type: "reputable_press" }, { name: "The National's Aaron Dessner speaks out on if Gracie Abrams' 'Death Wish' is about Taylor Swift", url: "https://www.nme.com/news/music/the-nationals-aaron-dessner-speaks-out-on-if-gracie-abrams-death-wish-is-about-taylor-swift-3958555", reliability: 4, type: "reputable_press" }, { name: "Gracie Abrams Song \"Death Wish\" Is Not About Taylor Swift", url: "https://www.eonline.com/news/1434254/gracie-abrams-song-death-wish-is-not-about-taylor-swift", reliability: 3, type: "reputable_press" }],
    },
    {
      slug: "showgirl-esb-green-ts-debut-era",
      kind: "theory",
      title: "The green Empire State Building and the \"TS\" logos that lit a new-era hunt",
      claim: "On Aug 20, 2026 the Empire State Building glowed green, its official X account captioning it \"WhaTS happening?\" — capitalized \"TS\" reading as Taylor's initials. The same day, a green \"TS\" logo turned up on a black wall at an undisclosed spot, with more spotted across several cities. Swifties read the convergence as an easter-egg cue for her next era.",
      evidence: "The facts are on the record and sourced (the ESB light change and the ESB official account's \"WhaTS happening?\" post); everything past them is fan decoding, and the reads openly diverge. The loudest ties green to her 2006 self-titled debut — whose 20th anniversary lands Oct 24, 2026 — and reads it as a debut \"Taylor's Version\" tease; others point instead to Reputation's black-and-green snake imagery, the other un-re-recorded title. Fans noted the font and layout match none of her past album branding. The pattern is real — the ESB lit orange in Aug 2025 for The Life of a Showgirl and blue in Jul 2026 for the wedding — but so is the countervailing coverage (\"Swifties calm down, not everything is an Easter egg\"). Nothing so far officially links the green display to any confirmed project. If an announcement or a debunk follows, this promotes with the citation; if it goes quiet, it fades.",
      confidence: "plausible",
      outcome: "pending",
      sources: [{ name: "Taylor Swift Fuels Album Theories as Empire State Building Flashes Green 'TS' Logo and Asks 'WhaTS Happening?'", url: "https://www.ibtimes.co.uk/empire-state-building-green-taylor-swift-speculation-1815429", reliability: 3, type: "reputable_press" }, { name: "Empire State Building goes green as mysterious TS symbols spark Taylor Swift fan theories", url: "https://www.contactmusic.com/story/467/3593838/empire-state-building-goes-green-as-mysterious-ts-symbols-spark-taylor-swift-fan-theories", reliability: 3, type: "reputable_press" }, { name: "Empire State Building goes green as mysterious TS symbols spark Taylor Swift fan theories", url: "https://uk.news.yahoo.com/empire-state-building-goes-green-090000104.html", reliability: 3, type: "reputable_press" }],
      relatedSlugs: ["tloas:showgirl-spotify-canvas-color-swap"],
    },
  ],
  "ttpd": [
    {
      slug: "thank-you-aimee-capitals",
      kind: "easter_egg",
      title: "The capitals in \"thanK you aIMee\"",
      claim: "The track title is stylized \"thanK you aIMee\" — the stray capitals spell KIM. Press and fans read the song as addressed to a famous bully by that name; Taylor has never said so herself.",
      evidence: "The stylization is objective fact (it is printed that way on the tracklist) and the reading was reported by major outlets within hours. But the attribution remains an inference from typography — so it stays labeled as reporting, not confirmation.",
      confidence: "reputable_reporting",
      outcome: "pending",
      sources: [{ name: "The Tortured Poets Department", url: "https://en.wikipedia.org/wiki/The_Tortured_Poets_Department", reliability: 2, type: "wiki" }],
      relatedSlugs: ["reputation:snake-reclamation"],
    },
    {
      slug: "peter-pan-throughline",
      kind: "easter_egg",
      title: "Peter, four years later",
      claim: "The Anthology track \"Peter\" reads as the grown-up ending to folklore's Peter-and-Wendy thread — fans hold that the boy who \"lost Wendy\" in \"cardigan\" is the same Peter who finally never comes back here.",
      evidence: "The Peter Pan allusion is explicit in both lyrics four years apart, and the callback was noted across the album's press coverage. The songs connect textually; whether they share one narrator is the (unconfirmed) fan layer.",
      confidence: "reputable_reporting",
      outcome: "partially_confirmed",
      sources: [{ name: "The Tortured Poets Department", url: "https://en.wikipedia.org/wiki/The_Tortured_Poets_Department", reliability: 2, type: "wiki" }, { name: "cardigan (song)", url: "https://en.wikipedia.org/wiki/Cardigan_(song)", reliability: 2, type: "wiki" }],
      relatedSlugs: ["folklore:teenage-love-triangle"],
    },
    {
      slug: "fortnight-dead-poets-casting",
      kind: "easter_egg",
      title: "The Dead Poets run the Tortured Poets asylum",
      claim: "The two scientists experimenting on Taylor in the \"Fortnight\" video are Ethan Hawke and Josh Charles — the schoolboys of Dead Poets Society (1989), cast on purpose: the Tortured Poets Department tipping its cap to cinema's most famous tortured poets.",
      evidence: "Hawke confirmed the intent in release-week interviews: Taylor reached out through his daughter Maya, and he described the album title as owing \"some debt\" to the film. Charles said he assumed Hawke was punking him when he called with the offer. Both cameos were reported the day the video dropped.",
      confidence: "confirmed_interview",
      outcome: "confirmed",
      sources: [{ name: "Ethan Hawke Talks Taylor Swift's 'Fortnight' Music Video", url: "https://www.hollywoodreporter.com/music/music-news/ethan-hawke-taylor-swift-fortnight-music-video-1235892762/", reliability: 4, type: "reputable_press" }, { name: "Taylor Swift Reunites 'Dead Poets' Stars Ethan Hawke, Josh Charles For 'Fortnight' Video", url: "https://deadline.com/2024/04/taylor-swift-dead-poets-society-stars-ethan-hawke-josh-charles-fortnight-video-1235890796/", reliability: 4, type: "reputable_press" }],
    },
    {
      slug: "ttpd-spotify-library-eggs",
      kind: "easter_egg",
      title: "The pop-up library that leaked lyrics on a schedule",
      claim: "Three days before release, a Spotify 'library' installation at LA's Grove was one big walk-through egg hunt: an open book displaying unreleased lyrics (swapped for a fresh set at 2 p.m.), shelves of books spined with track titles, and a globe pointed at Florida.",
      evidence: "Fans documented the room in real time and the plants paid off on release day: \"Even statues crumble if they're made to wait\" and \"One less temptress, one less dagger to sharpen\" both surfaced as album lines, and the book spines — \"The Manuscript,\" \"The Albatross\" — matched the record. Dried flowers and a peace-sign bust rounded out the set dressing fans mined for days.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift 'The Tortured Poets Department' LA Spotify library", url: "https://www.deseret.com/entertainment/2024/04/16/taylor-swift-tortured-poets-department-los-angeles-art-installation/", reliability: 3, type: "reputable_press" }, { name: "As Taylor Swift's 'The Tortured Poets Department' drops, here's everything you need to know", url: "https://www.nbcnews.com/pop-culture/music/taylor-swift-new-album-tortured-poets-department-what-know-rcna148277", reliability: 4, type: "reputable_press" }],
    },
    {
      slug: "black-dog-real-pub",
      kind: "easter_egg",
      title: "The Black Dog is a real pub, and fans found it in days",
      claim: "The bar the ex walks into in \"The Black Dog\" is a real place — fans pinned it to The Black Dog at 112 Vauxhall Walk in London within days of release and turned an unassuming neighborhood pub into a Swiftie pilgrimage site.",
      evidence: "The pub's owners say they learned about the song from the fan surge itself, then leaned in: lyric signage in the window, \"home to tortured poets\" in the Instagram bio, a \"Taylor's Version\" cocktail menu, and queues they had to turn away. Taylor has never said whether she meant this exact Black Dog — the fan identification, and the pub's embrace of it, is the story.",
      confidence: "reputable_reporting",
      outcome: "partially_confirmed",
      sources: [{ name: "What it's like inside The Black Dog, the London pub made famous by Taylor Swift", url: "https://www.cnn.com/travel/black-dog-vauxhall-london-pub-taylor-swift", reliability: 4, type: "reputable_press" }, { name: "Why Swifties have sniffed out and descended upon London's Black Dog pub", url: "https://www.cbsnews.com/news/talyor-swift-london-pub-black-dog-swifties-descend/", reliability: 4, type: "reputable_press" }],
      relatedSlugs: ["ttpd:ttpd-grief-playlists"],
    },
    {
      slug: "ttpd-grief-playlists",
      kind: "easter_egg",
      title: "The heartbreak playlists were made of unreleased lyrics",
      claim: "Two weeks before TTPD, five Apple Music playlists of her older songs mapped the five stages of grief — and the titles were themselves the egg: \"I Love You, It's Ruining My Life,\" \"Old Habits Die Screaming,\" and \"I Can Do It With a Broken Heart\" were all unreleased TTPD lines hiding in plain sight.",
      evidence: "Taylor curated all five (denial, anger, bargaining, depression, acceptance) from her first ten albums with her own notes on each stage. On release day the titles resolved: \"I Love You, It's Ruining My Life\" is a \"Fortnight\" lyric, \"Old Habits Die Screaming\" is in \"The Black Dog,\" and \"I Can Do It With a Broken Heart\" is on the tracklist itself.",
      confidence: "official",
      outcome: "confirmed",
      sources: [{ name: "Taylor Swift Shares 5 'Stages of Heartbreak' Playlists on Apple Music", url: "https://www.billboard.com/music/music-news/taylor-swift-5-stages-of-heartbreak-playlists-apple-music-1235649873/", reliability: 4, type: "reputable_press" }, { name: "Taylor Swift Soundtracks the Five Stages of Grief With New Apple Music Playlists", url: "https://www.rollingstone.com/music/music-news/taylor-swift-stages-grief-playlists-apple-music-1234999955/", reliability: 4, type: "reputable_press" }],
      relatedSlugs: ["ttpd:black-dog-real-pub"],
    },
    {
      slug: "clara-bow-it-girl-lineage",
      kind: "theory",
      title: "Clara Bow, Stevie Nicks, and the it-girl assembly line",
      claim: "The album closer reads as Taylor mapping the industry's cycle of crowning and discarding its women: label voices call the narrator \"Clara Bow in this light,\" then \"Stevie Nicks in '75,\" then tell her a newer girl has the \"edge\" that Taylor \"never did\" — she puts herself mid-conveyor-belt, next in line to be replaced.",
      evidence: "The lineage is right there in the text — the song names Clara Bow (the silent era's original \"It Girl,\" who retired young under relentless media scrutiny) and Stevie Nicks by name before turning the same appraising label-speak on Taylor herself. Critics read it as a companion to her earlier fame parables \"The Lucky One\" and \"Nothing New\": Rolling Stone's Rob Sheffield tied it to her writing on short-lived fame and being left behind, and NPR and The Ringer both framed it as Taylor clocking the cyclical nature of stardom. The self-aware reading is widely shared; she has not narrated it line by line.",
      confidence: "reputable_reporting",
      outcome: "partially_confirmed",
      sources: [{ name: "Clara Bow (song)", url: "https://en.wikipedia.org/wiki/Clara_Bow_(song)", reliability: 2, type: "wiki" }, { name: "Who Is Clara Bow? The Inspiration Behind Taylor Swift's Song", url: "https://time.com/6969048/clara-bow-taylor-swift-song/", reliability: 4, type: "reputable_press" }],
    },
    {
      slug: "cassandra-reputation-callback",
      kind: "theory",
      title: "Cassandra: the prophet no one believed, and the snakes",
      claim: "Fans read \"Cassandra\" as Taylor mapping her 2016 public downfall onto the Greek myth of the prophet cursed to tell the truth and never be believed — the tell being the snake motif (\"they filled my cell with snakes... do you believe me now?\"), the reputation-era emoji pile-on revisited from the far side of vindication.",
      evidence: "The myth is explicit: Apollo curses Cassandra so her true prophecies always go unheeded. The lyric pulls its snake imagery straight from the reputation-era campaign this catalog already documents, and Billboard, Capital FM and others read the track as Taylor's account of being publicly disbelieved in 2016 — down to the \"supposed supporters who didn't take her side.\" It points at the same public controversy the \"thanK you aIMee\" stylization does; it is a documented press reading of a public chapter, not an authorial confirmation.",
      confidence: "reputable_reporting",
      outcome: "pending",
      sources: [{ name: "Cassandra (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Cassandra_(Taylor_Swift_song)", reliability: 2, type: "wiki" }, { name: "Taylor Swift Explains The Meaning Behind Her 'Cassandra' Lyrics", url: "https://www.capitalfm.com/news/music/taylor-swift-cassandra-lyrics-meaning-who/", reliability: 3, type: "reputable_press" }],
      relatedSlugs: ["ttpd:thank-you-aimee-capitals", "reputation:snake-reclamation"],
    },
    {
      slug: "ttpd-quill-fountain-pen-era",
      kind: "theory",
      title: "The most \"quill and fountain pen\" album she's made",
      claim: "Using Taylor's own three-pen system — Quill (antique, literary), Fountain Pen (modern, brutally honest), Glitter Gel Pen (carefree fun) — fans peg The Tortured Poets Department as her heaviest lean yet toward the quill/fountain-pen end: the poetry-department framing, the typewriter aesthetic, almost no glitter-gel levity.",
      evidence: "Taylor defined the three categories herself while accepting the Songwriter-Artist of the Decade honor at the 2022 Nashville Songwriter Awards, naming \"ivy\" as a quill lyric, \"All Too Well\" as fountain pen, and \"Shake It Off\" as glitter gel. Fans applied the framework to TTPD before release and pointed to a planted clue — the fountain pen sitting on the writing desk in the album's Spotify pop-up library. Which specific tracks land in which category is fan debate; Taylor has not sorted this album's songs in public.",
      confidence: "reputable_reporting",
      outcome: "pending",
      sources: [{ name: "Taylor Swift organises her lyrics into three \"dorky\" pen-themed categories", url: "https://www.nme.com/news/music/taylor-swift-organises-her-lyrics-into-three-dorky-pen-themed-categories-3325355", reliability: 4, type: "reputable_press" }, { name: "Is Taylor Swift's 'The Tortured Poets Department' A Quill, Fountain Or Glitter Pen album?", url: "https://www.capitalfm.com/news/music/taylor-swifts-quill-fountain-glitter-pen-songwriting/", reliability: 3, type: "reputable_press" }],
      relatedSlugs: ["ttpd:ttpd-spotify-library-eggs"],
    },
  ],
};
