// GENERATED FILE — do not hand-edit.
// Produced by scripts/sync-longlive-videos.mjs from supabase/seed/videos/**
// (or the live Supabase video_work table when configured).
// Re-run that script after video-seed changes; don't edit this file directly.

import type { EraId, VideoNote } from './types';

export const VIDEOS_RAW: Partial<Record<EraId, VideoNote[]>> = {
  "1989": [
    {
      slug: "shake-it-off-mv",
      kind: "music_video",
      title: "Shake It Off",
      director: "Mark Romanek",
      releasedOn: "2014-08-18",
      relatedSongs: ["Shake It Off"],
      summary: "Dropped the day 1989 was announced: Taylor gamely flails through ballet, breakdance, twerk squads and cheer lines before the finale says the quiet part — just dance like the fans do.",
      easterEggs: [],
      symbolism: "Failing every polished dance style on purpose is the thesis: the haters' scorecard doesn't apply.",
      youtubeId: "nfWlot6h_JM",
      sources: [{ name: "Taylor Swift - Shake It Off", url: "https://www.youtube.com/watch?v=nfWlot6h_JM", reliability: 5, type: "official" }, { name: "Shake It Off", url: "https://en.wikipedia.org/wiki/Shake_It_Off", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "blank-space-mv",
      kind: "music_video",
      title: "Blank Space",
      director: "Joseph Kahn",
      releasedOn: "2014-11-10",
      relatedSongs: ["Blank Space"],
      summary: "The satire that ended the \"boy-crazy\" narrative by playing it to the hilt: a mansion romance curdles into golf-club-to-the-sports-car mania, with Taylor grinning through the tabloid caricature.",
      easterEggs: [],
      symbolism: "She is playing the media's version of Taylor Swift, not herself — the video is the song's joke made visible, and mainstream coverage read it exactly that way.",
      youtubeId: "e-ORhEE9VVg",
      sources: [{ name: "Taylor Swift - Blank Space", url: "https://www.youtube.com/watch?v=e-ORhEE9VVg", reliability: 5, type: "official" }, { name: "Blank Space", url: "https://en.wikipedia.org/wiki/Blank_Space", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "style-mv",
      kind: "music_video",
      title: "Style",
      director: "Joseph Kahn",
      releasedOn: "2015-02-13",
      relatedSongs: ["Style"],
      summary: "No plot, all texture: shattered mirrors, projected faces, fog and headlights — the album's moodiest song gets a video made of double exposures instead of story.",
      easterEggs: [],
      symbolism: "The broken-mirror shards and projections keep the two lovers overlapping without ever quite aligning — the never-out-of-style loop rendered literally.",
      youtubeId: "-CmadmM5cOk",
      sources: [{ name: "Taylor Swift - Style", url: "https://www.youtube.com/watch?v=-CmadmM5cOk", reliability: 5, type: "official" }, { name: "Style (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Style_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "bad-blood-mv",
      kind: "music_video",
      title: "Bad Blood",
      director: "Joseph Kahn",
      releasedOn: "2015-05-17",
      relatedSongs: ["Bad Blood"],
      summary: "The squad-era action trailer: a betrayal, a training montage, and a cast of codenamed stars (Catastrophe, Arsyn, Knockout...) marching into a fireball — premiered at the Billboard Music Awards.",
      easterEggs: ["Every cameo carries a comic-book codename in the credits — fans keep a full roster of who played whom."],
      symbolism: null,
      youtubeId: "QcIy9NiNbmo",
      sources: [{ name: "Taylor Swift - Bad Blood ft. Kendrick Lamar", url: "https://www.youtube.com/watch?v=QcIy9NiNbmo", reliability: 5, type: "official" }, { name: "Bad Blood (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Bad_Blood_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "wildest-dreams-mv",
      kind: "music_video",
      title: "Wildest Dreams",
      director: "Joseph Kahn",
      releasedOn: "2015-08-30",
      relatedSongs: ["Wildest Dreams"],
      summary: "Old-Hollywood safari melodrama: two co-stars fall for each other on a 1950s film set, and the premiere ends the romance the way the song promised it would end. Proceeds went to African Parks.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "IdneKLhsWOQ",
      sources: [{ name: "Taylor Swift - Wildest Dreams", url: "https://www.youtube.com/watch?v=IdneKLhsWOQ", reliability: 5, type: "official" }, { name: "Wildest Dreams", url: "https://en.wikipedia.org/wiki/Wildest_Dreams", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "the-1989-world-tour-live-film",
      kind: "tour_film",
      title: "The 1989 World Tour Live",
      director: "Jonas Åkerlund",
      releasedOn: "2015-12-20",
      relatedSongs: [],
      summary: "The Sydney stadium show captured for Apple Music — light-up wristbands, the catwalk, and the era's guest-star ritual folded into a streaming-exclusive concert film.",
      easterEggs: [],
      symbolism: null,
      youtubeId: null,
      sources: [{ name: "The 1989 World Tour Live", url: "https://en.wikipedia.org/wiki/The_1989_World_Tour_Live", reliability: 2, type: "wiki" }, { name: "Taylor Swift '1989 World Tour Live' Concert Film Coming to Apple Music: Watch Trailer", url: "https://www.billboard.com/music/pop/taylor-swift-1989-world-tour-live-concert-film-apple-music-6805694/", reliability: 4, type: "reputable_press" }],
      tags: ["Tour"],
    },
    {
      slug: "out-of-the-woods-mv",
      kind: "music_video",
      title: "Out of the Woods",
      director: "Joseph Kahn",
      releasedOn: "2015-12-31",
      relatedSongs: ["Out of the Woods"],
      summary: "Premiered on New Year's Eve: the woods literally chase Taylor — vines grab, snow buries, wolves close in — until she outruns the forest back to the beach and meets herself.",
      easterEggs: [],
      symbolism: "The pursuing forest is the anxiety spiral of the lyric; arriving at her own calm self on the shore closes the loop the song leaves open.",
      youtubeId: "JLf9q36UsBk",
      sources: [{ name: "Out of the Woods (song)", url: "https://en.wikipedia.org/wiki/Out_of_the_Woods_(song)", reliability: 2, type: "wiki" }, { name: "Watch Taylor Swift's New Music Video 'Out of the Woods'", url: "https://time.com/4164964/taylor-swift-new-music-video-out-woods-watch/", reliability: 4, type: "reputable_press" }, { name: "Taylor Swift Will Close Out Her Stellar 2015 with a New Music Video", url: "https://www.vanityfair.com/hollywood/2015/12/taylor-swift-out-of-the-woods-music-video-announcement", reliability: 4, type: "reputable_press" }],
      tags: ["Music"],
    },
    {
      slug: "grammys-album-of-the-year-2016",
      kind: "award_speech",
      title: "Accepting Album of the Year for 1989 — 58th GRAMMYs",
      director: null,
      releasedOn: "2016-02-15",
      relatedSongs: [],
      summary: "A second Album of the Year makes her the first woman to win it twice — and she closes with advice to any young woman watching: there will be people who try to undercut your success.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "dMCAEUb0h34",
      sources: [{ name: "Taylor Swift | Album of the Year | 58th GRAMMYs", url: "https://www.youtube.com/watch?v=dMCAEUb0h34", reliability: 5, type: "official" }, { name: "Taylor Swift's Grammys Speech", url: "https://time.com/4225261/2016-grammys-taylor-swift-kanye-west/", reliability: 4, type: "reputable_press" }],
      tags: ["Music"],
    },
    {
      slug: "i-dont-wanna-live-forever-mv",
      kind: "music_video",
      title: "I Don't Wanna Live Forever",
      director: null,
      releasedOn: "2017-01-27",
      relatedSongs: ["I Don't Wanna Live Forever"],
      summary: "A ZAYN/Taylor Swift duet written for the Fifty Shades Darker soundtrack — her first original song since 1989 — released December 2016, with its official video following in January 2017.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "7F37r50VUTQ",
      sources: [{ name: "ZAYN, Taylor Swift - I Don't Wanna Live Forever (Fifty Shades Darker)", url: "https://www.youtube.com/watch?v=7F37r50VUTQ", reliability: 5, type: "official" }, { name: "I Don't Wanna Live Forever", url: "https://en.wikipedia.org/wiki/I_Don%27t_Wanna_Live_Forever", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "new-romantics-mv",
      kind: "music_video",
      title: "New Romantics",
      director: "Jonas Åkerlund",
      releasedOn: null,
      relatedSongs: ["New Romantics"],
      summary: "A thank-you cut from 1989 World Tour footage — backstage, crowd waves, confetti — released as the era's victory lap for the fans who made the bonus track a hit.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "wyK7YuwUWsU",
      sources: [{ name: "New Romantics (song)", url: "https://en.wikipedia.org/wiki/New_Romantics_(song)", reliability: 2, type: "wiki" }],
      tags: ["Music", "Tour"],
    },
  ],
  "debut": [
    {
      slug: "ellen-first-interview-2008",
      kind: "interview",
      title: "First interview on The Ellen DeGeneres Show",
      director: null,
      releasedOn: "2008-01-17",
      relatedSongs: [],
      summary: "Eighteen years old and one album in, with 'Teardrops on My Guitar' crossing over to pop radio: her first talk-show sit-down, on a couch she would keep coming back to for the next decade.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "vBgiDYBCuxY",
      sources: [{ name: "Taylor Swift's First Interview with Ellen!", url: "https://www.youtube.com/watch?v=vBgiDYBCuxY", reliability: 5, type: "official" }, { name: "Taylor Swift's Best Moments on 'Ellen'", url: "https://www.billboard.com/music/music-news/taylor-swift-ellen-appearances-8511659/", reliability: 4, type: "reputable_press" }],
    },
    {
      slug: "our-song-mv",
      kind: "music_video",
      title: "Our Song",
      director: "Trey Fanjoy",
      releasedOn: null,
      relatedSongs: ["Our Song"],
      summary: "Front-porch performance piece — barefoot on the steps in a blue dress, then a flower-drenched fantasy set, for the song she wrote for her ninth-grade talent show.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "Jb2stN7kH28",
      sources: [{ name: "Taylor Swift - Our Song", url: "https://www.youtube.com/watch?v=Jb2stN7kH28", reliability: 5, type: "official" }, { name: "Our Song (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Our_Song_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "picture-to-burn-mv",
      kind: "music_video",
      title: "Picture to Burn",
      director: "Trey Fanjoy",
      releasedOn: null,
      relatedSongs: ["Picture to Burn"],
      summary: "Revenge fantasy: Taylor and her friend Abigail spy on the ex from a parked truck, then Taylor leads her band inside to trash his house in her imagination while Abigail keeps watch outside — the first of many satirical self-aware villain turns.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "yCMqcFAigRg",
      sources: [{ name: "Picture to Burn", url: "https://en.wikipedia.org/wiki/Picture_to_Burn", reliability: 2, type: "wiki" }, { name: "Video Premiere: 'Picture to Burn,' Taylor Swift", url: "https://theboot.com/video-premiere-picture-to-burn-taylor-swift/", reliability: 4, type: "reputable_press" }],
      tags: ["Music"],
    },
    {
      slug: "shouldve-said-no-mv",
      kind: "music_video",
      title: "Should've Said No",
      director: "Trey Fanjoy",
      releasedOn: null,
      relatedSongs: ["Should've Said No"],
      summary: "Built from her live 43rd ACM Awards performance: hooded-sweatshirt confessional through a costume change into a black dress, closing on the last lines sung in pouring stage rain.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "v9bxXO9fj98",
      sources: [{ name: "Should've Said No", url: "https://www.youtube.com/watch?v=v9bxXO9fj98", reliability: 5, type: "official" }, { name: "Should've Said No", url: "https://en.wikipedia.org/wiki/Should've_Said_No", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "teardrops-on-my-guitar-mv",
      kind: "music_video",
      title: "Teardrops on My Guitar",
      director: "Trey Fanjoy",
      releasedOn: null,
      relatedSongs: ["Teardrops on My Guitar"],
      summary: "High-school hallways and a bedroom confessional: Taylor watches Drew from the next locker over, then tells the guitar what she can't tell him.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "xKCek6_dB0M",
      sources: [{ name: "Taylor Swift - Teardrops On My Guitar", url: "https://www.youtube.com/watch?v=xKCek6_dB0M", reliability: 5, type: "official" }, { name: "Teardrops on My Guitar", url: "https://en.wikipedia.org/wiki/Teardrops_on_My_Guitar", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "tim-mcgraw-mv",
      kind: "music_video",
      title: "Tim McGraw",
      director: "Trey Fanjoy",
      releasedOn: null,
      relatedSongs: ["Tim McGraw"],
      summary: "The first video: a sun-flared lakeside memory reel — a 16-year-old Taylor in a white sundress, a Chevy truck, a summer already turning into a song about being remembered.",
      easterEggs: [],
      symbolism: "Establishes the visual grammar her early videos reuse: golden-hour nostalgia, the letter/memory motif, and Taylor as narrator of her own past.",
      youtubeId: "GkD20ajVxnY",
      sources: [{ name: "Taylor Swift - Tim McGraw", url: "https://www.youtube.com/watch?v=GkD20ajVxnY", reliability: 5, type: "official" }, { name: "Tim McGraw (song)", url: "https://en.wikipedia.org/wiki/Tim_McGraw_(song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
  ],
  "evermore": [
    {
      slug: "willow-mv",
      kind: "music_video",
      title: "willow",
      director: "Taylor Swift",
      releasedOn: "2020-12-11",
      relatedSongs: ["willow"],
      summary: "Picks up in the exact frame cardigan left off: from the piano, Taylor follows a golden thread through winter woods, a carnival tent, and firelit ritual circles to find the person on the other end.",
      easterEggs: ["Opens inside the same piano the cardigan video ends in — a deliberate continuity handoff between sister albums."],
      symbolism: "The glowing thread is the \"invisible string\" made visible — the two sister-album videos form one continuous story fans treat as a diptych.",
      youtubeId: "RsEZmictANA",
      sources: [{ name: "Taylor Swift - willow (Official Music Video)", url: "https://www.youtube.com/watch?v=RsEZmictANA", reliability: 5, type: "official" }, { name: "willow (song)", url: "https://en.wikipedia.org/wiki/Willow_(song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "jimmy-kimmel-live-2020",
      kind: "interview",
      title: "Interview on Jimmy Kimmel Live!",
      director: null,
      releasedOn: "2020-12-14",
      relatedSongs: [],
      summary: "Days after evermore arrived with no rollout: how she kept a second surprise album secret in the same year as folklore, the fan theories she reads, and the William Bowery question.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "ionfV_r8s40",
      sources: [{ name: "Taylor Swift on Turning 31, New Album, Fan Theories, Documentary & Boyfriend’s Pseudonym", url: "https://www.youtube.com/watch?v=ionfV_r8s40", reliability: 5, type: "official" }],
      tags: ["Music", "Lore"],
    },
    {
      slug: "mr-perfectly-fine-taylors-version-lyric-video",
      kind: "lyric_video",
      title: "Mr. Perfectly Fine (Taylor's Version) (From the Vault)",
      director: null,
      releasedOn: "2021-04-09",
      relatedSongs: ["Mr. Perfectly Fine (Taylor's Version)"],
      summary: "A vault-track lyric video released alongside Fearless (Taylor's Version) — the \"casually cruel\" comeback song fans had wanted a video for since it leaked in 2010.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "rFjJs6ZjPe8",
      sources: [{ name: "Taylor Swift - Mr. Perfectly Fine (Taylor's Version) (From The Vault) (Lyric Video)", url: "https://www.youtube.com/watch?v=rFjJs6ZjPe8", reliability: 5, type: "official" }, { name: "Mr. Perfectly Fine", url: "https://en.wikipedia.org/wiki/Mr._Perfectly_Fine", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "the-best-day-taylors-version-mv",
      kind: "music_video",
      title: "The Best Day (Taylor's Version)",
      director: null,
      releasedOn: "2021-04-09",
      relatedSongs: ["The Best Day (Taylor's Version)"],
      summary: "A new home-movie video built from never-before-seen family footage spanning her childhood to young adulthood, released three weeks after Fearless (Taylor's Version) — extending the original tribute for the re-recording era.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "n0cde-Km05o",
      sources: [{ name: "Taylor Swift - The Best Day (Taylor's Version) (Official Music Video)", url: "https://www.youtube.com/watch?v=n0cde-Km05o", reliability: 5, type: "official" }, { name: "The Best Day (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/The_Best_Day_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "all-too-well-the-short-film",
      kind: "short_film",
      title: "All Too Well: The Short Film",
      director: "Taylor Swift",
      releasedOn: "2021-11-12",
      relatedSongs: ["All Too Well (10 Minute Version)"],
      summary: "Fifteen minutes starring Sadie Sink and Dylan O'Brien: the whole arc of the fan-canonized breakup epic — the refrigerator-light dance, the kitchen fight, the scarf — released with Red (Taylor's Version) and premiered theatrically.",
      easterEggs: [],
      symbolism: "The closing scene jumps years ahead to an author reading from a book titled All Too Well: the song's thesis that she keeps custody of the story by writing it.",
      youtubeId: "tollGa3S0o8",
      sources: [{ name: "Taylor Swift - All Too Well: The Short Film", url: "https://www.youtube.com/watch?v=tollGa3S0o8", reliability: 5, type: "official" }, { name: "All Too Well: The Short Film", url: "https://en.wikipedia.org/wiki/All_Too_Well:_The_Short_Film", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "all-too-well-10-min-snl-performance",
      kind: "performance",
      title: "All Too Well (10 Minute Version) — Live on Saturday Night Live",
      director: null,
      releasedOn: "2021-11-13",
      relatedSongs: ["All Too Well (10 Minute Version)"],
      summary: "A rare single-song SNL musical-guest slot, one day after Red (Taylor's Version): the full ten minutes live on a leaf-strewn stage, short-film footage rolling behind her, snow falling by the last verse.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "nJr_8l0AEWE",
      sources: [{ name: "Taylor Swift - All Too Well (10 Minute Version) (Live on Saturday Night Live)", url: "https://www.youtube.com/watch?v=nJr_8l0AEWE", reliability: 5, type: "official" }, { name: "'SNL': Taylor Swift Performs \"All Too Well (10 Minute Version)\"", url: "https://www.billboard.com/music/pop/taylor-swift-snl-all-too-well-10-minute-version-performance-video-9659774/", reliability: 4, type: "reputable_press" }],
      tags: ["Music"],
    },
    {
      slug: "i-bet-you-think-about-me-mv",
      kind: "music_video",
      title: "I Bet You Think About Me",
      director: "Blake Lively",
      releasedOn: "2021-11-15",
      relatedSongs: ["I Bet You Think About Me"],
      summary: "Blake Lively's directorial debut: Taylor crashes a pastel society wedding as the red-dressed ghost of relationships past, gleefully ruining the cake — the vault track as screwball comedy.",
      easterEggs: [],
      symbolism: "She is the only thing in red in a room styled entirely in polite neutrals — the era's color used as a walking punchline.",
      youtubeId: "5UMCrq-bBCg",
      sources: [{ name: "I Bet You Think About Me", url: "https://en.wikipedia.org/wiki/I_Bet_You_Think_About_Me", reliability: 2, type: "wiki" }, { name: "Taylor Swift to Release 'I Bet You Think About Me' Music Video Directed By Blake Lively", url: "https://www.teenvogue.com/story/taylor-swift-i-bet-you-think-about-me-music-video-blake-lively", reliability: 4, type: "reputable_press" }],
      tags: ["Music"],
    },
    {
      slug: "nyu-commencement-2022",
      kind: "speech",
      title: "NYU commencement address",
      director: null,
      releasedOn: "2022-05-18",
      relatedSongs: [],
      summary: "An honorary Doctor of Fine Arts at Yankee Stadium, then twenty minutes to NYU's class of 2022 — including her case that cringe is unavoidable over a long enough life.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "OBG50aoUwlI",
      sources: [{ name: "NYU's 2022 Commencement Speaker Taylor Swift", url: "https://www.youtube.com/watch?v=OBG50aoUwlI", reliability: 5, type: "official" }],
    },
    {
      slug: "vmas-midnights-announcement-2022",
      kind: "award_speech",
      title: "Announcing Midnights from the VMAs stage",
      director: null,
      releasedOn: "2022-08-28",
      relatedSongs: [],
      summary: "'All Too Well: The Short Film' wins Video of the Year — and she spends the end of the acceptance speech announcing a brand-new album, Midnights, arriving October 21.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "_J1dJLDrPBo",
      sources: [{ name: "Taylor Swift Announces Her New Album 'Midnights' at the 2022 VMAs | MTV News", url: "https://www.youtube.com/watch?v=_J1dJLDrPBo", reliability: 5, type: "official" }],
      tags: ["Music"],
    },
  ],
  "fearless": [
    {
      slug: "change-live-2009",
      kind: "performance",
      title: "Change (Live)",
      director: null,
      releasedOn: "2009-06-16",
      relatedSongs: ["Change"],
      summary: "A full-length live performance video of the Fearless-era anthem, posted to her official channel the same week as the deluxe-cut video for \"I'm Only Me When I'm With You.\"",
      easterEggs: [],
      symbolism: null,
      youtubeId: "FMDVWSqALRs",
      sources: [{ name: "Taylor Swift - Change (Live)", url: "https://www.youtube.com/watch?v=FMDVWSqALRs", reliability: 5, type: "official" }, { name: "Change (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Change_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "im-only-me-when-im-with-you-mv",
      kind: "music_video",
      title: "I'm Only Me When I'm With You",
      director: null,
      releasedOn: "2009-06-16",
      relatedSongs: ["I'm Only Me When I'm with You"],
      summary: "The official video for the Taylor Swift (Deluxe Edition) bonus cut, uploaded to her channel during the Fearless era rather than around the debut album's 2006 release — YouTube's own \"Music video by Taylor Swift performing...\" credit line confirms the official upload.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "AlTfYj7q5gQ",
      sources: [{ name: "Taylor Swift - I'm Only Me When I'm With You", url: "https://www.youtube.com/watch?v=AlTfYj7q5gQ", reliability: 5, type: "official" }, { name: "Taylor Swift (album)", url: "https://en.wikipedia.org/wiki/Taylor_Swift_(album)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "fearless-mv",
      kind: "music_video",
      title: "Fearless",
      director: null,
      releasedOn: "2010-01-01",
      relatedSongs: ["Fearless"],
      summary: "A live-performance-style video built from touring footage for the album's title track, released as its final single.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "ptSjNWnzpjg",
      sources: [{ name: "Taylor Swift - Fearless", url: "https://www.youtube.com/watch?v=ptSjNWnzpjg", reliability: 5, type: "official" }, { name: "Fearless (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Fearless_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "grammys-album-of-the-year-2010",
      kind: "award_speech",
      title: "Accepting Album of the Year for Fearless — 52nd GRAMMYs",
      director: null,
      releasedOn: "2010-01-31",
      relatedSongs: [],
      summary: "Twenty years old, holding Album of the Year for Fearless and, at the time, the youngest artist ever to win it. She thanks her parents and producer Nathan Chapman.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "BFk2NjdJ1yY",
      sources: [{ name: "Taylor Swift accepting the GRAMMY for Album of the Year at the 52nd GRAMMY Awards | GRAMMYs", url: "https://www.youtube.com/watch?v=BFk2NjdJ1yY", reliability: 5, type: "official" }],
      tags: ["Music"],
    },
    {
      slug: "change-mv",
      kind: "music_video",
      title: "Change",
      director: null,
      releasedOn: null,
      relatedSongs: ["Change"],
      summary: "Taylor and her band perform in a ballroom, intercut with a version featuring 2008 Beijing Olympics footage tying the anthem to Team USA.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "B1jYllE0T-k",
      sources: [{ name: "Taylor Swift - Change", url: "https://www.youtube.com/watch?v=B1jYllE0T-k", reliability: 5, type: "official" }, { name: "Change (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Change_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "fifteen-mv",
      kind: "music_video",
      title: "Fifteen",
      director: "Roman White",
      releasedOn: null,
      relatedSongs: ["Fifteen"],
      summary: "A greenhouse-dream staging of freshman year: scenes bloom and dissolve around Taylor as she narrates Abigail's story and her own — memory rendered as a garden being planted and unplanted.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "Pb-K2tXWK4w",
      sources: [{ name: "Fifteen (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Fifteen_(Taylor_Swift_song)", reliability: 2, type: "wiki" }, { name: "Taylor Swift Flashed Back To High School For VMA-Nominated 'Fifteen'", url: "https://web.archive.org/web/20150327105811/http://www.mtv.com/news/1646390/taylor-swift-flashed-back-to-high-school-for-vma-nominated-fifteen/", reliability: 4, type: "reputable_press" }],
      tags: ["Music"],
    },
    {
      slug: "journey-to-fearless",
      kind: "tour_film",
      title: "Journey to Fearless",
      director: null,
      releasedOn: null,
      relatedSongs: [],
      summary: "The first concert film: a three-part TV documentary following the Fearless Tour — 19-year-old headliner, screaming arenas, and the backstory told between stadium cuts.",
      easterEggs: [],
      symbolism: null,
      youtubeId: null,
      sources: [{ name: "Journey to Fearless", url: "https://en.wikipedia.org/wiki/Journey_to_Fearless", reliability: 2, type: "wiki" }, { name: "Taylor Swift: Journey to Fearless", url: "https://www.shoutfactory.com/products/taylor-swift-journey-to-fearless", reliability: 4, type: "reputable_press" }],
      tags: ["Tour"],
    },
    {
      slug: "love-story-mv",
      kind: "music_video",
      title: "Love Story",
      director: "Trey Fanjoy",
      releasedOn: null,
      relatedSongs: ["Love Story"],
      summary: "The period-piece blockbuster: a campus meet-cute dissolves into a full Regency-styled castle romance, ballgown and all, ending with the two reunited across a field — the happy ending the song writes over Romeo and Juliet.",
      easterEggs: [],
      symbolism: "The dual-timeline device (present-day glance, imagined past) became a signature she returned to through Wildest Dreams and beyond.",
      youtubeId: "8xg3vE8Ie_E",
      sources: [{ name: "Taylor Swift - Love Story", url: "https://www.youtube.com/watch?v=8xg3vE8Ie_E", reliability: 5, type: "official" }, { name: "Love Story (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Love_Story_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "love-story-live-letterman",
      kind: "performance",
      title: "Love Story (Live on Letterman)",
      director: null,
      releasedOn: null,
      relatedSongs: ["Love Story"],
      summary: "A solo performance of the breakout single on the Late Show with David Letterman, part of the national TV rounds Taylor did during Fearless's 2008-2009 promotional run.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "mNLVMDF9mUo",
      sources: [{ name: "Taylor Swift - Love Story (Live on Letterman)", url: "https://www.youtube.com/watch?v=mNLVMDF9mUo", reliability: 5, type: "official" }, { name: "Love Story (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Love_Story_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "the-best-day-mv",
      kind: "music_video",
      title: "The Best Day",
      director: null,
      releasedOn: null,
      relatedSongs: ["The Best Day"],
      summary: "A home-movie tribute assembled from Taylor family footage — childhood birthdays, ordinary afternoons with her mother — released as a Mother's Day surprise.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "l4_6eQm7RTQ",
      sources: [{ name: "Taylor Swift - The Best Day", url: "https://www.youtube.com/watch?v=l4_6eQm7RTQ", reliability: 5, type: "official" }, { name: "The Best Day (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/The_Best_Day_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "white-horse-mv",
      kind: "music_video",
      title: "White Horse",
      director: "Trey Fanjoy",
      releasedOn: null,
      relatedSongs: ["White Horse"],
      summary: "The anti-fairytale companion to Love Story: a dim apartment, a phone that shouldn't be answered, and a breakup played in intercut apology scenes — no castle, no rescue.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "D1Xr-JFLxik",
      sources: [{ name: "White Horse (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/White_Horse_(Taylor_Swift_song)", reliability: 2, type: "wiki" }, { name: "Taylor Swift Talks About 'Emotional' New Video For 'White Horse'", url: "https://web.archive.org/web/20121106152258/http://www.mtv.com/news/articles/1602728/taylor-swift-talks-about-emotional-new-video-white-horse.jhtml", reliability: 4, type: "reputable_press" }],
      tags: ["Music"],
    },
    {
      slug: "you-belong-with-me-mv",
      kind: "music_video",
      title: "You Belong with Me",
      director: "Roman White",
      releasedOn: null,
      relatedSongs: ["You Belong with Me"],
      summary: "Taylor plays both the band-tee girl next door and the brunette cheer captain across the driveway — window-sign confessions, a prom-night reveal, and the era's defining underdog fantasy.",
      easterEggs: [],
      symbolism: "Casting herself as her own rival literalizes the song's point-of-view trick; the \"I love you\" window sign became one of her most-referenced images.",
      youtubeId: "VuNIsY6JdUw",
      sources: [{ name: "Taylor Swift - You Belong With Me", url: "https://www.youtube.com/watch?v=VuNIsY6JdUw", reliability: 5, type: "official" }, { name: "You Belong with Me", url: "https://en.wikipedia.org/wiki/You_Belong_with_Me", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
  ],
  "folklore": [
    {
      slug: "cardigan-mv",
      kind: "music_video",
      title: "cardigan",
      director: "Taylor Swift",
      releasedOn: "2020-07-24",
      relatedSongs: ["cardigan"],
      summary: "Self-directed under COVID protocols and released with the surprise album: a glowing piano becomes a portal from a candlelit cabin to a mossy forest to a storm-tossed sea, and back to safety under a cardigan.",
      easterEggs: [],
      symbolism: "The piano-portal is the act of songwriting itself — climbing into the instrument to survive the wilderness and the deep water, then coming home.",
      youtubeId: "K-a8s8OLBSE",
      sources: [{ name: "Taylor Swift - cardigan", url: "https://www.youtube.com/watch?v=K-a8s8OLBSE", reliability: 5, type: "official" }, { name: "cardigan (song)", url: "https://en.wikipedia.org/wiki/Cardigan_(song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "betty-live-acm-2020",
      kind: "performance",
      title: "betty (Live From The 2020 Academy of Country Music Awards)",
      director: null,
      releasedOn: "2020-09-16",
      relatedSongs: ["betty"],
      summary: "A surprise, country-leaning live debut of \"betty\" at the pandemic-era ACMs, broadcast from Nashville venues including the Grand Ole Opry House.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "orXAg5dIMa8",
      sources: [{ name: "Taylor Swift - betty (Live from the 2020 Academy of Country Music Awards)", url: "https://www.youtube.com/watch?v=orXAg5dIMa8", reliability: 5, type: "official" }, { name: "55th Academy of Country Music Awards", url: "https://en.wikipedia.org/wiki/55th_Academy_of_Country_Music_Awards", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "folklore-long-pond-studio-sessions-film",
      kind: "documentary",
      title: "folklore: the long pond studio sessions",
      director: "Taylor Swift",
      releasedOn: "2020-11-25",
      relatedSongs: [],
      summary: "The Disney+ film where folklore got its liner notes out loud: Taylor, Aaron Dessner and Jack Antonoff play the album through in a woodland studio and explain it song by song — including the William Bowery reveal.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "jgdFUoZzCI0",
      sources: [{ name: "Folklore: The Long Pond Studio Sessions", url: "https://en.wikipedia.org/wiki/Folklore:_The_Long_Pond_Studio_Sessions", reliability: 2, type: "wiki" }, { name: "Taylor Swift Is Releasing a \"Folklore\" Special on Disney+", url: "https://www.teenvogue.com/story/taylor-swift-folklore-special-disney-plus", reliability: 4, type: "reputable_press" }, { name: "folklore: the long pond studio sessions | Official Trailer", url: "https://www.youtube.com/watch?v=jgdFUoZzCI0", reliability: 5, type: "official" }],
      tags: ["Music"],
    },
    {
      slug: "cardigan-august-willow-grammys-2021",
      kind: "performance",
      title: "cardigan / august / willow (Live From The 63rd GRAMMYs)",
      director: null,
      releasedOn: "2021-03-14",
      relatedSongs: ["cardigan", "august", "willow"],
      summary: "A folklore/evermore medley performed with Jack Antonoff and Aaron Dessner at the pandemic-era 63rd Grammy Awards, staged outdoors at the LA Convention Center.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "Uzii44SDYFA",
      sources: [{ name: "Taylor Swift - cardigan / august / willow (Live From The 63rd GRAMMYs® / 2021)", url: "https://www.youtube.com/watch?v=Uzii44SDYFA", reliability: 5, type: "official" }, { name: "63rd Annual Grammy Awards", url: "https://en.wikipedia.org/wiki/63rd_Annual_Grammy_Awards", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
  ],
  "lover": [
    {
      slug: "me-mv",
      kind: "music_video",
      title: "ME!",
      director: "Dave Meyers & Taylor Swift",
      releasedOn: "2019-04-26",
      relatedSongs: ["ME!"],
      summary: "The era-flip: a French-arguing snake bursts into pastel butterflies, and the rest is a candy-colored musical-theater fever dream with Brendon Urie — released 4/26 after a fan-tracked countdown.",
      easterEggs: ["The Kelsey Montague butterfly mural in Nashville went up hours before the drop as a real-world clue.", "A neon \"Lover\" sign appears months before the album title was announced."],
      symbolism: "The snake-to-butterflies opening is the official handoff from reputation to Lover, staged in one cut.",
      youtubeId: "FuXNumBwDOM",
      sources: [{ name: "Taylor Swift - ME! (feat. Brendon Urie of Panic! At The Disco)", url: "https://www.youtube.com/watch?v=FuXNumBwDOM", reliability: 5, type: "official" }, { name: "ME!", url: "https://en.wikipedia.org/wiki/Me!", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "me-live-billboard-music-awards-2019",
      kind: "performance",
      title: "ME! (Live From The Billboard Music Awards) ft. Brendon Urie",
      director: null,
      releasedOn: "2019-05-01",
      relatedSongs: ["ME!"],
      summary: "\"ME!\"'s world-premiere live debut, opening the NBC broadcast alongside Brendon Urie of Panic! At The Disco.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "bqOfdv9i4sE",
      sources: [{ name: "ME! (feat. Brendon Urie of Panic! At The Disco) (Live From The Billboard Music Awards / 2019)", url: "https://www.youtube.com/watch?v=bqOfdv9i4sE", reliability: 5, type: "official" }, { name: "2019 Billboard Music Awards", url: "https://en.wikipedia.org/wiki/2019_Billboard_Music_Awards", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "you-need-to-calm-down-mv",
      kind: "music_video",
      title: "You Need to Calm Down",
      director: "Drew Kirsch & Taylor Swift",
      releasedOn: "2019-06-17",
      relatedSongs: ["You Need to Calm Down"],
      summary: "A trailer-park block party stacked with LGBTQ icons — and a mid-video Katy Perry burger-and-fries reconciliation — ending on a title card for the Equality Act petition.",
      easterEggs: ["The burger-and-fries costumes end the long-running Katy Perry feud on camera."],
      symbolism: null,
      youtubeId: "Dkk9gvTmCXY",
      sources: [{ name: "Taylor Swift - You Need To Calm Down", url: "https://www.youtube.com/watch?v=Dkk9gvTmCXY", reliability: 5, type: "official" }, { name: "You Need to Calm Down", url: "https://en.wikipedia.org/wiki/You_Need_to_Calm_Down", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "lover-mv",
      kind: "music_video",
      title: "Lover",
      director: "Drew Kirsch",
      releasedOn: "2019-08-22",
      relatedSongs: ["Lover"],
      summary: "A couple lives inside a dollhouse where every room is a different color and mood — an image fans never stopped decoding, especially once the Eras Tour opened with the Lover set.",
      easterEggs: [],
      symbolism: "The house-of-rooms was later read as a map of her discography's moods; the \"Lover house\" became load-bearing fan canon for era iconography.",
      youtubeId: "-BjZmE2gtdo",
      sources: [{ name: "Taylor Swift - Lover (Official Music Video)", url: "https://www.youtube.com/watch?v=-BjZmE2gtdo", reliability: 5, type: "official" }, { name: "Lover (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Lover_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "vmas-video-of-the-year-2019",
      kind: "award_speech",
      title: "Accepting Video of the Year for 'You Need to Calm Down' — 2019 VMAs",
      director: null,
      releasedOn: "2019-08-26",
      relatedSongs: [],
      summary: "'You Need to Calm Down' wins Video of the Year, and she uses the podium to point back at the Equality Act petition the video ends on — noting from the stage that the White House had not responded to it.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "8z4icNgFSPI",
      sources: [{ name: "Taylor Swift Wins Video of the Year | 2019 Video Music Awards", url: "https://www.youtube.com/watch?v=8z4icNgFSPI", reliability: 5, type: "official" }, { name: "Taylor Swift calls out White House during VMAs acceptance speech", url: "https://www.cbsnews.com/detroit/news/taylor-swift-calls-out-white-house-during-vmas-acceptance-speech", reliability: 4, type: "reputable_press" }],
      tags: ["Music"],
    },
    {
      slug: "amas-artist-of-the-decade-2019",
      kind: "award_speech",
      title: "Accepting Artist of the Decade — 2019 American Music Awards",
      director: null,
      releasedOn: "2019-11-24",
      relatedSongs: [],
      summary: "Carole King hands her Artist of the Decade — one of the wins that night that carried her to a record 29 American Music Awards.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "0pbSQ_0qbqU",
      sources: [{ name: "Taylor Swift wins the Artist of the Decade Award  I  AMAs 2019", url: "https://www.youtube.com/watch?v=0pbSQ_0qbqU", reliability: 5, type: "official" }, { name: "Taylor Swift's Artist of the Decade Speech at the 2019 AMAs", url: "https://www.billboard.com/music/awards/taylor-swift-artist-decade-speech-2019-amas-8544659/", reliability: 4, type: "reputable_press" }],
      tags: ["Music"],
    },
    {
      slug: "amas-artist-of-the-decade-medley-2019",
      kind: "performance",
      title: "Artist of the Decade Medley — 2019 American Music Awards",
      director: null,
      releasedOn: "2019-11-24",
      relatedSongs: ["The Man", "Love Story", "I Knew You Were Trouble", "Blank Space", "Shake It Off"],
      summary: "A career-spanning medley for the Artist of the Decade honor at the Microsoft Theater — joined by Halsey and Camila Cabello on \"Shake It Off\" and Misty Copeland for a \"First Dance Remix.\"",
      easterEggs: [],
      symbolism: null,
      youtubeId: "SVY8I46dkb0",
      sources: [{ name: "Taylor Swift - Live at the 2019 American Music Awards", url: "https://www.youtube.com/watch?v=SVY8I46dkb0", reliability: 5, type: "official" }, { name: "2019 American Music Awards", url: "https://en.wikipedia.org/wiki/2019_American_Music_Awards", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "christmas-tree-farm-mv",
      kind: "music_video",
      title: "Christmas Tree Farm",
      director: "Taylor Swift",
      releasedOn: "2019-12-06",
      relatedSongs: ["Christmas Tree Farm"],
      summary: "A self-directed holiday video built from real Taylor-family home footage — sledding, decorating, and Taylor unwrapping her first guitar — set on the actual Pennsylvania tree farm the song is named for.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "mN3rDTAdM2o",
      sources: [{ name: "Taylor Swift - Christmas Tree Farm", url: "https://www.youtube.com/watch?v=mN3rDTAdM2o", reliability: 5, type: "official" }, { name: "Christmas Tree Farm", url: "https://en.wikipedia.org/wiki/Christmas_Tree_Farm", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "sundance-miss-americana-qa-2020",
      kind: "press_event",
      title: "Miss Americana — Sundance world-premiere Q&A",
      director: null,
      releasedOn: "2020-01-23",
      relatedSongs: [],
      summary: "Miss Americana opens Sundance, and Taylor joins director Lana Wilson on stage afterwards for the festival Q&A — days before the documentary landed on Netflix.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "JqIt0H6XqpA",
      sources: [{ name: "Taylor Swift: Miss Americana - Sundance 2020 World Premiere Q&A", url: "https://www.youtube.com/watch?v=JqIt0H6XqpA", reliability: 3, type: "video" }, { name: "Miss Americana", url: "https://en.wikipedia.org/wiki/Miss_Americana", reliability: 2, type: "wiki" }],
    },
    {
      slug: "miss-americana",
      kind: "documentary",
      title: "Miss Americana",
      director: "Lana Wilson",
      releasedOn: "2020-01-31",
      relatedSongs: [],
      summary: "The Netflix documentary that opened the vault for real: the eating-disorder disclosure, the political-silence breaking point, and the Lover sessions — Sundance premiere, then streaming.",
      easterEggs: [],
      symbolism: null,
      youtubeId: null,
      sources: [{ name: "Miss Americana", url: "https://en.wikipedia.org/wiki/Miss_Americana", reliability: 2, type: "wiki" }, { name: "Taylor Swift Gets On the Right Side of History in First Trailer for Netflix's Miss Americana", url: "https://www.vanityfair.com/hollywood/2020/01/taylor-swift-netflix-miss-americana", reliability: 4, type: "reputable_press" }],
      tags: ["Music"],
    },
    {
      slug: "the-man-mv",
      kind: "music_video",
      title: "The Man",
      director: "Taylor Swift",
      releasedOn: "2020-02-27",
      relatedSongs: ["The Man"],
      summary: "Her solo directorial debut: buried under prosthetics, Taylor plays \"Tyler\" — the swaggering executive whose every entitled move the song calls out — until the credits reveal the trick.",
      easterEggs: [],
      symbolism: "The double-standard satire is the point: the same behavior reads as boss-like on a man, so she performs it as one. Her father cameos as the tennis umpire.",
      youtubeId: "AqAJLh9wuZ0",
      sources: [{ name: "Taylor Swift - The Man (Official Video)", url: "https://www.youtube.com/watch?v=AqAJLh9wuZ0", reliability: 5, type: "official" }, { name: "The Man (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/The_Man_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "city-of-lover",
      kind: "performance",
      title: "Taylor Swift: City of Lover",
      director: null,
      releasedOn: "2020-05-17",
      relatedSongs: [],
      summary: "The one-night Paris concert special that became the Lover era's only live document after the pandemic canceled Lover Fest — aired on ABC, intimate theater instead of stadiums.",
      easterEggs: [],
      symbolism: null,
      youtubeId: null,
      sources: [{ name: "Taylor Swift City of Lover Concert", url: "https://en.wikipedia.org/wiki/Taylor_Swift_City_of_Lover_Concert", reliability: 2, type: "wiki" }, { name: "Listen to Taylor Swift's City of Lover Film Soundtrack", url: "https://pitchfork.com/news/listen-to-taylor-swifts-city-of-lover-film-soundtrack", reliability: 4, type: "reputable_press" }],
      tags: ["Music"],
    },
  ],
  "midnights": [
    {
      slug: "anti-hero-mv",
      kind: "music_video",
      title: "Anti-Hero",
      director: "Taylor Swift",
      releasedOn: "2022-10-21",
      relatedSongs: ["Anti-Hero"],
      summary: "Self-directed release-day centerpiece: Taylor hosts a house party for her own worst selves — a giant \"monster on the hill\" at the dinner table, a ghost at her funeral, and heirs squabbling over her will.",
      easterEggs: ["The squabbling funeral beneficiaries are played by comedians Mike Birbiglia, John Early and Mary Elizabeth Ellis — the will scene fans quote line-for-line."],
      symbolism: "Every setpiece literalizes a lyric: the too-big self at the table, the future reading of the will, the \"it's me, hi\" doubles — self-loathing staged as sitcom.",
      youtubeId: "b1kbLwvqugk",
      sources: [{ name: "Taylor Swift - Anti-Hero (Official Music Video)", url: "https://www.youtube.com/watch?v=b1kbLwvqugk", reliability: 5, type: "official" }, { name: "Anti-Hero (song)", url: "https://en.wikipedia.org/wiki/Anti-Hero_(song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "bejeweled-mv",
      kind: "music_video",
      title: "Bejeweled",
      director: "Taylor Swift",
      releasedOn: "2022-10-25",
      relatedSongs: ["Bejeweled"],
      summary: "A Cinderella retelling with Laura Dern as the wicked stepmother, HAIM as stepsisters and Dita Von Teese in the martini glass — and, by Taylor's own warning, packed wall-to-wall with easter eggs.",
      easterEggs: ["The elevator button for floor 3 lights up — read (correctly) as pointing at album #3, Speak Now.", "The purple gown and castle staging were decoded as Speak Now (Taylor's Version) signals months before its Nashville announcement."],
      symbolism: null,
      youtubeId: "b7QlX3yR2xs",
      sources: [{ name: "Taylor Swift - Bejeweled (Official Music Video)", url: "https://www.youtube.com/watch?v=b7QlX3yR2xs", reliability: 5, type: "official" }, { name: "Bejeweled (song)", url: "https://en.wikipedia.org/wiki/Bejeweled_(song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "lavender-haze-mv",
      kind: "music_video",
      title: "Lavender Haze",
      director: "Taylor Swift",
      releasedOn: "2023-01-27",
      relatedSongs: ["Lavender Haze"],
      summary: "The album's dreamiest visual: a purple fog rolls through a 70s-styled apartment, koi swim across the ceiling, and Taylor drifts from bed to a lavender field without the night ever ending.",
      easterEggs: [],
      symbolism: "The all-consuming lavender cloud is the song's borrowed 50s idiom for being untouchably in love — weather instead of narrative.",
      youtubeId: "h8DLofLM7No",
      sources: [{ name: "Lavender Haze", url: "https://en.wikipedia.org/wiki/Lavender_Haze", reliability: 2, type: "wiki" }, { name: "Taylor Swift Shares New \"Lavender Haze\" Video: Watch", url: "https://pitchfork.com/news/taylor-swift-shares-new-lavender-haze-video-watch", reliability: 4, type: "reputable_press" }],
      tags: ["Music"],
    },
    {
      slug: "i-can-see-you-mv",
      kind: "music_video",
      title: "I Can See You",
      director: "Taylor Swift",
      releasedOn: "2023-07-08",
      relatedSongs: ["I Can See You (Taylor's Version) (From the Vault)"],
      summary: "A vault-track heist: Joey King, Taylor Lautner, and Presley Cash break Taylor out of imprisonment in a vault — a metaphor for reclaiming her masters — premiered live at the July 7, 2023 Kansas City stop of the Eras Tour, the night Speak Now (Taylor's Version) dropped.",
      easterEggs: [],
      symbolism: "The vault break-out literalizes the re-recording project itself: taking her art back from Big Machine.",
      youtubeId: "lVkKLf4DCn8",
      sources: [{ name: "Taylor Swift - I Can See You (Taylor's Version) (From The Vault) (Official Video)", url: "https://www.youtube.com/watch?v=lVkKLf4DCn8", reliability: 5, type: "official" }, { name: "I Can See You (song)", url: "https://en.wikipedia.org/wiki/I_Can_See_You_(song)", reliability: 2, type: "wiki" }],
      tags: ["Music", "Tour"],
    },
    {
      slug: "eras-tour-film-premiere-carpet-2023",
      kind: "press_event",
      title: "Red carpet at the Eras Tour concert-film premiere",
      director: null,
      releasedOn: "2023-10-11",
      relatedSongs: [],
      summary: "The Eras Tour film premiere at The Grove, pulled forward a day by demand: a blue floral gown, the shopping centre closed to the public, and a carpet she works slowly along the barricades.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "X_wHLxTOzas",
      sources: [{ name: "Taylor Swift hits red carpet for premiere of ‘Eras Tour’ concert film l GMA", url: "https://www.youtube.com/watch?v=X_wHLxTOzas", reliability: 5, type: "official" }, { name: "The Grove shut down for Taylor Swift \"The Eras Tour\" movie premiere", url: "https://www.cbsnews.com/amp/losangeles/news/the-grove-shutdown-for-taylor-swift-the-eras-tour-movie-premiere", reliability: 4, type: "reputable_press" }],
      tags: ["Fashion"],
    },
    {
      slug: "taylor-swift-the-eras-tour-film",
      kind: "tour_film",
      title: "Taylor Swift: The Eras Tour",
      director: "Sam Wrench",
      releasedOn: "2023-10-13",
      relatedSongs: [],
      summary: "The SoFi Stadium shows cut into a theatrical event that broke the all-time concert-film box-office record — released straight to cinemas on a distribution deal negotiated with AMC itself.",
      easterEggs: [],
      symbolism: null,
      youtubeId: null,
      sources: [{ name: "Taylor Swift: The Eras Tour", url: "https://en.wikipedia.org/wiki/Taylor_Swift:_The_Eras_Tour", reliability: 2, type: "wiki" }, { name: "\"Taylor Swift: The Eras Tour\" Shatters Records and Becomes the Most-Watched Music Film on Disney+", url: "https://people.com/taylor-swift-the-eras-tour-most-watched-music-film-disney-plus-8611339", reliability: 4, type: "reputable_press" }],
      tags: ["Tour"],
    },
    {
      slug: "grammys-album-of-the-year-2024",
      kind: "award_speech",
      title: "Accepting Album of the Year for Midnights — 66th GRAMMYs",
      director: null,
      releasedOn: "2024-02-04",
      relatedSongs: [],
      summary: "A fourth Album of the Year, for Midnights: no artist in Grammy history had won it more than three times. She had already announced The Tortured Poets Department from the same stage earlier that night.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "Yq-q-ZCZwxc",
      sources: [{ name: "TAYLOR SWIFT Wins Album Of The Year For 'MIDNIGHTS' | 2024 GRAMMYs Acceptance Speech", url: "https://www.youtube.com/watch?v=Yq-q-ZCZwxc", reliability: 5, type: "official" }],
      tags: ["Music"],
    },
    {
      slug: "karma-mv",
      kind: "music_video",
      title: "Karma (feat. Ice Spice)",
      director: "Taylor Swift",
      releasedOn: null,
      relatedSongs: ["Karma"],
      summary: "Released with the Til Dawn edition remix: cosmic Taylor rides mythological karma imagery — a giant cat, a lassoed moon — with Ice Spice materializing for the new verse.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "XzOvgu3GPwY",
      sources: [{ name: "Taylor Swift ft. Ice Spice - Karma (Official Music Video)", url: "https://www.youtube.com/watch?v=XzOvgu3GPwY", reliability: 5, type: "official" }, { name: "Karma (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Karma_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
  ],
  "red": [
    {
      slug: "safe-and-sound-mv",
      kind: "music_video",
      title: "Safe & Sound",
      director: null,
      releasedOn: "2012-02-13",
      relatedSongs: ["Safe & Sound"],
      summary: "A barefoot walk through a Watertown, Tennessee forest and cemetery in a long white gown, intercut with The Civil Wars performing by firelight — recorded for The Hunger Games soundtrack, dotted with mockingjay references.",
      easterEggs: ["Taylor finds a mockingjay pin during the woods sequence, tying the video to the film's central symbol."],
      symbolism: null,
      youtubeId: "RzhAS_GnJIc",
      sources: [{ name: "Safe & Sound feat. The Civil Wars (The Hunger Games: Songs From District 12 And Beyond)", url: "https://www.youtube.com/watch?v=RzhAS_GnJIc", reliability: 5, type: "official" }, { name: "Safe & Sound (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Safe_%26_Sound_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "everything-has-changed-britains-got-talent-2013",
      kind: "performance",
      title: "Everything Has Changed — Britain's Got Talent",
      director: null,
      releasedOn: "2013-06-08",
      relatedSongs: ["Everything Has Changed"],
      summary: "A guest performance of \"Everything Has Changed\" with Ed Sheeran during the live final of Britain's Got Talent series 7, alongside fellow guest act Psy.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "YfPfgZjhH1w",
      sources: [{ name: "Britain's Got Talent performance: Everything Has Changed", url: "https://www.youtube.com/watch?v=YfPfgZjhH1w", reliability: 5, type: "official" }, { name: "Britain's Got Talent (series 7)", url: "https://en.wikipedia.org/wiki/Britain%27s_Got_Talent_(series_7)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "red-mv",
      kind: "music_video",
      title: "Red",
      director: "Kenny Jackson",
      releasedOn: "2013-07-03",
      relatedSongs: ["Red"],
      summary: "An edited concert-performance video cut from live shows in front of thousands of fans, rather than a scripted narrative — the album's fifth single.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "Zlot0i3Zykw",
      sources: [{ name: "Taylor Swift - Red", url: "https://www.youtube.com/watch?v=Zlot0i3Zykw", reliability: 5, type: "official" }, { name: "Red (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Red_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "22-mv",
      kind: "music_video",
      title: "22",
      director: "Anthony Mandler",
      releasedOn: null,
      relatedSongs: ["22"],
      summary: "Shot like a home movie of the best day off ever: real-friends hangout energy, the \"not a lot going on at the moment\" tee, a beach-party ending — breakfast at midnight canonized.",
      easterEggs: ["Anti-Hero's party ghosts wear the 22 video's heart-shaped sunglasses and cat ears, and the \"not a lot going on at the moment\" tee returned — reworded — as an Eras Tour costume."],
      symbolism: null,
      youtubeId: "AgFeZr5ptV8",
      sources: [{ name: "Taylor Swift - 22", url: "https://www.youtube.com/watch?v=AgFeZr5ptV8", reliability: 5, type: "official" }, { name: "22 (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/22_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "begin-again-mv",
      kind: "music_video",
      title: "Begin Again",
      director: "Philip Andelman",
      releasedOn: null,
      relatedSongs: ["Begin Again"],
      summary: "Shot in Paris: a slow, sunlit walk out of one story and into the possibility of another — café tables, cobblestones, and the album's gentlest landing.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "cMPEd8m79Hw",
      sources: [{ name: "Begin Again (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Begin_Again_(Taylor_Swift_song)", reliability: 2, type: "wiki" }, { name: "Taylor Swift Starts Over in Scenic 'Begin Again' Video", url: "https://tasteofcountry.com/taylor-swift-begin-again-video/", reliability: 4, type: "reputable_press" }],
      tags: ["Music"],
    },
    {
      slug: "everything-has-changed-mv",
      kind: "music_video",
      title: "Everything Has Changed",
      director: "Philip Andelman",
      releasedOn: null,
      relatedSongs: ["Everything Has Changed"],
      summary: "Two grade-schoolers play out the duet's friendship-into-something-more — and the kicker reveals Taylor and Ed Sheeran as the parents picking them up.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "w1oM3kQpXRo",
      sources: [{ name: "Everything Has Changed", url: "https://en.wikipedia.org/wiki/Everything_Has_Changed", reliability: 2, type: "wiki" }, { name: "Taylor Swift, Ed Sheeran Return to Childhood in 'Everything Has Changed' Video: Watch", url: "https://www.billboard.com/music/music-news/taylor-swift-ed-sheeran-return-to-childhood-in-everything-has-changed-video-watch-1565874/", reliability: 4, type: "reputable_press" }],
      tags: ["Music"],
    },
    {
      slug: "i-knew-you-were-trouble-mv",
      kind: "music_video",
      title: "I Knew You Were Trouble",
      director: "Anthony Mandler",
      releasedOn: null,
      relatedSongs: ["I Knew You Were Trouble"],
      summary: "A two-minute spoken prologue, a desert festival, a doomed bad-boy romance told in flashback grit — the era's deliberate swerve from country sweetheart staging into pop cinema.",
      easterEggs: [],
      symbolism: "Waking up alone in the desert bookends the story: the video opens on the aftermath and spends its runtime explaining the wreckage.",
      youtubeId: "vNoKguSdy4Y",
      sources: [{ name: "Taylor Swift - I Knew You Were Trouble", url: "https://www.youtube.com/watch?v=vNoKguSdy4Y", reliability: 5, type: "official" }, { name: "I Knew You Were Trouble", url: "https://en.wikipedia.org/wiki/I_Knew_You_Were_Trouble", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "love-story-live-from-new-york-city",
      kind: "performance",
      title: "Love Story (Live from New York City)",
      director: null,
      releasedOn: null,
      relatedSongs: ["Love Story"],
      summary: "A solo live performance of the Fearless-era catalog hit taped in New York City during the Red run, one of six songs the official channel posted under the \"Live From New York City\" banner.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "yfWgXcrNQIw",
      sources: [{ name: "Taylor Swift - Love Story (Live from New York City)", url: "https://www.youtube.com/watch?v=yfWgXcrNQIw", reliability: 5, type: "official" }, { name: "Love Story (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Love_Story_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "mean-live-from-new-york-city",
      kind: "performance",
      title: "Mean (Live from New York City)",
      director: null,
      releasedOn: null,
      relatedSongs: ["Mean"],
      summary: "A solo live performance of the Grammy-winning Speak Now single taped in New York City during the Red run, one of six songs the official channel posted under the \"Live From New York City\" banner.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "RQuY8kERaU0",
      sources: [{ name: "Taylor Swift - Mean (Live from New York City)", url: "https://www.youtube.com/watch?v=RQuY8kERaU0", reliability: 5, type: "official" }, { name: "Mean (song)", url: "https://en.wikipedia.org/wiki/Mean_(song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "red-live-from-new-york-city",
      kind: "performance",
      title: "Red (Live from New York City)",
      director: null,
      releasedOn: null,
      relatedSongs: ["Red"],
      summary: "A solo live performance of the title track taped in New York City, one of six Red-era and catalog songs the official channel posted under the \"Live From New York City\" banner.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "gQ0pP2z9niw",
      sources: [{ name: "Taylor Swift - Red (Live from New York City)", url: "https://www.youtube.com/watch?v=gQ0pP2z9niw", reliability: 5, type: "official" }, { name: "Red (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Red_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "the-last-time-mv",
      kind: "music_video",
      title: "The Last Time",
      director: null,
      releasedOn: null,
      relatedSongs: ["The Last Time"],
      summary: "A live-performance video built from Red Tour footage of Taylor and duet partner Gary Lightbody trading the song's dueling verses onstage, seated on facing stools — the album's final single.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "QuijXg8wm28",
      sources: [{ name: "Taylor Swift - The Last Time ft. Gary Lightbody", url: "https://www.youtube.com/watch?v=QuijXg8wm28", reliability: 5, type: "official" }, { name: "The Last Time (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/The_Last_Time_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "we-are-never-ever-getting-back-together-mv",
      kind: "music_video",
      title: "We Are Never Ever Getting Back Together",
      director: "Declan Whitebloom",
      releasedOn: null,
      relatedSongs: ["We Are Never Ever Getting Back Together"],
      summary: "Styled as one continuous take through a storybook house party — pajamas, a phone call, and a band in animal costumes — for her first Hot 100 #1.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "WA4iX5D9Z64",
      sources: [{ name: "Taylor Swift - We Are Never Ever Getting Back Together", url: "https://www.youtube.com/watch?v=WA4iX5D9Z64", reliability: 5, type: "official" }, { name: "We Are Never Ever Getting Back Together", url: "https://en.wikipedia.org/wiki/We_Are_Never_Ever_Getting_Back_Together", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "we-are-never-ever-getting-back-together-live-from-new-york-city",
      kind: "performance",
      title: "We Are Never Ever Getting Back Together (Live from New York City)",
      director: null,
      releasedOn: null,
      relatedSongs: ["We Are Never Ever Getting Back Together"],
      summary: "A solo live performance of the Red lead single taped in New York City, one of six Red-era and catalog songs the official channel posted under the \"Live From New York City\" banner.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "BktS1hkMx_k",
      sources: [{ name: "Taylor Swift - We Are Never Ever Getting Back Together (Live from New York City)", url: "https://www.youtube.com/watch?v=BktS1hkMx_k", reliability: 5, type: "official" }, { name: "We Are Never Ever Getting Back Together", url: "https://en.wikipedia.org/wiki/We_Are_Never_Ever_Getting_Back_Together", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "you-belong-with-me-live-from-new-york-city",
      kind: "performance",
      title: "You Belong with Me (Live from New York City)",
      director: null,
      releasedOn: null,
      relatedSongs: ["You Belong with Me"],
      summary: "A solo live performance of the Fearless-era catalog hit taped in New York City during the Red run, one of six songs the official channel posted under the \"Live From New York City\" banner.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "tvnGBYMe9gM",
      sources: [{ name: "Taylor Swift - You Belong With Me (Live from New York City)", url: "https://www.youtube.com/watch?v=tvnGBYMe9gM", reliability: 5, type: "official" }, { name: "You Belong with Me", url: "https://en.wikipedia.org/wiki/You_Belong_with_Me", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
  ],
  "reputation": [
    {
      slug: "look-what-you-made-me-do-mv",
      kind: "music_video",
      title: "Look What You Made Me Do",
      director: "Joseph Kahn",
      releasedOn: "2017-08-27",
      relatedSongs: ["Look What You Made Me Do"],
      summary: "The VMA-premiered resurrection: zombie Taylor claws out of a grave, a snake serves tea on a throne, and the finale lines up fifteen past Taylors to bicker over which one is fake.",
      easterEggs: ["The gravestone reads Nils Sjöberg — the pseudonym she used as a songwriter on \"This Is What You Came For.\"", "\"The old Taylor can't come to the phone right now\" is delivered from atop a mountain of her past selves; the closing lineup of fifteen era-Taylors instead bickers over her old media narratives.", "The \"Junior Jewels\" shirt from You Belong with Me returns, now scrawled with her real friends' names."],
      symbolism: "Every set piece answers a headline from the preceding decade — the era's whole thesis is that she is burying the old narratives on camera.",
      youtubeId: "3tmd-ClpJxA",
      sources: [{ name: "Taylor Swift - Look What You Made Me Do", url: "https://www.youtube.com/watch?v=3tmd-ClpJxA", reliability: 5, type: "official" }, { name: "Look What You Made Me Do", url: "https://en.wikipedia.org/wiki/Look_What_You_Made_Me_Do", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "ready-for-it-mv",
      kind: "music_video",
      title: "...Ready for It?",
      director: "Joseph Kahn",
      releasedOn: "2017-10-26",
      relatedSongs: ["...Ready for It?"],
      summary: "Cyberpunk Taylor vs. Taylor: a cloaked figure walks a neon corridor to confront a caged android version of herself — the robot cracks its shell and levels the wall between them.",
      easterEggs: [],
      symbolism: "Widely read (and reported) as public-image Taylor confronting the real one — the naked android is the self the armor was built around.",
      youtubeId: "wIft-t-MQuE",
      sources: [{ name: "Taylor Swift - ...Ready For It?", url: "https://www.youtube.com/watch?v=wIft-t-MQuE", reliability: 5, type: "official" }, { name: "...Ready for It?", url: "https://en.wikipedia.org/wiki/...Ready_for_It%3F", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "end-game-mv",
      kind: "music_video",
      title: "End Game",
      director: "Joseph Kahn",
      releasedOn: "2018-01-12",
      relatedSongs: ["End Game"],
      summary: "A globe-hopping party flex — Miami boat lights, Tokyo arcades, London double-deckers — with Ed Sheeran and Future riding shotgun through the era's one pure hangout video.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "dfnCAmr569k",
      sources: [{ name: "Taylor Swift - End Game ft. Ed Sheeran, Future", url: "https://www.youtube.com/watch?v=dfnCAmr569k", reliability: 5, type: "official" }, { name: "End Game (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/End_Game_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "delicate-mv",
      kind: "music_video",
      title: "Delicate",
      director: "Joseph Kahn",
      releasedOn: "2018-03-11",
      relatedSongs: ["Delicate"],
      summary: "Premiered at the iHeartRadio Awards: a note makes Taylor invisible mid-press-gauntlet, and she dances unwatched through a hotel — lobby, hallway, rain — until the note's magic runs out at a dive bar.",
      easterEggs: [],
      symbolism: "Invisibility as relief: the fame-armor drops the second nobody can see her, which is the lyric's whole ache — wanting one person to see through it on purpose.",
      youtubeId: "tCXGJQYZ9JA",
      sources: [{ name: "Taylor Swift - Delicate", url: "https://www.youtube.com/watch?v=tCXGJQYZ9JA", reliability: 5, type: "official" }, { name: "Delicate (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Delicate_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "angels-with-robbie-williams-reputation-tour-2018",
      kind: "performance",
      title: "Angels (with Robbie Williams) — reputation Stadium Tour, Wembley",
      director: null,
      releasedOn: "2018-06-23",
      relatedSongs: [],
      summary: "A surprise Wembley Stadium duet: Robbie Williams joins for his own 1997 hit \"Angels\" during the London stop of the reputation Stadium Tour.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "RamgJyJsep4",
      sources: [{ name: "Taylor Swift and Robbie Williams - Angels - reputation Stadium Tour", url: "https://www.youtube.com/watch?v=RamgJyJsep4", reliability: 5, type: "official" }, { name: "Reputation Stadium Tour", url: "https://en.wikipedia.org/wiki/Reputation_Stadium_Tour", reliability: 2, type: "wiki" }],
      tags: ["Tour"],
    },
    {
      slug: "reputation-stadium-tour-film",
      kind: "tour_film",
      title: "Taylor Swift: reputation Stadium Tour",
      director: "Paul Dugdale",
      releasedOn: "2018-12-31",
      relatedSongs: [],
      summary: "The Dallas stadium show, released to Netflix on New Year's Eve — the snake-throne era preserved in full, from the tilted stage to the Long Live/New Year's Day piano coda.",
      easterEggs: [],
      symbolism: null,
      youtubeId: null,
      sources: [{ name: "Taylor Swift: Reputation Stadium Tour", url: "https://en.wikipedia.org/wiki/Taylor_Swift:_Reputation_Stadium_Tour", reliability: 2, type: "wiki" }, { name: "Taylor Swift's Reputation Film Shows Why She's One of the All-Time Greats", url: "https://www.rollingstone.com/music/music-live-reviews/taylor-swift-reputation-stadium-tour-netflix-movie-review-773808/", reliability: 4, type: "reputable_press" }],
      tags: ["Tour"],
    },
  ],
  "speak-now": [
    {
      slug: "speak-now-live-letterman",
      kind: "performance",
      title: "Speak Now (Live on Letterman)",
      director: null,
      releasedOn: "2010-10-26",
      relatedSongs: ["Speak Now"],
      summary: "A solo performance of the title track on the Late Show with David Letterman, taped the day after the album's October 25, 2010 release.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "4wUPASp2hfY",
      sources: [{ name: "Taylor Swift - Speak Now (Live on Letterman)", url: "https://www.youtube.com/watch?v=4wUPASp2hfY", reliability: 5, type: "official" }, { name: "Speak Now (song)", url: "https://en.wikipedia.org/wiki/Speak_Now_(song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "you-belong-with-me-live-letterman",
      kind: "performance",
      title: "You Belong With Me (Live on Letterman)",
      director: null,
      releasedOn: "2010-12-07",
      relatedSongs: ["You Belong with Me"],
      summary: "A solo TV performance of the Fearless-era hit on the Late Show with David Letterman, uploaded during the Speak Now promotional cycle alongside the era's other Letterman performance videos.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "zudLJdajX5Y",
      sources: [{ name: "Taylor Swift - You Belong With Me (Live on Letterman)", url: "https://www.youtube.com/watch?v=zudLJdajX5Y", reliability: 5, type: "official" }, { name: "You Belong with Me", url: "https://en.wikipedia.org/wiki/You_Belong_with_Me", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "mine-live-bbc-radio-2",
      kind: "performance",
      title: "Mine (Live, BBC Radio 2 Session)",
      director: null,
      releasedOn: "2011-08-24",
      relatedSongs: ["Mine"],
      summary: "An acoustic session performance of \"Mine\" recorded for BBC Radio 2, posted to her official channel the same day as her Coldplay \"Viva La Vida\" cover from the same session.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "_9RWI5JBew0",
      sources: [{ name: "Taylor Swift - Mine (Live, BBC Radio 2 Session)", url: "https://www.youtube.com/watch?v=_9RWI5JBew0", reliability: 5, type: "official" }, { name: "Mine (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Mine_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "viva-la-vida-cover-bbc-radio-2",
      kind: "performance",
      title: "Viva La Vida",
      director: null,
      releasedOn: "2011-08-24",
      relatedSongs: [],
      summary: "A three-guitar acoustic cover of Coldplay's \"Viva La Vida,\" recorded in a BBC Radio 2 studio during the Speak Now era and posted the same day as her BBC session performance of \"Mine.\"",
      easterEggs: [],
      symbolism: null,
      youtubeId: "AcGbuveDwTg",
      sources: [{ name: "Taylor Swift - Viva La Vida", url: "https://www.youtube.com/watch?v=AcGbuveDwTg", reliability: 5, type: "official" }, { name: "Taylor Swift's roots unearthed as young star's rare, old-school Coldplay cover is rediscovered online", url: "https://www.themusicman.uk/rare-taylor-swift-coldplay-cover/", reliability: 4, type: "reputable_press" }],
      tags: ["Music"],
    },
    {
      slug: "speak-now-world-tour-live",
      kind: "tour_film",
      title: "Speak Now World Tour – Live",
      director: null,
      releasedOn: "2011-11-21",
      relatedSongs: [],
      summary: "The theatrical Speak Now show — aerial ballet, the levitating balcony, the confetti-showered Love Story finale performed from a flying balcony — captured across the 2011 arena run and released as a live CD/DVD.",
      easterEggs: [],
      symbolism: null,
      youtubeId: null,
      sources: [{ name: "Speak Now World Tour", url: "https://en.wikipedia.org/wiki/Speak_Now_World_Tour", reliability: 2, type: "wiki" }, { name: "Taylor Swift Announces Speak Now World Tour Live CD/DVD", url: "https://www.hollywoodreporter.com/news/general-news/taylor-swift-speak-now-tour-live-cd-dvd-263669/", reliability: 4, type: "reputable_press" }],
      tags: ["Tour"],
    },
    {
      slug: "back-to-december-mv",
      kind: "music_video",
      title: "Back to December",
      director: "Yoann Lemoine",
      releasedOn: null,
      relatedSongs: ["Back to December"],
      summary: "Snow falls indoors: Taylor writes an apology from a room slowly buried in winter while the boy she wronged moves through parallel scenes — her first video built on a single sustained visual metaphor.",
      easterEggs: [],
      symbolism: "The encroaching snow literalizes the regret the lyric circles — December overtaking the room as the apology goes unanswered.",
      youtubeId: "QUwxKWT6m7U",
      sources: [{ name: "Taylor Swift - Back To December", url: "https://www.youtube.com/watch?v=QUwxKWT6m7U", reliability: 5, type: "official" }, { name: "Back to December", url: "https://en.wikipedia.org/wiki/Back_to_December", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "back-to-december-live-letterman",
      kind: "performance",
      title: "Back to December (Live on Letterman)",
      director: null,
      releasedOn: null,
      relatedSongs: ["Back to December"],
      summary: "A solo TV performance of the Speak Now ballad on the Late Show with David Letterman, part of the same album-era promotional run that put \"Speak Now\" and \"Mine\" on the show.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "vio0RidOMUM",
      sources: [{ name: "Taylor Swift - Back To December (Live on Letterman)", url: "https://www.youtube.com/watch?v=vio0RidOMUM", reliability: 5, type: "official" }, { name: "Back to December", url: "https://en.wikipedia.org/wiki/Back_to_December", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "mean-mv",
      kind: "music_video",
      title: "Mean",
      director: "Declan Whitebloom",
      releasedOn: null,
      relatedSongs: ["Mean"],
      summary: "Banjo-vaudeville staging with a moral: the mocked kids of the verses grow up and out — into the big city, the stadium, the life the bully said they'd never have — while the band plays a saloon set.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "jYa1eI1hpDE",
      sources: [{ name: "Taylor Swift - Mean", url: "https://www.youtube.com/watch?v=jYa1eI1hpDE", reliability: 5, type: "official" }, { name: "Mean (song)", url: "https://en.wikipedia.org/wiki/Mean_(song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "mine-mv",
      kind: "music_video",
      title: "Mine",
      director: "Roman White",
      releasedOn: null,
      relatedSongs: ["Mine"],
      summary: "A whole imagined lifetime in four minutes: from café glance to kids and a kitchen argument and back — the flash-forward fantasy structure the song's \"careless man's careful daughter\" narrates.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "XPBwXKgDTdE",
      sources: [{ name: "Taylor Swift - Mine", url: "https://www.youtube.com/watch?v=XPBwXKgDTdE", reliability: 5, type: "official" }, { name: "Mine (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Mine_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "mine-live-letterman",
      kind: "performance",
      title: "Mine (Live on Letterman)",
      director: null,
      releasedOn: null,
      relatedSongs: ["Mine"],
      summary: "A solo TV performance of the Speak Now lead single on the Late Show with David Letterman, part of the same album-era promotional run that put \"Speak Now\" and \"Back to December\" on the show.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "xcLIGAIkztc",
      sources: [{ name: "Taylor Swift - Mine (Live on Letterman)", url: "https://www.youtube.com/watch?v=xcLIGAIkztc", reliability: 5, type: "official" }, { name: "Mine (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Mine_(Taylor_Swift_song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "ours-mv",
      kind: "music_video",
      title: "Ours",
      director: "Declan Whitebloom",
      releasedOn: null,
      relatedSongs: ["Ours"],
      summary: "Taylor plays an office worker grinding through corporate monotony — bus commute, water-cooler small talk — until the day ends at the airport, where she reunites with her boyfriend, a soldier returning home, played by Zach Gilford.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "LZ34LlaIk88",
      sources: [{ name: "Taylor Swift - Ours", url: "https://www.youtube.com/watch?v=LZ34LlaIk88", reliability: 5, type: "official" }, { name: "Ours (song)", url: "https://en.wikipedia.org/wiki/Ours_(song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "sparks-fly-mv",
      kind: "music_video",
      title: "Sparks Fly",
      director: null,
      releasedOn: null,
      relatedSongs: ["Sparks Fly"],
      summary: "A live-performance video compiled from Speak Now World Tour footage, directed by Christian Lamb and released August 2011 — the album's fifth single.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "oKar-tF__ac",
      sources: [{ name: "Taylor Swift - Sparks Fly", url: "https://www.youtube.com/watch?v=oKar-tF__ac", reliability: 5, type: "official" }, { name: "Sparks Fly (song)", url: "https://en.wikipedia.org/wiki/Sparks_Fly_(song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "the-story-of-us-mv",
      kind: "music_video",
      title: "The Story of Us",
      director: "Noble Jones",
      releasedOn: null,
      relatedSongs: ["The Story of Us"],
      summary: "A library at war: two exes study tables apart as the silence gets louder, pages fly, and the \"chapter\" conceit of the lyric plays out in the stacks.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "nN6VR92V70M",
      sources: [{ name: "The Story of Us (song)", url: "https://en.wikipedia.org/wiki/The_Story_of_Us_(song)", reliability: 2, type: "wiki" }, { name: "Taylor Swift Tells 'The Story of Us' in New Video", url: "https://tasteofcountry.com/taylor-swift-story-of-us-video/", reliability: 4, type: "reputable_press" }],
      tags: ["Music"],
    },
  ],
  "tloas": [
    {
      slug: "new-heights-podcast-2025",
      kind: "interview",
      title: "New Heights — announcing The Life of a Showgirl",
      director: null,
      releasedOn: "2025-08-13",
      relatedSongs: [],
      summary: "Her first-ever podcast appearance, on Jason and Travis Kelce’s show: a mint-green briefcase opens on album No. 12, out October 3, plus buying back her masters. The livestream buckled at roughly 1.3 million concurrent viewers.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "M2lX9XESvDE",
      sources: [{ name: "Taylor Swift on Reclaiming Her Masters, Wrapping The Eras Tour, and The Life of a Showgirl | NHTV", url: "https://www.youtube.com/watch?v=M2lX9XESvDE", reliability: 5, type: "official" }],
      tags: ["Music"],
    },
    {
      slug: "graham-norton-2025",
      kind: "interview",
      title: "The Graham Norton Show",
      director: null,
      releasedOn: "2025-10-02",
      relatedSongs: [],
      summary: "On the Graham Norton couch as The Life of a Showgirl lands: album promo that detours into wedding plans, and an invitation for the host.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "NlOdFJmkEls",
      sources: [{ name: "Taylor Swift Invites Graham Norton To Her Wedding - BBC", url: "https://www.youtube.com/watch?v=NlOdFJmkEls", reliability: 5, type: "official" }],
      tags: ["Music", "Relationship"],
    },
    {
      slug: "the-official-release-party-of-a-showgirl",
      kind: "performance",
      title: "The Official Release Party of a Showgirl",
      director: null,
      releasedOn: "2025-10-03",
      relatedSongs: [],
      summary: "Release weekend as a cinema event: the Ophelia video premiere, lyric videos, and behind-the-scenes cuts packaged into a theatrical party that topped the box office on album weekend.",
      easterEggs: [],
      symbolism: null,
      youtubeId: null,
      sources: [{ name: "The Official Release Party of a Showgirl", url: "https://en.wikipedia.org/wiki/The_Official_Release_Party_of_a_Showgirl", reliability: 2, type: "wiki" }, { name: "Taylor Swift Debuts The Fate of Ophelia Music Video After Premiering It at Life of a Showgirl Movie Event", url: "https://people.com/taylor-swift-the-fate-of-ophelia-music-video-11823344", reliability: 4, type: "reputable_press" }],
      tags: ["Music"],
    },
    {
      slug: "the-fate-of-ophelia-mv",
      kind: "music_video",
      title: "The Fate of Ophelia",
      director: "Taylor Swift",
      releasedOn: "2025-10-05",
      relatedSongs: ["The Fate of Ophelia"],
      summary: "The lead single's video premiered as the centerpiece of the release-party theatrical event: showgirl staging that pulls Ophelia out of the water and onto the stage, inverting the Hamlet ending.",
      easterEggs: [],
      symbolism: "Rescue-by-love replaces the drowning — the era's glitter is framed as the survivable version of the tragedy.",
      youtubeId: "ko70cExuzZM",
      sources: [{ name: "The Fate of Ophelia", url: "https://en.wikipedia.org/wiki/The_Fate_of_Ophelia", reliability: 2, type: "wiki" }, { name: "Taylor Swift Debuts The Fate of Ophelia Music Video After Premiering It at Life of a Showgirl Movie Event", url: "https://people.com/taylor-swift-the-fate-of-ophelia-music-video-11823344", reliability: 4, type: "reputable_press" }, { name: "Taylor Swift - The Fate of Ophelia (Official Music Video)", url: "https://www.youtube.com/watch?v=ko70cExuzZM", reliability: 5, type: "official" }],
      tags: ["Music"],
    },
    {
      slug: "tonight-show-fallon-2025",
      kind: "interview",
      title: "The Tonight Show Starring Jimmy Fallon",
      director: null,
      releasedOn: "2025-10-06",
      relatedSongs: [],
      summary: "Roughly twenty minutes with Fallon on the new album, the engagement and regaining her masters — including why she is not playing the 2026 Super Bowl halftime show. An extended cut aired as its own special four days later.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "GzjZqH0WRwE",
      sources: [{ name: "Taylor Swift Stops by The Tonight Show | The Tonight Show Starring Jimmy Fallon", url: "https://www.youtube.com/watch?v=GzjZqH0WRwE", reliability: 5, type: "official" }, { name: "Taylor Swift on The Tonight Show", url: "https://www.hollywoodreporter.com/music/music-news/taylor-swift-jimmy-fallon-tonight-show-life-of-a-showgirl-1236394527/", reliability: 4, type: "reputable_press" }, { name: "How to Watch the Extended Taylor Swift Tonight Show Interview", url: "https://www.nbc.com/nbc-insider/how-to-watch-taylor-swift-extended-tonight-show-interview", reliability: 4, type: "reputable_press" }],
      tags: ["Music", "Relationship"],
    },
    {
      slug: "zane-lowe-apple-music-2025",
      kind: "interview",
      title: "The Zane Lowe Interview — Apple Music",
      director: null,
      releasedOn: "2025-10-07",
      relatedSongs: [],
      summary: "An extended sit-down with Zane Lowe, conducted over FaceTime, on how The Life of a Showgirl was written.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "mUZ9T-hstUI",
      sources: [{ name: "Taylor Swift: The Life of a Showgirl and Writing Process | The Zane Lowe Interview", url: "https://www.youtube.com/watch?v=mUZ9T-hstUI", reliability: 5, type: "official" }],
      tags: ["Music"],
    },
    {
      slug: "late-night-seth-meyers-2025",
      kind: "interview",
      title: "Late Night with Seth Meyers — the sole-guest episode",
      director: null,
      releasedOn: "2025-10-08",
      relatedSongs: [],
      summary: "A rare sole-guest episode of Late Night: the album, Travis Kelce, and a full hour built around one interview.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "Wd7S1wZqkbI",
      sources: [{ name: "Taylor Swift and Seth Talk The Life of a Showgirl, Travis Kelce and More", url: "https://www.youtube.com/watch?v=Wd7S1wZqkbI", reliability: 5, type: "official" }, { name: "Taylor Swift Extended Interview on Late Night With Seth Meyers", url: "https://variety.com/2025/music/news/taylor-swift-extended-interview-late-night-with-seth-meyers-1236534347/", reliability: 4, type: "reputable_press" }],
      tags: ["Music", "Relationship"],
    },
    {
      slug: "late-show-colbert-2025",
      kind: "interview",
      title: "The Late Show with Stephen Colbert",
      director: null,
      releasedOn: "2025-12-10",
      relatedSongs: [],
      summary: "Her first time on Colbert's couch: The End of an Era docuseries and The Final Show film, the engagement, the masters — and a ranking of her own top five songs.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "qtyzac0JbS4",
      sources: [{ name: "Taylor Swift's Good Year: Engaged To The Love Of Her Life, In Control Of Her Music Masters", url: "https://www.youtube.com/watch?v=qtyzac0JbS4", reliability: 5, type: "official" }, { name: "Taylor Swift on The Late Show", url: "https://www.rollingstone.com/music/music-news/taylor-swift-engagement-masters-showgirl-late-show-1235482380/", reliability: 4, type: "reputable_press" }, { name: "Taylor Swift's Five Favorite Taylor Swift Songs", url: "https://www.billboard.com/music/pop/taylor-swift-five-favorite-taytay-songs-colbert-1236134507/", reliability: 4, type: "reputable_press" }],
      tags: ["Music", "Relationship"],
    },
    {
      slug: "opalite-mv",
      kind: "music_video",
      title: "Opalite",
      director: null,
      releasedOn: "2026-01-12",
      relatedSongs: ["Opalite"],
      summary: "A 1990s-styled rom-com in which Taylor's lonely Pet Rock owner and Domhnall Gleeson's cactus owner are brought together by a magical \"Opalite\" spray — released as the era's second single.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "1FVF-9KQiPo",
      sources: [{ name: "Taylor Swift - Opalite (Official Music Video)", url: "https://www.youtube.com/watch?v=1FVF-9KQiPo", reliability: 5, type: "official" }, { name: "Opalite (song)", url: "https://en.wikipedia.org/wiki/Opalite_(song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "elizabeth-taylor-mv",
      kind: "music_video",
      title: "Elizabeth Taylor",
      director: null,
      releasedOn: "2026-03-09",
      relatedSongs: ["Elizabeth Taylor"],
      summary: "The album's third single, named for the screen icon, arrives with its own official video as part of an extended single cycle five months after the album's release.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "WqbJT_vC0rs",
      sources: [{ name: "Taylor Swift - Elizabeth Taylor (Official Music Video)", url: "https://www.youtube.com/watch?v=WqbJT_vC0rs", reliability: 5, type: "official" }, { name: "The Life of a Showgirl", url: "https://en.wikipedia.org/wiki/The_Life_of_a_Showgirl", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "i-knew-it-i-knew-you-mv",
      kind: "music_video",
      title: "I Knew It, I Knew You",
      director: null,
      releasedOn: "2026-06-05",
      relatedSongs: ["I Knew It, I Knew You"],
      summary: "The Toy Story 5 single's official video is built entirely from Toy Story franchise footage centered on Jessie — her meeting Woody, being abandoned by Emily, and finding a new home with Bonnie.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "hDU4GB1PTxc",
      sources: [{ name: "Taylor Swift - I Knew It, I Knew You (from Toy Story 5)", url: "https://www.youtube.com/watch?v=hDU4GB1PTxc", reliability: 5, type: "official" }, { name: "I Knew It, I Knew You", url: "https://en.wikipedia.org/wiki/I_Knew_It,_I_Knew_You", reliability: 2, type: "wiki" }, { name: "Taylor Swift Wrote and Recorded 'I Knew It, I Knew You' in 8 Hours Right After Watching 'Toy Story 5'", url: "https://variety.com/2026/music/news/taylor-swift-wrote-recorded-toy-story-song-eight-hours-1236785352/", reliability: 4, type: "reputable_press" }],
      tags: ["Music"],
    },
    {
      slug: "icon-sessions-grammy-museum-medley",
      kind: "performance",
      title: "The Icon Sessions at the Grammy Museum",
      director: null,
      releasedOn: "2026-08-24",
      relatedSongs: ["I Knew It, I Knew You", "August", "All Too Well"],
      summary: "A medley of \"I Knew It, I Knew You,\" \"August\" and \"All Too Well\" for The Recording Academy Songwriters & Composers Wing 20-Year Retrospective, live at the Grammy Museum — pairing her Toy Story 5 single with catalog favorites from folklore and Red.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "_9jaJtmraXA",
      sources: [{ name: "Taylor Swift Performance - The Icon Sessions at the Grammy Museum", url: "https://www.youtube.com/watch?v=_9jaJtmraXA", reliability: 5, type: "official" }],
      tags: ["Music"],
    },
  ],
  "ttpd": [
    {
      slug: "fortnight-mv",
      kind: "music_video",
      title: "Fortnight (feat. Post Malone)",
      director: "Taylor Swift",
      releasedOn: "2024-04-19",
      relatedSongs: ["Fortnight"],
      summary: "Black-and-white asylum-for-poets imagery: Taylor is committed to an asylum and later enters a room marked \"The Tortured Poets Department,\" where Post Malone types across from her — with Dead Poets Society's Ethan Hawke and Josh Charles as the doctors.",
      easterEggs: ["Ethan Hawke and Josh Charles — two of the original Dead Poets Society cast — cameo as the doctors, a casting-level pun on the album title."],
      symbolism: "The typewriter-era styling and the institution of tortured poets literalize the album's conceit: heartbreak processed as manuscript, \"I love you, it's ruining my life\" typed instead of said.",
      youtubeId: "q3zqJs7JUCQ",
      sources: [{ name: "Taylor Swift - Fortnight (feat. Post Malone) (Official Music Video)", url: "https://www.youtube.com/watch?v=q3zqJs7JUCQ", reliability: 5, type: "official" }, { name: "Fortnight (song)", url: "https://en.wikipedia.org/wiki/Fortnight_(song)", reliability: 2, type: "wiki" }],
      tags: ["Music"],
    },
    {
      slug: "vmas-fortnight-speech-2024",
      kind: "award_speech",
      title: "Accepting Best Collaboration for 'Fortnight' — 2024 VMAs",
      director: null,
      releasedOn: "2024-09-11",
      relatedSongs: [],
      summary: "Accepting Best Collaboration for 'Fortnight' with Post Malone, she stops the speech to mark the date: the anniversary of September 11.",
      easterEggs: [],
      symbolism: null,
      youtubeId: "g55D_gAoC3I",
      sources: [{ name: "Taylor Swift Remembers 9/11 During VMAs Acceptance Speech", url: "https://www.youtube.com/watch?v=g55D_gAoC3I", reliability: 5, type: "official" }],
      tags: ["Music"],
    },
    {
      slug: "i-can-do-it-with-a-broken-heart-mv",
      kind: "music_video",
      title: "I Can Do It with a Broken Heart",
      director: "Taylor Swift",
      releasedOn: null,
      relatedSongs: ["I Can Do It with a Broken Heart"],
      summary: "Built from real Eras Tour rehearsal and backstage footage: the show-must-go-on song scored by the machinery of the actual show — lifts, quick changes, and the smile snapping on at places, everyone.",
      easterEggs: [],
      symbolism: "Using documentary tour footage as the \"set\" makes the lyric literal: the biggest tour ever staged is the broken heart's day job.",
      youtubeId: "Sl6en1NPTYM",
      sources: [{ name: "I Can Do It with a Broken Heart", url: "https://en.wikipedia.org/wiki/I_Can_Do_It_with_a_Broken_Heart", reliability: 2, type: "wiki" }, { name: "Taylor Swift Offers Inside Look at Tour - and Confirms How She Gets Onstage - with 'I Can Do It with a Broken Heart' Video", url: "https://people.com/taylor-swift-releases-i-can-do-it-with-a-broken-heart-music-video-8698971", reliability: 4, type: "reputable_press" }],
      tags: ["Music", "Tour"],
    },
  ],
};
