// GENERATED FILE — do not hand-edit.
// Produced by scripts/sync-longlive-videos.mjs from supabase/seed/videos/**
// (or the live Supabase video_work table when configured).
// Re-run that script after video-seed changes; don't edit this file directly.

import type { EraId, VideoNote } from './types';

export const VIDEOS_RAW: Partial<Record<EraId, VideoNote[]>> = {
  "1989": [
    {
      slug: "shake-it-off-mv",
      kind: "music_video",
      title: "Shake It Off",
      director: "Mark Romanek",
      releasedOn: "2014-08-18",
      relatedSongs: ["Shake It Off"],
      summary: "Dropped the day 1989 was announced: Taylor gamely flails through ballet, breakdance, twerk squads and cheer lines before the finale says the quiet part — just dance like the fans do.",
      easterEggs: [],
      youtubeId: "nfWlot6h_JM",
      sources: [{ name: "Taylor Swift - Shake It Off", url: "https://www.youtube.com/watch?v=nfWlot6h_JM" }, { name: "Shake It Off", url: "https://en.wikipedia.org/wiki/Shake_It_Off" }],
    },
    {
      slug: "blank-space-mv",
      kind: "music_video",
      title: "Blank Space",
      director: "Joseph Kahn",
      releasedOn: "2014-11-10",
      relatedSongs: ["Blank Space"],
      summary: "The satire that ended the \"boy-crazy\" narrative by playing it to the hilt: a mansion romance curdles into golf-club-to-the-sports-car mania, with Taylor grinning through the tabloid caricature.",
      easterEggs: [],
      youtubeId: "e-ORhEE9VVg",
      sources: [{ name: "Taylor Swift - Blank Space", url: "https://www.youtube.com/watch?v=e-ORhEE9VVg" }, { name: "Blank Space", url: "https://en.wikipedia.org/wiki/Blank_Space" }],
    },
    {
      slug: "style-mv",
      kind: "music_video",
      title: "Style",
      director: "Joseph Kahn",
      releasedOn: "2015-02-13",
      relatedSongs: ["Style"],
      summary: "No plot, all texture: shattered mirrors, projected faces, fog and headlights — the album's moodiest song gets a video made of double exposures instead of story.",
      easterEggs: [],
      youtubeId: "-CmadmM5cOk",
      sources: [{ name: "Taylor Swift - Style", url: "https://www.youtube.com/watch?v=-CmadmM5cOk" }, { name: "Style (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Style_(Taylor_Swift_song)" }],
    },
    {
      slug: "bad-blood-mv",
      kind: "music_video",
      title: "Bad Blood",
      director: "Joseph Kahn",
      releasedOn: "2015-05-17",
      relatedSongs: ["Bad Blood"],
      summary: "The squad-era action trailer: a betrayal, a training montage, and a cast of codenamed stars (Catastrophe, Arsyn, Knockout...) marching into a fireball — premiered at the Billboard Music Awards.",
      easterEggs: ["Every cameo carries a comic-book codename in the credits — fans keep a full roster of who played whom."],
      youtubeId: "QcIy9NiNbmo",
      sources: [{ name: "Taylor Swift - Bad Blood ft. Kendrick Lamar", url: "https://www.youtube.com/watch?v=QcIy9NiNbmo" }, { name: "Bad Blood (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Bad_Blood_(Taylor_Swift_song)" }],
    },
    {
      slug: "wildest-dreams-mv",
      kind: "music_video",
      title: "Wildest Dreams",
      director: "Joseph Kahn",
      releasedOn: "2015-08-30",
      relatedSongs: ["Wildest Dreams"],
      summary: "Old-Hollywood safari melodrama: two co-stars fall for each other on a 1950s film set, and the premiere ends the romance the way the song promised it would end. Proceeds went to African Parks.",
      easterEggs: [],
      youtubeId: "IdneKLhsWOQ",
      sources: [{ name: "Taylor Swift - Wildest Dreams", url: "https://www.youtube.com/watch?v=IdneKLhsWOQ" }, { name: "Wildest Dreams", url: "https://en.wikipedia.org/wiki/Wildest_Dreams" }],
    },
    {
      slug: "the-1989-world-tour-live-film",
      kind: "tour_film",
      title: "The 1989 World Tour Live",
      director: "Jonas Åkerlund",
      releasedOn: "2015-12-20",
      relatedSongs: [],
      summary: "The Sydney stadium show captured for Apple Music — light-up wristbands, the catwalk, and the era's guest-star ritual folded into a streaming-exclusive concert film.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "The 1989 World Tour Live", url: "https://en.wikipedia.org/wiki/The_1989_World_Tour_Live" }],
    },
    {
      slug: "out-of-the-woods-mv",
      kind: "music_video",
      title: "Out of the Woods",
      director: "Joseph Kahn",
      releasedOn: "2015-12-31",
      relatedSongs: ["Out of the Woods"],
      summary: "Premiered on New Year's Eve: the woods literally chase Taylor — vines grab, snow buries, wolves close in — until she outruns the forest back to the beach and meets herself.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "Out of the Woods (song)", url: "https://en.wikipedia.org/wiki/Out_of_the_Woods_(song)" }],
    },
    {
      slug: "new-romantics-mv",
      kind: "music_video",
      title: "New Romantics",
      director: "Jonas Åkerlund",
      releasedOn: null,
      relatedSongs: ["New Romantics"],
      summary: "A thank-you cut from 1989 World Tour footage — backstage, crowd waves, confetti — released as the era's victory lap for the fans who made the bonus track a hit.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "New Romantics (song)", url: "https://en.wikipedia.org/wiki/New_Romantics_(song)" }],
    },
  ],
  "debut": [
    {
      slug: "our-song-mv",
      kind: "music_video",
      title: "Our Song",
      director: "Trey Fanjoy",
      releasedOn: null,
      relatedSongs: ["Our Song"],
      summary: "Front-porch performance piece — barefoot on the steps in a blue dress, then a flower-drenched fantasy set, for the song she wrote for her ninth-grade talent show.",
      easterEggs: [],
      youtubeId: "Jb2stN7kH28",
      sources: [{ name: "Taylor Swift - Our Song", url: "https://www.youtube.com/watch?v=Jb2stN7kH28" }, { name: "Our Song (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Our_Song_(Taylor_Swift_song)" }],
    },
    {
      slug: "picture-to-burn-mv",
      kind: "music_video",
      title: "Picture to Burn",
      director: "Trey Fanjoy",
      releasedOn: null,
      relatedSongs: ["Picture to Burn"],
      summary: "Revenge-fantasy split-screen: Taylor and her band trash an ex's house in her imagination while she sits primly in the truck outside — the first of many satirical self-aware villain turns.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "Picture to Burn", url: "https://en.wikipedia.org/wiki/Picture_to_Burn" }],
    },
    {
      slug: "teardrops-on-my-guitar-mv",
      kind: "music_video",
      title: "Teardrops on My Guitar",
      director: "Trey Fanjoy",
      releasedOn: null,
      relatedSongs: ["Teardrops on My Guitar"],
      summary: "High-school hallways and a bedroom confessional: Taylor watches Drew from the next locker over, then tells the guitar what she can't tell him.",
      easterEggs: [],
      youtubeId: "xKCek6_dB0M",
      sources: [{ name: "Taylor Swift - Teardrops On My Guitar", url: "https://www.youtube.com/watch?v=xKCek6_dB0M" }, { name: "Teardrops on My Guitar", url: "https://en.wikipedia.org/wiki/Teardrops_on_My_Guitar" }],
    },
    {
      slug: "tim-mcgraw-mv",
      kind: "music_video",
      title: "Tim McGraw",
      director: "Trey Fanjoy",
      releasedOn: null,
      relatedSongs: ["Tim McGraw"],
      summary: "The first video: a sun-flared lakeside memory reel — a 16-year-old Taylor in a white sundress, a Chevy truck, a summer already turning into a song about being remembered.",
      easterEggs: [],
      youtubeId: "GkD20ajVxnY",
      sources: [{ name: "Taylor Swift - Tim McGraw", url: "https://www.youtube.com/watch?v=GkD20ajVxnY" }, { name: "Tim McGraw (song)", url: "https://en.wikipedia.org/wiki/Tim_McGraw_(song)" }],
    },
  ],
  "evermore": [
    {
      slug: "willow-mv",
      kind: "music_video",
      title: "willow",
      director: "Taylor Swift",
      releasedOn: "2020-12-11",
      relatedSongs: ["willow"],
      summary: "Picks up in the exact frame cardigan left off: from the piano, Taylor follows a golden thread through winter woods, a carnival tent, and firelit ritual circles to find the person on the other end.",
      easterEggs: ["Opens inside the same piano the cardigan video ends in — a deliberate continuity handoff between sister albums."],
      youtubeId: "RsEZmictANA",
      sources: [{ name: "Taylor Swift - willow (Official Music Video)", url: "https://www.youtube.com/watch?v=RsEZmictANA" }, { name: "willow (song)", url: "https://en.wikipedia.org/wiki/Willow_(song)" }],
    },
    {
      slug: "all-too-well-the-short-film",
      kind: "short_film",
      title: "All Too Well: The Short Film",
      director: "Taylor Swift",
      releasedOn: "2021-11-12",
      relatedSongs: ["All Too Well (10 Minute Version)"],
      summary: "Fifteen minutes starring Sadie Sink and Dylan O'Brien: the whole arc of the fan-canonized breakup epic — the kitchen dance, the car fight, the scarf — released with Red (Taylor's Version) and premiered theatrically.",
      easterEggs: [],
      youtubeId: "tollGa3S0o8",
      sources: [{ name: "Taylor Swift - All Too Well: The Short Film", url: "https://www.youtube.com/watch?v=tollGa3S0o8" }, { name: "All Too Well: The Short Film", url: "https://en.wikipedia.org/wiki/All_Too_Well:_The_Short_Film" }],
    },
    {
      slug: "i-bet-you-think-about-me-mv",
      kind: "music_video",
      title: "I Bet You Think About Me",
      director: "Blake Lively",
      releasedOn: "2021-11-15",
      relatedSongs: ["I Bet You Think About Me"],
      summary: "Blake Lively's directorial debut: Taylor crashes a pastel society wedding as the red-dressed ghost of relationships past, gleefully ruining the cake — the vault track as screwball comedy.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "I Bet You Think About Me", url: "https://en.wikipedia.org/wiki/I_Bet_You_Think_About_Me" }],
    },
  ],
  "fearless": [
    {
      slug: "fifteen-mv",
      kind: "music_video",
      title: "Fifteen",
      director: "Roman White",
      releasedOn: null,
      relatedSongs: ["Fifteen"],
      summary: "A greenhouse-dream staging of freshman year: scenes bloom and dissolve around Taylor as she narrates Abigail's story and her own — memory rendered as a garden being planted and unplanted.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "Fifteen (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Fifteen_(Taylor_Swift_song)" }],
    },
    {
      slug: "journey-to-fearless",
      kind: "tour_film",
      title: "Journey to Fearless",
      director: null,
      releasedOn: null,
      relatedSongs: [],
      summary: "The first concert film: a three-part TV documentary following the Fearless Tour — 19-year-old headliner, screaming arenas, and the backstory told between stadium cuts.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "Journey to Fearless", url: "https://en.wikipedia.org/wiki/Journey_to_Fearless" }],
    },
    {
      slug: "love-story-mv",
      kind: "music_video",
      title: "Love Story",
      director: "Trey Fanjoy",
      releasedOn: null,
      relatedSongs: ["Love Story"],
      summary: "The period-piece blockbuster: a campus meet-cute dissolves into a full Regency-styled castle romance, ballgown and all, ending on the proposal the song rewrites into Romeo and Juliet with a happy ending.",
      easterEggs: [],
      youtubeId: "8xg3vE8Ie_E",
      sources: [{ name: "Taylor Swift - Love Story", url: "https://www.youtube.com/watch?v=8xg3vE8Ie_E" }, { name: "Love Story (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Love_Story_(Taylor_Swift_song)" }],
    },
    {
      slug: "white-horse-mv",
      kind: "music_video",
      title: "White Horse",
      director: "Trey Fanjoy",
      releasedOn: null,
      relatedSongs: ["White Horse"],
      summary: "The anti-fairytale companion to Love Story: a dim apartment, a phone that shouldn't be answered, and a breakup played in intercut apology scenes — no castle, no rescue.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "White Horse (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/White_Horse_(Taylor_Swift_song)" }],
    },
    {
      slug: "you-belong-with-me-mv",
      kind: "music_video",
      title: "You Belong with Me",
      director: "Roman White",
      releasedOn: null,
      relatedSongs: ["You Belong with Me"],
      summary: "Taylor plays both the band-tee girl next door and the brunette cheer captain across the driveway — window-sign confessions, a prom-night reveal, and the era's defining underdog fantasy.",
      easterEggs: [],
      youtubeId: "VuNIsY6JdUw",
      sources: [{ name: "Taylor Swift - You Belong With Me", url: "https://www.youtube.com/watch?v=VuNIsY6JdUw" }, { name: "You Belong with Me", url: "https://en.wikipedia.org/wiki/You_Belong_with_Me" }],
    },
  ],
  "folklore": [
    {
      slug: "cardigan-mv",
      kind: "music_video",
      title: "cardigan",
      director: "Taylor Swift",
      releasedOn: "2020-07-24",
      relatedSongs: ["cardigan"],
      summary: "Self-directed under COVID protocols and released with the surprise album: a glowing piano becomes a portal from a candlelit cabin to a mossy forest to a storm-tossed sea, and back to safety under a cardigan.",
      easterEggs: [],
      youtubeId: "K-a8s8OLBSE",
      sources: [{ name: "Taylor Swift - cardigan", url: "https://www.youtube.com/watch?v=K-a8s8OLBSE" }, { name: "cardigan (song)", url: "https://en.wikipedia.org/wiki/Cardigan_(song)" }],
    },
    {
      slug: "folklore-long-pond-studio-sessions-film",
      kind: "documentary",
      title: "folklore: the long pond studio sessions",
      director: "Taylor Swift",
      releasedOn: "2020-11-25",
      relatedSongs: [],
      summary: "The Disney+ film where folklore got its liner notes out loud: Taylor, Aaron Dessner and Jack Antonoff play the album through in a woodland studio and explain it song by song — including the William Bowery reveal.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "Folklore: The Long Pond Studio Sessions", url: "https://en.wikipedia.org/wiki/Folklore:_The_Long_Pond_Studio_Sessions" }],
    },
  ],
  "lover": [
    {
      slug: "me-mv",
      kind: "music_video",
      title: "ME!",
      director: "Dave Meyers & Taylor Swift",
      releasedOn: "2019-04-26",
      relatedSongs: ["ME!"],
      summary: "The era-flip: a French-arguing snake bursts into pastel butterflies, and the rest is a candy-colored musical-theater fever dream with Brendon Urie — released 4/26 after a fan-tracked countdown.",
      easterEggs: ["The Kelsey Montague butterfly mural in Nashville went up hours before the drop as a real-world clue.", "A neon \"Lover\" sign appears months before the album title was announced."],
      youtubeId: "FuXNumBwDOM",
      sources: [{ name: "Taylor Swift - ME! (feat. Brendon Urie of Panic! At The Disco)", url: "https://www.youtube.com/watch?v=FuXNumBwDOM" }, { name: "ME!", url: "https://en.wikipedia.org/wiki/Me!" }],
    },
    {
      slug: "you-need-to-calm-down-mv",
      kind: "music_video",
      title: "You Need to Calm Down",
      director: "Drew Kirsch & Taylor Swift",
      releasedOn: "2019-06-17",
      relatedSongs: ["You Need to Calm Down"],
      summary: "A trailer-park block party stacked with LGBTQ icons — and a mid-video Katy Perry burger-and-fries reconciliation — ending on a title card for the Equality Act petition.",
      easterEggs: ["The burger-and-fries costumes end the long-running Katy Perry feud on camera."],
      youtubeId: "Dkk9gvTmCXY",
      sources: [{ name: "Taylor Swift - You Need To Calm Down", url: "https://www.youtube.com/watch?v=Dkk9gvTmCXY" }, { name: "You Need to Calm Down", url: "https://en.wikipedia.org/wiki/You_Need_to_Calm_Down" }],
    },
    {
      slug: "lover-mv",
      kind: "music_video",
      title: "Lover",
      director: "Drew Kirsch",
      releasedOn: "2019-08-22",
      relatedSongs: ["Lover"],
      summary: "A couple lives inside a dollhouse where every room is a different color and mood — an image fans never stopped decoding, especially once the Eras Tour opened with the Lover set.",
      easterEggs: [],
      youtubeId: "-BjZmE2gtdo",
      sources: [{ name: "Taylor Swift - Lover (Official Music Video)", url: "https://www.youtube.com/watch?v=-BjZmE2gtdo" }, { name: "Lover (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Lover_(Taylor_Swift_song)" }],
    },
    {
      slug: "miss-americana",
      kind: "documentary",
      title: "Miss Americana",
      director: "Lana Wilson",
      releasedOn: "2020-01-31",
      relatedSongs: [],
      summary: "The Netflix documentary that opened the vault for real: the eating-disorder disclosure, the political-silence breaking point, and the Lover sessions — Sundance premiere, then streaming.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "Miss Americana", url: "https://en.wikipedia.org/wiki/Miss_Americana" }],
    },
    {
      slug: "the-man-mv",
      kind: "music_video",
      title: "The Man",
      director: "Taylor Swift",
      releasedOn: "2020-02-27",
      relatedSongs: ["The Man"],
      summary: "Her solo directorial debut: buried under prosthetics, Taylor plays \"Tyler\" — the swaggering executive whose every entitled move the song calls out — until the credits reveal the trick.",
      easterEggs: [],
      youtubeId: "AqAJLh9wuZ0",
      sources: [{ name: "Taylor Swift - The Man (Official Video)", url: "https://www.youtube.com/watch?v=AqAJLh9wuZ0" }, { name: "The Man (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/The_Man_(Taylor_Swift_song)" }],
    },
    {
      slug: "city-of-lover",
      kind: "performance",
      title: "Taylor Swift: City of Lover",
      director: null,
      releasedOn: "2020-05-17",
      relatedSongs: [],
      summary: "The one-night Paris concert special that became the Lover era's only live document after the pandemic canceled Lover Fest — aired on ABC, intimate theater instead of stadiums.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "Taylor Swift City of Lover Concert", url: "https://en.wikipedia.org/wiki/Taylor_Swift_City_of_Lover_Concert" }],
    },
  ],
  "midnights": [
    {
      slug: "anti-hero-mv",
      kind: "music_video",
      title: "Anti-Hero",
      director: "Taylor Swift",
      releasedOn: "2022-10-21",
      relatedSongs: ["Anti-Hero"],
      summary: "Self-directed release-day centerpiece: Taylor hosts a house party for her own worst selves — a giant \"monster on the hill\" at the dinner table, a ghost at her funeral, and heirs squabbling over her will.",
      easterEggs: ["The squabbling funeral beneficiaries are played by comedians Mike Birbiglia, John Early and Mary Elizabeth Ellis — the will scene fans quote line-for-line."],
      youtubeId: "b1kbLwvqugk",
      sources: [{ name: "Taylor Swift - Anti-Hero (Official Music Video)", url: "https://www.youtube.com/watch?v=b1kbLwvqugk" }, { name: "Anti-Hero (song)", url: "https://en.wikipedia.org/wiki/Anti-Hero_(song)" }],
    },
    {
      slug: "bejeweled-mv",
      kind: "music_video",
      title: "Bejeweled",
      director: "Taylor Swift",
      releasedOn: "2022-10-25",
      relatedSongs: ["Bejeweled"],
      summary: "A Cinderella retelling with Laura Dern as the wicked stepmother, HAIM as stepsisters and Dita Von Teese in the martini glass — and, by Taylor's own warning, packed wall-to-wall with easter eggs.",
      easterEggs: ["The elevator button for floor 3 lights up — read (correctly) as pointing at album #3, Speak Now.", "The purple gown and castle staging were decoded as Speak Now (Taylor's Version) signals months before its Nashville announcement."],
      youtubeId: "b7QlX3yR2xs",
      sources: [{ name: "Taylor Swift - Bejeweled (Official Music Video)", url: "https://www.youtube.com/watch?v=b7QlX3yR2xs" }, { name: "Bejeweled (song)", url: "https://en.wikipedia.org/wiki/Bejeweled_(song)" }],
    },
    {
      slug: "lavender-haze-mv",
      kind: "music_video",
      title: "Lavender Haze",
      director: "Taylor Swift",
      releasedOn: "2023-01-27",
      relatedSongs: ["Lavender Haze"],
      summary: "The album's dreamiest visual: a purple fog rolls through a 70s-styled apartment, koi swim across the ceiling, and Taylor drifts from bed to a lavender field without the night ever ending.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "Lavender Haze", url: "https://en.wikipedia.org/wiki/Lavender_Haze" }],
    },
    {
      slug: "taylor-swift-the-eras-tour-film",
      kind: "tour_film",
      title: "Taylor Swift: The Eras Tour",
      director: "Sam Wrench",
      releasedOn: "2023-10-13",
      relatedSongs: [],
      summary: "The SoFi Stadium shows cut into a theatrical event that broke the all-time concert-film box-office record — released straight to cinemas on a distribution deal negotiated with AMC itself.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "Taylor Swift: The Eras Tour", url: "https://en.wikipedia.org/wiki/Taylor_Swift:_The_Eras_Tour" }],
    },
    {
      slug: "karma-mv",
      kind: "music_video",
      title: "Karma (feat. Ice Spice)",
      director: "Taylor Swift",
      releasedOn: null,
      relatedSongs: ["Karma"],
      summary: "Released with the Til Dawn edition remix: cosmic Taylor rides mythological karma imagery — a giant cat, a wrecking-ball moon — with Ice Spice materializing for the new verse.",
      easterEggs: [],
      youtubeId: "XzOvgu3GPwY",
      sources: [{ name: "Taylor Swift ft. Ice Spice - Karma (Official Music Video)", url: "https://www.youtube.com/watch?v=XzOvgu3GPwY" }, { name: "Karma (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Karma_(Taylor_Swift_song)" }],
    },
  ],
  "red": [
    {
      slug: "22-mv",
      kind: "music_video",
      title: "22",
      director: "Anthony Mandler",
      releasedOn: null,
      relatedSongs: ["22"],
      summary: "Shot like a home movie of the best day off ever: real-friends hangout energy, the \"not a lot going on at the moment\" tee, a beach-party ending — breakfast at midnight canonized.",
      easterEggs: ["The hipster-glasses-and-tee look returned a decade later in the Anti-Hero video and as an Eras Tour costume — the era cross-reference fans clock instantly."],
      youtubeId: "AgFeZr5ptV8",
      sources: [{ name: "Taylor Swift - 22", url: "https://www.youtube.com/watch?v=AgFeZr5ptV8" }, { name: "22 (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/22_(Taylor_Swift_song)" }],
    },
    {
      slug: "begin-again-mv",
      kind: "music_video",
      title: "Begin Again",
      director: "Philip Andelman",
      releasedOn: null,
      relatedSongs: ["Begin Again"],
      summary: "Shot in Paris: a slow, sunlit walk out of one story and into the possibility of another — café tables, cobblestones, and the album's gentlest landing.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "Begin Again (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Begin_Again_(Taylor_Swift_song)" }],
    },
    {
      slug: "everything-has-changed-mv",
      kind: "music_video",
      title: "Everything Has Changed",
      director: "Philip Andelman",
      releasedOn: null,
      relatedSongs: ["Everything Has Changed"],
      summary: "Two grade-schoolers play out the duet's friendship-into-something-more — and the kicker reveals Taylor and Ed Sheeran as the parents picking them up.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "Everything Has Changed", url: "https://en.wikipedia.org/wiki/Everything_Has_Changed" }],
    },
    {
      slug: "i-knew-you-were-trouble-mv",
      kind: "music_video",
      title: "I Knew You Were Trouble",
      director: "Anthony Mandler",
      releasedOn: null,
      relatedSongs: ["I Knew You Were Trouble"],
      summary: "A two-minute spoken prologue, a desert festival, a doomed bad-boy romance told in flashback grit — the era's deliberate swerve from country sweetheart staging into pop cinema.",
      easterEggs: [],
      youtubeId: "vNoKguSdy4Y",
      sources: [{ name: "Taylor Swift - I Knew You Were Trouble", url: "https://www.youtube.com/watch?v=vNoKguSdy4Y" }, { name: "I Knew You Were Trouble", url: "https://en.wikipedia.org/wiki/I_Knew_You_Were_Trouble" }],
    },
    {
      slug: "we-are-never-ever-getting-back-together-mv",
      kind: "music_video",
      title: "We Are Never Ever Getting Back Together",
      director: "Declan Whitebloom",
      releasedOn: null,
      relatedSongs: ["We Are Never Ever Getting Back Together"],
      summary: "Styled as one continuous take through a storybook house party — pajamas, a phone call, and a band in animal costumes — for her first Hot 100 #1.",
      easterEggs: [],
      youtubeId: "WA4iX5D9Z64",
      sources: [{ name: "Taylor Swift - We Are Never Ever Getting Back Together", url: "https://www.youtube.com/watch?v=WA4iX5D9Z64" }, { name: "We Are Never Ever Getting Back Together", url: "https://en.wikipedia.org/wiki/We_Are_Never_Ever_Getting_Back_Together" }],
    },
  ],
  "reputation": [
    {
      slug: "look-what-you-made-me-do-mv",
      kind: "music_video",
      title: "Look What You Made Me Do",
      director: "Joseph Kahn",
      releasedOn: "2017-08-27",
      relatedSongs: ["Look What You Made Me Do"],
      summary: "The VMA-premiered resurrection: zombie Taylor claws out of a grave, a snake serves tea on a throne, and the finale lines up fifteen past Taylors to bicker over which one is fake.",
      easterEggs: ["The gravestone reads Nils Sjöberg — the pseudonym she used as a songwriter on \"This Is What You Came For.\"", "\"The old Taylor can't come to the phone right now\" is delivered by the lineup of her past era selves.", "The \"Junior Jewels\" shirt from You Belong with Me returns, now scrawled with her real friends' names."],
      youtubeId: "3tmd-ClpJxA",
      sources: [{ name: "Taylor Swift - Look What You Made Me Do", url: "https://www.youtube.com/watch?v=3tmd-ClpJxA" }, { name: "Look What You Made Me Do", url: "https://en.wikipedia.org/wiki/Look_What_You_Made_Me_Do" }],
    },
    {
      slug: "ready-for-it-mv",
      kind: "music_video",
      title: "...Ready for It?",
      director: "Joseph Kahn",
      releasedOn: "2017-10-26",
      relatedSongs: ["...Ready for It?"],
      summary: "Cyberpunk Taylor vs. Taylor: a cloaked figure walks a neon corridor to confront a caged android version of herself — the robot cracks its shell and levels the wall between them.",
      easterEggs: [],
      youtubeId: "wIft-t-MQuE",
      sources: [{ name: "Taylor Swift - ...Ready For It?", url: "https://www.youtube.com/watch?v=wIft-t-MQuE" }, { name: "...Ready for It?", url: "https://en.wikipedia.org/wiki/...Ready_for_It%3F" }],
    },
    {
      slug: "end-game-mv",
      kind: "music_video",
      title: "End Game",
      director: "Joseph Kahn",
      releasedOn: "2018-01-12",
      relatedSongs: ["End Game"],
      summary: "A globe-hopping party flex — Miami boat lights, Tokyo arcades, London double-deckers — with Ed Sheeran and Future riding shotgun through the era's one pure hangout video.",
      easterEggs: [],
      youtubeId: "dfnCAmr569k",
      sources: [{ name: "Taylor Swift - End Game ft. Ed Sheeran, Future", url: "https://www.youtube.com/watch?v=dfnCAmr569k" }, { name: "End Game (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/End_Game_(Taylor_Swift_song)" }],
    },
    {
      slug: "delicate-mv",
      kind: "music_video",
      title: "Delicate",
      director: "Joseph Kahn",
      releasedOn: "2018-03-11",
      relatedSongs: ["Delicate"],
      summary: "Premiered at the iHeartRadio Awards: a note makes Taylor invisible mid-press-gauntlet, and she dances unwatched through a hotel — lobby, hallway, rain — until the note's magic runs out at a dive bar.",
      easterEggs: [],
      youtubeId: "tCXGJQYZ9JA",
      sources: [{ name: "Taylor Swift - Delicate", url: "https://www.youtube.com/watch?v=tCXGJQYZ9JA" }, { name: "Delicate (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Delicate_(Taylor_Swift_song)" }],
    },
    {
      slug: "reputation-stadium-tour-film",
      kind: "tour_film",
      title: "Taylor Swift: reputation Stadium Tour",
      director: "Paul Dugdale",
      releasedOn: "2018-12-31",
      relatedSongs: [],
      summary: "The Dallas stadium show, released to Netflix on New Year's Eve — the snake-throne era preserved in full, from the tilted stage to the Long Live/New Year's Day piano coda.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "Taylor Swift: Reputation Stadium Tour", url: "https://en.wikipedia.org/wiki/Taylor_Swift:_Reputation_Stadium_Tour" }],
    },
  ],
  "speak-now": [
    {
      slug: "speak-now-world-tour-live",
      kind: "tour_film",
      title: "Speak Now World Tour – Live",
      director: null,
      releasedOn: "2011-11-21",
      relatedSongs: [],
      summary: "The theatrical Speak Now show — aerial ballet, the levitating balcony, the sparkler-burst Long Live finale — captured across the 2011 arena run and released as a live CD/DVD.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "Speak Now World Tour", url: "https://en.wikipedia.org/wiki/Speak_Now_World_Tour" }],
    },
    {
      slug: "back-to-december-mv",
      kind: "music_video",
      title: "Back to December",
      director: "Yoann Lemoine",
      releasedOn: null,
      relatedSongs: ["Back to December"],
      summary: "Snow falls indoors: Taylor writes an apology from a room slowly buried in winter while the boy she wronged moves through parallel scenes — her first video built on a single sustained visual metaphor.",
      easterEggs: [],
      youtubeId: "QUwxKWT6m7U",
      sources: [{ name: "Taylor Swift - Back To December", url: "https://www.youtube.com/watch?v=QUwxKWT6m7U" }, { name: "Back to December", url: "https://en.wikipedia.org/wiki/Back_to_December" }],
    },
    {
      slug: "mean-mv",
      kind: "music_video",
      title: "Mean",
      director: "Declan Whitebloom",
      releasedOn: null,
      relatedSongs: ["Mean"],
      summary: "Banjo-vaudeville staging with a moral: the mocked kids of the verses grow up and out — into the big city, the stadium, the life the bully said they'd never have — while the band plays a saloon set.",
      easterEggs: [],
      youtubeId: "jYa1eI1hpDE",
      sources: [{ name: "Taylor Swift - Mean", url: "https://www.youtube.com/watch?v=jYa1eI1hpDE" }, { name: "Mean (song)", url: "https://en.wikipedia.org/wiki/Mean_(song)" }],
    },
    {
      slug: "mine-mv",
      kind: "music_video",
      title: "Mine",
      director: "Roman White",
      releasedOn: null,
      relatedSongs: ["Mine"],
      summary: "A whole imagined lifetime in four minutes: from café glance to kids and a kitchen argument and back — the flash-forward fantasy structure the song's \"careless man's careful daughter\" narrates.",
      easterEggs: [],
      youtubeId: "XPBwXKgDTdE",
      sources: [{ name: "Taylor Swift - Mine", url: "https://www.youtube.com/watch?v=XPBwXKgDTdE" }, { name: "Mine (Taylor Swift song)", url: "https://en.wikipedia.org/wiki/Mine_(Taylor_Swift_song)" }],
    },
    {
      slug: "the-story-of-us-mv",
      kind: "music_video",
      title: "The Story of Us",
      director: "Noble Jones",
      releasedOn: null,
      relatedSongs: ["The Story of Us"],
      summary: "A library at war: two exes study tables apart as the silence gets louder, pages fly, and the \"chapter\" conceit of the lyric plays out in the stacks.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "The Story of Us (song)", url: "https://en.wikipedia.org/wiki/The_Story_of_Us_(song)" }],
    },
  ],
  "tloas": [
    {
      slug: "the-official-release-party-of-a-showgirl",
      kind: "performance",
      title: "The Official Release Party of a Showgirl",
      director: null,
      releasedOn: "2025-10-03",
      relatedSongs: [],
      summary: "Release weekend as a cinema event: the Ophelia video premiere, lyric videos, and behind-the-scenes cuts packaged into a theatrical party that topped the box office on album weekend.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "The Official Release Party of a Showgirl", url: "https://en.wikipedia.org/wiki/The_Official_Release_Party_of_a_Showgirl" }],
    },
    {
      slug: "the-fate-of-ophelia-mv",
      kind: "music_video",
      title: "The Fate of Ophelia",
      director: "Taylor Swift",
      releasedOn: null,
      relatedSongs: ["The Fate of Ophelia"],
      summary: "The lead single's video premiered as the centerpiece of the release-party theatrical event: showgirl staging that pulls Ophelia out of the water and onto the stage, inverting the Hamlet ending.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "The Fate of Ophelia", url: "https://en.wikipedia.org/wiki/The_Fate_of_Ophelia" }],
    },
  ],
  "ttpd": [
    {
      slug: "fortnight-mv",
      kind: "music_video",
      title: "Fortnight (feat. Post Malone)",
      director: "Taylor Swift",
      releasedOn: "2024-04-19",
      relatedSongs: ["Fortnight"],
      summary: "Black-and-white asylum-for-poets imagery: Taylor is committed to a \"forgotten words\" institution, typewriters spark, and Post Malone shares the desk — with Dead Poets Society's Ethan Hawke and Josh Charles as the doctors.",
      easterEggs: ["Ethan Hawke and Josh Charles — two of the original Dead Poets Society cast — cameo as the doctors, a casting-level pun on the album title."],
      youtubeId: "q3zqJs7JUCQ",
      sources: [{ name: "Taylor Swift - Fortnight (feat. Post Malone) (Official Music Video)", url: "https://www.youtube.com/watch?v=q3zqJs7JUCQ" }, { name: "Fortnight (song)", url: "https://en.wikipedia.org/wiki/Fortnight_(song)" }],
    },
    {
      slug: "i-can-do-it-with-a-broken-heart-mv",
      kind: "music_video",
      title: "I Can Do It with a Broken Heart",
      director: "Taylor Swift",
      releasedOn: null,
      relatedSongs: ["I Can Do It with a Broken Heart"],
      summary: "Built from real Eras Tour rehearsal and backstage footage: the show-must-go-on song scored by the machinery of the actual show — lifts, quick changes, and the smile snapping on at places, everyone.",
      easterEggs: [],
      youtubeId: null,
      sources: [{ name: "I Can Do It with a Broken Heart", url: "https://en.wikipedia.org/wiki/I_Can_Do_It_with_a_Broken_Heart" }],
    },
  ],
};
