// Mood scores — 1989 era (1989 2014 / Taylor's Version 2023, incl. From The
// Vault). Stage 2 of the Mood Chat feature
// (docs/proposals/2026-07-19-mood-chat.md). Scored ONLY from each track's
// existing researched note/summary/inspiration/themes in
// supabase/seed/tracks/1989.mjs — no invented facts, no lyrics. `oneLiner` and
// `useCase` are ORIGINAL prose. The eight axes are each 0..1; energy is
// 0 (still) .. 1 (driving); valence is 0 (sad) .. 1 (happy).

export default {
  eraSlug: '1989',
  songs: [
    {
      slug: 'welcome-to-new-york',
      moods: {
        heartbreak: 0.02,
        anger: 0.0,
        nostalgia: 0.1,
        joy: 0.85,
        calm: 0.2,
        defiance: 0.4,
        longing: 0.4,
        catharsis: 0.6,
      },
      energy: 0.8,
      valence: 0.9,
      useCase: ['moving somewhere new', 'a clean-slate fresh start', 'the city as rebirth'],
      oneLiner: 'Arrival as rebirth — a new city where nobody knows the old story and everyone came to reinvent themselves.',
    },
    {
      slug: 'blank-space',
      moods: {
        heartbreak: 0.05,
        anger: 0.3,
        nostalgia: 0.05,
        joy: 0.65,
        calm: 0.1,
        defiance: 0.8,
        longing: 0.1,
        catharsis: 0.5,
      },
      energy: 0.8,
      valence: 0.65,
      useCase: ['leaning into a reputation', 'playing the villain they wrote', 'a wink at your own bad press'],
      oneLiner: 'Playing the maneater the tabloids invented — and writing the character better than they ever could.',
    },
    {
      slug: 'style',
      moods: {
        heartbreak: 0.3,
        anger: 0.05,
        nostalgia: 0.3,
        joy: 0.4,
        calm: 0.25,
        defiance: 0.2,
        longing: 0.8,
        catharsis: 0.5,
      },
      energy: 0.7,
      valence: 0.5,
      useCase: ['a cant-quit attraction', 'crashing back to the same person', 'a midnight drive with someone'],
      oneLiner: 'Two people who keep crashing back together — chemistry that never goes out of fashion, dread humming underneath.',
    },
    {
      slug: 'out-of-the-woods',
      moods: {
        heartbreak: 0.35,
        anger: 0.05,
        nostalgia: 0.3,
        joy: 0.2,
        calm: 0.05,
        defiance: 0.15,
        longing: 0.55,
        catharsis: 0.75,
      },
      energy: 0.8,
      valence: 0.35,
      useCase: ['love that feels one crisis from over', 'anxious cliffhanger romance', 'asking are we in the clear yet'],
      oneLiner: 'A fragile love lived one disaster at a time — panic rendered as a chorus you cannot stop repeating.',
    },
    {
      slug: 'all-you-had-to-do-was-stay',
      moods: {
        heartbreak: 0.4,
        anger: 0.45,
        nostalgia: 0.15,
        joy: 0.2,
        calm: 0.05,
        defiance: 0.6,
        longing: 0.3,
        catharsis: 0.7,
      },
      energy: 0.75,
      valence: 0.4,
      useCase: ['an ex crawling back too late', 'he had one job', 'closing a door with self-respect'],
      oneLiner: 'An ex comes crawling back and the answer is the title — he had exactly one job.',
    },
    {
      slug: 'shake-it-off',
      moods: {
        heartbreak: 0.02,
        anger: 0.05,
        nostalgia: 0.02,
        joy: 0.9,
        calm: 0.1,
        defiance: 0.75,
        longing: 0.02,
        catharsis: 0.6,
      },
      energy: 0.9,
      valence: 0.92,
      useCase: ['shrugging off the haters', 'dancing through criticism', 'refusing to let it land'],
      oneLiner: 'The haters keep hating and she keeps dancing — laughing at the noise instead of arguing with it.',
    },
    {
      slug: 'i-wish-you-would',
      moods: {
        heartbreak: 0.4,
        anger: 0.1,
        nostalgia: 0.35,
        joy: 0.15,
        calm: 0.15,
        defiance: 0.25,
        longing: 0.85,
        catharsis: 0.55,
      },
      energy: 0.75,
      valence: 0.35,
      useCase: ['wishing theyd make the first move', 'driving past an ex’s street', 'late-night stubborn regret'],
      oneLiner: 'Two stubborn exes driving past each other’s lives, each wishing the other would make the move neither will.',
    },
    {
      slug: 'bad-blood',
      moods: {
        heartbreak: 0.4,
        anger: 0.8,
        nostalgia: 0.1,
        joy: 0.2,
        calm: 0.05,
        defiance: 0.75,
        longing: 0.1,
        catharsis: 0.7,
      },
      energy: 0.85,
      valence: 0.4,
      useCase: ['a friend who betrayed you', 'holding a stadium-sized grudge', 'a backstab, not a breakup'],
      oneLiner: 'A friendship betrayed at the professional level — not a breakup, a backstab, with a chorus built for grudges.',
    },
    {
      slug: 'wildest-dreams',
      moods: {
        heartbreak: 0.45,
        anger: 0.02,
        nostalgia: 0.5,
        joy: 0.3,
        calm: 0.35,
        defiance: 0.1,
        longing: 0.85,
        catharsis: 0.5,
      },
      energy: 0.55,
      valence: 0.4,
      useCase: ['a romance you know is doomed', 'wanting to be remembered beautifully', 'pre-writing the nostalgia'],
      oneLiner: 'Scripting the memory before the romance even ends — if it has to be doomed, let it be remembered cinematic.',
    },
    {
      slug: 'how-you-get-the-girl',
      moods: {
        heartbreak: 0.1,
        anger: 0.05,
        nostalgia: 0.1,
        joy: 0.65,
        calm: 0.25,
        defiance: 0.2,
        longing: 0.5,
        catharsis: 0.4,
      },
      energy: 0.65,
      valence: 0.75,
      useCase: ['winning someone back', 'the exact right thing to say', 'showing up in the rain'],
      oneLiner: 'A step-by-step how-to for the boy who left — sunny on top, pointed underneath.',
    },
    {
      slug: 'this-love',
      moods: {
        heartbreak: 0.2,
        anger: 0.02,
        nostalgia: 0.35,
        joy: 0.45,
        calm: 0.75,
        defiance: 0.05,
        longing: 0.6,
        catharsis: 0.55,
      },
      energy: 0.3,
      valence: 0.6,
      useCase: ['a love that quietly comes back', 'stillness after the storm', 'patient tidal devotion'],
      oneLiner: 'Love as tide — something released that actually comes back, the quietest song on a maximalist record.',
    },
    {
      slug: 'i-know-places',
      moods: {
        heartbreak: 0.15,
        anger: 0.2,
        nostalgia: 0.05,
        joy: 0.3,
        calm: 0.1,
        defiance: 0.6,
        longing: 0.45,
        catharsis: 0.5,
      },
      energy: 0.75,
      valence: 0.45,
      useCase: ['protecting a love from prying eyes', 'us against the watchers', 'a romance planned like a heist'],
      oneLiner: 'Two lovers planning a romance like a heist — the watchers are hunters, and privacy is the getaway route.',
    },
    {
      slug: 'clean',
      moods: {
        heartbreak: 0.4,
        anger: 0.02,
        nostalgia: 0.4,
        joy: 0.35,
        calm: 0.7,
        defiance: 0.15,
        longing: 0.4,
        catharsis: 0.85,
      },
      energy: 0.3,
      valence: 0.5,
      useCase: ['finally over someone', 'the day the wound stops needing checking', 'healing as detox'],
      oneLiner: 'Healing framed as detox — the drought, the flood, and the morning you notice the wound finally closed.',
    },
    {
      slug: 'wonderland',
      moods: {
        heartbreak: 0.3,
        anger: 0.05,
        nostalgia: 0.1,
        joy: 0.45,
        calm: 0.1,
        defiance: 0.3,
        longing: 0.6,
        catharsis: 0.55,
      },
      energy: 0.8,
      valence: 0.45,
      useCase: ['falling fast and losing the plot', 'a dazzling disorienting romance', 'madness you both chose'],
      oneLiner: 'Falling fast into a dazzling, disorienting romance and losing the plot together — madness as the destination.',
    },
    {
      slug: 'you-are-in-love',
      moods: {
        heartbreak: 0.05,
        anger: 0.0,
        nostalgia: 0.3,
        joy: 0.6,
        calm: 0.75,
        defiance: 0.02,
        longing: 0.7,
        catharsis: 0.5,
      },
      energy: 0.3,
      valence: 0.8,
      useCase: ['the small unglamorous proofs of love', 'yearning for an ordinary intimacy', 'watching real love up close'],
      oneLiner: 'Real love assembled from small proofs — burnt toast, a word mid-dance — narrated from just outside it.',
    },
    {
      slug: 'new-romantics',
      moods: {
        heartbreak: 0.25,
        anger: 0.1,
        nostalgia: 0.1,
        joy: 0.75,
        calm: 0.1,
        defiance: 0.6,
        longing: 0.2,
        catharsis: 0.7,
      },
      energy: 0.85,
      valence: 0.75,
      useCase: ['treating heartbreak as raw material', 'bored broke and building anyway', 'collective bright defiance'],
      oneLiner: 'An anthem for turning heartbreak into raw material — bored, broke, and building castles from the bricks thrown at you.',
    },
    {
      slug: 'slut',
      moods: {
        heartbreak: 0.2,
        anger: 0.15,
        nostalgia: 0.2,
        joy: 0.5,
        calm: 0.55,
        defiance: 0.6,
        longing: 0.5,
        catharsis: 0.5,
      },
      energy: 0.45,
      valence: 0.6,
      useCase: ['choosing love despite the gossip', 'letting the name-calling be the tax', 'a dreamy shrug at the headlines'],
      oneLiner: 'If the tabloids will call her that anyway, this love is worth the headline — anger swapped for a dreamy shrug.',
    },
    {
      slug: 'say-dont-go',
      moods: {
        heartbreak: 0.6,
        anger: 0.15,
        nostalgia: 0.15,
        joy: 0.1,
        calm: 0.15,
        defiance: 0.2,
        longing: 0.8,
        catharsis: 0.7,
      },
      energy: 0.6,
      valence: 0.25,
      useCase: ['waiting for someone to fight for you', 'loving someone who lets you twist', 'the silence that answers for them'],
      oneLiner: 'Loving someone who lets you twist — waiting for him to fight for it while the silence gives its own answer.',
    },
    {
      slug: 'now-that-we-dont-talk',
      moods: {
        heartbreak: 0.3,
        anger: 0.2,
        nostalgia: 0.2,
        joy: 0.5,
        calm: 0.15,
        defiance: 0.65,
        longing: 0.25,
        catharsis: 0.65,
      },
      energy: 0.75,
      valence: 0.6,
      useCase: ['no longer faking his taste', 'reclaiming yourself after a breakup', 'a petty precise post-mortem'],
      oneLiner: 'Once the silence sets in, the wins count themselves — no more faking a taste for his music, his friends, his idea of you.',
    },
    {
      slug: 'suburban-legends',
      moods: {
        heartbreak: 0.4,
        anger: 0.1,
        nostalgia: 0.4,
        joy: 0.45,
        calm: 0.15,
        defiance: 0.2,
        longing: 0.7,
        catharsis: 0.55,
      },
      energy: 0.7,
      valence: 0.45,
      useCase: ['a love you turned into legend', 'destiny meeting ordinary letdown', 'forgiving someone too fast'],
      oneLiner: 'Casting the two of you as hometown legend, then watching him wreck the legend right on schedule.',
    },
    {
      slug: 'is-it-over-now',
      moods: {
        heartbreak: 0.45,
        anger: 0.55,
        nostalgia: 0.25,
        joy: 0.15,
        calm: 0.05,
        defiance: 0.6,
        longing: 0.45,
        catharsis: 0.7,
      },
      energy: 0.8,
      valence: 0.35,
      useCase: ['a breakup with no clean ending', 'who ended it and when', 'seeing an ex move on too fast'],
      oneLiner: 'The question you ask when a breakup never got a clean end — who ended what, and why is he already photographed with someone new.',
    },
  ],
};
