// Mood scores — debut era (Taylor Swift, 2006). Stage 2 of the Mood Chat
// feature (docs/proposals/2026-07-19-mood-chat.md). Scored ONLY from each
// track's existing researched note/summary/themes in
// supabase/seed/tracks/debut.mjs — no invented facts, no lyrics. `oneLiner` and
// `useCase` are ORIGINAL prose. The eight axes are each 0..1; energy is
// 0 (still) .. 1 (driving); valence is 0 (sad) .. 1 (happy).

export default {
  eraSlug: 'debut',
  songs: [
    {
      slug: 'tim-mcgraw',
      moods: {
        heartbreak: 0.4,
        anger: 0.02,
        nostalgia: 0.9,
        joy: 0.35,
        calm: 0.6,
        defiance: 0.05,
        longing: 0.7,
        catharsis: 0.4,
      },
      energy: 0.35,
      valence: 0.5,
      useCase: ['missing a summer that ended', 'a first-love goodbye', 'back roads at dusk'],
      oneLiner: 'A debut goodbye that just wants to be remembered when the right song comes on.',
    },
    {
      slug: 'picture-to-burn',
      moods: {
        heartbreak: 0.3,
        anger: 0.85,
        nostalgia: 0.1,
        joy: 0.4,
        calm: 0.05,
        defiance: 0.8,
        longing: 0.05,
        catharsis: 0.6,
      },
      energy: 0.8,
      valence: 0.45,
      useCase: ['a petty breakup singalong', 'burning an ex from memory', 'feeling done and loving it'],
      oneLiner: 'A banjo kiss-off that turns a bad boyfriend into a bonfire and laughs about it.',
    },
    {
      slug: 'teardrops-on-my-guitar',
      moods: {
        heartbreak: 0.75,
        anger: 0.05,
        nostalgia: 0.4,
        joy: 0.1,
        calm: 0.4,
        defiance: 0.05,
        longing: 0.85,
        catharsis: 0.4,
      },
      energy: 0.4,
      valence: 0.2,
      useCase: ['loving someone who wants someone else', 'smiling through a crush', 'quiet heartache'],
      oneLiner: 'Being the shoulder a boy cries on about another girl, and hiding what it costs.',
    },
    {
      slug: 'a-place-in-this-world',
      moods: {
        heartbreak: 0.05,
        anger: 0.02,
        nostalgia: 0.2,
        joy: 0.4,
        calm: 0.35,
        defiance: 0.4,
        longing: 0.6,
        catharsis: 0.4,
      },
      energy: 0.5,
      valence: 0.55,
      useCase: ['starting over somewhere new', 'not knowing your path yet', 'believing there is a place for you'],
      oneLiner: 'A thirteen-year-old narrating her own uncertainty, sure only that a path exists.',
    },
    {
      slug: 'cold-as-you',
      moods: {
        heartbreak: 0.7,
        anger: 0.4,
        nostalgia: 0.15,
        joy: 0.02,
        calm: 0.35,
        defiance: 0.3,
        longing: 0.4,
        catharsis: 0.5,
      },
      energy: 0.35,
      valence: 0.15,
      useCase: ['done with someone who gives nothing back', 'quiet anger', 'a surgical breakup ballad'],
      oneLiner: 'A slow, precise takedown of a boy who never gave anything back.',
    },
    {
      slug: 'the-outside',
      moods: {
        heartbreak: 0.3,
        anger: 0.05,
        nostalgia: 0.35,
        joy: 0.05,
        calm: 0.35,
        defiance: 0.35,
        longing: 0.6,
        catharsis: 0.55,
      },
      energy: 0.4,
      valence: 0.25,
      useCase: ['feeling shut out of the group', 'writing through loneliness', 'when nobody saved you a seat'],
      oneLiner: 'A kid on the outside of every friend group turning exclusion into a song.',
    },
    {
      slug: 'tied-together-with-a-smile',
      moods: {
        heartbreak: 0.4,
        anger: 0.02,
        nostalgia: 0.2,
        joy: 0.05,
        calm: 0.45,
        defiance: 0.05,
        longing: 0.4,
        catharsis: 0.6,
      },
      energy: 0.35,
      valence: 0.25,
      useCase: ['worrying about a friend', 'loving someone falling apart', 'the girl who seems fine but isnt'],
      oneLiner: 'A tender letter to a beautiful friend who is quietly coming undone.',
    },
    {
      slug: 'stay-beautiful',
      moods: {
        heartbreak: 0.05,
        anger: 0.02,
        nostalgia: 0.25,
        joy: 0.6,
        calm: 0.55,
        defiance: 0.05,
        longing: 0.6,
        catharsis: 0.3,
      },
      energy: 0.45,
      valence: 0.7,
      useCase: ['a crush you admire from afar', 'wishing someone well', 'soft hopeful daydreams'],
      oneLiner: 'Admiring a boy from a distance and wishing him well, ending or not.',
    },
    {
      slug: 'shouldve-said-no',
      moods: {
        heartbreak: 0.55,
        anger: 0.75,
        nostalgia: 0.1,
        joy: 0.05,
        calm: 0.1,
        defiance: 0.75,
        longing: 0.1,
        catharsis: 0.8,
      },
      energy: 0.75,
      valence: 0.3,
      useCase: ['when someone cheated and chose it', 'a stadium-sized kiss-off', 'blame where it belongs'],
      oneLiner: 'A betrayal answered with a stadium chorus that puts the blame exactly where it belongs.',
    },
    {
      slug: 'marys-song-oh-my-my-my',
      moods: {
        heartbreak: 0.02,
        anger: 0.0,
        nostalgia: 0.85,
        joy: 0.7,
        calm: 0.6,
        defiance: 0.05,
        longing: 0.3,
        catharsis: 0.4,
      },
      energy: 0.45,
      valence: 0.85,
      useCase: ['believing in forever love', 'a wedding slow dance', 'growing old with someone'],
      oneLiner: 'A whole lifetime of love, from backyard dares to a porch swing at eighty-seven.',
    },
    {
      slug: 'our-song',
      moods: {
        heartbreak: 0.0,
        anger: 0.0,
        nostalgia: 0.5,
        joy: 0.85,
        calm: 0.4,
        defiance: 0.05,
        longing: 0.2,
        catharsis: 0.45,
      },
      energy: 0.7,
      valence: 0.9,
      useCase: ['giddy new-relationship joy', 'young love with no soundtrack', 'a windows-down singalong'],
      oneLiner: 'A couple with no song deciding the everyday details already are one.',
    },
    {
      slug: 'im-only-me-when-im-with-you',
      moods: {
        heartbreak: 0.0,
        anger: 0.0,
        nostalgia: 0.45,
        joy: 0.8,
        calm: 0.4,
        defiance: 0.15,
        longing: 0.15,
        catharsis: 0.45,
      },
      energy: 0.7,
      valence: 0.88,
      useCase: ['the people you never perform for', 'best-friend belonging', 'feeling fully yourself'],
      oneLiner: 'A stomping tribute to the people around whom you never have to perform.',
    },
    {
      slug: 'invisible',
      moods: {
        heartbreak: 0.55,
        anger: 0.05,
        nostalgia: 0.25,
        joy: 0.05,
        calm: 0.45,
        defiance: 0.05,
        longing: 0.85,
        catharsis: 0.35,
      },
      energy: 0.35,
      valence: 0.25,
      useCase: ['being overlooked by someone', 'wallflower longing', 'waiting to be noticed'],
      oneLiner: 'Watching a boy chase someone else while you wait, unseen and seeing everything.',
    },
    {
      slug: 'a-perfectly-good-heart',
      moods: {
        heartbreak: 0.85,
        anger: 0.15,
        nostalgia: 0.2,
        joy: 0.02,
        calm: 0.3,
        defiance: 0.1,
        longing: 0.5,
        catharsis: 0.55,
      },
      energy: 0.45,
      valence: 0.15,
      useCase: ['first heartbreak bewilderment', 'asking why someone hurt you', 'no revenge, just confusion'],
      oneLiner: 'First heartbreak as pure bewilderment: why break a heart that was working fine?',
    },
  ],
};
