// Mood scores — Fearless era (Fearless 2008 / Platinum 2009 / Taylor's Version
// 2021). Stage 2 of Mood Chat (docs/proposals/2026-07-19-mood-chat.md). Scored
// ONLY from each track's existing researched note/summary/themes in
// supabase/seed/tracks/fearless.mjs — no invented facts, no lyrics. `oneLiner`
// and `useCase` are ORIGINAL prose. Axes 0..1; energy 0 (still)..1 (driving);
// valence 0 (sad)..1 (happy).

export default {
  eraSlug: 'fearless',
  songs: [
    {
      slug: 'fearless',
      moods: {
        heartbreak: 0.0,
        anger: 0.0,
        nostalgia: 0.3,
        joy: 0.85,
        calm: 0.35,
        defiance: 0.4,
        longing: 0.5,
        catharsis: 0.55,
      },
      energy: 0.65,
      valence: 0.9,
      useCase: ['taking a leap on someone new', 'dancing in the rain anyway', 'optimistic butterflies'],
      oneLiner: 'Fearless not as being unafraid but driving into the storm anyway.',
    },
    {
      slug: 'fifteen',
      moods: {
        heartbreak: 0.4,
        anger: 0.05,
        nostalgia: 0.85,
        joy: 0.35,
        calm: 0.5,
        defiance: 0.15,
        longing: 0.5,
        catharsis: 0.65,
      },
      energy: 0.45,
      valence: 0.5,
      useCase: ['looking back on being young', 'advice to a younger self', 'freshman-year nostalgia'],
      oneLiner: 'Freshman year in hindsight, when who you become matters more than the boy.',
    },
    {
      slug: 'love-story',
      moods: {
        heartbreak: 0.1,
        anger: 0.02,
        nostalgia: 0.4,
        joy: 0.85,
        calm: 0.3,
        defiance: 0.6,
        longing: 0.7,
        catharsis: 0.7,
      },
      energy: 0.7,
      valence: 0.9,
      useCase: ['a giddy fairy-tale romance', 'wanting a happy ending', 'forbidden-love butterflies'],
      oneLiner: 'Romeo and Juliet with Shakespeare overruled and the happy ending written in.',
    },
    {
      slug: 'hey-stephen',
      moods: {
        heartbreak: 0.0,
        anger: 0.0,
        nostalgia: 0.25,
        joy: 0.8,
        calm: 0.4,
        defiance: 0.1,
        longing: 0.55,
        catharsis: 0.35,
      },
      energy: 0.55,
      valence: 0.88,
      useCase: ['a flirty crush', 'making your case to someone', 'playful infatuation'],
      oneLiner: 'A serenade that lists every other girl, then makes its own case with a wink.',
    },
    {
      slug: 'white-horse',
      moods: {
        heartbreak: 0.8,
        anger: 0.2,
        nostalgia: 0.35,
        joy: 0.02,
        calm: 0.4,
        defiance: 0.5,
        longing: 0.4,
        catharsis: 0.7,
      },
      energy: 0.35,
      valence: 0.2,
      useCase: ['realizing it was never a fairy tale', 'leaving a boy who wont change', 'rescuing yourself'],
      oneLiner: 'The moment after the apology when you realize there was never going to be a rescue.',
    },
    {
      slug: 'you-belong-with-me',
      moods: {
        heartbreak: 0.35,
        anger: 0.05,
        nostalgia: 0.3,
        joy: 0.55,
        calm: 0.3,
        defiance: 0.35,
        longing: 0.85,
        catharsis: 0.5,
      },
      energy: 0.65,
      valence: 0.6,
      useCase: ['pining for someone taken', 'underdog crush', 'wishing they saw you'],
      oneLiner: 'The girl next door making her closing argument to a boy who never looks over.',
    },
    {
      slug: 'breathe',
      moods: {
        heartbreak: 0.65,
        anger: 0.02,
        nostalgia: 0.4,
        joy: 0.05,
        calm: 0.55,
        defiance: 0.02,
        longing: 0.55,
        catharsis: 0.6,
      },
      energy: 0.35,
      valence: 0.25,
      useCase: ['losing a friend with no villain', 'a goodbye nobody wanted', 'the guilt of leaving'],
      oneLiner: 'A breakup with no one to blame: losing a friend and grieving the guilt of it.',
    },
    {
      slug: 'tell-me-why',
      moods: {
        heartbreak: 0.4,
        anger: 0.6,
        nostalgia: 0.1,
        joy: 0.1,
        calm: 0.2,
        defiance: 0.6,
        longing: 0.3,
        catharsis: 0.55,
      },
      energy: 0.6,
      valence: 0.35,
      useCase: ['done with someone hot and cold', 'mixed-signal frustration', 'demanding better'],
      oneLiner: 'A vented rant set to a stomp, done guessing which version of him shows up.',
    },
    {
      slug: 'youre-not-sorry',
      moods: {
        heartbreak: 0.7,
        anger: 0.45,
        nostalgia: 0.15,
        joy: 0.02,
        calm: 0.3,
        defiance: 0.6,
        longing: 0.3,
        catharsis: 0.7,
      },
      energy: 0.45,
      valence: 0.2,
      useCase: ['refusing a fake apology', 'finally hanging up', 'done being lied to'],
      oneLiner: 'The sound of someone finally hanging up on an apology that was never real.',
    },
    {
      slug: 'the-way-i-loved-you',
      moods: {
        heartbreak: 0.5,
        anger: 0.15,
        nostalgia: 0.75,
        joy: 0.2,
        calm: 0.25,
        defiance: 0.35,
        longing: 0.85,
        catharsis: 0.55,
      },
      energy: 0.55,
      valence: 0.35,
      useCase: ['missing a chaotic ex', 'safe love that feels like nothing', 'craving intensity'],
      oneLiner: 'A perfect-on-paper boyfriend losing to the memory of a screaming-in-the-rain love.',
    },
    {
      slug: 'forever-and-always',
      moods: {
        heartbreak: 0.75,
        anger: 0.6,
        nostalgia: 0.25,
        joy: 0.05,
        calm: 0.1,
        defiance: 0.4,
        longing: 0.5,
        catharsis: 0.65,
      },
      energy: 0.6,
      valence: 0.2,
      useCase: ['a promise revoked out of nowhere', 'breakup whiplash', 'wanting an explanation'],
      oneLiner: 'A forever promise revoked in real time, and the demand to know where he went.',
    },
    {
      slug: 'the-best-day',
      moods: {
        heartbreak: 0.05,
        anger: 0.0,
        nostalgia: 0.95,
        joy: 0.7,
        calm: 0.7,
        defiance: 0.05,
        longing: 0.35,
        catharsis: 0.6,
      },
      energy: 0.35,
      valence: 0.85,
      useCase: ['missing your mom', 'childhood-memory comfort', 'gratitude for family'],
      oneLiner: 'A secret thank-you to the mother who drove her away from every mean day.',
    },
    {
      slug: 'change',
      moods: {
        heartbreak: 0.0,
        anger: 0.15,
        nostalgia: 0.15,
        joy: 0.6,
        calm: 0.2,
        defiance: 0.85,
        longing: 0.35,
        catharsis: 0.8,
      },
      energy: 0.8,
      valence: 0.75,
      useCase: ['believing the underdog wins', 'a perseverance anthem', 'walls coming down'],
      oneLiner: 'A fight song for the scrappy underdog who believes the walls will come down.',
    },
    {
      slug: 'jump-then-fall',
      moods: {
        heartbreak: 0.0,
        anger: 0.0,
        nostalgia: 0.1,
        joy: 0.9,
        calm: 0.35,
        defiance: 0.1,
        longing: 0.45,
        catharsis: 0.4,
      },
      energy: 0.6,
      valence: 0.92,
      useCase: ['falling fast and happily', 'all butterflies, no warnings', 'new-crush giddiness'],
      oneLiner: 'The sunniest kind of falling: all butterflies, no warnings.',
    },
    {
      slug: 'untouchable',
      moods: {
        heartbreak: 0.2,
        anger: 0.0,
        nostalgia: 0.3,
        joy: 0.3,
        calm: 0.6,
        defiance: 0.05,
        longing: 0.9,
        catharsis: 0.45,
      },
      energy: 0.4,
      valence: 0.5,
      useCase: ['yearning for someone out of reach', 'a starlit daydream', 'distance as romance'],
      oneLiner: 'Longing for someone just out of reach, rendered as a starlit trance.',
    },
    {
      slug: 'come-in-with-the-rain',
      moods: {
        heartbreak: 0.5,
        anger: 0.02,
        nostalgia: 0.35,
        joy: 0.1,
        calm: 0.6,
        defiance: 0.1,
        longing: 0.7,
        catharsis: 0.4,
      },
      energy: 0.35,
      valence: 0.3,
      useCase: ['done chasing but still hoping', 'leaving a door unlocked', 'quiet letting go'],
      oneLiner: 'Done chasing someone but not done hoping, with a door left quietly unlocked.',
    },
    {
      slug: 'superstar',
      moods: {
        heartbreak: 0.1,
        anger: 0.0,
        nostalgia: 0.3,
        joy: 0.45,
        calm: 0.45,
        defiance: 0.05,
        longing: 0.8,
        catharsis: 0.35,
      },
      energy: 0.45,
      valence: 0.55,
      useCase: ['a hopeless celebrity crush', 'loving someone from the crowd', 'front-row daydreams'],
      oneLiner: 'A front-row daydream about loving someone famous who will never look down.',
    },
    {
      slug: 'the-other-side-of-the-door',
      moods: {
        heartbreak: 0.55,
        anger: 0.4,
        nostalgia: 0.15,
        joy: 0.1,
        calm: 0.15,
        defiance: 0.5,
        longing: 0.65,
        catharsis: 0.7,
      },
      energy: 0.65,
      valence: 0.3,
      useCase: ['saying leave when you mean stay', 'wanting the grand gesture', 'a post-fight standoff'],
      oneLiner: 'Saying go when you mean stay, and waiting for the grand gesture instead of silence.',
    },
    {
      slug: 'today-was-a-fairytale',
      moods: {
        heartbreak: 0.0,
        anger: 0.0,
        nostalgia: 0.35,
        joy: 0.9,
        calm: 0.35,
        defiance: 0.05,
        longing: 0.4,
        catharsis: 0.4,
      },
      energy: 0.6,
      valence: 0.92,
      useCase: ['a perfect ordinary date', 'giddy new romance', 'magic on a plain afternoon'],
      oneLiner: 'A perfect ordinary date replayed in storybook terms.',
    },
    {
      slug: 'you-all-over-me',
      moods: {
        heartbreak: 0.7,
        anger: 0.05,
        nostalgia: 0.7,
        joy: 0.05,
        calm: 0.45,
        defiance: 0.1,
        longing: 0.75,
        catharsis: 0.55,
      },
      energy: 0.4,
      valence: 0.25,
      useCase: ['a breakup that leaves residue', 'moving on but not clean', 'wiser and wearier'],
      oneLiner: 'Clean but not new: a breakup leaves a residue no amount of moving on scrubs off.',
    },
    {
      slug: 'mr-perfectly-fine',
      moods: {
        heartbreak: 0.45,
        anger: 0.55,
        nostalgia: 0.2,
        joy: 0.4,
        calm: 0.15,
        defiance: 0.75,
        longing: 0.25,
        catharsis: 0.7,
      },
      energy: 0.75,
      valence: 0.45,
      useCase: ['an ex who moved on too fast', 'wit as armor', 'a receipts singalong'],
      oneLiner: 'A catalog of a casually cruel ex, skewered with a wink and the receipts.',
    },
    {
      slug: 'we-were-happy',
      moods: {
        heartbreak: 0.7,
        anger: 0.02,
        nostalgia: 0.85,
        joy: 0.15,
        calm: 0.5,
        defiance: 0.05,
        longing: 0.7,
        catharsis: 0.55,
      },
      energy: 0.35,
      valence: 0.25,
      useCase: ['grieving a love that worked', 'missing the golden middle', 'the happiness that hurts'],
      oneLiner: 'Cataloging the golden middle of a love, because the happiness is what hurts to recall.',
    },
    {
      slug: 'thats-when',
      moods: {
        heartbreak: 0.2,
        anger: 0.05,
        nostalgia: 0.35,
        joy: 0.55,
        calm: 0.5,
        defiance: 0.05,
        longing: 0.6,
        catharsis: 0.5,
      },
      energy: 0.45,
      valence: 0.7,
      useCase: ['finding a way back', 'forgiving and returning', 'negotiating a reunion'],
      oneLiner: 'An apology and its answer, traded verse by verse toward a way back.',
    },
    {
      slug: 'dont-you',
      moods: {
        heartbreak: 0.55,
        anger: 0.1,
        nostalgia: 0.5,
        joy: 0.15,
        calm: 0.55,
        defiance: 0.2,
        longing: 0.75,
        catharsis: 0.45,
      },
      energy: 0.4,
      valence: 0.3,
      useCase: ['running into an ex', 'unfair leftover chemistry', 'guarding yourself'],
      oneLiner: 'Running into the ex who acts like nothing happened, and hating how well it works.',
    },
    {
      slug: 'bye-bye-baby',
      moods: {
        heartbreak: 0.65,
        anger: 0.05,
        nostalgia: 0.55,
        joy: 0.05,
        calm: 0.55,
        defiance: 0.05,
        longing: 0.6,
        catharsis: 0.65,
      },
      energy: 0.35,
      valence: 0.25,
      useCase: ['a goodbye with no fight left', 'accepting its over', 'watching a future drive away'],
      oneLiner: 'A goodbye sadder than it is angry, letting a whole planned future drive away.',
    },
  ],
};
