// Mood scores — folklore era (folklore, 2020). Stage 2 of Mood Chat
// (docs/proposals/2026-07-19-mood-chat.md). Scored ONLY from each track's
// existing researched note/summary/themes in supabase/seed/tracks/folklore.mjs
// — no invented facts, no lyrics. `oneLiner` and `useCase` are ORIGINAL prose.
// Axes 0..1; energy 0 (still)..1 (driving); valence 0 (sad)..1 (happy).

export default {
  eraSlug: 'folklore',
  songs: [
    {
      slug: 'the-1',
      moods: {
        heartbreak: 0.45,
        anger: 0.05,
        nostalgia: 0.6,
        joy: 0.35,
        calm: 0.6,
        defiance: 0.1,
        longing: 0.75,
        catharsis: 0.5,
      },
      energy: 0.45,
      valence: 0.45,
      useCase: ['doing the math on the one who got away', 'fine, honestly, but wistful', 'imagining the parallel life'],
      oneLiner: 'A breezy what-if with a bruise under it: someone doing okay who can’t stop wondering.',
    },
    {
      slug: 'cardigan',
      moods: {
        heartbreak: 0.6,
        anger: 0.1,
        nostalgia: 0.75,
        joy: 0.3,
        calm: 0.4,
        defiance: 0.15,
        longing: 0.85,
        catharsis: 0.7,
      },
      energy: 0.45,
      valence: 0.4,
      useCase: ['being chosen back years later', 'remembering a teenage love', 'the ache of first heartbreak'],
      oneLiner: 'Betty grown up, remembering being young and discarded and chosen again — the favorite comfort object.',
    },
    {
      slug: 'the-last-great-american-dynasty',
      moods: {
        heartbreak: 0.1,
        anger: 0.25,
        nostalgia: 0.5,
        joy: 0.5,
        calm: 0.25,
        defiance: 0.75,
        longing: 0.2,
        catharsis: 0.6,
      },
      energy: 0.6,
      valence: 0.6,
      useCase: ['a woman labeled mad for having fun', 'inheriting someone’s notoriety', 'history rhyming across owners'],
      oneLiner: 'A scandalous widow’s fifty years of gossip — then the narrator buys the house and inherits it all.',
    },
    {
      slug: 'exile',
      moods: {
        heartbreak: 0.85,
        anger: 0.25,
        nostalgia: 0.4,
        joy: 0.05,
        calm: 0.3,
        defiance: 0.15,
        longing: 0.75,
        catharsis: 0.8,
      },
      energy: 0.5,
      valence: 0.2,
      useCase: ['talking past someone you loved', 'a breakup with no shared story', 'two people, two truths'],
      oneLiner: 'A duet staged as two monologues: he saw no signs, she gave hundreds, and neither one hears the other.',
    },
    {
      slug: 'my-tears-ricochet',
      moods: {
        heartbreak: 0.75,
        anger: 0.65,
        nostalgia: 0.35,
        joy: 0.05,
        calm: 0.2,
        defiance: 0.55,
        longing: 0.55,
        catharsis: 0.85,
      },
      energy: 0.45,
      valence: 0.2,
      useCase: ['betrayed by a former ally', 'grieving something that was stolen', 'haunting the person who wronged you'],
      oneLiner: 'Narrated from inside a casket: a betrayer shows up to mourn the very person he cast out and sold.',
    },
    {
      slug: 'mirrorball',
      moods: {
        heartbreak: 0.4,
        anger: 0.05,
        nostalgia: 0.35,
        joy: 0.35,
        calm: 0.55,
        defiance: 0.1,
        longing: 0.65,
        catharsis: 0.55,
      },
      energy: 0.4,
      valence: 0.45,
      useCase: ['wondering who you are with no audience', 'exhausted from people-pleasing', 'shining hardest when they might leave'],
      oneLiner: 'A disco-ball confession from a performer with nowhere left to perform, spinning to keep the crowd.',
    },
    {
      slug: 'seven',
      moods: {
        heartbreak: 0.3,
        anger: 0.1,
        nostalgia: 0.9,
        joy: 0.4,
        calm: 0.55,
        defiance: 0.1,
        longing: 0.8,
        catharsis: 0.6,
      },
      energy: 0.35,
      valence: 0.5,
      useCase: ['a childhood friend you never forgot', 'innocence witnessing something dark', 'love passed down like a folk song'],
      oneLiner: 'Two little girls plotting pirate escapes, one of them living in a frightening house, remembered decades on.',
    },
    {
      slug: 'august',
      moods: {
        heartbreak: 0.65,
        anger: 0.05,
        nostalgia: 0.7,
        joy: 0.3,
        calm: 0.35,
        defiance: 0.1,
        longing: 0.9,
        catharsis: 0.75,
      },
      energy: 0.5,
      valence: 0.35,
      useCase: ['wanting someone who was never yours', 'a summer that felt like a lifetime', 'hoping against the facts'],
      oneLiner: 'The summer fling from the other girl’s side: she knew he was never hers and wanted him anyway.',
    },
    {
      slug: 'this-is-me-trying',
      moods: {
        heartbreak: 0.5,
        anger: 0.2,
        nostalgia: 0.3,
        joy: 0.2,
        calm: 0.35,
        defiance: 0.3,
        longing: 0.55,
        catharsis: 0.8,
      },
      energy: 0.4,
      valence: 0.35,
      useCase: ['when just showing up is heroic', 'invisible effort no one claps for', 'one day sober, one more time'],
      oneLiner: 'Three people barely holding on, where pulling into the driveway you almost skipped is the whole victory.',
    },
    {
      slug: 'illicit-affairs',
      moods: {
        heartbreak: 0.7,
        anger: 0.25,
        nostalgia: 0.3,
        joy: 0.15,
        calm: 0.25,
        defiance: 0.2,
        longing: 0.8,
        catharsis: 0.8,
      },
      energy: 0.4,
      valence: 0.25,
      useCase: ['a secret world one person wide', 'the ruin under the high', 'erasing yourself for someone'],
      oneLiner: 'An affair anatomized in second person, curdling from instructions into an indictment and a bridge-scream.',
    },
    {
      slug: 'invisible-string',
      moods: {
        heartbreak: 0.05,
        anger: 0.02,
        nostalgia: 0.7,
        joy: 0.65,
        calm: 0.7,
        defiance: 0.05,
        longing: 0.55,
        catharsis: 0.6,
      },
      energy: 0.4,
      valence: 0.8,
      useCase: ['every wrong turn now looks like fate', 'gratitude for the detours', 'thanking even the old wounds'],
      oneLiner: 'A fate song where every detour reads, in hindsight, as one gold string pulling two people together.',
    },
    {
      slug: 'mad-woman',
      moods: {
        heartbreak: 0.2,
        anger: 0.85,
        nostalgia: 0.1,
        joy: 0.1,
        calm: 0.1,
        defiance: 0.9,
        longing: 0.15,
        catharsis: 0.8,
      },
      energy: 0.55,
      valence: 0.3,
      useCase: ['called crazy until you become it', 'female rage with teeth', 'refusing the no-win trap'],
      oneLiner: 'The angriest song on the quietest album: gaslight a woman into the witch role and she’ll play it with teeth.',
    },
    {
      slug: 'epiphany',
      moods: {
        heartbreak: 0.6,
        anger: 0.05,
        nostalgia: 0.5,
        joy: 0.05,
        calm: 0.5,
        defiance: 0.1,
        longing: 0.6,
        catharsis: 0.75,
      },
      energy: 0.25,
      valence: 0.25,
      useCase: ['things too heavy to say out loud', 'honoring frontline workers', 'trauma carried across generations'],
      oneLiner: 'Her grandfather’s war and a 2020 hospital ward in one hymn: some things can only be slept off in dreams.',
    },
    {
      slug: 'betty',
      moods: {
        heartbreak: 0.35,
        anger: 0.1,
        nostalgia: 0.55,
        joy: 0.5,
        calm: 0.35,
        defiance: 0.2,
        longing: 0.75,
        catharsis: 0.6,
      },
      energy: 0.55,
      valence: 0.55,
      useCase: ['a doorstep apology you owe', 'teenage recklessness and regret', 'betting everything on forgiveness'],
      oneLiner: 'James’s harmonica-flavored apology: a seventeen-year-old grovels at a party, and the answer stays unwritten.',
    },
    {
      slug: 'peace',
      moods: {
        heartbreak: 0.3,
        anger: 0.05,
        nostalgia: 0.25,
        joy: 0.4,
        calm: 0.5,
        defiance: 0.2,
        longing: 0.8,
        catharsis: 0.7,
      },
      energy: 0.3,
      valence: 0.5,
      useCase: ['offering everything but a normal life', 'loving someone under permanent siege', 'honesty about what you can’t give'],
      oneLiner: 'A pre-nup of the soul: she can promise devotion, loyalty, and fire — but never, ever peace.',
    },
    {
      slug: 'hoax',
      moods: {
        heartbreak: 0.8,
        anger: 0.15,
        nostalgia: 0.3,
        joy: 0.05,
        calm: 0.4,
        defiance: 0.1,
        longing: 0.7,
        catharsis: 0.7,
      },
      energy: 0.2,
      valence: 0.15,
      useCase: ['staying faithful to what wounds you', 'a barefoot walk back anyway', 'braided, composite grief'],
      oneLiner: 'A bleak piano ending: choosing a love that hurts over every painless alternative on offer.',
    },
    {
      slug: 'the-lakes',
      moods: {
        heartbreak: 0.2,
        anger: 0.2,
        nostalgia: 0.55,
        joy: 0.4,
        calm: 0.7,
        defiance: 0.4,
        longing: 0.8,
        catharsis: 0.6,
      },
      energy: 0.35,
      valence: 0.5,
      useCase: ['retiring from the discourse', 'escaping somewhere with no wifi', 'taking the one person who matters'],
      oneLiner: 'A Lake District escape fantasy: leave the hunters and clowns online, take the muse, grow roses.',
    },
  ],
};
