// Mood scores — Lover era (Lover, 2019). Stage 2 of Mood Chat
// (docs/proposals/2026-07-19-mood-chat.md). Scored ONLY from each track's
// existing researched note/summary/themes in supabase/seed/tracks/lover.mjs
// — no invented facts, no lyrics. `oneLiner` and `useCase` are ORIGINAL prose.
// Axes 0..1; energy 0 (still)..1 (driving); valence 0 (sad)..1 (happy).

export default {
  eraSlug: 'lover',
  songs: [
    {
      slug: 'i-forgot-that-you-existed',
      moods: {
        heartbreak: 0.05,
        anger: 0.1,
        nostalgia: 0.1,
        joy: 0.7,
        calm: 0.45,
        defiance: 0.55,
        longing: 0.05,
        catharsis: 0.7,
      },
      energy: 0.55,
      valence: 0.8,
      useCase: ['finally not caring about a grudge', 'indifference as the real revenge', 'closing a heavy chapter'],
      oneLiner: 'The giggling epilogue to reputation: not love, not hate, just the freedom of forgetting.',
    },
    {
      slug: 'cruel-summer',
      moods: {
        heartbreak: 0.2,
        anger: 0.1,
        nostalgia: 0.2,
        joy: 0.6,
        calm: 0.05,
        defiance: 0.4,
        longing: 0.9,
        catharsis: 0.85,
      },
      energy: 0.85,
      valence: 0.55,
      useCase: ['a secret summer romance', 'blurting out love you meant to hide', 'desperation under a cool surface'],
      oneLiner: 'A garden-gate summer fling with the catalog’s most famous bridge-scream about saying too much.',
    },
    {
      slug: 'lover',
      moods: {
        heartbreak: 0.05,
        anger: 0.02,
        nostalgia: 0.4,
        joy: 0.7,
        calm: 0.75,
        defiance: 0.1,
        longing: 0.6,
        catharsis: 0.55,
      },
      energy: 0.35,
      valence: 0.85,
      useCase: ['a first dance at a wedding', 'leaving the Christmas lights up', 'settling into a forever'],
      oneLiner: 'A waltz with its own vows in the bridge, written in one night to be slow-danced to indefinitely.',
    },
    {
      slug: 'the-man',
      moods: {
        heartbreak: 0.05,
        anger: 0.55,
        nostalgia: 0.05,
        joy: 0.5,
        calm: 0.1,
        defiance: 0.85,
        longing: 0.1,
        catharsis: 0.6,
      },
      energy: 0.75,
      valence: 0.55,
      useCase: ['tired of the double standard', 'ambition read as a liability', 'flipping the genders on your critics'],
      oneLiner: 'A thought experiment: run every criticism of her career with the genders swapped and watch it flip.',
    },
    {
      slug: 'the-archer',
      moods: {
        heartbreak: 0.35,
        anger: 0.05,
        nostalgia: 0.2,
        joy: 0.15,
        calm: 0.45,
        defiance: 0.1,
        longing: 0.8,
        catharsis: 0.55,
      },
      energy: 0.4,
      valence: 0.35,
      useCase: ['wondering who could ever stay', 'attachment anxiety at 2am', 'being both hunter and target'],
      oneLiner: 'One synth pulse, no chorus, no drop: pure confession that nothing resolves, including her.',
    },
    {
      slug: 'i-think-he-knows',
      moods: {
        heartbreak: 0.02,
        anger: 0.02,
        nostalgia: 0.05,
        joy: 0.8,
        calm: 0.2,
        defiance: 0.2,
        longing: 0.7,
        catharsis: 0.35,
      },
      energy: 0.7,
      valence: 0.85,
      useCase: ['a confident, electric crush', 'flirting with someone who knows it', 'the charge of mutual attraction'],
      oneLiner: 'A strutting deep cut about a crush on someone fully, infuriatingly aware of his own charm.',
    },
    {
      slug: 'miss-americana-and-the-heartbreak-prince',
      moods: {
        heartbreak: 0.35,
        anger: 0.4,
        nostalgia: 0.35,
        joy: 0.35,
        calm: 0.1,
        defiance: 0.65,
        longing: 0.45,
        catharsis: 0.7,
      },
      energy: 0.65,
      valence: 0.4,
      useCase: ['disillusioned but deciding to speak', 'watching a rigged scoreboard', 'political heartbreak in a letterman jacket'],
      oneLiner: 'High-school Americana as national allegory: the homecoming-queen dream curdling, and speaking anyway.',
    },
    {
      slug: 'paper-rings',
      moods: {
        heartbreak: 0.02,
        anger: 0.02,
        nostalgia: 0.15,
        joy: 0.9,
        calm: 0.2,
        defiance: 0.3,
        longing: 0.5,
        catharsis: 0.5,
      },
      energy: 0.85,
      valence: 0.9,
      useCase: ['giddy about the whole package', 'the person over the paperwork', 'joyful, all-in commitment'],
      oneLiner: 'Pop-punk giddiness: she’d marry this one with rings cut from paper after years of gilded drama.',
    },
    {
      slug: 'cornelia-street',
      moods: {
        heartbreak: 0.4,
        anger: 0.02,
        nostalgia: 0.6,
        joy: 0.35,
        calm: 0.4,
        defiance: 0.05,
        longing: 0.85,
        catharsis: 0.65,
      },
      energy: 0.45,
      valence: 0.45,
      useCase: ['a memory pinned to one street', 'fear a place could turn unlivable', 'love tangled up with geography'],
      oneLiner: 'A whole street she couldn’t walk again if this love ended — memory amputated block by block.',
    },
    {
      slug: 'death-by-a-thousand-cuts',
      moods: {
        heartbreak: 0.75,
        anger: 0.1,
        nostalgia: 0.4,
        joy: 0.25,
        calm: 0.15,
        defiance: 0.2,
        longing: 0.7,
        catharsis: 0.7,
      },
      energy: 0.6,
      valence: 0.3,
      useCase: ['a city full of reminders', 'heartbreak felt in a hundred small places', 'grief you imagined into being'],
      oneLiner: 'A breakup song written inside a happy relationship, sparked by a rom-com in a strange creative loop.',
    },
    {
      slug: 'london-boy',
      moods: {
        heartbreak: 0.02,
        anger: 0.02,
        nostalgia: 0.15,
        joy: 0.85,
        calm: 0.25,
        defiance: 0.1,
        longing: 0.55,
        catharsis: 0.35,
      },
      energy: 0.65,
      valence: 0.9,
      useCase: ['falling for someone’s whole city', 'playful, all-in devotion', 'a tourist-map valentine'],
      oneLiner: 'An American falls for the whole British kit — pubs, rugby, high tea — geography chaos and all.',
    },
    {
      slug: 'soon-youll-get-better',
      moods: {
        heartbreak: 0.85,
        anger: 0.15,
        nostalgia: 0.35,
        joy: 0.1,
        calm: 0.35,
        defiance: 0.1,
        longing: 0.8,
        catharsis: 0.75,
      },
      energy: 0.25,
      valence: 0.2,
      useCase: ['a parent in a hospital', 'bargaining with something bigger', 'love that can only wait and hope'],
      oneLiner: 'Written amid her mother’s cancer: waiting rooms, bargaining, and a refrain that has to be true.',
    },
    {
      slug: 'false-god',
      moods: {
        heartbreak: 0.3,
        anger: 0.2,
        nostalgia: 0.2,
        joy: 0.4,
        calm: 0.4,
        defiance: 0.35,
        longing: 0.8,
        catharsis: 0.6,
      },
      energy: 0.45,
      valence: 0.5,
      useCase: ['fighting across time zones', 'love neither of you will quit', 'devotion even when it’s misplaced'],
      oneLiner: 'Saxophone and sacrilege: a long-distance argument where the relationship is treated as religion.',
    },
    {
      slug: 'you-need-to-calm-down',
      moods: {
        heartbreak: 0.02,
        anger: 0.35,
        nostalgia: 0.05,
        joy: 0.75,
        calm: 0.15,
        defiance: 0.75,
        longing: 0.05,
        catharsis: 0.6,
      },
      energy: 0.8,
      valence: 0.8,
      useCase: ['telling trolls to take a seat', 'standing up as an ally', 'de-escalating with a smile'],
      oneLiner: 'Three verses of "take several seats" — haters, picketers, rivals — ending on a real policy ask.',
    },
    {
      slug: 'afterglow',
      moods: {
        heartbreak: 0.5,
        anger: 0.15,
        nostalgia: 0.2,
        joy: 0.3,
        calm: 0.35,
        defiance: 0.1,
        longing: 0.75,
        catharsis: 0.75,
      },
      energy: 0.5,
      valence: 0.4,
      useCase: ['owning that you started the fight', 'anxiety torching something good', 'an apology and a plea to stay'],
      oneLiner: 'An accountability ballad: she claims the arson and asks the other person to stay inside the glow.',
    },
    {
      slug: 'me',
      moods: {
        heartbreak: 0.02,
        anger: 0.05,
        nostalgia: 0.05,
        joy: 0.85,
        calm: 0.1,
        defiance: 0.5,
        longing: 0.2,
        catharsis: 0.45,
      },
      energy: 0.85,
      valence: 0.9,
      useCase: ['a technicolor confidence boost', 'celebrating being one of a kind', 'a pastel palette flip'],
      oneLiner: 'Self-celebration as a duet: two dramatic people pitching their own irreplaceability in full color.',
    },
    {
      slug: 'its-nice-to-have-a-friend',
      moods: {
        heartbreak: 0.05,
        anger: 0.02,
        nostalgia: 0.55,
        joy: 0.6,
        calm: 0.75,
        defiance: 0.05,
        longing: 0.6,
        catharsis: 0.4,
      },
      energy: 0.3,
      valence: 0.8,
      useCase: ['friendship ripening into love', 'a whole life told in miniature', 'quiet, gentle tenderness'],
      oneLiner: 'Steel drums and a children’s choir tell a whole life — snow fights to a ring — in under three minutes.',
    },
    {
      slug: 'daylight',
      moods: {
        heartbreak: 0.1,
        anger: 0.02,
        nostalgia: 0.45,
        joy: 0.65,
        calm: 0.8,
        defiance: 0.15,
        longing: 0.55,
        catharsis: 0.8,
      },
      energy: 0.4,
      valence: 0.8,
      useCase: ['redefining what love means to you', 'peace after years of drama', 'choosing what you love over what you hate'],
      oneLiner: 'The closer that revises her own catalog: love isn’t golden or red drama but ordinary daylight.',
    },
  ],
};
