export default {
  eraSlug: 'midnights',
  songs: [
    {
      slug: 'lavender-haze',
      moods: {
        heartbreak: 0.03, anger: 0.05, nostalgia: 0.05, joy: 0.55,
        calm: 0.55, defiance: 0.5, longing: 0.15, catharsis: 0.25,
      },
      energy: 0.5,
      valence: 0.7,
      useCase: ['ignoring what people say about your relationship', 'protecting new love from the noise', 'staying in the glow instead of explaining'],
      oneLiner: 'A private glow she refuses to explain to anyone outside it.',
    },
    {
      slug: 'maroon',
      moods: {
        heartbreak: 0.65, anger: 0.1, nostalgia: 0.6, joy: 0.1,
        calm: 0.3, defiance: 0.05, longing: 0.5, catharsis: 0.55,
      },
      energy: 0.35,
      valence: 0.25,
      useCase: ['grieving a love that dissolved slowly', 'remembering a relationship through its colors', 'the stain a near-love leaves behind'],
      oneLiner: 'A New York almost-love remembered in deepening shades of red until only the stain remains.',
    },
    {
      slug: 'anti-hero',
      moods: {
        heartbreak: 0.1, anger: 0.15, nostalgia: 0.05, joy: 0.15,
        calm: 0.05, defiance: 0.1, longing: 0.1, catharsis: 0.75,
      },
      energy: 0.65,
      valence: 0.35,
      useCase: ['3 a.m. spirals of self-doubt', 'confessing you might be the problem', 'laughing at your own worst habits'],
      oneLiner: 'A guided tour of 3 a.m. self-loathing set to a hook so catchy it became a global catchphrase.',
    },
    {
      slug: 'snow-on-the-beach',
      moods: {
        heartbreak: 0.03, anger: 0.02, nostalgia: 0.05, joy: 0.65,
        calm: 0.5, defiance: 0.05, longing: 0.35, catharsis: 0.3,
      },
      energy: 0.35,
      valence: 0.75,
      useCase: ['falling for someone at the exact same moment', 'a feeling too improbable to fully trust', 'wonder instead of doubt'],
      oneLiner: 'Two people falling at the same instant, weird and beautiful like snow landing on a beach.',
    },
    {
      slug: 'youre-on-your-own-kid',
      moods: {
        heartbreak: 0.3, anger: 0.1, nostalgia: 0.5, joy: 0.3,
        calm: 0.15, defiance: 0.55, longing: 0.35, catharsis: 0.8,
      },
      energy: 0.6,
      valence: 0.5,
      useCase: ['growing up without anyone catching you', 'turning loneliness into self-reliance', 'the crescendo of finally moving on'],
      oneLiner: 'A whole coming-of-age compressed into one crescendo that ends in choosing yourself.',
    },
    {
      slug: 'midnight-rain',
      moods: {
        heartbreak: 0.4, anger: 0.05, nostalgia: 0.35, joy: 0.15,
        calm: 0.25, defiance: 0.35, longing: 0.3, catharsis: 0.35,
      },
      energy: 0.55,
      valence: 0.4,
      useCase: ['choosing ambition over comfort', 'a breakup with no villain', 'wondering about the road not taken'],
      oneLiner: 'He wanted quiet and settled; she wanted the whole loud world, and the wanting chose for her.',
    },
    {
      slug: 'question',
      moods: {
        heartbreak: 0.4, anger: 0.15, nostalgia: 0.45, joy: 0.1,
        calm: 0.1, defiance: 0.15, longing: 0.5, catharsis: 0.35,
      },
      energy: 0.55,
      valence: 0.35,
      useCase: ['interrogating an ex about one unresolved night', 'replaying a kiss that never got explained', 'cross-examining an old almost'],
      oneLiner: 'A cross-examination disguised as a pop song, still chasing what one unresolved kiss meant.',
    },
    {
      slug: 'vigilante-shit',
      moods: {
        heartbreak: 0.1, anger: 0.55, nostalgia: 0.02, joy: 0.1,
        calm: 0.35, defiance: 0.7, longing: 0.05, catharsis: 0.6,
      },
      energy: 0.45,
      valence: 0.35,
      useCase: ['plotting cold, lawful revenge', 'helping a wronged friend collect evidence', 'dressing for vengeance'],
      oneLiner: 'Revenge served through paperwork — cold, controlled, and dressed for the occasion.',
    },
    {
      slug: 'bejeweled',
      moods: {
        heartbreak: 0.15, anger: 0.05, nostalgia: 0.1, joy: 0.65,
        calm: 0.1, defiance: 0.6, longing: 0.1, catharsis: 0.5,
      },
      energy: 0.75,
      valence: 0.7,
      useCase: ['proving you can still light up a room', 'convincing yourself you have not lost your shine', 'walking out the door and glittering anyway'],
      oneLiner: 'Half pep talk to a partner, half proof to herself that the quiet years did not dim her shine.',
    },
    {
      slug: 'labyrinth',
      moods: {
        heartbreak: 0.25, anger: 0.03, nostalgia: 0.2, joy: 0.35,
        calm: 0.35, defiance: 0.1, longing: 0.45, catharsis: 0.45,
      },
      energy: 0.35,
      valence: 0.45,
      useCase: ['falling in love again while still healing', 'talking yourself through a panic', 'terrified of the drop into new love'],
      oneLiner: 'Breath held in an emotional stairwell, talking herself through the fear of falling again.',
    },
    {
      slug: 'karma',
      moods: {
        heartbreak: 0.05, anger: 0.2, nostalgia: 0.02, joy: 0.65,
        calm: 0.3, defiance: 0.55, longing: 0.05, catharsis: 0.55,
      },
      energy: 0.7,
      valence: 0.65,
      useCase: ['gloating while karma does the work', 'watching enemies get their invoice', 'serenity as the ultimate revenge'],
      oneLiner: 'Cosmic justice as her personal pet — serene, smug, and coming for her enemies on its own schedule.',
    },
    {
      slug: 'sweet-nothing',
      moods: {
        heartbreak: 0.05, anger: 0.02, nostalgia: 0.15, joy: 0.5,
        calm: 0.75, defiance: 0.05, longing: 0.2, catharsis: 0.2,
      },
      energy: 0.15,
      valence: 0.65,
      useCase: ['coming home to someone who wants nothing from you', 'a tiny refuge from the industry noise', 'love that asks for nothing'],
      oneLiner: 'Industry wolves demand more all day; at home someone only wants her company and a poem.',
    },
    {
      slug: 'mastermind',
      moods: {
        heartbreak: 0.05, anger: 0.02, nostalgia: 0.1, joy: 0.55,
        calm: 0.3, defiance: 0.3, longing: 0.25, catharsis: 0.4,
      },
      energy: 0.45,
      valence: 0.6,
      useCase: ['admitting you planned the whole meet-cute', 'being fully seen and loved anyway', 'confessing the scheme behind the magic'],
      oneLiner: 'A love that looked like fate was actually chess, and he knew and stayed anyway.',
    },
    {
      slug: 'the-great-war',
      moods: {
        heartbreak: 0.35, anger: 0.35, nostalgia: 0.15, joy: 0.15,
        calm: 0.2, defiance: 0.15, longing: 0.3, catharsis: 0.7,
      },
      energy: 0.5,
      valence: 0.4,
      useCase: ['surviving your relationship\'s worst fight', 'old wounds making you swing at someone innocent', 'planting peace over a battle you barely survived'],
      oneLiner: 'Old wounds make her swing at someone innocent, and the vow after the battle is never again.',
    },
    {
      slug: 'bigger-than-the-whole-sky',
      moods: {
        heartbreak: 0.55, anger: 0.05, nostalgia: 0.2, joy: 0.02,
        calm: 0.15, defiance: 0.03, longing: 0.6, catharsis: 0.75,
      },
      energy: 0.15,
      valence: 0.1,
      useCase: ['grieving something that never got to exist', 'mourning a loss with no name', 'a goodbye you never chose'],
      oneLiner: 'A goodbye to something that never got to exist, left open enough to hold anyone\'s grief.',
    },
    {
      slug: 'paris',
      moods: {
        heartbreak: 0.03, anger: 0.02, nostalgia: 0.1, joy: 0.65,
        calm: 0.4, defiance: 0.2, longing: 0.15, catharsis: 0.2,
      },
      energy: 0.45,
      valence: 0.7,
      useCase: ['turning a bedroom into another city', 'shutting out the gossip cycle together', 'giddy secrecy as the whole romance'],
      oneLiner: 'No trip required — two people draw the blinds and the room quietly becomes Paris.',
    },
    {
      slug: 'high-infidelity',
      moods: {
        heartbreak: 0.45, anger: 0.3, nostalgia: 0.1, joy: 0.05,
        calm: 0.2, defiance: 0.2, longing: 0.15, catharsis: 0.5,
      },
      energy: 0.5,
      valence: 0.3,
      useCase: ['keeping one foot out the door', 'infidelity as symptom of a cold relationship', 'guilt dressed up as self-defense'],
      oneLiner: 'A narrator inside a cold relationship keeps one foot out the door, then finally uses it.',
    },
    {
      slug: 'glitch',
      moods: {
        heartbreak: 0.1, anger: 0.03, nostalgia: 0.15, joy: 0.4,
        calm: 0.3, defiance: 0.1, longing: 0.35, catharsis: 0.25,
      },
      energy: 0.4,
      valence: 0.5,
      useCase: ['a casual arrangement that turned into real feelings', 'calling accidental love a system error', 'five years of a glitch nobody fixed'],
      oneLiner: 'The setup was supposed to be temporary; five years of uptime later, the glitch is the whole program.',
    },
    {
      slug: 'wouldve-couldve-shouldve',
      moods: {
        heartbreak: 0.6, anger: 0.4, nostalgia: 0.45, joy: 0.02,
        calm: 0.1, defiance: 0.15, longing: 0.35, catharsis: 0.75,
      },
      energy: 0.35,
      valence: 0.15,
      useCase: ['re-litigating what happened to you at nineteen', 'regret that still haunts your sleep decades later', 'reckoning with an old wound as an adult'],
      oneLiner: 'An adult re-litigating what happened to her at nineteen, still making ruins of her sleep at thirty-two.',
    },
    {
      slug: 'dear-reader',
      moods: {
        heartbreak: 0.1, anger: 0.05, nostalgia: 0.1, joy: 0.1,
        calm: 0.2, defiance: 0.35, longing: 0.15, catharsis: 0.4,
      },
      energy: 0.3,
      valence: 0.35,
      useCase: ['getting advice from someone who admits she is lost too', 'burning the map and moving cities anyway', 'a warning disguised as an advice column'],
      oneLiner: 'Life tips from a self-described bad example, who admits at the end that you should not listen.',
    },
    {
      slug: 'hits-different',
      moods: {
        heartbreak: 0.55, anger: 0.2, nostalgia: 0.2, joy: 0.15,
        calm: 0.05, defiance: 0.15, longing: 0.4, catharsis: 0.55,
      },
      energy: 0.55,
      valence: 0.25,
      useCase: ['crying at parties you did not want to attend', 'seeing his face in every stranger', 'every coping mechanism failing at once'],
      oneLiner: 'Every coping mechanism fails at once — crying at parties, arguing with strangers, spiraling in public.',
    },
    {
      slug: 'youre-losing-me',
      moods: {
        heartbreak: 0.75, anger: 0.25, nostalgia: 0.15, joy: 0.02,
        calm: 0.1, defiance: 0.1, longing: 0.3, catharsis: 0.6,
      },
      energy: 0.3,
      valence: 0.1,
      useCase: ['fading in a relationship no one will end', 'watching a partner refuse to fight or choose', 'the slow flatline before a breakup'],
      oneLiner: 'A slow flatline in a relationship where the other person will not fight, choose, or even argue.',
    },
  ],
};
