// Mood scores — Red era (Red 2012 / Taylor's Version 2021, incl. From The
// Vault). Stage 2 of the Mood Chat feature
// (docs/proposals/2026-07-19-mood-chat.md). Scored ONLY from each track's
// existing researched note/summary/inspiration/themes in
// supabase/seed/tracks/red.mjs — no invented facts, no lyrics. `oneLiner` and
// `useCase` are ORIGINAL prose. The eight axes are each 0..1; energy is
// 0 (still) .. 1 (driving); valence is 0 (sad) .. 1 (happy).

export default {
  eraSlug: 'red',
  songs: [
    {
      slug: 'state-of-grace',
      moods: {
        heartbreak: 0.2,
        anger: 0.05,
        nostalgia: 0.4,
        joy: 0.5,
        calm: 0.15,
        defiance: 0.4,
        longing: 0.55,
        catharsis: 0.7,
      },
      energy: 0.75,
      valence: 0.6,
      useCase: ['falling into something risky', 'a love worth the wreck', 'arena-sized new beginnings'],
      oneLiner: 'The door kicked open on a love that will change everything — reckless, ruinous, and chosen anyway.',
    },
    {
      slug: 'red',
      moods: {
        heartbreak: 0.6,
        anger: 0.2,
        nostalgia: 0.6,
        joy: 0.4,
        calm: 0.1,
        defiance: 0.2,
        longing: 0.7,
        catharsis: 0.7,
      },
      energy: 0.7,
      valence: 0.4,
      useCase: ['a love that ran too hot to keep', 'remembering in color', 'the highs and the gray after'],
      oneLiner: 'An entire relationship graded by color — and red saved for the parts that refuse to fade.',
    },
    {
      slug: 'treacherous',
      moods: {
        heartbreak: 0.15,
        anger: 0.02,
        nostalgia: 0.1,
        joy: 0.3,
        calm: 0.4,
        defiance: 0.35,
        longing: 0.85,
        catharsis: 0.45,
      },
      energy: 0.4,
      valence: 0.45,
      useCase: ['wanting what you know is trouble', 'a slow-burn you cant stop', 'the first step down a bad slope'],
      oneLiner: 'Seeing exactly where the slope leads and taking the first step down it anyway, slowly.',
    },
    {
      slug: 'i-knew-you-were-trouble',
      moods: {
        heartbreak: 0.55,
        anger: 0.45,
        nostalgia: 0.1,
        joy: 0.15,
        calm: 0.05,
        defiance: 0.3,
        longing: 0.2,
        catharsis: 0.8,
      },
      energy: 0.85,
      valence: 0.3,
      useCase: ['blaming yourself for ignoring red flags', 'a self-aware bad-decision spiral', 'the floor giving out'],
      oneLiner: 'The red flags were visible from the parking lot — and the bass drop is the floor giving out anyway.',
    },
    {
      slug: 'all-too-well',
      moods: {
        heartbreak: 0.9,
        anger: 0.4,
        nostalgia: 0.9,
        joy: 0.05,
        calm: 0.15,
        defiance: 0.25,
        longing: 0.85,
        catharsis: 0.8,
      },
      energy: 0.5,
      valence: 0.15,
      useCase: ['crying in the car', 'an autumn you cant give back', 'remembering every detail on purpose'],
      oneLiner: 'A relationship rebuilt object by object — a scarf, an autumn, a refrigerator-light dance — because remembering is the only power left.',
    },
    {
      slug: '22',
      moods: {
        heartbreak: 0.05,
        anger: 0.02,
        nostalgia: 0.3,
        joy: 0.9,
        calm: 0.1,
        defiance: 0.4,
        longing: 0.1,
        catharsis: 0.5,
      },
      energy: 0.85,
      valence: 0.9,
      useCase: ['a night out with your friends', 'ditching the heartbreak for one night', 'happy free confused all at once'],
      oneLiner: 'Being twenty-two as a whole mood: dressed up, heartbreak benched, dancing like the night belongs to your friends.',
    },
    {
      slug: 'i-almost-do',
      moods: {
        heartbreak: 0.65,
        anger: 0.05,
        nostalgia: 0.4,
        joy: 0.05,
        calm: 0.4,
        defiance: 0.2,
        longing: 0.85,
        catharsis: 0.4,
      },
      energy: 0.4,
      valence: 0.2,
      useCase: ['hovering over the call button', 'not texting the ex', 'every reason to reach out but one not to'],
      oneLiner: 'Every reason to call after a breakup, held back by the one reason not to — so the song replaces the phone call.',
    },
    {
      slug: 'we-are-never-ever-getting-back-together',
      moods: {
        heartbreak: 0.2,
        anger: 0.4,
        nostalgia: 0.1,
        joy: 0.6,
        calm: 0.05,
        defiance: 0.85,
        longing: 0.05,
        catharsis: 0.7,
      },
      energy: 0.85,
      valence: 0.75,
      useCase: ['done with the on-again-off-again', 'a gleeful spiteful breakup', 'closing the door with an eye-roll'],
      oneLiner: 'A breakup declared with a flounce and an eye-roll — the never-ever doing gleeful, spiteful work.',
    },
    {
      slug: 'stay-stay-stay',
      moods: {
        heartbreak: 0.05,
        anger: 0.05,
        nostalgia: 0.2,
        joy: 0.85,
        calm: 0.45,
        defiance: 0.1,
        longing: 0.15,
        catharsis: 0.4,
      },
      energy: 0.65,
      valence: 0.85,
      useCase: ['a love that survives the fights', 'goofy easygoing devotion', 'staying instead of storming out'],
      oneLiner: 'A fight that ends in laughter instead of tears — staying becomes the punchline and the point.',
    },
    {
      slug: 'the-last-time',
      moods: {
        heartbreak: 0.75,
        anger: 0.2,
        nostalgia: 0.25,
        joy: 0.02,
        calm: 0.35,
        defiance: 0.25,
        longing: 0.7,
        catharsis: 0.7,
      },
      energy: 0.5,
      valence: 0.2,
      useCase: ['worn down from giving last chances', 'two people talking past each other', 'the same doorway one more time'],
      oneLiner: 'Two exhausted people at the same doorway again — one pleading for a last chance, one too worn down to give it.',
    },
    {
      slug: 'holy-ground',
      moods: {
        heartbreak: 0.15,
        anger: 0.02,
        nostalgia: 0.8,
        joy: 0.65,
        calm: 0.3,
        defiance: 0.15,
        longing: 0.35,
        catharsis: 0.7,
      },
      energy: 0.8,
      valence: 0.75,
      useCase: ['looking back fondly instead of bitter', 'gratitude for a love that ended', 'making peace with the past'],
      oneLiner: 'Years later the anger burns off and only gratitude is left — the ground a good love stood on, consecrated.',
    },
    {
      slug: 'sad-beautiful-tragic',
      moods: {
        heartbreak: 0.75,
        anger: 0.05,
        nostalgia: 0.7,
        joy: 0.02,
        calm: 0.5,
        defiance: 0.05,
        longing: 0.7,
        catharsis: 0.5,
      },
      energy: 0.3,
      valence: 0.15,
      useCase: ['mourning something already gone', 'the fog of remembering', 'no blame left, only sadness'],
      oneLiner: 'A relationship seen from the far shore with no blame left — just the three adjectives of the title taking turns.',
    },
    {
      slug: 'the-lucky-one',
      moods: {
        heartbreak: 0.1,
        anger: 0.1,
        nostalgia: 0.5,
        joy: 0.25,
        calm: 0.4,
        defiance: 0.3,
        longing: 0.55,
        catharsis: 0.45,
      },
      energy: 0.5,
      valence: 0.4,
      useCase: ['wondering if the fame is worth it', 'wanting to disappear from the spotlight', 'admiring someone who walked away'],
      oneLiner: 'A starlet trades Madison Square Garden for a rose garden — and you start to suspect the runaway was the lucky one.',
    },
    {
      slug: 'everything-has-changed',
      moods: {
        heartbreak: 0.05,
        anger: 0.0,
        nostalgia: 0.2,
        joy: 0.75,
        calm: 0.45,
        defiance: 0.05,
        longing: 0.65,
        catharsis: 0.4,
      },
      energy: 0.5,
      valence: 0.8,
      useCase: ['first-meeting butterflies', 'wanting to know everything about someone', 'the day that split before and after'],
      oneLiner: 'Two people who just met and already split time into before and after — all butterflies and wanting to know more.',
    },
    {
      slug: 'starlight',
      moods: {
        heartbreak: 0.02,
        anger: 0.0,
        nostalgia: 0.75,
        joy: 0.75,
        calm: 0.35,
        defiance: 0.2,
        longing: 0.5,
        catharsis: 0.45,
      },
      energy: 0.7,
      valence: 0.85,
      useCase: ['dreaming up a glamorous night', 'young and sure the future is gleaming', 'dancing like its decades ago'],
      oneLiner: 'A whole shimmering night invented around one old photograph — two teenagers and a future still unwritten.',
    },
    {
      slug: 'begin-again',
      moods: {
        heartbreak: 0.25,
        anger: 0.02,
        nostalgia: 0.3,
        joy: 0.65,
        calm: 0.6,
        defiance: 0.1,
        longing: 0.4,
        catharsis: 0.6,
      },
      energy: 0.45,
      valence: 0.8,
      useCase: ['a first date after heartbreak', 'realizing love isnt all scorn', 'quietly starting to believe again'],
      oneLiner: 'A Wednesday-cafe first date where she catches herself laughing — and heartbreak does not get the last word.',
    },
    {
      slug: 'the-moment-i-knew',
      moods: {
        heartbreak: 0.85,
        anger: 0.25,
        nostalgia: 0.2,
        joy: 0.02,
        calm: 0.2,
        defiance: 0.1,
        longing: 0.7,
        catharsis: 0.6,
      },
      energy: 0.45,
      valence: 0.12,
      useCase: ['watching a door for someone who wont come', 'a birthday that fell apart', 'the exact moment you knew'],
      oneLiner: 'Standing in a party dress watching a door that never opens — the relationship ending in an empty doorway.',
    },
    {
      slug: 'come-back-be-here',
      moods: {
        heartbreak: 0.5,
        anger: 0.02,
        nostalgia: 0.35,
        joy: 0.15,
        calm: 0.4,
        defiance: 0.05,
        longing: 0.9,
        catharsis: 0.4,
      },
      energy: 0.45,
      valence: 0.3,
      useCase: ['missing someone an ocean away', 'resenting the distance', 'a perfect weekend cut short'],
      oneLiner: 'One perfect weekend, then an ocean — resenting geography itself for interrupting something that barely started.',
    },
    {
      slug: 'girl-at-home',
      moods: {
        heartbreak: 0.05,
        anger: 0.15,
        nostalgia: 0.1,
        joy: 0.55,
        calm: 0.2,
        defiance: 0.65,
        longing: 0.05,
        catharsis: 0.45,
      },
      energy: 0.7,
      valence: 0.65,
      useCase: ['turning down a taken man', 'solidarity with the girl at home', 'doing the right thing on principle'],
      oneLiner: 'A flirtatious guy with a girlfriend gets shut down out of solidarity — not jealousy, just the girl at home.',
    },
    {
      slug: 'ronan',
      moods: {
        heartbreak: 0.95,
        anger: 0.05,
        nostalgia: 0.6,
        joy: 0.1,
        calm: 0.3,
        defiance: 0.05,
        longing: 0.8,
        catharsis: 0.75,
      },
      energy: 0.35,
      valence: 0.1,
      useCase: ['grieving a child', 'holding a memory that hurts', 'a loss with no words'],
      oneLiner: 'A eulogy in a grieving mother’s own words for a boy who died just before turning four — one of her heaviest songs.',
    },
    {
      slug: 'better-man',
      moods: {
        heartbreak: 0.6,
        anger: 0.3,
        nostalgia: 0.5,
        joy: 0.05,
        calm: 0.35,
        defiance: 0.4,
        longing: 0.6,
        catharsis: 0.65,
      },
      energy: 0.5,
      valence: 0.3,
      useCase: ['missing someone you were right to leave', 'grief without regret', 'wishing hed just been kinder'],
      oneLiner: 'Missing someone and refusing to apologize for leaving — the love was real, but so was the pattern.',
    },
    {
      slug: 'nothing-new',
      moods: {
        heartbreak: 0.35,
        anger: 0.1,
        nostalgia: 0.4,
        joy: 0.05,
        calm: 0.45,
        defiance: 0.15,
        longing: 0.6,
        catharsis: 0.55,
      },
      energy: 0.35,
      valence: 0.25,
      useCase: ['fearing youll be replaced', 'aging out of the spotlight', 'wondering if the applause fades'],
      oneLiner: 'The fear of being novelty — what happens when a newer, shinier girl arrives and everyone stops clapping.',
    },
    {
      slug: 'babe',
      moods: {
        heartbreak: 0.7,
        anger: 0.5,
        nostalgia: 0.2,
        joy: 0.05,
        calm: 0.1,
        defiance: 0.55,
        longing: 0.4,
        catharsis: 0.7,
      },
      energy: 0.6,
      valence: 0.25,
      useCase: ['one betrayal that ends everything', 'the last straw', 'a future canceled in a moment'],
      oneLiner: 'One act of betrayal detonates the whole future tense — every plan they made now needs a new pronoun.',
    },
    {
      slug: 'message-in-a-bottle',
      moods: {
        heartbreak: 0.05,
        anger: 0.0,
        nostalgia: 0.15,
        joy: 0.8,
        calm: 0.15,
        defiance: 0.1,
        longing: 0.65,
        catharsis: 0.45,
      },
      energy: 0.8,
      valence: 0.85,
      useCase: ['a crush youre hoping reaches them', 'fizzy long-shot hope', 'throwing your heart into the void'],
      oneLiner: 'A crush lobbed into the void like a corked note into the sea — pure fizzy hope it finds the right person.',
    },
    {
      slug: 'i-bet-you-think-about-me',
      moods: {
        heartbreak: 0.15,
        anger: 0.35,
        nostalgia: 0.3,
        joy: 0.5,
        calm: 0.2,
        defiance: 0.7,
        longing: 0.1,
        catharsis: 0.55,
      },
      energy: 0.65,
      valence: 0.6,
      useCase: ['betting an ex still thinks of you', 'a witty class-warfare kiss-off', 'small-town pride vs his fancy world'],
      oneLiner: 'A small-town girl toasts the rich ex at his own imaginary wedding — and bets she still haunts his world.',
    },
    {
      slug: 'forever-winter',
      moods: {
        heartbreak: 0.55,
        anger: 0.05,
        nostalgia: 0.2,
        joy: 0.15,
        calm: 0.25,
        defiance: 0.2,
        longing: 0.75,
        catharsis: 0.7,
      },
      energy: 0.6,
      valence: 0.3,
      useCase: ['loving someone whos struggling', 'wishing youd understood sooner', 'staying on the line for someone'],
      oneLiner: 'Circling someone in crisis, terrified of losing them and promising to stay on the line.',
    },
    {
      slug: 'run',
      moods: {
        heartbreak: 0.05,
        anger: 0.02,
        nostalgia: 0.2,
        joy: 0.45,
        calm: 0.6,
        defiance: 0.4,
        longing: 0.65,
        catharsis: 0.45,
      },
      energy: 0.4,
      valence: 0.6,
      useCase: ['running away with someone', 'a private escape from expectations', 'a quiet getaway fantasy'],
      oneLiner: 'An elopement daydream in hushed harmony — two people ditching everyone’s expectations with a head start.',
    },
    {
      slug: 'the-very-first-night',
      moods: {
        heartbreak: 0.4,
        anger: 0.02,
        nostalgia: 0.8,
        joy: 0.7,
        calm: 0.15,
        defiance: 0.1,
        longing: 0.8,
        catharsis: 0.6,
      },
      energy: 0.8,
      valence: 0.6,
      useCase: ['missing the private early days', 'dancing back to the beginning', 'grief hiding inside a bop'],
      oneLiner: 'Grief disguised as a party track — missing the private version of a love, back when it was only theirs.',
    },
    {
      slug: 'all-too-well-10-minute-version',
      moods: {
        heartbreak: 0.95,
        anger: 0.6,
        nostalgia: 0.85,
        joy: 0.05,
        calm: 0.1,
        defiance: 0.3,
        longing: 0.9,
        catharsis: 0.8,
      },
      energy: 0.5,
      valence: 0.15,
      useCase: ['the 3am spiral', 'ten minutes of reopening the wound', 'the directors cut of heartbreak'],
      oneLiner: 'Ten minutes of a wound reopened on purpose — the uncut draft, every excised verse restored.',
    },
  ],
};
