// Mood scores — reputation era (reputation, 2017). Stage 2 of Mood Chat
// (docs/proposals/2026-07-19-mood-chat.md). Scored ONLY from each track's
// existing researched note/summary/themes in supabase/seed/tracks/reputation.mjs
// — no invented facts, no lyrics. `oneLiner` and `useCase` are ORIGINAL prose.
// Axes 0..1; energy 0 (still)..1 (driving); valence 0 (sad)..1 (happy).

export default {
  eraSlug: 'reputation',
  songs: [
    {
      slug: 'ready-for-it',
      moods: {
        heartbreak: 0.05,
        anger: 0.2,
        nostalgia: 0.1,
        joy: 0.55,
        calm: 0.05,
        defiance: 0.8,
        longing: 0.65,
        catharsis: 0.55,
      },
      energy: 0.95,
      valence: 0.6,
      useCase: ['a new love you keep secret', 'armor up and let someone in', 'the thrill of a co-conspirator'],
      oneLiner: 'Industrial armor on the verses, a secret love song hiding in the chorus.',
    },
    {
      slug: 'end-game',
      moods: {
        heartbreak: 0.1,
        anger: 0.15,
        nostalgia: 0.1,
        joy: 0.55,
        calm: 0.1,
        defiance: 0.55,
        longing: 0.7,
        catharsis: 0.45,
      },
      energy: 0.85,
      valence: 0.6,
      useCase: ['wanting to be someone’s ending', 'judged by your worst headlines', 'past baggage on the table'],
      oneLiner: 'Big reputations all asking the same thing: judge me up close, not by the highlight reel.',
    },
    {
      slug: 'i-did-something-bad',
      moods: {
        heartbreak: 0.05,
        anger: 0.75,
        nostalgia: 0.05,
        joy: 0.5,
        calm: 0.02,
        defiance: 0.95,
        longing: 0.05,
        catharsis: 0.8,
      },
      energy: 0.9,
      valence: 0.5,
      useCase: ['done apologizing for existing', 'burned as a witch anyway', 'playing the villain on purpose'],
      oneLiner: 'Zero remorse as a power stance: if they’ll burn her either way, she’ll supply the gasoline.',
    },
    {
      slug: 'dont-blame-me',
      moods: {
        heartbreak: 0.15,
        anger: 0.15,
        nostalgia: 0.05,
        joy: 0.5,
        calm: 0.1,
        defiance: 0.6,
        longing: 0.8,
        catharsis: 0.85,
      },
      energy: 0.8,
      valence: 0.5,
      useCase: ['love that feels like a drug', 'obsessive devotion', 'pleading guilty with a choir behind you'],
      oneLiner: 'A gospel-stomp confession that love made her crazy and she’d be convicted for it gladly.',
    },
    {
      slug: 'delicate',
      moods: {
        heartbreak: 0.2,
        anger: 0.02,
        nostalgia: 0.15,
        joy: 0.5,
        calm: 0.55,
        defiance: 0.15,
        longing: 0.8,
        catharsis: 0.55,
      },
      energy: 0.5,
      valence: 0.6,
      useCase: ['starting something real, terrified', 'wondering if it’s too soon', 'liked despite your worst name'],
      oneLiner: 'The soft center: your reputation’s never been worse, so someone liking you anyway must be real.',
    },
    {
      slug: 'look-what-you-made-me-do',
      moods: {
        heartbreak: 0.05,
        anger: 0.85,
        nostalgia: 0.1,
        joy: 0.4,
        calm: 0.02,
        defiance: 0.95,
        longing: 0.05,
        catharsis: 0.8,
      },
      energy: 0.85,
      valence: 0.45,
      useCase: ['clapping back at the whole narrative', 'the old you can’t come to the phone', 'reinventing after a burial'],
      oneLiner: 'A revenge overture that kills the old Taylor and dares everyone who wrote her obituary.',
    },
    {
      slug: 'so-it-goes',
      moods: {
        heartbreak: 0.1,
        anger: 0.1,
        nostalgia: 0.1,
        joy: 0.5,
        calm: 0.35,
        defiance: 0.35,
        longing: 0.65,
        catharsis: 0.4,
      },
      energy: 0.6,
      valence: 0.55,
      useCase: ['someone only you get to see', 'shutting the door on the world', 'private intensity'],
      oneLiner: 'A dissolve into someone behind closed doors, shrugging at everything outside the two of them.',
    },
    {
      slug: 'gorgeous',
      moods: {
        heartbreak: 0.05,
        anger: 0.2,
        nostalgia: 0.05,
        joy: 0.75,
        calm: 0.1,
        defiance: 0.3,
        longing: 0.65,
        catharsis: 0.35,
      },
      energy: 0.65,
      valence: 0.75,
      useCase: ['furious that someone’s that attractive', 'a tipsy inconvenient crush', 'petty and loving it'],
      oneLiner: 'The album’s lightest confession: being mad at someone just for being that gorgeous.',
    },
    {
      slug: 'getaway-car',
      moods: {
        heartbreak: 0.55,
        anger: 0.1,
        nostalgia: 0.3,
        joy: 0.35,
        calm: 0.05,
        defiance: 0.5,
        longing: 0.5,
        catharsis: 0.8,
      },
      energy: 0.8,
      valence: 0.45,
      useCase: ['a rebound you knew was doomed', 'fleeing one wreck into another', 'owning that you did wrong'],
      oneLiner: 'A heist epic about using one love to escape another, doomed from the ignition and knowing it.',
    },
    {
      slug: 'king-of-my-heart',
      moods: {
        heartbreak: 0.05,
        anger: 0.02,
        nostalgia: 0.15,
        joy: 0.8,
        calm: 0.35,
        defiance: 0.25,
        longing: 0.6,
        catharsis: 0.6,
      },
      energy: 0.7,
      valence: 0.85,
      useCase: ['falling deeper in stages', 'contentment over flash', 'someone winning over your cynicism'],
      oneLiner: 'Three acts of falling: from liking your own company to full fanfare for the right person.',
    },
    {
      slug: 'dancing-with-our-hands-tied',
      moods: {
        heartbreak: 0.4,
        anger: 0.1,
        nostalgia: 0.25,
        joy: 0.4,
        calm: 0.15,
        defiance: 0.5,
        longing: 0.75,
        catharsis: 0.7,
      },
      energy: 0.75,
      valence: 0.45,
      useCase: ['loving someone under a spotlight', 'holding on as it might blow up', 'a dance inside the blast radius'],
      oneLiner: 'Loving someone while the world watches with knives out, and slow-dancing through the dread anyway.',
    },
    {
      slug: 'dress',
      moods: {
        heartbreak: 0.05,
        anger: 0.05,
        nostalgia: 0.15,
        joy: 0.55,
        calm: 0.3,
        defiance: 0.25,
        longing: 0.85,
        catharsis: 0.5,
      },
      energy: 0.55,
      valence: 0.65,
      useCase: ['friendship burning past its container', 'grown-up wanting', 'a want you finally say out loud'],
      oneLiner: 'The most grown-up song yet: desire stated plainly enough to make the listening parties blush.',
    },
    {
      slug: 'this-is-why-we-cant-have-nice-things',
      moods: {
        heartbreak: 0.15,
        anger: 0.65,
        nostalgia: 0.15,
        joy: 0.55,
        calm: 0.02,
        defiance: 0.85,
        longing: 0.1,
        catharsis: 0.75,
      },
      energy: 0.85,
      valence: 0.5,
      useCase: ['a betrayal you can laugh at now', 'offering forgiveness then yanking it', 'gleeful pettiness'],
      oneLiner: 'A party-crash diss track that fake-toasts forgiveness for a knife-in-the-back friendship, then laughs.',
    },
    {
      slug: 'call-it-what-you-want',
      moods: {
        heartbreak: 0.15,
        anger: 0.05,
        nostalgia: 0.2,
        joy: 0.55,
        calm: 0.6,
        defiance: 0.5,
        longing: 0.5,
        catharsis: 0.65,
      },
      energy: 0.45,
      valence: 0.65,
      useCase: ['the calm after your name got wrecked', 'one person who stayed', 'not caring what they call it'],
      oneLiner: 'The peace treaty after the war: the castle fell, the crowd left, and the one who stayed is enough.',
    },
    {
      slug: 'new-years-day',
      moods: {
        heartbreak: 0.15,
        anger: 0.02,
        nostalgia: 0.55,
        joy: 0.45,
        calm: 0.85,
        defiance: 0.05,
        longing: 0.7,
        catharsis: 0.6,
      },
      energy: 0.2,
      valence: 0.65,
      useCase: ['wanting the person who stays to clean up', 'the quiet morning after', 'ordinary, unglamorous devotion'],
      oneLiner: 'A bare piano closer: after twelve tracks of armor, she just wants whoever holds the trash bag.',
    },
  ],
};
