// Mood scores — Speak Now era (Speak Now 2010 / Taylor's Version 2023). Stage 2
// of Mood Chat (docs/proposals/2026-07-19-mood-chat.md). Scored ONLY from each
// track's existing researched note/summary/themes in
// supabase/seed/tracks/speak-now.mjs — no invented facts, no lyrics. `oneLiner`
// and `useCase` are ORIGINAL prose. Axes 0..1; energy 0 (still)..1 (driving);
// valence 0 (sad)..1 (happy).

export default {
  eraSlug: 'speak-now',
  songs: [
    {
      slug: 'mine',
      moods: {
        heartbreak: 0.15,
        anger: 0.05,
        nostalgia: 0.3,
        joy: 0.7,
        calm: 0.35,
        defiance: 0.35,
        longing: 0.6,
        catharsis: 0.6,
      },
      energy: 0.65,
      valence: 0.8,
      useCase: ['scared to let love in', 'hoping against your own pattern', 'building a life with someone'],
      oneLiner: "A careless man's careful daughter imagining, verse by verse, what staying could look like.",
    },
    {
      slug: 'sparks-fly',
      moods: {
        heartbreak: 0.05,
        anger: 0.0,
        nostalgia: 0.25,
        joy: 0.8,
        calm: 0.2,
        defiance: 0.35,
        longing: 0.65,
        catharsis: 0.5,
      },
      energy: 0.75,
      valence: 0.85,
      useCase: ['a magnetic bad idea', 'electric first attraction', 'wanting the rain-soaked kiss'],
      oneLiner: 'Attraction as weather: a green-eyed bad idea and the kiss she wants anyway.',
    },
    {
      slug: 'back-to-december',
      moods: {
        heartbreak: 0.7,
        anger: 0.05,
        nostalgia: 0.7,
        joy: 0.05,
        calm: 0.45,
        defiance: 0.05,
        longing: 0.75,
        catharsis: 0.7,
      },
      energy: 0.4,
      valence: 0.25,
      useCase: ['owning that you hurt someone', 'an apology you owe', 'wishing you could go back'],
      oneLiner: 'Her first apology song: owning the December she gave back someone who deserved better.',
    },
    {
      slug: 'speak-now',
      moods: {
        heartbreak: 0.05,
        anger: 0.1,
        nostalgia: 0.15,
        joy: 0.8,
        calm: 0.2,
        defiance: 0.6,
        longing: 0.5,
        catharsis: 0.6,
      },
      energy: 0.65,
      valence: 0.85,
      useCase: ['saying it before its too late', 'a rom-com fantasy', 'crashing the wrong wedding'],
      oneLiner: 'A rom-com heist: crash the wedding and say it before the door closes forever.',
    },
    {
      slug: 'dear-john',
      moods: {
        heartbreak: 0.8,
        anger: 0.6,
        nostalgia: 0.35,
        joy: 0.02,
        calm: 0.3,
        defiance: 0.6,
        longing: 0.5,
        catharsis: 0.85,
      },
      energy: 0.45,
      valence: 0.15,
      useCase: ['leaving someone who played games', 'reclaiming your story', 'a slow blues burn'],
      oneLiner: 'A young woman reclaiming a manipulative older love: she should have known, but he did.',
    },
    {
      slug: 'mean',
      moods: {
        heartbreak: 0.1,
        anger: 0.55,
        nostalgia: 0.1,
        joy: 0.4,
        calm: 0.15,
        defiance: 0.9,
        longing: 0.2,
        catharsis: 0.75,
      },
      energy: 0.75,
      valence: 0.6,
      useCase: ['answering a bully', 'proving them wrong', 'resilience against cheap shots'],
      oneLiner: "A banjo clapback at a critic: someday she'll be big enough the cheap shots can't reach.",
    },
    {
      slug: 'the-story-of-us',
      moods: {
        heartbreak: 0.45,
        anger: 0.25,
        nostalgia: 0.3,
        joy: 0.15,
        calm: 0.15,
        defiance: 0.4,
        longing: 0.65,
        catharsis: 0.6,
      },
      energy: 0.75,
      valence: 0.35,
      useCase: ['performing indifference near an ex', 'pride versus longing', 'an unfinished story'],
      oneLiner: 'Two exes rows apart performing indifference, narrated by the one who hates the silence.',
    },
    {
      slug: 'never-grow-up',
      moods: {
        heartbreak: 0.3,
        anger: 0.0,
        nostalgia: 0.9,
        joy: 0.25,
        calm: 0.75,
        defiance: 0.05,
        longing: 0.65,
        catharsis: 0.65,
      },
      energy: 0.3,
      valence: 0.4,
      useCase: ['wishing time would slow down', 'homesick for childhood', 'first night on your own'],
      oneLiner: 'A lullaby to a child that turns out to be a lullaby to herself, alone in a new apartment.',
    },
    {
      slug: 'enchanted',
      moods: {
        heartbreak: 0.1,
        anger: 0.0,
        nostalgia: 0.4,
        joy: 0.75,
        calm: 0.35,
        defiance: 0.1,
        longing: 0.85,
        catharsis: 0.6,
      },
      energy: 0.6,
      valence: 0.8,
      useCase: ['a dazzling first meeting', 'replaying a night all over', 'hoping hes not taken'],
      oneLiner: "One wonderstruck first meeting replayed all night, hoping he isn't going home to someone else.",
    },
    {
      slug: 'better-than-revenge',
      moods: {
        heartbreak: 0.2,
        anger: 0.8,
        nostalgia: 0.2,
        joy: 0.3,
        calm: 0.05,
        defiance: 0.85,
        longing: 0.15,
        catharsis: 0.65,
      },
      energy: 0.85,
      valence: 0.4,
      useCase: ['a full-drama grudge', 'pop-punk jealousy', 'teenage revenge energy'],
      oneLiner: 'A full-drama-mode grudge song written at eighteen against the girl who stole him.',
    },
    {
      slug: 'innocent',
      moods: {
        heartbreak: 0.25,
        anger: 0.1,
        nostalgia: 0.45,
        joy: 0.2,
        calm: 0.6,
        defiance: 0.3,
        longing: 0.4,
        catharsis: 0.65,
      },
      energy: 0.4,
      valence: 0.45,
      useCase: ['extending grace to someone', 'forgiving in public', 'everyone can still grow'],
      oneLiner: 'A pointedly gracious hand offered to the man who humiliated her on live TV.',
    },
    {
      slug: 'haunted',
      moods: {
        heartbreak: 0.75,
        anger: 0.2,
        nostalgia: 0.2,
        joy: 0.02,
        calm: 0.1,
        defiance: 0.2,
        longing: 0.8,
        catharsis: 0.7,
      },
      energy: 0.75,
      valence: 0.15,
      useCase: ['feeling someone slip away', 'the panic of losing them', 'a gothic breakdown'],
      oneLiner: 'The orchestral panic of feeling someone slip away mid-sentence.',
    },
    {
      slug: 'last-kiss',
      moods: {
        heartbreak: 0.9,
        anger: 0.02,
        nostalgia: 0.8,
        joy: 0.02,
        calm: 0.5,
        defiance: 0.02,
        longing: 0.85,
        catharsis: 0.7,
      },
      energy: 0.3,
      valence: 0.1,
      useCase: ['a 1am breakup autopsy', 'hoarding the small details', 'the saddest slow ballad'],
      oneLiner: 'A 1 a.m. autopsy of a breakup, kept alive in remembered dates and doorway postures.',
    },
    {
      slug: 'long-live',
      moods: {
        heartbreak: 0.1,
        anger: 0.0,
        nostalgia: 0.75,
        joy: 0.75,
        calm: 0.35,
        defiance: 0.35,
        longing: 0.55,
        catharsis: 0.85,
      },
      energy: 0.7,
      valence: 0.8,
      useCase: ['a victory lap with your people', 'celebrating a shared run', 'graduation and goodbyes'],
      oneLiner: 'A toast to everyone who built the improbable run: remember how it felt to hold the crown.',
    },
    {
      slug: 'ours',
      moods: {
        heartbreak: 0.05,
        anger: 0.05,
        nostalgia: 0.2,
        joy: 0.75,
        calm: 0.55,
        defiance: 0.5,
        longing: 0.3,
        catharsis: 0.45,
      },
      energy: 0.45,
      valence: 0.85,
      useCase: ['a love others dont get', 'tuning out the gossip', 'quiet contentment together'],
      oneLiner: 'A shrug at everyone who disapproves, because the love belongs to exactly two people.',
    },
    {
      slug: 'if-this-was-a-movie',
      moods: {
        heartbreak: 0.6,
        anger: 0.05,
        nostalgia: 0.55,
        joy: 0.1,
        calm: 0.4,
        defiance: 0.1,
        longing: 0.85,
        catharsis: 0.55,
      },
      energy: 0.5,
      valence: 0.25,
      useCase: ['waiting for a reunion scene', 'wishing life had a third act', 'the ache of no comeback'],
      oneLiner: 'Knowing exactly how the movie ends—he comes back in the rain—and living the unscripted version.',
    },
    {
      slug: 'superman',
      moods: {
        heartbreak: 0.35,
        anger: 0.02,
        nostalgia: 0.35,
        joy: 0.35,
        calm: 0.4,
        defiance: 0.05,
        longing: 0.8,
        catharsis: 0.4,
      },
      energy: 0.5,
      valence: 0.45,
      useCase: ['loving someone always leaving', 'hero worship with a bruise', 'waiting for a return'],
      oneLiner: 'Hero worship with a bruise in it: he saves the world, she does the un-dazzling waiting.',
    },
    {
      slug: 'electric-touch',
      moods: {
        heartbreak: 0.15,
        anger: 0.0,
        nostalgia: 0.2,
        joy: 0.6,
        calm: 0.2,
        defiance: 0.35,
        longing: 0.65,
        catharsis: 0.55,
      },
      energy: 0.75,
      valence: 0.7,
      useCase: ['a first date that could go either way', 'hope over a bad track record', 'second-chance nerves'],
      oneLiner: 'Two people with bad track records meeting anyway: every ending says run, the spark says stay.',
    },
    {
      slug: 'when-emma-falls-in-love',
      moods: {
        heartbreak: 0.1,
        anger: 0.0,
        nostalgia: 0.4,
        joy: 0.55,
        calm: 0.65,
        defiance: 0.05,
        longing: 0.4,
        catharsis: 0.4,
      },
      energy: 0.35,
      valence: 0.7,
      useCase: ['admiring how a friend loves', 'a tender character study', 'wishing you loved like her'],
      oneLiner: 'An admiring portrait of a friend who loves carefully and completely.',
    },
    {
      slug: 'i-can-see-you',
      moods: {
        heartbreak: 0.05,
        anger: 0.0,
        nostalgia: 0.2,
        joy: 0.55,
        calm: 0.2,
        defiance: 0.3,
        longing: 0.8,
        catharsis: 0.5,
      },
      energy: 0.75,
      valence: 0.65,
      useCase: ['a crush kept behind the eyes', 'slow-burn tension', 'wanting what you cant say'],
      oneLiner: 'Desire kept strictly behind the eyes, a secret both people pretend not to notice.',
    },
    {
      slug: 'castles-crumbling',
      moods: {
        heartbreak: 0.4,
        anger: 0.15,
        nostalgia: 0.3,
        joy: 0.02,
        calm: 0.2,
        defiance: 0.15,
        longing: 0.5,
        catharsis: 0.7,
      },
      energy: 0.55,
      valence: 0.15,
      useCase: ['fearing a fall from grace', 'the terror of letting everyone down', 'cheers turning to jeers'],
      oneLiner: 'A ruler watching cheers turn to jeers, terrified of disappointing everyone who chanted her name.',
    },
    {
      slug: 'foolish-one',
      moods: {
        heartbreak: 0.5,
        anger: 0.05,
        nostalgia: 0.2,
        joy: 0.2,
        calm: 0.35,
        defiance: 0.15,
        longing: 0.85,
        catharsis: 0.5,
      },
      energy: 0.45,
      valence: 0.3,
      useCase: ['waiting for a text that wont come', 'catching your own delusion', 'reading into the crumbs'],
      oneLiner: 'Lecturing herself to stop reading into the crumbs, then planning the wedding anyway.',
    },
    {
      slug: 'timeless',
      moods: {
        heartbreak: 0.05,
        anger: 0.0,
        nostalgia: 0.75,
        joy: 0.6,
        calm: 0.65,
        defiance: 0.1,
        longing: 0.6,
        catharsis: 0.55,
      },
      energy: 0.4,
      valence: 0.8,
      useCase: ['believing love is fated', 'love across any century', 'old-photograph romance'],
      oneLiner: "Flipping through strangers' old photos and deciding she'd have found him in any century.",
    },
  ],
};
