export default {
  eraSlug: 'ttpd',
  songs: [
    {
      slug: 'fortnight',
      moods: {
        heartbreak: 0.6, anger: 0.1, nostalgia: 0.35, joy: 0.1,
        calm: 0.35, defiance: 0.05, longing: 0.6, catharsis: 0.45,
      },
      energy: 0.35,
      valence: 0.25,
      useCase: ['grieving a brief but ruinous fling', 'numbness after something intense ended', 'the ex you still picture next door'],
      oneLiner: 'A two-week affair that left permanent damage, sung in a medicated near-monotone.',
    },
    {
      slug: 'the-tortured-poets-department',
      moods: {
        heartbreak: 0.35, anger: 0.1, nostalgia: 0.15, joy: 0.35,
        calm: 0.3, defiance: 0.15, longing: 0.3, catharsis: 0.35,
      },
      energy: 0.3,
      valence: 0.45,
      useCase: ['laughing at your own poetic self-pity', 'an in-joke relationship nobody else gets', 'deflating your own tragic myth'],
      oneLiner: 'Two melodrama addicts cataloging their own tortured-artist routine, half in love with the bit.',
    },
    {
      slug: 'my-boy-only-breaks-his-favorite-toys',
      moods: {
        heartbreak: 0.55, anger: 0.15, nostalgia: 0.1, joy: 0.15,
        calm: 0.1, defiance: 0.1, longing: 0.35, catharsis: 0.45,
      },
      energy: 0.6,
      valence: 0.3,
      useCase: ['convincing yourself damage meant something', 'a cheerful beat hiding a sad excuse', 'realizing your cope was never true'],
      oneLiner: 'Rationalizing the wreckage as proof of love, in bright synth-pop that hides the wound in plain sight.',
    },
    {
      slug: 'down-bad',
      moods: {
        heartbreak: 0.6, anger: 0.1, nostalgia: 0.15, joy: 0.1,
        calm: 0.3, defiance: 0.05, longing: 0.65, catharsis: 0.4,
      },
      energy: 0.4,
      valence: 0.2,
      useCase: ['re-entry after someone abandoned the high', 'wanting to be taken back after being dropped', 'grieving a whirlwind that vanished'],
      oneLiner: 'A dazzling love-bomb disappears, leaving ordinary life feeling like the wrong planet.',
    },
    {
      slug: 'so-long-london',
      moods: {
        heartbreak: 0.75, anger: 0.15, nostalgia: 0.5, joy: 0.05,
        calm: 0.2, defiance: 0.25, longing: 0.4, catharsis: 0.7,
      },
      energy: 0.45,
      valence: 0.15,
      useCase: ['leaving a city that was really a relationship', 'exhausted grief after years of trying', 'a farewell too tired for anger'],
      oneLiner: 'A choral eulogy for a whole shared life, grief that quietly accelerates instead of exploding.',
    },
    {
      slug: 'but-daddy-i-love-him',
      moods: {
        heartbreak: 0.15, anger: 0.35, nostalgia: 0.05, joy: 0.5,
        calm: 0.05, defiance: 0.75, longing: 0.15, catharsis: 0.55,
      },
      energy: 0.7,
      valence: 0.55,
      useCase: ['choosing your own mistakes on purpose', 'telling the judgmental chorus to back off', 'defying disapproval with a grin'],
      oneLiner: 'A gleeful, country-sized rebellion against everyone who thinks they know better.',
    },
    {
      slug: 'fresh-out-the-slammer',
      moods: {
        heartbreak: 0.1, anger: 0.05, nostalgia: 0.25, joy: 0.55,
        calm: 0.15, defiance: 0.3, longing: 0.5, catharsis: 0.4,
      },
      energy: 0.5,
      valence: 0.6,
      useCase: ['running back to an old flame on release', 'relief after finally getting free', 'a rebound that feels like coming home'],
      oneLiner: 'The first call after a confining relationship ends goes straight to the one who waited.',
    },
    {
      slug: 'florida',
      moods: {
        heartbreak: 0.25, anger: 0.15, nostalgia: 0.05, joy: 0.35,
        calm: 0.05, defiance: 0.55, longing: 0.2, catharsis: 0.6,
      },
      energy: 0.75,
      valence: 0.45,
      useCase: ['fantasizing about disappearing and starting over', 'dark comedy about running away', 'reinvention as an escape hatch'],
      oneLiner: 'Florida as a witness-protection fantasy: reinvention with gothic humor and three exclamation points.',
    },
    {
      slug: 'guilty-as-sin',
      moods: {
        heartbreak: 0.3, anger: 0.05, nostalgia: 0.1, joy: 0.2,
        calm: 0.25, defiance: 0.15, longing: 0.6, catharsis: 0.35,
      },
      energy: 0.35,
      valence: 0.35,
      useCase: ['wanting someone you should not want', 'desire dressed up as guilt', 'emotional betrayal that never leaves your head'],
      oneLiner: 'Fantasizing inside a fading relationship and putting the fantasy itself on trial.',
    },
    {
      slug: 'whos-afraid-of-little-old-me',
      moods: {
        heartbreak: 0.3, anger: 0.75, nostalgia: 0.1, joy: 0.05,
        calm: 0.05, defiance: 0.7, longing: 0.15, catharsis: 0.7,
      },
      energy: 0.65,
      valence: 0.2,
      useCase: ['channeling fame-fueled rage into performance', 'becoming the villain they already named', 'reputation weaponized right back'],
      oneLiner: 'An asylum aria for a woman raised by the circus, now performing the monster they accused her of being.',
    },
    {
      slug: 'i-can-fix-him-no-really-i-can',
      moods: {
        heartbreak: 0.25, anger: 0.1, nostalgia: 0.05, joy: 0.35,
        calm: 0.1, defiance: 0.4, longing: 0.3, catharsis: 0.35,
      },
      energy: 0.5,
      valence: 0.4,
      useCase: ['insisting you can save someone unsalvageable', 'a self-aware bad-decision joke', 'the moment denial finally cracks'],
      oneLiner: 'A saloon-door twang pastiche about the fixer-upper delusion, undone by its own last line.',
    },
    {
      slug: 'loml',
      moods: {
        heartbreak: 0.85, anger: 0.15, nostalgia: 0.4, joy: 0.05,
        calm: 0.35, defiance: 0.1, longing: 0.55, catharsis: 0.7,
      },
      energy: 0.2,
      valence: 0.08,
      useCase: ['the biggest loss you have ever survived', 'a devastation too large for anger', 'grieving a life you built around someone'],
      oneLiner: 'A piano dirge that quietly redefines its own title, from love of my life to loss of my life.',
    },
    {
      slug: 'i-can-do-it-with-a-broken-heart',
      moods: {
        heartbreak: 0.5, anger: 0.1, nostalgia: 0.05, joy: 0.25,
        calm: 0.05, defiance: 0.45, longing: 0.25, catharsis: 0.65,
      },
      energy: 0.85,
      valence: 0.35,
      useCase: ['functioning through depression in public', 'the show must go on, literally', 'professionalism as the only armor left'],
      oneLiner: 'Performing the biggest show on earth nightly while privately falling apart backstage.',
    },
    {
      slug: 'the-smallest-man-who-ever-lived',
      moods: {
        heartbreak: 0.6, anger: 0.85, nostalgia: 0.1, joy: 0.02,
        calm: 0.05, defiance: 0.5, longing: 0.2, catharsis: 0.8,
      },
      energy: 0.55,
      valence: 0.1,
      useCase: ['pure contempt for someone who vanished', 'demanding answers that never came', 'scorched-earth fury after abandonment'],
      oneLiner: 'The album’s most contemptuous bridge, demanding an autopsy on a love that vanished unexplained.',
    },
    {
      slug: 'the-alchemy',
      moods: {
        heartbreak: 0.05, anger: 0.02, nostalgia: 0.1, joy: 0.85,
        calm: 0.15, defiance: 0.15, longing: 0.2, catharsis: 0.5,
      },
      energy: 0.65,
      valence: 0.85,
      useCase: ['new love that actually feels like winning', 'rare joy breaking through a grief album', 'falling for someone without the dread'],
      oneLiner: 'The one unguarded, giddy chemical reaction on a record otherwise built from wreckage.',
    },
    {
      slug: 'clara-bow',
      moods: {
        heartbreak: 0.25, anger: 0.15, nostalgia: 0.45, joy: 0.15,
        calm: 0.35, defiance: 0.25, longing: 0.3, catharsis: 0.45,
      },
      energy: 0.4,
      valence: 0.35,
      useCase: ['watching the industry get ready to replace you', 'fame as a role handed down, not earned', 'unease about being interchangeable'],
      oneLiner: 'An it-girl assembly line running from Clara Bow to Stevie Nicks to whoever gets told she looks like you next.',
    },
    {
      slug: 'the-black-dog',
      moods: {
        heartbreak: 0.6, anger: 0.3, nostalgia: 0.25, joy: 0.05,
        calm: 0.15, defiance: 0.1, longing: 0.6, catharsis: 0.4,
      },
      energy: 0.45,
      valence: 0.2,
      useCase: ['obsessively tracking someone who left', 'digital-age grief over a shared place lost', 'jealousy that will not log off'],
      oneLiner: 'Watching an ex’s location on a shared app, grieving a life that used to include you in real time.',
    },
    {
      slug: 'imgonnagetyouback',
      moods: {
        heartbreak: 0.2, anger: 0.3, nostalgia: 0.15, joy: 0.35,
        calm: 0.05, defiance: 0.6, longing: 0.35, catharsis: 0.45,
      },
      energy: 0.75,
      valence: 0.45,
      useCase: ['plotting either romance or revenge, undecided', 'playful menace toward an ex', 'unfinished business with real edge'],
      oneLiner: 'A gleeful threat that refuses to decide whether it means winning him back or getting revenge.',
    },
    {
      slug: 'the-albatross',
      moods: {
        heartbreak: 0.2, anger: 0.1, nostalgia: 0.1, joy: 0.15,
        calm: 0.3, defiance: 0.35, longing: 0.4, catharsis: 0.4,
      },
      energy: 0.4,
      valence: 0.35,
      useCase: ['owning a reputation as a bad omen', 'being the warning that turns into a gift', 'literary self-mythology as armor'],
      oneLiner: 'A cursed omen self-applied, arriving anyway as the very rescue the wise men warned him about.',
    },
    {
      slug: 'chloe-or-sam-or-sophia-or-marcus',
      moods: {
        heartbreak: 0.45, anger: 0.2, nostalgia: 0.2, joy: 0.05,
        calm: 0.2, defiance: 0.15, longing: 0.5, catharsis: 0.35,
      },
      energy: 0.4,
      valence: 0.25,
      useCase: ['feeling interchangeable after a breakup', 'lingering long after being replaced', 'the sting of easy replaceability'],
      oneLiner: 'A replacement so easy the new partners barely need distinct names, and she lingers anyway.',
    },
    {
      slug: 'how-did-it-end',
      moods: {
        heartbreak: 0.55, anger: 0.2, nostalgia: 0.3, joy: 0.05,
        calm: 0.35, defiance: 0.15, longing: 0.3, catharsis: 0.45,
      },
      energy: 0.35,
      valence: 0.2,
      useCase: ['explaining a breakup to everyone but yourself', 'public appetite for a private ending', 'an ending with no satisfying answer'],
      oneLiner: 'A breakup autopsy performed for an audience of friends, fans and press leaning in for the cause of death.',
    },
    {
      slug: 'so-high-school',
      moods: {
        heartbreak: 0.05, anger: 0.02, nostalgia: 0.4, joy: 0.8,
        calm: 0.15, defiance: 0.1, longing: 0.2, catharsis: 0.35,
      },
      energy: 0.6,
      valence: 0.85,
      useCase: ['feeling like a teenager with a new crush', 'giddy new love with zero cynicism', 'a simple, uncomplicated infatuation'],
      oneLiner: 'A 90s-rock crush that makes a grown woman feel sixteen again, giddy over video games and inside jokes.',
    },
    {
      slug: 'i-hate-it-here',
      moods: {
        heartbreak: 0.25, anger: 0.15, nostalgia: 0.45, joy: 0.15,
        calm: 0.4, defiance: 0.2, longing: 0.45, catharsis: 0.3,
      },
      energy: 0.3,
      valence: 0.3,
      useCase: ['retreating into an imagined interior world', 'wishing you were born in another era', 'coping by mentally checking out'],
      oneLiner: 'An escapist’s manifesto: secret gardens and imaginary decades built to survive the real one.',
    },
    {
      slug: 'thank-you-aimee',
      moods: {
        heartbreak: 0.2, anger: 0.35, nostalgia: 0.3, joy: 0.35,
        calm: 0.2, defiance: 0.65, longing: 0.1, catharsis: 0.7,
      },
      energy: 0.5,
      valence: 0.55,
      useCase: ['outliving a feud and finding it funny', 'turning an old cruelty into fuel', 'triumph dressed as a thank-you note'],
      oneLiner: 'Ironic gratitude toward an old bully, thanked for accidentally building something stronger.',
    },
    {
      slug: 'i-look-in-peoples-windows',
      moods: {
        heartbreak: 0.35, anger: 0.05, nostalgia: 0.3, joy: 0.1,
        calm: 0.35, defiance: 0.05, longing: 0.65, catharsis: 0.3,
      },
      energy: 0.25,
      valence: 0.25,
      useCase: ['searching for someone who left no trace', 'quiet voyeuristic grief', 'a fleeting ache that never resolves'],
      oneLiner: 'A ninety-second miniature about scanning strangers’ windows for any glimpse of someone gone.',
    },
    {
      slug: 'the-prophecy',
      moods: {
        heartbreak: 0.55, anger: 0.1, nostalgia: 0.15, joy: 0.05,
        calm: 0.15, defiance: 0.1, longing: 0.7, catharsis: 0.55,
      },
      energy: 0.35,
      valence: 0.15,
      useCase: ['begging the universe for a different pattern', 'fear of being permanently unlovable', 'praying your luck finally turns'],
      oneLiner: 'A raw plea bargaining with fate itself, to change a pattern from always-left to finally-kept.',
    },
    {
      slug: 'cassandra',
      moods: {
        heartbreak: 0.3, anger: 0.5, nostalgia: 0.15, joy: 0.05,
        calm: 0.15, defiance: 0.55, longing: 0.25, catharsis: 0.55,
      },
      energy: 0.45,
      valence: 0.2,
      useCase: ['being right and punished for it anyway', 'watching a mob turn against you', 'vindication that arrives too late'],
      oneLiner: 'A cursed prophetess who told the truth and was never believed, until the mob turned late and useless.',
    },
    {
      slug: 'peter',
      moods: {
        heartbreak: 0.45, anger: 0.15, nostalgia: 0.4, joy: 0.1,
        calm: 0.3, defiance: 0.3, longing: 0.45, catharsis: 0.45,
      },
      energy: 0.3,
      valence: 0.25,
      useCase: ['giving up on someone who never changes', 'closing the door on wasted waiting', 'a gentle goodbye to an old fantasy'],
      oneLiner: 'A Wendy who finally closes the window on the boy who kept promising to grow up.',
    },
    {
      slug: 'the-bolter',
      moods: {
        heartbreak: 0.35, anger: 0.1, nostalgia: 0.15, joy: 0.2,
        calm: 0.2, defiance: 0.55, longing: 0.3, catharsis: 0.4,
      },
      energy: 0.45,
      valence: 0.3,
      useCase: ['leaving before you can be discarded', 'owning a reputation for running first', 'independence that is really self-protection'],
      oneLiner: 'A character study of a woman who runs before she can be treated as disposable, wearing her own flight response like a badge.',
    },
    {
      slug: 'robin',
      moods: {
        heartbreak: 0.1, anger: 0.02, nostalgia: 0.3, joy: 0.45,
        calm: 0.7, defiance: 0.1, longing: 0.2, catharsis: 0.25,
      },
      energy: 0.15,
      valence: 0.6,
      useCase: ['protecting someone else’s innocence', 'a tender promise to shield a child', 'quiet devotion with nothing asked back'],
      oneLiner: 'A lullaby promising to guard a child’s unbothered world for as long as it can last.',
    },
    {
      slug: 'the-manuscript',
      moods: {
        heartbreak: 0.35, anger: 0.05, nostalgia: 0.55, joy: 0.2,
        calm: 0.45, defiance: 0.15, longing: 0.25, catharsis: 0.6,
      },
      energy: 0.25,
      valence: 0.4,
      useCase: ['finding peace with pain you once lived inside', 'turning old wreckage into finished work', 'the epilogue after healing'],
      oneLiner: 'An old heartbreak reread years later, then formally handed over to the readers as finished art.',
    },
  ],
};
